### ISSUE TITLE
Error with opam init

### ISSUE THREAD

**Issue by lpw25** [ocaml/opam#1000]
```
$ opam init --root=opam
default    Downloading https://opam.ocaml.org/urls.txt
[ERROR] Too many downloaded files.
'opam init --root=opam' failed.
# opam-version    1.1.0
# os              linux
Too many downloaded files.
```

Note that there was no directory called `opam` when I ran this. If I add such a directory then it works fine.

**Comment by herbelin** [comment]
With opam 1.2.0, I still have the error:
$ opam init --root my-opam
Checking for available remotes: rsync and local, git, mercurial.
[NOTE] darcs not found, you won't be able to use darcs repositories unless you install it.
[WARNING] Recommended external solver aspcud not found.
[default] Downloading https://opam.ocaml.org/urls.txt
[ERROR] Too many downloaded files.
# opam-version    1.2.0
# os              linux
Too many downloaded files.

**Comment by johanatan** [comment]
I'm seeing this issue as well. Any fix?
