### ISSUE TITLE
OPAM in a box

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#1035]
This is a tracker thread to pull together the various scripts and tools required to generate an "OPAM in a box" suitable for teaching purposes.  It should result in:

- [x] A base OCaml installation of 4.01.0 *(available via Ubuntu PPA in avsm/ppa)*
- [x] an OPAM installation with a user-configured set of packages all pre-installed, including any external library dependencies (e.g. libpcre). *(see https://github.com/AltGr/docker-opam)*
- [x] An `.ocamlinit` file preconfigured to require all the libraries.
- [x] The `utop` toplevel.
- [x] The `merlin` tool configured to work with Emacs and Vim.
- [x] An `opam-doc`-generated set of cross-referenced HTML docs for all the installed packages, served via a localhost webserver.
- [ ] A local HTTP remote of all the archives, so that it can be used without requiring external net access. *(OPAM 1.1.1dev has `opam-admin make --resolve <pkgs>` to generate this)*
- [ ] an iPython/OCaml console running (ocaml/opam-repository#1690)

For a first milestone, we're going to pull this together using Ubuntu and shell scripting, and wrap it for release using Docker containers (see http://anil.recoil.org/2013/11/15/docker-and-opam.html for an overview of this).  When this works satisfactorily, we can distribute the Ubuntu+Docker binaries in a VM for those folk using Windows as a second step.

This thread arose from a discussion with various profs and @yminsky, and a followup meeting with @AltGr and @samoht.  We'll use this issue to track progress of the various steps above.

**Comment by AltGr** [comment]
Closing this issue as it is vastly out of date, and although the support for this feature is not perfect yet, most of it is there, and the remaining bits already have active issues for them.
