### ISSUE TITLE
Install for all compilers

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam#1058]
It would be nice to have an option to perform an install for all installed compilers at the same time.  For example

```
opam install --all merlin
```

**Comment by dra27** [comment]
Related to #2410

**Comment by dra27** [comment]
This should be superseded by features in opam 2.2 for layered switches. Especially since the introduction of local switches in opam 2.0, it's not clear that you'd ever want "install this to every switch known to opam" anymore.
