### ISSUE TITLE
Don't repackage upstream tarballs

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam#1090]
Ref: discussion of #807

**Comment by avsm** [comment]
Apologies for reopening this, but I'm not sure this is fixed yet. `opam admin make` in current trunk still creates repackaged +opam.tar.gz files.  Is there an equivalent `opam admin` command to construct the by-hash mirrors, or does that need to be written via `opam-lib`? (I dont mind doing it, just checking first)

**Comment by avsm** [comment]
This was due to trying with an older checkout of opam2. alpha6+ `opam admin make` now puts files in `cache` and does not repackage them, and also downloads in parallel.  Extremely cool work, thank you @altgr!
