### ISSUE TITLE
zarith, CFLAGS, LDFLAGS on OS X + MacPorts

### ISSUE THREAD

**Issue by mattam82** [ocaml/opam#1091]
Hi, to be able to compile zarith.1.2 on my setup I had to add CFLAGS and LDFLAGS that point to /opt/local/include and lib (for macport's gmp), is there a way to set them permanently in opam's config or do I have to do that in my .profile?

**Comment by ctchou** [comment]
The above fix no longer works.  It does not seem possible to change LDFLAGS and CFLAGS.

**Comment by c-garcia** [comment]
Hi

After checking that CFLAGS and LDFLAGS settings do not work on MacOS (El Capitan) + macports, I have just defined C_INCLUDE_PATH and LIBRARY_PATH (as suggested by @dbrumley) and I have been able to make it work. To maintain the consistency between invocations, I have added them to my shell profile.

HTH

**Comment by tiffanyb** [comment]
Similar issue while `opam install zarith`:

```
#=== ERROR while compiling zarith.1.7 =========================================#
# context     2.0.4 | macos/x86_64 | ocaml-base-compiler.4.07.1 | https://opam.ocaml.org#005edd16
# path        ~/.opam/default/.opam-switch/build/zarith.1.7
# command     ~/.opam/opam-init/hooks/sandbox.sh build sh -exc LDFLAGS="$LDFLAGS -L/opt/local/lib -L/usr/local/lib" CFLAGS="$CFLAGS -I/opt/local/include -I/usr/local/include" ./configure
# exit-code   2
# env-file    ~/.opam/log/zarith-60317-ffb3fd.env
# output-file ~/.opam/log/zarith-60317-ffb3fd.out
### output ###
# [...]
# + LDFLAGS=' -L/opt/local/lib -L/usr/local/lib'
# + CFLAGS=' -I/opt/local/include -I/usr/local/include'
# + ./configure
# binary ocaml: found in /Users/tiffanyb/.opam/default/bin
# binary ocamlc: found in /Users/tiffanyb/.opam/default/bin
# binary ocamldep: found in /Users/tiffanyb/.opam/default/bin
# binary ocamlmklib: found in /Users/tiffanyb/.opam/default/bin
# binary ocamldoc: found in /Users/tiffanyb/.opam/default/bin
# binary ar: found in /opt/local/bin
# binary perl: found in /opt/local/bin
# binary /opt/local/bin/gcc-mp-8: not found
# required program /opt/local/bin/gcc-mp-8 not found
``` 

yet `/opt/local/bin/gcc-mp-8` does exist in my computer.

The problem is resolved by specifying `CC`: `CC=gcc-mp-8 opam install zarith`
