### ISSUE TITLE
deal with port blocking

### ISSUE THREAD

**Issue by mor1** [ocaml/opam#1155]
port blocking (not uncommon for eg., the git port, TCP/9418) seems to prevent some packages being installed which
can stall a sequence of dependency installations without any indication to the user what's going on 

(suggestion: i wonder if this would be avoided by replacing all `git://github.com` urls in opam-repository with `-k git https://github.com` urls?);

**Comment by AltGr** [comment]
These probably need to be fixed:
```
% git grep 'git://' **/url
packages/camlp4/camlp4.4.03.0/url:git: "git://github.com/ocaml/camlp4#trunk"
packages/portia/portia.0.1/url:git: "git://github.com/rixed/portia"
packages/ppx_tools/ppx_tools.0.1/url:git: "git://github.com/alainfrisch/ppx_tools.git"
packages/quickcheck/quickcheck.0.0.3/url:git: "git://github.com/avsm/ocaml-quickcheck.git"
packages/sedlex/sedlex.1.99.1/url:git: "git://github.com/alainfrisch/sedlex.git"
```

**Comment by AltGr** [comment]
Closing as this is an issue with the repository, and package releases shouldn't be downloaded from git anyway.
