### ISSUE TITLE
Is there a command to clear the caches used by OPAM?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#1269]
When I troubleshoot some package installation, I'd like a way to be sure
I start from a clean ~/.opam directory in terms of cache files.

**Comment by KyleLH** [comment]
+1, this would be awesome. In the meantime, any way to do it manually?

**Comment by AltGr** [comment]
There is now `opam clean`

**Comment by UnixJunkie** [comment]
cool, thanks!
