### ISSUE TITLE
opam switch: Do not recompile to install an alias

### ISSUE THREAD

**Issue by nbraud** [ocaml/opam#1314]
Currently, `opam switch install foo -A installed_switch` compiles `installed_switch` anew.

It should be possible (at least on switches that correspond to a release, and not a git branch) to reuse the compiler's binaries. Using hardlinks (though only available on Linux), shouldn't even be necessary to take special care during `opam switch remove`.

This would greatly accelerate the workflow (recommanded [in the documentation](http://opam.ocaml.org/doc/Advanced_Usage.html#h3-Abilitytomakeacopyofagivencompilerunderanalias) where one creates a switch so as to develop a specific project in a clean environment.

**Comment by little-arhat** [comment]
Really wish opam could do that!

**Comment by AltGr** [comment]
Since compilers are packages, this is now a subset of #629
