### ISSUE TITLE
Check for depexts earlier

### ISSUE THREAD

**Issue by jpdeplaix** [ocaml/opam#1379]
I went to an opam issue when I tried to install a package that requires `conf-gtksourceview.2`.
It tried to install it and it failed after having removed all the packages already installed.

The error message is:

```
=-=-= conf-gtksourceview.2 troobleshooting =-=-=
This package requires gtksourceview 2.0 development packages installed on your system.
```

So I guess opam checks a bit late in the installation process for the depexts. If it's possible, I think it should be done before performing installation.

EDIT: Tested with opam 1.1.1

**Comment by AltGr** [comment]
Merging into #1519
