### ISSUE TITLE
Handle Git submodules

### ISSUE THREAD

**Issue by NicolasT** [ocaml/opam#1422]
We have some sources for which we provide Opam package descriptions in our `devel` repository, which use a `git` tree as `url`.
Whilst this works just fine, a recent change causes trouble: instead of containing some third-party sources in the repository as a tarball, we switched to using a *git submodule*. Using a submodule requires some extra care running `git submodule update --init` after cloning the repository, or running `git clone` with the `--recursive` flag.
Since Opam doesn't handle submodules, initially the build of our package failed (since files were missing). I added `git submodule update --init` to the build steps (https://github.com/Incubaid/opam-repository-devel/pull/6), which now works, but sub-optimally: I didn't dig into this yet, but it looks like the repository which is checked out in `packages.dev/camltc` is copied into a `build` folder, in which the actual building is done.
Since the submodule content isn't in the `packages.dev/camltc` folder, this results in the submodule to be re-cloned for every build, which is rather undesired.

I think the Opam Git support should initialize submodules when cloning a repository to `packages.dev`, and update submodules after every update/reset action, so the submodule contents are copied into the `build` folder as expected, and no `git` commands are required in the Opam package build script.

**Comment by gasche** [comment]
On the coq-club mailing-list, topic "8.5 and MathClasses" (I can't find archives for this post, sorry), @spitters comments that they do rely on submodules in the Coq [math-classes](https://github.com/math-classes/math-classes) library, and that they found OPAM non-support to be problematic:

> About the change in math-classes. It used to be a git submodule of corn.  
> In order to move to use Coq's new contrib system we need to use opam.  
> Opam does not play well with git submodules.  
> I am hoping for a better integration of opam and git at some point, but this is the source of some recent changes.  
> I'll improve the documentation once I find the time for that.

@spitters made [a comment](https://github.com/ocaml/opam/issues/1847#issuecomment-61614907) in #1847 mentioning submodules, but I wasn't sure opam upstream was aware of this additional use-case.

**Comment by spitters** [comment]
Thanks for adding this discussion here.

The issue with math-classes has been discussed at length on Coq-dev.
Basically, I am told that git submodules are broken and we should move away
from them.
That may be true. However, for active development git seems to be more
suited than opam.
I can try to dig up the coqdev discussions if needed. I currently cannot
find the archives online.



The comment #1847 was related to work on:
https://github.com/HoTT/HoTT/

This library used to depend on a modified version of Coq trunk which we
provided as a git submodule.
Currently, we can work with Coq 8.5beta, so we can avoid the submodule.
I also provide experimental install instructions for HoTT on opam here:
https://github.com/HoTT/HoTT/issues/694

This will become an issue again when we will need to depend on an unstable
version of Coq again.

Bas

**Comment by dbuenzli** [comment]
Le jeudi, 7 mai 2015 à 14:31, Bas Spitters a écrit :
> Basically, I am told that git submodules are broken and we should move away
> from them.

I have to say that the rare times I had to use them it seemed it was introducing more problems than it was solving (but maybe that was because I was misunderstanding them).

**Comment by AltGr** [comment]
I also could never find a proper use of submodules where they ended up being convenient, despite my considerable experience with git. But that's not enough to conclude they're useless or broken :)

The interface isn't quite lean though, and I am not sure how to handle them correctly -- I would like to do the submodules fetch during the `fetch` call (we first fetch, then check if there is a diff with the given ref, then reset to it) -- but you can't specify a given version of the `.gitmodules` to `git submodule init`.

We could probably just call `git submodule update --init --recursive` in our `reset` function though, as we don't depend on the network accesses being only in the fetch call. Anyone is welcome to experiment, the related code is at https://github.com/ocaml/opam/blob/1.3/src/repository/opamGit.ml#L104

**Comment by spitters** [comment]
Perhaps a bit more on the math-classes use case. Slightly simplified.
We have a general library (A=math-classes) and a specific one (B=corn).
Before using opam, we'd be editing files in both repos and have git take care of putting things in the right place. Then at the time of a new coq-release we would ship a tar-ball to the coq-devs to be put in the contribs.

Coq is moving to opam for the contribs and we'd like to take advantage of this.
However, I do not fully appreciate yet how to integrate the smooth use of the two libraries on git/github with the opam use case. Currently, we've temporarily given up on git submodules. However, this means that development versions of the library, which are not in opam, will be harder to install for others.

Suggestions are appreciated. @clarus is the main coq opam developer at the moment and may have more insights into this.

**Comment by AltGr** [comment]
Not sure yet how well that would fit you, but OPAM has its own handling of development-version libraries, through pinning (to a directory, git repo, possibly on a given ref). There is no easy way to specify that as a dependency though, although there is an [ongoing discussion](http://lists.ocaml.org/pipermail/platform/2015-May/000562.html) on this specific need.

**Comment by spitters** [comment]
Yes, I am aware of the pinning option.

However, we would usually be developing on both libraries at the same time.
Git handles this nicely, but it seems that this is harder to track using
opam.

**Comment by AltGr** [comment]
opam remotes based on git will now automatically fetch submodules too, so this has been implemented. Thanks for the feedback!

**Comment by avsm** [comment]
@Altgr does this impose a higher minimum version on the Git installation?  I'm struggling to get OPAM 1.2.2 to work on CentOS 6 for example (see facebook/Reason#383), so a check for the Git version before erroring out would be handy in OPAM2

**Comment by AltGr** [comment]
We use `git submodule update --init --recursive`, whenever a `.gitmodules` file is present. So for repositories not having that file, nothing should be changed (and repositories having it probably wouldn't have worked anyway).
As for checking the `git` version, this could easily be done e.g. on `opam init`, but we need to know what the lower requirement is (and I couldn't easily find in git's doc what version `git submodule` was added in)
