### ISSUE TITLE
Support for pluggable hooks

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#1431]
Would be nice to have a way for a package to install hooks, which will be then triggered by OPAM on specific events (prepare, build, install).

An idea would be to add an `opam hook` sub-commands with the following behaviour:
```
$ opam hook list
[ list the hooks enabled in the current switch ]

$ opam hook add install script.sh
[ add script.sh as an install hook for the current switch. This will be run every-time a new package is installed ]

$ opam hook remove install script.sh
[ remove script.sh from the list of install hooks ]

$ opam hook run install
[ run all the install script hooks for all the already installed packages ]
```

Remark: it is expected than the script hooks call back `opam config var <value>` to get some information about the default paths. In that case, it is expected than OPAM does not dead-lock. Not totally sure about other commands (I guess `opam list` should be fine as well).

**Comment by AltGr** [comment]
There are now hooks (`pre`, `post` and `wrapper`) for each of `build`, `install` and `remove` ; these can be configured for the whole opam root (`~/.opam/config`) as well as for a single switch (`~/.opam/<switch>/.opam-switch/switch-config`), and even in init-config files, to be registered at `opam init` (`~/.opamrc` or `/etc/opamrc`).

Additionally, variables in the supplied hook commands are expanded in the context of the package command, making all opam information available to the hook through `argv` in a flexible way.

Adding or removing the hooks is still manual at the moment, which is good while we test them, check use-cases and mostly use them in CI systems ; it won't in any case be done by packages. We can wait until the use-cases arise to provide a specific UI for this (and maybe implement it through a plugin, as suggested in the first post).

Regarding opam-doc, `opam show <pkg> -f installed-files` and `opam search --owns-file <file>` may help.

I am closing this, as some version of it is now provided in opam, but am still open to remarks!
