### ISSUE TITLE
Automatically check depexts field

### ISSUE THREAD

**Issue by whitequark** [ocaml/opam#1519]
It would be great if opam would automatically check the installed packages against dpkg database / offer to invoke apt-get on debian/ubuntu.

**Comment by AltGr** [comment]
Just an update: the [`opam-depext`](https://github.com/ocaml/opam-depext) plugin now works fairly well and is still being improved for various OSes. It gets installed automatically on `opam depext <pkg>` with latest opam, though, and on errors on packages with depexts, opam advertises it.

So this got much, much better. It's still a manual process, though, with nothing built into opam; changes in the underlying system are not detected either (but you can just re-run `opam depext` without argument).

**Comment by rjbou** [comment]
Addressed in #3975. Thanks all!
