### ISSUE TITLE
Do not reclone git repositories for dev packages

### ISSUE THREAD

**Issue by jpdeplaix** [ocaml/opam#1530]
With a devel package (with a git url), if you install it and then reinstall it just after (for instance if the first attempt failed), the git repository of the package will be cloned twice.

For example:
```
$ opam install llvm.9999
…
Fetching https://github.com/llvm-mirror/llvm.git (~200MB)
…
Failling

$ opam install llvm.9999
…
Fetching …
^Z
$ ls ~/.opam/package.dev/llvm.9999
```
The directory is empty and the git repository will be cloned twice.

**Comment by AltGr** [comment]
This appears to be fixed; thanks for reporting!
