### ISSUE TITLE
opam *.install files should provide a way to install executables to lib/

### ISSUE THREAD

**Issue by whitequark** [ocaml/opam#1532]
See https://github.com/dbuenzli/topkg/issues/7 for details.

**Comment by whitequark** [comment]
Can we get this in 1.2.1? Should be a trivial fix.

**Comment by dbuenzli** [comment]
@whitequark what do you suggest ? That the `.install` procedure should preserve permissions. Or to add a new `lib_exec:` field ?

**Comment by whitequark** [comment]
I think adding a `libexec:` field would be in line to `bin:` forcing the executable bit on and `doc:` and the rest forcing it off.

**Comment by dbuenzli** [comment]
I agree, adding `libexec:` seems cleaner. Maybe the [doc](http://opam.ocaml.org/doc/manual/dev-manual.html#sec25) should mention when executable bits are set. But why executable bit on `doc:` ?

**Comment by whitequark** [comment]
I mean, in my previous comment, that currently `bin:` forces executable bit on and all other fields, for example `doc:`, force it off. (As far as I understand the mechanism.) I don't suggest setting the executable bit on documentation, of course.

**Comment by AltGr** [comment]
ok, libexec sounds like a good idea, It may squeeze into 1.2.1

**Comment by AltGr** [comment]
Libexec field implemented in #1982
