### ISSUE TITLE
Local switches

### ISSUE THREAD

**Issue by yallop** [ocaml/opam#1595]
It'd be useful for `opam switch` to support local switches (and other targets, such as URLs), analogous to local pins for packages.  In other words, I'd like to be able to write

``` bash
$ opam switch ~/src/ocaml
```

or

``` bash
$ opam switch git@github.com:ocaml/ocaml.git#constructors_with_record3
```

and have OPAM fetch the compiler description directly from the specified location.

**Comment by samoht** [comment]
@AltGr can we close this issue now? Are the local switches in master already?

**Comment by AltGr** [comment]
@samoht: hm, this issue originally means a completely different thing from what has been called "local switches" in more recent discussions, it seems to me. It relates to being able to have a compiler based on a local directory, which, if not as straight-forward as in the proposal (which would have put a _lot_ of overload on the `opam switch` command), can be done using `opam pin` and compiler-packages,  as easily as:
```bash
opam switch foo --empty
opam pin add ocaml-variants git@github.com:ocaml/ocaml.git#constructors_with_record3
opam switch set-base ocaml-variants # Optionally
```
As such, I think this could be closed, as doing a `pin-and-select-as-compiler-and-switch` command would be too cumbersome in the CLI (and there is already the possibility to use an import-file to do that in one step)

What the recent discussions have been about was the ability to hold the switch prefix and metadata in a custom directory, outside of `~/.opam`; something like:
```bash
opam switch
opam switch create --prefix ./foo 4.03.0
# Or even, detecting that ./foo is a path instead of a name:
opam switch create ./foo 4.03.0
```
This is not available yet but will be added shortly; I don't expect any technical difficulty, but want to get a good story first, regarding the CLI we provide.
Indeed, this is a good start, but not so useful in itself; the feature wish generally includes more than that, in particular ability for opam to detect and use a "switch prefix" stored in a `.opamswitch` directory in a parent of the PWD, automatically (unless OPAMSWITCH is set ? That should be a warning).

We may not have to link this with the `opam package` features, that would help work from the source directory of a package (but without pinning it permanently), although the two are generally presented together for NPM-like workflows. But maybe some sugar bridging the gap will be helpful once we get both.
