### ISSUE TITLE
List the available filters

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#1604]
I didn't saw any list of the available filters in the documentation, did I miss it ?

**Comment by dra27** [comment]
@Drup - how well does the present state of https://github.com/ocaml/opam/blob/master/doc/pages/Manual.md address this for you?

**Comment by Drup** [comment]
@dra27 It's not really addressed, as far as I can tell. The section on filter doesn't tell you at all which filter variables can be used, or where to find that information.

**Comment by dra27** [comment]
@Drup - the section immediately above?

**Comment by Drup** [comment]
hum, indeed, I did Ctrl-f "filter" and didn't look up. Maybe add a small reference ?

**Comment by AltGr** [comment]
Note that you can browse the up-to-date version online at https://opam.ocaml.org/doc/2.0/Manual.html
