### ISSUE TITLE
`opam pin edit <pkg>` could be used to edit the metadata for a package

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#1646]
That would be nice of `opam pin edit <pkg>` would work even if the package is not pinned. That would create a overlay for the given package, and propose to edit the `opam` file. That would be quite handy to quickly fix a broken package. Could then use `opam show <pkg> --raw` or `opam-publish` to create a patch to send to the main repo.

**Comment by AltGr** [comment]
This can be achieved, more or less, using `opam pin add <pkg> <version> --edit`
