### ISSUE TITLE
Fish shell init scripts should treat PATH and MANPATH as arrays

### ISSUE THREAD

**Issue by hugomg** [ocaml/opam#1797]
In Fish, the PATH and MANPATH environment variables are arrays of strings instead of a single colon-separated string. In opam-init/variables.fish, these currently colon-separated values:

    set -gx MANPATH $MANPATH:/home/hugo/.opam/4.02.1/man
    set -gx PATH /home/hugo/.opam/4.02.1/bin:$PATH

should instead be space separated:

    set -gx MANPATH $MANPATH /home/hugo/.opam/4.02.1/man
    set -gx PATH /home/hugo/.opam/4.02.1/bin $PATH

This different syntax is only needed for [PATH and MANPATH](https://github.com/fish-shell/fish-shell/commit/c0b8e81b023bf1f118311a060662bea1ad565a19). The remaining variables (CAML_LD_LIBRARY_PATH, PERL5LIB, etc) should remain colon separated as they are right now.

**Comment by AltGr** [comment]
Should be fixed now, thanks for reporting.
