### ISSUE TITLE
git tag URLs seem to be broken in 1.2.0rc4

### ISSUE THREAD

**Issue by hcarty** [ocaml/opam#1808]
I have a local repository with a package defined with a git URL `ssh://host:port/repo/#v0.1.0`.  This works under opam 1.1.0.  Under 1.2.0rc4 I get `fatal: Couldn't find remote ref v0.1.0`

`v0.1.0` is a tag in this instance.

**Comment by AltGr** [comment]
d287442895d0ba1c9d1bc4b0694df2746a6731e5 should work around this, falling back to fetching all refs when the clever version fails.
