### ISSUE TITLE
More aggressive caching

### ISSUE THREAD

**Issue by whitequark** [ocaml/opam#1821]
I frequently reinstall packages, and on a slow connection it can be very annoying how opam downloads and discards the package archives every time. It seems like the cache is cleared entirely every time a repository updates; but this is not necessary for the vast majority of packages, validated by checksum!

**Comment by whitequark** [comment]
Can you please simply switch to caching packages by using their checksum, rather than archive name, as the key? This is a trivial issue to fix and it is extremely annoying to anyone who needs to download large archives.

**Comment by AltGr** [comment]
Yes, archives are now cleaned less eagerly, but this would be useful for e.g. multiple packages based on the same archive (like the new separate packages for opam sub-libraries).

Opam has seen a general overhaul since 1.2, but archive and download handling haven't been much changed yet -- this will be the next target, and is likely going to go together with repository and package signing, which requires it anyway.

**Comment by whitequark** [comment]
> Yes, archives are now cleaned less eagerly, but this would be useful for e.g. multiple packages based on the same archive (like the new separate packages for opam sub-libraries).

You don't have to clean archives at all if you do it like I suggest. Multiple packages is just a free bonus

**Comment by whitequark** [comment]
Uh... also, archives shouldn't be per-switch. This is such a waste of disk space, bandwidth and time :(

**Comment by AltGr** [comment]
They obviously shouldn't; it's the result of the previous solution being a mess and me procrastinating a proper rewrite: redundant multiple levels of caching have been removed, but without a proper scheme to replace them.

One reason why we don't have indexing by hashes yet -- which would be by far, I fully agree, the most convenient -- is that there are many complaints that MD5 isn't safe and shouldn't be used for that anymore. Yet it's the only hashing algo built-in OCaml, and a wider selection of hashes is anyway planned with the signing framework. So while moving to a global MD5-based cache of archives now should be quite easy, I am not sure it is the best idea in the middle term.

**Comment by whitequark** [comment]
I don't see any problem with adding a pure-OCaml SHA256 implementation just for this, and I see very little problems with adding a C stub. Seems like a straightforward case of perfect being an enemy of working for me.

**Comment by whitequark** [comment]
@AltGr did you implement this?

**Comment by whitequark** [comment]
@AltGr Please indicate at least something about the bug's status, or I will open a new one for every one you've closed this way.

**Comment by AltGr** [comment]
Yes, sorry, when I close an old bug without a message, it means that either it's obsolete and doesn't apply anymore, or it has been implemented. Opam now caches downloaded files by hash, and keeps them until explicit cleanup.

**Comment by whitequark** [comment]
@AltGr Thank you for clarification, I will keep this in mind from now on.
