### ISSUE TITLE
opam --root over an NFS folder on network

### ISSUE THREAD

**Issue by william3** [ocaml/opam#1854]
opam init --root /shared/nfs/directory/on/the/network
is VERY slow (30 minutes), while duration seems normal in /home/directory/.opam (seconds)
Usual access to /shared/directory/on/the/network is fast. The reason to use this directory is that many people would need access to OPAM installed packages.

OPAM indeed doesn't play very well with NFS for a few reasons:
    OPAM accesses a lot of files, especially at init or update
    OPAM uses some temporary directories within the opam root, in particular, compilations are done there: compiling over NFS is generally a bad idea.
- Not sure exactly how to improve on this, maybe an option (or automatic behaviour) to set the build directories outside of the OPAM root would be worth investigating.
- A status bar could show that opam does not freezes but is actually very slow

Also, there is maybe a way I can handle this with actual opam 1.2 ? like installing in .opam, then copying files to /shared/nfs/directory/on/the/network ?

The problem is not blocking, because I only use opam once a year when ocaml is updated.

Best regards

**Comment by AltGr** [comment]
This should be improved in the new version, which has much better use of locking and loads the files in a more organised manner; if anyone can test, that would be helpful.

**Comment by UnixJunkie** [comment]
by the way, working on top of NFS is not so rare as one might think. For example, all supercomputer frontends usually serve users' homes over NFS (or some NFS-like).

**Comment by UnixJunkie** [comment]
I confirm that even with opam-2.0 this is too slow.
What should I provide in order to show what is slow?
An strace?
Running opam under some profiler?
If you tell me which procedure to follow, I can send you the data.

**Comment by UnixJunkie** [comment]
maybe a workaround:
https://github.com/ocaml/opam/pull/3429

**Comment by dra27** [comment]
This should be addressed in opam 2.1 by the new faster repo sync mechanism as the repository files are now in a tarball
