### ISSUE TITLE
Add a dev dependency flag

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#1861]
As discussed on the [list](http://lists.ocaml.org/pipermail/opam-devel/2014-October/000739.html), for specifying development (i.e. pin) dependencies,

**Comment by AltGr** [comment]
This is non-trivial to implement because current value of the flags (build, doc, test) can be defined globally, while this is defined for a single package (and depending on its state and URL too, not just its opam file). Not in 1.2.1

**Comment by dbuenzli** [comment]
Would it be possible to make it *parsed* in the opam file format of 1.2.1 ?

**Comment by dbuenzli** [comment]
I'm not sure why this was closed, do we really have `dev` dependencies in `opam` 2.0 ?

I [routinely](https://github.com/dbuenzli/tgls/issues/9) [get](https://github.com/dbuenzli/tgls/pull/16) [bogus](https://github.com/dbuenzli/uunf/issues/6) [issues](https://github.com/dbuenzli/uucp/issues/10) [about](https://github.com/dbuenzli/uucp/issues/6) this.

**Comment by AltGr** [comment]
Indeed, this was implemented in #2205, sorry for the lack of details. The dependency flags are now standard variables, however, so that was superseded and the `dev` variable we spoke about earlier works here too, as a dependency filter !

This means that even dependencies like `[ "foo" {!dev} | "bar" {dev} ]` are possible

**Comment by AltGr** [comment]
(it's even lacking from the short doc here: http://opam.ocaml.org/doc/2.0/Manual.html#opamfield-depends)

**Comment by dbuenzli** [comment]
Aha that's good, thanks.

**Comment by cdaringe** [comment]
hmmmm, it's still not clear to me how to use the `dev` flag, even having consulted the docs and PRs. the dev flag is something i would use that is not for build | test | doc, but rather, say, a particular version of the LSP or ocamlformat. 

to use `dev`:

- mark deps like ... ???  ` "my_dep" {>= "0.0.0" & dev}`
- install via `opam install . --dev` ?
