### ISSUE TITLE
Solver again broken

### ISSUE THREAD

**Issue by fdagnat** [ocaml/opam#1912]
Hello,
Gringo has been upgraded in homebrew but this upgrade breaks indirectly opam because aspcud has registered the old path of gringo (gringo   : /usr/local/Cellar/gringo/4.4.0/bin/gringo) whereas gringo is now in /usr/local/Cellar/gringo/4.4.0_1/bin/gringo...

I have not been able to find documentation on how the paths of aspcud can be configured. It seems rather fragile to rely on the real path to gringo. aspcud should use the /usr/local/bin version of gringo which is stable and always linked to the binary of gringo... Perhaps it a problem of the brew package for aspcud?

I know the issue is not really an opam one but for the basic user it shows only in opam...

**Comment by fdagnat** [comment]
Issue solved with reinstallation of the aspcud package

**Comment by AltGr** [comment]
Ok, glad it was. Thanks for the follow-up!
