### ISSUE TITLE
Solver issues with OCaml 4.01 and opam 1.2

### ISSUE THREAD

**Issue by ivg** [ocaml/opam#1923]
We've a CI that builds with different versions of opam+compiler, and we've ran into an interesting problem, when a solver can't resolve dependencies correctly. Currently we've three variants in matrix:

```
OCAML_VERSION=4.01.0 OPAM_VERSION=1.1.0
OCAML_VERSION=4.01.0 OPAM_VERSION=1.2.0
OCAML_VERSION=4.02.0 OPAM_VERSION=1.2.0
```

The second variant fails, since it can't install the newest version of the `piqi` library. Other packages installed are also not the freshest one. I've tried to use `aspcud` but the result is exactly the same, so maybe the problem is not with a solver, but with some package configuration.  We have the following build dependencies: `"core_kernel oasis piqi zarith bitstring utop cmdliner faillib ezjsonm lwt-zmq uri"`, and build logs are available [here](https://travis-ci.org/BinaryAnalysisPlatform/bap/builds/45098687).

**Comment by AltGr** [comment]
Ok, I am getting an understanding of what happened. The fundamental issue is that _the best_ solution is a subjective concern. What was at play here is simply the change to "more advanced" solver criteria, which in your case didn't meet your expectation as well -- here is a diff of the two proposed solutions:

```
1.1                                   | 1.2
base-no-ppx.base                        base-no-ppx.base
base64.1.0.0                          <
bin_prot.111.03.00                      bin_prot.111.03.00
bitstring.2.0.3                       | bitstring.2.0.4
camlp4.4.01.0                           camlp4.4.01.0
camomile.0.8.5                          camomile.0.8.5
cmdliner.0.9.5                        | cmdliner.0.9.6
comparelib.109.60.00                    comparelib.109.60.00
conf-gmp.1                              conf-gmp.1
core_kernel.111.28.00                   core_kernel.111.28.00
                                      > cppo.1.1.2
easy-format.1.0.2                       easy-format.1.0.2
enumerate.111.08.00                     enumerate.111.08.00
ezjsonm.0.3.0                         | ezjsonm.0.4.0
faillib.111.17.00                       faillib.111.17.00
fieldslib.109.20.03                     fieldslib.109.20.03
herelib.109.35.02                       herelib.109.35.02
hex.0.1.0                               hex.0.1.0
jsonm.0.9.1                             jsonm.0.9.1
lambda-term.1.7                         lambda-term.1.7
lwt-zmq.2.0.0                           lwt-zmq.2.0.0
lwt.2.4.6                               lwt.2.4.6
oasis.0.4.5                             oasis.0.4.5
ocaml-data-notation.0.0.11              ocaml-data-notation.0.0.11
ocamlfind.1.5.5                         ocamlfind.1.5.5
ocamlify.0.0.1                          ocamlify.0.0.1
ocamlmod.0.0.7                          ocamlmod.0.0.7
optcomp.1.6                           <
ounit.2.0.0                             ounit.2.0.0
pa_bench.111.28.00                      pa_bench.111.28.00
pa_ounit.111.28.00                      pa_ounit.111.28.00
pa_test.111.08.00                       pa_test.111.08.00
pipebang.110.01.00                      pipebang.110.01.00
piqi.0.7.1                            | piqi.0.6.5
piqilib.0.6.9                         <
re.1.2.2                                re.1.2.2
react.1.2.0                             react.1.2.0
sexplib.111.25.00                       sexplib.111.25.00
stringext.1.1.0                         stringext.1.1.0
type_conv.111.13.00                     type_conv.111.13.00
typerep.111.17.00                       typerep.111.17.00
uint.1.1.5                              uint.1.1.5
ulex.1.1                                ulex.1.1
uri.1.7.2                               uri.1.7.2
utop.1.15                             | utop.1.17
uutf.0.9.3                              uutf.0.9.3
variantslib.109.15.03                   variantslib.109.15.03
xmlm.1.2.0                              xmlm.1.2.0
zarith.1.3                              zarith.1.3
zed.1.3                                 zed.1.3
zmq.4.0-3                               zmq.4.0-3
```

So, though the chosen version for piqi is lower, OPAM 1.2 picked newer versions of bitstring, cmdliner, ezjsonm and utop, while also installing less extra packages. Now, to know why all newer versions couldn't be installed at once, you would have to try to explicitely install them together to have OPAM output the reason of the conflict.

You can always specify the optimisation criteria through the `--criteria` flag or the `OPAMCRITERIA` env variable (for the record, criteria used by OPAM 1.1 were `-removed,-notuptodate,-new`), but I don't recommend that as it may better fit your expectation in this precise case just by chance.

The best solution in your case would be to be more specific in your request, eg. `opam install xxx yyy 'piqi>=0.7'`, or even, if you want to guarantee the latest available version of piqi, `opam install xxx yyy piqi=$(opam show piqi --field=version)`. (OPAM 1.1 doesn't support `PKG=V` or `PKG>=V`, but `PKG.V` should work for both versions)

**Comment by AltGr** [comment]
If you want to know more about the solver criteria, there is [a detailed guide](http://opam.ocaml.org/doc/Specifying_Solver_Preferences.html) in opam's documentation.

**Comment by ivg** [comment]
Thanks you so much for the detailed answer!
