### ISSUE TITLE
Add link to relevant bug-trackers on error

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#1929]
Now that the `bug-reports` field is used a bit more pervasively, it would be nice to use that information and display the relevant bug-tracker uris in case of errors.

**Comment by AltGr** [comment]
Errors at compile or remove time of the package ? Hm, good idea.

**Comment by rjbou** [comment]
Closing the issue, as the PR is closed. Cf. PR for more details. Feel free to reopen.
Thanks!
