### ISSUE TITLE
Dose and Ctypes module name clash prevents concurrent linkage

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#1931]
This occurs when trying to use `opam-publish`.

```
ocamlbuild -use-ocamlfind -pkgs opam-lib,opam-lib.repositories,opam-lib.client,cmdliner,github.unix src/opam_publish.native
+ ocamlfind ocamlopt -linkpkg -package github.unix -package cmdliner -package opam-lib.client -package opam-lib.repositories -package opam-lib src/version.cmx src/opam_publish.cmx -o src/opam_publish.native
File "_none_", line 1: 
Error: Files /Users/avsm/.opam/system/lib/dose3/common.cmxa
       and /Users/avsm/.opam/system/lib/ctypes/ctypes.cmxa
       both define a module named Common
```

I'd suggest that both Dose and Ctypes should not stick a global module called `Common` :-) /cc @yallop

**Comment by yallop** [comment]
This'll be fixed in the next release.

**Comment by AltGr** [comment]
Filed a bug in dose's [tracker](https://gforge.inria.fr/tracker/index.php?func=detail&aid=18454&group_id=4395&atid=13808)

**Comment by yallop** [comment]
As of version 0.4 ctypes no longer exposes a module named `Common`.

**Comment by AltGr** [comment]
Closing then, although there is no follow-up on Dose yet. Thanks!
