### ISSUE TITLE
Fish Shell Support Not Working Out of the Box

### ISSUE THREAD

**Issue by trevorsummerssmith** [ocaml/opam#1932]
Hello,

I am using opam 1.2.0 and fish 2.1.1. The fish scripts installed by opam do not work. They output pages of syntax errors, because they are not fish scripts. This is a jarring experience on install. Details below.

The init.fish script calls three other scripts:

1) variables.sh - does not work, but this is fixed in #1797
2) complete.sh - this is not a fish script and will not work.
3) switch_eval.sh - this is not a fish script and will not work.

Both of these files can be straightforwardly ported to fish.

Thoughts? Thank you.

Trevor

Output of opam config report as requested in the bug report filing guidelines.

```shell
trevor@trevor-mac ~/.o/opam-init $$ opam config report
# OPAM status report
# opam-version    1.2.0
# self-upgrade    no
# os              darwin
# external-solver aspcud
# criteria        -count(removed),-notuptodate(request),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution)*
# jobs            1
# repositories    1* (http)
# pinned          0
# current-switch  4.02.1
# last-update     2015-01-04 13:39
```

**Comment by AltGr** [comment]
complete.sh and switch_eval.sh shouldn't be used if you're on fish, so you should be fine with the #1797 fix. If you're willing to port the completion script to fish, the contribution would be very welcome :)

**Comment by trevorsummerssmith** [comment]
@AltGr thanks for your response. I don't have time right now to work on the completion script. I think that should be another ticket -- provide that functionality for fish.

My ticket was meant to highlight that on installation, the fish script will NOT work, this was meant to be a bug ticket. #1797 does NOT fix this issue, because the init.sh calls complete.sh and switch_eval.sh.

I agree with you that complete.sh and switch_eval.sh should not be called by init.fish.

The fix to this issue is to remove those lines from the fish.init file (which looks like the shell's globals in the OPAM need to be modified to say "shell_eval = false" and "complete = false" if it is using fish shell [somewhere around here] (https://github.com/ocaml/opam/blob/2b172252e16de7747edc7d495249471720a84d4a/src/client/opamArg.ml#L997)). Both of those values can be updated to true, once the scripts are ported.

**Comment by AltGr** [comment]
Ok, here is the trick: it _was_ generating the proper `init.fish` script with `opam init --fish`, but for some reason you were still getting a (broken) `init.fish` file with `opam init --sh` with the completion and stuff...
Thanks for reporting !
