### ISSUE TITLE
Prettier error message when install script don't match existing files.

### ISSUE THREAD

**Issue by def-lkb** [ocaml/opam#1935]
If check [opamAction.ml:74](https://github.com/ocaml/opam/blob/23d6b7863b44f20bc7b1a20c4a63d925158129aa/src/client/opamAction.ml#L74) fails, nothing is reported immediately, but opam will fail with an internal error "Error processing %s.install" raised by [opamAction.ml:136](https://github.com/ocaml/opam/blob/23d6b7863b44f20bc7b1a20c4a63d925158129aa/src/client/opamAction.ml#L136).

Also the format `"Error processing %s.install"` should be replaced by `"Printf.sprintf "Error processing %s"` since the parameter will be substituted by a proper filename.

**Comment by AltGr** [comment]
Are you on 1.2 ? This seems to be already fixed on master.

**Comment by def-lkb** [comment]
Yes, this was on 1.2.0.
Second point is still valid on master.

**Comment by AltGr** [comment]
Ok, thanks !

**Comment by def-lkb** [comment]
Here is the log with a recent master (35675fccd8c66bb52c4f7ffec45c6763d271f5c1 from Jan 12):
```
[ERROR] While installing the following files:
 - ocamlmerlin in /home/def/.opam/4.02.1/bin
[ERROR] Failure("Error processing /home/def/.opam/4.02.1/install/merlin.install.install")

#=== ERROR while installing merlin.2.0.0 ======================================#
Failure("Error processing /home/def/.opam/4.02.1/install/merlin.install.install")
```

The build fails because of the Makefile generating the file at the wrong place (the script is deliberatly wrong, opam behavior is totally correct).
I'd still like a more friendly error message (e.g the file is not found, and that is the processing error, not a syntax problem in the .install, etc)

**Comment by AltGr** [comment]
Granted, there is some noise below, but isn't the beginning:
```
[ERROR] While installing the following files:
 - ocamlmerlin in /home/def/.opam/4.02.1/bin
```
what you want already ?
