### ISSUE TITLE
`opam lint` should not warm if a test depends is repeated in depopt

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#1938]
If I have:

```
name: "a"
depends: [ b {test} ]
```

```
name: "b"
```

and "a" and "b" both installed, reinstalling "b" should reinstall "a". This is not the case at the moment. ie. `test` dependencies should behave like normal optional dependencies.

```
# OPAM status report
# opam-version    1.2.0 (c22e5b3f217cff64f3cc3cef7712684034dfd785)
# self-upgrade    no
# os              darwin
# external-solver aspcud
# criteria        -removed,-notuptodate,-changed*
# jobs            1
# repositories    1* (http), 1 (version-controlled)
# pinned          5 (path), 2 (version control)
# current-switch  4.02.1
# last-update     2015-01-10 00:57
```

**Comment by AltGr** [comment]
The current semantics is simply: "use this dep if --test is specified, otherwise ignore it"
So it won't recompile unless you're specifying `--test` in the command.

Is it a bug on the above, or is this semantics not what you would want ? Anyway, that should be clearly specified.

**Comment by samoht** [comment]
Should be better specified and `opam lint` should not give a warning if this is the recommend way to do.

**Comment by AltGr** [comment]
Indeed, the lint function doesn't check extra flags of depends, and a depopt that's also a test dep can make sense ; although I still don't see why, in the general case, you'd want `opam reinstall b` (without --test) to reinstall `a` ?

**Comment by samoht** [comment]
I'm fine to repeat the real optional dependencies in depopts, I was just being confused by `lint`. 

See https://github.com/samoht/ocaml-git/commit/b6614444bfd43cb43236403feccbc14affba353d for instance.

**Comment by samoht** [comment]
> I'm fine to repeat the real optional dependencies in depopts, I was just being confused by lint.

To clarify: I'm fine to do it, I just find it not very elegant :p

**Comment by AltGr** [comment]
Indeed, it's not... on the other hand do you think that should always be the case ? I was just curious of your use-case, and why precisely you need it.

**Comment by samoht** [comment]
>  I was just curious of your use-case, and why precisely you need it.

what I really need is the `feature` stuff :p I want to enable/disable stuff at configuration time depending on what is installed. Examples:
- enable the tests if we are in `test` mode. Currently my workaround is to put `alcotest` as a `test` dependency and call configure with `--%{alcotest:enable}%-tests`. I would prefer not do that and pass `--%{test:enable}%--tests` indeed. In that case I don't care about recompilation.
- enable some `unix` sub-packages if a set of dependencies is present: `--%{git+conduit+cohttp:enable}-unix}%` and the unix sub-package should also be present for the tests, so I also have `--%{git+conduit+cohttp+alcotest:enable}-tests`. So now `git`, `conduit` and `cohttp` become `test` dependencies as well but I want them to cause a recompilation of my package.

**Comment by AltGr** [comment]
>  * enable the tests if we are in test mode. Currently my workaround is to put alcotest as a test dependency and call configure with --%{alcotest:enable}%-tests. I would prefer not do that and pass --%{test:enable}%--tests indeed. In that case I don't care about recompilation

Makes perfect sense: I'll add `test` and `doc` variables right away. (Not `test:enable` though, because that's defined with a package name, not a variable, on the left of the colon. Otherwise, for consistency's sake, we'd have to define `:xxx` conversions in a more generic way and write something like `alcotest:installed:enable` ; features will obviously include an easy way to convert bools to enable/disable anyway)

> * enable some unix sub-packages if a set of dependencies is present: --%{git+conduit+cohttp:enable}-unix}% and the unix sub-package should also be present for the tests, so I also have --%{git+conduit+cohttp+alcotest:enable}-tests. So now git, conduit and cohttp become test dependencies as well but I want them to cause a recompilation of my package.

I see, they _are_ indeed both test-deps and depopts then, for distinct reasons, so it seems fine to me to add them in both fields (and that shouldn't cause a warning).

Thanks, that's an interesting use-case !
