### ISSUE TITLE
ERROR while installing ocamlfind.1.5.5

### ISSUE THREAD

**Issue by rogergl** [ocaml/opam#1939]
I'm trying to run opam install utop. But I get ERROR while installing ocamlfind.1.5.5. I'm using opam 1.2.0 on Mac 10.10.  Any ideas how to make this work ? Is this the right place to ask this question ?

**Comment by dbuenzli** [comment]
No, this should be filed [here](https://github.com/ocaml/opam-repository) along with the output of the failing install for diagnosing the situation.
