### ISSUE TITLE
Cute utf8 icon when applying a patch

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#1947]
The action of applying a patch doesn't have a cute utf8 icon. It's dragged all the way to the left and not aligned with the other actions. :(

**Comment by AltGr** [comment]
:D
Glad you like the new display. Indeed patching is not considered a first-class action at the moment, but I am precisely in the process of improving download/patch stuff.

I started with this to get my mind clear on how it's happening at the moment and how to simplify:

![archive download](https://cloud.githubusercontent.com/assets/807966/5787810/ea6acda4-9e54-11e4-9900-3e7af74148f8.png)

**Comment by AltGr** [comment]
Should be cleaner now.
