### ISSUE TITLE
Show a warning for lack of aspcud

### ISSUE THREAD

**Issue by whitequark** [ocaml/opam#1951]
It's a rather common issue that without aspcud, an upgrade requires completely bogus downgrades. At the same time it looks like some operations (installs?) don't really need aspcud.

I propose to show a warning that a better solution would be available if aspcud is present, but only if any downgrade or uninstall is scheduled as a result of install or upgrade action. This would really help the mostly novice users who don't have aspcud and didn't usually even know it can be an issue.

**Comment by AltGr** [comment]
Hmm, indeed, I see your point on a user perspective. That would amount to adding heuristics on top of the heuristics to try and detect that they underperformed though ; not the best feeling, though that should be straightforward to implement and harmless.

Note that there already is a warning about aspcud at init time. But I guess, init being a bit verbose, that it may be easily overlooked...

**Comment by whitequark** [comment]
Why the close?

**Comment by AltGr** [comment]
Because it has been implemented :)
See ddb4dd38

**Comment by avsm** [comment]
awesome @altgr :-)
