### ISSUE TITLE
'make libinstall' doesn't install .mli or .cmx files

### ISSUE THREAD

**Issue by jonludlam** [ocaml/opam#1953]
It should, shouldn't it?

**Comment by AltGr** [comment]
Should it ? I don't know if there is a global recommended behaviour. My understanding is that cmx files are redundant with the cmxa, and mli shouldn't be needed if you have the cmi and cmtis. mli could still be useful, I guess, if you want to access the ocamldoc (until we have the new ocamldoc, that is...) ; although cmti _should_ be enough. It just feels too much like C to install header files...

**Comment by yallop** [comment]
Cross-module Inlining needs the `.cmx` files; the `.cmxa` isn't sufficient.

**Comment by jonludlam** [comment]
https://fedoraproject.org/wiki/Packaging:OCaml?rd=Packaging/OCaml has suggestions for which things to package for Fedora. I believe it's slightly out of date in that it doesn't mention cmxs cmxt and these sort of newer files

**Comment by avsm** [comment]
We should install `.mli` files -- they act as human-readable documentation (I commonly grep for them in `~/.opam`). 

There's no question that `.cmx` and `.cmxs` files should be installed -- the former is for cross module inlining, and the latter for natdynlink support.  Fixing this in 1.2.1 would be good, as we're increasingly using opamLib for infrastructure related tasks, and not having these available in the source package will be problematic (vs fixing them up in the individual Deb and RPMs)
