### ISSUE TITLE
Can't "opam init" on Ubuntu 12.04

### ISSUE THREAD

**Issue by pdonadeo** [ocaml/opam#1955]
When I try to init opam on Ubuntu 12.04.5 I obtain an error message regarding di external solver.

First I added the OPAM repository:
```
# add-apt-repository ppa:avsm/ppa
# aptitude update
# aptitude install opam ocaml-nox
```
The OCaml compiler installed (from @avsm repo) is 4.02.1-1ppa3~precise and compiling a simple "hello world" works as expected.

Then, as unprivileged user:

```
$ opam init                                                                                                                                                                
Checking for available remotes: rsync and local, git.                                                                                                                        
[NOTE] hg not found, you won't be able to use mercurial repositories unless you install it.                                                                                  
[NOTE] darcs not found, you won't be able to use darcs repositories unless you install it.                                                                                   
[default] Downloading https://opam.ocaml.org/urls.txt                                                                                                                        
[default] Downloading https://opam.ocaml.org/index.tar.gz                                                                                                                    
Updating ~/.opam/repo/compiler-index ...                                                                                                                                     
Updating ~/.opam/compilers/ ...                                                                                                                                              
Updating ~/.opam/repo/package-index ...                                                                                                                                      
Updating ~/.opam/packages/ ...                                                                                                                                               
[WARNING] External solver failed with inconsistent return value. Request saved to "/home/pdonadeo/.opam/log/solver-error-25512-1.cudf"                                       
[ERROR] Please retry with option --use-internal-solver
```

The first problem I see is that the file /home/pdonadeo/.opam/log/solver-error-25512-1.cudf does not exist, because OPAM deletes the .opam directory upon failure.

Ubuntu packages versions are:
 * OPAM: 1.2.0-1ppa1~precise
 * ocaml-nox: 4.02.1-1ppa3~precise
 * aspcud: 2011.03.17.dfsg-3
 * clasp: 2.0.4-1
 * gringo: 3.0.3-7

Do you have any ideas about this situation? Can I help?

Incidentally, using the --use-internal-solver option works.

**Comment by AltGr** [comment]
Thanks for reporting. Does running `opam switch new-test --alias-of system` once you have a working opam root reproduce the issue ? It should be a similar request to the solver.

Not sure where this could come from, but indeed these aspcud/clasp/gringo packages are a bit old ; hopefully you could get more information from the above, please do also try to dump the cudf solver request with `--cudf <name>` ; then `aspcud <name>-1.cudf /dev/stdout -removed,-notuptodate,-changed` should replay the solver query. Thanks.

**Comment by pdonadeo** [comment]
@AltGr just checked... and it works now. I can't believe...

Probably a system update occurred in the last 48 hours changed some mysterious state, I really don't know.

Forget this issue, I'm sorry for the noise.
