### ISSUE TITLE
Warn/error when opam root is inside a pinned package

### ISSUE THREAD

**Issue by dsheets** [ocaml/opam#1956]
I needed to test a package with a custom opam root so I made a new opam root in the development directory of said package and then I initialized opam and then I pinned the package.

By the time I realized the mistake I'd made, `rsync` had gobbled my last 5GB of disk.

This isn't a very common occurrence but it is rather shocking to come across.

**Comment by AltGr** [comment]
:D 
Indeed, did not foresee that one... Note that with the new "mixed mode git" pin, the rsync is limited to git-tracked files so you should have been safe (it's `--kind git`, but targetting a local directory and without a branch set). See the [FAQ](https://opam.ocaml.org/doc/FAQ.html#WhatisquotmixedmodeVCpinquot) for details.

But indeed, good idea to detect that.

**Comment by dsheets** [comment]
Ah, yes, I was using 1.2.0 as released which still defaults to `-k path` because I needed to avoid the `opam-lib` change to the `base_packages` identifier used by `opamfu`.

I think this kind of mistake should be quite rare in practice. Labeling enhancement.

**Comment by avsm** [comment]
Also ran across this in opam-boot!
