### ISSUE TITLE
Version mismatch in ~/.opam/config

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam#1958]
When installing `opam` by pinning the Git repository, one may end up with different versions of `opam` for different switches.  This is *convenient* because `opam-lib` API is incompatible across versions and `opam-lib` requires that the version of OPAM matches in `~/.opam/config`.

The problem is that `~/.opam/config` is *shared* among switches and so, if versions differ, after switching, one may be unable to use the version of `opam` in the current path because of errors like
```
[ERROR] ~/.opam reports a newer OPAM version, aborting.
```

**Comment by AltGr** [comment]
It may indeed be dangerous when there is a significant repo format change ; but it shouldn't be the case for patch-versions.
You can anyway work around it by setting `OPAMSKIPVERSIONCHECKS` to `1` -- or setting reference `OpamGlobals.skip_version_checks` in OCaml code using the library.

**Comment by Chris00** [comment]
Maybe setting `OPAMSKIPVERSIONCHECKS=1` could be suggested as part of the error message? (Explaining it is not a good permanent default?)

**Comment by AltGr** [comment]
Note that I relaxed the check in `~/.opam/config` to only refer to the minor version, not the patch version. That'll remove the complaints at least when changing only OPAM's patch version.
