### ISSUE TITLE
ability to pin packages from switch/compiler descriptions

### ISSUE THREAD

**Issue by gasche** [ocaml/opam#1959]
In order to support a user-friendly OPAM workflow for Coq users, it would be helpful to be able to provide OPAM switches (that is, compiler descriptions) that list coq in their `packages` field *and* pin it to a specific version.

I'm thinking of simply something like

```
packages: [ ["coq" {= "8.4.5"}]]
pin: [
  ["coq" {= "8.4.5"}]
]
```

but you may want to generalize it to something like:

```
commands: [
  ["install" "coq.8.4.5"]
  ["pin" "ad" "coq" "8.4.5"]
]
```

(The first form already allows for pinning with different kinds than versions (path or dvcs), which I don't have a use for but other might.)

As a hack I tried to list in the `packages` field a package whose install command was `opam pin add coq 8.4.5` (and `pin remove` in `uninstall`), but this does not work: when `opam pin` is invoked recursively from the `opam switch install` process, it tries to get hold of the OPAM lock and fails.

**Comment by gasche** [comment]
The reason why it would be important to `pin` is that differences between Coq versions are so large than most packages need to be rewritten in non-trivial way at a version change. If a 8.4 user has installed a few packages and then asks to install a 8.5-specific package, proposing to upgrade Coq (and uninstall/upgrade all its package) is almost never the right thing to do -- and would take hours. It's much better to forbid this by pinning (and use `opam list -A` to unsee 8.5-specific packages), and advertize to the Coq community the use of one switch for each Coq version.

(Thomas Braibant previously considered making a small fork of OPAM so that the concept of switches would depend not on the OCaml version, but -- for Coq users -- on the Coq version. You can see the pinning idea as a way to encode this logic without paying the cost of an upstream fork.)

**Comment by gasche** [comment]
I wonder whether this is related to #1930 : in [his post](https://github.com/ocaml/opam/issues/1930#issuecomment-68673591) @AltGr says that

> Any entries you put in the packages field of the compiler definition will be considered as "base", immovable packages (we may relax some constraints, step by step, later on)."

and this is more or less what I'd like to have here.

**Comment by yallop** [comment]
> As a hack I tried to list in the packages field a package whose install command was opam pin add coq 8.4.5 (and pin remove in uninstall), but this does not work: when opam pin is invoked recursively from the opam switch install process, it tries to get hold of the OPAM lock and fails.

Would a base package which depends on `coq 8.4.5` (rather than pinning it in the build step) do what you need?  You could also add a constraint to the base package to tie it to a particular compiler switch to avoid unwanted upgrade suggestions.

**Comment by gasche** [comment]
If I understand correctly, you are suggesting that in the description of this new coq-8.4-specific OPAM switch, I use:

```
packages: [
  "coq" "select-coq-8.4"
]
```

where `select-coq-8.4` itself depends on `"coq" {= "8.4.5"}`.

I previously tried almost the same thing, but `select-coq-8.4` had this pinning hack. You seem to assume that base packages are un-removable (which is what I need here), is this documented anywhere as a robust behavior?

**Comment by samoht** [comment]
I'll let Louis reply more precisely, but 1) currently you have no guarantee that a base package will be kept at the same version. The solver should include the base packages in the install set of each request though, so in practice this should be fine. And opam will warn the user if a base package is not properly installed in the current switch. And 2) yes, the compiler-as-package branch should resolve the problem more nicely: a switch will just become a set of constraints that should always hold for the current switch.

**Comment by avsm** [comment]
Any package that is installed with a fixed constraint will take priority over a subsequent installation (since the later one will not be admitted due to a constraint failure). So it's not special as a base package; just installing the select-coq package first should be sufficient to achieve what you need.

**Comment by gasche** [comment]
I'm sorry if I'm a bit slow here (I'm not familiar at all with how OPAM encodes installation problems), but what @avsm is saying is that OPAM never removes existing packages to satisfy new installation requests? I'm a bit wary of relying on this (that sounds like a result of the current implementation choices rather than a design invariant), but I'll experiment with it to see how well it works in practice.

**Comment by gasche** [comment]
I tried "just" have a dependency to coq-8.4 in a `base` package of the switch, and it appears not to work. That is, if I try to install a package that requires coq-8.5, opam gladly proposes to remove the version-fixing package and update the Coq version:

> The following actions will be performed:
> - remove    coq:select84.1
> - upgrade   coq from 8.4.5 to 8.5beta1            [required by pidetop]
> - install   pidetop.0.2.0

**Comment by AltGr** [comment]
> I tried "just" having a dependency to coq-8.4 in a base package of the switch, and it appears not to work. That is, if I try to install a package that requires coq-8.5, opam gladly proposes to remove the version-fixing package and update the Coq version

Switch to OPAM master :)

> As a hack I tried to list in the packages field a package whose install command was opam pin add coq 8.4.5 (and pin remove in uninstall), but this does not work: when opam pin is invoked recursively from the opam switch install process, it tries to get hold of the OPAM lock and fails.

Yes, that's the only sane behaviour in this case.

> > Any entries you put in the packages field of the compiler definition will be considered as "base", immovable packages (we may relax some constraints, step by step, later on)."
> and this is more or less what I'd like to have here.

Cool, that's now the case  :-)

> currently you have no guarantee that a base package will be kept at the same version. 

Wasn't the case in 1.2, but now you do. There should be no need for pinning, specifying in the .comp's  `packages:` field, with the appropriate version, is all you should need. It's actually better than pinning, because it also guarantees the package won't be removed.

**Comment by gasche** [comment]
Ok, thanks a lot -- it's very good.

I guess we will have to advertise pinning the Coq version for 1.1.1 and 1.2 user, and use this technique for user-friendly coq OPAM switches once 1.3 is released and packaged.

**Comment by avsm** [comment]
@AltGr I think  you can get the same behaviour in OPAM 1.2 by registering the `select-coq-8.4` package as a root, right?  I.e. by typing in `opam install select-coq-8.4`.

**Comment by avsm** [comment]
Reopening this -- I'd like to see if there's a course of action to make this work with OPAM 1.2 rather force all Coq users to move to a development master.

**Comment by gasche** [comment]
I think I tried what you suggest previously: before putting `select-coq-8.4` in the `packages` field, I started from a blank switch and installed Coq then did `opam install select-coq-8.4`. It still proposed to remove this package and upgrade Coq when I tried to install a 8.5-only package.

**Comment by AltGr** [comment]
Indeed, in 1.2, you have pinning a a means to lock to a version, but there is no way to mark a package as unremovable (letting the user do so may be too likely to lead to "no solution available" situations ?).

But this'll be in 1.2.1, which is just around the corner !

On the "base" packages, a new feature was added more recently: they are initially locked to the version that was first installed; but, by pinning them, you still have a way to override this and set them to a different version. This could be used, for example, to explicitely upgrade your Coq version. Unsolved yet, the downside is that the switch name, version and maybe variables could get out of sync.
