### ISSUE TITLE
search for plugins using active switch PATH as well

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#1978]
Right now if you do:

```
opam init -a
opam install depext
opam depext foo
```

It fails since the user hasnt done the `opam config env` step yet.  It would make using plugins easier if `opam` searched in the active switch `PATH` for a plugin executable as well (e.g. like running `opam config exec`).

**Comment by AltGr** [comment]
Indeed, good point.

**Comment by AltGr** [comment]
The only downside is that `config exec` loads the full OPAM state, which can take time (the first time). It doesn't actually need the costly part, but we can probably leave that for a later optimisation pass.
There is a similar issue with using `opam list` at editor launch from `opam-user-setup`: it can eat up to a few seconds on first run.
