### ISSUE TITLE
add new variable %{ld_conf}%

### ISSUE THREAD

**Issue by tuong** [ocaml/opam#198]
When using the existing OCaml (`system`), `opam install P` could fail if the following conditions are encountered :
- `P` tries to write in `$(ocamlc -where)/ld.conf`,
- `$(ocamlc -where)/ld.conf` can only be read.

Here, `opam init` should copy `$(ocamlc -where)/ld.conf` to a writable file so that packagers could later refer to this file as `%{ld_conf}%`.

**Comment by xavierleroy** [comment]
For the record: I think OPAM setting `CAML_LD_LIBRARY_PATH` is harmful and useless, see my comment here https://github.com/ocaml/ocaml/issues/6532#issuecomment-626605401
