### ISSUE TITLE
issues with env vars detection.

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#1984]
- The env detection is broken when the env variables (especially the path) are modified after opam. This is new in trunk.
- the message about wrong env variables is printed even for commands invoked during completion, which is very annoying.

**Comment by Drup** [comment]
After more .zsh fiddling, the detection issue seems to appear only when I have twice the entry in my $PATH. This happened because I had ``eval `opam config env` `` in my `.profile` and ```source /home/gabriel/.opam/opam-init/init.zsh``` in my `.zsh` (for completion, in particular).

**Comment by AltGr** [comment]
On the first point, the function to detect your base PATH and previous changes made by OPAM can only be a heuristic. It normally replaces a previous OPAM(-looking) entry in the PATH, but in the case of sourcing `init.zsh`, there is a static prepend -- so yes, if you source that after evaluating `opam config env`, it won't play nice. Not sure how to make the situation better.
