### ISSUE TITLE
Gather error dump files in one (sensible) location

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#1992]
I tend to run opam in whatever terminal I have under my hand, and every time something fails (which happen often enough when hacking something) it spreads error dumps everywhere. I would prefer if error dumps where confined either in `/tmp/` or in `.opam/logs`.

**Comment by AltGr** [comment]
Indeed, sorry, just fixed this actually (see aace9efa7cc5e1728a166e3cfc1a31ba8d81c98b)

**Comment by Drup** [comment]
Thanks! The already fixed bugs are my favorite kind. <3
