### ISSUE TITLE
removing camlp4 on base system switch results in spurious warning

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#2003]
```
[WARNING] Directory /home/travis/.opam/system/lib/camlp4 is not empty, not
          removing
[WARNING] Directory /home/travis/.opam/system/lib/camlp4 is not empty, not
          removing
```

This can't be avoided, since ocamlfind puts a META file in that directory.  Should this warning also go into a different level of verbosity than default?

**Comment by AltGr** [comment]
Hm, that warning may still be useful for random packages... What's most questionable here is the implicit link between the name of the package and its library directory IMHO.

**Comment by avsm** [comment]
I think this sort of warning needs to go into a linting tool and not OPAM itself.  The link between the package name and the library directory is very ocamlfind specific..

**Comment by AltGr** [comment]
Alright, but we are quite far from having such a tool at the moment (we do have syntactic checks, but this requires installing + removing and checking what happens). Would be a good thing for sure, but it seems to me tracking of OPAM installed files from OPAM itself should go first.

As for the warning... would turning it into a `[NOTE]` be better ? (I've removed the duplicate already)
