### ISSUE TITLE
Remote local disabling 

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2004]
I would like to be able to disable a remote locally to some switch. It would allow me to have remotes overwriting some packages for experimenting while keeping a "stable" switch.

**Comment by AltGr** [comment]
Something like this is on the planned features (dubbed "per-switch-remotes"), it's just non-trivial to add to the current design (remotes are global and the highest priority origin is pre-computed for each package ; switches have no related configuration at the moment). Nothing impossible though.

**Comment by samoht** [comment]
+1 

This starts to come back quite often in discussion (and I tend to agree more and more): sometime your really don't want to add a new global remote. More recent example is to test the new version of mirage (which is not yet released). Easiest way it to test is to add `github.com/mirage/mirage-dev` as a remote -- but what you really want to do is to create a new switch to test the release and pin all the package in the remote.

So maybe a `opam pin repo-add <repo>` command or similar.

**Comment by amirmc** [comment]
Another +1 for per-switch-remotes.

I use multiple switches for different projects (usually aliased from `system`) and I recently hit an issue where I wanted 'production' MirageOS in one switch (i.e. the stuff anyone gets from the main opam package repo) and another switch with whatever is in the mirage-dev remote. Pretty much exactly the scenario Thomas just described.

In my particular case, I wanted to run through a normal tutorial/talk workflow and then show a feature of the upcoming functoria release.  I thought I could get away with this by setting things up in separate switches but I got a little bitten when the `mirage` tool decided to 'upgrade' things in the 'production' switch :)

It all worked out fine in my case, but I really want to be able to have remotes-per-switch as well as global remotes.

**Comment by amirmc** [comment]
I also think it would be useful to surface the remotes that you have installed as part of the `opam list` command.  One of the potential issues in having both remote-per-switch *and* global remotes is remembering the set up.  Having the first few lines of the `opam list` command output the global/local remotes would help.

(the only reason I suggest `opam list` in addition to the current `opam remote` is because I use 'opam list` more often and it seems like a useful place for a reminder that there's a *local* remote in play).

**Comment by avsm** [comment]
+1 for per-switch remotes. This is one of the few global options in OPAM that breaks out of the switch sandbox, and is particularly problematic for large-scale industrial development where it's quite common to have multiple remotes (e.g. MirageOS unikernels).  A fix in 1.3 would be both welcomed and tested by us :)

**Comment by yomimono** [comment]
I'd also really like this, for the reasons mentioned above by @avsm , @samoht, and @amirmc ; I currently avoid using custom remotes entirely because most of the situations in which I want them are switch-local and the risk of trashing other switches is high.
