### ISSUE TITLE
Make your stuff backwards compatible

### ISSUE THREAD

**Issue by wwat** [ocaml/opam#2009]
```
[ERROR] Your version of OPAM (1.1.1) is not recent enough to <dont care>.
```
Can't you fix your software such that I do *not* need to care about such details?

**Comment by nbraud** [comment]
You should use distribution-provided packages, that are meant for users not to care about such details (aside from updating their system from time to time).
For Debian/Ubuntu, @avsm provides a PPA that is up-to-date.

**Comment by AltGr** [comment]
Sorry if you hit a bug. 1.1 should still be supported, but there is a [glitch](http://opam.ocaml.org/doc/FAQ.html#Gaspopaminitgivesmescreensfullsoferrorsaboutupgrading)

Otherwise, can you fix your report so that it contains the details that may enable us to fix the issue ?
