### ISSUE TITLE
Newest package version is not visible

### ISSUE THREAD

**Issue by SGrondin** [ocaml/opam#2010]
I'm pretty sure this is an OPAM bug and not an Lwt one.

I'm running Debian 6 in a VM to make my builds.
On my development machine with Debian 8, I can install lwt.2.4.7 just fine.

On my build machine, with a fresh `4.02.0` (and `4.02.01`) switch, running `opam install lwt.2.4.7` fails with
```
Your request can't be satisfied
 - No package matches lwt.
```

**Comment by AltGr** [comment]
Curious indeed.

Could you please try:
* `opam list lwt` / `opam list --unavailable lwt`
* running the install command with `--debug` may give clues on what happens
* please include `opam config report` for both machines

Thanks!

**Comment by SGrondin** [comment]
This is a fresh 4.02.1 switch.
```bash
don@debian:~/HARchiver/hotfix$ opam list lwt
# Available packages for 4.02.1:
lwt  --  A cooperative threads library for OCaml
don@debian:~/HARchiver/hotfix$ opam list --unavailable lwt
# Existing packages for 4.02.1:
lwt  --  A cooperative threads library for OCaml
don@debian:~/HARchiver/hotfix$ opam install lwt.2.4.7
Your request can't be satisfied:
  - No package matches lwt.

No solution found, exiting
don@debian:~/HARchiver/hotfix$ opam show lwt
             package: lwt
             version: 2.4.7
          repository: default
        upstream-url: https://github.com/ocsigen/lwt/archive/2.4.7.tar.gz
       upstream-kind: http
   upstream-checksum: c837ccc92a08b71a86a83d96c55e986f
             depends: ocamlfind >= 1.5.0 & (base-no-ppx | ppx_tools)
             depopts: base-threads | base-unix | conf-libev | camlp4 | ssl | react | lablgtk
   installed-version: 2.4.5 [4.02.0]
  available-versions: 2.3.2, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7
         description: A cooperative threads library for OCaml
This library is part of the Ocsigen project. See:

http://ocsigen.org/lwt
```
This is the output of `opam install --debug lwt.2.4.7`: http://pastebin.com/FXLFDhRd

`opam config report` on the VM (where the bug happens).:
```
# OPAM status report
# opam-version    1.2.0 (cbe460bcb01aef4150084e627701bd16681bf7cb)
# self-upgrade    no
# os              linux
# external-solver no
# criteria        -removed,-notuptodate,-changed*
# jobs            1
# repositories    1* (http)
# pinned          0
# current-switch  4.02.1
# last-update     2015-02-17 07:17
```
And on my dev machine:
```
```

Thank you.

**Comment by AltGr** [comment]
Not really a fix, but until I look into this, it'll probably be solved by installing `aspcud`. The error message is plain wrong though.

Thanks for reporting.

**Comment by SGrondin** [comment]
I can confirm that it works with aspcud. Weird that it doesn't with the base solver, though.
