### ISSUE TITLE
Review the `--json` command-line option

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#2014]
It doesn't seem particularly useful in its current state:

almost useful:
```
$ opam install gg --json=bar
... ok
$ cat bar
[
  [
    {
      "install": {
        "name": "gg",
        "version": "0.9.0"
      }
    }
  ]
]
```

but not so useful:
```
$ opam install xapi --json=foo
The following dependencies couldn't be met:
  - xapi -> cdrom
Your request can't be satisfied:
  - cdrom is not available because your OS doesn't match = linux.

No solution found, exiting
$ cat foo
[]

$ opam install opium --json=foo
[NOTE] Package opium is already installed (current version is 0.13.0).
thomas@piana:~/git/ocaml-cohttp$ cat foo
[]
```

Would be great if all the packages involved were somewhat display in there and the status of their execution. I don't have a more precise spec, but something allowing to script the installation of rev-deps would be good, e.g.

```
$ for i in `opam list -s --rec --depends-on=cohttp`; do echo $i; opam install -y -j 4 $i --json=$i.json; done
$ gather-results *.json
| name | status |
| -------- | -------- |
| foo      | ok |
| bar      | conflict: xxx |
| toto     | error: yyy |
```

**Comment by AltGr** [comment]
Well, this option has been here for a very long time without any use (or tests), so I wouldn't expect it to give interesting output :)
I'll put adding conflicts output on my list. The `already installed` case is more tricky since it stops much before calling the solver or other Json aware functions.

**Comment by AltGr** [comment]
There isn't too much work involved and this may soon become very useful. Proposed format:
```
PACKAGE == { "name" : NAME, "version" : VERSION }
ACTION == { ("install" | "remove") : PACKAGE }
RESULT == {
  "action" : ACTION,
  "result" : ("success" | "failed" | "aborted"),
  "duration" : FLOAT,
  "stdout" : [ STRING ... ],
  "stderr" : [ STRING ... ]
}

{
  "request": {
    "install" : [ PACKAGE ... ],
    "remove" : [ PACKAGE ... ],
    "upgrade" : [ PACKAGE ...],
    "criteria" : STRING
  },
  ( "conflicts" : [ STRING ... ] |
    "solution" : [ ACTION ... ],
    "results" : [ RESULT ... ] )
}
```

@avsm, @samoht anything more that would be nice to have for bulk builds ?

**Comment by AltGr** [comment]
JSON output has now been refactored and should be fairly complete. It could even be used as the basis for an implementation of `opam error` (#2133).
