### ISSUE TITLE
remove on failed build ignores remove instructions

### ISSUE THREAD

**Issue by whitequark** [ocaml/opam#2019]
I have a package ctypes-android with the following description:
```
opam-version: "1"
maintainer: "whitequark@whitequark.org"
homepage: "https://github.com/ocamllabs/ocaml-ctypes"
license: "MIT"
build: [
  ["env" "OCAMLFIND_TOOLCHAIN=android" make "ctypes-cstubs"]
  ["env" "OCAMLFIND_TOOLCHAIN=android" make "install"]
]
remove: [
  ["ocamlfind" "-toolchain" "android" "remove" "ctypes"]
]
depends: [ "base-bytes" "ocamlfind" "ocaml-android" ]
tags: ["org:ocamllabs" "org:mirage"]
ocaml-version: [ >= "4.00.0" ]
messages: [
  "ctypes-android only includes support for cstubs, i.e. no libffi"
]
```

It has failed to build, after which opam decided, on its own, to do `ocamlfind remove ctypes` for whatever reason:
```
ocamlfind install ctypes META CHANGES.md
ocamlfind: Package ctypes is already installed
 - (file /home/whitequark/.opam/4.02.1+32bit/lib/ctypes/META already exists)
Makefile:165: recipe for target 'META-install' failed
make: *** [META-install] Error 2
[ERROR] The compilation of ctypes-android.dev failed.
Removing ctypes-android.dev.
  ocamlfind remove ctypes
```

**Comment by whitequark** [comment]
Oh, nevermind, I had it pinned, and `opam` from a pin overrides `opam` from repository.

Actually, it would be useful to have a flag that prevents that.

**Comment by AltGr** [comment]
Indeed, the repo's `opam` will only get used if there is none in the source. In that case, you should be notified if you made manual changes through `opam pin edit` and the repo's definition was updated though.

`opam show --were` and `opam show --raw` are useful to debug such cases.
