### ISSUE TITLE
`dev-repo:` doesn't allow specifying pinning kind

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam#2026]
With git repos, we usually have `git://` or an end in `.git` that lift the ambiguity, but this is a problem for mercurial for example, where URLs like `https://bitbucket.org/yminsky/planets` have no explicit relationship with mercurial.

Proposed syntax: `dev-repo: "url" {kind}`, e.g.

```
dev-repo: "https://bitbucket.org/yminsky/planets" {hg}
```

This is a file syntax change, so likely not for before 1.3. It would be nice to have a syntactically backwards-compatible workaround in 1.2.1 though.

**Comment by whitequark** [comment]
You could add `dev-repo-hg` as a temporary workaround that doesn't introduce much syntax horror and is easy to recognize.

**Comment by AltGr** [comment]
It has the same problem: opam 1.2 will report an error on an unknown field, and ignore the whole file. (If the file is declared with a different major/minor version, though, it'll acknowledge it may not be aware of the full format and just ignore the unknown or bad syntax field).

Wouldn't something as simple as "hg=https://..." do ?

**Comment by whitequark** [comment]
The usual convention for these things is `hg+https` (`git+ssh` is actually used, IIRC.)

**Comment by whitequark** [comment]
You could actually leave it as `hg+https`, since it is a more or less accepted way.

**Comment by AltGr** [comment]
Ah, of course ! Thanks for the tip
