### ISSUE TITLE
Recompile all dependencies with debugging support.

### ISSUE THREAD

**Issue by jordwalke** [ocaml/opam#2048]
Hello,

Does `OPAM` track which dependencies have been compiled with debugging support (`OPAMDEBUG`/`OCAMLPARAM`)? It's difficult to recall which packages had been installed when debugging flags were enabled (globally, at the time of their compilation of course). In order to build/run some package `X` with debugging support, then how do we ensure that all of `X`'s dependencies have been installed/built/compiled with debugging support?

I know `OPAM` doesn't assume the role of build toolchain, but it does satisfy dependencies, and when building one project for the sake of debugging (or not), whether or not a dependency was compiled with debug support actually does become a kind of dependency itself. I was curious if `OPAM` can help out this part of the development workflow.

**Comment by jordwalke** [comment]
Also, I've not yet heard a great reason for not having the debug flag enabled by default. Could OPAM by default, warn if the flag is not enabled (maybe that's overstepping its bounds a bit, but OPAM seems to be the only unified entrypoint into the build toolchain that I can think of).

**Comment by AltGr** [comment]
This is left to the build scripts / compiler definitions and environment variables at the moment: OPAM does not directly control what build flags packages use. I agree that building everything with debug should be the right thing to do, though.
There is indeed some rationalisation to do in environment variables, compiler flags, etc. In particular if we want to help with cross-compilation at some point. See also open issue #1942

Quite the overkill, and you'll probably end up rebuilding everything, but `opam list --rec --required-by <pkg>` will give you all transitive dependencies, that you can explicitely `opam reinstall`.

**Comment by avsm** [comment]
It may be worth tracking 'significant' environment variables in a more structured way.  We had an interesting bug that took a few hours to track down yesterday.  The Travis OCaml CI scripts were setting `EXTRA_DEPS` to install a dependency, and this was a significant environment variable in the `mirage-xen-minios` package, which promptly failed to build.  Although it would be very hard to automatically find all these variables, it would perhaps be useful to track external variables which propagate through to the build (or even sanitise them for controlled builds, as `sudo` does).

**Comment by jordwalke** [comment]
Is there a way to make `ocamlc/ocamlopt` behave as if the `-g` flag were passed, even if it were not actually passed? This would make many things so much easier because you wouldn't have to hunt down package owners to tell them to add debug flags. Also, sometimes you may not want debug symbols in your binary, and it's kind of a global decision for the top level app to make. An environment variable might be suitable there.

**Comment by AltGr** [comment]
@jordwalke I think you can use `OCAMLPARAM` for that.

Also, the new compiler-package definitions (opam 2.0) allow to specify a `setenv:` field with variables that all dependent packages (and `opam config env`) will inherit. So using `opam pin edit ocaml` (`ocaml` being the wrapper compiler package that every package depends on) and adding the debug flag to `OCAMLPARAM` should guarantee that all your packages get recompiled properly with that flag.

This is getting more technical, but since we now also track files installed by every package, we could also use that to find packages that weren't compiled with debug symbols (use `find` and `file` in your opam prefix to locate non-debug OCaml object files, then `opam search --owns-file` to identify the culprit).

**Comment by jordwalke** [comment]
Thanks for the tip, I didn't know about `OCAMLPARAM`.

**Comment by dra27** [comment]
I think the passage of time has largely dealt with this issue - I'm not sure that there's anything which wants doing in opam which isn't tracked elsewhere (in particular, environment scrubbing, cf. https://github.com/ocaml/opam/issues/4423#issuecomment-876976642 for example).

Please re-open if there's more to discuss!
