### ISSUE TITLE
MacOS lambda-term/lwt install

### ISSUE THREAD

**Issue by vzaliva** [ocaml/opam#2050]
I am trying install lambda-term which depends on lwt.

    #=== ERROR while installing lwt.2.4.5 =========================================#
    # opam-version 1.2.0
    # os           darwin
    # command      ./configure --disable-libev --enable-react --disable-ssl --enable-unix --enable-extra --    enable-preemptive --disable-glib --disable-text
    # path         /Users/lord/.opam/system/build/lwt.2.4.5
    # compiler     system (4.02.1)
    # exit-code    1
    # env-file     /Users/lord/.opam/system/build/lwt.2.4.5/lwt-8855-05296d.env
    # stdout-file  /Users/lord/.opam/system/build/lwt.2.4.5/lwt-8855-05296d.out
    # stderr-file  /Users/lord/.opam/system/build/lwt.2.4.5/lwt-8855-05296d.err
    ### stderr ###
    # ...[truncated]
    # ocamlfind: Package `camlp4' not found
    # W: Failure("Command ''/Users/lord/.opam/system/bin/ocamlfind' query -format %d camlp4 > '/var/folders/hh/h6kt24208xj44z0059_xd9rh0000gn/T/oasis-4aa54c.txt'' terminated with error code 2")
    # ocamlfind: Package `camlp4' not found
    # W: Failure("Command ''/Users/lord/.opam/system/bin/ocamlfind' query -format %d camlp4 > '/var/folders/hh/h6kt24208xj44z0059_xd9rh0000gn/T/oasis-b9a491.txt'' terminated with error code 2")
    # ocamlfind: Package `camlp4.quotations.o' not found
    # W: Failure("Command ''/Users/lord/.opam/system/bin/ocamlfind' query -format %d camlp4.quotations.o > '/var/folders/hh/h6kt24208xj44z0059_xd9rh0000gn/T/oasis-7b2f43.txt'' terminated with error code 2")
    # E: Cannot find findlib package camlp4
    # E: Cannot find findlib package camlp4.extend
    # E: Cannot find findlib package camlp4.quotations.o
    # E: Failure("3 configuration errors")
    =-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
    The following failed
     - install   lwt.2.4.5
    Due to the errors, the following have been cancelled
     - install   lambda-term.1.8

I also tried to install 'ocaml-lwt' via macports. It was installed successfully but opam does not see it.
Here is list of installed packages (opam list):

    # Installed packages for system:
    base-bigarray            base  Bigarray library distributed with the OCaml compi
    base-bytes               base  Bytes library distributed with the OCaml compiler
    base-threads             base  Threads library distributed with the OCaml compil
    base-unix                base  Unix library distributed with the OCaml compiler
    batteries               2.3.1  Community-maintained foundation library
    camlp4          4.02.1+system  Camlp4 is a system for writing extensible parsers
    camomile                0.8.5  A comprehensive Unicode library
    extlib                  1.6.1  A complete yet small extension for OCaml standard
    ocaml-makefile         6.38.0  Easy to use Makefile for small to medium-sized OC
    ocamlfind               1.5.5  A library manager for OCaml
    ocamlsdl                0.9.1  Interface between OCaml and SDL
    react                   1.2.0  Declarative events and signals for OCaml
    zed                       1.4  Abstract engine for text edition in OCaml

**Comment by AltGr** [comment]
This is a package related error, not an OPAM bug, please report to opam-repository

**Comment by vzaliva** [comment]
shouldn't opam see system-install lwt?

**Comment by AltGr** [comment]
System and OPAM libraries live in their own directories: it is discouraged to mix them. In the case where you are using a system compiler, that would be possible, but a nightmare to maintain consistent (OPAM doesn't introspect macports state, and there is no guarantee their 'lwt' packages are equivalent).

You can, however, make OPAM pretend you installed lwt, using `--fake` -- check the FAQ -- but that discouraged and probably won't solve your problem.
