### ISSUE TITLE
opam switch reinstall vs. opam upgrade

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2051]
Apparently, it's not possible to do `opam upgrade` on switch foo and do `opam switch reinstall bar`, while it's possible to upgrade two different switchs concurrently.

**Comment by Drup** [comment]
Apparently, `opam switch reinstall bar` try to acquires the lock on the *current* switch.

**Comment by AltGr** [comment]
Indeed, that's a bug, thanks for noticing!
At the moment the entire switch directory is wiped, which means the lock can't be properly kept though. I'll try and make it more discerning.
