### ISSUE TITLE
curl doesn't want to download cudf

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2052]
When installing opam git:
```
[ -e  cudf-0.7.tar.gz ] || curl  -OL https://gforge.inria.fr/frs/download.php/file/33593/cudf-0.7.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

I can download it manually, but it's a bit annoying.

**Comment by Drup** [comment]
I guess the issue is on the inria forge ? @rdicosmo ?

**Comment by Drup** [comment]
(Same thing for dose)

**Comment by rdicosmo** [comment]
Indeed, that's fishy... 

openssl s_client -connect gforge.inria.fr:https -showcerts > /dev/null
depth=0 OU = Domain Control Validated, CN = gforge.inria.fr
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 OU = Domain Control Validated, CN = gforge.inria.fr
verify error:num=27:certificate not trusted
verify return:1
depth=0 OU = Domain Control Validated, CN = gforge.inria.fr
verify error:num=21:unable to verify the first certificate
verify return:1
DONE

opening an issue on the forge :-)

On Mon, Mar 09, 2015 at 11:32:40AM -0700, Gabriel Radanne wrote:
> I guess the issue is on the inria forge ? @rdicosmo ?
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

-- 
Roberto Di Cosmo
 
------------------------------------------------------------------
Professeur               En delegation a l'INRIA
PPS                      E-mail: roberto@dicosmo.org
Universite Paris Diderot WWW  : http://www.dicosmo.org
Case 7014                Tel  : ++33-(0)1-57 27 92 20
5, Rue Thomas Mann       
F-75205 Paris Cedex 13   Identica: http://identi.ca/rdicosmo
FRANCE.                  Twitter: http://twitter.com/rdicosmo
------------------------------------------------------------------
Attachments:
MIME accepted, Word deprecated
      http://www.gnu.org/philosophy/no-word-attachments.html
------------------------------------------------------------------
Office location:
 
Bureau 3020 (3rd floor)
Batiment Sophie Germain
Avenue de France
Metro Bibliotheque Francois Mitterrand, ligne 14/RER C
-----------------------------------------------------------------
GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3

**Comment by AltGr** [comment]
Indeed, this breaks `make lib-ext` and -- transitively -- the [travis tests](https://travis-ci.org/ocaml/opam/jobs/53746761)
It doesn't break `opam install cudf` because of #2006 -- note that you can now specify any download command though.

**Comment by AltGr** [comment]
If you're on a release, you can get the [opam-full](https://github.com/ocaml/opam/releases/download/1.2.1-rc2/opam-full-1.2.1-rc2.tar.gz) archive that already contains the downloaded lib-ext archives to bypass the problem.

**Comment by rdicosmo** [comment]
It was a mishandling of the CA chain update on the Inria gforge, it should
be fixed in the next few hours...

Sorry for the inconvenience :-)

On Mon, Mar 09, 2015 at 08:00:06PM -0700, Louis Gesbert wrote:
> If you're on a release, you can get the opam-full archive that already contains
> the downloaded lib-ext archives to bypass the problem.
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

-- 
Roberto

**Comment by rdicosmo** [comment]
Fixed now ...

2015-03-10 10:49 GMT+01:00 Roberto Di Cosmo <roberto@dicosmo.org>:

> It was a mishandling of the CA chain update on the Inria gforge, it should
> be fixed in the next few hours...
>
> Sorry for the inconvenience :-)
>
> On Mon, Mar 09, 2015 at 08:00:06PM -0700, Louis Gesbert wrote:
> > If you're on a release, you can get the opam-full archive that already
> contains
> > the downloaded lib-ext archives to bypass the problem.
> >
> > —
> > Reply to this email directly or view it on GitHub.*
> >
>
> --
> Roberto
>



-- 
Roberto Di Cosmo

------------------------------------------------------------------
Professeur               En delegation a l'INRIA
PPS                      E-mail: roberto@dicosmo.org
Universite Paris Diderot WWW  : http://www.dicosmo.org
Case 7014                Tel  : ++33-(0)1-57 27 92 20
5, Rue Thomas Mann
F-75205 Paris Cedex 13   Identica: http://identi.ca/rdicosmo
FRANCE.                  Twitter: http://twitter.com/rdicosmo
------------------------------------------------------------------
Attachments:
MIME accepted, Word deprecated
      http://www.gnu.org/philosophy/no-word-attachments.html
------------------------------------------------------------------
Office location:

Bureau 320 (3rd floor)
Batiment Sophie Germain
Avenue de France
Metro Bibliotheque Francois Mitterrand, ligne 14/RER C
-----------------------------------------------------------------
GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3
