### ISSUE TITLE
REPL use of opam-lib

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#2055]
```
utop # 
#require "opam-lib.client";;
The files /Users/avsm/.opam/mirtls/lib/opam-lib/opam-core.cma and /Users/avsm/.opam/mirtls/lib/re/re.cma disagree over interface Re
```

Is this a known issue?

**Comment by AltGr** [comment]
Hm, no, I do that without trouble ; did you install opam-lib through OPAM or by hand ? Maybe it wasn't recompiled after `re` changed ?

using opam-lib isn't compatible with using `make lib-ext` ; but the Makefile should be clever enough to not accept `make libinstall` at all in that case.
