### ISSUE TITLE
Option to bypass locks

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#2060]
Would be nice to have an option to bypass the locks. While testing mirage apps, the `mirage configure` phase calls `opam install`, so if you happen to run `mirage configure` in `build` you are screwed. 

Would be nice to have an option to give to opam in that case (which can be used directly in the `mirage` tool).

**Comment by AltGr** [comment]
Although it may be tempting to "solve" the issue that way, and it is indeed easy, I really wish we can fine a better way to solve this, and take the opportunity to refine locking behaviour: if there is such an option, people will start using it as soon as locks get in the way, defeating their purpose and opening a whole new world of trouble.

Possibilities:
- Option `--safe` disables write locks, waiting for read locks and any writing or update operation (by failing when attempted) -- it was intended for completion scripts
- Mirage could check if the package is installed first: `opam list -i <package> --safe || opam install <package>`, not failing in case the package is already there
- Similarly, OPAM could be refined to get a read-only lock during query resolution, then a write lock when processing the actions. This way, `--show` or installing an already installed package wouldn't need the write lock at all.
- If you _really_ want to bypass the locks, you always have the option to do `rm -f ~/.opam/lock ~/.opam/<switch>/lock`. Your call :)

**Comment by samoht** [comment]
> Mirage could check if the package is installed first: opam list -i <package> --safe || opam install <package>, not failing in case the package is already there

That will not solve the problem. If you have:

```
build: [
  [ "mirage" "configure" ]
  [ make ]
]
```
The `mirage configure` will result in installing a bunch of package (using `opam install ...`) so you have a problem.

**Comment by samoht** [comment]
In that case, though, you want to use the same lock as the running `opam`. Maybe there should be a way to have re-entrant locks ... (not sure exactly how this could work)

**Comment by AltGr** [comment]
It's not planned to have a reentrant OPAM, and I don't see how that could consistently happen in the future -- so I was under the assumption that, in your case, the packages that `mirage configure` would install have already been installed on the system. Can you not statically extract dependencies from `mirage configure` and add them to the `opam` file ?

opam-installing from an OPAM package may actually work if it is to another switch. But to the same switch, that really is a bad idea :p

**Comment by samoht** [comment]
> Can you not statically extract dependencies from mirage configure and add them to the opam file ?

no, that's what configure is doing: evaluating `config.ml` to find which package needs to be installed and how to initialise the various functors to create the final application, which can varying depending on the library you are using and the backend you are interested in. `mirage configure` generates a Makefile, which will then call opam to install the right dependencies.

I agree that's maybe not what you want to use to release mirage applications. However, that's very useful to test mirage applications using Travis CI. See the hacks that I have to do [here](https://github.com/samoht/mirage-skeleton/blob/e046410a043bfae4170edaf5c08e789c96029b31/.travis.yml) instead of putting the build commands in the opam file.

As everything runs into automated scripts anyway, having an option to bypass the locks is not so bad.

**Comment by AltGr** [comment]
You really want dynamic dependencies then %)
What's the issue with my last suggestion then ? It's equivalent, self-documenting, and doesn't advertise doing it from OPAM.

**Comment by samoht** [comment]
> What's the issue with my last suggestion then ? It's equivalent, self-documenting, and doesn't advertise doing it from OPAM.

Hum, that could indeed work. Need to think how to integrate that nicely in our current test scripts though.

**Comment by AltGr** [comment]
Locks are now much better and should not get in the way. I won't offer an option to bypass, as that could lead to corruption :)
