### ISSUE TITLE
error: at least two arguments expected

### ISSUE THREAD

**Issue by talex5** [ocaml/opam#2062]
Since upgrading to 1.2.1, using the external solver gives:

    # 0opam update
    [WARNING] Running as root is not recommended

    =-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    [default] synchronized from https://opam.ocaml.org
    [WARNING] External solver failed:
	      # opam-version 1.2.1
	      # os           linux
	      # command
	      /.cache/0install.net/injector/exec-9d988f/OPAMEXTERNALSOLVER/OPAMEXTERNALSOLVER
	      # path         /
	      # exit-code    1
	      # env-file     /.opam/log/log-814-05296d.env
	      # stdout-file  /.opam/log/log-814-05296d.out
	      # stderr-file  /.opam/log/log-814-05296d.err
	      ### stdout ###
	      # Default search options for clasp (overwrite with -c):
	      # [...]
	      # Default paths (overwrite with -e, -s, -g, -l, -t):
	      #   encoding :
	      /var/cache/0install.net/implementations/sha1new=5f838f78e489dabc2e2965ba100f14ae8350cbce/misc2012.lp
	      #   clasp    :
	      /var/cache/0install.net/implementations/sha1new=5f838f78e489dabc2e2965ba100f14ae8350cbce/clasp
	      #   gringo   :
	      /var/cache/0install.net/implementations/sha1new=5f838f78e489dabc2e2965ba100f14ae8350cbce/gringo
	      #   cudf2lp  :
	      /var/cache/0install.net/implementations/sha1new=5f838f78e489dabc2e2965ba100f14ae8350cbce/cudf2lp
	      #   TMPDIR   : /tmp/
	      # 
	      # aspcud is part of Potassco : http://potassco.sourceforge.net/#aspcud
	      # Get help/report bugs via   : http://sourceforge.net/projects/potassco/support
	      ### stderr ###
	      # error: at least two arguments expected

    [ERROR] Please retry with option --use-internal-solver

Using the internal solver as requested works. Any idea what causes this?

    [WARNING] Running as root is not recommended
    # OPAM status report
    # opam-version    1.2.1 
    # self-upgrade    no
    # os              linux
    # external-solver no
    # criteria        -removed,-notuptodate,-changed*
    # jobs            4
    # repositories    1* (http)
    # pinned          0
    # current-switch  system*
    # last-update     2015-03-18 10:06

**Comment by talex5** [comment]
Seems it doesn't like absolute paths:

    $ env OPAMEXTERNALSOLVER=/usr/bin/aspcud ./opam-1.2.1-x86_64-Linux update
    ...
    [ERROR] Please retry with option --use-internal-solver

    $ env OPAMEXTERNALSOLVER=aspcud ./opam-1.2.1-x86_64-Linux update
    ...
    Updates available ...

    $ which aspcud
    /usr/bin/aspcud

Is there an easy fix for this?

**Comment by talex5** [comment]
Actually, it doesn't like anything that isn't exactly "aspcud".

**Comment by AltGr** [comment]
You should now provide the full command (from `opam --help`: `Either 'aspcud', 'packup' or a custom command that may contain the variables %{input}%, %{output}% and %{criteria}%`)

If your solver is indeed an instance of aspcud, the full command is simply `"SOLVER %{input}% %{output}% %{criteria}%"`. This adds flexibility since solvers tend to not have the same command-line format.

**Comment by talex5** [comment]
Ah. That's inconvenient for the 0install package. I tried this in the feed:

    <requires importance="recommended" interface="http://repo.roscidus.com/utils/aspcud">
      <executable-in-var name="OPAMEXTERNALSOLVER_BIN"/>
      <environment name="OPAMEXTERNALSOLVER" value="${OPAMEXTERNALSOLVER_BIN} %{input}% %{output}% %{criteria}%"/>
    </requires>

Which runs it with:

    info: OPAMEXTERNALSOLVER=${OPAMEXTERNALSOLVER_BIN} %{input}% %{output}% %{criteria}%
    info: OPAMEXTERNALSOLVER_BIN=/home/tal/.cache/0install.net/injector/exec-6a5950/OPAMEXTERNALSOLVER_BIN/OPAMEXTERNALSOLVER_BIN

But I get:

    [WARNING] External solver failed:
	      # opam-version 1.2.1
	      # os           linux
	      # command      ${OPAMEXTERNALSOLVER_BIN} /home/tal/.opam/log/solver-in-26567-a4abd5
	      /home/tal/.opam/log/solver-out-26567-000417 -removed,-notuptodate,-changed
	      # path         /home/tal/repositories/ocaml/feeds
	      # exit-code    127
	      # env-file     /home/tal/.opam/log/log-26567-70a526.env
	      # stdout-file  /home/tal/.opam/log/log-26567-70a526.out
	      # stderr-file  /home/tal/.opam/log/log-26567-70a526.err

    [ERROR] Please retry with option --use-internal-solver

I assume the variable needs to be expanded before being passed to opam. However, 0install doesn't provide a way to do that (and it's not clear what the escaping rules should be anyway). Wouldn't it be better to have the argument spec in a different parameter, so that `OPAMEXTERNALSOLVER` behaves consistently and there's no need for escaping?

**Comment by AltGr** [comment]
Ah, annoying indeed. The rationale was that it may be specified in `~/.opam/config`'s  `solver:` field, with the same format as the commands in `opam` files -- and the environment variable follows the same format.

What could be done is split between

* a new `solver-bin` OPAM variable (specified through config or environment)
* a `solver-command:` field similar to the current `solver:` field, but that is allowed to reference the `solver-bin` variable, e.g. `solver-command: [ solver-bin input output criteria ]` or `OPAMEXTERNALSOLVERCOMMAND="%{solver-bin}% %{input}% %{output}% %{criteria}%"`. A bit ad-hoc though, as you're unlikely to select another solver without changing the command, and deciding the default values when partially defined becomes quite complex (which is not good).

**Comment by talex5** [comment]
That would solve the problem for me.

[ For the current 0install package of OPAM 1.2.1 I have it add an `aspcud` binary to PATH, but this isn't ideal because when you do `opam config env` opam includes this in the modified path it prints, but without the other variable needed to run it. The result is that the user gets a broken `aspcud` binary in their path. Also, any subprocesses run by opam inherit its aspcud binary. So, I'd rather pass it in an environment variable as before so it only affects opam itself. ]
