### ISSUE TITLE
opam 1.2.1 with fish breaks man command

### ISSUE THREAD

**Issue by talex5** [ocaml/opam#2070]
Under fish, evalling `opam config env` replaces `MANPATH` instead of extending it:

    $ man cp | head -1
    CP(1)                                          User Commands                                         CP(1)
    $ eval (opam config env | sed 's/$/;/g')
    $ man cp
    No manual entry for cp

**Comment by AltGr** [comment]
Indeed, I found out while fixing #2063 and this has been fixed already as part of 496c5a28e85ac9c35ff2d5b8f23f6496bc4e56a5.

Thanks!
