### ISSUE TITLE
`opam` configures package with the wrong options

### ISSUE THREAD

**Issue by planar** [ocaml/opam#2076]
Try this with `opam` version 1.2.1:

```
$ opam install -y ounit.2.0.0 cstruct.1.5.0 osm_xml.0.0.1 async.112.17.00
```
[...]

```
$ opam remove ounit

The following actions will be performed:
  ⊘  remove    async         112.17.00        [uses async_extra]
  ⊘  remove    osm_xml       0.0.1            [uses ounit]
  ↻  recompile cstruct       1.5.0            [uses async]
  ⊘  remove    async_extra   112.17.00        [uses core]
  ⊘  remove    async_unix    112.17.00        [uses core]
  ⊘  remove    async_kernel  112.17.00        [uses core]
  ⊘  remove    core          112.17.00        [required by osm_xml]
  ⊘  remove    custom_printf 112.17.00        [required by core]
  ⊘  remove    core_kernel   112.17.00        [required by core]
  ⊘  remove    pa_bench      112.06.00        [required by core]
  ⊘  remove    pa_ounit      112.17.00        [uses ounit]
  ⊘  remove    ounit         2.0.0    
```

First, I don't understand why opam wants to remove `core` just because another package that depends on it (`osm_xml`) is removed. But let's say the solver's ways are unfathomable.

Then it proceeds to remove all these packages, including `ounit`, and to recompile `cstruct`, but it tries to configures `cstruct` with `--enable-tests`, which it's only supposed to do when `ounit` is available, so it fails.

**Comment by AltGr** [comment]
> First, I don't understand why opam wants to remove core just because another package that depends on it (osm_xml) is removed. But let's say the solver's ways are unfathomable.

The solver is right, indeed, but the reasons printed seem indeed bogus. If you run with `--cudf foo` you'll get a `foo-actions-full.dot` graph that shows all dependencies between actions.
The message _should_ be something like:
```
The following actions would be performed:
  ⊘  remove    async         112.17.00        [uses async_extra]
  ⊘  remove    osm_xml       0.0.1            [uses ounit]
  ↻  recompile cstruct       1.5.0            [uses async]
  ⊘  remove    async_extra   112.17.00        [uses core]
  ⊘  remove    async_unix    112.17.00        [uses core]
  ⊘  remove    async_kernel  112.17.00        [uses core]
  ⊘  remove    core          112.17.00        [uses core_kernel]
  ⊘  remove    custom_printf 112.17.00        [uses pa_ounit]
  ⊘  remove    core_kernel   112.17.00        [uses pa_ounit]
  ⊘  remove    pa_bench      112.06.00        [uses pa_ounit]
  ⊘  remove    pa_ounit      112.17.00        [uses ounit]
  ⊘  remove    ounit         2.0.0    
===== ↻  1   ⊘  11 =====
```

`required by` indeed not being a valid explanation for a removal (only "uses" and "conflicts with" are). I'll see what's going on, thanks for reporting.

![actions-full](https://cloud.githubusercontent.com/assets/807966/6794340/dac26d06-d213-11e4-8dea-e5699b07a666.png)

>  Then it proceeds to remove all these packages, including ounit, and to recompile cstruct, but it tries to configures cstruct with --enable-tests, which it's only supposed to do when ounit is available, so it fails.

I'll check, but something seems wrong indeed, OPAM normally computes the new state and evaluates variables in that context.

**Comment by AltGr** [comment]
Ah! Of course...
I put the graph above to explain the first bug (action reasons) -- but it actually contains the answer to the second one: there is no arrow between cstruct and ounit. The bug is actually in the repository: cstruct should have a `depopt: "ounit"`. Since things happen in parallel, the environment passed to the install of `cstruct` is computed from the original state and only the actions that are _required_ to get there (in this case, only `async` removed) -- that may not be the exact state on disk.

There should be a detection of such cases in `opam lint`: I don't think there is a legit use of referring to a package variable without depending (optionally) on that package. I'll add it.

**Comment by planar** [comment]
There *is* a dependency of `cstruct` on `ounit`, but it's marked `{test}`. What does such a dependency mean? Should it be replaced by a depopt? Should there be a depopt in addition to this one?

**Comment by AltGr** [comment]
A `{test}` dependency is only used when building with `--build-test` (`-t`): it should relate to the `build-test:` commands in the opam file, if any (see doc on `build-test:` and the flags in `depends:` in [the new manual](https://opam.ocaml.org/doc/Manual.html#opam)).

So in the case of `cstruct`, there should either:
* be a `build-test` field that calls again `./configure`, with the `--enable-tests` option
* be, additionally, a depopt on `ounit`. Although in that case tests will be built whenever `ounit` is installed, even if `--build-test` wasn't specified.

A possibility would be to define a `test` variable that is `true` when `-t` is specified, and that is accessible from the build scripts; however, I don't think having both that and the `build-test:` field is a good idea, as they would serve the same purpose.

Note that all this applies similarly to `build-doc:`

**Comment by AltGr** [comment]
Quite similar: #1938 (where I actually promised about a `test` variable already then forgot about it right away, oops -- sorry @samoht)

**Comment by planar** [comment]
Thanks for the explanation! I sent a PR to fix it in opam-repository.
