### ISSUE TITLE
Error when installing under Windows: install "opam.exe", not "opam"

### ISSUE THREAD

**Issue by alainfrisch** [ocaml/opam#2083]
Under Windows, opam-installer complains that src/opam doesn't exist.  Indeed, it should install src/opam.exe instead.  (Same for other executables.) The script produced by `opam-installer -script` works fine (because of Cygwin's magic that allows to refer to opam for opam.exe).

**Comment by AltGr** [comment]
Thanks for the report; I think that is solved in the Windows-specific dev branch
