### ISSUE TITLE
OPAM 1.2.1 & external solver

### ISSUE THREAD

**Issue by Fourchaux** [ocaml/opam#2085]
I was using OPAM (v1.2.0x86_64-Linux) & cudf_remote_proxy without any problem.
With the new version 1.2.1x86_64-Linux (and the same cudf) I have :

$ opam update
...
[WARNING] External solver failed:
          # opam-version 1.2.1
          # os           linux
          # command      cudf_remote_proxy
...
[ERROR] Please retry with option --use-internal-solver

Is there a specific setting to do ?

(also :
$ opam --solver=cudf_remote_proxy
doesn't work. What is the syntax ?)

**Comment by hnrgrgr** [comment]
Same error here, with: ```opam --solver=aspcd```.

```
[WARNING] External solver failed:
          # opam-version         1.2.1
          # os                   linux
          # command              /usr/local/bin/aspcud/aspcud
          # path                 /usr/src
          # exit-code            1
          # env-file             /opt/opam/log/log-6-3bd1cf.env
          # stdout-file          /opt/opam/log/log-6-3bd1cf.out
          # stderr-file          /opt/opam/log/log-6-3bd1cf.err
          ### stdout ###
          # Default search options for clasp (overwrite with -c):
          # [...]
          # Default paths (overwrite with -e, -s, -g, -l, -t):
          #   encoding : /usr/local/bin/aspcud/misc2012.lp
          #   clasp    : /usr/local/bin/aspcud/clasp
          #   gringo   : /usr/local/bin/aspcud/gringo
          #   cudf2lp  : /usr/local/bin/aspcud/cudf2lp
          #   TMPDIR   : /tmp/
          # 
          # aspcud is part of Potassco :
          http://potassco.sourceforge.net/#aspcud
          # Get help/report bugs via   :
          http://sourceforge.net/projects/potassco/support
          ### stderr ###
          # error: at least two arguments expected
```

**Comment by AltGr** [comment]
Can you check if OPAMEXTERNALSOLVER is defined (or if there is a related entry in `$opam/config`) ? This may be the same as #2062

**Comment by AltGr** [comment]
> `$ opam --solver=cudf_remote_proxy` doesn't work. What is the syntax ?

From `opam --help`:
```
       --solver=CMD
           Specify the name of the external dependency solver. The default
           value is aspcud. Either 'aspcud', 'packup' or a custom command that
           may contain the variables %{input}%, %{output}% and %{criteria}%
```
a full command is now expected, for the proxy that would be `--solver='cudf_remote_proxy %{input}% %{output}% %{criteria}%'` ; similarly for the environment variable ; in `$opam/config` that would be:
```
solver: [ "cudf_remote_proxy" input output criteria ]
```

**Comment by hnrgrgr** [comment]
Indeed, in my case this is a duplicate of #2062. There was an environment variable :

   OPAMEXTERNALSOLVER=/usr/local/bin/aspcud

**Comment by hnrgrgr** [comment]
Concerning @Fourchaux 's bug, I have updated [cude-solvers website](http://cudf-solvers.irill.org/index.html) with the new instructions.

**Comment by Fourchaux** [comment]
Ah,  the full command  solves the problem. Merveilleux.

Small note :
$ opam config report

#OPAM status report
#opam-version    1.2.1 
#self-upgrade    no
#os              linux
#external-solver no        <---------    ? ? ?
#criteria        -removed,-notuptodate,-changed*
#jobs            1
#repositories    1* (http)
#pinned          2 (version control)
#current-switch  4.02.1
#last-update     2015-03-26 09:19

**Comment by AltGr** [comment]
```
#external-solver no <--------- ? ? ?
```
that's a bug in 1.2.1, already fixed since. :/

**Comment by Fourchaux** [comment]
great.
