### ISSUE TITLE
the depexts field of an opam file is not enforced

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#2091]
Hello,

sudo aptitude remove libgmp-dev
opam install conf-gmp

this fails in
[ERROR] The compilation of conf-gmp failed at "sh -c cc -c $CFLAGS test.c".

This is the wrong error message.
The correct error message is that the system package libgmp-dev (in my case
and on my machine) is missing.
This is due to the fact that the depexts field was not enforced before the package actions
are taken.
At the very least, opam should warn about the depexts fields which are not satisfied.

**Comment by AltGr** [comment]
There is no depext handling at all built-in opam at the moment ; it only makes the depext metadata available. The `opam-depext` prototype provides a way to handle it, and it is planned to integrate with OPAM at some point ; it's non-trivial to do correctly and needs some OS/distribution specific interactions though -- system packages can be changed or removed at any moment behind OPAM's back. See https://github.com/ocaml/opam/blob/master/doc/design/depexts-plugins for the plans.

The current recommendation is that packages having depexts should also use `post-messages:` to give hints to the user in case of failure. This recommendation is implemented in opam-lint:

```
% opam lint packages/conf-gmp/conf-gmp.1
Errors found in ~/ocamlpro/opam-repository/packages/conf-gmp/conf-gmp.1/opam:
    [...]
    warning 38: Package declares 'depexts', but has no 'post-messages' to help the user out when they are missing
```

**Comment by avsm** [comment]
@altgr maybe an opam FAQ entry to advertise depext?

**Comment by AltGr** [comment]
Already there :D
[FAQ entry](https://opam.ocaml.org/doc/FAQ.html#Somepackagefailduringcompilationcomplainingaboutmissingdependenciesquotm4quotquotlibgtkquotetc)

**Comment by UnixJunkie** [comment]
OPAM should at least warn about the depexts field not being satisfied (this is as grave as
a regular 'depends' not being satisfied: the precondition to install the package is not met).
If users can see the warning, they can take action to install by hand the missing packages right away.
Many opam packagers already took care of listing the correct package names for several distros
in the depexts field.

**Comment by UnixJunkie** [comment]
I think that opam should be able to check necessary system-wide installed packages on at
leat deb and rpm-based linuces plus mac osx with homebrew.

**Comment by AltGr** [comment]
We'll likely see about integration of opam-depext features into opam in 2.1

Note, though, that there is now a warning whenever a package that has depexts fails to install (even if opam has no way to check the depext itself at the moment), e.g.:
```
=-=- conf-sfml2.1 troubleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package relies on external (system) dependencies that may be missing. `opam depext conf-sfml2.1' may help you find the correct installation
   for your system.
```

**Comment by dra27** [comment]
Related to #2426

**Comment by AltGr** [comment]
Merging into #1519
