### ISSUE TITLE
automatic plugin installation

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#2092]
As a followup to #1978, our convention is that `opam plugin` is available as a `plugin` package in OPAM. So if its not installed, how about OPAM attempt to install it?

```
$ opam depext foo
The `depext` plugin is not currently installed.
Would you like to install it?
Y
+ opam install depext
+ ...
Installing external dependencies.
```

This would work for a number of other plugins as well that are all tracked in the db.

**Comment by AltGr** [comment]
Nice idea! Maybe that should only be allowed for packages with a certain flag, to avoid weird behaviour on e.g. `opam lwt`

**Comment by avsm** [comment]
Yep a opam:plugin tag perhaps

**Comment by dbuenzli** [comment]
Le mardi, 31 mars 2015 à 11:41, Anil Madhavapeddy a écrit :
> Yep a opam:plugin tag perhaps

I also suggested in #2046 to use tags to modify the behaviour of opam. It's not clear to me whether this is a good idea or not, but I tend to think it is not.  

It feels like we are missing a broader mechanism to pass arguments from packages to opam, I can see the thing evolve into having `opam:arg(value)` tags at which point it will become evidently cumbersome.  

I think that the tags: field should remain uninterpreted by opam itself.  

I mean we can add new fields to the format itself.

Best,

Daniel

**Comment by AltGr** [comment]
Actually, there is already a `flags:` field (having both `tags:` and `flags:` may be a bit confusing ?) for telling OPAM about specific package behaviour. I do seem to have forgotten them in the [new manual](http://opam.ocaml.org/doc/Manual.html) though, I'll fix that (it's listed in the full [dev-manual](http://opam.ocaml.org/doc/manual/dev-manual.html#sec9) but without explanations). For now we have the following flags:
* `light-uninstall` to explicitely tell OPAM that the source doesn't need to be downloaded for uninstalling (in the hope to replace the hack that infers that from the fact that all uninstall commands are `ocamlfind remove`)
* `all-switches` experimental, for future use, does nothing
* `verbose` prints the build script's stdout to the user

it's a bit experimental (and mostly, undocumented yet) but has been there a while

**Comment by dbuenzli** [comment]
Le mardi, 31 mars 2015 à 14:42, Louis Gesbert a écrit :

> (having both tags: and flags: may be a bit confusing ?)

It's fine with me, tags are for package taxonomy (in the sense browse/search/select by tags). Flags are for signifying something to opam about the package, which is an entirely different business. Though we could maybe call them opam-flags.

Best,

Daniel

**Comment by avsm** [comment]
Agreed on the namespace clash.  It would be good to export `opam-tags` (or `opam-flags` or `flags`) in a structured way into the package taxonomy namespace though.  Perhaps they could be merged in as `opam:<flag>` so that they can be searched on using the tags mechanism as per any user-defined tags.

**Comment by avsm** [comment]
Since 1.2.2 might be our "LTS" release, could I nominate this minifeature as something that would be very useful?

**Comment by avsm** [comment]
It would let us just tell people to do `opam depext` without the installation step.

**Comment by AltGr** [comment]
Ok, on it
