### ISSUE TITLE
Error during pkg.install doesn't run remove commands?

### ISSUE THREAD

**Issue by dsheets** [ocaml/opam#2096]
```
#=== ERROR while installing pkg.0.5.1 ======================================#
Some files in ~/.opam/4.02.1/install/pkg.install couldn't be installed:
  - /home/dsheets/.opam/4.02.1/build/pkg.0.5.1/cmd to /home/dsheets/.opam/4.02.1/bin

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install pkg 0.5.1
No changes have been performed
```

but `ocamlfind query pkg` sure finds it and a bunch of files are in said directory.

The next install fails with

```
# ocamlfind: Package pkg is already installed
#  - (file /home/dsheets/.opam/4.02.1/lib/pkg/META already exists)
```

and then, of course, the remove commands are run and `ocamlfind query pkg` does not find it.

**Comment by AltGr** [comment]
Indeed, that sounds like a bug, OPAM should either just warn and mark the package as installed, or (preferably) fail, remove it and mark as uninstalled.

Thanks for reporting!
