### ISSUE TITLE
opam should not unpack archive in formats it does not understand

### ISSUE THREAD

**Issue by whitequark** [ocaml/opam#2099]
See https://github.com/whitequark/opam-android/issues/4.

This worked on opam 1.1--the opam file includes the steps to unpack the (self-extracting) archive. Now it's broken on 1.2.

**Comment by AltGr** [comment]
So in case it's not a recognised archive, it's just copied to the build directory ? Ok, I can restore this behaviour if it's useful.

**Comment by whitequark** [comment]
Yes.
