### ISSUE TITLE
Depend upon a package with depopts constraint

### ISSUE THREAD

**Issue by trevorsummerssmith** [ocaml/opam#2100]
Hello,
I would like to depend on cohttp that has been build with its optional dependency async_ssl. I could not find anywhere online that this is a thing one can do. Can one currently do this? If not, are there work arounds and is there interest in discussing this feature?
Thanks
Trevor

**Comment by Drup** [comment]
You can depends on async_ssl directly.

**Comment by trevorsummerssmith** [comment]
Thanks @Drup. I had a misunderstanding of the depopts field in Opam: I incorrectly thought that the depopts field in a package was installed only if the package was installed prior to the dependent package. I see this is incorrect, and that a depopts package will reinstall already installed packages. Please feel free to close the ticket.
