### ISSUE TITLE
Wildcards in version constraints

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam#2102]
Not sure exactly where this fits, but it would seem worthwile UI-wise. I also wonder if the Mancoosi team (@rdicosmo, @abate) has already examined such a feature, which seems likely.

It is common for a package to depend on a major or minor version of another package. At the moment, the meaning is clear, but the syntax is a bit awkward, since for depending on any version in the `1.2` branch, one has to write `{ >= "1.2" & < "1.3" }` ; it's also slightly inaccurate since `1.3~beta` would fit in this range (but that shouldn't be a problem if we rather expect `1.3.0~beta`, which doesn't)

So I'm wondering what the impact of having a syntax like `{ = "1.2.*" }` (or less intuitively, but more consistently, `{ =~ "1.2" }`, with the `=~` operator defined as "prefix match") would be ? We could automatically translate that into a range referring to existing package versions before passing to the solver.

**Comment by abate** [comment]
I don't think that adding a bit of syntactic sugar so { = "1.2.*" } means exactly  { >= "1.2" & < "1.3" } is a problem. However adding { = "1.2.*" } meaning "all versions starting with the prefix 1.2" would mess up the version ordering. Maven dependencies uses this kind of constraints. Since we can't express these constraints with a total order, we ended up expanding all dependencies, generating huge cudfs. I would vote against transforming the comparing function in a way that the ordering function is not total, but it won't hurt adding a bit of syntactic sugar to make it easier for users to express their version constraints.

**Comment by Drup** [comment]
Is this related to the possibility of allowing { =~ "*+foo" } that would accept all versions that are of the "foo" variety ?

**Comment by rdicosmo** [comment]
I fully sustain Pietro's remark: adding syntactic sugar is ok, _but_ it
must be encodable into current CUDF constraints with little size increase.

So, a shorthand for { >= "1.2" & < "1.3" } is perfectly fine, but a
shorthand for "all version numbers with prefix 1.2-" is dangerous (may
expand into dozens of constraints)

2015-04-06 10:40 GMT+02:00 abate <notifications@github.com>:

> I don't think that adding a bit of syntactic sugar so { = "1.2.*" } means
> exactly { >= "1.2" & < "1.3" } is a problem. However adding { = "1.2.*" }
> meaning "all versions starting with the prefix 1.2" would mess up the
> version ordering. Maven dependencies uses this kind of constraints. Since
> we can't express these constraints with a total order, we ended up
> expanding all dependencies, generating huge cudfs. I would vote against
> transforming the comparing function in a way that the ordering function is
> not total, but it won't hurt adding a bit of syntactic sugar to make it
> easier for users to express their version constraints.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocaml/opam/issues/2102#issuecomment-89977434>.
>



-- 
Roberto Di Cosmo

------------------------------------------------------------------
Professeur               En delegation a l'INRIA
PPS                      E-mail: roberto@dicosmo.org
Universite Paris Diderot WWW  : http://www.dicosmo.org
Case 7014                Tel  : ++33-(0)1-57 27 92 20
5, Rue Thomas Mann
F-75205 Paris Cedex 13   Identica: http://identi.ca/rdicosmo
FRANCE.                  Twitter: http://twitter.com/rdicosmo
------------------------------------------------------------------
Attachments:
MIME accepted, Word deprecated
      http://www.gnu.org/philosophy/no-word-attachments.html
------------------------------------------------------------------
Office location:

Bureau 320 (3rd floor)
Batiment Sophie Germain
Avenue de France
Metro Bibliotheque Francois Mitterrand, ligne 14/RER C
-----------------------------------------------------------------
GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3

**Comment by clarus** [comment]
I have checked what the `npm` people do: [npm/semver](https://docs.npmjs.com/misc/semver). They have two syntaxes:

* `~a.b.c` for `>= a.b.c & < a.(b+1).0`
* `^a.b.c` for `>= a.b.c & < (a+1).0.0`

and forbid to install a version with letters if the constraint does not yet include letters (see [prerelease-tags](https://docs.npmjs.com/misc/semver#prerelease-tags)).

I wonder how this could integrate with the total ordering of OPAM. Hoping that there are in practice in small finite number of versions with letters, would adding explicit `!= 1.3~beta` for each version with letters make sense for the solver?

**Comment by AltGr** [comment]
hmm, interesting, thanks! That doesn't seem flexible enough for our more general versionning though.
One possibility could be to have a wildcard char meaning "the set of versions between that version with the last [chunk](http://opam.ocaml.org/doc/Manual.html#PackageFormulas) (included) and that + 1 (excluded)". Then `= "1.2*"` (or maybe more consistently, something like `=* "1.2"`) would mean `>= "1.2" & < "1.3"` ; `= "1.2.*"` would mean `>= "1.2." & < "1.2/"` (ascii order).

Of course wildcards like `*~beta` would be completely different: they can only enumerate on _existing_ versions at any given time. This results in lots of expansion that may make version formula handling much more complex... You can always add constraints manually for each known `~beta` version.

all in all, it might be a little verbose now but the semantics are clear: I am not sure the above would be worth the added complexity.

**Comment by AltGr** [comment]
Closed in favor of #2976
