### ISSUE TITLE
coq build fails on netbsd: gmake issue

### ISSUE THREAD

**Issue by azarens** [ocaml/opam#2104]
The configure script fails to run when coq 8.4.5 is being built on a NetBSD box.  The issue lies in that the opam sets the build build process such that an attempt to invoke a make command as `make` is made, even when the packages expects a GNU Make.  The fix is easy: just add `-makecmd gmake` option to the configure script and also replace invocations of `make` with `gmake` when on BSD.

Thus, we should have in the recipe:
```
build: [
  ["./configure" "-makecmd" "%{make}%" "-configdir" "%{lib}%/coq/config" "-mandir" man "-docdir" doc "--prefix" prefix "--usecamlp5" \
"--camlp5dir" "%{lib}%/camlp5" "--coqide" "no"]
  ["%{make}%" "-j%{jobs}%" "world"]
  ["%{make}%" "-j%{jobs}%" "states"]
  ["%{make}%" "install"]
]
```

The build succeded on my box once this adjustment was introduced.

Please adjust the recipe accordingly.

**Comment by AltGr** [comment]
This should probably be posted on [opam-repository](https://github.com/ocaml/opam-repositories/issues) since it is a packaging error.

Note that you can write `make` instead of `"%{make}%"` :)
