### ISSUE TITLE
Untangle library initialisation

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam#2106]
This issue is actually mostly to document what I am currently doing.

## Issue

`opam-core:OpamGlobals` includes many global references used for configuration. These are first initialised using the environment or default values, and then updated throughout, mostly in `opam-client:OpamArg`. Some of them may be loaded from the global configuration file, which happens in `opam-client:OpamState.load_state` ; since the file has actually lowest priority, we need to keep track of whether the value has been already set or not (either using an auxiliary reference, or an option and an accessor function resolving to the default value if needed).

This is also a big problem for library use of `opam-core`: these variables concern every part of OPAM, even the client ; so you need to sort out the meaningful ones, and initialise them by hand if you want to control their values e.g. using command-line argument. Also, it's not obvious if or when new configuration variables are added. And the only way to circumvent environment variables like `OPAMDEBUG` is to re-set them (annoying in tools nesting calls like `opam-rt` calling instances of `opam`).

We have already been hit, for example, by bugs in tools using `opam-core` but not directly related to the OPAM installation (e.g. `opam-installer`) failing if you didn't have a `~/.opam/log` available, or spawning log files in the wrong places.

## How I'm improving

 1. Better separation between the OPAM libraries
 2. No initialisation done at module load
 3. Configuration values stored in records, with a single global reference

The idea is to have a configuration module at the root of each library, with a similar structure: a private record type, a default value (using lazy fields in case it includes any computation), a global reference and an update function, with an optional argument per field in the record.

Higher up in the library hierarchy may sit an `init_config` function that provides initialisation using the environment variables and optional arguments.

In practice, only a few meaningful global configuration variables remain in `opam-core`, mostly related to logging ; there is no dependency to the OPAM root anymore. Most of them, including OPAMROOT, are now in `opam-client` since they are related to the user query -- some of which should probably not be in the global conf at all, but that's a different subject. And a few moved to `opam-solver` and `opam-repositories` (which now includes the download functions).

## Current state

It took me a while to sort all this out, but I got back to a compiling and working OPAM ; likely with a few regressions at the moment though, I still have a few rough edges to polish and testing to do.

**Comment by AltGr** [comment]
I'm also considering splitting core into
 1. The general-purpose modules (misc, system, console, etc.)
 2. The OPAM infrastructure (lexer, parser, OpamFormat, OpamFile)

But this one patch is already going to be huge enough.

The hierarchy below `~/.opam/` is currently only used by `opam-client`, and I have already moved `OpamPath` there.

**Comment by avsm** [comment]
Can you get rid of "misc" while you are there? A slightly more specific module name is always handy :)

**Comment by dbuenzli** [comment]
Don't know if that may help but I solved similar problems in the library for developping drivers in assemblage  see [here](https://github.com/samoht/assemblage/blob/master/lib-driver/assemblage_driver.mli#L65-L104).

**Comment by AltGr** [comment]
@avsm sure, I already put all its contents into submodules anyway (e.g. `OpamMisc.String` rather than functions that are _implicitely_ on strings). How about `OpamStd` ?

@dbuenzli thanks! That could have been handy but I've already done that step ; also, I'd like to avoid a dependency towards cmdliner for the libs -- although exporting Args could be handy for tools

@samoht where and how is `opam-admin findlib` used ? I'd like to get it out of `opam-admin`, since it depends on `opam-client` (and on an initialised OPAMROOT) while all the other commands only rely on a repository hierarchy, and I am trying to make the distinction clear.

**Comment by samoht** [comment]
>  where and how is opam-admin findlib used ? I'd like to get it out of opam-admin, since it depends on opam-client (and on an initialised OPAMROOT) while all the other commands only rely on a repository hierarchy, and I am trying to make the distinction clear.

It is supposed to run manually for now on, but at one point we would like to run automatically on every PR of opam-repository. The goal is to help `codoc` generating documentation sorted by ocamlfind packages.

**Comment by AltGr** [comment]
Ok, so it won't break anything if I make it separate (or better yet, not use OPAMROOT, if possible)

**Comment by AltGr** [comment]
Branch now public at https://github.com/ocaml/opam/commits/1.3 :)

**Comment by AltGr** [comment]
162 files changed, 7451 insertions(+), 6241 deletions(-)
:D

**Comment by AltGr** [comment]
@samoht, since 97a2274d49b58624092ca01e5a39643413a78900, the core is really small and independent of any OPAM datastructures (see [the modules file](https://github.com/ocaml/opam/blob/1.3/doc/modules) for details). So if you wanted to use opam's parallel engine as a library, that should now be fine !

Initialisation requires [`OpamSystem.init()`](https://github.com/ocaml/opam/blob/97a2274d49b58624092ca01e5a39643413a78900/src/core/opamSystem.ml#L655-L659) (to set up proper signal handlers), and look at [`opamCoreConfig.mli`](https://github.com/ocaml/opam/blob/1.3/src/core/opamCoreConfig.mli) for details on the global options (`OpamStd.Config.init()` takes care of initialising them from the environment variables).

The only dependencies are Unix, OCamlGraph, Re and Jsonm (Jsonm could actually be removed as well).

**Comment by samoht** [comment]
That's great, thanks! Still a bit convoluted to have to install opam-core to use a parallel library, but that's much better than the previous state!

**Comment by AltGr** [comment]
opam-core is actually really close to the minimum you need for OpamParallel now -- so it's mostly a matter of naming and git repositories: stdlib, logging, system and parallel
