### ISSUE TITLE
Adding support for "as fresh as possible" installations

### ISSUE THREAD

**Issue by rdicosmo** [ocaml/opam#2109]
The current implementation of opam, when calling the external solver, is unable to obtain solutions that give preference to fresher packages (it only supports, using the -notuptodate measure, giving preference to the latest version). This issue is raised again and again all over the place, see #2108 and #1897.

It is pretty easy to give priority to fresher versions when the latest is impossible to install, with no changes to the solver, as follows:

   - for each package, add in the generated CUDF an integer field
         penalty: 
     with value equal to the number of versions it lags behind the latest one available
  
    For example, if package foo has version 3.1 4.2 5.6 and 5.7, then 3.1 has penalty 3,
    4.2 has penalty 2, 5.6 has penalty 1 and 5.7 has penalty 0

  - add the user preference "-sum(solution, penalty)" when calling the solver

and that will do it ... of course, on the academic side, we know this will not be "perfect" in all cases, but in practice it will make a hell of a difference.

A side note, as always: there are no "quirks" in the external solvers.... aspcud/packup and the like *really* return a solution that is optimal according to the criteria passed to them. The issue is to find the right criteria/preferences to obtain what we have in mind :-)

**Comment by avsm** [comment]
This would be *extremely* useful!  With the increasing number upper bounds, the current criteria do return the lowest package quite often when packages are downgraded.  Thanks very much for explaining how to generate more optimal criteria...

**Comment by rdicosmo** [comment]
Great! Looking forward to see an implementation around :-)

On Tue, Apr 14, 2015 at 05:42:01AM -0700, Anil Madhavapeddy wrote:
> This would be *extremely* useful! With the increasing number upper bounds, the
> current criteria do return the lowest package quite often when packages are
> downgraded. Thanks very much for explaining how to generate more optimal
> criteria...
> 
> > On 14 Apr 2015, at 13:37, Roberto Di Cosmo <notifications@github.com> wrote:
> >
> > The current implementation of opam, when calling the external solver, is
> unable to obtain solutions that give preference to fresher packages (it only
> supports, using the -notuptodate measure, giving preference to the latest
> version). This issue is raised again and again all over the place, see #2108
> <https://github.com/ocaml/opam/issues/2108> and #1897 <https://github.com/ocaml
> /opam/issues/1897>.
> >
> > It is pretty easy to give priority to fresher versions when the latest is
> impossible to install, with no changes to the solver, as follows:
> >
> > for each package, add in the generated CUDF an integer field
> > penalty:
> > with value equal to the number of versions it lags behind the latest one
> available
> >
> > For example, if package foo has version 3.1 4.2 5.6 and 5.7, then 3.1 has
> penalty 3,
> > 4.2 has penalty 2, 5.6 has penalty 1 and 5.7 has penalty 0
> >
> > add the user preference "-sum(solution, penalty)" when calling the solver
> > and that will do it ... of course, on the academic side, we know this will
> not be "perfect" in all cases, but in practice it will make a hell of a
> difference.
> >
> > A side note, as always: there are no "quirks" in the external solvers....
> aspcud/packup and the like really return a solution that is optimal according
> to the criteria passed to them. The issue is to find the right criteria/
> preferences to obtain what we have in mind :-)
> >
> > —
> > Reply to this email directly or view it on GitHub <https://github.com/ocaml/
> opam/issues/2109>.
> >
> 
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

-- 
Roberto Di Cosmo
 
------------------------------------------------------------------
Professeur               En delegation a l'INRIA
PPS                      E-mail: roberto@dicosmo.org
Universite Paris Diderot WWW  : http://www.dicosmo.org
Case 7014                Tel  : ++33-(0)1-57 27 92 20
5, Rue Thomas Mann       
F-75205 Paris Cedex 13   Identica: http://identi.ca/rdicosmo
FRANCE.                  Twitter: http://twitter.com/rdicosmo
------------------------------------------------------------------
Attachments:
MIME accepted, Word deprecated
      http://www.gnu.org/philosophy/no-word-attachments.html
------------------------------------------------------------------
Office location:
 
Bureau 3020 (3rd floor)
Batiment Sophie Germain
8 place Aurélie Nemours
Metro Bibliotheque Francois Mitterrand, ligne 14/RER C
-----------------------------------------------------------------
GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3

**Comment by samoht** [comment]
That's a great idea! I think in that case it would even be better to have an exponential penalty so that it's better to have two almost up-to-date packages than one very old.

**Comment by AltGr** [comment]
Awesome, it's that simple ! Thanks!
Does that work even with older versions of aspcud / packup ?
Implementing should be a matter of hours, maybe a bit more if we need to keep a backwards-compatible version.

> A side note, as always: there are no "quirks" in the external solvers

I know! hence the tone of my question :)
There are cases where the criteria don't allow to discriminate among equivalent solutions, though. I have no trouble understanding several reasons why introducing a biased way to pick one in that case would be a bad idea (feels like hiding a bug rather than solving it the right way). But the _temptation_ is always there :D. Anyway, since there _is_ after all a way to specify this in Cudf, everythingis cool!

Actually if that works well that could be a good candidate for backport and an incentive to release a 1.2.2

@samoht: sounds like a good idea, but I would be cautious of adding any extra cleverness in the mechanism, it may make solutions (even more) difficult to understand, and fixing/improving suff more difficult. Also, there will always be a bias depending on the metric (number of intermediate versions ? Age ? Delay with the latest release ? Proportionate to the package's number of versions ? It's release frequency ?). Not at all saying we shouldn't do it -- but I'd rather plan ahead and have it as simple as possible until we have something sound.

**Comment by rdicosmo** [comment]
Yes , the "sum" criterium is old and was supported in aspcud 1.8 afair

Roberto Di Cosmo (via mobile/cell)

**Comment by rdicosmo** [comment]
Great, if you can create a test branch, the only functionality  you need to
code is the addition of the penalty field to the cudf file.

Everything else can be simply added to the user preferences, and we may
need to experiment a bit before finding the right default to use for
install/upgrade

Roberto Di Cosmo (via mobile/cell)

**Comment by rdicosmo** [comment]
An alternative name, instead of penalty, could be "versionlag", which is more true to the content of the field.

We may keep "penalty" for an overall computed penalty field where we can play with ideas like @samoht's exponential values (dangerous, in principle, as we can get a lot of artifacts in the solution, but worth experimenting)

**Comment by AltGr** [comment]
Done! Quite straight-forward :)

Note that I took a conservative approach in the default solver criteria: I kept the `-notuptodate` in front of the `-sum(version-lag)`, so it should really only change anything in the problematic cases we had. The criteria list is starting to get a bit too long though:
```
let default_criteria_latest = {
  crit_default = "-count(removed),\
                  -notuptodate(request),-sum(request,version-lag),\
                  -count(down),\
                  -notuptodate(changed),-count(changed),\
                  -notuptodate(solution),-sum(solution,version-lag)";
  crit_upgrade = "-count(down),\
                  -count(removed),\
                  -notuptodate(solution),-sum(solution,version-lag),\
                  -count(new)";
  crit_fixup = "-count(changed),\
                -notuptodate(solution),-sum(solution,version-lag)";
}
```

**Comment by AltGr** [comment]
(the above snippet is now in `src/solver/opamSolverConfig.ml`)

**Comment by rdicosmo** [comment]
A little step forward in the code, a huge leap forward in user satisfaction

Roberto Di Cosmo (via mobile/cell)

**Comment by avsm** [comment]
+1 !

**Comment by samoht** [comment]
A good side-effect of this feature is that it can help us test the lower bounds in Travis CI, by setting `+sum(solution,version-lag)"`.

**Comment by rdicosmo** [comment]
Indeed :-)

2015-04-16 10:31 GMT+02:00 Thomas Gazagnaire <notifications@github.com>:

> A good side-effect of this feature is that it can help us test the lower
> bounds in Travis CI, by setting +sum(solution,version-lag)".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocaml/opam/issues/2109#issuecomment-93677691>.
>



-- 
Roberto Di Cosmo

------------------------------------------------------------------
Professeur               En delegation a l'INRIA
PPS                      E-mail: roberto@dicosmo.org
Universite Paris Diderot WWW  : http://www.dicosmo.org
Case 7014                Tel  : ++33-(0)1-57 27 92 20
5, Rue Thomas Mann
F-75205 Paris Cedex 13   Identica: http://identi.ca/rdicosmo
FRANCE.                  Twitter: http://twitter.com/rdicosmo
------------------------------------------------------------------
Attachments:
MIME accepted, Word deprecated
      http://www.gnu.org/philosophy/no-word-attachments.html
------------------------------------------------------------------
Office location:

Bureau 320 (3rd floor)
Batiment Sophie Germain
Avenue de France
Metro Bibliotheque Francois Mitterrand, ligne 14/RER C
-----------------------------------------------------------------
GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3

**Comment by avsm** [comment]
I just had a successful downgrade to the latest-valid version of Core. This feature is a roaring success in my book @rdicosmo @AltGr!

@samoht I could set that in the bulk builds perhaps...

**Comment by samoht** [comment]
@avsm can at least add the right env variable to one of the Travis build in opam-repository.

**Comment by avsm** [comment]
Sounds good to me.  Not sure what that env variable is exactly, but I've refreshed the PPA in avsm/ppa-opam-experimental with a 1.2.2 snapshot, so it can be added any time.

**Comment by rdicosmo** [comment]
Nice to hear this !
Happy up/downgrading :-)

On Fri, Apr 17, 2015 at 07:07:30AM -0700, Anil Madhavapeddy wrote:
> I just had a successful downgrade to the latest-valid version of Core. This
> feature is a roaring success in my book @rdicosmo @AltGr!
> 
> @samoht I could set that in the bulk builds perhaps...
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

-- 
Roberto

**Comment by Drup** [comment]
> A good side-effect of this feature is that it can help us test the lower bounds in Travis CI, by setting +sum(solution,version-lag)".

After having experienced this (by accident) for llvmgraph, I think it's rather a good idea! You need to test both the lower and upper bounds, though.
