### ISSUE TITLE
OPAM 1.2.1 Installation Fails on Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by AGIsmail** [ocaml/opam#2110]
Hi, 

I tried installing opam using the full archive located at [1] on Ubuntu Trusty but it keeps kicking an error saying ocamlfind doesn't exist.
I'm following these steps:
1) apt-get install build-essential m4 ocaml ocaml-native-compilers camlp4-extra
2) wget [1] & tar -zxvf
3)  ./configure, then make lib-ext, then make
4) make install gives the error:
make: ocamlfind: Command not found
src/opam-installer --prefix /usr/local --mandir /usr/local/share/man opam.install
src/opam                         => /usr/local/bin/opam
src/opam-admin                   => /usr/local/bin/opam-admin
src/opam-installer               => /usr/local/bin/opam-installer
5) ocamlfind exists:
username@pc:~/Folder$ ocamlfind
Usage: ocamlfind query        [-help | other options] <package_name> ...

If it's any help, I had opam 1.2.0 installed using:
add-apt-repository ppa:avsm/ppa
apt-get update
apt-get install ocaml ocaml-native-compilers camlp4-extra opam

I uninstalled 1.2.0, and as much as I could before trying to install 1.2.1, but it still gets stuck here.
I tried the above steps on a Debian 3.18 and it works fine.

Thanks!

Links:
[1] https://github.com/ocaml/opam/releases/download/1.2.1/opam-full-1.2.1.tar.gz

**Comment by AltGr** [comment]
That's very weird... ocamlfind is detected by ./configure and won't be used if absent; in your case it's present and detected, but I can't figure why the Makefile would return `command not found`.

Anyway, it still went on and the following messages seem to indicate that OPAM was installed successfully.

**Comment by AGIsmail** [comment]
Yes, that's true, OPAM exists.

I thought I'd be a good samaritan and post the issue either way in case it helps y'all in any way. I'd be happy to assist if you need any logs, a platform to experiment on etc.

Cheers.

**Comment by AltGr** [comment]
Indeed, thanks for reporting! Here it's harmless enough (the Makefile only calls ocamlfind to detect if you use a special OCaml lib dir, and install the libraries there when you do `make libinstall`. It's not even used by `make install`). I still don't understand why it happened though. The call is done as such:
```
      LIBINSTALL_DIR ?= $(shell $(OCAMLFIND) printconf destdir)
```
might the `$(shell)` make command use a different PATH ?

**Comment by AGIsmail** [comment]
I'm not sure if I understood your correctly, so I may have went off on a tangent.
I added this at the end of the makefile: print-%  : ; @echo $* = $($*)
Running make print-LIBINSTALL_DIR gives the correct folder where ocamlfind is located: 
username@pc:~/Folder$ make print-LIBINSTALL_DIR
LIBINSTALL_DIR = /home/folder/folder/.opam/system/lib

If the same command is run showing OPAMINSTALLER_FLAGS, it gives the prefix, man and lib folders.

However, if we print the flags or lib dir using 'make install print-' the lib dir is an empty string and the flags var does not contain the library directory, which I think is the point. 

So far, I'm not sure, where and why opam.install calls OCAMLFIND/ocamlfind either, but it seems like it is, any ideas?

**Comment by AGIsmail** [comment]
Successfully installed on an Ubuntu VM using the exact same steps.
Must be related to the system policies enforced on the other PC.
Since this is not an issue with opam, I'll be closing this ticket.
Thanks for all your help.
Cheers!
