### ISSUE TITLE
`--external` output is clobbered when querying pinned package

### ISSUE THREAD

**Issue by ivg** [ocaml/opam#2139]
I usually install external dependencies with the help of opam:
```
$ sudo apt-get install `opam install <pkg-name> -eubuntu`
```
But with the latest opam it stopped to work, due to a fancy output:

```
=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[bap.master] Synchronizing with /home/ivg/factory/bap
```
(BTW, spell-checker suggests me to use "Synchronizing")

So now, I have:
```
$ PKGS=`opam install bap -e ubuntu`
$ echo $PKGS
=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= [bap.master] Synchronizing with /home/ivg/factory/bap clang libcurl4-gnutls-dev libgmp-dev libzip-dev llvm llvm-3.4-dev m4 time
```

Unfortunately everything is written into standard output, so redirecting doesn't help. 

I don't know about your policies about printing stuff, but one of the solutions would be to output all logging and user interacting stuff into stderr, so that `opam` can still be used in scripts.

**Comment by avsm** [comment]
The best way do this now is to use `opam depext` (and `opam install depext` first if using opam<1.2.2dev).  The old tag syntax is from OPAM 1.1 and has an equivalent in OPAM 1.2 if you run `opam depext` with the `-d` flag:

e.g.:
```
opam list --safe --recursive --external=x86_64,osx,homebrew --required-by=foo
```

**Comment by ivg** [comment]
Wow, `depext` works like a charm!
 
I've tried to use `installext` yesteday, but it fails with the same issue, as I described, i.e., chokes on `=-=-=-`. Btw, should I report the issue to `installext` or it is deprecated?

**Comment by avsm** [comment]
installext is deprecated, but an issue would still be useful there to remind me to deprecate it :)

**Comment by ivg** [comment]
actually it was already reported avsm/opam-installext#4 :)

**Comment by avsm** [comment]
opam-installext now marked as deprecated in opam and its README.  Thanks for the reminder!
