### ISSUE TITLE
Interactive behaviour

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#2140]
It seems that opam now automatically interprets my inputs without waiting for me to validate them (i.e. enter a newline). I personally don't like this behaviour. It gives you no chance to correct a possibly wrong input.

**Comment by dbuenzli** [comment]
Just as anecdotal evidence I don't think there any command line tool that I use that behaves that way (e.g. at least `cp`, `mv`, `git`, `ssh` come to mind).

**Comment by Drup** [comment]
If you are talking about "typing Y immediately validates a choice", `pacman`, the Arch linux package manager, does that as well (and I personally rather like it, but I can understand why someone wouldn't).

**Comment by dbuenzli** [comment]
> (and I personally rather like it, but I can understand why someone wouldn't).

Mmmh maybe it's something to get used to (think before you type..., rather than think before you validate) but in general I prefer when the UIs I use are consistent. And in some sense the single keystroke validation is already available through the default. 

To take a GUI button analogy the keystroke + validation is akin to being able to mousedown a button but cancel its actuation by moving out of the button before mousing up. With this analogy the current behaviour would correspond to a button that actuates as soon as you mousedown on it.

I think these kind of autovalidating UIs are best for things like incremental search and/or immediate feedback parameter tweaking (think sliders) and less for launching potentially huge, side effectful computations.

**Comment by dbuenzli** [comment]
Since we have been living with this for more than a year I don't think its worth changing back again.
