### ISSUE TITLE
pin git mixed mode breaks some pin workflows

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#2141]
It seems that in git mixed mode, the `git` directory is not present in the "checkout". This is annoying since it breaks version watermarking systems and pin workflows that are based on detecting whether the git repo is here (okay maybe it shouldn't do it this that way).

**Comment by dbuenzli** [comment]
> (okay maybe it shouldn't do it this that way)

Well in general there's a function that must be applied on a checkout to get to a distribution/buildable state so it feels natural to detect it that way.

**Comment by AltGr** [comment]
Indeed, only the tracked files are rsync-ed. We can add the VC dir too.

**Comment by samoht** [comment]
rsyncing the whole `.git` sub-diir might be slow. But maybe in mixed mode we don't care.

**Comment by AltGr** [comment]
It's indeed quite slow, at least the first time around...

**Comment by dbuenzli** [comment]
Don't have the commands but maybe clone + pull + generate a patch of the dirtyness in the source and apply the dirtyness to clone ?

**Comment by AltGr** [comment]
@dbuenzli hm, that could work, but the current implementation works in the same way for mercurial and darcs too; not sure it'd be as easy to implement such a mechanism for all of them. I'll use the current setup for a while and see if there are more issues or if it is really too slow.

**Comment by AltGr** [comment]
In the git case, `git clone --no-checkout` to get only the `.git` dir, then rsync would work too.

**Comment by dbuenzli** [comment]
This doesn't appear to be the case only in mixed mode but also on local git pins. Did the fix make it in opam 1.2.2 ?

**Comment by AltGr** [comment]
No, it wasn't in time for 1.2.2. It shouldn't affect non-mixed local git pins (i.e. with a branch set) though: those are simply done with a `git clone`.

About the speed of rsync: wouldn't it actually be more clever to clone/update normally _then_ rsync the work dir, always ? It would add a bit of work when you edit files while staying on the same commit, but that shouldn't be a big problem.

**Comment by dbuenzli** [comment]
> It shouldn't affect non-mixed local git pins (i.e. with a branch set) though: those are simply done with a git clone.

What do you mean by "branch set", what I did is `opam pin add -kgit bla bla` in my mental model this shouldn't be mixed mode.

**Comment by dbuenzli** [comment]
> what I did is opam pin add -kgit bla bla

Mmh now that I read the manual it seems that this *will* be mixed mode. I think it's bad, I thought that 
`-kgit` would have enforced non-mixed mode and that mixed mode would have been e.g. `-kmixed` or `-kgit-mixed`

**Comment by dbuenzli** [comment]
Also it would be nice to indicate mixed mode in `opam pin list` what I realize now is that some of these supposedly `git` pins are `mixed-mode`, `opam` is lying to me.

**Comment by AltGr** [comment]
damn, I thought I had been clear in the doc from the beginning that mixed mode was incurring for _git_ pins, whenever on a local directory _and_ without a branch set: there is no "mixed mode option".
If even you didn't get it properly... :/

**Comment by AltGr** [comment]
For my defense ;)
```
% opam pin add -k git bla some/git/dir
Package bla does not exist, create as a NEW package ? [Y/n] y
bla is now git-pinned to /home/me/some/git/dir
[NOTE] Pinning in mixed mode: OPAM will use tracked files in the current working tree from
       /home/lg/ocamlpro/ocp-indent. If this is not what you want, pin to a given branch
       (e.g. /home/me/some/git/dir#HEAD)
[...]
```
Maybe part of the issue is that it implicitly converted existing pins ?

**Comment by dbuenzli** [comment]
> damn, I thought I had been clear in the doc from the beginning that mixed mode was incurring for git pins, whenever on a local directory and without a branch set: there is no "mixed mode option".
> If even you didn't get it properly... :/

Yes I find this rather confusing. A `git` pin takes its data from the git repo, not from dirt. I was from the onset rather against these mixed mode which lack traceability, reproducability and hygiene. But apparently dropped the ball at some point.

I would still advocate for `opam pin list` to indicate `git (mixed)` on mixed mode pins rather than `git`. Looking for a `#BRANCH` part at the end of the path to be able to infer this is non-mixed mode is easy to miss and rather involved.  

> Maybe part of the issue is that it implicitly converted existing pins ?

Maybe. I know that the message is useful since it prompted me at least once to do what should be done by default.

**Comment by samoht** [comment]
I'm not very found of mixing `git` and `mixed` together as well ... It's confusing if `-k git` not always means "use git" ...

**Comment by dbuenzli** [comment]
Related to #2033, #2015. I think `opam` became a little bit confusing and not enough explicit on the `pin` front and I don't like it when `opam` is an unclear tool. My take on this is:

1. Default `opam pin add` should remain as it stands, this means VCS detection + mixed. I don't like it, it's a bad default for me but let's not change the behaviour every two versions (and apparently I'm in the minority, people like their package system to be in an unknown, untraceable state). I was already used to automatically specify `-kgit` to override the broken (yes) behaviour.
2. `opam pin list` should indicate `$VCS (mixed)` when a pin is in mixed mode. So that it is easy to asses the exact mode of your pins when you feel something is going wrong. 
3. `opam pin add -k $VCS pkg repo` should be `$VCS` mode in *non-mixed* mode.
4. `opam pin add -k $VCS --mixed pkg repo` should be `$VCS` mode in mixed mode.
5. `opam pin add -k $VCS --mixed pkg repo#BRANCH` should be an error.

**Comment by dbuenzli** [comment]
Btw. reading documentation about mixed mode 

> When they don't, in the special case of version-controlled pinning to a local path, OPAM will use "mixed mode": it will only use version-controlled files, but at their current, on-disk version.

It seems to be an insane mode. Basically if I stash and checkout another branch to do some work and for some other unrelated reason I do an `opam update -u` then it will resintall the pin with the checkout. It means that when you do an `opam update -u` you need to make sure you didn't checkout a branch you wouldn't want in any of your mixed-mode pins. Good luck remembering this after you lost focus on what you were doing. This seems like a recipe to maximise [mode errors](http://en.wikipedia.org/wiki/Mode_%28computer_interface%29). 

But then choose your own poison as they say --- just that having poison as the default in tools is usually a bad idea.

**Comment by dbuenzli** [comment]
> It seems to be an insane mode.

Not even talking about having uncompilable sources due to a refactoring and suddenly you upgrade opam for other reasons. 

This should discussed with mixed mode users but I have the impression that you want to be able to control *when* changes are actually picked up (commits are made for that but then I can sympathise with the fact that it can be annoying to have to commit in certain scenarios...). 

If that is the case it seems to me that a saner and safer system would be to forget about mixed mode pins as they exist now, keep only our good old pins and have a `--dirty` option to `install/reinstall` usable only on vcs-pinned packages. The semantics would be as follows. Given a vcs-pinned package `pkg` issuing `opam install pkg --dirty` will:

1. Install `pkg` using version controlled files at their current on-disk version and records the repo's latest commit.
2. The package will not update until the repo's latest commit differs from the recorded commit in 1. If the user wants a new dirty snapshot he can reissue a `opam install pkg --dirty`.
3. `opam info pkg` indicates in the `pinned:` field both the recorded commit and the fact that this is a dirty install.

I think this would make the pin system much simpler for the users to understand and control (including for those who like me do not use mixed mode). But I don't know if this would satisfy mixed mode users. Something along this line would of course also render [these suggestions](https://github.com/ocaml/opam/issues/2141#issuecomment-101994075) obsolete.

Incidentally while I can't see myself using mixed mode for the insanity reasons mentioned above. I can see myself using `install --dirty` in certain cases when you quickly want to test something.

**Comment by dbuenzli** [comment]
(Putting things differently I think that mixed-mode git pins are broken by design because they fail to acknowledge the fact that a git repo directory is a *working* directory and as such it may not constantly represent a state you may want to install)

**Comment by AltGr** [comment]
Err, please calm down. This has been discussed and implemented more than six months ago, and everybody seemed happy with it at the time, and since. I also made extra effort to be explicit about what was happening whenever it happened, and in the doc. It _is_ in OPAM 1.2.1 -- it was only decided to keep path pinning as the default, so as not to break existing scripts within a patch version: detection of VCS is there, but only enabled with `-k auto` or `OPAMPINKINDAUTO=1`. As planned, I made that the default on the 1.3 branch. These changes since 1.2.1 aren't directly related to mixed mode.

On some of the remarks:
- Pinning without a specific branch will make OPAM sync to the current HEAD (at least on git), so Daniel's scenario of checking out a different branch then running `opam update -u`  will have the same consequences with and without mixed mode. It doesn't seem that bad to me, why chose a specific branch if none was specified ?
- `opam pin` should show mixed mode: definitely, good idea
- about tracability: `opam show` will give you the git-hash used.
- defaults of `opam pin add`: it's interactive and explicit, you have plenty of time to change your mind.  The attempt is to have the default give the least surprising behaviour (yes, "I pinned to there and it's not in sync!"), and it's expected that advanced users that are beyond that can specify what they want.
- automatic mixed mode when no branch is set: maybe not the best UI design choice on my part, but then adding too many pinning options may not have been much better.

**Comment by dbuenzli** [comment]
> Err, please calm down.

I am calm.

> This has been discussed and implemented more than six months ago, and everybody seemed happy with it at the time, and since.

There's a difference between discussing and using. But I welcome contradiction from these happy persons. 

> Pinning without a specific branch will make OPAM sync to the current HEAD (at least on git), so Daniel's scenario of checking out a different branch then running opam update -u will have the same consequences with and without mixed mode. It doesn't seem that bad to me, why chose a specific branch if none was specified ?

This should be master (or the branch specified if any). Currently I have: 
```
> opam pin list | wc -l 
      20
```

The idea that I should have to care/remember about what is currently checked out or saved (in mixed mode) in each of these repos whenever I do an `opam update -u` is insane.

> about tracability: opam show will give you the git-hash used.

It should also show dirtyness (if it doesn't) --- n.b. by definition dirtyness is not traceable. 

> defaults of opam pin add: it's interactive and explicit, you have plenty of time to change your mind. The attempt is to have the default give the least surprising behaviour (yes, "I pinned to there and it's not in sync!"), and it's expected that advanced users that are beyond that can specify what they want.

I don't really care about the default to be honest, see next point. 

> automatic mixed mode when no branch is set: maybe not the best UI design choice on my part, but then adding too many pinning options may not have been much better.

I disagree with that, it defeats expectations. `opam pin -kgit` should be git and that's all. Not that broken mixed mode. If I am explicit about the kind of pin I want then it should catch that explicit mode and an option should exist for specifying the broken mixed mode.

Altogether given the number of pins mentioned above I still think that [this design](https://github.com/ocaml/opam/issues/2141#issuecomment-102022921) is a much better system to live in: it is a declarative system. What we have currently is a confusing imperative system that depends on the state of your hard disk and picks up whatever crap exists at the time you `opam update -u`. But then if OCaml programmers like it why not, FP is (sadly) more a figment of their imagination than a reality for most of them so I can imagine them not being disturbed. It remains that in my opinion the the whole pin system could be much more simple conceptually without that insane mixed mode.

**Comment by dbuenzli** [comment]
I have started a discussion about this on opam-devel http://lists.ocaml.org/pipermail/opam-devel/2015-May/001068.html
