### ISSUE TITLE
opam-depext not found with opam 1.2.1

### ISSUE THREAD

**Issue by talex5** [ocaml/opam#2142]
`opam depext` is no longer working for me (using the 0install package):

    $ 0install run --version=1.2.0 opam depext
    # Detecting depexts using flags: x86_64 linux arch
    # No extra OS packages requirements found.

    $ 0install run --version=1.2.1 opam depext
    opam: unknown command `depext'.
    Usage: opam COMMAND ...
    Try `opam --help' for more information.

`strace`ing the two versions shows that 1.2.0 does:

    [pid 10043] execve("/bin/sh", ["/bin/sh", "-c", "command -v opam-depext"], [/* 41 vars */]) = 0

while 1.2.1 does:

    [pid 10326] stat("/home/tal/.cache/0install.net/implementations/sha256new_5UFFHTGKFG26KQFVJVKYB56WSAAX5IYV54HUQCTMEYTJJEBX7SOQ/bin/opam-depext", 0x7ffcfc5aef60) = -1 ENOENT (No such file or directory)

Does opam expect opam-depext to be installed in the same directory as itself? But I can't imagine that happens even with a non-0install package. What's the correct behaviour here?

**Comment by AltGr** [comment]
OPAM was previously only looking in the normal PATH for plugins; it's now checking what switch it is in to properly find plugins installed in that switch. This means that, if it detects an opam root, it will load some stuff in it to get the correct switch. Do you also get that with 1.2.2 ?

**Comment by talex5** [comment]
Same problem with 1.2.2. Even happens just when building from the Git clone:

    $ make

    $ opam-depext
    # Detecting depexts using flags: x86_64 linux arch
    # No extra OS packages requirements found.

    $ ./src/opam depext
    opam: unknown command `depext'.
    Usage: opam COMMAND ...
    Try `opam --help' for more information.

**Comment by AltGr** [comment]
`OPAMDEBUG=1 opam depext` might give you some more hints ?

**Comment by talex5** [comment]
It works with this change:

    diff --git a/src/client/opamArg.ml b/src/client/opamArg.ml
    index 7a8f0bd..34330b9 100644
    --- a/src/client/opamArg.ml
    +++ b/src/client/opamArg.ml
    @@ -1980,7 +1980,7 @@ let check_and_run_external_commands () =
	   && List.for_all (fun (_,info) -> Term.name info <> name) commands
	 then
	 (* No such command, check if there is a matching plugin *)
    -    let command = opam ^ "-" ^ name in
    +    let command = "opam-" ^ name in
	 let t = OpamState.load_env_state "plugins" in
	 let env = OpamState.get_full_env ~force_path:false t in
	 let env = Array.of_list (List.rev_map (fun (k,v) -> k^"="^v) env) in

**Comment by AltGr** [comment]
Hm, indeed, relying on `argv.(0)` was probably a bad idea (or at least, it should basename).

Thanks!

**Comment by avsm** [comment]
Does this need an rc3 of 1.2.2?

**Comment by talex5** [comment]
1.2.2 is already released. I made a patched release for 0install (which always runs binaries by their full path, and so always hits this problem):

https://github.com/talex5/opam/releases/tag/1.2.2-tal1
