### ISSUE TITLE
why3 0.85 is broken

### ISSUE THREAD

**Issue by cogumbreiro** [ocaml/opam#2143]
Trying to install why3 via opam, but I get the following error:

```
$ opam install why3
The following actions will be performed:
 - install   why3.0.85
=== 1 to install ===

=-=- Synchronizing package archives -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] Downloading https://opam.ocaml.org/archives/why3.0.85+opam.tar.gz
[ERROR] Could not download archives of why3.0.85
```

**Comment by AltGr** [comment]
Packaging issues are generally to be reported to the [opam-repository](https://github.com/ocaml/opam-repository/issues/) tracker

Please also specify your OPAM version, system and make sure you ran `opam update`. The source is now in `why3-base` and `why3` itself shouldn't trigger any download.

Thanks!
