### ISSUE TITLE
opam update failing on fresh install

### ISSUE THREAD

**Issue by chetmurthy** [ocaml/opam#2145]
I've just installed:

ocaml 4.02.1
opam-full 1.2.0

using ocamlbrew, and I find that when I do "opam update" (after sourcing the bashrc), I get an error on one of the files.  I figured I should report this problem before debugging it, since it might be a problem with the source data ... Hereinafter please find the output of opam update (in its entirety):

chet@groupon:~/Hack/ocamlbrew$ opam list
# Installed packages for system:
base-bigarray  base  Bigarray library distributed with the OCaml compiler
base-threads   base  Threads library distributed with the OCaml compiler
base-unix      base  Unix library distributed with the OCaml compiler
chet@groupon:~/Hack/ocamlbrew$ opam update
[default] Downloading https://opam.ocaml.org/urls.txt
Updating ~/Hack/ocaml-4.02.1/.opam/repo/compiler-index ...
Updating ~/Hack/ocaml-4.02.1/.opam/compilers/ ...
Updating ~/Hack/ocaml-4.02.1/.opam/repo/package-index ...
Updating ~/Hack/ocaml-4.02.1/.opam/packages/ ...
[ERROR] At ~/Hack/ocaml-4.02.1/.opam/repo/default/packages/bisect_ppx/bisect_ppx.0.1/opam:6:48:
  Not a recognised version-control URL
chet@groupon:~/Hack/ocamlbrew$ 

I attach the offending file; the cited line starts with "dev-repo".  Is this a known problem?

==================================================
opam-version: "1.2"
name: "bisect_ppx"
version: "0.1"
maintainer: "Leonid Rozenberg <leonidr@gmail.com>"
authors: "Leonid Rozenberg <leonidr@gmail.com>"
dev-repo: "https://github.com/rleonid/bisect_ppx"
bug-reports: "https://github.com/rleonid/bisect_ppx/issues"
build: [
  ["sh" "configure"]
  [make "all"]
]
install: [
  [make "install"]
  ["cp" "bisect-report" bin]
  ["cp" "bisect-report.opt" bin]
  ]
remove: ["ocamlfind" "remove" "bisect_ppx"]
depends: [
  "ocamlfind" "ppx_tools" {build}
]

**Comment by samoht** [comment]
Thanks for the report, this is fixed by https://github.com/ocaml/opam-repository/pull/4062. The update will be live in about 10 minutes.

@AltGr I think that 1.2.2 is much more relax with errors of such kinds now?

**Comment by AltGr** [comment]
Yes, there already was a "permissive" mode that would ignore most errors, but it was only activated for files declared with a higher minor OPAM version ; it's now enabled by default, and in this case should just silently ignore the `dev-repo` field.
