### ISSUE TITLE
Show patch application before compilation

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2146]
At some point, patch application was shown before compilation (unless I imagined it ?),  but it's not anymore, even in verbose mode.

It was useful to debug conditional patch application.

**Comment by AltGr** [comment]
Indeed it was, but lots of messages have been cleaned up :)
Verbosity levels have been added: try `-vv` to also display calls to commands outside build scripts (curl, install, patch...)
`--debug` will also print a message about patch application

**Comment by Drup** [comment]
hum, right, I missed that in the 1.2.1 changelog. Not sure I'm convinced it shouldn't be showed in -v directly, though. :)

**Comment by samoht** [comment]
Yea I've been hit by the issue as well: application of patch would be useful to be seen with -v I think

**Comment by AltGr** [comment]
Closed by #2179
