### ISSUE TITLE
camlp4 and a system switch

### ISSUE THREAD

**Issue by alainfrisch** [ocaml/opam#2151]
I tried installing OPAM 1.2.2 for use for a "system" switch, but then installing camlp4 through OPAM seems somehow broken.  Camlp4 files are installed in:

```
  .opam/system/bin/
  .opam/system/lib/ocaml/camlp4/
```

and there is a .opam/system/lib/camlp4/META file, with a line:

```
directory = "+camlp4"
```

Consequently, "ocamlfind query camlp4" returns the path $PREFIX/lib/camlp4 (where $PREFIX is the installation directory for my system install), although there is no camlp4 files there.  This breaks installation of packages that depend on camlp4.  For instance, lwt fails with:

```
# [...]
# W: Field 'pkg_camlp4' is not set: When looking for findlib package camlp4, directory /home/afrisch/branches/v4/mlfi/mlfi-ins/lib/camlp4 return doesn't exist
# W: Field 'pkg_camlp4_quotations_o' is not set: When looking for findlib package camlp4.quotations.o, directory /home/afrisch/branches/v4/mlfi/mlfi-ins/lib/camlp4 return doesn't exist
# W: Field 'pkg_camlp4_extend' is not set: When looking for findlib package camlp4.extend, directory /home/afrisch/branches/v4/mlfi/mlfi-ins/lib/camlp4 return doesn't exist
# W: Failure("When looking for findlib package camlp4, directory /home/afrisch/branches/v4/mlfi/mlfi-ins/lib/camlp4 return doesn't exist")
# W: Failure("When looking for findlib package camlp4, directory /home/afrisch/branches/v4/mlfi/mlfi-ins/lib/camlp4 return doesn't exist")
# W: Failure("When looking for findlib package camlp4.quotations.o, directory /home/afrisch/branches/v4/mlfi/mlfi-ins/lib/camlp4 return doesn't exist")
# E: Cannot find findlib package camlp4
# E: Cannot find findlib package camlp4.extend
# E: Cannot find findlib package camlp4.quotations.o
# E: Failure("3 configuration errors")
```

I fixed that  by changing manually the `directory` line in camp4's META to point to $HOME/.opam/system/lib/ocaml/camlp4.

Is it a (known) issue with camlp4 and a system switch?  Did I miss some steps that would avoid the manual patch of camlp4's META file?

Some info:

```
$ opam list | grep camlp4
camlp4           4.03.0  Camlp4 is a system for writing extensible parsers for p

$ ocamlfind list | grep camlp4 
camlp4              (version: 4.03.0+dev7-2015-02-08-LEXIFI)
...
```

**Comment by samoht** [comment]
I think it's best to install the system camlp4 if you are using the system compiler. At one point, we tried to fix the installation of camlp4 in all possible cases but it was really a pain. If you have any idea idea to improve this, you are very welcome :-)

**Comment by alainfrisch** [comment]
I take your answer as "yes, this is a known issue".

I might have missed something, but a fix could be to arrange that when camlp4 is installed through OPAM, the `directory` directive in the installed META file corresponds to the actual installation directory, i.e. `.opam/system/lib/ocaml/camlp4/` in the case of a system switch.  This won't magically make it work for people who pass `-I +camlp4` on the compiler command line -- of course -- but at least it should make it work for package that relies on findlib.

Perhaps this should be addressed directly in camlp4 install rules, not at the level of its OPAM package description (I don't know).

**Comment by avsm** [comment]
This isn't a known issue -- the intention behind the `camlp4.4.02.1+system` package is that it checks that the system camlp4 is installed and errors out if isn't.  It shouldn't just silently continue, as it seems to have in your case.

https://github.com/ocaml/opam-repository/blob/master/packages/camlp4/camlp4.4.02.1+system/files/check-camlp4.sh

There was a fairly long thread on caml-devel around the 4.02.0 release time about workarounds for the `+I camlp4` issue, but none of them were practical. For now, it's best to use a custom compiler switch if you want a local camlp4, and install it alongside your system compiler.  Perhaps we should investigate how to fix this for 4.02.2 though...

**Comment by alainfrisch** [comment]
The version which was chosen was camlp4.4.03.0, perhaps because my system switch is based on OCaml's trunk.  Is that the problem?

Even without fixing `+I camlp4`, ensuring that the installed META doesn't point to a wrong location would already improve the situation for all packages that locate camlp4 through findlib, such as lwt.  I don't see cases where this would cause a regression.

**Comment by AltGr** [comment]
This seems obsolete; please reopen if not!

**Comment by snowcrshd** [comment]
I think I might have the same issue.

Current OCaml version: 4.04.0
Current OPAM version: 1.2.2

I'm running Fedora 24 and did the following:

1. Installed OPAM binary I got from http://opam.ocaml.org/doc/Install.html
2. Downloaded and built OCaml 4.04 source and installed it to /usr/local
3. Ran `opam init`
4. Tried installing `lwt` and got the error below:

```
[ERROR] The compilation of lwt failed at "ocaml setup.ml -configure --prefix /home/ltadeu/.opam/system --disable-libev --enable-camlp4 --enable-react --disable-ssl
        --enable-unix --enable-preemptive --disable-glib --enable-ppx".
Processing  4/4: [lwt: ocamlfind remove]
#=== ERROR while installing lwt.2.6.0 =========================================#
# opam-version 1.2.2
# os           linux
# command      ocaml setup.ml -configure --prefix /home/ltadeu/.opam/system --disable-libev --enable-camlp4 --enable-react --disable-ssl --enable-unix --enable-preemptive --disable-glib --enable-ppx
# path         /home/ltadeu/.opam/system/build/lwt.2.6.0
# compiler     system (4.04.0)
# exit-code    1
# env-file     /home/ltadeu/.opam/system/build/lwt.2.6.0/lwt-24887-ebe0e0.env
# stdout-file  /home/ltadeu/.opam/system/build/lwt.2.6.0/lwt-24887-ebe0e0.out
# stderr-file  /home/ltadeu/.opam/system/build/lwt.2.6.0/lwt-24887-ebe0e0.err
### stderr ###
# [...]
# W: Field 'pkg_camlp4' is not set: When looking for findlib package camlp4, directory /usr/local/lib/ocaml/camlp4 return doesn't exist
# W: Field 'pkg_camlp4_quotations_o' is not set: When looking for findlib package camlp4.quotations.o, directory /usr/local/lib/ocaml/camlp4 return doesn't exist
# W: Field 'pkg_camlp4_extend' is not set: When looking for findlib package camlp4.extend, directory /usr/local/lib/ocaml/camlp4 return doesn't exist
# W: Failure("When looking for findlib package camlp4, directory /usr/local/lib/ocaml/camlp4 return doesn't exist")
# W: Failure("When looking for findlib package camlp4, directory /usr/local/lib/ocaml/camlp4 return doesn't exist")
# W: Failure("When looking for findlib package camlp4.quotations.o, directory /usr/local/lib/ocaml/camlp4 return doesn't exist")
# E: Cannot find findlib package camlp4
# E: Cannot find findlib package camlp4.extend
# E: Cannot find findlib package camlp4.quotations.o
# E: Failure("3 configuration errors")
```

Checking if I have camlp4 installed:

```
opam list | grep camlp4
camlp4           4.04+system  Camlp4 is a system for writing extensible parsers 
```

And here's what I get when I set opam config environment:

```
set -gx CAML_LD_LIBRARY_PATH "/home/ltadeu/.opam/system/lib/stublibs:/usr/local/lib/ocaml/stublibs";
set -gx MANPATH "" "/home/ltadeu/.opam/system/man";
set -gx PERL5LIB "/home/ltadeu/.opam/system/lib/perl5";
set -gx OCAML_TOPLEVEL_PATH "/home/ltadeu/.opam/system/lib/toplevel";
set -gx PATH "/home/ltadeu/.opam/system/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/sbin";
```

PS: I'm running fish shell.

**Comment by krizex** [comment]
Same issue with @snowcrshd

**Comment by dozylynx** [comment]
ocamlfind (v 1.7.3 at least) overwrites the camlp4/META file. See the logic in ocamlfind's configure script: If camlp4 is detected as in the $PATH but executing it fails for some reason, then the ocamlfind configure script will overwrite the camlp4 META file with an old, incorrect version that is missing the quotations package information. That then causes the lwt build to fail, as seen in the traces above.
