### ISSUE TITLE
Makefile assumes tar has function modifier z

### ISSUE THREAD

**Issue by alanfeldstein** [ocaml/opam#2158]
cd tmp && tar xfz ../extlib-1.5.3.tar.gz
tar: z: unknown function modifier
Usage: tar {c|r|t|u|x}[BDeEFhilmnopPqTvw@[0-7]][bfk][X...] [blocksize] [tarfile] [size] [exclude-file...] {file | -I include-file | -C directory file}...

This comes from
opam-full-1.2.2-rc2/src_ext/Makefile

%.stamp: %.download
    mkdir -p tmp
    cd tmp && tar xf$(if $(patsubst %.tar.gz,,$(URL_$_)),j,z) ../$(notdir $(URL_$_))
...

The makefile seems to be assuming GNU tar. There are at least three possible solutions to this bug:

(1) Have configure look for gtar and use it over tar if found.
This solution is not ideal because gtar is not the standard name for GNU tar.

(2) Simply add the GNU tar requirement to README.md.
This is a lazy solution, pushing responsibility onto the user.

(3) Modify the makefile to call gunzip, followed by tar.
This is the most robust solution, supporting the greatest number of platforms. One person makes the change, benefiting multiple users.

Alan Feldstein
Cosmic Horizon
http://www.alanfeldstein.com/

**Comment by avsm** [comment]
Which platform are you build on, out of curiosity?

**Comment by alanfeldstein** [comment]
Solaris 10

**Comment by AltGr** [comment]
Indeed, (3) seems like a good solution. However, the opam binary itself will later want to "tar xfz"/"tar xfj" the downloaded packages, at installation time -- so we would need to workaround that too.

**Comment by alanfeldstein** [comment]
I could create and submit a fix that employs solution (3), but the fact that the OPAM binary will also want to "tar xfz"/"tar xfj" means that mine would be only a partial solution. If OPAM itself is an OCaml program and I want OPAM to install utop as suggested by "Real World OCaml", which I'm reading to learn OCaml, then I'm not the best candidate to fix the OPAM binary. Rather, I'm motivated to await these fixes while diverting my attention to installing utop from sources.

**Comment by AltGr** [comment]
That's fine, your reports are pretty useful already -- thanks!

**Comment by michipili** [comment]
If this is helpful, I have written [autoconf macros to detect compression options supported by tar](https://github.com/michipili/bsdowl/blob/master/aclocal.m4#L167).  Feel free to plunder this treasure! :)

I use them in BSD Owl to automatically produce (GPG-singed) tarballs out of a source tree.

**Comment by dra27** [comment]
I believe this was fixed in #2791 - can this issue be closed, or are there other instances to worry about?
