### ISSUE TITLE
opam config env --csh does not work anymore

### ISSUE THREAD

**Issue by Xoff-off** [ocaml/opam#2170]
"opam config env --csh" does not work anymore but it was working fine before. What can I do to make it work again ? I tried to find an alternative and did not find one.

**Comment by AltGr** [comment]
The new option is `--shell=csh'.

**Comment by Xoff-off** [comment]
Please update the documentation, it does not show in `opam --help`

**Comment by Xoff-off** [comment]
Ok sorry, I just find it now in `opam config --help` Thank you !
