### ISSUE TITLE
Warn on bad opam file when pinning

### ISSUE THREAD

**Issue by jpdeplaix** [ocaml/opam#2173]
If I have this on my opam file:
```
depends: [
  "oasis" {build} {>= "0.4.5"}
]
```
The parsing succeed but everything is ignored after the ```depends```. It caused my a lot of troubles today :/

**Comment by AltGr** [comment]
Warning messages on malformed files have been turned off by default, because they're not the concern of end-users (esp. since when triggered by file format incompatibilities between versions). Always use --verbose when testing your own packages -- and lint them !

**Comment by jpdeplaix** [comment]
Ok, fair enough

**Comment by AltGr** [comment]
what was your use-case ? Maybe we could add more verbose checks e.g. when importing a new opam file from source for a pinned package.

**Comment by jpdeplaix** [comment]
Yep, I was pinning a package locally: ```opam pin add -n --kind=git package .```

**Comment by AltGr** [comment]
k, there should definitely be a warning in this case -- there is one only when you use `--edit` I think, at the moment.
