### ISSUE TITLE
Respect `opam config var lib` internally

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#2175]
For various reason the `lib` path is sometimes computed from `OpamPath.Switch.lib` and sometimes for reading `global-config.config` (which is read by `opam config var`). It would be great if everything goes through the file, so it can be easily tweaked by the user.

This is somehow related to #2149 but it is also useful for cross-compilation. See also #2153 to have a fully working system.

**Comment by AltGr** [comment]
This should now be the case ! :)

**Comment by samoht** [comment]
Great!!
