### ISSUE TITLE
Issues with last aspcud

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2176]
I recently updated aspcud/gringo/clasp to versions 1.9.1/4.5.0/3.1.2. It was not a fabulous idea and now everything is broken. :(

On most (but not all) call to the solver, I get 
```
External solver failed with inconsistent return value. Request saved
          to "/home/gabriel/.opam/log/solver-error-2749-1.cudf"
```

The file is [here](http://pastebin.archlinux.fr/1044859).

A manual call gives:
``` 
% aspcud -d /home/gabriel/.opam/log/solver-error-2749-1.cudf /tmp/bla "-count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)"    
debug: created temporary file /tmp/cudf2lp.outggzeT9
debug: created temporary file /tmp/cudf2lp.errIzZ1dO
debug: created temporary file /tmp/gringo.outkhYPys
debug: created temporary file /tmp/gringo.errn5pET6
debug: created temporary file /tmp/clasp.outENiteL
debug: created temporary file /tmp/clasp.err1AGizp
debug: starting process cudf2lp -f /home/gabriel/.opam/log/solver-error-2749-1.cudf -c -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
debug: starting process gringo -Wno-atom-undefined -f /usr/share/aspcud/misc2012.lp -f /tmp/cudf2lp.outggzeT9
debug: starting process clasp -q1,2 --stats=2 --opt-strategy=5 -f /tmp/gringo.outkhYPys
clasp version 3.1.2
Reading from /tmp/gringo.outkhYPys
Solving...
```

Witch return a file with a single line in it:
```
FAIL
```

clasp and gringo don't produce errors on their own.

**Comment by Drup** [comment]
I tried with both last release and the git version.

**Comment by AltGr** [comment]
arg... thanks for reporting, I'll see what can be done.

**Comment by AltGr** [comment]
my (working) combination from Debian testing is:
- aspcud **1.9.1**
- clasp **3.1.2**
- gringo **4.4.0**

The only difference is gringo, would you try downgrading ?

**Comment by choeger** [comment]
I am facing the same issue on fedora 22, no downgrade (aspcud 1.9.0, gringo 4.2.1, clasp 3.0.6) helped. The provided binaries (downloadable from sourceforge) worked flawlessly. It *seems* that this may be caused by a newer compiler or std lib.

**Comment by Drup** [comment]
@choeger It seems to work, thanks a lot. I'll keep testing.

I'm not sure what is the bug exactly and to who it should be reported.

**Comment by c-cube** [comment]
I have the same kind of errors (on archlinux) with gringo 4.5.0-1, clasp 3.1.2-1, aspcud 1.9.1-1.

**Comment by samoht** [comment]
Is the issue reported upstream?

**Comment by Drup** [comment]
Pretty sure that's not an issue anymore. I recompiled ascpud a few month ago without issue. Closing!
