### ISSUE TITLE
Work on the signing spec, following discussion on the ML

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam#2182]
Original discussion happening at http://lists.ocaml.org/pipermail/platform/2015-June/thread.html

The final version of the document should be added to doc/design in the main opam repository
- [ ] Clarify status on signatures on key removal, what happens with invalid signatures
- [ ] Clarify that root keys are shipped with the binary
- [ ] Specify whether the initial-bootstrap key can be used to sign later on, and how it's checked (the feature might be useful for some small third-party repos to skip delegations ?)
- [ ] Need more details on keyids and uniqueness
- [ ] Pick up one of "developer", "package maintainer" and "author" and be consistent
- [ ] Specify date format correctly
- [ ] Getting rid of compilers definitions first ?
- [ ] Travis is not appropriate, replace by our own server/unikernel

This is just a summary of what needs to be changed on the specification. Please keep the discussion to the mailing-list for now.

**Comment by hannesm** [comment]
more from Thomas Gazagnaire:
- [ ] it would help to explain somewhere (and if possible early in the document) what does it mean to sign a file, i.e. adding a field "signature". The "Signed files and tags" explain part of the process, but without explicitly saying anything.
- [ ] also it was not totally clear to me at first read that the Linearity condition is a kind of "custom policy checking", where the custom policy is actually quite different of what the default TUF specification. i.e., the snapshot bot should know and apply a policy set by the repository maintainers (which can change over time).

**Comment by AltGr** [comment]
This is largely outdated, and large progress has been made since, closing.
