### ISSUE TITLE
Incorrect use of Filename.concat

### ISSUE THREAD

**Issue by braibant** [ocaml/opam#2188]
Hi,

I am attempting to compile Opam 1.2.2 under the Cygwin environment, using WODI to provide the compilers. After some steps, I am in a state in which `opam init` returns  

```
$ opam init
Checking for available remotes: rsync and local, git.
  - you won't be able to use mercurial repositories unless you install the hg
    command on your system.
  - you won't be able to use darcs repositories unless you install the darcs
    command on your system.

[WARNING] Recommended external solver aspcud not found.
[WARNING] Recommended dependencies -- most packages rely on these:
            - cc


=-=- Fetching repository information =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default: http]
[ERROR] Initialisation failed
# opam-version         1.2.2 (391297300524717e1475deaea37bca287c7f5e36)
# os                   win32
# command              curl --write-out %{http_code}\n --insecure --retry 3 --retry-delay 2 --compressed -OL https://opam.ocaml.org\urls.txt
# path                 C:\cygwin64\tmp\opam-96-e7966f
# exit-code            23
# env-file             C:\cygwin64\home\vagrant\.opam\log\log-96-c61e7b.env
# stdout-file          C:\cygwin64\home\vagrant\.opam\log\log-96-c61e7b.out
# stderr-file          C:\cygwin64\home\vagrant\.opam\log\log-96-c61e7b.err
### stderr ###
# curl: Remote file name has no length!
# curl: try 'curl --help' or 'curl --manual' for more information
```

The command is `curl --write-out %{http_code}\n --insecure --retry 3 --retry-delay 2 --compressed -OL https://opam.ocaml.org\urls.txt`. 

I suspect that the culprit is a line like the following one, which apparently uses `Filename.concat`. In my case, Filename.concat "a" "b" is "a\b". 

https://github.com/ocaml/opam/blob/9da8b5b9752b72f876084217d9cdbc492cd49f3f/src/repository/opamHTTP.ml#L34

**Comment by braibant** [comment]
I was using 1.2.2 for this experiment, but the issue is still present using `master`

**Comment by AltGr** [comment]
Ah, indeed, there are a few places where file functions are used for URLs; I had actually spotted and fixed those, on a branch that cleaned our filename interface, but that branch also experimented with ocaml-fileutils, which turned out to be a bad idea (unmaintained, and I found a handful of bugs already during the experiment). I'll get back to it and port the fixes
