### ISSUE TITLE
Cannot compile OPAM on cygwin

### ISSUE THREAD

**Issue by eleirin** [ocaml/opam#2192]
Hello everyone,
After several struggles and some day spent on it, I finally give it up and come to beg for some help ^^"
I installed OPAM on windows through installing WODI and then a non-up-to-date OPAM with it, to finally fetch OPAM through this version of OPAM (as afforementioned, yes, it was a bit tedious and a lot of trials-and-errors)
So I thought I was finally done, and enter the command "opam init"

```
$ opam init
[WARNING] C:\cygwin\home\Epiphanie\.opam exists and is not empty
Proceed ? [Y/n]
Checking for available remotes: [ERROR] Initialisation failed
# opam-version    1.2.2
# os              win32
C:\cygwin\usr\local\bin\opam: "create_process" failed on /bin/sh: No such file or directory
Fatal error:
# opam-version    1.2.2
# os              win32
C:\cygwin\usr\local\bin\opam: "create_process" failed on /bin/sh: No such file or directory"
```

Ah. I did some ressearch, but the only things I found is either that I should put /usr/bin at the beginning of my $PATH, which I did, or some references to this error without further mentions ^^
Also deleting the folder does not change anything in case you were wondering

Thank you very much in advance, I hope my tone wasn't too eager, and have a nice day~

**Comment by AltGr** [comment]
Thanks for reporting ; we are looking into Windows compatibility (cygwin being one aspect of it), but there is yet much work to be done.

We opened a dedicated mailing-list at http://lists.ocaml.org/pipermail/wg-windows/ ;
There is also a history of reports on the subject, you may want to check e.g. #246

**Comment by Epiphania** [comment]
Oh, thank you very much, I'm going to read through this then. I already checked the thread (sorry, should I have posted my problem there?) 
And yes, I understand that it is a huge work, thank you so much for this

I will answer more thoroughly once I read through the mailing list
Thanks very much for the fast answer (and opam did a wonderful job at installing Why on my linux without any problems!)

**Comment by struktured** [comment]
I got opam working with cygwin64 but some packages still have trouble installing after opam init, such as camlp4. I will post a link on how I set it up when I'm ready.

**Comment by braibant** [comment]
@struktured That's really good to know. Please post a link on the wg-windows ML when you are ready.

**Comment by haochenx** [comment]
looking at the path in your output, namely, `C:\cygwin\home\Epiphanie\.opam`, it's very likely that you're not in a cygwin environment. It's possible that you are using MSYS, which doesn't emulate linux's directory structures, thus `/bin/sh` points to nothing.

**Comment by dra27** [comment]
@haochenx is right - it looks like you're using a very old mingw-compiled opam which won't work without further patches.

@AltGr - I think this can be safely closed.
