### ISSUE TITLE
Perpetual warning in `opam switch list`

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2199]
This warning is always there, even if I just ran the command and if everything else is working fine.
```
[WARNING] The environment is not in sync with the current switch.
          You should run: eval `opam config env`
```

**Comment by AltGr** [comment]
Last version ? I remember fixing this some time ago

**Comment by Drup** [comment]
Version from yesterday, let me update.

I indeed remember it was fixed at some point, but here it is again.

**Comment by AltGr** [comment]
stop searching, I got it too actually. Thanks for reporting!
