### ISSUE TITLE
0.12.0 is considered different of 0.12

### ISSUE THREAD

**Issue by zoggy** [ocaml/opam#2204]
Hello,

I was giving the following dependency constraint: "xtmpl" { >= "0.12.0" }. But xtmpl comes in version 0.12, not 0.12.0. opam could not resolve the constraint.

Would it be possible to consider 0.12 by being valid when depending on 0.12.0 ? More generally, version numbers could be normalized by removing ending ".0"s.

**Comment by AltGr** [comment]
The opposite is true: 0.12 < 0.12.0
The current version ordering scheme is taken from Debian and described in [the Manual](opam.ocaml.org/doc/Manual.html#PackageFormulas)
Normalising could lead to some issues, e.g. `0.12~dev` is within the range  `>= "0.12" & < "0.13"`, while `0.12.0~dev` is not.

**Comment by zoggy** [comment]
I do not see the problem: normalising would result in 0.12.0~dev to be reduced to 0.12~dev . This normalisation could take place when converting strings into version numbers. (but I don't know if there is a datatype for version numbers, I hope so). But if compatibility with debian rules is important, no problem. I'll try not to forget this trap :)

**Comment by lefessan** [comment]
We should clearly not diverge from the Debian version ordering schema.

**Comment by avsm** [comment]
I agree that sticking to some existing convention is wise -- in case Debian's set a precedent, so picking their behaviour would minimise divergence.
