### ISSUE TITLE
type_conv download failed in OS X due to curl: (56) SSLRead()

### ISSUE THREAD

**Issue by camlspotter** [ocaml/opam#2212]
It seems I cannot download packages from Jane Street downloads due to errors related to SSLRead().  It relates with https://github.com/ocaml/opam/issues/2006 which exists since Feburary.

```
$ opam install --verbose type_conv
opam install --verbose type_conv
The following actions will be performed:
 - install   type_conv.112.01.01
=== + 1 ===

=-=- Synchronizing package archives -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[type_conv.112.01.01] Downloading https://ocaml.janestreet.com/ocaml-core/112.01.00/individual/type_conv-112.01.01.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
curl: (56) SSLRead() return error -9841
000
[ERROR] https://ocaml.janestreet.com/ocaml-core/112.01.00/individual/type_conv-112.01.01.tar.gz is not available
[ERROR] Could not download archives of type_conv.112.01.01

'opam install --verbose type_conv' failed.
```

**Comment by AltGr** [comment]
It's an issue with OSX's curl... For this reason we've switched to wget by default on OSX, but you may have an old setting stuck somewhere, or an older opam.
On recent opam, you may use `OPAMFETCH=wget`, and check your `~/.opam/config` for `download-command: wget` ; but that should be the default.
On older opam (<1.2.1), you may try setting `OPAMCURL=wget`, or, that failing, ensuring opam won't find curl in your `PATH`.

Ref: https://github.com/ocaml/opam/issues/2006#issuecomment-74832764
