### ISSUE TITLE
Is it possible to pin package to dev repo and specify branch?

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/opam#2220]
I know you can do `$ opam pin add <package> --dev-repo`, but if I want to specify a branch as well? In the full repo pin syntax, you can do `#branch`. Is there an equivalent here?

**Comment by dbuenzli** [comment]
I don't think so, maybe just add an optional argument to the `--dev-repo` option to specify the branch ?

**Comment by AltGr** [comment]
You will need to extract the dev-repo field to add the branch.
`opam pin add <pkg> $(opam show <pkg> -f 'dev-repo:')#branch`
