### ISSUE TITLE
`opam update` needs more than 128M RAM

### ISSUE THREAD

**Issue by vbmithr** [ocaml/opam#2225]
It can't run it on my OpenWRT router because opam update (using a local repository) takes too much RAM. Any way to decrease the amount of RAM used by OPAM ?

Very general question I agree :)

**Comment by vbmithr** [comment]
```
        Command being timed: "opam update"
        User time (seconds): 5.08
        System time (seconds): 3.65
        Percent of CPU this job got: 59%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:14.70
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 144584
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 30
        Minor (reclaiming a frame) page faults: 125007
        Voluntary context switches: 38286
        Involuntary context switches: 1343
        Swaps: 0
        File system inputs: 476560
        File system outputs: 125656
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

It actually uses 144584 kbytes on my desktop machine. I would be interested at any optimization that could reduce this RAM usage to something below 100Mib let's say.

**Comment by vbmithr** [comment]
Out of memory even with a 1024M swap file used. (cannot fork aspcud: Out of memory).

**Comment by AltGr** [comment]
Did you try without solver (e.g using the IRILL's [solver farm](http://cudf-solvers.irill.org/index.html) ?)
Opam might be failing after successfully updating, when attempting to print the available upgrades message (which calls the solver).

**Comment by vbmithr** [comment]
On 29/06/2015 07:19, Louis Gesbert wrote:
> Did you try without solver (e.g using the IRILL's solver farm
> <http://cudf-solvers.irill.org/index.html> ?)
> Opam might be failing after successfully updating, when attempting to
> print the available upgrades message (which calls the solver).

Yes, I tried this and 1024M swap. At some point, opam wants to fork and
cannot because of Out of memory.

What exactly eats RAM in OPAM ?

-- 
Vincent

**Comment by AltGr** [comment]
Not sure. I ran [this](http://memprof.typerex.org/users/464527645bfe7266d83e8f3c716f1090/2015-01-07_14-54-47_2bdd6b66e160df2089bc981f1ad000a2_24038/index.html) a while ago but it doesn't go that high. I'd otherwise say, probably the multiple conversions between OPAM state and Cudf/Dose universe that cause multiple copies of the whole package information to be stored ?

**Comment by vbmithr** [comment]
On 30/06/2015 04:43, Louis Gesbert wrote:
> Not sure. I ran this
> <http://memprof.typerex.org/users/464527645bfe7266d83e8f3c716f1090/2015-01-07_14-54-47_2bdd6b66e160df2089bc981f1ad000a2_24038/index.html>
> a while ago but it doesn't go that high. I'd otherwise say, probably the
> multiple conversions between OPAM state and Cudf/Dose universe that
> cause multiple copies of the whole package information to be stored ?

I'm wondering how you get such small memory usage on ocp-memprof.
time -v opam update gives me:

Maximum resident set size (kbytes): 124868

And this is rather consistent with my observation opam crashing on
machine with low memory.

Do you have a rough estimate of the size of an OPAM state / Dose
universe and the amount of times it is copied ?

Any way to share those datastructures ?
More than 100M is a large amount of memory, I'm wondering what's in it.

-- 
Vincent

**Comment by AltGr** [comment]
Not sure, but `opam update` parses all opam files from the repository, then marshalls that for caching. I guess, due to the size of the repository and the multiple copies of the package universe, that it can quickly grow.
Note that `opam update` no longer calls the solver.
