### ISSUE TITLE
Unable to install android cross-build tools

### ISSUE THREAD

**Issue by nobrowser** [ocaml/opam#2226]
I am trying to follow the instructions here:

https://github.com/whitequark/opam-android/blob/master/README.md

My build system is amd64 with Debian wheezy.  I follow the instructions exactly, but:

```
eval `opam config env`
 [2+0]~$ eval `opam config env`
 [3+0]~$ ANDROID_LEVEL=21 ANDROID_ARCH=armv7 opam install ocaml-android
Your request can't be satisfied:
  - No package matches ocaml-android.

No solution found, exiting
```

Strangely,

```
 [5+0]~$ opam list -a | fgrep ocaml-android
ocaml-android               --  A meta-package depending on any OCaml cross-comp
ocaml-android32             --  OCaml cross-compiler for 32-bit Android targets
```

**Comment by avsm** [comment]
which version of OPAM do you have installed? Is it 1.2.0+?

**Comment by nobrowser** [comment]
Built from git source at the 1.2 tag

**Comment by AltGr** [comment]
(note: you can use `opam list '*ocaml-android*'`, or opam search, rather than grep)

It's weird because the error you get is an error from the solver, that normally happens when you specify unsatisfiable version constraints. Opam would have failed earlier if no package by this name existed. Care to include `opam config report` ?

**Comment by nobrowser** [comment]
I have

OPAMUSEINTERNALSOLVER=1

would that make a difference?

**Comment by AltGr** [comment]
Yes, please try with the external solver (e.g. aspcud). `config report` ?

**Comment by whitequark** [comment]
@nobrowser Your problem is that you're trying to use a 32-bit compiler on a 64-bit switch. This won't work; do `opam switch 4.02.3+32bit` first.
