### ISSUE TITLE
OPAM does not honor & constraints in depend flags

### ISSUE THREAD

**Issue by vbmithr** [ocaml/opam#2227]
https://github.com/ocaml/opam-repository/pull/4325

It seems that OPAM does not care about a dep marked `{build & test}`.

**Comment by AltGr** [comment]
Are you wanting `{build | test}` ? I'm afraid it's indeed unsupported at the moment, so you have no choice but to duplicate:
```
"ounit" {build}
"ounit" {test}
```

However, in the current specification, `build` only avoids recompilations, and still guarantees the dependency is always installed, so the only difference with adding the `{test}` line is that you'll re-run the tests with the new version of ounit if it gets upgraded and you were running with `--test`. I guess you'll be fine with just `{build}`.

**Comment by AltGr** [comment]
Closing because of #2771 
Just remember that in `depend {filter}`, the filter part is a condition for the dependency to hold.
