### ISSUE TITLE
Wrong formula in conflict message

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam#2229]
```
$ mkdir -p /tmp/p; echo 'opam-version: "1.2" depends: "ocp-indent" { >= "2" | < "0.1" }' >/tmp/p/opam
$ opam pin add test-conflicts.1 /tmp/p
[...]
The following dependencies couldn't be met:
  - test-conflicts -> ocp-indent (< 0.1 & >= 2)
Your request can't be satisfied:
  - ocp-indent<0.1 is not available because the package is pinned to /home/lg/ocamlpro/ocp-indent, version 1.5.1.
  - ocp-indent>=2 is not available because the package is pinned to /home/lg/ocamlpro/ocp-indent, version 1.5.1.
```

The message refers to `(< 0.1 & >= 2)` while it was an `|` in the original constraint. Otherwise it's fine (in particular the two reasons following). [This](https://github.com/ocaml/opam/blob/c93132e707258a19281ad67a66495ba65751a080/src/solver/opamCudf.ml#L276-L348) is probably the function in cause ; but it's quite complex already (it gathers all dependency chains returned by Dose in order to aggregate them for a concise message).
It may be difficult to retrieve the original logical operator, as Dose returns a list of chains without connection between them.

**Comment by kit-ty-kate** [comment]
This has been fixed at some point in the past 9 years. As of 2.3.0 opam outputs either:
```
[ERROR] Package conflict!
  * Missing dependency:
    - test-conflicts → ocp-indent >= 2
    no matching version

No solution found, exiting
```
or
```
[ERROR] Package conflict!
  * Missing dependency:
    - test-conflicts → ocp-indent >= 1.8
    not available because the package is pinned to version 1.5.1

No solution found, exiting
```
Depending on the version of ocp-indent installed.
