### ISSUE TITLE
Add a way to clear the archive caches

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#2235]
Currently, opam stores some cache at the following places:
- Normally all the build files should already be cleaned-up, but it that's not the case the files live in `~/.opam/<switch>/build`
- The globally cached archive are stored in `~/.opam/archives`
- The repository archives are stored in `~/.opam/repo/<repo-name>/archives`
- If you have local pins, you could find some of the archives in `~/.opam/<switch>/packages.dev/<pkg-name>`

Would be nice to have a command to clear all of them.

**Comment by UnixJunkie** [comment]
related to https://github.com/ocaml/opam/issues/1269

**Comment by amirmc** [comment]
Is this still a pending feature?  I found my way here via a google search for `clear opam archive cache` :)

**Comment by UnixJunkie** [comment]
After an opam install of many things, it would be nice to be able to reclaim some space...

**Comment by AltGr** [comment]
Implemented by #2791
