### ISSUE TITLE
Precedence in .install files

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam#2242]
When creating a (static) `.install` file, one cannot know in advance whether the target platform will support both byte and native compilation.  Thus one is force to use:

```
  "?_build/src/server/libres3_report.byte" {"libres3_report"}
  "?_build/src/server/libres3_report.native" {"libres3_report"}
```

Can it be assumed that, because it comes second, the native code version will take precedence in case both exist?  It would also be nice to specify that behavior [in the manual](http://opam.ocaml.org/doc/Manual.html#packagenameinstall).

**Comment by dbuenzli** [comment]
> It would also be nice to specify that behavior in the manual.

I think we should avoid this. The build system should generate a precise `.install` file. This makes `.install` declarative manifest files rather than the description of a sequential install procedure.

**Comment by AltGr** [comment]
I agree with leaving this unspecified (or even forbidding it), to push the issue to the build system where it belongs.
