### ISSUE TITLE
opam file format add a syntax for field extension

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#2254]
opam should allow fields of the form `x-IDENT:` to exist in `opam` files without opam having an opinion about them. It could be for example useful to replace these new `findlib` files that seem to be creeping in the opam repository for whatever reason.

**Comment by rgrinberg** [comment]
+1

**Comment by AltGr** [comment]
Sounds like a good idea, and there should be no difficulty to implement. The field will just have to parse correctly, and the corresponding record (`OpamFile.OPAM.t`) may hold a string map containing the fields' syntax structures.

**Comment by AltGr** [comment]
The chance should also be taken to remove obsolete, legacy fields that nobody knows of:
- `libraries: `, `syntax:` these were intended for planned findlib implementation/replacement I think, but never got used. They contain filtered string lists.
- `configure-style:` the field name is accepted but not bound anywhere it seems.
- `build-env:` would allow to provide specific environment variables for the package's command I guess, but not implemented.

Not yet completely sure about the usefulness of `build-env`, but the others should probably be removed. If you have any use for them speak now!

**Comment by AltGr** [comment]
My bad, `build-env` _is_ honored, albeit in build only, just unused.
