### ISSUE TITLE
opam doesn't allow man location to appear later in MANPATH

### ISSUE THREAD

**Issue by aw1621107** [ocaml/opam#2256]
Related to/same thing as #2159, I think? I'm on 1.3.0-dev installed from homebrew, OS X 10.11, ocaml 4.02.2. Issue says fixed, but doesn't seem to be the case for me...

I have this in my `~/.profile`, which is sourced by `~/.bash_profile`:

    MANPATH=
    export MANPATH
    eval $(/usr/libexec/path_helper -s)
    export PATH=$(brew --prefix coreutils)/libexec/gnubin:$PATH
    export MANPATH=$(brew --prefix coreutils)/libexec/gnuman:$MANPATH

It's to get around some funky things with GNU coreutils, without which man pages sort of break, so I'd like to keep that if possible. Changing things to source `~/.profile` after opam init (and taking out the first line to not overwrite opam's config) instead of before doesn't seem to change anything.

(Also, minor annoyance, the leading colon that opam produces on the manpath looks out of place when nothing else is added. Not experienced enough to say if it's incorrect, though)

Doing the same thing as the reporter in the other issue results in this:

    $ opam switch
    $ env > pre
    $ eval `opam config env`
    $ env > post
    $ diff -U 0 pre post

 ...

    -MANPATH=/usr/local/opt/coreutils/libexec/gnuman:/usr/share/man:/usr/local/share/man:/opt/X11/share/man:/Library/TeX/Distributions/.DefaultTeX/Contents/Man:/Users/awang/.opam/system/man
    +MANPATH=/Users/awang/.opam/system/man:/usr/local/opt/coreutils/libexec/gnuman:/usr/share/man:/usr/local/share/man:/opt/X11/share/man:/Library/TeX/Distributions/.DefaultTeX/Contents/Man

**Comment by AltGr** [comment]
Hm, there is an option to change the PATH in-place, rather than prepend the opam path (i.e. an element that points below the current opam root (`~/.opam`) is replaced, rather than removed and the new path prepended). It should be possible to use the same behaviour for MANPATH when the option is specified.

But I am curious why having the opam manpath first in the list might break.

> (Also, minor annoyance, the leading colon that opam produces on the manpath looks out of place when nothing else is added. Not experience enough to say if it's incorrect, though)

It's the normal way to tell the system to use the default path after that one is tried, rather than override it, AFAIK

**Comment by aw1621107** [comment]
Oh, didn't know about that was possible. How do you do it? If it's in the man page, must have overlooked it, and can't seem to find it on the opam webpage.

Didn't know about the leading colon thing either. So it's like prepending that bit to PATH? And would double colons created by later exports be bad?

**Comment by AltGr** [comment]
From `man manpath`:

>ENVIRONMENT
>       MANPATH
>              If $MANPATH is set, manpath displays its value rather than determining it on the fly.  If $MANPATH is prefixed by a  colon,  then  the value  of  the variable is appended to the list determined from the content of the configuration files.  If the colon comes at the end of the value in the variable, then the determined list is appended to the content of the variable.  If the value of the variable  contains a double colon (::), then the determined list is inserted in the middle of the value, between the two colons.
