### ISSUE TITLE
opam not upgrading vcs packages in some cases

### ISSUE THREAD

**Issue by ygrek** [ocaml/opam#2258]
See below  :
```
$ opam upgrade
The following actions will be performed:
  ↻  recompile devkit     git                 [upstream changes]
  ↻  recompile app        git                 [uses devkit]
===== ↻  2 =====
Do you want to continue ? [Y/n] 
^C
$ opam uninstall app
The following actions will be performed:
  ⊘  remove app git

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
⊘  removed   app.git
Done.
$ opam upgrade
Everything as up-to-date as possible (run with --verbose to show unavailable upgrades).
```
`app` depends on `devkit` from git, after pushing commits to `devkit` and doing `opam upgrade` it correctly wants to recompile `devkit` to pick up changes, but after removing one package that depends on this library subsequent `opam upgrade` forgets that library was updated and needs to be recompiled.

**Comment by AltGr** [comment]
hm, packages with upstream changes are stored in file `<switch>/reinstall` ; `opam remove` might reset it by mistake... I'll check, thanks for reporting!
