### ISSUE TITLE
"Could not fetch repo" for all git repos

### ISSUE THREAD

**Issue by holocronweaver** [ocaml/opam#2262]
Hi, new Ocaml user here.

On Ubuntu 15.04 x64 I attempted to add a Github repo using the command provided by the repo maintainer:
`opam repository add android git://github.com/whitequark/opam-android`
The command would hang indefinitely at the `Processing` line. Using `--verbose --debug` flags produced no useful information related to the hang from what I could see. I tried to add a dozen other repos the same way and the commands stalled the same way, including projects hosted by bitbucket. I also enabled ssh LogLevel 3, but no ssh related messages appeared when attempting to add a repo, so I don't think ssh is the problem.

So I switched to Mac OS X 10.10 and attempted to add the same repo. No hang this time, but I received back the message, `[ERROR] Could not fetch repo`. Again, I tried a dozen repos using multiple methods (http, https, git:) and enabled ssh log debugging and got no clues. FWIW, [here is the debug+verbose output from the command](https://gist.github.com/holocronweaver/8ac32aed037764b64270).

I have no trouble with networking or interacting with Github via ssh outside of opam. Really stumped as to what could be causing this.

On both systems I am using git 2.4.5. My colleagues are using the same version and aren't having the issue. They also have the exact same Ubuntu and OS X versions I have.

**Comment by dbuenzli** [comment]
> Hi, new Ocaml user here.

Welcome. 

Just tried with opam 1.2.2 and git 2.4.4 with the line you gave and can't reproduce . Could you maybe provide the output of `opam config report`.

**Comment by holocronweaver** [comment]
Sure, here you go:
```
# OPAM config report
# opam-version    1.2.2
# self-upgrade    no
# os              darwin
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            4
# repositories    1* (http)
# pinned          0
# current-switch  4.02.1+32bit
# last-update     2015-07-19 02:12
```

**Comment by dbuenzli** [comment]
Mmh, I have no clue. The only difference with me here is that your switch is `4.02.1+32bit` and mine is `4.02.1`. Fundamentally this should have no effect but could you maybe try to `opam switch 4.02.1` and retry. Also can you `git clone` the repo manually somewhere ?

**Comment by holocronweaver** [comment]
>try to opam switch 4.02.1 and retry.

No change.

> can you git clone the repo manually somewhere ? 

Done, and I manually added the repo successfully this way. I guess as long as I `git pull` from this repo i can stay up to date? Still would like to know why the remote add is failing.

**Comment by dbuenzli** [comment]
> Still would like to know why the remote add is failing.

It is indeed very puzzling. Did you add the new repo under the same name ? I was thinking about permissions problems in `.opam/repo`, maybe you should try to wipe out the `.opam` directory and start over.

**Comment by holocronweaver** [comment]
> Did you add the new repo under the same name?

Yep!

> try to wipe out the .opam directory and start over

I had tried this before to no effect. I don't think it is a permissions issue since this is occurring on both Ubuntu 15.04 and Mac OS X which are on totally different drives and have different FS types, and none of my colleagues with the same setup had the problem.

I don't understand enough Ocaml to be confident, but this is where the problem occurs:
```
  try
    let t = OpamProcess.Job.run (update t repo) t in
    fix_descriptions t
  with
  | _ ->
    cleanup t repo;
    OpamConsole.error_and_exit "Could not fetch repo"
```
I could try debugging that with some guidance.

**Comment by dbuenzli** [comment]
I don't have much clues at that point maybe @AltGr will have an idea. Meanwhile you could try to post a gist with `--verbose --debug --debug-level=100` exhibiting the problem.

**Comment by holocronweaver** [comment]
Ok, I updated [the gist log](https://gist.github.com/holocronweaver/8ac32aed037764b64270) with that `debug-level`. I notice the line `Cannot find /Users/jesse/.opam/4.02.1+32bit/reinstall` appears just before the `Could not fetch repo` message. Might that be the problem?

**Comment by holocronweaver** [comment]
I figured out the problem. My git config has a couple git hooks, one of which is supposed to prompt me for the credentials I wish to use that repo (since I have use a different e-mail address in different contexts). Apparently opam was stalling on the prompt and never showed it to me, so I had no idea what was happening.

If possible, I would hope git hooks are obeyed and opam doesn't block on them, but I am not really sure how opam should accomplish this.

The troublesome git hook is [git-passport](https://github.com/frace/git-passport), in case you want to reproduce.

**Comment by AltGr** [comment]
Thanks for reporting and investigating this!
Indeed, having interactive programs called during fetch isn't well supported; I am not sure how we could handle this properly without giving up on parallel downloads. Note that you don't even need hooks to get the problems, if you have repositories using e.g. `git+ssh://` they may need a password.

One "solution" is to run these commands with no access to the terminal or stdin: then they should fail rather than hang, which is probably a better behaviour...

On the output: since recently, opam has verbosity levels, to see fetch commands you need to specify at least `-vv` (the single verbosity mode being intended to mostly debug package scripts)

**Comment by holocronweaver** [comment]
> One "solution" is to run these commands with no access to the terminal or stdin

I am guessing you have a method in mind to accomplish this? If it is trivial enough, I'd appreciate it if let me make the changes by pointing me in the right direction. A learning exercise of sorts to make me more comfortable with OCaml and contributing to opam.

**Comment by AltGr** [comment]
Well `repository/opamGit.ml` uses `OpamSystem.make_command`, which already has an optional argument `allow_stdin`, so this would be quite trivial -- there is some investigation needed, though, as parallel runs should already use `allow_stdin:false` as a default (`OpamProcess.background_run` as compared to `OpamProcess.run`)
The code of `OpamProcess` and `OpamParallel` is non-trivial though.

Contributions are always appreciated!
