### ISSUE TITLE
Add `{build,run}-benchmark` and a `benchmark` filter ?

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#2278]
@xavierleroy is suggesting this in this comment https://github.com/ocaml/ocaml/pull/226#issuecomment-128280325. Is it worth making this different from the testing support ?

**Comment by avsm** [comment]
Yeah, benchmarks are normally longer running and require a stable reproducible setup. It's definitely a different mode than testing.  I currently abuse the Alcotest interface by putting benchmarks in as `Slow` tests.

**Comment by dbuenzli** [comment]
I once discussed this with @pqwy who is kind of a benchmarking freak and IIRC the outcome of the discussion was that with lack of control over benchmark setup and knowledge of the specifics of the benchmarks such a feature would likely lead people to make wrong inferences. 

It seems that for the compilers, controlled benchmark suites like OCamlPro's `operf-{micro,macro}` are better suited to this.
