### ISSUE TITLE
feature request: new option for opam switch

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#2279]
Would it be possible to not need to do eval `opam config env`
after an opam switch command?
That would be nice: new users to opam wish this behavior.

**Comment by avsm** [comment]
Unfortunately not. There is no way to update an existing shell environment without going through the `eval` command.  See also `ssh-agent` or `docker-machine` or `gpg-agent` for other commands that share this problem.

**Comment by AltGr** [comment]
well if you did the shell install at init, you can run `opam-switch-eval <switch>` to do the switch and eval directly. This is a pre-loaded shell function.

**Comment by lefessan** [comment]
Better, you can use 'ocp-manager' or 'opam-manager' (reimplementation). It is a wrapper around all OCaml commands that automatically update the PATH after OPAM switch. Once installed, they are straight forward to use for beginners.

**Comment by UnixJunkie** [comment]
Thanks for all the proposals, I will tell users in my team.
