### ISSUE TITLE
Where is stdlib.h in opam installed switches?

### ISSUE THREAD

**Issue by michipili** [ocaml/opam#2296]
The file `stdlib.h` is used to prepare OCaml bindings, but it cannot be found in opam managed compiler switches:

```console
% find "${OPAMROOT}" -name stdlib\*
/opt/opam/4.02.3/lib/ocaml/stdlib.a
/opt/opam/4.02.3/lib/ocaml/stdlib.cma
/opt/opam/4.02.3/lib/ocaml/stdlib.cmxa
/opt/opam/4.02.3/lib/ocaml/stdlib.p.a
/opt/opam/4.02.3/lib/ocaml/stdlib.p.cmxa
/opt/opam/4.02.3/lib/ocaml/vmthreads/stdlib.cma
/opt/opam/4.02.3/lib/stdlib
```

----
<smaller>
Environment
```
% opam --version
1.2.1
```
</smaller>

**Comment by avsm** [comment]
stdlib.h is part of the C standard interface; not OPAM/OCaml

See https://en.wikibooks.org/wiki/C_Programming/C_Reference/stdlib.h

**Comment by michipili** [comment]
Okay, so I guess the responsible is programming late an night on the weekend. Let's turn our attention to something else.  Thank you for the nice & patient answer, though! :)
