### ISSUE TITLE
removing dependency marked with {build} removes the package too

### ISSUE THREAD

**Issue by ygrek** [ocaml/opam#2297]
consider : 
```
$ opam remove mybuild
The following actions will be performed:
  ⊘  remove sqlgg   0.3.0*                    [uses mybuild]
  ⊘  remove mybuild 2     
===== ⊘  4 =====
Do you want to continue ? [Y/n] 
```
```
$ opam info --raw sqlgg | grep mybuild
  "mybuild" {build}
```

My understanding is that `{build}` marks dep as only used during build and it can be removed after the package is installed without affecting the package

**Comment by ygrek** [comment]
opam version 1.2.2

**Comment by AltGr** [comment]
Yes, this is the expected behaviour.
See https://github.com/ocaml/opam/issues/1231#issuecomment-48709126 for the explanation why. Basically, you could end up with a set of package that isn't installable in a single step, and we don't want to support that.

**Comment by ygrek** [comment]
I see, it's a pity, though understandable.
