### ISSUE TITLE
opam init fails - Ubuntu Vivid 15

### ISSUE THREAD

**Issue by QuinDennis** [ocaml/opam#2298]
I've tried installing opam from Software Center, .debs, ocamlbrew,... 

 tried https://launchpad.net/~avsm/+archive/ubuntu/ppa/+build/7793985/+files/opam_1.2.2-1ppa2~vivid_amd64.deb

  opam init always fails reporting opam version is 1.1.1 , needs to be 1.2, but everything I try to install doesn't change the opam --version number from 1.1.1.

[WARNING] Errors while parsing conduit.0.8.0 OPAM file, skipping.
[ERROR] Your version of OPAM (1.1.1) is not recent enough to read ~/.opam/repo/default/packages/conduit/conduit.0.8.1/opam. Upgrade OPAM to a more recent version (at least 1.2) to read this file correctly.

**Comment by avsm** [comment]
What is `opam --version` telling you?

**Comment by QuinDennis** [comment]
1.1.1, no matter what I do, what I install, the version # doesn't change.

Thanks for your reply!

On 09/04/2015 01:16 PM, Anil Madhavapeddy wrote:
>
> What is |opam --version| telling you?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ocaml/opam/issues/2298#issuecomment-137810281>.
>

-- 
Quin Dennis | t: 512.392.8619

**Comment by AltGr** [comment]
You're probably not using the opam version installed through the package manager, check `which opam`

**Comment by usefulalgorithm** [comment]
`opam init https://opam.ocaml.org/1.1`

**Comment by AltGr** [comment]
@usefulalgorithm: this will tell opam to use our backported package repository, which is there to maintain compatibility with 1.1 systems. However, we're dropping support, which means you won't get any more package updates on that repository. So if installing opam 1.2 is at all possible, it would be a much better solution.

See the related FAQ entry: http://opam.ocaml.org/doc/FAQ.html#Gaspopaminitgivesmescreensfullsoferrorsaboutupgrading
