### ISSUE TITLE
Avoid adding trailing slash to URLs

### ISSUE THREAD

**Issue by kayceesrk** [ocaml/opam#2300]
I have a twitter shortened URL https://t.co/oePZwHTXMc which resolves to https://github.com/ocamllabs/opam-repo-dev. When I do

    opam remote add ocl -k git https://t.co/oePZwHTXMc

I get

    ....
    ### stderr ###
    # fatal: repository 'https://t.co/oePZwHTXMc/' not found

Opam adds a trailing slash to the URL. https://t.co/oePZwHTXMc/ returns me a 404. It seems to be quite common to have different contents served on / and no-/ URLs [1]. Opam should treat it as such.

[1] http://googlewebmastercentral.blogspot.co.uk/2010/04/to-slash-or-not-to-slash.html

opam config report
-------
    # OPAM status report
    # opam-version    1.2.0
    # self-upgrade    no
    # os              darwin
    # external-solver aspcud
    # criteria        -count(removed),-notuptodate(request),-count(down),-notuptodate(changed), count(changed),-notuptodate(solution)*
    # jobs            1
    # repositories    1* (http), 1 (version-controlled)
    # pinned          0
    # current-switch  4.03.0+effects
    # last-update     2015-09-10 11:39

**Comment by AltGr** [comment]
It's `git`'s behaviour:
```
% git clone http://t.co/oePZwHTXMc
Clonage dans 'oePZwHTXMc'...
fatal: repository 'http://t.co/oePZwHTXMc/' not found
```
opam doesn't rewrite the url in this case, not sure what we could do.
