### ISSUE TITLE
opam should verify compiler archive checksum

### ISSUE THREAD

**Issue by whitequark** [ocaml/opam#2301]
I've just discovered that it doesn't and I can only say one thing about it: WTF?! Seriously, not even md5?

**Comment by cfcs** [comment]
Sounds related to integrity checking / package signing in general.

That is:

https://github.com/ocaml/opam/issues/2182

https://github.com/ocaml/opam/issues/423

https://github.com/ocaml/opam/issues/2006

https://github.com/ocaml/opam/issues/563

https://github.com/ocaml/opam/issues/408
