### ISSUE TITLE
"os" value should always be taken from $opam/$SWITCH/config/global-config.config

### ISSUE THREAD

**Issue by db4** [ocaml/opam#2304]
I have cygwin-build opam which I use to manage the native Win32 ocaml toolchain. So I manually changed `os: "cygwin"` in $opam/$SWITCH/config/global-config.config to `os: "win32"`. Now filters are evaluated correctly:
```
patches: ["win32.patch" {os = "win32"}]
```
but not the os field itself:
```
os: ["win32"] # not satisfied: os expands to "cygwin"
```
This is because in the latter case "os" is taken from OpamStd.Sys.os_string instead of the config file. I believe it should be fixed.

**Comment by AltGr** [comment]
Indeed; note that the `os:` field is deprecated, though, and you should use the `available:` field instead. It is based on the same variable and thus exposes consistent behaviour:

    available: [os = "win32"]

**Comment by AltGr** [comment]
(note: the above is part of the pending automatic rewrites that are delayed until we deprecate 1.1, which should be soon)

**Comment by db4** [comment]
Thank you, `available:` is enough so you can close the issue. One more wish: can you introduce a `toolchain` variable having by default the same value as `$(TOOLCHAIN)` in OCaml compiler config? That would allow to apply toolchain-specific patches etc.

**Comment by dbuenzli** [comment]
> One more wish: can you introduce a toolchain variable having by default the same value as $(TOOLCHAIN) in OCaml compiler config? That would allow to apply toolchain-specific patches etc.

That would indeed be useful for the windows ports e.g. for determining file extensions. But its name should be more precise than `$(TOOLCHAIN)`, especially in the context of compiler as packages. Besides do you know the difference between `CCOMPTYPE` and `TOOLCHAIN` ?

**Comment by db4** [comment]
> That would indeed be useful for the windows ports e.g. for determining file extensions. But its name should be more precise than `$(TOOLCHAIN)`, especially in the context of compiler as packages. 

Well, the name is entirely up to you. What about `ocaml_toolchain`?

> Besides do you know the difference between `CCOMPTYPE` and `TOOLCHAIN` ?

`CCOMPTYPE` is the family of C compiler. Can be `cc` or `msvc`. `TOOLCHAIN` as also OS-dependent. Some examples:
```
Linux/gcc:
TOOLCHAIN=cc
CCOMPTYPE=cc
```
```
Windows/cygwin:
TOOLCHAIN=cc
CCOMPTYPE=cc
```
```
Windows/mingw:
TOOLCHAIN=mingw
CCOMPTYPE=cc
```
```
Windows/msvc:
TOOLCHAIN=msvc
CCOMPTYPE=msvc
```

**Comment by AltGr** [comment]
The idea is to actually make opam more generic in this respect, by allowing compilers¹ to define their own variables. Then it should be a convention on the opam-repository to have compilers export these variables ; this mechanism would replace specific handling code for variables such that `ocaml-native-tools` as well, which doesn't have to be checked dynamically since it's a constant of the compiler.


¹ "compiler", by which I mean in the extended sense: "something you can `opam switch` to"
