### ISSUE TITLE
Mechanism for updating and upgrading a number of switches

### ISSUE THREAD

**Issue by amirmc** [ocaml/opam#2305]
I just wondered what others think of a feature where it's possible to update/upgrade a number of switches in one step.

I'm thinking something along the lines of:
`$ opam update -u --all-of-the-switches-no-seriously!`
(that second flag is just some suggested text)

Such a command would step through the switches and upgrade the packages found there, returning to the original switch once done (you should be able to specify a subset of switches too).

My reason for this is that I typically keep a separate switch for different projects (usually aliases of `system`), which have different packages installed.  Occasionally, I'd just like to upgrade everything at once.  Just FYI, at the moment I have switches called `mirage`, `cosmetrics`, `ocamlorg` and `core`.

Of course, this might be a dumb idea but it would be nice to know how dumb :)

**Comment by avsm** [comment]
you could build this as a shell script plugin

something like:

```
#!/bin/sh -e
# opam-switches
shift
for s in `opam switch list -s`; do
   opam --switch $s $*
done
```

(untested)

and then `opam switches update -u` should work

**Comment by amirmc** [comment]
> for s in `opam switch list -s`; do

I think this line needs to be:
```for s in `opam switch list -s -i`; do```
which filters for only the installed switches.

I wasn't aware of the `--switch` flag. That makes things a lot simpler.

I'll try it out when I'm feeling brave and report back. :)

**Comment by abate** [comment]
hi, I'm working with @AltGr toward the integration of this functionality (and others) in opam. The general idea is to feed the solver with an higher level description of the opam universe, that will enable it to compute an upgrade-all solution spanning all packages on all installed switches. I'm in the integration phase at the moment. I'll send a public branch for testing in the next couple of months (or before). In the mean time a shell script should do it...

**Comment by Drup** [comment]
@abate That sounds amazing. I will be quite happy to test that!

**Comment by lefessan** [comment]
Indeed, Pietro (@abate) is working at INRIA/IRILL with me and Roberto to improve Dose, in a first time, and OPAM, in a second time, to be able to define multi-switch constraints (see the poster at OCaml'2014). The work on Dose is done and well-tested (to handle multi-switches universes), and he is now working with @AltGr to have OPAM use that new version of Dose, that will be able to implement "upgrade-all", but we hope also cross-compilation switches and other use-cases from the poster.
