### ISSUE TITLE
fatal: No path specified. See 'man git-pull' for valid url syntax

### ISSUE THREAD

**Issue by zoggy** [ocaml/opam#2312]
Hello,

I'm setting up a private opam repository. It lives in a directory. I added a package, with  a `url` file like the following:
````
git: "git+ssh://gitosis@git.foo.net:dynamow.git#dynamow2"
````
Then I added my opam repo and updated it:
````sh
opam repo add myrepo /path/to/my/repo
opam update myrepo
````
When I try to install this package (called dynamow.2.0+dynamow2), I get the following errors:
````
[dynamow: from myrepo] Repo archive not found
[dynamow: git] Command started
+ git "fetch" "-q" "origin" "+dynamow2:refs/remotes/opam-ref" (CWD=/home/zoggy/.opam/packages.dev/dynamow.2.0+dynamow2)
- fatal: No path specified. See 'man git-pull' for valid url syntax
[dynamow: git] Command started
+ git "fetch" "-q" "origin" (CWD=/home/zoggy/.opam/packages.dev/dynamow.2.0+dynamow2)
- fatal: No path specified. See 'man git-pull' for valid url syntax
[ERROR] The sources of the following couldn't be obtained, aborting:
          - dynamow.2.0+dynamow2
        (This may be fixed by running 'opam update')
'opam install -v -v -v dynamow' failed.

````
Did I forget to something ?

**Comment by AltGr** [comment]
What versions of opam and git ?
it seems that something might have failed during the initialisation at /home/zoggy/.opam/packages.dev/dynamow.2.0+dynamow2 ; can you check what is there ? Is it reproductible if you remove the directory and try the install again ?

Thanks!

**Comment by zoggy** [comment]
````
$ opam --version
1.2.2
$ git --version
git version 1.9.1
````
Removing the directory does not change anything. It is recreated with only a `.git` directory in it. Could it be due to the git repository path being not an absolute one but relative to the user home directory ?  (not `git://git.foo.net/path/to/dynamow.git#dynamow2` but `git+ssh://gitosis@git.foo.net:dynamow.git#dynamow2`)

**Comment by zoggy** [comment]
````
$ cd /home/zoggy/.opam/packages.dev/dynamow.2.0+dynamow2
$ cat .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = git+ssh://gitosis@git.foo.net:dynamow.git
	fetch = +refs/heads/*:refs/remotes/origin/*
````
(git.foo.net is not the real name, of course)

**Comment by AltGr** [comment]
Thanks. git doesn't like the `git+ssh://` syntax, and it shouldn't have been passed to the command for git initialisation : the prefix should have been stripped.
You'll have to fall back to the older `git: "git@..."` without the full url for now.

I have a rewrite pending for the url-parsing code that sanitises a bit how we handle this, but it's still too buggy to be merged at the moment. It removes the need for the various, mutually exclusive field names (`git:`, `src:`, `darcs:`...) in favor of the url syntax.

**Comment by zoggy** [comment]
Indeed, using
````
git: "gitosis@git.foo.net:dynamow.git#dynamow2"
````
works well. Thanks !
