### ISSUE TITLE
custom subcommands are broken

### ISSUE THREAD

**Issue by whitequark** [ocaml/opam#2316]
To reproduce:
```
$ opam --version
1.2.2
$ opam install opam-query
[NOTE] Package opam-query is already installed (current version is 1.2).
$ opam query
opam: unknown command `query'.
Usage: opam COMMAND ...
Try `opam --help' for more information.
$ opam-query
$
```

**Comment by AltGr** [comment]
Please check where opam-query has been installed and if your environment is up-to-date: I remember fixing lookup so that it looks in the appropriate PATH for the current switch, but this may have been after 1.2.2 was released.

Thanks for reporting!

**Comment by whitequark** [comment]
Yes, it is up-to-date:
```
$ opam config list |grep prefix
prefix               /home/whitequark/.opam/4.02.3
$ which opam-query
/home/whitequark/.opam/4.02.3/bin/opam-query
```

Even weirder, it changes behavior under strace (!):
```
$ opam query
opam: unknown command `query'.
Usage: opam COMMAND ...
Try `opam --help' for more information.
$ strace -eexecve opam query
execve("/usr/bin/opam", ["opam", "query"], [/* 69 vars */]) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=948, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=950, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
execve("/home/whitequark/.opam/4.02.3/bin/opam-query", ["opam-query"], [/* 70 vars */]) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=951, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
opam-query: internal error, uncaught exception:
            # opam-version    1.2.0
            # os              linux
            File /home/whitequark/opam does not exist
            Raised at file "core/opamSystem.ml", line 26, characters 10-30
+++ exited with 1 +++
```

I have no clue why is opam-query trying to look into ~/opam, this seems to be some kind of opam-lib bug... and in fact it didn't do that the previous time I compiled opam-query (see 1st comment; I rebuilt everything just now). This is really weird.

**Comment by whitequark** [comment]
Yes, it is up-to-date:
```
$ opam config list |grep prefix
prefix               /home/whitequark/.opam/4.02.3
$ which opam-query
/home/whitequark/.opam/4.02.3/bin/opam-query
```

Even weirder, it changes behavior under strace (!):
```
$ opam query
opam: unknown command `query'.
Usage: opam COMMAND ...
Try `opam --help' for more information.
$ strace -eexecve opam query
execve("/usr/bin/opam", ["opam", "query"], [/* 69 vars */]) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=948, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=950, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
execve("/home/whitequark/.opam/4.02.3/bin/opam-query", ["opam-query"], [/* 70 vars */]) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=951, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
opam-query: internal error, uncaught exception:
            # opam-version    1.2.0
            # os              linux
            File /home/whitequark/opam does not exist
            Raised at file "core/opamSystem.ml", line 26, characters 10-30
+++ exited with 1 +++
```

I have no clue why is opam-query trying to look into ~/opam, this seems to be some kind of opam-lib bug... and in fact it didn't do that the previous time I compiled opam-query (see 1st comment; I rebuilt everything just now). This is really weird.

**Comment by whitequark** [comment]
Ok, WTF. There are two issues here.

The first one, which serves mainly to obscure debugging, is that opam seems to only self-upgrade when invoked as `opam` and not `/usr/bin/opam`.

The second one was opam-query being built with opam-lib=1.2.0, because you have constrained opam-query to 1.2.0 for some reason I do not comprehend. It builds just fine with 1.2.2.

**Comment by whitequark** [comment]
The last strace entries before opam claims that opam-query doesn't exist are the following:
```
open("/home/whitequark/Work/opam-query/opam", O_RDONLY) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
lseek(3, 0, SEEK_CUR)                   = 0
read(3, "opam-version: \"1.2\"\nname: \"opam-"..., 65536) = 614
read(3, "", 65536)                      = 0
stat("git://github.com/whitequark/opam-query", 0x7ffe54850670) = -1 ENOENT (No such file or directory)
```
What?

**Comment by whitequark** [comment]
Ok, I figured it out. On my machine, opam is a function:
```
$ type opam
opam is a function
opam () 
{ 
    $(which opam) $* && if [ "$1" = "switch" ]; then
        eval $($(which opam) config env);
    fi
}
```
Thus, opam is actually always invoked as `/usr/bin/opam`. And when it is invoked as `/usr/bin/opam` instead of `opam`--note that only the `Sys.argv.[0]` is different, the actual executable is the same, as you can see in the strace logs above--for some reason it cannot find the plugin.

**Comment by AltGr** [comment]
Hm, thanks for the detailed reports!
Indeed, I thought it was a better idea not to hardcode the "opam-" prefix and use `Filename.basename Sys.argv.(0)` instead ; in case we would like to have some opam variants with different names at some point maybe -- but it turns out that was quite ill-advised (I myself use `opam.1.1.1`, etc. binaries for quick access to earlier versions when testing is needed).

It's weird that the `basename` didn't make it work though...
The culprit code is here: https://github.com/ocaml/opam/blob/ff0fa0f64267da2fa8f6adeb22086ba642eb8d0c/src/client/opamMain.ml#L1412-L1421

**Comment by whitequark** [comment]
Thanks!
