### ISSUE TITLE
plugins prefixed with opam- should be recognized for automatic installation

### ISSUE THREAD

**Issue by whitequark** [ocaml/opam#2318]
I can see that opam-publish was renamed to publish so that `opam publish` automatically installs the plugin. But this just unnecessarily pollutes the namespace; I would like `opam query` to do the same (indeed, lack of the installed plugin has screwed up my publication process a few times already) but I do not want to squat the very generic name "query", which is certainly useful for something else.

**Comment by avsm** [comment]
see http://lists.ocaml.org/pipermail/opam-devel/2015-August/001165.html <http://lists.ocaml.org/pipermail/opam-devel/2015-August/001165.html> for related discussion on same topic.

**Comment by whitequark** [comment]
Relevant message: http://lists.ocaml.org/pipermail/opam-devel/2015-August/001184.html

I think a very easy and reasonable change is to have stub `publish` and `depext` and maybe even `query` packages, whereas the actual command would live under `opam-publish` etc. That would at least make it clear why the names are taken.

**Comment by AltGr** [comment]
Yes, we indend to prefer `opam-*` packages, following the previous discussions, but the renaming was required for compatibility with opam 1.2. As for the renamings, this sounds like a good idea during the migration period, indeed.
