### ISSUE TITLE
when upgrading a package, opam removes the old one before the latest version is even compiled

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#2319]
This is quite optimistic.
In case the latest version doesn't compile, it is not necessary to remove the previous one.
I understand the current behavior is:
uninstall old package; try to compile new package; install new package
A better approach might be:
try to compile new package; remove old package; install new package
The sequence being interrupted as soon as a step failed.
The idea comes from a Gentoo user.

**Comment by AltGr** [comment]
Good idea indeed. This would be quite easy to implement with the new action graph, that separates build from install actions, and minimises the consequences of failures: just insert remove actions at different points in the graph.

However, in the current state of the repository, most packages don't yet separate properly their `build` and `install` fields. While we need to get there (e.g. to track files and provide clean removal), with packages installing as part of their build and `ocamlfind` failing on already installed packages, the consequences would be disastrous currently.

Note also that this will only improve the situation at the roots of the dependency tree: if b depends on a and you recompile a, you'll still need to remove b before removing a before reinstalling a before trying to recompile b. So you only win if a fails to compile (which is already a real good thing!)

Thanks for the idea!

**Comment by AltGr** [comment]
(we'd also need to be careful that build and remove don't use the same source directory, so that remove doesn't reset it after the package was built. For the cases where removal needs the source...)

The situation would be better if we had only had an `install` field and added the `build` step.

**Comment by AltGr** [comment]
With this done properly, we could also handle downloads in the same pass as builds, while keeping the guarantee that a failed download can't cause unwanted removals. It wouldn't be a huge gain in terms of parallelism though.

**Comment by cfcs** [comment]
I run into this problem quite often, usually when people fail to declare correct dependencies (both opam pkgs and system binaries/libraries/headers).

It's quite annoying when the updated pkg is a dependency for many others, since that causes them to be removed in turn, starting an avalanche of deletion that renders the build environment limb. So a :+1: from me on getting this issue resolved!

**Comment by AltGr** [comment]
Implemented a while ago (credits to @hnrgrgr) now, and it's quite awesome. Thanks for the suggestion!
