### ISSUE TITLE
Installation documentation (README.md) is confusing

### ISSUE THREAD

**Issue by MSoegtropIMC** [ocaml/opam#2322]
Dear OPAM Team,

as ocaml beginner I compiled opam on cygwin. I found that some parts of the README are more confusing than helpful:

* Run `make lib-ext` as advertised by `./configure` if you don't have the
  dependencies installed and only need the opam binary (not the libs). This will
  locally take care of all OCaml dependencies for you.

* Otherwise, make sure to have ocamlfind, ocamlgraph, cmdliner, jsonm, cudf,
  dose 3.2.2+opam and re >= 1.2.0 installed. Or run `opam install
  opam-lib --deps-only` if you already have a working instance. Re-run
  `./configure` once done.

My problem (as an ocaml beginner) is that i simply don't know if I "only need the opam binary (not the libs)". Also this line from the opam readme:

* Run `make libinstall` if needed (this is incompatible with `make lib-ext`, as
  the opam library would conflict with installed versions of the dependencies)

is confusing, How shall I know if I need this or not?

In the end I came to the (I guess wrong) conclusion that it might be safer to follow the "Otherwise" path cited above and install the dependencies manually. But there are some dependencies (e.g. cmdliner) which can only be build using opam or by reverse engineering the opam build files, which is not that easy for an ocaml beginner. I had lengthy discussions with the cmdliner team if there shouldn't be a way to build opam dependencies without opam, but they refused any support for this, not even minor updates to the documentation (see https://github.com/dbuenzli/cmdliner/issues/34).

So in the end the "Otherwise" path mentioned above does not really work (without reverse engineering the build files of dependencies).

I would suggest that the opam readme file contains more information under which situations one "wants the libs" and needs to follow the "otherwise" path. As far as I can tell (with my limited beginner knowledge) it is fine to follow the "make lib-ext" or even the "make cold" path and to install whatever libs one might want with the resulting opam binary.

Would it make sense to completely remove the "Otherwise" path and the "make libinstall" section? Or say that if you magically have all dependencies, follow the "Otherwise" path with "make libinstall". If at least one of the dependencies is missing, follow the make ext-lib / no make libinstall path.

Best regards,

Michael

**Comment by AltGr** [comment]
Indeed, for the `libinstall`, it should at least be clearer that "if you don't know, you don't need it". You basically only need it if you plan to develop on opam itself or on related tools. The `make lib-ext` target is precisely here to help with bootstrapping and to avoid installing all deps by hand! So indeed it's just that bit of information that, it seems, was missing for you -- sorry about that!

Best of luck!

**Comment by MSoegtropIMC** [comment]
In this case I would suggest to change the comment in the Readme to:

•Run  make lib-ext  as advertised by  ./configure  if you don't have the
 dependencies installed and only need the opam binary (not the libs). This will
 locally take care of all OCaml dependencies for you. For just using opam the binary is sufficient - the libraries can be installed using opam later. The libs are only requried if you want to develop on opam itself.

Best regards,

Michael
