### ISSUE TITLE
Aspcud solver failed with inconsistent return value

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam#2323]
With the latest Debian upgrade (`aspcud 1:1.9.1-2`), I get the following error:
```
$ opam install pfff
[WARNING] External solver failed with inconsistent return value. Request saved
          to "/home/trch/.opam/log/solver-error-21149-1.cudf"
[ERROR] External solver failure, please fix your installation and check
        /home/trch/.opam/config and variable $OPAMEXTERNALSOLVER.
        You may also retry with option --use-internal-solver
```
When running `aspcud` on the CUDF file, I get
```
/usr/share/aspcud/misc2012.lp:142:53-54: info: global variable in tuple of aggregate element:
  D

/usr/share/aspcud/misc2012.lp:152:53-54: info: global variable in tuple of aggregate element:
  A

/usr/share/aspcud/misc2012.lp:152:49-50: info: global variable in tuple of aggregate element:
  P

/usr/share/aspcud/misc2012.lp:154:53-54: info: global variable in tuple of aggregate element:
  D

/usr/share/aspcud/misc2012.lp:154:49-50: info: global variable in tuple of aggregate element:
  P

/usr/share/aspcud/misc2012.lp:204:46-47: info: global variable in tuple of aggregate element:
  C

/usr/share/aspcud/misc2012.lp:206:46-47: info: global variable in tuple of aggregate element:
  C

clasp version 3.1.3
Reading from /tmp/gringo.outKpSLQu
Solving...
```
I have [filed a bug against the Debian package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=801169) but I also report it here because opam may want to distinguish between `aspcud` warnings and failures.

**Comment by dinosaure** [comment]
With [cudf_remote_proxy](http://cudf-solvers.irill.org/index.html) (add `solver: [ "cudf_remote_proxy" ]` in `$OPAMROOT/config`), this works fine.

**Comment by Chris00** [comment]
For the record, `aptitude install clasp/unstable` solved the problem.

**Comment by AltGr** [comment]
Thanks for the report :/

In case this happens again, we now support different solvers which may be used to work around such issues in the future:
http://opam.ocaml.org/doc/Install.html#ExternalSolvers
