### ISSUE TITLE
Print an error or warning if a key in opam file is duplicated

### ISSUE THREAD

**Issue by whitequark** [ocaml/opam#2324]
It took me several days to notice this bug:
```
opam-version: "1"
maintainer: "whitequark@whitequark.org"
patches: [ "ar-fix.patch" ]
substs: ["android.conf" "config/Makefile"]
patches: ["patches/ocamldoc.patch"]
```
Only the first `patches` is actually used.

**Comment by dbuenzli** [comment]
Please error or merge the fields, let's not go the way of json.

**Comment by whitequark** [comment]
I prefer error I think, merge does not sound universally useful enough to me.

**Comment by dbuenzli** [comment]
Merge is also more annoying to parse and more painful for good error report.

**Comment by avsm** [comment]
Error indeed.

**Comment by AltGr** [comment]
Good news: this is already supported by the new opam-file parser/printer implementation, just recently merged :)
As an error I mean.

**Comment by avsm** [comment]
Is the rest of the current opam repository passing the stricter duplicate key check?

**Comment by AltGr** [comment]
Yes, everything seems good!
