### ISSUE TITLE
Are OPAM packages supposed to work with a custom GCC?

### ISSUE THREAD

**Issue by thranur** [ocaml/opam#2338]
I have a machine where GCC is not installed as `gcc` by default, but as `gcc-4.8` (for several reasons). This does not seem a problem in itself for OPAM, but `ocamlfind` for instance does not work without `gcc` in the PATH (`sh: gcc: command not found`).

I suppose package writers have the right to assume that some basic tools such as GCC will be in the PATH with their standard names, but I'd like to confirm is this is indeed the case, or if I could ask package writers to support other use cases as well. I believe that in your tests you have a somewhat standard configuration, and only if the package does not compile in that configuration, then you inform the package developers that their packages are broken?

Otherwise, is there an environment variable which can be configured to change this value, and that package managers could/should support? I tried setting `CC=gcc-4.8` but it didn't help much.

**Comment by hannesm** [comment]
I don't have any `gcc` here either, only a `cc` (which is a clang compiler, using FreeBSD).  Most packages work fine without `gcc` for me (for some I had to send patches upstream (such as zarith)).

**Comment by thranur** [comment]
I actually got misled by my weird configuration where I removed gcc *after* installing OCaml... in fact, my question should be more on the lines of "is there a way to pass option `-cc` to the ocamlc/ocamlopt commands in OPAM packages?"

**Comment by AltGr** [comment]
opam 2 offers all ways to specify environment variables, or even run package commands inside wrappers, so I think there should be no problem with doing this kind of customisation (offering the facilities provided by ocaml, or whatever compiler you are using)
