### ISSUE TITLE
lastest dev version is broken

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2343]
In a switch with a lot of things installed, it says nothing is installed and `opam list` returns nothing. I checked `.opam/switch/installed` and it was indeed not empty.

**Comment by AltGr** [comment]
An upgrade from .opam/switch/installed to .opam/switch/state should have taken place; probably,  `~/.opam/config` already reported a newer version (1.3) so the upgrade wasn't done:

1. edit `~/.opam/config` and change `opam-version:` to `1.2` or `1.3~dev`
2. re-run any opam command, _e.g._ `opam list`, and you should be ok.

**Comment by AltGr** [comment]
(it _was_ broken in some other ways though, ie `eval $(opam config env)` didn't work, see https://github.com/ocaml/opam/pull/2344)
