### ISSUE TITLE
Upgrade from 1.2 to 1.3 doesn't preserve version of pin packages

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2353]
All my pin packages went from "dev" version to whatever the last stable version was.

**Comment by Drup** [comment]
(It worked fine when I re-pinned them)

**Comment by AltGr** [comment]
Ah, sorry about this, and thanks for notifying!
It shouldn't be much to fix.

**Comment by Drup** [comment]
Lot's of things have changed, closing!
