### ISSUE TITLE
build step executed while the ocaml version constraint is not satisfied

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#2357]
Is this normal? I run opam 1.2.2.
This package

    https://github.com/UnixJunkie/opam-repository/tree/older_clangml_fix/packages/conf-pic-switch/conf-pic-switch.0.1

I think it should not start to build the package (I am using ocaml 4.02.3).
Is there an error in the way I test the ocaml version in the opam file?

**Comment by AltGr** [comment]
Er, sorry, what command did you attempt and what got wrong ?

**Comment by UnixJunkie** [comment]
opam pin add conf-pic-switch https://github.com/UnixJunkie/opam-repository/tree/older_clangml_fix/packages/conf-pic-switch/conf-pic-switch.0.1

It executes the build step even when the available ocaml-version constraint is not satisfied

**Comment by UnixJunkie** [comment]
Is there something wrong with my package?

**Comment by UnixJunkie** [comment]
@samoth suggested to add parentheses to the ocaml version constraints, sorry for the noise
