### ISSUE TITLE
opam-managed ocamlc out-of-sync with platform shared libraries

### ISSUE THREAD

**Issue by basus** [ocaml/opam#2360]
I tried running `opam update` followed by `opam upgrade` today and got the following error on my Arch Linux system: 
```
The following actions will be performed:
  ∗  install ocamlfind 1.5.6
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

[ocamlfind] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of ocamlfind failed at "./configure -bindir /home/basus/.opam/4.02.1/bin -sitelib /home/basus/.opam/4.02.1/lib -mandir /home/basus/.opam/4.02.1/man -config /home/basus/.opam/4.02.1/lib/findlib.conf".
Processing  1/1: [ocamlfind: make uninstall]
#=== ERROR while installing ocamlfind.1.5.6 ===================================#
# opam-version 1.2.1
# os           linux
# command      ./configure -bindir /home/basus/.opam/4.02.1/bin -sitelib /home/basus/.opam/4.02.1/lib -mandir /home/basus/.opam/4.02.1/man -config /home/basus/.opam/4.02.1/lib/findlib.conf
# path         /home/basus/.opam/4.02.1/build/ocamlfind.1.5.6
# compiler     4.02.1
# exit-code    1
# env-file     /home/basus/.opam/4.02.1/build/ocamlfind.1.5.6/ocamlfind-11588-1872ec.env
# stdout-file  /home/basus/.opam/4.02.1/build/ocamlfind.1.5.6/ocamlfind-11588-1872ec.out
# stderr-file  /home/basus/.opam/4.02.1/build/ocamlfind.1.5.6/ocamlfind-11588-1872ec.err
### stdout ###
# Welcome to findlib version 1.5.6
# Configuring core...
### stderr ###
# configure: cannot determine ocaml's standard library directory



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install ocamlfind 1.5.6
No changes have been performed

=-=- ocamlfind.1.5.6 troubleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> Could not build ocamlfind. The most common reason for that is a missing 'm4' system package.

```

However, the m4 package *is* installed on my system. Any idea on how I could go about debugging this?

**Comment by dsheets** [comment]
The relevant line is:
```
# configure: cannot determine ocaml's standard library directory
```

From this, I went to the findlib source repo and read the source of `configure` where it prints this message. It calls a function `get_stdlib` which invokes `ocamlc -where`. My guess is that you have not run ```eval `opam config env` ``` or you have not configured your shell to automatically run that command and so `ocamlc` is not in your path. What does `which ocamlc` yield?

**Comment by dsheets** [comment]
Also, this issue would be better located at [ocaml/opam-repository](https://github.com/ocaml/opam-repository) as it concerns an opam package and not "opam the tool". It can be resolved here, though :smiley:.

**Comment by basus** [comment]
I have <code>eval \`opam config env\`</code> in my `.zshrc` and running `which ocamlc` gives: `/home/basus/.opam/4.02.1/bin/ocamlc`. I ran the `eval` command again, just to be sure and received the same result.

I'll remember to file package-related bugs against the other repo next time :-)

**Comment by dsheets** [comment]
`ocamlc -where 2>/dev/null | tr -d '\015'`?

**Comment by basus** [comment]
Looks like the problem is with my system I got no output from your command, but when I try to run just `ocamlc` I got the following error:

`/home/basus/.opam/4.02.1/bin/ocamlrun: error while loading shared libraries: libncursesw.so.5: cannot open shared object file: No such file or directory`

It looks like `libncursesw` moved from 5 to 6, but `ocamlc` got left behind.

**Comment by dsheets** [comment]
You might try `opam switch reinstall 4.02.1` which will rebuild the compiler and all packages and should pick up any changes in shared libraries due to upgrades.

This problem is actually due to the design of opam as a platform-independent package manager so your distro package manager knows nothing of the binaries that opam builds that may need to be updated. There have been discussions about external package manager plugins but nothing shipped, yet. I guess this is another use case for platform package manager integration.

Thanks for your report!

**Comment by basus** [comment]
I went ahead and moved up to 4.02.3 while I'm at it. For future reference, it might be good if opam linked against `libncursesw.so` instead of `libncurses.so.X` directly. The former is a symlink to the latter managed (I think) by the system package manager, so that should mitigate against this particular sort of issue.

I'm going to go ahead and close this thread.
