### ISSUE TITLE
OCAML_TOPLEVEL_PATH not present in opam config env under Cygwin

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam#2362]
Compiling opam under Cygwin works but `opam config env` [does not set  `OCAML_TOPLEVEL_PATH`](https://ci.appveyor.com/project/Chris00/ocaml-mindstorm/build/1.0.83#L1854).

**Comment by dra27** [comment]
I've just been scratching my head about this too - the relevant code (src/state/opamState.ml or src/state/opamEnv.ml, depending on where you are in this history) seems to have been commented out last November... but I haven't figured out why!

**Comment by Chris00** [comment]
@dra27 If you find out the culprit, the above simple change should enable you to test it (provided they enable AppVeyor or that you do on your clone).

**Comment by AltGr** [comment]
Setting the variables is now purely defined in the packages
