### ISSUE TITLE
`opam source` fails if the package source has `opam` file or directory.

### ISSUE THREAD

**Issue by camlspotter** [ocaml/opam#2364]
I submit an issue to opam-repository https://github.com/ocaml/opam-repository/issues/5142 days ago.  I think I should have asked it here.

I got issue reports about my opam packages which have `opam` directory: `opam source` fails due to its existence:

```shell
$ opam source ppx_meta_conv
opam source ppx_meta_conv
Downloading archive of ppx_meta_conv.2.2.0...
[default] https://opam.ocaml.org/archives/ppx_meta_conv.2.2.0+opam.tar.gz downloaded
Successfully extracted to /Users/jun/ppx_meta_conv.2.2.0
Fatal error:
OpamSystem.File_not_found("/Users/jun/ppx_meta_conv.2.2.0/opam")
Backtrace:
  Raised at file "core/opamSystem.ml", line 150, characters 30-51
  Called from file "core/opamFilename.ml", line 184, characters 2-43
  Called from file "client/opamArg.ml", line 1783, characters 10-158
  Called from file "cmdliner/src/cmdliner.ml", line 1247, characters 17-26
  Called from file "cmdliner/src/cmdliner.ml", line 1284, characters 6-34
  Called from file "client/opamArg.ml", line 2023, characters 10-56
```

Not only my packages, but some other packages also have `opam`. Therefore `opam source` of them should fail.

Do we have any consensus about this?  Are software packages allowed to have `opam` fie or directory?  It is pretty reasonable to me to keep `opam` and related files in the source repo...

Whether it is forbidden/discouraged or not, `opam source` should print a better diagnostics.

Thanks,
Jun

**Comment by AltGr** [comment]
This is definitely a bug, having an `opam` file or directory is _recommended_ by the [packaging manual](http://opam.ocaml.org/doc/Packaging.html), and opam will use them when pinning.

What version of opam ?

**Comment by camlspotter** [comment]
Confirmed with tag 1.2.2.  It has `opam` directory, not a file.

**Comment by AltGr** [comment]
This has been fixed, thanks for reporting.
