### ISSUE TITLE
opam pin add --dev doesn't update opam data properly

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2365]
It seems like `opam pin add <foo> --dev` and `opam pin add <foo> <foo-repo>` don't do the same. The first on doesn't properly update opam information based on the opam file in the repository.

**Comment by AltGr** [comment]
I think the update of the opam information must have failed for a different reason: it's really the same code in both cases, and the same call to `OpamState.update_pinned_package` should have taken place.

I'd be glad if you could gather some more information on this...

**Comment by Drup** [comment]
Pretty sure that's gone since.
