### ISSUE TITLE
Compiling opam under cygwin/mingw fails...

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam#2367]
Compiling opam under cygwin/mingw fails because the dose 3 tarball contains a symlink and [`tar` returns](https://ci.appveyor.com/project/Chris00/ocaml-appveyor/build/1.0.40#L4132):

```
/usr/bin/tar: dose.3.3/doseparseNoRpm: Cannot create symlink to ‘doseparse/’: No such file or directory
/usr/bin/tar: Exiting with failure status due to previous errors
Makefile:55: recipe for target 'dose.stamp' failed
```

**Comment by AltGr** [comment]
Cc @abate: could you get rid of the symlink in the tarball ?

**Comment by abate** [comment]
Yes... I've fixed this master (I'll upload a new release in the opam archive soon). I've removed the symlinks from the tarballs and added a hook in the makefile. I won't fix dose.3.3 ... (that btw it dose3 , version 3 . I know it's confusing. We got stuck with the name dose3 for historic reasons ...)

**Comment by abate** [comment]
the new version of dose (4.1) just landed in the opam repository.

**Comment by dra27** [comment]
I compile on a Windows 7 with native symlinking enabled, but I think this issue is resolved even on ones which don't?

**Comment by Chris00** [comment]
The [problem of compiling the Git version of opam on AppVeyor](https://ci.appveyor.com/project/Chris00/ocaml-appveyor/build/1.0.208#L5564) hasn't fully disappeared.

**Comment by Chris00** [comment]
On Appveyor, configuring OPAM fails with “[checking for an installed Microsoft C Compiler for x64... ./configure: line 3321: ./shell/msvs-detect: Permission denied](https://ci.appveyor.com/project/Chris00/ocaml-appveyor#L5315)”.

**Comment by dra27** [comment]
(that link should be https://ci.appveyor.com/project/Chris00/ocaml-appveyor/builds/26743963#L5315)

**Comment by Chris00** [comment]
Fix: `chmod +x shell/msvs-detect`

**Comment by dra27** [comment]
@Chris00 - see #3963

**Comment by dra27** [comment]
Incidentally, I think that dose 5 has no symlinks at all (or perhaps I contributed a workaround??), so this issue can possibly be closed?
