### ISSUE TITLE
Installing opam under cygwin/mingw fails...

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam#2369]
Installing opam under cygwin/mingw [fails](https://ci.appveyor.com/project/Chris00/ocaml-appveyor/build/1.0.50#L6225), even if the final path does not [contain spaces](https://github.com/ocaml/opam/issues/2368):

```
src/opam-installer --prefix C:/opam --mandir C:/opam/share/man opam.install
Creating directory C:/opam\bin
src\opam                         => C:/opam\bin\opam
[ERROR] Failure during install
rm: cannot remove ‘C:\\cygwin\\tmp\\opam-appveyor-100/command-100-4438d8.err’: Device or resource busy
rm: cannot remove ‘C:\\cygwin\\tmp\\opam-appveyor-100/command-100-4438d8.out’: Device or resource busy
rm: cannot remove ‘C:\\cygwin\\tmp\\opam-appveyor-100/command-100-4438d8.err’: Device or resource busy
rm: cannot remove ‘C:\\cygwin\\tmp\\opam-appveyor-100/command-100-4438d8.out’: Device or resource busy
# opam-version    1.3.0~dev3
# os              win32
C:\projects\ocaml-appveyor\opam\src\opam-installer: "create_process" failed on /bin/sh: No such file or directoryFatal error: exception # opam-version    1.3.0~dev3
# os              win32
Cannot remove C:\cygwin\tmp\opam-appveyor-100 (error 1).
Makefile:64: recipe for target 'install' failed
make: *** [install] Error 2
```

**Comment by dra27** [comment]
This is because opam tests for whether commands are available by executing /bin/sh so it's obviously a non-starter for native Windows.

It will be fixed 'ere long: https://github.com/dra27/opam/commit/36ab0af750430e7ac710fcf6288da00be5e36050

**Comment by Chris00** [comment]
I reran the installation of OPAM on AppVeyor with OCaml being compiled with MSVC — instead of coming from Cygwin — and I hit a problem with duplicated files, [it seems](https://ci.appveyor.com/project/Chris00/ocaml-appveyor/build/1.0.236#L7405).  @dra27 any idea?

**Comment by dra27** [comment]
I've been a preoccupied with OCaml stuff recently - I just started to catch up with the new solver stuff at the weekend. I expect that to lead with patches for ocaml-mccs.

**Comment by Chris00** [comment]
OK!
