### ISSUE TITLE
OpamFilename.rec_files gives paths that are not files

### ISSUE THREAD

**Issue by gasche** [ocaml/opam#2372]
In the context of my add-ocamlbuild-deps script, I run a regexp on the content (`OpamFilename.with_contents`) of all files (`OpamFilename.rec_files`) in an archive. However this sometimes fails with an exception:

```
Fatal error: exception OpamSystem.File_not_found("/tmp/opam-1566-4f1270/archive/bencode.docdir")
```

I think the problem comes from the symlink-follow logic, when a symlink points to something that does not exist or is not a directory. I could avoid the failure in my script by checking `OpamFilename.exists` before doing any further processing.

`OpamFilename.rec_files` should only list files that pass the `OpamFilename.exists` test.

**Comment by rjbou** [comment]
Fixed by #2515.
Thanks for the report!
