### ISSUE TITLE
opam-remove tries to download the version to be removed

### ISSUE THREAD

**Issue by fblanqui** [ocaml/opam#2373]
Hello.
```
09:03 ~ opam --version
1.2.0
09:01 ~ opam list hevea
Available packages for 4.02.1:
hevea  2.23  A quite complete and fast LATEX to HTML translator
09:01 ~ opam remove hevea
The following actions will be performed:
 - remove    hevea.2.23
 - install   ocamlbuild.0                          [upstream changes]
=== 1 to install | 1 to remove ===
Do you want to continue ? [Y/n] Y

=-=- Synchronizing package archives -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[hevea.2.23] Downloading http://hevea.inria.fr/distri/hevea-2.23.tar.gz
[ERROR] curl: code 404 while downloading http://hevea.inria.fr/distri/hevea-2.23.tar.gz
[ERROR] http://hevea.inria.fr/distri/hevea-2.23.tar.gz is not available
[ERROR] Could not download archives of hevea.2.23
```
Why opam-remove tries to download the package that I want to remove?! Since this package does not exist anymore, it cannot remove it and upgrade it to 2.25... I am stuck.

Frédéric.

**Comment by dsheets** [comment]
Hi, Frédéric. Opam considers remove commands to be run from the source package root in order to support uses like `make uninstall`. In hevea's case, the removal is simply a sequence of `rm` commands which you can read by running `opam info --raw hevea`. You should be able to run these commands with `opam remove --force hevea`.

**Comment by hannesm** [comment]
@dsheets while I understand that it is atm the case that opam needs the source package for uninstalling, I think this is a design mistake.  IMHO the installation should keep track of what was installed (.install file) and remove should a purely local action.

**Comment by fblanqui** [comment]
opam remove --force did not work either.

**Comment by dsheets** [comment]
@hannesm Yes, it is a deficiency in the current design. It is the simplest possible thing to implement (nothing) but it clearly has significant drawbacks. Moving to more tracking/total tracking has been discussed a lot and is something that should occur in the next several minor releases. See #1215.

@fblanqui Odd. It does not attempt to download the archive if the package is not installed and you try to force an uninstall but it does attempt to download the archive if the package is already installed. The only remaining current method I know is the potentially dangerous:
```
rm -r `opam config expand %{lib}%/hevea`
rm `opam config expand '%{bin}%/hevea %{bin}%/hacha %{bin}%/esponja %{bin}%/bibhva'`
rm `opam config expand '%{bin}%/imagen'`
opam remove --fake hevea
```

**Comment by AltGr** [comment]
Yes, tracking of installed files is going to happen, which should make `remove:` instructions unneeded as well.
`--force` tells opam to run the uninstall instructions even if it doesn't think the package is currently installed, it won't affect downloading.
You may want to try `--fake` to do the opposite: register the package as uninstalled without actually doing anything, which should unblock opam (--fake is a bit dangerous, make sure it doesn't fake other operations besides the removal).

Note that packagers have a way of specifying that their package doesn't need downloading for uninstallling.

**Comment by dsheets** [comment]
> Note that packagers have a way of specifying that their package doesn't need downloading for uninstallling.

Which is...?

**Comment by AltGr** [comment]
```
flags: light-uninstall
```
It's documented in the [official manual](http://opam.ocaml.org/doc/Manual.html#opamflag-light-uninstall)

**Comment by Drup** [comment]
`git grep "light-uninstall" ` returns 6 results, you might want to advertise it a bit more. :D 
(But it seems it's inferred for the most common idiom, so it shouldn't matter, maybe add it to the lint ?)

**Comment by AltGr** [comment]
Closing as sub-issue of #502
