### ISSUE TITLE
return value on command abortion, or script-friendly query interface

### ISSUE THREAD

**Issue by gasche** [ocaml/opam#2378]
I just fixed issue [#8](https://github.com/gasche/opam-compiler-conf/issues/8) in my [opam-compiler-conf](https://github.com/gasche/opam-compiler-conf/) script: after running the `opam switch remove $SWITCH` command, my script would always assume that the switch was correctly uninstalled -- and then remove the corresponding compiler description file. This is wrong, as users may be prompted yes/no questions and abort the remove command -- which lead to an inconsistent state that confused later runs of my script.

I tried to find a way using the current opam interface to write scripts that are more resilient, but I found nothing satisfying (hence this issue). Basically I could:
- use `--yes`, but that is making my script more robust by being more dangerous to my users, which I don't want
- use the return code, _if_ `opam` returned a non-0 return code when the script terminates but has not accomplished the requested goal (if a user answer `no`, the switch is not uninstalled as it should has been)
- call a for-scripting opam command to test whether a particular switch is installed, _if_ it existed

For now I am working around the issue by manually checking for the existence of a `$(opam config var root)/compilers/$SWITCH` directory.

**Comment by AltGr** [comment]
This has been corrected. Thanks!
