### ISSUE TITLE
Is it possible to query for OS version?

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/opam#2379]
I know you can do checks like `os = "darwin"` but I'd like to enable a flag only on el capitan. Is this possible in an opam file?

**Comment by avsm** [comment]
This would be useful for me as well.  It is possible to have a conf-macosx.10.11 package and depend on that, but the error messages are unsatisfactory (an installation error as opposed to a constraint error).

**Comment by AltGr** [comment]
There could easily be defined as an `os-version` variable... the problem being to compute it reliably, which would require specific code for every platform (it's already not easy to reliably get e.g. the [Linux distribution](https://github.com/ocaml/opam-depext/blob/fc183489fb9ee2265b6d969fcab846d38bceb937/depext.ml#L82-L107)).

Also, on Linux, this wouldn't make much sense, unless we also include an `os-distribution` variable (or we could prefix the `os-version` with the distribution name, but then, there is no natural ordering).

**Comment by dbuenzli** [comment]
I also need this (more precisely I want to express osx >= 10.10). On osx `sw_vers(1)` has the info in machine readable format. Related to https://github.com/ocaml/opam/issues/2391

**Comment by dra27** [comment]
I can imagine this coming up for Windows at some point too.

@AltGr - perhaps we just have swallow having a certain amount of OS-specific code here? It seems better to have opam do this directly, rather than having conf packages as at least it would create consistency between different repository universes?

**Comment by AltGr** [comment]
We now define a `os-version` variable :)
