### ISSUE TITLE
Output of opam info

### ISSUE THREAD

**Issue by herbelin** [ocaml/opam#2380]
Hi, the output of "opam info package" is a bit misleading for a beginner as it is mixing two kinds of information of different level.

The fields installed-versions and available-versions are about the package name and they list all versions of that package.

All other fields are about a specific version of the package. Despite of this, the two package-dependent fields are shown in the middle of the version-dependent output. For instance, it took me some times to realize that the field descr is the description of the version and not the description of the package. Since a package can have its contents evolve along versions, this is misguiding (there is actually one descr file per version, not per package).

A typical layout which I would find clearer is the following (using ocamlfind as an example).

For "opam info ocamlfind":
```
package: ocamlfind
installed-versions: 1.5.4 [system], 1.5.5 [4.02.1 4.00.0 3.12.1], 1.5.6 [4.02.3 4.01.0]
available-versions: 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6
default-version: 1.5.5
---------------------------------------------------------------------------------------------
metadata of version 1.5.5
upstream-url: http://download.camlcity.org/download/findlib-1.5.5.tar.gz
upstream-kind: http
upstream-checksum: 703eae112f9e912507c3a2f8d8c48498
homepage: http://projects.camlcity.org/projects/findlib.html
bug-reports: mailto:gerd@gerd-stolpmann.de
dev-repo: https://github.com/whitequark/ocaml-findlib.git
author: Gerd Stolpmann <gerd@gerd-stolpmann.de>
description: A library manager for OCaml
Findlib is a library manager for OCaml. It provides a convention how
to store libraries, and a file format ("META") to describe the
properties of libraries. There is also a tool (ocamlfind) for
interpreting the META files, so that it is very easy to use libraries
in programs and scripts.
```
For "opam info ocamlfind.1.5.5": same as above starting from line "metadata from version 1.5.5".

**Comment by AltGr** [comment]
That's quite true indeed, and yours seem a good suggestion. thanks!
