### ISSUE TITLE
help output missing --require-checksums

### ISSUE THREAD

**Issue by agarwal** [ocaml/opam#2394]
```
$ opam --version
1.2.2

$ opam --help | grep require-checksums
       OPAMREQUIRECHECKSUMS see option `--require-checksums'.
```

Thus you can see that the `--help` output doesn't include documentation on the `--require-checksums` flag, even though I tested that my opam does recognize the flag.

**Comment by AltGr** [comment]
it's only available for some commands, see e.g. `opam install --help`

**Comment by agarwal** [comment]
Right, I realize opam's command line help isn't so fine tuned to the sub-command the help is being requested for. Probably there's no easy solution to that (note Core's Command does handle this correctly). Feel free to close the issue if there's nothing that can be reasonably done. Thanks.

**Comment by dbuenzli** [comment]
> (note Core's Command does handle this correctly)

So does `cmdliner`, but `opam`'s handling of env variable pre-dates `cmdliner`'s support for this and may be done in an ad-hoc fashion.

**Comment by agarwal** [comment]
Great, so it's just a matter of using `cmdliner`'s latest features.
