### ISSUE TITLE
External solver failure 9 'unsafe variables', on OS X 

### ISSUE THREAD

**Issue by timrichardson** [ocaml/opam#2395]
I'm a newbie, and on OS X I'm running into failure to opam update after installation. 

I ocaml is installed from macports
opam is installed as per the instructions 

```
wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin/
```

with version 1.2.2 

```
$opam update

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[default] synchronized from https://opam.ocaml.org
[WARNING] External solver failed:
# opam-version 1.2.2
# os           darwin
# command      aspcud /Users/tim/.opam/log/solver-in-35500-58c514 /Users/tim/.opam/log/solver-out-35500-ffb3fd -count(down),-count(removed),-notuptodate(solution),-sum(solution,version-lag),-count(new)
# path         /Users/tim
# exit-code    1
# env-file     /Users/tim/.opam/log/log-35500-05296d.env
# stdout-file  /Users/tim/.opam/log/log-35500-05296d.out
# stderr-file  /Users/tim/.opam/log/log-35500-05296d.err
### stderr ###
# [...]
# /opt/local/share/aspcud/misc2012.lp:378:1-379:64: error: unsafe variables in:
#   alchain(T,A,X,B,Y1,Y2):-#inc_base;alvalue(T,A,X,B,Y1);alcount(T,A,X,B);Y<=Y1:alvalue(T,A,X,B,Y),Y<Y2;Y1<Y2.
# /opt/local/share/aspcud/misc2012.lp:378:20-22: note: 'Y2' is unsafe
# 
# /opt/local/share/aspcud/misc2012.lp:378:1-379:64: error: unsafe variables in:
#   alchain(T,A,X,B,Y1,Y2):-#inc_base;alvalue(T,A,X,B,Y2);alcount(T,A,X,B);Y<=Y1:alvalue(T,A,X,B,Y),Y<Y2;Y1<Y2.
# /opt/local/share/aspcud/misc2012.lp:378:17-19: note: 'Y1' is unsafe
# 
# *** ERROR: (gringo): grounding stopped because of errors
# error: gringo returned with non-zero exit status

[ERROR] External solver failure, please fix your installation and check
        /Users/tim/.opam/config and variable $OPAMEXTERNALSOLVER.
        You may also retry with option --use-internal-solver
```

**Comment by lucbouge** [comment]
I confirm. See my post  #2396.

**Comment by timrichardson** [comment]
This alternative works fine. 
https://github.com/IRILL/cudf_remote_proxy

**Comment by AltGr** [comment]
We have seen this kind of errors in the past when there was a mismatch between the versions of aspcud and its dependencies, in particular, gringo. Has gringo been updated recenlty on your system ?

You're using macports, and most people are on homebrew it seems, so you may have different versions from what most are using, which could explain the issue.
Brew has aspcud 1.9.1 and gringo 4.5.3.

**Comment by lucbouge** [comment]
Thanks, I did not think of that. Macport reads today:
  * aspcud: 1.9.0
  * gringo: 4.5.4
Could this slight subsubversion shift explain this behavior?

**Comment by lucbouge** [comment]
Lokking more closely at the error messages, I have discovered using the `-use-internal-solver` option circumvents the problem. 
```
opam update --use-internal-solver
opam upgrade --use-internal-solver --yes
```
It confirms that the problem lies with `aspcud`, the external solver.

**Comment by timrichardson** [comment]
Gringo was updated recently by macports due to an upstream release (as Luc says). Yet we can see that macports lags with aspcud. I will report this to macports.

In my case, I am pleased about the remote inria dependency solving service via the very clear instructions I mentioned above. I was reluctant to use the internal solver as the documentation seems to discourage it, referring to is as "naive".

**Comment by timrichardson** [comment]
Macports has closed my ticket by upgrading aspcud to 1.9.1

**Comment by lucbouge** [comment]
Thank you for your help, Tim and Louis AltGr.

I upgraded aspcud to version 1.9.1 through Macports, and everything resumed working as if nothing happened. So good!

The ticket can be closed, I guess.

Regards, Luc.

**Comment by avsm** [comment]
Excellent!  Leaving it open in case there's a documentation entry or version check that might help.
