### ISSUE TITLE
WARNING: you have a different version of OPAM installed at /usr/local/bin/opam

### ISSUE THREAD

**Issue by cpitclaudel** [ocaml/opam#2399]
I'm getting the warning above when running the setup script. It seems to come from this test:

```
if [ "$OPAM" != "$BINDIR/opam" ]; then
```

Printing these two values gives me:

```
/usr/local/bin/opam
/usr/local/bin//opam
```

Am I doing something wrong?

**Comment by AltGr** [comment]
Fixed by 16dc6e7e196dfe6e7c667949358394b22c64d1c8. Thanks for reporting!
