### ISSUE TITLE
OPAMYES + syntax error edit offers = purgatory

### ISSUE THREAD

**Issue by dsheets** [ocaml/opam#2401]
When `OPAMYES=1` is set and an opam file being pinned has a syntax error, opam will repeatedly attempt to open your editor until you fix the syntax error. If you don't fix the syntax error, you will be doomed to wander the wastes of your editor buffer for all eternity. [Legend](https://github.com/ocaml/ocaml-travisci-skeleton/issues/75) has it that if you teach your spawned processes to do this, they will go mad with the impossibility of the task.

I think opam should sprout the ability to put it into non-interactive mode and `OPAMYES=1` should not affect interactive prompts. What say you?

**Comment by dbuenzli** [comment]
Personally I have always been confused by the editor and I'm not sure it's useful in practice as you often want to fix things not on the file that will be in the opam repository but at the source (in the source repository).

**Comment by AltGr** [comment]
Oops :)
We should certainly be more careful with the editor. Checking its return value would be a minimum...
@dbuenzli, opam normally prompts you to copy back the opam to your source, which makes them mostly equivalent. Editing at the source is not always possible, e.g. if you pin to a remote.
