### ISSUE TITLE
caml.inria.fr should be be replaced by github

### ISSUE THREAD

**Issue by scemama** [ocaml/opam#2403]
Hi,
when I try to install opam as:
```
wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin/
```
It tries to download the source files of the OCaml compiler from the `http://caml.inria.fr` website which seems to be down now that OCaml moved to GitHub. I think that Opam should now download the files from the github releases : https://github.com/ocaml/ocaml/archive/4.02.2.tar.gz, right?

I tried to fork the project to make a pull request, but I couldn't manage to find where the address is wrong. It seems to me that the address is given by some http connexion. Nevertheless, I found that it should be changed in the shell/bootstrap-ocaml.sh file.

Thanks for doing this fix quickly because all my installation scripts rely on the correct installation of Opam...
 ;-). 

Cheers,
Anthony

**Comment by dbuenzli** [comment]
See this message https://sympa.inria.fr/sympa/arc/caml-list/2016-01/msg00036.html

**Comment by dbuenzli** [comment]
Btw. there's no guarantee the tarball you mention above is the same as the actual release. I don't know how @damiendoligez creates the actual distribution tarball but the way github decides to considers checkouts of git tags as denoting releases of your project is a completely broken idea.

**Comment by scemama** [comment]
Oops! I didn't know about this message. Sorry.
Thanks for the precision about git tags and for your quick reply.
I close the issue.

**Comment by damiendoligez** [comment]
FTR, I create the distribution by checking out the git tag, then removing some auxiliary directories, so GitHub's tarball should be OK, although it won't be the exact same file.
