### ISSUE TITLE
CVS dev-repo support

### ISSUE THREAD

**Issue by dsheets** [ocaml/opam#2408]
Support for CVS dev repos would be nice. CVS is still in use by some projects that use SourceForge.

**Comment by michipili** [comment]
Which CVS software do you want to work with? If I remember correctly, some “enterprise” versions of CVS display poor interoperability with the “standard” CVS tools and I had a hard time figuring out which options of my free software client where actually supported by the servers.  Also, IIRC, there are several access methods for CVS (either using a dedicated daemon or a remote shell access, or using local files) so maybe it could be useful to have more details on the concrete use-cases you have in mind!

**Comment by dra27** [comment]
Contribution for this is welcome, if it remains of use!
