### ISSUE TITLE
is there a way to install binaries globally

### ISSUE THREAD

**Issue by bobzhang** [ocaml/opam#2410]
for example, I want to install `ocp-indent` into a global position so that I don't need install again when I switch to another compiler, thanks

**Comment by bobzhang** [comment]
This would be really nice to have

**Comment by AltGr** [comment]
I know this would be useful, but as it breaks the current rules and isolation, I haven't yet found a satisfying design (where do you install ? Do you need su ? Does opam keep tracking the installed file and remove it on remove, or is it a one shot install ? What if multiple switches install Portability ? Etc.)

Note that `.install` files have had a `misc:` field for this purpose, but it hasn't been ever used AFAIK, and it requires absolute paths, which is weird and non-portable.

On the specific `ocp-indent` issue, [opam-user-setup](https://opam.ocaml.org/packages/user-setup/) solves that with some clever elisp/vim code that will use ocp-indent from the original switch where it was installed if not present on the current switch (but not e.g. merlin, as that wouldn't work)

**Comment by dra27** [comment]
This would also be useful for the Windows switches, allowing them to share flexlink

**Comment by RandomDSdevel** [comment]
@bobzhang, @AltGr:  Isn't this feature request really just a combination of #1058 and #1950?  Could a resolution for it be built on top of those for those other two issues?

**Comment by hcarty** [comment]
For some packages, like `merlin`, it would be nice to install it once per compiler variant since there is some compiler-specific information to deal with.  Then these basic tools could be installed under a single `4.06.1-tools` switch and shared across a number of local `4.06.1` switches, for example.

**Comment by dra27** [comment]
This will be subsumed by the layered switches feature in opam 2.2 (which will have a spec shortly, but is presently covered in [opam 2.2 slides](https://github.com/ocaml/opam/wiki/opam-2.2-slides.pdf))
