### ISSUE TITLE
compilers-to-packages.ml is broken in trunk

### ISSUE THREAD

**Issue by thranur** [ocaml/opam#2411]
The following block in `compilers-to-packages.ml` is syntactically invalid:

      let available =
        match OF.ocaml_version opam with
        | None -> available
        | Some cstr ->
          let filter = OpamFormula.
          OpamFormula.ands [cstr; available]
      in

I'd really like to be able to run this script from trunk, but I get the following error and I am unable to quickly find which filter or formula should be used instead...

    File "./opam/admin-scripts/compilers-to-packages.ml", line 176, characters 4-8:
    Error: Syntax error: operator expected.

**Comment by AltGr** [comment]
Oops, sorry about this, seems I stopped in the middle of updating.
You'll need a small conversion function:
```
let rec filter_of_formula atom_f = function
  | Empty -> FBool true
  | Atom at -> atom_f at
  | Block f -> filter_of_formula atom_f f
  | And (a, b) -> FAnd (filter_of_formula atom_f a, filter_of_formula atom_f b)
  | Or (a, b) -> FOr (filter_of_formula atom_f a, filter_of_formula atom_f b)
```
and the case is then:
```
        | Some cstr ->
          let filter =
            filter_of_formula
              (fun (op,v) -> FIdent ([], OpamVariable.of_string "ocaml-version", None))
              cstr
          in
          FAnd (filter, available)
```

I don't guarantee the results on trunk though!

**Comment by thranur** [comment]
Thank you very much, this does fix compilation. I could not yet test if the behavior is precisely the one I wanted, but I see no reason why it wouldn't be.
