### ISSUE TITLE
Suggestion: renaming opam files

### ISSUE THREAD

**Issue by ghost** [ocaml/opam#2416]
I don't know if this is intentional, but the amount of files named `opam`, and opam-related things makes me think of Monty Python's spam sketch.

For instance, if I do `find ~/.opam -name opam`, I may find:
- the `opam` binary itself;
- the `opam` file in each package defining the information that OPAM needs;
- eventually, a directory called opam containing the opam binary (due to personal preferences).

When compiling OPAM itself, it's even worse, because then there's the `opam` git directory, the `opam` text file describing itself, and the `opam` binary compiled inside the `src` directory.

I've seen an issue on an OCaml project about having an `opam` file for the project, but wanting to have an `opam` directory (since each directory was named after a package) but not being able due to the name conflict.

Let's say that `opam`, without extension, prefix or suffix, is not necessarily the best naming convention for OPAM-related files. Is there an alternative name which is considered by opam tools?

Otherwise, it could be useful to have an officially-accepted "backup" name such as "manifest.opam", or "_opam", or "opam.package", or "package.opamspec", etc. I'd even suggest "OPAM" in uppercase to make it stand out, but this would be problematic in case-insensitive file systems.

By the way, "opam.opam", "opam.opam.opam" and even "opam,opam,opam" are also valid possibilities.

**Comment by AltGr** [comment]
:D
You have a point.
A directory (or file) named `<pkgname>.opam` in the source is also recognised. This also allows having several packages in the same source tree.
