### ISSUE TITLE
Several issues when using opam admin make by compiling from 1.2.2 sources

### ISSUE THREAD

**Issue by thranur** [ocaml/opam#2417]
This is mostly a list of several small issues I had when trying to make a local OPAM repository from 1.2.2 sources. Some of them have already been listed in other issues, but some I couldn't find.

In the interest of further googlability, and so that you may possibly resolve some of them if they are still present, I describe the steps I had to perform. Feel free to close this issue if it seems not relevant for the current master; I hope Google will index it for later retrieval (and for the error messages, if others find them).

I tried this on a brand new Debian machine (minimal netinst ISO installation, no desktop environment):
- Install all essential dependencies (m4, unzip, make, gcc, etc.);
- Download pre-compiled binary opam for Linux 64 bits;
- `opam init` with a 4.02.3 OCaml;
- Configure environment, test OCaml, everything works;
- Download and untar opam-full-1.2.2.tar.gz;
- Run `./configure`, it complains about lack of essential packages, suggests `make lib-ext`;
- Run `make lib-ext`, then `make`, then `make install`, then `make clean-ext`, then `make libinstall` to obtain extra administrative tools>
- Try running `admin-scripts/extract_mini_repository.sh ocaml-4.02.3` to create a local repository. `compilers-to-packages.ml` fails with an extlib-related error message (incorrect arguments passed to the program):
  
  ```
  opam-admin.top: admin-scripts/compilers-to-packages.ml.
  ExtLib installation program v1.3
  (c)2003,2004 Nicolas Cannasse
    -d <dir> : install in target directory
    -b : byte code installation
    -n : native code installation
    -doc : documentation installation
    -nodoc : documentation installation
    -help  Display this list of options
    --help  Display this list of options
  ```
- `make clean`, use existing opam to install all dependencies. `dose3` no longer exists, so `dose` is installed instead.
- Try running `make`, obtain issue with [Debian.Version](https://github.com/ocaml/opam/issues/2402). Patch using `sed -i s/Debian.Version/Versioning.Debian/g src/*/*.ml`, then run `make` again, then `make install` and `make libinstall`.
- Retry running `extract_mini_repository.sh`, but inadvertently adding `ocaml-4.02.1` when it wasn't necessary (already added by the script), ending in the following command being executed:
      opam admin make --resolve --compiler 4.02.1 ocaml.4.02.1 ocaml-4.02.1 core
  
  This unfortunate sequence of arguments, for some reason triggers this exception:
  
  ```
  Fatal error: exception File "solver/opamCudf.ml", line 197, characters 22-28: Assertion failed
  ```
- Find out the error on the command line by adding `-x` to the shell script, fix it, finally obtain the local repository.
- Repeat process for other packages, notice that some created repositories do not have all dependencies, possibly related to https://github.com/ocaml/opam/pull/2257

**Comment by AltGr** [comment]
Thanks a lot for the precise report. I am now focused on deep changes in opam, but adapting the scripts is next on my list!

**Comment by AltGr** [comment]
Hopefully the main errors here have been fixed, and we have something better coming to replace the `extract_mini_repository` script.
Thanks for reporting!
