### ISSUE TITLE
opam cp bug

### ISSUE THREAD

**Issue by agarwal** [ocaml/opam#2420]
It seems opam tries to be smart when it encounters a `cp` command, rather than simply passing it to the shell. Unfortunately, there also is a bug. Steps to reproduce:

```
$ mkdir cp-opam-bug
```

Then populate the directory so it looks like this:

```
$ tree .
.
├── dir1
│   ├── a
│   └── b
├── dir2
│   ├── c
│   └── d
└── opam
```

where the `opam` file contents are:

```
$ cat opam 
opam-version: "1.2"
name: "cp-opam-bug"
version: "dev"

install: [
  ["cp" "-PR" "dir1" cp-opam-bug:lib]
  ["cp" "-PR" "dir2" cp-opam-bug:lib]
]

remove: [
  ["rm" "-rf" "%{cp-opam-bug:lib}%/dir1"]
  ["rm" "-rf" "%{cp-opam-bug:lib}%/dir2"]
]
```

Now, install the package:

```
$ cd cp-opam-bug
$ opam pin add cp-opam-bug . -n
$ opam install cp-opam-bug -v
$ ls `opam config var cp-opam-bug:lib`
a           b           dir2        opam.config
```

So the contents of `dir1` got copied, instead of `dir1` itself. Surprisingly, that's not the case for `dir2`. Swap the order of the install lines, and refresh the pin (which AFAICT requires removing the pin and adding it again, or the changes don't get picked up. I think #894 is still not resolved). Install again, and you get the opposite:

```
$ ls `opam config var cp-opam-bug:lib`
c           d           dir1        opam.config
```

My workaround for now is to put these commands in a script, and call the script. However, the extra intelligence opam applies to `cp` is presumably useful for something. In particular, are we supposed to be able to omit the `rm` commands?

**Comment by agarwal** [comment]
So this is related to shell/Unix behavior after all, but opam could still help. First, note that the shell does weird things. In a new empty directory:

```
$ mkdir dir1
$ touch dir1/a
$ cp -PR dir1 foo
$ $ ls foo/
a
$ cp -PR dir1 foo
$ ls foo/
a    dir1
```

So the behavior of the `cp` command depends on whether or not the destination directory already exists or not.

Now my workaround in opam is to do `"mkdir" pkg-name:lib` as the first step in `install`. Would it make sense for opam to create all the possible destination directories---lib, bin, sbin, share, and etc---prior to running the install commands?

This has the drawback of possibly having empty directories. One option would be to check for that at the end of the install commands and remove them. Or just leave them.

**Comment by AltGr** [comment]
Indeed, these shell behaviours are quite the annoyance. Another possibility is to write:
```
install: [
  ["cp" "-PR" "dir1" "%{_:lib}%/dir1"]
  ["cp" "-PR" "dir2" "%{_:lib}%/dir2"]
]
```
Except, of course, now you are assuming that the dirs _don't_ already exist or it would again go wrong. `install -d` is somewhat better, but I don't think it's as portable.

>  refresh the pin (which AFAICT requires removing the pin and adding it again, or the changes don't get picked up. I think #894 is still not resolved)

On updating a pinned package (which is done automatically when it's mentionned on the command-line of e.g. an `install` command), its new opam file should be picked up (and you'll get an interactive prompt in the event you had changes in the metadata on the opam side too).
You can also repin without unpinning first to make sure to reset the metadata.
And for this kind of tweaks, the recommended way is to use `opam pin edit` to directly access opam's opam file.
