### ISSUE TITLE
would be nice to have a flag enforce-depext in the .opam/config file

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#2426]
It would always try to satisfy the depext when installing something (as if they were regular dependencies). Alternatively, maybe an opam option would be enough.

**Comment by AltGr** [comment]
Note that opam has no understanding of the meaning of the `depext` flags at the moment: this would go with the merge of the opam-depext plugin and the related platform-detection code upstream.

Alternatively, with some implementation of pre-install hooks, we could imagine calling opam-depext from there to do such a validation.
