### ISSUE TITLE
opam file accepts `post-message:` field but does nothing

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#2427]
The `post-message:` triggers no error or lint warnings, but does nothing with it. `post-messages:` is the right field to use.

**Comment by AltGr** [comment]
Couldn't reproduce from master. Do you get reports for any other unknown field but not `opam-message:` ?

**Comment by dbuenzli** [comment]
Tried with master and indeed `opam lint` reports that 

```
 error  3: Invalid or duplicate field: 'post-message:'
```

However it also reports: 
```
 error 42: The 'dev-repo' field doesn't use version control. 
You may use URLs of the form "git+https://" or a ".hg" or ".git" suffix
```

Which is not true, the URI mentioned ends with `.git`; this seems to be wrongly reported on on all my opam files...

**Comment by dbuenzli** [comment]
Ouch. It seems not a good idea to do a `brew install --HEAD` and then try to go back to the official release.

**Comment by AltGr** [comment]
Arg, sorry about that -- I should probably make migration less automatic for dev releases.

I can't give any guarantee about that, but you might have luck restoring your switches with `opam.1.2.2 switch import ~/.opam/<switch> --switch <switch> --fake`. It's dangerous but should restore the legacy files from the state file, assuming the package installations are correct already.

> Error 42

Ah, I need to fix the message. I changed things a bit while rationalising URL handling, and in this case, we still have some magic to handle `https://xxx/x.git` as git, but from the command-line only; for file interaction, parsing/printing needs to be bijective, so the prefix is mandatory (or we would have a bug with `opam pin add x https://xxxx/x.git --kind http`).

**Comment by AltGr** [comment]
NB on the lint error: the repo conversion to the new version will automatically take care of this, so you shouldn't have to worry about it.

**Comment by dbuenzli** [comment]
> Arg, sorry about that -- I should probably make migration less automatic for dev releases.

Bah, in the end a `rm -rf .opam` from time to time can't be harmful. 

> so the prefix is mandatory

Ok. Do these prefix work with 1.2.2 ?
