### ISSUE TITLE
Closed source material needs to be manually added in this similar to nix flow + depexts on nix?

### ISSUE THREAD

**Issue by fxfactorial** [ocaml/opam#2436]
I have this flow in nix os and I want to copy it in opam, but I don't know if such functionality exists. Here's the flow I'm envisioning

``` shell
$ opam install foo
....
...
Sorry can't install foo because you don't have XYZ closed source SDK. do:

opam repository --add-manual file://some/path

then run this installation again
```

and the end user does the command, runs `opam install foo` again and all is well.

Also, can opam somehow use a nix package as information to install from as a system dependency like `apt-get` or `brew`

**Comment by dbuenzli** [comment]
Use the `post-messages:` field, see documentation in [this section](https://opam.ocaml.org/doc/manual/dev-manual.html#sec9).

**Comment by fxfactorial** [comment]
Somewhat relevant but I mean to say I want to integrate a third party closed source, say tarball, on the fly as an opam package.

**Comment by dbuenzli** [comment]
> say tarball,

AFAIK That won't be possible. But you can simply have a repo that you ask users to pin in your `post-message:`, its `opam` file should have all the instructions to download the tarball and install it.

**Comment by fxfactorial** [comment]
@dbuenzli No, I can't do that because I can't redistribute these third party packages, say Apple or the JDK. I need the end user to do it.

**Comment by dbuenzli** [comment]
> No, I can't do that because I can't redistribute these third party packages,

You don't redistribute them if you download them from the install procedure.

> say Apple or the JDK.

If you are talking about this then these shouldn't be part of the opam tree. It's better to simply tell users in a post-message they need to install these and direct them to install instructions and/or use a `source` depext (see e.g. [here](https://github.com/ocaml/opam-repository/blob/e1031fb457c34aaa62897af620d492cc16a107ac/packages/tsdl/tsdl.0.8.1/opam#L16)).

**Comment by fxfactorial** [comment]
But that's exactly what I'm trying to do: I'm trying to get them to install them according to some instruction and my example from nix shows the kind of functionality I'm looking for from opam.

**Comment by dbuenzli** [comment]
So what's the problem then ?

**Comment by fxfactorial** [comment]
Okay, perhaps we are talking past one another. Can you provide an example of what you think I can do, explicit opam steps please.

**Comment by dbuenzli** [comment]
You can check in the build instructions of your opam package `p` that the environment is according to your wishes. If it's not fail and use a post-message that says to invoke `opam depext p`. In the depexts of your package `p` use a `source` depext that invokes a script that setups the environment according to your wishes. 

If you believe the setup should live in `opam`'s tree then you should rather do this through an opam package `p'` that `p` depends on.

**Comment by dra27** [comment]
@fxfactorial - is this is still an open issue for you?

**Comment by fxfactorial** [comment]
No
