### ISSUE TITLE
opam install apron fails

### ISSUE THREAD

**Issue by mihasighi** [ocaml/opam#2440]
Hi,

I'm using spam on a Darwin Kernel Version 15.3.0 RELEASE_X86_64 x86_64 
and trying to install apron package. The installation fails with errors
(reported in ~/.opam/system/build/apron.20160108/apron*.err

`ld: warning: directory not found for option '-L~/.opam/system/share/apron/lib'`
`ld: library not found for -lmpfr`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`File "caml_startup", line 1:
Error: Error during linking`
`make[1]: *** [apron.d.cmxs] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [apron.cmxs] Error 2
make: *** [ml] Error 2
`

maybe because of these last commands where -L/usr/local/lib is not present

`/usr/local/bin/ocamlmklib -dllpath ~/.opam/system/share/apron/lib -L~/.opam/system/share/apron/lib -o apron -oc apron_caml apron.cmx -lapron -lmpfr -lgmp -lm`
`/usr/local/bin/ocamlmklib -dllpath ~/.opam/system/share/apron/lib -L~/.opam/system/share/apron/lib -o apron.d -oc apron_caml_debug apron.cmx -lapron_debug -lmpfr -lgmp -lm`

Because libmpfr and libgmp are installed with homebrew

`$opam depext apron
Detecting depexts using flags: x86_64 osx homebrew
The following system packages are needed:
- gmp
- mpfr
  All required OS packages found.`

and

`$brew info mpfr
mpfr: stable 3.1.3 (bottled)
C library for multiple-precision floating-point computations
http://www.mpfr.org/
/usr/local/Cellar/mpfr/3.1.3 (24 files, 3.5M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/mpfr.rb
==> Dependencies
Build: xz ✔
Required: gmp ✔
`

**Comment by dsheets** [comment]
This works for me in a similar configuration (and OS X 10.11.2) both with and without `conf-ppl`.

What version of OCaml is running in the `system` switch? You may have better luck reporting this issue to the apron issue tracker at <https://gforge.inria.fr/tracker/?atid=8946&group_id=2625&func=browse>.

**Comment by mihasighi** [comment]
Hi,

On 2016-02-21 17:59, David Sheets wrote:
> This works for me in a similar configuration (and OS X 10.11.2) both
> with and without conf-ppl.

I also have another Mac on which the installation works well, called 
2009 below.

> What version of OCaml is running in the system switch?

I've applied ocamlfind list on both (2009 -- working one with OCaml 
4.02.3, 2014 -- not working one) and the result is:

$diff ~/ocamlfind.2009 ~/ocamlfind.2014

1,14c1
< apron               (version: 20160108)
< apron.apron         (version: n/a)
< apron.boxD          (version: n/a)
< apron.boxMPFR       (version: n/a)
< apron.boxMPQ        (version: n/a)
< apron.octD          (version: n/a)
< apron.octMPQ        (version: n/a)
< apron.polkaGrid     (version: n/a)
< apron.polkaMPQ      (version: n/a)
< apron.polkaRll      (version: n/a)
< apron.ppl           (version: n/a)
< apron.t1pD          (version: n/a)
< apron.t1pMPFR       (version: n/a)
< apron.t1pMPQ        (version: n/a)
---
> 
19,35c6,23
< camlp4              (version: [distributed with Ocaml])
< camlp4.exceptiontracer (version: [distributed with Ocaml])
< camlp4.extend       (version: [distributed with Ocaml])
< camlp4.foldgenerator (version: [distributed with Ocaml])
< camlp4.fulllib      (version: [distributed with Ocaml])
< camlp4.gramlib      (version: [distributed with Ocaml])
< camlp4.lib          (version: [distributed with Ocaml])
< camlp4.listcomprehension (version: [distributed with Ocaml])
< camlp4.locationstripper (version: [distributed with Ocaml])
< camlp4.macro        (version: [distributed with Ocaml])
< camlp4.mapgenerator (version: [distributed with Ocaml])
< camlp4.metagenerator (version: [distributed with Ocaml])
< camlp4.profiler     (version: [distributed with Ocaml])
< camlp4.quotations   (version: [distributed with Ocaml])
< camlp4.quotations.o (version: [distributed with Ocaml])
< camlp4.quotations.r (version: [distributed with Ocaml])
< camlp4.tracer       (version: [distributed with Ocaml])
---
> camllib             (version: 1.3.0)
> camlp4              (version: 4.02.3)
> camlp4.exceptiontracer (version: 4.02.3)
> camlp4.extend       (version: 4.02.3)
> camlp4.foldgenerator (version: 4.02.3)
> camlp4.fulllib      (version: 4.02.3)
> camlp4.gramlib      (version: 4.02.3)
> camlp4.lib          (version: 4.02.3)
> camlp4.listcomprehension (version: 4.02.3)
> camlp4.locationstripper (version: 4.02.3)
> camlp4.macro        (version: 4.02.3)
> camlp4.mapgenerator (version: 4.02.3)
> camlp4.metagenerator (version: 4.02.3)
> camlp4.profiler     (version: 4.02.3)
> camlp4.quotations   (version: 4.02.3)
> camlp4.quotations.o (version: 4.02.3)
> camlp4.quotations.r (version: 4.02.3)
> camlp4.tracer       (version: 4.02.3)
51a40
> cudd                (version: 2.3.0)
85a75
>

**Comment by mihasighi** [comment]
Very strange: the compilation of the opam sources for apron
(got from ~/.opam/archives/)
has no problems after setting correctly the Makefile.config !

Another colleague of mine has the same problem ...
It could be then a problem of opam packaging !

**Comment by AltGr** [comment]
Is this issue still relevant ? It looks indeed like a packaging issue.

**Comment by mihasighi** [comment]
On 2016-06-01 12:10, Louis Gesbert wrote:
> Is this issue still relevant ? It looks indeed like a packaging issue.
> 

Indeed, it was a problem of packaging Apron. Now, it is fixed for the 
latest version of spam (tried on a Mac OS 10.7).

**Comment by mihasighi** [comment]
On 2016-06-07 09:36, Mihaela Sighireanu wrote:
> On 2016-06-01 12:10, Louis Gesbert wrote:
>> Is this issue still relevant ? It looks indeed like a packaging issue.
>> 
> 
> Indeed, it was a problem of packaging Apron. Now, it is fixed for the
> latest version of spam (tried on a Mac OS 10.7).
                    ^^^^^^ opam

**Comment by UnixJunkie** [comment]
I think this can be closed, also, it should have been reported in https://github.com/ocaml/opam-repository/issues, not here.
