### ISSUE TITLE
Packages testing for presence of Cygwin

### ISSUE THREAD

**Issue by ghost** [ocaml/opam#2447]
I'd like to know if there is currently a way in OPAM to identify, for packaging purposes, the presence of Cygwin.

If I run `opam config list`, I get `os = win32`, but no more than that.

I wanted to be able to create a package constraint based on cygwin, something like:

```
[make] { os != "cygwin" }
[make "--prefix=$(cygpath %prefix%)"] { os = "cygwin" }
```

So far, I need to filter based on `os = "win32"` and then filter again (inside a script, using shell tests) to check for the presence of Cygwin.

There are at least two packages in `opam-repository` which check for `os = "cygwin"` (camlidl.1.05 and agrep.1.0) but I think their tests do not work.

My current solution works but is not ideal, I'm just asking in case there's a simpler way.

**Comment by AltGr** [comment]
Nothing at the moment I'm afraid. Opam 2.0 will delegate the definition of these variables to the compiler installation scripts, which will allow to easily provide such information in a more flexible way.

However, opam 1.2 bases the value of the `os` variable upon [Sys.os_type](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Sys.html#VALos_type). It doesnt document whether Cygwin is installed, though, only if OCaml was built with it I guess. There could be a virtual `conf-cygwin` package for that.

**Comment by dra27** [comment]
Which opam were you using to do this? A version compiled on Cygwin or one of the mingw builds?
