### ISSUE TITLE
opam lint should be configurable

### ISSUE THREAD

**Issue by gasche** [ocaml/opam#2448]
I looked, and it seems that there is currently no support for users willing to configure opam lint to enforce or non-enforce specific policies. I think that having this capability would solve many of the disagreements arising in ocaml/opam-repository#5791.

I'm not familiar with the internals of `lint`, and I don't know in particular whether it tries to detect to which repository a package is destined to. (I'm not using `opam publish` and I would suspect the long tail of contributors is not either).

At the least, I would expect the ability to pass configuration options as command-line parameters to the tool. It would be interesting to have a more convenient way to pass configuration through an implicit file, eg. some preference file in `.opam`.
It would be useful to be able to make those configuration options depend on the repository for which the linted file is intended, but I don't know how to inform `opam lint` of this. Any support for this in the OPAM codebase would still be useful even if user-local can't use it, as it would also be available to camelus for free -- if I understand [the camelus sources](https://github.com/AltGr/Camelus/blob/master/opam_ci.ml#L228-L234) correctly.

(In particular, any explicit way for repos to set Q/A configuration options in their own configuration could rely on this capability, and needs it to be implemented.)

**Comment by AltGr** [comment]
Indeed, I numbered the warnings and errors a while ago for that purpose, which was the larger part of the work: it's now just a question of interface. Repositories have a configuration file already, which may be used by Camelus (but in this case, wouldn't it be simpler to just give the right arguments to the Camelus instance ?), and possibly opam-publish, by checking the file from the repository it's generating the PR for.

**Comment by AltGr** [comment]
One further thought: I believe it's undesirable to make Camelus checks depend on options that are versionned in the repo it is checking (as travis does). Using a separate channel to specify the options guarantees a PR can't choose the terms on which it is tested.

**Comment by AltGr** [comment]
(one further note: the repository-checking script `admin-scripts/lint.ml` offers command-line switches to enable or disable warnings based on their number)

**Comment by avsm** [comment]
@altgr could we just move `opam lint` into being an external plugin that uses opamlib? will be easier to add custom policies then

**Comment by AltGr** [comment]
Seems this was closed by mistake; `opam lint` should be configurable, at least from the command-line to begin with.

**Comment by AltGr** [comment]
You can now specify e.g. `opam lint -w +10..40-17`, which should solve this ticket.
