### ISSUE TITLE
Best effort `opam switch import`

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#2450]
It would be nice to have a `--best-effort` (or `--skip-failures`, or ...) option in `opam switch import`. Currently if a single constraint can't be satisified everything fails, e.g.: 

```
The following dependencies couldn't be met:
  - cohttp -> sexplib < 113.01.00
Your request can't be satisfied:
  - sexplib<113.01.00 is not available because your system doesn't comply with ocaml-version >= "4.02.1" & ocaml-version < "4.03".
```

But a lot of the other elements that do not depend on this can still be installed.

**Comment by dbuenzli** [comment]
Another thing would be to avoid aborting installations of packages whenever one of its depopts fails but install it nevertheless.

**Comment by AltGr** [comment]
Not really a duplicate, but the idea already arose in #1520 

On your second proposition, it's indeed a possibility, but I am not sure it should be the default. At the moment, once we are at the processing stage, we have a graph of actions which doesn't distinguish anymore between the reasons why the actions have to be ordered in a given way, so it could be tricky to implement.

**Comment by dbuenzli** [comment]
> but I am not sure it should be the default.

Why ? I think it should, and also on `opam upgrades`. It makes the system much more usable as it keeps the installed packages in my switch as much as possible the same as they were before the failure.

The problem with aborts is that when a depopt package fails I then have to *remember* and *manually* reinstall all the packages that were aborted because of the depopt failure. 

I would much more prefer if these packages would simply reinstall without the depopt. These will simply get recompiled once the depopt failure has been resolved which frees me from remembering which packages are no longer installed because of the depopt failure. The initial state will then naturally be recovered once a new `opam update` solves the problem. 

This would also be very useful for `pins` were failures can be more widespread and kill part of your switch install base because you made a hasty commit that doesn't compile.

**Comment by AltGr** [comment]
I had in mind the case where you want A with a specific depopt B and type `opam install A B`. In this specific case, the time spent building B is just wasted. That's why I wasn't sure, I wasn't sure either it shouldn't be the default.

**Comment by dbuenzli** [comment]
> the time spent building B is just wasted

Maybe we could simply ask.

**Comment by AltGr** [comment]
The new `--soft-request` applies to `import` as well, and results in the requested feature \o/
Not hard-failing on depopts that failed to build is a different story though, that should probably be tracked separately.
