### ISSUE TITLE
Error during switch reinstall leads to broken OPAM

### ISSUE THREAD

**Issue by thranur** [ocaml/opam#2454]
**Note: I believe I've been able to simplify the situation in a subsequent message, so it might be better to just read my next post before reading this one; the solution there should be applicable to this case as well. I'm just leaving this one here for completion.**

This is my setup:
- A local OCaml git clone;
- A local repository created via `opam remote add`, following recommendations from https://github.com/ocaml/opam/wiki/FAQ;
- A `local_beta.comp/descr` pair created in my local repository, which point to a `file:///...` containing a local branch of the OCaml git clone;
- I'm then trying to do `opam install switch local_beta` or `opam reinstall switch local_beta` while I locally modify my OCaml git clone.

What I observed is that:
- If there is an error during compilation of OCaml, OPAM stops and displays:
  
  ```
  The former package state can be restored with opam switch import
   "/home/user/.opam/backup/state-20160202141016.export" --switch local_beta
  ```

If I copy that exact command and run it, I get:

```
Fatal error:
# opam-version    1.2.2
# os              linux
opam: "open" failed on /home/user/.opam/local_beta/lock: No such file or directory
```

If I manually do a `opam switch <previous existing and working OCaml compiler>`, and then type the indicated command, it seems to work better, but it fails again later.

Also, during such processes I get lots of `[ERROR] No global config file found for switch local_beta. Switch broken ?` and instability, such that I still didn't find the proper way of restoring to a working configuration. I ended up having to manually clean my `.opam` directories mentioning the `local_beta` switch and erasing references from files such as `compiler-index` and `aliases`, to manually restore a "stable" situation.

Finally (this has probably been mentioned in another issue), the `switch reinstall` error message, when the switch is not installed, is not clear at all: `opam: "open" failed on /home/user/.opam/localbeta/lock: No such file or directory`. I would not mind having a `reinstall` command that emits a warning if nothing is installed, and then installs it anyway, but anyway the error message could be clearer.

I found that the situation with packages (instead of compilers) is much more stable: even if the `reinstall` fails once, the second time it always seems to work. But dealing with switches is more complicated and there is an excessive amount of states and situations to consider. I'm just pointing out some issues I've had, in hopes it might help, but unfortunately I do not have any solutions to propose (other than changing some error messages).

**Comment by thranur** [comment]
This is a related behavior that I noticed, that could be simpler to solve (and is possibly the cause of the complex situation I just described):

- I wanted to do a `opam switch 4.02.1+fp`, because I already have such a compiler installed in my `.opam`;
- I accidentally typed `opam switch 4.02.1` instead, so it started downloading and compiling a different compiler;
- Because I didn't have time to wait until it was finished, I hurriedly pressed `Ctrl+C`.

This left my opam in the following state:

1. `opam switch` thinks the 4.02.1 compiler was successfully installed:

        opam switch
        ....
        4.02.1        I 4.02.1        Official 4.02.1 release

2. I cannot actually switch to it because it is not really installed:

        opam switch 4.02.1
        [ERROR] No global config file found for switch 4.02.1. Switch broken ?
        [ERROR] No global config file found for switch 4.02.1. Switch broken ?
        [ERROR] No global config file found for switch 4.02.1. Switch broken ?
        [ERROR] No global config file found for switch 4.02.1. Switch broken ?
        # To setup the new switch in the current shell, you need to run:
        eval `opam config env --switch=4.02.1`
        Fatal error:
        # opam-version    1.2.2
        # os              linux
        opam: "open" failed on /home/user/.opam/4.02.1/lock: No such file or directory

3. I cannot remove the switch, nor tell OPAM that it is in fact not installed:

        opam switch remove 4.02.1
        The compiler switch 4.02.1 does not exist.

`opam switch reinstall` also fails.

The only way I've currently been able to undo this is by manually deleting specific files, directories and lines in `.opam` as described in my previous message.

An option such as `opam switch remove --force`, which would perform the same steps as my manual deletion, would be very useful and allow the user to always revert to a "stable" state (if I correctly understood what happened here).

**Comment by AltGr** [comment]
Thanks a lot for the detailed reports. Indeed, we tried to make sure to behave as well as possible on Ctrl-c whenever it happens, but it seems you have hit a bad case that we missed -- sorry about it!

The upcoming version of opam properly separates switch creation from packages installation (including the compiler), and it allows empty switches, which should avoid most of these corner-cases.

**Comment by thranur** [comment]
Thanks!

Anyway, if I'm reporting these issues, it's because opam enabled me to do several kinds of complex configurations that I'd probably not have done myself in pre-opam times. The more powerful you make opam, the more likely it is to invent a new scenario which has not been thought of before...
