### ISSUE TITLE
cudf tarball's checksum has changed

### ISSUE THREAD

**Issue by seliopou** [ocaml/opam#2455]
While trying to run `make lib-ext`, I ran into the following error:

```
[ -e  cudf.0.7+opam.tar.gz ] || curl  -OL http://opam.ocaml.org/archives/cudf.0.7+opam.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 56162  100 56162    0     0   180k      0 --:--:-- --:--:-- --:--:--  179k
ocaml ../shell/md5check.ml cudf.0.7+opam.tar.gz 2c23f4a6c377270c34962574a1bed669
MD5 for cudf.0.7+opam.tar.gz differ:
  expected: 2c23f4a6c377270c34962574a1bed669
    actual: 787f21acee9940cc902f16e8a58ac79f
mkdir -p tmp
cd tmp && tar xfz ../cudf.0.7+opam.tar.gz
tar: Error opening archive: Failed to open '../cudf.0.7+opam.tar.gz'
Makefile:55: recipe for target 'cudf.stamp' failed
gmake: *** [cudf.stamp] Error 1
```

It seems as though the checksum for the cudf tarball has changed, which leads to the build failing.

Related to this bug report is are a few questions: are the maintainers aware that the content of the tarball has changed? Is it safe to use the new tarball?

**Comment by AltGr** [comment]
I think if you can trust @abate it's safe  -- I'l let him confirm :)

**Comment by dbuenzli** [comment]
Trustable or not it is not acceptable to tweak release tarballs after they have been published. Don't people have any idea on how to do releases these days ?

**Comment by abate** [comment]
cudf is not my baby . @rdicosmo : do you know what is going on ?

**Comment by rdicosmo** [comment]
It's Zack's library... cc:ing him

On Fri, Mar 04, 2016 at 01:43:44AM -0800, Pietro Abate wrote:
> cudf is not my baby . @rdicosmo : do you know what is going on ?
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

-- 
Roberto Di Cosmo
 
------------------------------------------------------------------
Professeur               En detachement a l'INRIA
PPS                      E-mail: roberto@dicosmo.org
Universite Paris Diderot WWW  : http://www.dicosmo.org
Case 7014                Tel  : ++33-(0)1-57 27 92 20
5, Rue Thomas Mann       
F-75205 Paris Cedex 13   Identica: http://identi.ca/rdicosmo
FRANCE.                  Twitter: http://twitter.com/rdicosmo
------------------------------------------------------------------
Attachments:
MIME accepted, Word deprecated
      http://www.gnu.org/philosophy/no-word-attachments.html
------------------------------------------------------------------
Office location:
 
Bureau 3020 (3rd floor)
Batiment Sophie Germain
8 place Aurélie Nemours
Metro Bibliotheque Francois Mitterrand, ligne 14/RER C
-----------------------------------------------------------------
GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3

**Comment by AltGr** [comment]
Actually, no need!
The upstream tarball hasn't changed. This is the repackaged opam archive -- we switched to it when the inria gforge had issues, and didn't revert.
Now I'll investigate _why_ the opam-repository archive has changed: this normally doesn't happen.

(Note: opam 2.0 won't repackage archives)

**Comment by AltGr** [comment]
@seliopou: if you have a minute, you can fix this by falling back to the real upstream (as pointed to by the repository's cudf.0.7 package)

**Comment by rdicosmo** [comment]
On Fri, Mar 04, 2016 at 10:50:20AM +0100, Roberto Di Cosmo wrote:
> It's Zack's library... cc:ing him

I have no idea what you 2 are talking about and can't find a reference
to the relevant GitHub issue in your email. But FWIW no CUDF release has
been done in a while.

-- 
Stefano Zacchiroli  . . . . . . .  zack@upsilon.cc . . . . o . . . o . o
Maître de conférences . . . . . http://upsilon.cc/zack . . . o . . . o o
Former Debian Project Leader . . . . . @zacchiro . . . . o o o . . . o .
« the first rule of tautology club is the first rule of tautology club »

**Comment by rdicosmo** [comment]
You can forget the issue: they found out it is not on our side ;-)

On Fri, Mar 04, 2016 at 11:10:41AM +0100, Stefano Zacchiroli wrote:
> On Fri, Mar 04, 2016 at 10:50:20AM +0100, Roberto Di Cosmo wrote:
> > It's Zack's library... cc:ing him
> 
> I have no idea what you 2 are talking about and can't find a reference
> to the relevant GitHub issue in your email. But FWIW no CUDF release has
> been done in a while.
> 
> -- 
> Stefano Zacchiroli  . . . . . . .  zack@upsilon.cc . . . . o . . . o . o
> Maître de conférences . . . . . http://upsilon.cc/zack . . . o . . . o o
> Former Debian Project Leader . . . . . @zacchiro . . . . o o o . . . o .
> « the first rule of tautology club is the first rule of tautology club »

-- 
Roberto Di Cosmo
 
------------------------------------------------------------------
Professeur               En detachement a l'INRIA
PPS                      E-mail: roberto@dicosmo.org
Universite Paris Diderot WWW  : http://www.dicosmo.org
Case 7014                Tel  : ++33-(0)1-57 27 92 20
5, Rue Thomas Mann       
F-75205 Paris Cedex 13   Identica: http://identi.ca/rdicosmo
FRANCE.                  Twitter: http://twitter.com/rdicosmo
------------------------------------------------------------------
Attachments:
MIME accepted, Word deprecated
      http://www.gnu.org/philosophy/no-word-attachments.html
------------------------------------------------------------------
Office location:
 
Bureau 3020 (3rd floor)
Batiment Sophie Germain
8 place Aurélie Nemours
Metro Bibliotheque Francois Mitterrand, ligne 14/RER C
-----------------------------------------------------------------
GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3
