### ISSUE TITLE
Longer stderr output at build failures

### ISSUE THREAD

**Issue by camlspotter** [ocaml/opam#2457]
Related: https://github.com/ocaml/opam-repository/issues/5860

Is there a way to control the number of stderr lines when opam failed to install a package?  Currently it seems to be 10 lines, but using `omake` it is often the case that 10 lines are not enough and I need always to see the stderr file itself.

Locally it is not a big issue but in Travis of `opam-repository`: I guess there is no way to see the stderr dump for the pull-requester.  It is very hard to understand the real cause of the build failure, especially when I cannot prepare the exactly same build environment (OS, compiler versions and so on) Travis does.  .... or can we see the stderr dump somehow?

**Comment by AltGr** [comment]
There is: set the `OPAMERRLOGLEN` environment variable.
It's documented in `opam --help`

Related: #2133 
--json will also include reports, including all logs, in a json file.

**Comment by camlspotter** [comment]
Thanks.  Checked that it will be available in 1.3.0.  (not in 1.2.2
