### ISSUE TITLE
opam lint should be more careful about self-references

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#2458]
Since I didn't get [any answer](http://lists.ocaml.org/pipermail/opam-devel/2016-February/001342.html) I'll repeat the question here.

I'm trying to refer to `%{mypkg:etc}%` in `mypkg`'s opam `build:` section. It works perfectly but `opam lint` complains:  

```
warning 41: Some packages are mentionned in package scripts of features, but there is no dependency or depopt toward them
```

So either there's another way or `opam lint` should not complain about this.

**Comment by AltGr** [comment]
You can write `%{_:etc}%`, but I don't think that was in 1.2. Anyway, your point remains and this is a bug in `opam lint`. Thanks for reporting!
