### ISSUE TITLE
Solver don't want to choose the latest package version

### ISSUE THREAD

**Issue by ivg** [ocaml/opam#2462]
This is 

```
$ opam --version
1.2.2
```

With just freshly create state with compiler `4.02.3`, when I try to install with just `opam install bap`, it tries to install version `0.9.4`, while the latest available version is `0.9.9`.  The latest version is installable, but has 6 more dependencies.
Here is the [CUDF](https://github.com/ocaml/opam/files/159225/bap-cudf.zip).

Do you have any suggestions?

**Comment by ivg** [comment]
my guess, is that version is improperly constrained, i.e., most of the packages has a halfopen interval of constrains, or even no constraint at all (that actually signals, that this version will fail to install). So the solver, minimizes the version lag of all dependencies, so that total freshness of the repository would be better, than for the latest version (that is properly constraint). So a proper solution on my side, would be to retroactively constraint old versions of bap.

On the opam side, is it possible to prioritize the version lag of the target package over the cumulative version lags of the dependencies? I.e., if a user request for a package `xxx` then intuitively he wants to get the latest available version, and he really doesn't care about the versions of dependencies.

**Comment by dsheets** [comment]
What is the output of `opam config report`?

**Comment by AltGr** [comment]
> On the opam side, is it possible to prioritize the version lag of the target package over the cumulative version lags of the dependencies?

With aspcud, we normally would do just that: the [default criteria](https://github.com/ocaml/opam/blob/5507426030a60c50f7479ac758d116b573fdbd5e/src/solver/opamSolverConfig.ml#L155-L167) are:
```
-count(removed),\
-notuptodate(request),-sum(request,version-lag),\
-count(down),\
-notuptodate(changed),-count(changed),\
-notuptodate(solution),-sum(solution,version-lag)
```
Notice that `-sum(request,version-lag)` -- minimise the version lag of packages included in the _request_ -- is much before `-sum(solution,version-lag)` -- minimise the version lag of _all_ packages included in the solution.

Your cudf file, however, shows that opam is using the older, compat criteria (`-removed,-notuptodate,-changed`), which obviously aren't that clever. Please check your criteria (`opam config report`). Newer dev versions have a broader compatibility with different solvers, but 1.2.2 is picky about having aspcud 1.9 to select the better criteria.

**Comment by ivg** [comment]
Looks like, that I have the latest release, with the compat criterion, since I have aspcud-1.8 installed in my system: 
```
$ opam config report
# OPAM config report
# opam-version    1.2.2 
# self-upgrade    no
# os              linux
# external-solver aspcud $in $out $criteria
# criteria        -removed,-notuptodate,-changed
# jobs            16
# repositories    1* (http), 1 (local)
# pinned          3 (path), 1 (version control)
# current-switch  4.02.3
# last-update     2016-03-04 13:10
```

I've tried with the `1.9.0` and can confirm, that the latest version is chosen. 

Thanks!
