### ISSUE TITLE
Add `description` field to findlib subpackages

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/opam#2463]
It would be great if all of [these](https://github.com/ocaml/opam/blob/5507426030a60c50f7479ac758d116b573fdbd5e/META.in#L7-L40) findlib subpackages had short descriptions.

I'd write them myself but I don't know enough about opam-lib yet.

**Comment by AltGr** [comment]
Indeed; short descriptions are available here: http://opam.ocaml.org/doc/2.0/api/

**Comment by dra27** [comment]
Descriptions were added in 30c19fba48e4200c68d6b1d01902bf6da098b7df; I think this can be closed?
