### ISSUE TITLE
feature request: find latest working version of a dependency

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#2466]
Hello,

opam --find-latest-depexts some_package

For the package named some_package, the command would find via a dichotomic search
the latest version compatible with some_package for each of its depext
that cannot be installed to its latest available version.

**Comment by AltGr** [comment]
This seems difficult, for two reasons:
- (i) opam has no notion of versions of the depexts (those are handled transparently by the host package manager)
- (ii) package managers don't, in general, provide multiple versions of the packages

**Comment by UnixJunkie** [comment]
I wrote a mistake. I meant for the depends field of the opam file, not the depexts.

**Comment by AltGr** [comment]
I belive the new `opam list --coinstallable-with` should fulfill that usecase. Thanks!
