### ISSUE TITLE
Add OpamFile.OPAM.fields

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#2470]
with signature: 
```
val fields : t -> value OpamStd.String.Map.t
```
like `OpamFile.OPAM.extensions` but with all the fields. The current interface is a little bit annoying to query arbitrary fields. Related to #2446.

**Comment by AltGr** [comment]
Indeed; you could obtain it using the low-level functions (from `OpamFile.Syntax` -- which is not exported at the moment). It may be preferable, however, to load the opam file properly using `OpamFile.OPAM` and reprint its fields, to take the syntactic sugar and rewritings into account.

**Comment by dbuenzli** [comment]
> to load the opam file properly using OpamFile.OPAM and reprint its fields, to take the syntactic sugar and rewritings into account.

That's what I'm doing, but then everytime you add new fields to the OPAM file format I need to update my code which is suboptimal for generic query functionality like #2246.

**Comment by dbuenzli** [comment]
This seems to exists in v2. https://opam.ocaml.org/doc/2.0/api/ocamldoc/OpamFile.OPAM.html#VALfields
