### ISSUE TITLE
Feature request: lint that warns on %{x}

### ISSUE THREAD

**Issue by whitequark** [ocaml/opam#2473]
Nothing else uses this substitution syntax and it's an error I made over ten times just *today*. Bonus points if it checks the files referenced by `substs:`.

**Comment by AltGr** [comment]
Ah! I thought we had this already, but indeed, while the code for detecting this case is present in the filter-handling [code](https://github.com/ocaml/opam/blob/master/src/format/opamFilter.ml#L179), it hasn't been bound to `opam lint`.

I'll fix this, thanks for reporting. As for the `substs:` files, however, those are part of the package source, and lint purely acts on the metadata at the moment.
