### ISSUE TITLE
upgrade leaves me in a catastrophic state

### ISSUE THREAD

**Issue by peterfrey** [ocaml/opam#2477]
I executed: sudo opam ugrade
then:

```
===== ERROR while installing conf-ncurses.1 =====
# opam-version 1.1.0
# os           linux
# command      pkg-config ncurses
# path         /home/peter/.opam/4.02.1/build/conf-ncurses.1
# compiler     4.02.1
# exit-code    1
# env-file     /home/peter/.opam/4.02.1/build/conf-ncurses.1/conf-ncurses-30604-813bac.env
# stdout-file  /home/peter/.opam/4.02.1/build/conf-ncurses.1/conf-ncurses-30604-813bac.out
# stderr-file  /home/peter/.opam/4.02.1/build/conf-ncurses.1/conf-ncurses-30604-813bac.err

The former state can be restored with opam switch import -f "/home/peter/.opam/4.02.1/backup/state-20160213165228.export"
'opam upgrade' failed.
```

After restoring with above command I need to accept :
```
85 to install | 0 to reinstall | 1 to upgrade | 0 to downgrade | 0 to remove
Do you want to continue ? [Y/n] n
```

But I arrive again at the same problem.
I tried to install ocamlfind, but that wants camlp4 and during that installation conf-ncurses get invoked
and I am dead again.

At the moment I can't even compile; the backup files are gone.
Do I re-install everything??
How can I be sure this ncurses-thing does not rear its head again?

Peter

**Comment by AltGr** [comment]
> I executed: sudo opam ugrade
You shouldn't need to `sudo`

> # opam-version 1.1.0

This is quite old, please try to upgrade to 1.2.2 if possible. The 1.1 repository is no longer updated.

Otherwise, it seems you are missing a system dependency, make sure that you have `libncurses-dev` or similar installed on your system.

**Comment by peterfrey** [comment]
thanks.
missing libncurses was the problem.
According to my (synaptic) package manager I had the second latest 
version installed; but it appears it was not active.
I am not sure what happened. Using the lines below (after un-installing 
that version)

|add-apt-repository ppa:avsm/ppa apt-get update apt-get install ocaml 
opam things got fixed. I was afraid opam would overwrite the current 
configuration, but opam is smarter than I am ... |

all is well again.
There does not seem to be a upgrade/update for opam itself.  The (very 
nice) manual is silent on it.
It is not needed; but perhaps the manual could mention that it can 
simply be re-installed when new versions come out.

thanks again
Peter
