### ISSUE TITLE
git branch fetches failing in older distros

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#2483]
Doing some bulk builds, and noting that some fail when fetching Git branches (from the Core PR in #5928)

https://github.com/avsm/opam-pr-build-results/blob/5928/README.md has the list of builds, and:
- https://github.com/avsm/opam-pr-build-results/blob/5928/build/log.centos-6_ocaml-4.02.3
- https://github.com/avsm/opam-pr-build-results/blob/5928/build/log.ubuntu-12.04_ocaml-4.02.3

are two examples where the sources aren't available.

@AltGr, is there a minimum git version needed?

**Comment by AltGr** [comment]
I think this was fixed by 8fcae42a
