### ISSUE TITLE
opam pin add obuild git@github.com:ocaml-obuild/obuild.git

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#2485]
Apparently, if I pin a package with a git URL, the X.install file is ignored despite there is one
in the git repository.

**Comment by dsheets** [comment]
This may be related to #2095.

**Comment by AltGr** [comment]
Weird, .install file handling shouldn't be dependent on the fact that the package has been pinned. Where is your `.install` file ? It should be at the root of the source tree. Also, the name must be `<name>.install`, where `<name>` is the name the package is being pinned as.

**Comment by UnixJunkie** [comment]
obuild.install is at the root, same for the opam file.
You can see the dev repo here: https://github.com/ocaml-obuild/obuild

**Comment by AltGr** [comment]
Confirmed working (may have been fixed since)
