### ISSUE TITLE
Dev version of opam gives non-sensical solution

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2486]
I'm not sure what's the problem. After noticing it. I upgraded everything (clasp, gringo, aspcud) without any change. Here is a log: https://gist.github.com/Drup/2de105c953341908a737
It also seems to takes a very long to come up with a solution, much longer than it should. 

```
% opam --git-version
fe1a2db6aebf953c258fbda69935db6814aa38a5
```
```
% opam config report
# OPAM config report
# opam-version    1.3.0~dev3 (fe1a2db6aebf953c258fbda69935db6814aa38a5) 
# self-upgrade    no
# os              linux
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            4
# repositories    1 (http), 3 (version-controlled)
# pinned          9 (version control)
# current-switch  4.02.3
# last-update     2016-03-22 12:28
```

**Comment by Drup** [comment]
It gives similar result if I use the solver farm, so it's probably not my local install that is wrong.

**Comment by Drup** [comment]
@AltGr This is very annoying. If this can't be solved in the near future, how do I downgrade back to stable opam ?

**Comment by lefessan** [comment]
I'm not sure I understand your problem: you asked for reinstall of tyxml, and that's what OPAM proposes to do. There seems to be an heuristics to minimize the number of installed packages, and that's probably the reason why it wants to remove some depopts too (and recompile concerned packages). Have you tried with other optimization criteria ?

**Comment by AltGr** [comment]
I am not sure what happens; such removals may happen when no metadata for the packages can be found anymore, or they are no longer available (try `opam reinstall tcpip --show` to see what happens ?).
The problem probably comes from the fact that recent dev opam requires the compiler defined as a package, which is not the case in the official repository. ~/.opam migration should have taken care of it locally, but it has not yet been extensively tested. You might want to try setting your remote to https://github.com/ocaml/opam-repository/tree/next — no automatic rewrite is in place yet.

I am guessing these packages may depend on `ocaml-version` which is no longer properly defined. You might want to try `opam config set ocaml-version xxx` by hand (it's now just a switch configuration variable, no longer a built-in)...

Sorry that the dev version is quite unstable lately. I am making good progress on testing and fixing (on branch "next") recently, and hope to get back to something more usable soon. I am sorry there is no code for _down_-grading your `~/.opam`.

I'd still like to thank you for testing the dev version and reporting!

**Comment by Drup** [comment]
@lefessan The optimization criteria is the default one, I don't have any custom thing and It doesn't (shouldn't) minimize installed packages. In particular, it should minimize removals ... Also, this behavior is new.

In general it gives me the same kind of solution that the internal solver would: random upgrade, downgrade and removal, bogus "impossible to upgrade" things, and so on.

@AltGr I'm not using the `next` branch, just the master one. The `ocaml-version` variable seems to still be defined there. Should I move to the `next` repository ?

```
% opam reinstall tcpip --show
tcpip is not installed. Install it ? [Y/n] y
The following actions would be performed:
  ∗  install channel 1.0.0                    [required by tcpip]
  ∗  install tcpip   2.7.0
===== ∗  2 =====
```

**Comment by AltGr** [comment]
@Drup what is the status of this ? Hopefully later versions + the rewritten 2.0~dev repo have fixed it ?

**Comment by Drup** [comment]
I haven't seen the problem again with 2.0, so yes, you probably fixed it on the way!
