### ISSUE TITLE
opam cannot install extlib

### ISSUE THREAD

**Issue by AbsCharlotte** [ocaml/opam#2489]
My opam cannot install extlib, I get the following message:
The dependency base-ocamlbuild of package ocamlbuild.0 is not available for your compiler or your OS.
'opam install extlib' failed.

I get exactly the same message if I try to install base-ocamlbuild or ocamlbuild.

I run Opam 1.1.1 and my current ocaml is 4.02.3

An idea where this message comes from? Any help would be appreciated!

Thanks
Charlotte

**Comment by dsheets** [comment]
We recommend using opam 1.2 or later with an external solver like `aspcud` installed. 1.2.2 is the newest stable version and likely fixes this problem. Support for opam 1.1 is ending soon.
