### ISSUE TITLE
unable to install opam on a shared server (no root access!)

### ISSUE THREAD

**Issue by hgouraud** [ocaml/opam#2491]
Rather mysterious!!
Would anyone have a suggestion to install opam on a remote shared server, given that I do not have root privilege on this machine (I am its only user).

Thanks
Henri

(uiserver):u72332903:~/packages/opam > ./configure --prefix=/kunden/homepages/30/d456759237/htdocs/packages/bin-opam
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for ocamlc... ocamlc
OCaml version is 3.12.1
OCaml library path is /kunden/homepages/30/d456759237/htdocs/lib/ocaml
checking for ocamlopt... ocamlopt
....
checking for ocamlyacc... ocamlyacc
checking for ocamlfind... no
checking for curl... curl

checking for OCaml findlib package unix... not found
checking for OCaml findlib package extlib... not found
checking for OCaml findlib package re... not found
checking for OCaml findlib package re.emacs... not found
checking for OCaml findlib package re.str... not found
checking for OCaml findlib package re.perl... not found
checking for OCaml findlib package re.pcre... not found
checking for OCaml findlib package re.glob... not found
checking for OCaml findlib package cmdliner... not found
checking for OCaml findlib package ocamlgraph... not found
checking for OCaml findlib package cudf... not found
checking for OCaml findlib package dose3.common... not found
checking for OCaml findlib package dose3.algo... not found
checking for OCaml findlib package jsonm... not found

Some dependencies are missing. If you are just interested in the stand-alone
binaries, run 'make lib-ext' to download and include them.

configure: creating ./config.status
config.status: creating Makefile.config
config.status: creating META
config.status: creating src/core/opamVersion.ml

Executables will be installed in /kunden/homepages/30/d456759237/htdocs/packages/bin-opam/bin
Manual pages will be installed in /kunden/homepages/30/d456759237/htdocs/packages/bin-opam/share/man
(uiserver):u72332903:~/packages/opam >
(uiserver):u72332903:~/packages/opam > make
make -C src opam-lib
make[1]: Entering directory /homepages/30/d456759237/htdocs/packages/opam/src' Makefile:49: **\* Dependencies missing. Either run 'make lib-ext' or install them and re-run './configure'. Stop. make[1]: Leaving directory/homepages/30/d456759237/htdocs/packages/opam/src'
make: **\* [opam-lib] Error 2
(uiserver):u72332903:~/packages/opam > make lib-ext
make -C src_ext lib-ext
make[1]: Entering directory /homepages/30/d456759237/htdocs/packages/opam/src_ext' cp graph/src/sig.mli graph/src/sig.ml cp graph/src/sig_pack.mli graph/src/sig_pack.ml cp graph/src/dot_ast.mli graph/src/dot_ast.ml [ ocamlc.opt = no ] || make -f ../OCamlMakefile subprojs SUBTARGET=bcl make[2]: Entering directory/homepages/30/d456759237/htdocs/packages/opam/src_ext'
make[3]: Entering directory /homepages/30/d456759237/htdocs/packages/opam/src_ext' make[4]: Entering directory/homepages/30/d456759237/htdocs/packages/opam/src_ext'
ocamldep -I extlib/ extlib/extArray.mli > ._bcdi/extlib/extArray.di
/bin/sh: /kunden/homepages/30/d456759237/htdocs/bin/ocamldep: /usr/local/bin/ocamlrun: bad interpreter: No such file or directory
make[4]: **\* Deleting file ._bcdi/extlib/extArray.di' .... ocamlopt.opt -pack -o graph.cmx graph/lib/bitv.cmx graph/lib/heap.cmx graph/lib/unionfind.cmx graph/src/sig_pack.cmx graph/src/sig.cmx graph/src/dot_ast.cmx graph/src/builder.cmx graph/src/classic.cmx graph/src/contraction.cmx graph/src/delaunay.cmx graph/src/dominator.cmx graph/src/dot_parser.cmx graph/src/fixpoint.cmx graph/src/gmap.cmx graph/src/gml.cmx graph/src/graphml.cmx graph/src/graphviz.cmx graph/src/leaderlist.cmx graph/src/oper.cmx graph/src/rand.cmx graph/src/strat.cmx graph/src/traverse.cmx graph/src/util.cmx graph/src/version.cmx graph/src/kruskal.cmx graph/src/flow.cmx graph/src/dot_lexer.cmx graph/src/components.cmx graph/src/coloring.cmx graph/src/blocks.cmx graph/src/dot.cmx graph/src/imperative.cmx graph/src/merge.cmx graph/src/minsep.cmx graph/src/persistent.cmx graph/src/nonnegative.cmx graph/src/path.cmx graph/src/topological.cmx graph/src/pack.cmx graph/src/mcs_m.cmx graph/src/cliquetree.cmx graph/src/md.cmx File "graph.cmx", line 1, characters 0-1: Error: File graph/src/dot.cmx was compiled without access to the .cmx file for module Dot_lexer, which was produced byocamlopt -for-pack'.
Please recompile graph/src/dot.cmx with the correct -I' option so that Dot_lexer.cmx is found. make[4]: **\* [graph.cmi] Error 2 make[4]: **\* Deleting filegraph.cmi'
make[4]: Leaving directory /homepages/30/d456759237/htdocs/packages/opam/src_ext' make[3]: **\* [native-code-library] Error 2 make[3]: Leaving directory/homepages/30/d456759237/htdocs/packages/opam/src_ext'
make[2]: **\* [subproj_graph] Error 2
make[2]: Leaving directory /homepages/30/d456759237/htdocs/packages/opam/src_ext' make[1]: **\* [build] Error 2 make[1]: Leaving directory/homepages/30/d456759237/htdocs/packages/opam/src_ext'
make: **\* [lib-ext] Error 2
(uiserver):u72332903:~/packages/opam >

**Comment by AltGr** [comment]
Repeating the opam log, but:
```
Some dependencies are missing. If you are just interested in the stand-alone
binaries, run 'make lib-ext' to download and include them.
```
Did you try that ? Dont forget to use e.g. `./configure --prefix ~/local` too if you want to install into your `HOME`.

**Comment by hannesm** [comment]
it seems that `/bin/sh: /kunden/homepages/30/d456759237/htdocs/bin/ocamldep: /usr/local/bin/ocamlrun: bad interpreter: No such file or directory` is the fatal problem (during `make lib-ext`)

**Comment by hgouraud** [comment]
yes, I can indeed see that, but how do I fix it?
I dont have root access, so ocamlrun cannot be installed in /usr/local/bib

H

**Comment by hgouraud** [comment]
Yes, I have configured with —prefix

**Comment by hgouraud** [comment]
Here is where ocamlrun is !
kunden/homepages/30/d456759237/htdocs/bin
(uiserver):u72333:~/bin > ls -al ocamlrun 
-rwxr-xr-x 1 u72333 ftpusers 164140 Jun 30  2013 ocamlrun
(uiserver):u72333:~/bin >

**Comment by samoht** [comment]
Seems that your ocaml installation is broken. How did you install it?

**Comment by hgouraud** [comment]
Just tried again :
starting from ocaml-4.02.3.tar.gz
tar xf
cd ocaml-4.02.3
.configure —prefix ~/local
make world.opt

fails :
(….)
cd asmrun; make all
make[4]: Entering directory `/homepages/30/d456759237/htdocs/packages/ocaml-4.02.3/asmrun'
gcc -I../byterun -DCAML_NAME_SPACE -DNATIVE_CODE -DTARGET_amd64 -DSYS_linux  -O -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT   -c -o startup.o startup.c
gcc -I../byterun -DCAML_NAME_SPACE -DNATIVE_CODE -DTARGET_amd64 -DSYS_linux  -O -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT   -c -o main.o main.c
gcc -I../byterun -DCAML_NAME_SPACE -DNATIVE_CODE -DTARGET_amd64 -DSYS_linux  -O -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT   -c -o fail.o fail.c
gcc -I../byterun -DCAML_NAME_SPACE -DNATIVE_CODE -DTARGET_amd64 -DSYS_linux  -O -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT   -c -o roots.o roots.c
gcc -I../byterun -DCAML_NAME_SPACE -DNATIVE_CODE -DTARGET_amd64 -DSYS_linux  -O -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT   -c -o globroots.o globroots.c
gcc -I../byterun -DCAML_NAME_SPACE -DNATIVE_CODE -DTARGET_amd64 -DSYS_linux  -O -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT   -c -o signals.o signals.c
gcc -I../byterun -DCAML_NAME_SPACE -DNATIVE_CODE -DTARGET_amd64 -DSYS_linux  -O -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT   -c -o signals_asm.o signals_asm.c
signals_asm.c: In function 'segv_handler':
signals_asm.c:207: error: 'REG_CR2' undeclared (first use in this function)
signals_asm.c:207: error: (Each undeclared identifier is reported only once
signals_asm.c:207: error: for each function it appears in.)
signals_asm.c:213: error: 'REG_RIP' undeclared (first use in this function)
signals_asm.c:228: error: 'REG_R14' undeclared (first use in this function)
signals_asm.c:229: error: 'REG_R15' undeclared (first use in this function)
make[4]: *** [signals_asm.o] Error 1
make[4]: Leaving directory `/homepages/30/d456759237/htdocs/packages/ocaml-4.02.3/asmrun'
make[3]: *** [makeruntimeopt] Error 2
make[3]: Leaving directory `/homepages/30/d456759237/htdocs/packages/ocaml-4.02.3'
make[2]: *** [opt-core] Error 2
make[2]: Leaving directory `/homepages/30/d456759237/htdocs/packages/ocaml-4.02.3'
make[1]: *** [opt.opt] Error 2
make[1]: Leaving directory `/homepages/30/d456759237/htdocs/packages/ocaml-4.02.3'
make: *** [world.opt] Error 2
(uiserver):u72333:~/packages/ocaml-4.02.3 >
