### ISSUE TITLE
Usage of opam packages with third parties

### ISSUE THREAD

**Issue by fxfactorial** [ocaml/opam#2500]
I have `usbmux`, https://github.com/onlinemediagroup/ocaml-usbmux, and I want to add it to third party packages like `nix`, `homebrew` and `apt-get` (mainly the binary executable) but its not clear to me what the canonical way to do this is. 

I've seen some in opam packages in `nix` but it would be a big hassle for me because of dependencies and whatnot, i.e. creating separate `nix` package for each. 

Any guidance or support from `opam` itself would be amazing.

**Comment by rgrinberg** [comment]
I'd recommend taking a look at https://github.com/ygrek/opam-bundle. I don't know if it addresses your problem directly but it seems to be the simplest way to distribute opam packages outside of opam.

**Comment by fxfactorial** [comment]
@rgrinberg thanks! I will try it out, another nice feature by @ygrek . Would be nice if opam itself provided this functionality.

**Comment by dra27** [comment]
See also #2944, I think?

**Comment by AltGr** [comment]
Not sure the bundler is good for packaging (the bundle includes OCaml and opam source + bootstrap scripts and creates a local opam environment on the target) ; but have a look at https://github.com/timbertson/opam2nix . I don't know if there are similar projects for other package managers
