### ISSUE TITLE
sh: `opam-switch-eval': not a valid identifier

### ISSUE THREAD

**Issue by choeger** [ocaml/opam#2501]
The opam init script opam-init/switch_eval.sh seems not to be POSIX-sh compliant:

sh-4.3$ . opam/opam-init/switch_eval.sh 
sh: `opam-switch-eval': not a valid identifier

**Comment by AltGr** [comment]
To be sure we discuss the same thing, could you include your opam version (or best, `opam config report`), and the switch_eval script ? Thanks !

On my version, there seems to be two issues:
- the `function` keyword is undefined (and unnecessary)
- dashes in the function name are not allowed (but it seems you can define with a different name and then make an alias to keep the legacy name -- not sure it's POSIX, this is with dash)

Does anyone use this feature anyway ? Maybe we should just remove it.

**Comment by dra27** [comment]
This script was removed in 1669739f2e039dfb9ee704a36ff993abff3519af, so presumably this can be closed?
