### ISSUE TITLE
Installing package with the -t flag installs test dependencies of all dependent packages

### ISSUE THREAD

**Issue by seliopou** [ocaml/opam#2506]
To reproduce, run the following command:

``` bash
opam install webmachine --deps-only -t
```

This will produce the following output (given that all of webmachine's non-test dependencies are installed):

```
The following actions will be performed:
  - install   ocaml-data-notation 0.0.11   
  - install   ounit               2.0.0    
  - install   astring             0.8.1    
  - install   ocamlify            0.0.1    
  - install   qcheck              0.4      
  - install   ocamlmod            0.0.8    
  - recompile re                  1.5.0    
  - recompile ppx_deriving        3.3      
  - recompile dispatch            0.3.0    
  - recompile cstruct             1.9.0    
  - recompile stringext           1.4.1    
  - install   oasis               0.4.5    
  - recompile ppx_type_conv       113.33.00
  - install   alcotest            0.4.8    
  - recompile ppx_sexp_conv       113.33.00
  - recompile uri                 1.9.2    
  - recompile ipaddr              2.7.0    
  - recompile conduit             0.11.0   
  - recompile cohttp              0.20.0   
===== 8 to install | 11 to recompile =====
Do you want to continue ? [Y/n] 
```

The only test dependency that webmachine has is oUnit. However it has dependencies that use alcotest and qtest as well.

I expect this command to only install oUnit, but it is installing the test dependencies of webmachine's dependencies as well.

**Comment by seliopou** [comment]
Possibly related to #2494.

**Comment by samoht** [comment]
See #2190

**Comment by AltGr** [comment]
Indeed, that's what `-t` does. More flexibility for tests would be nice...
- separating build and run of tests in opam files (#2494 : the above will not only fetch all test-deps, it will also run all tests of dependent packages)
- asking for specific test-depends
- listing test-dependencies (if there were an appropriate flag, you could do `opam install $(opam list -s --test --required-by webmachine)` as a workaround)

I am not sure about the distinctions between building, installing (?) an running the tests, and how we should modify the corresponding `build-test:` field. There is also, at the moment, a parity with the `build-doc:` field. But there is no blocker for separating at least dependency handling of test-dependencies and test-building.
