### ISSUE TITLE
Allow specifying `env` in packages

### ISSUE THREAD

**Issue by whitequark** [ocaml/opam#2509]
For cross-compilation, I have many environment variables to set:
- `OCAMLFIND_TOOLCHAIN`
- `CFLAGS`, `LDFLAGS`, `CC`, `LD`
- most importantly, `PATH` which has to be extended with the path to the toolchain, since `./configure` scripts do not allow doing something like `PATH+=` and trying to encode the code below so that it would properly extend `PATH` instead of hardcoding `/usr/bin:/bin` using only `sh -c` is an absolute escaping nightmare:

```
opam-version: "1"
maintainer: "whitequark@whitequark.org"
substs: ["libjpeg-sys-android.config"]
build: [
  ["./configure" "--host=%{conf-android:triple}%"
                 "--prefix=%{prefix}%/android-deps/libjpeg"
                 "--disable-shared"
                 "--with-pic"
                 "PATH=%{conf-android:toolchain}%:/usr/bin:/bin"
                 "CFLAGS=%{conf-android:cflags}%"
                 "LDFLAGS=%{conf-android:ldflags}%"]
  ["make" "-j" jobs "PATH=%{conf-android:toolchain}%:/usr/bin:/bin"]
]
install: [
  ["make" "install" "PATH=%{conf-android:toolchain}%:/usr/bin:/bin"]
]
remove:  [["rm" "-rf" "%{prefix}%/android-deps/libjpeg"]]
depends: ["conf-android"]
```

So, how about opam allowing `env:` for packages as well? Doesn't seem hard to me.

**Comment by AltGr** [comment]
It's somehow absent from the documentation, but there is a field `build-env:`, which seems to be what you are asking for -- I don't remember when it was first implemented, but there appears to be [one occurence](https://github.com/ocaml/opam-repository/blob/master/packages/sibylfs-lem/sibylfs-lem.0.4.0/opam#L8) in the official repository.

Additionally, the dev version has a "setenv:" field that you can use for a package to export env variables to dependent packages, and to the user (through `eval $(opam config env)`).  It doesn't work at the moment for variables that are already set by opam, though like `PATH`.

**Comment by whitequark** [comment]
Ah, that's useful. Is `setenv:` transitive?

**Comment by AltGr** [comment]
Yes, it affects all transitive dependents, and the user shell as well: If after a series of actions the opam-environment has changed, opam will prompt to re-run `eval $(opam config env)`.
This also means that independent packages may see the change, on next runs.

Multiple updates to the same variable may not work properly, I still need to test that.
Also, `opam config env -v` allows to track the package of origin of any changes.

**Comment by whitequark** [comment]
Hmmmm, I think `setenv:` is too invasive for my purposes. Explicitly pulling in variables from `conf-*` packages seems just fine.

**Comment by AltGr** [comment]
The original purpose was to allow setting `CAML_LD_LIBRARY_PATH` from compiler packages, like it was done for `.comp` files. It also allowed to remove a hack that had opam set some perl-related env variables just to fix some packages.
