### ISSUE TITLE
opam list -a | grep something truncates at column 80

### ISSUE THREAD

**Issue by manfredlotz** [ocaml/opam#2510]
When running 
opam list -a | grep something
the output get truncated at column 80.

Same for 
   opam list -a > /tmp/o.lst
Then the o.lst has at most 80 columns.

This is Fedora 23, opam 1.2.2

Any idea what is wrong? Thanks.

-- Manfred

**Comment by AltGr** [comment]
opam output wraps long lines to the terminal, and 80 columns otherwise. In recent (dev) versions you can set the environment variable `COLUMNS` to a large value to avoid this.

**Comment by manfredlotz** [comment]
Tested, works with the dev version. 

Why not implementing the other way round (downward compatibility?): default is to get it all, and those who wants to get a line wrapped should set it via the COLUMN variable?

**Comment by AltGr** [comment]
Indeed, thanks for the feedback: I changed the default behaviour to not wrap by default, which should make it easier for scripts (the previous rationale was that if you redirect to a log file, it may be better to have wrapped lines, but I don't think it matters that much).

As long as you run on the terminal, anyway, the detected terminal window width is used.

**Comment by wieczyk** [comment]
Could you release opam with this fix?

This ticket has been closed in 2016, but we have 2018 and I still cannot redirect output (from opam search/list) to file and use editor/page to process output (since it useless due to 80 column truncation).

I have latest opam package from Ubuntu (1.2.2).

**Comment by AltGr** [comment]
You can try 2.0.0~rc, which should be pretty close to the upcoming 2.0.0 version, or wait just a little more.
In the meantime, there is a fine workaround described above.
