### ISSUE TITLE
opam init fails on Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by soapdog** [ocaml/opam#2514]
The new [Bash on Windows] system has a preview available for Windows Insiders. I've been trying to run OCaml + OPAM in it but opam init is failing as can be seen in:

```
root@localhost:~# opam init                                                                                    
[WARNING] Running as root is not recommended                                                                   
Checking for available remotes: rsync and local, git.                                                          
  - you won't be able to use mercurial repositories unless you install the hg command on your system.          
  - you won't be able to use darcs repositories unless you install the darcs command on your system.           


=-=- Fetching repository information =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=                               
Processing: [default: http]mv: cannot move ‘/tmp/opam-14601-c61e7b/urls.txt’ to a subdirectory of itself, ‘/roo
t/.opam/repo/default/urls.txt.1’                                                                               
[ERROR] Initialisation failed                                                                                  
# opam-version 1.2.2                                                                                           
# os           linux                                                                                           
# command      mv /tmp/opam-14601-c61e7b/urls.txt /root/.opam/repo/default/urls.txt.1                          
# path         /tmp/opam-14601-c61e7b                                                                          
# exit-code    1                                                                                               

[ERROR] Command "mv /tmp/opam-14601-c61e7b/urls.txt /root/.opam/repo/default/urls.txt.1" failed:               
# opam-version 1.2.2                                                                                           
# os           linux                                                                                           
# command      mv /tmp/opam-14601-c61e7b/urls.txt /root/.opam/repo/default/urls.txt.1                          
# path         /tmp/opam-14601-c61e7b                                                                          
# exit-code    1                                                                                               

root@localhost:~#                                                                                              

```

If running OCaml and opam on windows 10 becomes simple through the new Bash thing it will be a great step forward for those using that platform.

**Comment by AltGr** [comment]
Thanks for the report! This is an interesting experiment.

From that bit of log, I get more questions than answers though:

1. `mv: cannot move ‘/tmp/opam-14601-c61e7b/urls.txt’ to a subdirectory of itself, ‘/roo
t/.opam/repo/default/urls.txt.1’` ; err, what ? There may be issues with either the `mv` command, or, more likely, how the paths are handled. Or both. But this message makes no sense...

2. also, it appears that opam failed to capture the output of the `mv` command, which is another puzzlement (we use OCaml's `Unix.create_process` and specify files for standard output descriptors).

It would be too easy to jump to the conclusion that Windows bash is completely broken, but these errors are surprising.
I am wondering also how OCaml reports this system (it knows about `Windows` and `Cygwin`, and adapts some stuff like EOLs and path separators accordingly) ; the Windows binary we provide may not be fit for this unexpected situation at the moment.

**Comment by soapdog** [comment]
Hi @AltGr,

I am more than happy to try to help debug this one, so if there is any experiment that you'd like me to run that could help shed some light on the bug please let me know.

The "Bash On Ubuntu On Windows" (horrible name, I know) is basically a windows subsystem that translate Linux Kernel syscalls into NT syscalls. After that, they have the Ubuntu 14.04 root filesystem and userland running. Normal ELF binaries, normal "linux userland". Still tty and some /dev stuff are not yet implemented. This is an insider preview alpha version, so I expect it to be buggy but it is better to start debugging it now so that once it is ready, opam and ocaml can take advantage of it. Still, I believe that when it is ready, opam and ocaml will just think it is a normal linux...

**Comment by Tatskaari** [comment]
Hi guys,

Looks like a known issue: https://github.com/Microsoft/BashOnWindows/issues/104

There's a bug when moving from a temp directory to a non-temp directory and it has been fixed internally. Should make its way to us soon.

**Comment by AltGr** [comment]
Nice to hear, thanks
@soapdog, thanks a lot for proposing to help test on this; I'd be happy to hear how far you can get once the /tmp issue is fixed.

**Comment by soapdog** [comment]
waiting for that fix to hit the insiders build. Once it does, I will test it and report back here. Thanks for all the help.

**Comment by Tatskaari** [comment]
Hi, just got an update and it does indeed fix this issue.

**Comment by soapdog** [comment]
Thanks for the feedback, do you know if that fix is out yet?

**Comment by sishtiaq** [comment]
It should be in Build 14355. 
I have opam working inside BashOnWindows. I have other problems further down the pipeline, but opam seems ok.

**Comment by dannywillems** [comment]
*opam init* is also working for me.

**Comment by echuber2** [comment]
Which versions of Ocaml are available on Bash on Win10 right now? It seems like 4.03.0 (proper) is not available when I do "opam switch". Is the repository maintaining a separate list for Windows clients?

**Comment by dannywillems** [comment]
@echuber2 any version works for me.

**Comment by dra27** [comment]
Are there any active opam issues with this at the moment, or can this issue be closed?

**Comment by sishtiaq** [comment]
Can be closed.
