### ISSUE TITLE
Allow to install files in /var/lib in OPAM install files

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#2517]
via a `var-lib:` section.

**Comment by dbuenzli** [comment]
In fact it should be `var_lib` since we already have `share_root`.

**Comment by dra27** [comment]
@AltGr - this is quite a straightforward change, what's your opinion on it?

**Comment by dbuenzli** [comment]
Can't remember why I wanted that. No-one else seems to want that, let's close.
