### ISSUE TITLE
Packages are removed when build dependencies are removed

### ISSUE THREAD

**Issue by yallop** [ocaml/opam#2518]
Here's an example:

```
$ opam --version
1.3.0~dev3
$ opam show --raw ppx_bitstring
             package: ppx_bitstring
   installed-version: 1.0.0 [4.02.3]
   available-version: 1.0.0
----------------------------------------------------------------------
opam-version: "1.2"
name: "ppx_bitstring"
version: "1.0.0"
descr: """
PPX implementation of the bitstring (https://github.com/mor1/ocaml-bitstring) extension.
"""
maintainer: "Xavier Guérin <github@applepine.org>"
authors: "Xavier Guérin <github@applepine.org>"
license: "BSD"
homepage: "https://github.com/xguerin/ppx_bitstring"
bug-reports: "https://github.com/xguerin/ppx_bitstring/issues"
depends: [
  "bitstring" {build}
  "core" {build}
  "ocamlbuild" {build}
  "ocamlfind" {build}
  "ppx_tools" {build}
]
build: make
install: [make "PREFIX=%{prefix}%" "install"]
remove: ["ocamlfind" "remove" "ppx_bitstring"]
dev-repo: "https://github.com/xguerin/ppx_bitstring.git"
url {
  src: "http://github.com/xguerin/ppx_bitstring/archive/v1.0.0.tar.gz"
  checksum: "4b18a94e5179ac503c2ee6d48b9d62d3"
}
$ opam remove core
The following actions will be performed:
  ⊘  remove ppx_bitstring 1.0.0                               [uses core]
  ⊘  remove core          113.00.00
===== ⊘  2 =====
Do you want to continue ? [Y/n] 
```

If `core` is only a build dependency of `ppx_bitstring` then it should be possible to remove `core` and leave `ppx_bitstring` installed.

**Comment by dbuenzli** [comment]
We all seem to be confused about this but there's a reason... see Louis answer in https://github.com/ocaml/opam/issues/2494

**Comment by yallop** [comment]
Thanks, @dbuenzli.  I hadn't seen that issue.

@AltGr says:

> Because a given state could be unreachable in a single step (or even in any given number thereof). Imagine that `a` build-depends on `b`, and `c` conflicts with `b`. You could have both `a` and `c` installed, but they're not installable in a single step, you would need to first install `b` and `a`, then remove `b`, then install `c`.

Doesn't the behaviour of build dependencies w.r.t. upgrade have a similar problem?  Suppose that `a` build-depends on `b.1.0` and conflicts with `b.2.0` (i.e. has `conflicts: [ "b" {build & = "2.0"}]`).  Then you can have both `a` and `b.2.0` installed, but they're not installable in a single step, just as in the example above.

**Comment by AltGr** [comment]
@yallop: No, in that case, you also won't be able to upgrade `b`. Also, build-conflicts are not allowed, so you'd write the above through depends: `depends: [ "b" {build & != "2.0"} ]`
