### ISSUE TITLE
Next: opam pin requires "name" fields

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2519]
On the `next` branch:

```
% opam pin add --no-action --dev js_of_ocaml       
[js_of_ocaml] git+https://github.com/ocsigen/js_of_ocaml.git updated
Fatal error:
Input error:
Field 'name:' is required
```

`name` was not required before, and it's already provided through the CLI. If you break all the `opam` files in user's repositories, migration to 2.0 is going to be a bit wild. :D 

(meta: do you want the next-related issues as separate issues or in the big PR ?)

**Comment by AltGr** [comment]
Indeed, that's a bug, just fixed. Thanks for reporting!

(reporting issues here is fine since I'll merge the PR shortly anyway)

**Comment by AltGr** [comment]
(thanks for trying the `next` branch btw!)
