### ISSUE TITLE
Next: `opam pin list` buggy

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2521]
```
% opam pin
Fatal error:
Invalid_argument("String.sub / Bytes.sub")
```

**Comment by Drup** [comment]
Same error with `opam switch list`.

**Comment by AltGr** [comment]
Arg, sorry, I stopped in the middle and forgot to push the fix :/
Now done; thanks @OCamlPro-Henry for providing a fix while I was away

**Comment by Drup** [comment]
It works! But I think something else is broken now: https://github.com/ocaml/opam/issues/2533
