### ISSUE TITLE
next: `opam init` fails on FreeBSD

### ISSUE THREAD

**Issue by seliopou** [ocaml/opam#2525]
Here's the output while attempting to setup the system switch (the output files are empty):

``` bash

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
-> installed base-bigarray.base
-> installed base-threads.base
-> installed base-unix.base
[ERROR] The compilation of ocaml failed at "./gen.sh".

#=== ERROR while compiling ocaml.system =======================================#
# opam-version 2.0~alpha (7cf601e4d403df78abc945853399e4eda8aa48cf)
# os           freebsd
# command      ./gen.sh
# path         /home/vagrant/.opam/system/.opam-switch/build/ocaml.system
# exit-code    127
# env-file     /home/vagrant/.opam/system/.opam-switch/build/ocaml.system/ocaml-61997-d474c2.env
# stdout-file  /home/vagrant/.opam/system/.opam-switch/build/ocaml.system/ocaml-61997-d474c2.out
# stderr-file  /home/vagrant/.opam/system/.opam-switch/build/ocaml.system/ocaml-61997-d474c2.err
```

I believe the immediate issue is that the location of `bash` is hard-coded in the `gen.sh` script. Using `#!/usr/bin/env bash` should work around this.

Another portability issue is lurking behind that one. `gen.sh` uses `md5sum`, which is not installed on FreeBSD systems. In its place is `md5`.

**Comment by hannesm** [comment]
maybe `gen.sh` can actually be written in platform-independent `sh`, rather than in `bash`? :)

**Comment by seliopou** [comment]
Where is `gen.sh` coming from, anyways? There's a copy of it in the `tests/` directory, but changing that doesn't seem to change what's used during installation.

**Comment by OCamlPro-Henry** [comment]
I just found it in the `ocaml.system` package in the `next` branch of `opam-repository`:

https://github.com/ocaml/opam-repository/blob/next/packages/ocaml/ocaml.system/files/gen.sh

**Comment by seliopou** [comment]
@OCamlPro-Henry thanks! Still not used to the new compilers-as-packages system and didn't think to look there.

**Comment by AltGr** [comment]
Yes, the "system" compiler is now a normal package that was added to the "next" repository (rather than dynamically generated using specific opam built-ins).

Writing it in bash was a quick filler, there is no reason not to actually write it in plain ocaml.
