### ISSUE TITLE
Absence of a system compiler should not be complained about unless required

### ISSUE THREAD

**Issue by mshinwell** [ocaml/opam#2527]
I don't think the message complaining that a system compiler couldn't be found should be emitted unless OPAM is actually going to try to invoke that compiler.  In some environments there may be no OCaml compiler on the path for good reason.

**Comment by AltGr** [comment]
Can you be more explicit about what command triggered what precise message ?
Opam tries to bind a system compiler by default on `opam init`, unless a specific compiler has been specified. Note that 2.0~alpha allows switchless opamroots, which makes it easier to handle the case where you don't have  a system compiler and didn't specify another one.

I've retained the default behaviour for compatibility for now, though: you need to specify `opam init --bare` if you don't want a (system) switch to be created.
