### ISSUE TITLE
Bad error message for "opam pin add"

### ISSUE THREAD

**Issue by mshinwell** [ocaml/opam#2528]
The following message, which happened when I tried to pin a package that probably has unsatisfiable version constraints, doesn't help me understand at all what is going wrong.  (It also doesn't seem to make sense...)

```
$ opam pin add cohttp /mnt/local/sda1/mshinwell/ocaml-cohttp
cohttp is now path-pinned to /mnt/local/sda1/mshinwell/ocaml-cohttp

[cohttp] /mnt/local/sda1/mshinwell/ocaml-cohttp/ synchronized
[cohttp] Installing new package description from /mnt/local/sda1/mshinwell/ocaml-cohttp

cohttp needs to be installed.
Your request can't be satisfied:
  - cohttp.0.20.2 is not available because the package is pinned to /mnt/local/sda1/mshinwell/ocaml-cohttp, version 0.20.2.
```

**Comment by AltGr** [comment]
Hm, this is the fallback message for pinned packages when no better reason is found, and should normally happen when you require a version different from the pinning version. Probably another consequence of the internal solver reporting incorrect conflicts ?
