### ISSUE TITLE
option to always do 'opam depext x' before doing opam install x

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#2530]
Hello,
When installing something with many dependencies, such an option might be handy.

**Comment by dsheets** [comment]
`opam depext -i x`

**Comment by UnixJunkie** [comment]
Would this install the depexts of all the dependencies too?

**Comment by AltGr** [comment]
@UnixJunkie yes;
the mid-term goal is to integrate depext within opam, with an option to always pull external dependencies (and also routinely check that they haven't been removed or updated...) ; depext as a plugin fills the gap and allows to check and validate integration on different OSes until then.
