### ISSUE TITLE
Next: opam switch remove do not update `.opam/config`

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2538]
I was removing old switches that were converted. not sure if that plays a role.

**Comment by AltGr** [comment]
hm, can't reproduce, what versions are you on ?
Thanks!

**Comment by Drup** [comment]
`opam-version    2.0~alpha (abbc828de87d32c774f1e30bf830144b44a06048)` (last commit on next)

It may be a corner case due to my oh-so-slightly messed up `.opam`. :p

**Comment by AltGr** [comment]
Ah, I found the bug by chance! It happened when you removed several switches at once (the updated state wasn't properly returned). I have a pending patch.

Thanks for reporting!

**Comment by Drup** [comment]
> It happened when you removed several switches at once

Ah, indeed! Thanks.
