### ISSUE TITLE
`opam --show-solver` to easily know which solver is used by default

### ISSUE THREAD

**Issue by gasche** [ocaml/opam#2540]
When helping beginners solve opam issues, I would really like to be able to know which solver they are using. For this it would suffice to have a `opam --show-solver` command that indicates which solver will be used by default.

**Comment by dbuenzli** [comment]
`opam config report` has the info and more that you'll also likely need to help beginners.

**Comment by gasche** [comment]
I guess this is the `external-solver` line you're thinking of. What does it show when opam would use the internal solver?

**Comment by dbuenzli** [comment]
`# external-solver no`

**Comment by AltGr** [comment]
Yes, I think `config report` is what you're looking for!

**Comment by gasche** [comment]
Indeed, thanks. I'll try to think of adding a line about that in the documentation.
