### ISSUE TITLE
Race condition on SIGINT

### ISSUE THREAD

**Issue by whitequark** [ocaml/opam#2542]
![2171](https://cloud.githubusercontent.com/assets/54771/14986828/f5623e16-113c-11e6-83d1-917bcd71f5de.png)

**Comment by AltGr** [comment]
Hm, funny, I had never seen that one. Likely a missing flush to stderr -- opam is single process, single thread and all the messages are printed from the opam code. In this case (single process and `-v`) though, output is synched every second through `alarm()`, so maybe the alarm somehow failed to be cancelled, which would be much worse.

I'll have a look, thanks for reporting!

**Comment by AltGr** [comment]
Must be here: https://github.com/ocaml/opam/blob/0e119a6291eeb74c2fd46ffcd50f9b8a25c58622/src/core/opamProcess.ml#L388

We don't actually catch SIGINT if it happens in OCaml code (if it's in sub-process code, which is most often the case, we get an EINTR, which is correctly handled), and don't clean the alarm accordingly.
