### ISSUE TITLE
camlp5 package cannot be installed with opam switch 4.02.0

### ISSUE THREAD

**Issue by matej-kosik** [ocaml/opam#2558]
Hi,

When I install opam 4.02.0 and when I try to compile camlp5, I am getting this error:
```
ocamlc.opt -warn-error A -I ../main -I ../boot -I ../ocaml_stuff/4.02.0/utils -I ../ocaml_stuff/4.02.0/parsing -I /home/me/.opam/4.02.0/lib/ocaml/compiler-libs -c -impl camlp5_top.ppo
File "camlp5_top.ml", line 1:
Error: The files ../ocaml_stuff/4.02.0/parsing/parsetree.cmi
       and /home/me/.opam/4.02.0/lib/ocaml/compiler-libs/toploop.cmi
       make inconsistent assumptions over interface Location
../config/Makefile:20: recipe for target 'camlp5_top.cmo' failed
```
I am not sure exactly why.

When I try install opam 4.02.3, compilation of camlp5 succeeds. I do not understand exactly what is happening but something (maybe opam, maybe camlp5, I do not know) maybe needs to be fixed.

**Comment by AltGr** [comment]
You'd probably have more luck reporting to [opam-repository](https://github.com/ocaml/opam-repository/issues), as this seems to be a packaging issue. Thanks!

**Comment by matej-kosik** [comment]
Ok. I'll repost it there. Thanks.
