### ISSUE TITLE
opam FAQ, macports, and virtualenv competing for environment variables.

### ISSUE THREAD

**Issue by dbrumley** [ocaml/opam#2566]
This post is to describe the confluence of three factors that caused me to loose time:
  1) macports writes to the `.profile` to prepend the macports path to the `PATH` environment variable, e.g., on login `export PATH=/opt/local/bin:${PATH}`.
  2) `elpy` and virtual environments want to prepend the virtualenv path to `PATH`, e.g., `export PATH=~/.venv/bin:${PATH}`.
 3) The documentation [here](https://github.com/ocaml/opam/wiki/Setup-Emacs.app-on-macosx-for-opam-usage) for OSX makes it so the shell is a login shell, thus `.bash_profile` is read for `M-x compile`.   

I had followed 3) above in my emacs, and spent some time debugging why elpy virtualenv (`pyvenv-activate` in particular) did not appear to work for test cases. The reason is the test cases use `M-x compile` to run the test suite.  This will, with (3) above, run the login shell, which sources `.bash_profile`, prepend macports path (`/opt/local/bin` here), and break virtualenv by changing python to point to system python instead of virtualenv python.

I don't have a good solution at this time, and would welcome suggestions.  It seems, on the surface, that the emacs setup should add environment variables whenever `merlin`/`tuareg` becomes active.  

Reference:
- https://github.com/jorgenschaefer/elpy/issues/538 is what tipped me off when virtualenv was no longer working in elpy.

**Comment by AltGr** [comment]
Thanks for reporting. An alternative to 3) could indeed be to set the [opam-update-env](http://opam.ocaml.org/doc/Tricks.html#UpdateOPAMenvironmentwithinemacs) function to `tuareg-mode-hook`.

If you use [opam-user-setup](http://opam.ocaml.org/packages/user-setup/user-setup.0.5/), emacs should load the proper opam environment at startup without relying on the 3) hack and requiring a login shell.

**Comment by AltGr** [comment]
This might well be related to https://github.com/ocaml/tuareg/issues/94 as well.
Closing as it's not clear to me what could be done within opam to mitigate this issue.
Thanks for reporting.
