### ISSUE TITLE
opam wants to install github&cohttp whatever the operation requested

### ISSUE THREAD

**Issue by Armael** [ocaml/opam#2569]
I observed this behavior with an opam-git from a few months ago (1.2.something); I upgraded to latest opam-git, and the issue still occurs.  
Whatever the operation I request, opam additionnaly decides to install github and cohttp. (I can still reproduce the issues after a couple of `opam update && opam upgrade` since `cohttp` doesn't seem to compile here)

For example, if I ask for the removal of `gg` (or any other installed package), I get the following log: https://gist.github.com/Armael/52cce8812f55c149bd0493de2daf70f4

Same issue happens when trying to install a package, upgrade packages, etc.

```
# OPAM config report
# opam-version    2.0~alpha (ce8605e0572335beb7f9ae04713c9cc8048cf707) 
# self-upgrade    no
# os              linux
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            1
# repositories    1* (http), 1 (version-controlled)
# pinned          3 (git), 1 (rsync)
# current-switch  4.02.3
```

**Comment by AltGr** [comment]
Apologies for the lack of followup. Opam will always attempt to maintain consistency of the installed package set, in particular, maintaining all dependencies of installed packages installed. This happens whatever the action you are asking for, hence the surprising results you are getting: it seems you somehow got in a situation where `github` and `cohttp` got uninstalled, while packages depending on them are still present (e.g. `publish`, that was installed, according to your logs, depends on `github`). Opam will implicitely "fix" that, and prefer a solution that includes the installation of the missing packages over a solution that removes the dependent packages (at least with the [default criteria](http://opam.ocaml.org/doc/Specifying_Solver_Preferences.html)).

It would sure be nice if opam printed the reasons for these actions, though, I will see if that can be done.
