### ISSUE TITLE
opam install ocamlbuild --root failure

### ISSUE THREAD

**Issue by trefis** [ocaml/opam#2578]
The failure:

```
% opam install -y ocamlbuild --solver "/home/trefis/.local/bin/aspcud" --root "/tmp/test-opam/opam_root/" --switch "4.03.0+j2-cent6_20160504_150130BST"
The following actions will be performed:
  ∗  install ocamlbuild 0.9.2

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of ocamlbuild failed at "make check-if-preinstalled all opam-install".
[WARNING] Directory /tmp/test-opam/opam_root/4.03.0+j2-cent6_20160504_150130BST/lib/ocamlbuild is not empty, not removing

#=== ERROR while installing ocamlbuild.0.9.2 ==================================#
# opam-version 1.2.1
# os           linux
# command      make check-if-preinstalled all opam-install
# path         /tmp/test-opam/opam_root/4.03.0+j2-cent6_20160504_150130BST/build/ocamlbuild.0.9.2
# compiler     4.03.0+j2-cent6_20160504_150130BST
# exit-code    2
# env-file     .../ocamlbuild-18430-6d07ae.env
# stdout-file  .../ocamlbuild-18430-6d07ae.out
# stderr-file  .../ocamlbuild-18430-6d07ae.err
### stdout ###
# if test -d /home/trefis/.opam/4.02.3/lib/ocaml/ocamlbuild; then\
#         >&2 echo "ERROR: Preinstalled ocamlbuild detected at"\
#              "/home/trefis/.opam/4.02.3/lib/ocaml/ocamlbuild";\
#         >&2 echo "Installation aborted; if you want to bypass this"\
#               "safety check, pass CHECK_IF_PREINSTALLED=false to make";\
#         exit 2;\
#       fi
### stderr ###
# ERROR: Preinstalled ocamlbuild detected at /home/trefis/.opam/4.02.3/lib/ocaml/ocamlbuild
# Installation aborted; if you want to bypass this safety check, pass CHECK_IF_PREINSTALLED=false to make
# make: *** [check-if-preinstalled] Error 2
```

Not that this also happens without the --switch (i.e. after a `opam config env --root ...`).
ocamlbuild ( @gasche ) might be partially to blame here, I don't know.

**Comment by trefis** [comment]
This looks wrong / to be the source of the problem:

```
% cat /tmp/test-opam/opam_root/4.03.0+j2-cent6_20160504_150130BST/build/ocamlbuild.0.9.2/Makefile.config
# This file was generated from configure.make

OCAML_PREFIX=/home/trefis/.opam/4.02.3
OCAML_BINDIR=/home/trefis/.opam/4.02.3/bin
OCAML_LIBDIR=/home/trefis/.opam/4.02.3/lib/ocaml

EXT_OBJ=.o
EXT_ASM=.s
EXT_LIB=.a
EXT_DLL=.so
EXE=

OCAML_NATIVE=false
OCAML_NATIVE_TOOLS=false
NATDYNLINK=true
SUPPORT_SHARED_LIBRARIES=true

PREFIX=/tmp/test-opam/opam_root/4.03.0+j2-cent6_20160504_150130BST
BINDIR=/tmp/test-opam/opam_root/4.03.0+j2-cent6_20160504_150130BST/bin
LIBDIR=/tmp/test-opam/opam_root/4.03.0+j2-cent6_20160504_150130BST/lib
```

**Comment by trefis** [comment]
OK understood: `opam config env` adds `/tmp/test-opam/opam_root/4.03.0+j2-cent6_20160504_150130BST/bin` to my path. But that directory contains nothing (the compiler is "preinstalled").
ocamlbuild's configure script calls `ocamlc -where`, which uses the `ocamlc` in my path, which doesn't match the desired opam switch.

**Comment by gasche** [comment]
See ocamlbuild's configuration logic in [configure.make](https://github.com/ocaml/ocamlbuild/blob/28758bc/configure.make). While we use `ocamlc -where` to find the compiler's `Makefile.config` to include, ocamlbuild's own configuration variable are (1) settable by the installer if need me (you can override `OCAMLBUILD_PREFIX` for example) and (2) use a cascade of tests with `opam` information chosen first -- this is why `PREFIX, BINDIR, LIBDIR` variables at the end of your script are correctly set, even though the `OCAML_...` refer to the old switch.

I guess that I could also use a cascade with `opam config var prefix` first to set the `OCAMLBUILD_PREFIX` variable by default. Could you confirm that running the installer with the environment variable `OCAMLBUILD_PREFIX=$(opam config var prefix)` explicitly set works on your system?

I would like to understand your setting a bit better, though. You say that the compiler is "preinstalled", but where does it live? Why does `ocamlc -where` not return the path of this preinstalled compiler (is it not in the PATH?) instead of some other compiler on your system?

**Comment by gasche** [comment]
Thomas remarked that there are two different place where I rely on `ocamlc -where`, and both are problematic here: the path chosen to get the `Makefile.config`, *and* the [preinstalled ocamlbuild test](https://github.com/ocaml/ocamlbuild/blob/28758bc02f82f23d2b2646e746855536deca8a89/Makefile#L333) in the `Makefile` proper. We may have to fix both, or maybe use for the second test a `configure.make`-set variable to benefit from the same cascading logic, if any.

**Comment by trefis** [comment]
I don't think setting `OCAMLBUILD_PREFIX` will help my case (I do not understand how it is related to the check, but that's another problem) since the check does also use `ocamlc -where`, cf. [configure.make](https://github.com/ocaml/ocamlbuild/blob/28758bc02f82f23d2b2646e746855536deca8a89/Makefile#L333).

As for my setup: I have a bunch of compilers installed in say `/usr/local/ocaml/` (i.e. I have a bunch of subdirs in there, on per compiler version). Only one of them is in my `PATH` at any given time.
My opam compiler description file just says: `preinstalled: true`.
The problem here is that indeed the `ocamlc` in my `PATH` is not the one corresponding to my switch, the reason for that being (as said in my previous message) that opam adds an empty directory to the `PATH`.
I guess it should either add the directory of the preinstalled compiler to the path or "just link things" into its switch subdirectory.

**Comment by gasche** [comment]
But how would `opam` know which preinstalled compiler it should activate at switch time? My understanding of `preinstalled` is that opam then uses "whatever is in the path" without handling the path by itself at installation time; therefore, I would not expect it to be handling the path either at switch time. If you use your own path-handling logic at the time where you setup the switch, shouldn't you use the same one when switching back?

**Comment by trefis** [comment]
> But how would opam know which preinstalled compiler it should activate at switch time? My understanding of preinstalled is that opam then uses "whatever is in the path" without handling the path by itself at installation time

Oh, that wasn't my intuition.
It makes sense actually considering the only path written in the compiler description is the one to add to CAML_LD_LIBRARY_PATH (I was actually expecting some magic based on that).

Thanks.

Note: I had also tried setting the PATH from the compiler description, but that just appears to be ignored. Might be a nice feature to add.

**Comment by gasche** [comment]
@AltGr could you maybe confirm/explain the intended semantics of `preinstalled` install in terms of PATH handling?

**Comment by jparsert** [comment]
I have the same issue. Opam refers to an "installation" of ocamlbuild in /usr/lib... which is not accessible to me. Any way around this?

**Comment by gasche** [comment]
I don't know how you are installing ocamlbuild and what is the environment around it, so it is hard to tell. The ocamlbuild installed in opam works well for switches such that the OCaml version in the path, at the time of installing ocamlbuild, is the same as the switch version. As far as I know, this assumption should essentially always be true, unless there is a problem in your environment.

**Comment by jparsert** [comment]
I mean, running opam install ocamlbuild produces the same error as this post. Namely, `Preinstalled ocamlbuild detected at /usr/lib64/ocaml/ocamlbuild`. But I do not have executable/write access to this directory, so I cannot remove/uninstall or run this ocamlbuild located in /usr/lib64...

**Comment by gasche** [comment]
What is the version of `ocamlc` in your PATH (in the opam environment)? You should not see this failure if it was a version installed in the opam switch that you are using.
