### ISSUE TITLE
Replace absolute path of OPAMROOT in config files by a variable

### ISSUE THREAD

**Issue by scemama** [ocaml/opam#2583]
(feature) :tropical_drink: 

Hi,
When I install using `OPAMROOT=/path/to/opam`, this absolute path is written some installed files (for example `4.02.1/config/global-config.config` ,`opam-init/init.sh`, `4.02.1/config/global-config.config`, `4.02.1/lib/findlib.conf`, ...).
So if I decide to move the `/path/to/opam`, I have to change manually all the files.

Would it be possible to defne only once the location of the `$OPAMROOT` and use the `OPAMROOT` variable in all the files?
Thanks,
Anthony

**Comment by AltGr** [comment]
That could be done in Opam indeed, but note that, in the case of OCaml, you will run into further issues down the line as the compilers and tools don't support being relocated very well at the moment.

In opam, this would need a specific handling for the default opam root `~/.opam` (absolute paths are needed as OPAMROOT may not be set) and an explicitely defined, different root. This also means that you might run into problems trying to set `OPAMROOT=~some-other-user/.opam`.

These difficulties put aside, yes, allowing relocatable roots would be nice for a variety of uses, and we'll try to improve on that front. Thanks for the suggestion!

**Comment by scemama** [comment]
To handle the `~/.opam` problem, a workaround would be to set the `OPAMROOT` environment variable to `~/.opam` if it is not defined whenever opam starts (using `Unix.putenv` for instance).
Thanks for the answer!

**Comment by AltGr** [comment]
The config files of switches have been modified to not hardcode paths, allowing `mv` on the switch directory to work _as far as opam is concerned_. A number of specific packages still have hardcoded paths, though.

**Comment by scemama** [comment]
Thank you very much!
