### ISSUE TITLE
Default config causes `opam switch` to complain about environment being out of sync

### ISSUE THREAD

**Issue by cpitclaudel** [ocaml/opam#2584]
I ran a standard `opam init`, then switched to OCaml 4.02.3. However, running a plain `opam switch` complains:

```
$ opam switch > /dev/null
[WARNING] The environment is not in sync with the current switch.
          You should run: eval `opam config env`
```

The only thing that `opam config env` does is reorganize folders in my `MANPATH`. It seems that the init bit that `opam init` added to my `.profile` appends to the end of the manpath, but `opam config env appends` to the front of it?

Here's a full transcript:

```
$ opam config report
# OPAM config report
# opam-version    1.2.2 
# self-upgrade    no
# os              linux
# external-solver no
# criteria        -removed,-notuptodate,-changed
# jobs            4
# repositories    1* (http)
# pinned          0
# current-switch  4.02.3
# last-update     2016-05-12 21:20

$ opam switch > /dev/null
[WARNING] The environment is not in sync with the current switch.
          You should run: eval `opam config env`

$ (echo $PATH; echo $OCAML_TOPLEVEL_PATH; echo $PERL5LIB; echo $MANPATH; echo $CAML_LD_LIBRARY_PATH) | tee old-vars
/home/clement/.opam/4.02.3/bin:/home/clement/.bin:/home/clement/scripts:/home/clement/.cask/bin:/home/clement/.cabal/bin:/opt/OpenPrinting-Gutenprint/sbin:/opt/OpenPrinting-Gutenprint/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
/home/clement/.opam/4.02.3/lib/toplevel
/home/clement/.opam/4.02.3/lib/perl5:
/opt/OpenPrinting-Gutenprint/man:/opt/OpenPrinting-Gutenprint/man:/usr/local/man:/usr/local/share/man:/usr/share/man:/home/clement/.opam/4.02.3/man
/home/clement/.opam/4.02.3/lib/stublibs

$ eval `opam config env`

$ (echo $PATH; echo $OCAML_TOPLEVEL_PATH; echo $PERL5LIB; echo $MANPATH; echo $CAML_LD_LIBRARY_PATH) | tee new-vars
/home/clement/.opam/4.02.3/bin:/home/clement/.bin:/home/clement/scripts:/home/clement/.cask/bin:/home/clement/.cabal/bin:/opt/OpenPrinting-Gutenprint/sbin:/opt/OpenPrinting-Gutenprint/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
/home/clement/.opam/4.02.3/lib/toplevel
/home/clement/.opam/4.02.3/lib/perl5:
/home/clement/.opam/4.02.3/man:/opt/OpenPrinting-Gutenprint/man:/opt/OpenPrinting-Gutenprint/man:/usr/local/man:/usr/local/share/man:/usr/share/man
/home/clement/.opam/4.02.3/lib/stublibs
```

```diff
$ diff -u old-vars new-vars
--- old-vars	2016-06-15 22:20:31.741173184 -0400
+++ new-vars	2016-06-15 22:20:49.561172420 -0400
@@ -1,5 +1,5 @@
 /home/clement/.opam/4.02.3/bin:/home/clement/.bin:/home/clement/scripts:/home/clement/.cask/bin:/home/clement/.cabal/bin:/opt/OpenPrinting-Gutenprint/sbin:/opt/OpenPrinting-Gutenprint/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
 /home/clement/.opam/4.02.3/lib/toplevel
 /home/clement/.opam/4.02.3/lib/perl5:
-/opt/OpenPrinting-Gutenprint/man:/opt/OpenPrinting-Gutenprint/man:/usr/local/man:/usr/local/share/man:/usr/share/man:/home/clement/.opam/4.02.3/man
+/home/clement/.opam/4.02.3/man:/opt/OpenPrinting-Gutenprint/man:/opt/OpenPrinting-Gutenprint/man:/usr/local/man:/usr/local/share/man:/usr/share/man
 /home/clement/.opam/4.02.3/lib/stublibs
```

**Comment by AltGr** [comment]
What probably happens is that you have shell init files that get loaded after `.profile`, and that further update your `MANPATH`, prepending the Gutenprint parts after opam initialised it (by loading e.g. `~/.opam/opam-init.variables.sh`). Then, when opam runs, it's not so clever as to discover that the modifications to that variable are harmless (for `PATH`, they may not be), and nags you again. Can you check if this is the case ?

Thanks for reporting.

**Comment by cpitclaudel** [comment]
Maybe; though I find it surprising that the value that I get for `MANPATH` before running `eval $(opam config env)` has the opam folder at the very end, after `/usr/local/man` etc.

```
$ echo $MANPATH
/opt/OpenPrinting-Gutenprint/man:/opt/OpenPrinting-Gutenprint/man:/usr/local/man:/usr/local/share/man:/usr/share/man:/home/clement/.opam/4.02.3/man

$ eval `opam config env`

$ echo $MANPATH
/home/clement/.opam/4.02.3/man:/opt/OpenPrinting-Gutenprint/man:/opt/OpenPrinting-Gutenprint/man:/usr/local/man:/usr/local/share/man:/usr/share/man
```

Here is another example that suggests that something is wrong with opam:

```
$ MANPATH=test

$ . /home/clement/.opam/opam-init/init.sh

$ echo $MANPATH
test:/home/clement/.opam/4.02.3/man

$ MANPATH=test

$ echo $MANPATH
test

$ . /home/clement/.opam/opam-init/init.sh

$ echo $MANPATH
test:/home/clement/.opam/4.02.3/man

$ . /home/clement/.opam/opam-init/init.sh

$ echo $MANPATH
test:/home/clement/.opam/4.02.3/man:/home/clement/.opam/4.02.3/man

$ . /home/clement/.opam/opam-init/init.sh

$ echo $MANPATH
test:/home/clement/.opam/4.02.3/man:/home/clement/.opam/4.02.3/man:/home/clement/.opam/4.02.3/man

$ eval `opam config env`

$ echo $MANPATH
/home/clement/.opam/4.02.3/man:test
```

Looks like `init.sh` (repeatedly) appends to the path but `opam config env` prepends to it.

**Comment by AltGr** [comment]
Indeed, `MANPATH` is hard-coded to use `=:` ([append with default](http://opam.ocaml.org/doc/Manual.html#Environmentupdates)), but opam 1.2.2 has a bug and doesn't handle that operator correctly in the dynamic case. So `variables.sh` is actually correct here, and `opam config env` should append rather than prepend.

The fact that `init.sh`, if sourced several times, repeadedly appends is normal: it is a trivial shell script that just does `MANPATH="$MANPATH:new_elt"`. It should be sourced just once at shell load time (where it makes sense to be as static as possible), and further updates done through `opam config env`, which is supposed to be idempotent.

Thanks for reporting: you were right to find something suspicious in there!
I am wondering if we could get rid of the `The environment is not in sync` when the variable has furher been updated, but I am afraid of problems e.g. in case the init scripts do something like `PATH=/usr/local/bin:$PATH` after the `init.sh` load, and `/usr/local` contains an instance of OCaml. There is a related `--inplace_path` argument, but only for the `PATH` variable.

**Comment by cpitclaudel** [comment]
Thanks for the clarification :)

**Comment by AltGr** [comment]
Closing, since this is has been fixed on master. Thanks!
