### ISSUE TITLE
opam init -y does not modify  ~/.bash_profile

### ISSUE THREAD

**Issue by MSoegtropIMC** [ocaml/opam#2592]
Dear Opam Team,

opam init -y

does not answer the question:

Do you want OPAM to modify ~/.bash_profile and ~/.ocamlinit?
(default is 'no', use 'f' to name a file other than ~/.bash_profile)
    [N/y/f] 

with yes. Or bash_profile is not modified for another reason. This is unexpected and inconvenient for running opam init from scripts.

Best regards,

Michael

**Comment by AltGr** [comment]
Ah, indeed, this does not follow the documentation for `-y` ; the idea was that changing your init scripts is never something that you will want done too eagerly. So for this specific question, you have `--no-setup` and `--auto-setup`.

That's no excuse for misleading documentation, though, esp. as `--yes` is advertised as "Disabl[ing] interactive mode". Thanks for reporting.

**Comment by AltGr** [comment]
The documentation has been tweaked as to be correct for that case.
