### ISSUE TITLE
Conflicting versions error message should mention incompatibilities with current OCaml version

### ISSUE THREAD

**Issue by cpitclaudel** [ocaml/opam#2595]
Running `opam install alcotest mirage-flow mirage-vnetif pcap-format` OCaml 4.03.0 yields the message below:

```
$ opam install alcotest mirage-flow mirage-vnetif pcap-format
The following dependencies couldn't be met:
  - pcap-format -> cstruct (>= 0.5.0 & < 0.6.0 | <= 1.9.0)
  - mirage-vnetif -> io-page -> cstruct >= 1.0.1
  - mirage-types-lwt -> cstruct >= 1.4.0
  - mirage-net-unix -> cstruct >= 0.8.1
Your request can't be satisfied:
  - Conflicting version constraints for cstruct

No solution found, exiting
```

Yet it isn't clear from the message what's actual wrong; it seems that e.g. `1.9.0` would work fine.
On the other hand, trying to install cstruct explains what's wrong:

```
$ opam pin add cstruct 1.9.0
cstruct is now version-pinned to 1.9.0

[cstruct] https://github.com/mirage/ocaml-cstruct/archive/v1.9.0.tar.gz downloaded

cstruct needs to be reinstalled.
[ERROR] cstruct.1.9.0 is not available because your system doesn't comply with ocaml-version >= "4.01.0" & ocaml-version < "4.03.0".
```

Maybe the error message could mention that no available version of `cstruct` satisfies the constraints, instead of claiming (apparently erroneously) that the constraints are conflicting.

Here's my config:

```
$ opam config report
# OPAM config report
# opam-version    1.2.2 
# self-upgrade    no
# os              linux
# external-solver no
# criteria        -removed,-notuptodate,-changed
# jobs            4
# repositories    1* (http)
# pinned          0
# current-switch  4.03.0
# last-update     2016-05-12 21:20
```

**Comment by AltGr** [comment]
Indeed, `No available versions of cstruct satisfy the constraints` would be more accurate, as opam checks only available packages matching them, not if the resulting set of _possible_ versions is empty (e.g. as `> 2 & < 1` would be).

Not also that in this specific case, the message may get better with dependencies towards ocaml (upcoming opam 2.0) rather than `available:` formulas.
