### ISSUE TITLE
Feature: have `--keep-build-dir` reuse previous build artifacts

### ISSUE THREAD

**Issue by gasche** [ocaml/opam#2596]
Feature request: when compiling a package with `-keep-build-dir`, reuse the build directory of a previous build if it still exists.

The use-case was suggested by @cpitclaudel on IRC just now. Consider a workflow when someone wants to iteratively develop a package Lib that is a dependency of a package Prog, and test the induced changes in Prog. If I pin `Lib` and reinstall it during development (`opam reinstall lib`), Prog will be reinstalled automatically by opam, but always starting from a clean (empty) state and rebuilding the whole package. On the other hand, with my proposed feature,  if I use `opam reinstall lib --keep-build-dir`, Prog would be recompiled from its old build directory, and thus reuse old build artifacts to substantially speed up compilation.

(One may also add a new option `--reuse-build-dir` for this specific semantics which arguably is a bit different from `--keep-build-dir`, as it explains how to deal with the past, not the future.)

A difficulty is to know whether the previous build directory actually corresponds to the same package sources. For archive packages, I think it's safe to assume that the same sources can be reused unchanged (the archive should not change without a version change). For path pins, there is no issue as there is no separate build directory -- people just build from the path itself. For git pins, one would probably have to `git pull` the new sources before rebuilding.

**Comment by AltGr** [comment]
I see how this could be useful.

How opam proceeds is that it maintains an internal mirror of the package (the archive, a git clone, an rsync'd dir, etc.) and synchronises that. At this point, it already has the information of whether the source has changed, and could, for this specific case, skip the step where it copies or uncompresses from the internal mirror to a fresh build dir, and just keep the old build dir. What is required is to pass the "has changed" information along, which might require a little bit of work though.

Thanks for the suggestion.

**Comment by samoht** [comment]
This feature would be very cool. With https://github.com/ocaml/ocamlbuild/issues/91 it could allow fast incremental recompilation of OCaml packages with opam, which would be very useful.

**Comment by AltGr** [comment]
Implemented. Regarding updates of the package, the new version is simply copied over the existing build dir, which should be fine in general.
