### ISSUE TITLE
Dependency flags. Minor parsing issue in 1.2.2

### ISSUE THREAD

**Issue by Kakadu** [ocaml/opam#2600]
I can write 

```
"ppx_deriving" { test & >= "3.0-modular-implicits" }
```
but I can't (opam lint fails)
```
"ppx_deriving" { >= "3.0-modular-implicits" & test }
```

Can you double check?

**Comment by AltGr** [comment]
Yes, the first is how you should write it according to [the documentation](http://opam.ocaml.org/doc/Manual.html#opamfield-depends), and the second is not accepted.

Note that this constraint has been relaxed in `2.0~dev`
