### ISSUE TITLE
opam pin -k git observes deleted files

### ISSUE THREAD

**Issue by hannesm** [ocaml/opam#2601]
hey (sorry if this has been reported before, I couldn't find any issue describing this behaviour).

I have `opam-1.2.2` installed; if I pin locally to git `opam pin add -k git foo /tmp/foo`, where the latest commit is deletion of a file (let's call it `/tmp/foo/bar`), and I run `opam install -b foo`, the build directory still contains a `bar`.

My expectation was that `-k git` will use the git HEAD, where `bar` is no longer present.

**Comment by hannesm** [comment]
hmmm, shouldn't it synchronise the git.... somehow I get `already up-to-date`:
```
=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[foo] /tmp/foo already up-to-date
The following actions will be performed:
  ∗  install foo *

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[foo] /tmp/foo already up-to-date
```

**Comment by AltGr** [comment]
You're probably in "mixed mode", read the note about it when pinning (opam will synchronise the tracked files only, but at their "tree" state, not their "index" or committed state).
The behaviour you describe has been fixed on master, but indeed was a bug with mixed mode (of which some have requested the removal, in favor of a `opam update <pkg> --dirty`, because it might be misleading)

**Comment by hannesm** [comment]
`pin -k git` resolves to mixed mode?  I'm confused now

**Comment by AltGr** [comment]
mixed mode is turned on for pins targetting a version-controlled local path, without a specific branch set (it's still related to git in the files it chooses to sync).
you need to select a ref to turn it off, e.g. `~/src/mypkg#HEAD`

**Comment by dbuenzli** [comment]
> you need to select a ref to turn it off, e.g. ~/src/mypkg#HEAD

I would even suggest `#master` this makes it for less surprises in the long term. @hannesm see this https://github.com/ocaml/opam/issues/2156 for a discussion of all this.

**Comment by hannesm** [comment]
thx @dbuenzli and @AltGr for the explanation and pointer
