### ISSUE TITLE
failure on opam switch 3.12.1

### ISSUE THREAD

**Issue by tjim** [ocaml/opam#2602]
Installing ocaml 3.12.1 fails because opam cannot retrieve a patch file

    https://github.com/hhugo/ocaml/compare/3.12.1...fix-3.12.1.diff

Github says this does not exist, leading to a 404 error.
(opam 1.2.2 on Mac OS 10.11.5)

**Comment by AltGr** [comment]
This seems to be a packaging issue, please report to `opam-repository` instead. Thanks!
