### ISSUE TITLE
Switch migration to dev~alpha2

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2616]
The migration of my `.opam` from dev~alpha1 went smoothly, my messy `.opam` doesn't seem broken! :)
However, it seems that you need to basically reinstall everything in your switches (because of the new `ocaml` package). It's a bit costly.

Adtionally, Non-standard switches causes issues. In my `4.02.1+BER` switch:
```
% eval `opam config env --switch 4.02.1+BER`                  
[ERROR] No definition found for the following installed packages: { base-bigarray.~unknown, base-metaocaml-ocamlfind.~unknown, base-ocamlbuild.~unknown, base-threads.~unknown, base-unix.~unknown }
        This switch may need to be reinstalled
[ERROR] No definition found for the following installed packages: { base-bigarray.~unknown, base-metaocaml-ocamlfind.~unknown, base-ocamlbuild.~unknown, base-threads.~unknown, base-unix.~unknown }
        This switch may need to be reinstalled
% opam upgrade --fixup                      
[ERROR] No definition found for the following installed packages: { base-bigarray.~unknown, base-metaocaml-ocamlfind.~unknown,
        base-ocamlbuild.~unknown, base-threads.~unknown, base-unix.~unknown }
        This switch may need to be reinstalled
The following dependencies couldn't be met:
  - ocaml-variants -> base-metaocaml-ocamlfind
Your request can't be satisfied:
  - base-metaocaml-ocamlfind.~unknown is part of the base for this compiler and can't be changed

No solution found, exiting
```

There are other issues with switches where I experimented with pinning compiler packages, but that's expected. :)

**Comment by Drup** [comment]
Apparently, there is a similar issues for all alias switchs, `base-threads` ends up with `unknown` version and can't be changed.

**Comment by AltGr** [comment]
You might be able to work around it with `opam switch set-compiler COMP --switch SWITCH` to exclude the base-* packages from base packages on the given switch.

**Comment by AltGr** [comment]
One possibility to fix this would be to allow `fixup` to change base packages, as a last resort when all else fails...

**Comment by AltGr** [comment]
Does `opam switch reinstall` work ?

**Comment by Drup** [comment]
Well, that was interesting:

```
% opam sw reinstall 4.02.1+BER                  
[ERROR] No definition found for the following installed packages: { base-bigarray.~unknown, base-metaocaml-ocamlfind.~unknown,
        base-ocamlbuild.~unknown, base-threads.~unknown, base-unix.~unknown }
        This switch may need to be reinstalled
[ERROR] Translation error for package base-unix (= 2)
Fatal error:
File "solver/opamCudf.ml", line 180, characters 6-12: Assertion failed
```

**Comment by Drup** [comment]
Your idea for fixup sounds good (I actually expected this behavior). I don't really need a workaround, it's quicker to just nuke the switch and recreate it, I'm only keeping them around for testing purposes. :)

**Comment by AltGr** [comment]
Difficult to be totally sure, but I _think_ this should be fixed. Please reopen if not, and as always, thanks for the feedback :)
