### ISSUE TITLE
Bash on Ubuntu on Windows: opam ocaml version

### ISSUE THREAD

**Issue by dannywillems** [ocaml/opam#2621]
I experiment OCaml on Bash on Ubuntu on Windows and I succeeded to install ocaml (with apt-get), compile opam from source, install js_of_ocaml, lwt, eliom, gen_js_api (and other) and switch to 4.03.0 with opam.

Now, I try to use a binding to a Cordova plugin (see [this repo](https://github.com/dannywillems/ocaml-cordova-plugin-list)). I added the remote package provider and try to use opam install cordova-plugin-sms and here the response:
```
[ERROR] cordova-plugin-sms.1.0 has unmet availability conditions: ocaml-version >= "4.03.0"
```
although I switched to 4.03.0
![opam ocaml version](https://cloud.githubusercontent.com/assets/6018454/17071377/813caefe-5061-11e6-855e-7a276efa6846.png)

I have same issue with an other pin package (jsoo_lib).

**Comment by dsheets** [comment]
I notice that you ran ```eval `opam switch 4.03.0` ``` when the result of `opam switch 4.03.0` told you to run ```eval `opam config env` ```. Have you tried installing `cordova-plugin-sms` after running ```eval `opam config env` ```?

**Comment by dannywillems** [comment]
Ahha, it was a mistake when I took the screenshot. In fact, I did the right eval but it seems it wasn't working because the compiler wasn't well installed (even if it was listed). There were no description for this compiler in the list.
I removed the compiler with ```opam switch remove``` and reinstalled it.
I have the same error. Here a screenshot.

![opam ocaml version](https://cloud.githubusercontent.com/assets/6018454/17085290/df10cb54-51d4-11e6-8ae5-0cb6d2a718da.png)

**Comment by AltGr** [comment]
I see you are using trunk opam; the format of packages has slightly changed recently, and while the repo at https://opam.ocaml.org/2.0~dev (to which you have been redirected) is automatically rewritten, your definition for `cordova-plugin-sms` was not.

As noted [on the `devel` mailing-list](http://lists.ocaml.org/pipermail/opam-devel/2016-July/001486.html), variable `ocaml-version` is no longer defined, and you should use a dependency towards the OCaml package instead (`depends: "ocaml" {>= "4.02.3"}` in your case) . For a quick workaround, you can define the variable manually with `opam config set ocaml-version 4.03.0`.

@dsheets: the eval command is needed for the shell and other programs to have PATH and other environment variables properly defined to access opam data, but shouldn't have any impact on uses of the `opam` command itself.

**Comment by dannywillems** [comment]
Thank you @AltGr It's working.

**Comment by AltGr** [comment]
It sounds a bit dangerous, but to avoid these issues it would be possible to have opam automatically upgrade definitions from the 1.2 format.

**Comment by dannywillems** [comment]
@AltGr I think it could be a good idea to automatically upgrade.
