### ISSUE TITLE
`opam pin edit` doesn't accept a TARGET

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2624]
In particular, that doesn't work: `opam pin edit ocaml-base-compilers.4.03.0`.
Why is that so ? I could want to tweak something in an existing package and then install it.

**Comment by dbuenzli** [comment]
Doesn't it work with `opam pin add -e pkg` ? I think `opam pin edit` is for editing an existing pin.

**Comment by AltGr** [comment]
Indeed, you can do it with `opam pin add ocaml-base-compilers 4.03.0 --edit`; but since we now accept `opam pin edit ocaml-base-compilers` on unpinned packages, it would make sense to allow to specify the version of the metadata you want to edit...

**Comment by AltGr** [comment]
(the trouble being that, if the package is already pinned, it doesn't make much sense)

**Comment by AltGr** [comment]
`opam pin ocaml-base-compilers.4.03.0 -e` now works, so I guess that provides everything you wanted.
