### ISSUE TITLE
author is not a subfield of authors

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2625]
In particular, `opam list --field-match=author:Radanne` is not equivalent to `opam list --field-match=authors:Radanne`. This made me very confused.

**Comment by Drup** [comment]
(IIRC, for a while, opam accepted both in opam files, and converted everything to `authors`)

**Comment by AltGr** [comment]
Yes, `author:` is deprecated and everything is treated as `authors:`; there is a missing check though, where you can specify `--field-match=foobar:foo` and you'll just get empty results...

**Comment by AltGr** [comment]
This has been fixed
