### ISSUE TITLE
opam cannot pin a shallow clone

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#2626]
Trying to Git pin to a shallow clone (for instance created with `--depth 1`) result in a error:

```
[datakit: git]
+ git "init" (CWD=/home/opam/.opam/system/packages.dev/datakit)
- Initialized empty Git repository in /home/opam/.opam/system/packages.dev/datakit/.git/
[datakit: git]
+ git "remote" "add" "origin" "/home/opam/src/datakit" (CWD=/home/opam/.opam/system/packages.dev/datakit)
[datakit: git]
+ git "commit" "--allow-empty" "-m" "opam-git-init" (CWD=/home/opam/.opam/system/packages.dev/datakit)
- [master (root-commit) 7ab575a] opam-git-init
[datakit: git]
[datakit: git]
+ git "fetch" "-q" "origin" "+HEAD:refs/remotes/opam-ref" (CWD=/home/opam/.opam/system/packages.dev/datakit)
- warning: no common commits
- warning: reject refs/remotes/opam-ref because shallow roots are not allowed to be updated
[datakit: git]
+ git "reset" "--hard" "refs/remotes/opam-ref" "--" (CWD=/home/opam/.opam/system/packages.dev/datakit)
- fatal: Failed to resolve 'refs/remotes/opam-ref' as a valid revision.
[91m'opam pin add datakit.dev -k git /home/opam/src/datakit#HEAD -n -vv' failed.
# opam-version    1.2.2
# os              linux
Git error: refs/remotes/opam-ref not found.
```

Would be great to not fail in that case, as a lot of CI are using shallow clones to speed-up their builds.

**Comment by samoht** [comment]
Note: sometimes it is possible to unshallow the repo manually, before calling opam. Sometimes (private builds) this is not possible.

**Comment by AltGr** [comment]
Shallow clone handling seems to have changed a lot in recent versions of git ; I don't really get the details yet, but from this [stack-overflow question](http://stackoverflow.com/questions/33085672/shallow-update-not-allowed-git-1-9) it seems that we could just add `--update-shallow` to the git command line.

That might break compat with earlier versions of `git` though, not sure when it has been introduced. Of course, we could change the way we proceed and clone directly, but that won't remove the need to do updates afterwards (unless we wipe the clone every time...).

**Comment by AltGr** [comment]
(the option seems to date back to 1.9.0 if I read [this](https://github.com/git/git/commit/48d25cae22667dfc2c31ad620172c0f0a3ac1490) correctly, so that may be OK)

**Comment by AltGr** [comment]
`--update-shallow` has been added, which should fix this.
