### ISSUE TITLE
aspcud not available on CentOS 6 despite what the wiki says

### ISSUE THREAD

**Issue by bbc2** [ocaml/opam#2629]
The [wiki][1] states that aspcud should be available on CentOS 6 and 7.  However, the linked page to the openSUSE build service reports this package as unresolvable in CentOS 6 for both x86_64 and i586. Is this a mistake or have I missed something?

[1]: https://github.com/ocaml/opam/wiki/Distributions

**Comment by avsm** [comment]
It's not available.  The [centos Docker containers](http://hub.docker/com/r/ocaml/opam) use an online solver hosted at solver.ocaml.io instead.

**Comment by bbc2** [comment]
Updated the wiki to reflect that: https://github.com/ocaml/opam/wiki/Distributions/_compare/b7a7f17cb5b9a3d7067835710a3d0255099daab4...c05eb58b050cd714f1aa874a755359edae7213bb.

**Comment by AltGr** [comment]
Thanks!
