### ISSUE TITLE
Unix.lockf may fail on some platforms (e.g. Hurd)

### ISSUE THREAD

**Issue by glondu** [ocaml/opam#2635]
Hello,

OPAM doesn't work on Hurd because Unix.lockf is not supported there. See:

  https://buildd.debian.org/status/fetch.php?pkg=opam&arch=hurd-i386&ver=1.2.2-5&stamp=1458386255

I think a fallback should be used in this case.

**Comment by glondu** [comment]
Bugreport in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829215

**Comment by AltGr** [comment]
Wow, interesting, and thanks for the report.
This should probably be reported to OCaml itself, and at least documented at http://caml.inria.fr/pub/docs/manual-ocaml/libref/Unix.html , which now has details on what is available on Windows -- I wasn't aware of further restrictions for more exotic OSes. I haven't checked how locks are handled on Windows, but there might actually be a workaround implemented there already, and implementing a workaround for all the locking logic in opam doesn't sound good. Of course, we could also either check the OS with a preselected list, or just try to catch the error and ignore locks altogether...

But I doubt Hurd doesn't offer any reasonable alternative way of locking ?

**Comment by sguillia** [comment]
OPAM doesn't work on OS X when the disk containing the `.opam` directory is mounted with NFS.

Command `opam install ocamlsdl` fails with error message:
```"lockf" failed: Operation not supported on socket```

Is there any fix planned ?

Thank you

**Comment by sthibaul** [comment]
FI, lockf was fixed in the case used by opam (whole-file locking), just the plumbing was missing.

**Comment by dra27** [comment]
It sounds like the original problem on Hurd will has been resolved. If the issue with NFS-mounted opam roots on macOS still exists, please could that be re-opened in a separate issue?

**Comment by dra27** [comment]
As a side-note for other platforms, OCaml's Unix library is possibly heading in the direction of _requiring_ `fnctl` record locking (which is the default implementation of `Unix.lockf`) and removing support for `lockf(3)` completely so it _might_ just becoming the case that it's required for opam too.
