### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by vbmithr** [ocaml/opam#2641]
```
dtc@dtc-test:~/code$ opam --version                                                                        
2.0~alpha3

dtc@dtc-test:~/code$ opam switch
# switch        compiler                       description
4.03.0+flambda  ocaml-variants.4.03.0+flambda  Official 4.03.0 release with flambda activated
default         ocaml-system.4.01.0            The OCaml compiler (system version, from outside of opam)

dtc@dtc-test:~/code$ opam install core.114.06+90                                                           
[ERROR] core.114.06+90 has unmet availability conditions: ocaml-version >= "4.03.0"
```

**Comment by vbmithr** [comment]
@AltGr Any idea?

**Comment by AltGr** [comment]
`ocaml-version` is no longer defined, and this means you are using a package definition for `core` that hasn't been rewritten (i.e. probably not from the rewritten official repo at `https://opam.ocaml.org/2.0`, to which you would have been redirected).

A short-term workaround is to use `opam config set ocaml-version 4.03.0` on this switch, although you might run into other issues with package definitions for `1.2`.
