### ISSUE TITLE
opam VIRUS in windows

### ISSUE THREAD

**Issue by azhai** [ocaml/opam#2643]
ocaml-4.02.3-x86_64-mingw64-installer4-opam.exe
Windows 7 64bit
The opam infect system's cmd.exe
Thousands of processes what named opam.exe are launched,

**Comment by samoht** [comment]
Sorry to hear that. Where did you download that `.exe` from?

**Comment by AltGr** [comment]
Sorry to hear that, and thanks for reporting, but without more detail, there is little we can do:

- where did you download the installer from ? This is probably where the file was infected, and I can assure you the source code present on Github is free of viruses. It _could_ be that our website at `https://opam.ocaml.org` has been compromised, but we don't even provide Windows binaries at the moment.
- what makes you assume that this is a virus ? Did it get diagnosed by some antivirus software ? If so, please give the details.
- can you explain what makes you think `cmd.exe` was infected ?

Another possibility is that this is a bug in the Windows installer you used, that somehow created a loop in the configuration of the startup of `cmd.exe`. If you have been using @protz's [installer](https://github.com/protz/ocaml-installer), I suggest you read the documentation there and check for known pitfalls, and this is where you should report issues.

**Comment by jabowery** [comment]
I don't think this is a virus.  I noticed my system grinding to a halt with large numbers of opam.exe and cmd.exe processes being spawned when I launched cmd.exe.  Uninstalling ocaml permitted me to use cmd.exe again.

The error message that came up repeatedly upon launching cmd.exe was:

`[ERROR] The current switch (system) is an unknown compiler switch.`
