### ISSUE TITLE
opam or OPAM ?

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam#2645]
I've started shifting from `OPAM` to `opam` for naming the project since @hannesm made me notice that this reminded him every time of the Monty Python's Flying Circus [SPAM](https://www.youtube.com/watch?v=M_eYSuPKP3Y) sketch, especially since the word appears so often in the documentation. And now I have just done it to you too.

But at the moment OPAM has no real policy or consistency on naming OPAM. Should the OPAM team define one and try to remain consistent on how we write OPAM, one way or the other ? The [OPAM homepage](https://opam.ocaml.org) still writes it OPAM.

**Comment by dbuenzli** [comment]
Yes it should. FWIW in documentation (e.g. `opkg` or `topkg`), I write `OPAM` everywhere except when I refer to the tool. E.g. I write `OPAM file` not `opam file`.

**Comment by samoht** [comment]
What about O'pam or Objective Pam?

**Comment by AltGr** [comment]
Ok, let's throw a vote: please react with +1/-1 emojis on the following proposals

**Comment by AltGr** [comment]
- keep to OPAM

**Comment by AltGr** [comment]
- lowercase opam

**Comment by AltGr** [comment]
- capitalised Opam

**Comment by lpw25** [comment]
- OCaml case: OPam
