### ISSUE TITLE
broken url for extlib in 1.2.2

### ISSUE THREAD

**Issue by jnbr** [ocaml/opam#2670]
in the 1.2.2 release, in src_ext/Makefile URL_extlib points to a broken link:
URL_extlib = http://ocaml-extlib.googlecode.com/files/extlib-1.5.3.tar.gz

this breaks building opam-1.2.2

The problem can be fixed by switching to this url (got it from here: http://opam.ocaml.org/packages/extlib/extlib.1.5.3/):
http://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/ocaml-extlib/extlib-1.5.3.tar.gz

**Comment by AltGr** [comment]
Yes, @avsm fixed that with a PR to the 1.2 branch already (#2668)
