### ISSUE TITLE
conf-pkg-config appears to be broken

### ISSUE THREAD

**Issue by janrichter222** [ocaml/opam#2675]
An opam install conf-pkg-config fails with message 

[ERROR] The compilation of conf-pkg-config.1.0 failed.
Removing conf-pkg-config.1.0.
  Nothing to do.

Inspecting the build folder, the package folder is empty.

**Comment by dsheets** [comment]
Could you please supply details of your OS/distribution/versions?

**Comment by dsheets** [comment]
Also, this tracker is for the `opam` tool [ocaml/opam-repository](https://github.com/ocaml/opam-repository/issues) is for the package database.
