### ISSUE TITLE
OPAM does not compile with recent version of OCaml

### ISSUE THREAD

**Issue by pmetras** [ocaml/opam#2680]
Trunk version of OPAM 2.0 (commit 21bd4113a4b4dea0524949fc05bafd80a3ac59cc) does not compile with development version of Ocaml (4.05.0+dev0-2016-08-01)

Result of gmake lib-ext on Minix3:

```
File "extlib/src/extString.ml", line 1:
Error: The implementation extlib/src/extString.ml
       does not match the interface extlib/src/extString.cmi:
       ...
       In module String:
       Values do not match:
         external unsafe_set : bytes -> int -> char -> unit
           = "%bytes_unsafe_set"
       is not included in
         external unsafe_set : ExtBytes.Bytes.t -> int -> char -> unit
           = "%string_unsafe_set"
../OCamlMakefile:1076: recipe for target 'extlib/src/extString.cmo' failed
gmake[4]: *** [extlib/src/extString.cmo] Error 2
gmake[4]: Leaving directory '/home/pierre/ocaml/opam/src_ext'
../OCamlMakefile:792: recipe for target 'byte-code-library' failed
```

**Comment by AltGr** [comment]
Probably just a problem with the version of extlib ? Assuming you have a working opam (1.2 ?), can you try `opam install opam-devel` ?

**Comment by hannesm** [comment]
looks like the same issue as https://github.com/ocaml/ocaml/pull/772 (followup of https://github.com/ocaml/ocaml/pull/596)... I think @gasche reported that extlib in trunk has fixed this...

**Comment by hannesm** [comment]
(see https://github.com/ocaml/opam-repository/pull/7507 for further references)

**Comment by AltGr** [comment]
Can you confirm this is fixed ?

**Comment by gasche** [comment]
See the current [opam-builder report](http://opam.ocamlpro.com/builder/html/report-full.html): the [extlib dependency](http://opam.ocamlpro.com/builder/html/report-full.html#extlib) now builds, but [dose](http://opam.ocamlpro.com/builder/html/report-full.html#dose) does not (only 3.1.2 does, not the 3.3 that opam-lib depends on).

**Comment by pmetras** [comment]
Sorry, I haven't had the time to test that trunk version solves the issue. I don't have previous versions of opam as I'm bootstraping it on Minix3. I looked briefly at changing the Makefile to download a more recent version of ocaml-extlib but it does not exist yet. And I was stuck there...
