### ISSUE TITLE
Trying to create a local switch (v2) wants to upgrade my global switch (v1.2.2)

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#2684]
I want to keep my global switch with 1.2.2, can't afford living on alpha software.

```
> opam2 switch create _opam 4.03.0
This version of opam requires an update to the layout of /Users/dbuenzli/.opam from version 1.2 to version 2.0~alpha3, which
can't be reverted.
```

**Comment by AltGr** [comment]
You still need an opam root, even if the switch is local. I'd advise exporting `OPAMROOT=$HOME/.opam2` and running `opam2 init` before the `switch create` command.

Also, `opam2 switch create ./ 4.03.0` will create the switch in `./_opam`, you probably don't want it in `_opam/_opam`.

**Comment by dbuenzli** [comment]
> You still need an opam root,

Ok but. Why ?

**Comment by AltGr** [comment]
Global configuration and repository caches are still held in ~/.opam. In other terms, local switches have been added, but they are not local opam roots.

**Comment by dbuenzli** [comment]
Ok thanks.
