### ISSUE TITLE
opam2 admin: convert all compiler descriptions to new format

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#2686]
Right now we only seem to convert the main compiler switches to the `ocaml-base-system` packages, but it would be really useful to have the entire set of variants (most notably, flambda), and also the trunk packages for 4.04/4.05 also included in the conversion.

This helps the https://hub.docker.com/r/ocaml/opam-dev/ packages for OPAM2 snaps exactly match the ones available from https://hub.docker.com/r/ocaml/opam/ for OPAM1...

**Comment by AltGr** [comment]
They are all there already, as `ocaml-variants.OCAMLVERSION+VARIANTNAME`, e.g. `ocaml-variants.4.03.0+flambda`.

The `ocaml-base-compiler` package only contains the official OCaml releases (in opam 1.2, that's the ones with no `+` in the version name)

**Comment by avsm** [comment]
Thanks for the clarifications! The OPAM2 Docker containers now support this scheme
