### ISSUE TITLE
make -j broken

### ISSUE THREAD

**Issue by whitequark** [ocaml/opam#2706]
To reproduce:
```
./configure
make -j4
```
This results in errors such as:
```
File "core/opamVersion.mli", line 14, characters 8-24:
Error: Unbound module OpamStd
../OCamlMakefile:1056: recipe for target 'core/opamVersion.cmi' failed
```

**Comment by AltGr** [comment]
This is a known bug; for parallel builds, use `make fast`, which relies on ocp-build. (OCaml)Makefiles are only really there for bootstrapping, they are not reliable for either parallel or incremental builds.

**Comment by whitequark** [comment]
Can you update the README?
