### ISSUE TITLE
variables.sh MANPATH odd?

### ISSUE THREAD

**Issue by mor1** [ocaml/opam#2714]
My `~/.opam/opam-init/variables.sh` had ended up with the following entry for `MANPATH`:

`MANPATH="$MANPATH:/Users/mort/.opam/system/man"; export MANPATH;`

...which conflicts with the output of `opam config env`, which has

`MANPATH="/Users/mort/.opam/system/man:$MANPATH"; export MANPATH;`

resulting in a warning.

I can't recall if I edited `variables.sh` (can't think why I would've) but I can't immediately see how `variables.sh` is created. Is it possible that it's being generated incorrectly?

OPAM version 1.2.2, `system` switch on OSX

**Comment by AltGr** [comment]
Yes, I remember fixing a bug in 1.2.2 where the append operator was handled 
incorrectly in `opam config env` -- sorry for the trouble and thanks for 
notifying!
Your diagnostic was indeed right and `variables.sh` is correct in this case 
(don't bother editing it, it is rewritten on every `opam switch`)

Best,
Louis Gesbert - OCamlPro

**Comment by mor1** [comment]
Ah right, cool. If it's already fixed, I guess I'll just close this then. Thanks!
