### ISSUE TITLE
Problem when trying to install utop

### ISSUE THREAD

**Issue by Jean-MichelC** [ocaml/opam#2719]
Hello,

On a debian, using emacs, I fail to install utop:
### 1. context
`~ $ ocaml -version
The OCaml toplevel, version 4.01.0`
`~ $ opam --version
1.2.0`

From the [utop doc](https://github.com/diml/utop) : 

> camlp4 (optional)

but it seems campl4p is the reason why my install fails :
### 2. the problem
`~ $ opam install utop
The following actions will be performed:
 - install   lwt.2.4.5                             [required by utop]
 - install   lambda-term.1.10.1                    [required by utop]
 - install   utop.1.19.3
=== 3 to install ===
Do you want to continue ? [Y/n] 

=-=- Synchronizing package archives -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

=-=- Installing packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Building lwt.2.4.5:
  ./configure --disable-libev --enable-react --disable-ssl --enable-unix --enable-extra --enable-preemptive --disable-glib --disable-text
  make build
  make install
[ERROR] The compilation of lwt.2.4.5 failed.
Removing lwt.2.4.5.
  ocamlfind remove lwt

 #=== ERROR while installing lwt.2.4.5 =========================================#
 # opam-version 1.2.0
 # os           linux
 # command      ./configure --disable-libev --enable-react --disable-ssl --enable-unix --enable-extra --enable-preemptive --disable-glib --disable-text
 # path         /home/jean-michel/.opam/system/build/lwt.2.4.5
 # compiler     system (4.01.0)
 # exit-code    1
 # env-file     /home/jean-michel/.opam/system/build/lwt.2.4.5/lwt-17296-1872ec.env
 # stdout-file  /home/jean-michel/.opam/system/build/lwt.2.4.5/lwt-17296-1872ec.out
 # stderr-file  /home/jean-michel/.opam/system/build/lwt.2.4.5/lwt-17296-1872ec.err
 ### stderr ###
 # ...[truncated]
 # W: Failure("When looking for findlib package camlp4, directory /usr/lib/ocaml/camlp4 return doesn't exist")
 # W: Failure("When looking for findlib package camlp4.quotations.o, directory /usr/lib/ocaml/camlp4 return doesn't exist")
 # W: Field 'pkg_camlp4_extend' is not set: When looking for findlib package camlp4.extend, directory /usr/lib/ocaml/camlp4 return doesn't exist
 # W: Failure("When looking for findlib package camlp4, directory /usr/lib/ocaml/camlp4 return doesn't  exist")
 # W: Failure("When looking for findlib package camlp4, directory /usr/lib/ocaml/camlp4 return doesn't exist")
 # W: Failure("When looking for findlib package camlp4.quotations.o, directory /usr/lib/ocaml/camlp4 return doesn't exist")
 # E: Cannot find findlib package camlp4
 # E: Cannot find findlib package camlp4.extend
 # E: Cannot find findlib package camlp4.quotations.o
 # E: Failure("3 configuration errors")

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following failed
 - install   lwt.2.4.5
Due to the errors, the following have been cancelled
 - install   utop.1.19.3
 - install   lambda-term.1.10.1`

**Comment by dbuenzli** [comment]
This doesn't seem to be the latest version of `lwt` could you try to do an `opam update` and retry `opam install utop`. If that still fails, try first with an `opam install lwt.2.5.2` and then `opam install utop`.

**Comment by Jean-MichelC** [comment]
Thks dbuenzli

I finally solved it by a simple 
`sudo apt-get install m4 ocaml-native-compilers camlp4-extra opam`
