### ISSUE TITLE
on freebsd: set owner/group (was: 1001/0): Operation not perimtted

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#2722]
Hello, I get a lot of those warnings when installing packages on freebsd.
There are just warnings but they clutter the logs.
It's the mv command issued by opam which triggers this.

**Comment by kit-ty-kate** [comment]
I've been using opam on FreeBSD lately and I've never seen this. I would assume this was fixed and can be closed.

**Comment by rjbou** [comment]
Thanks @kit-ty-kate
