### ISSUE TITLE
can't we have OS constraints in the depends section of an opam file ?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#2731]
depends: [                                                                      
      "conf-wget" {build & os = "darwin"}
    ]

opam tells me:
error  2: File format error: at ~/src/clangml/opam:28:26, Expected a list
              of constraints

**Comment by AltGr** [comment]
This is an opam 2.0 feature. See the [1.2 doc](http://opam.ocaml.org/doc/Manual.html#opamfield-depends) vs [2.0](http://opam.ocaml.org/doc/2.0/Manual.html#Filteredpackageformulas)

**Comment by UnixJunkie** [comment]
OK, I will just say it's a build constraint then.
