### ISSUE TITLE
gpgsign=true in .gitconfig is breaking opam repo add

### ISSUE THREAD

**Issue by dave-tucker** [ocaml/opam#2743]
I recently enabled GPG signing in my `.gitconfig` on Mac OSX

```
[commit]
    gpgsign = true
```

Running the following command now fails with the cryptic error `Couldn't fetch repo`

```
$ opam repo add mirage-dev https://github.com/mirage/mirage-dev.git
[ERROR] Could not fetch repo
```

This is the output with `-vv` enabled:

```
+ git "init" (CWD=/Users/dave/.opam/repo/mirage-dev)
- Initialized empty Git repository in /Users/dave/.opam/repo/mirage-dev/.git/
+ git "remote" "add" "origin" "git://github.com/mirage/mirage-dev.git" (CWD=/Users/dave/.opam/repo/mirage-dev)
+ git "commit" "--allow-empty" "-m" "opam-git-init" (CWD=/Users/dave/.opam/repo/mirage-dev)
- error: gpg failed to sign the data
- fatal: failed to write commit object
[ERROR] Could not fetch repo
'opam repo add -vv mirage-dev git://github.com/mirage/mirage-dev.git' failed.
```
reverting the change to my `~/.gitconfig` fixes the issue.

**Comment by AltGr** [comment]
Hi, and thanks for reporting.

I'll have to investigate what this git option does exactly; we may want to bypass `~/.gitconfig` for uses internal to opam as there have been an issue with a different option already.

opam sets a given user identity when calling git (to avoid blocking when they are not set up already) ; that may be the cause of the issue here.

**Comment by dave-tucker** [comment]
Thanks for the response @AltGr 

Here's a description of what this option does from `man gitconfig`
```
commit.gpgSign
    A boolean to specify whether all commits should be GPG signed. Use of this option when doing operations such as rebase can result in a large number of commits being signed. It may be convenient to use an agent to avoid typing your GPG passphrase several times.
```

It also gives your commits a [fancy looking badge on GitHub](https://github.com/blog/2144-gpg-signature-verification)
