### ISSUE TITLE
Typo in Opam FAQ: correct: "opam-depext" wrong: "opam depext"

### ISSUE THREAD

**Issue by lindig** [ocaml/opam#2745]
The FAQ includes an example for using opam depext (https://opam.ocaml.org/doc/FAQ.html):

```
opam install depext
opam depext <packages>
```

This should read:

```
opam install depext
opam-depext <packages>
```

**Comment by dsheets** [comment]
`depext` is an opam plugin with `tags: "flags:plugin"` in its opam file. `opam depext` should prompt the user to install `depext` if it isn't already installed. If installed, `opam depext` should execute `opam-depext`. Have you tried this?

**Comment by lindig** [comment]
Ahh - was confused here because I noticed opam-depext in my path. This was in a Docker container and was a bit difficult to debug. I guess it's fine then.
