### ISSUE TITLE
OPAM 2.0 & variable OPAMKEEPBUILDDIR

### ISSUE THREAD

**Issue by Fourchaux** [ocaml/opam#2746]
Can't we have the build directories with OPAM 2.0 ?  

I was using OPAMKEEPBUILDDIR (with OPAM 1.2.2) 
but this variable seems to have disappeared.

**Comment by AltGr** [comment]
it should still be there... The builds dirs have moved though, and are below `<switch>/.opam-switch/build`.
Moreover, `--reuse-build-dir` / `OPAMREUSEBUILDDIR` has been added to complement the keeping functionality.

**Comment by Fourchaux** [comment]
Ah, thank you. I forgot to check the .opam-switch repertory. No comment...

Note:
  (With opam 2.0~alpha4) $ opam --help
gives no info about OPAMKEEPBUILDDIR (or OPAMREUSEBUILDDIR)
