### ISSUE TITLE
Add --deps-only to the help output

### ISSUE THREAD

**Issue by basus** [ocaml/opam#2749]
It would be great to have `--deps-only` be part of the `help` command's output (and `man` page). Right now, it takes some googling to tell how to install dependencies for a project, whereas this seems like a common operation for a package manager.

**Comment by AltGr** [comment]
I don't understand, `opam install --help` show, as the third element below `OPTIONS`:
```
       --deps-only
           Install all its dependencies, but don't actually install the
           package.
```

And similarly for `man opam-install`, which has the same contents.

**Comment by basus** [comment]
Ahh, I didn't realize that the opam subcommands had their own help pages.
