### ISSUE TITLE
Install dependencies from an `opam` file

### ISSUE THREAD

**Issue by basus** [ocaml/opam#2750]
It would be great to have an option (maybe alongside `--deps-only`) where I can specify an `opam` (or `_oasis`) file to read the dependency list for. This would be useful for projects (closed or open source) that aren't regularly updated on the opam tracker.

**Comment by AltGr** [comment]
Indeed, that would be quite convenient, thanks for the suggestion.

You can do something similar by leveraging pinning, but I agree it's a bit heavyweight for that purpose:
```
opam pin add <pkgname> <directory containing the opam file> --no-action
opam install <pkgname> --deps-only
```
That will leave the package pinned, though.

**Comment by AltGr** [comment]
This now implementad as part of the `opam install DIR` feature. Thanks for the feedback!
