### ISSUE TITLE
Warning : Invalid field archive-mirrors

### ISSUE THREAD

**Issue by Fourchaux** [ocaml/opam#2758]
Quick question :

With opam 2.0~alpha5 (binary file opam-2.0-alpha5-x86_64-Linux) & OCaml 4.04.0+flambda
_$ opam upd_ displays (twice) the following Warning : 

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] synchronized from https://opam.ocaml.org/2.0~dev
[WARNING] Errors in ~/.opam/repo/default/repo, some fields have been ignored:
            - At ~/.opam/repo/default/repo:5:0:
              Invalid field archive-mirrors

Deleting the line _archive-mirrors: "https://opam.ocaml.org/2.0~dev/cache"_
is useless (Warning is back after some _$ opam upd_)

**Comment by AltGr** [comment]
Sorry about this -- this is a new field in the dev version, which has a new handling mechanism for downloads of archives and caches thereof; alpha5 doesn't yet know about this field, though, hence the warning -- you can safely ignore it, it'll be gone with the next prerelease.
