### ISSUE TITLE
Broken link in Wiki: Developing

### ISSUE THREAD

**Issue by RalfJung** [ocaml/opam#2759]
The wiki page <https://github.com/ocaml/opam/wiki/Developing> links to an "OPAM packaging tutorial" at <http://opam.ocamlpro.com/doc/Packaging.html>, but that page just gives a 404 error.

**Comment by Khady** [comment]
It should be fixed now.

2016-11-23 17:18 GMT+08:00 Ralf Jung <notifications@github.com>:

**Comment by RalfJung** [comment]
Indeed, thanks :)
