### ISSUE TITLE
[Feature Request] Show somewhere the actually installed git commit

### ISSUE THREAD

**Issue by RalfJung** [ocaml/opam#2765]
When I install a package from an opam repository that refers to a branch of a git repository, there seems to be no easy way to show the actual git commit that was installed. Knowing that git commit is useful e.g. for bugreports, where upstream will typically want to know which version the bug occurred with.

Currently, what I do is `cd ~/.opam/$SWITCH/packages.dev/$PACKAGE` followed by `git show`, but I feel like manually diving into opam-managed directories is suboptimal.

*Note*: I found the flag `--git-version` that most opam commands take, but its description ("Print the git version if it exists and exit.") is entirely opaque to me so I have no idea what it does, whether it is related to this request or how to use it. The git version of *what* is it talking about, and what does it mean by a git version "existing"?

**Comment by AltGr** [comment]
The information should be available in `opam show`, in the `pinned:` line. You can select that line specifically with `opam show -f pinned`.

> Note: I found the flag --git-version that most opam commands take, but its description ("Print the git version if it exists and exit.") is entirely opaque to me so I have no idea what it does, whether it is related to this request or how to use it. The git version of what is it talking about, and what does it mean by a git version "existing"?

Ah, sorry the doc is unclear. It's the git version _of opam_, which doesn't exist if you're on a release.

**Comment by RalfJung** [comment]
At least on opam 1.2, `show` does not show this information:
```
$ opam show coq
             package: coq
             version: 8.6.dev
          repository: coq-core-dev
              pinned: version
        upstream-url: git://github.com/coq/coq#v8.6
       upstream-kind: git
            homepage: http://coq.inria.fr/
         bug-reports: https://coq.inria.fr/bugs/
            dev-repo: https://scm.gforge.inria.fr/anonscm/git/coq/coq.git
              author: The Coq Development Team
             license: LGPL 2
             depends: camlp5
  installed-versions: 8.5.3 [coq-8.5], 8.6.dev [coq-8.6]
  available-versions: 8.0.dev, 8.1.dev, 8.2.dev, 8.3, 8.3.dev, 8.4pl1, 8.4pl2, 8.4pl4, 8.4.5, 8.4.6~camlp4, 8.4.6, 8.4.dev, 8.4.dev+ltacprof, 8.5~beta1, 8.5~beta2, 8.5~beta3, 8.5~rc1, 8.5.0~camlp4, 8.5.0, 8.5.1, 8.5.2~camlp4, 8.5.2, 8.5.3, 8.5.dev, 8.5.dev+ltacprof, 8.6~beta1, 8.6.dev, dev
         description: Formal proof management system.
$ opam show coq -f pinned
version
```

**Comment by AltGr** [comment]
Ah, it's only available (in 1.2) if your package is pinned to a version-controlled repository: here it seems (`pinned: version`) that it is only version-pinned, although it still points to a git url (my bad, you actually mentionned that in your original message).

The restriction is arbitrary, and is due to the fact that the version info is printed as part of the `pinned` field (see sample below) ; opam 2.0 has a much more flexible `opam show` format and I will make sure this restriction is lifted.
```
% opam show ocp-index                                  
             package: ocp-index
             version: 1.1.5
              pinned: git (27d92784)
        upstream-url: /home/lg/ocamlpro/ocp-index
       upstream-kind: git
            homepage: http://www.typerex.org/ocp-index.html
[...]
```

**Comment by RalfJung** [comment]
> opam 2.0 has a much more flexible opam show format and I will make sure this restriction is lifted.

Great, thanks :)

**Comment by RalfJung** [comment]
You said thus would be fixed with opam 2, and yet, with rc2, I get the following:
```
$ opam show coq
[...]
<><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><><><>
version      dev
repository   coq-core-dev
source-hash  b98ae49d
url.src:     git+https://github.com/coq/coq.git#master
homepage:    https://coq.inria.fr/
bug-reports: https://github.com/coq/coq/issues
dev-repo:    git+https://github.com/coq/coq.git
authors:     The Coq development team, INRIA, CNRS, University Paris Sud, University Paris 7, Ecole Polytechnique.
maintainer:  coqdev@inria.fr
license:     LGPL-2.1
flags:       light-uninstall
depends:     "ocaml" {>= "4.02.3"} "ocamlfind" {build} "camlp5" "num"
synopsis     Formal proof management system.
```

Seems like this should be re-opened?

**Comment by RalfJung** [comment]
Oh, never mind. It's not the the `version` row, there's a now row `source-hash` that I wasn't looking for. Sorry!
