### ISSUE TITLE
Inappropriate ioctl for device

### ISSUE THREAD

**Issue by msprotz** [ocaml/opam#2767]
I know about OPAMYES but I expected the following to work (this is on OSX, with brew's latest OPAM):

```
jonathan@chartreuse:/tmp $ cat test
#!/bin/bash

opam install core
jonathan@chartreuse:/tmp $ yes | ./test
The following actions will be performed:
  ∗  install bin_prot          113.33.00+4.03  [required by core]
  ∗  install typerep           113.24.00       [required by core]
  ∗  install variantslib       113.24.00       [required by core]
  ∗  install re                1.7.1           [required by ppx_expect]
  ∗  install ppx_core          113.33.01+4.03  [required by ppx_bench, ppx_assert, ppx_expect]
  ∗  install sexplib           113.33.00+4.03  [required by core]
  ∗  install fieldslib         113.24.00       [required by core]
  ∗  install ppx_optcomp       113.33.01+4.03  [required by ppx_driver]
  ∗  install ppx_driver        113.33.01+4.03  [required by core]
  ∗  install ppx_type_conv     113.33.02+4.03  [required by ppx_assert]
  ∗  install ppx_pipebang      113.33.00+4.03  [required by ppx_jane]
  ∗  install ppx_let           113.33.00+4.03  [required by ppx_jane]
  ∗  install ppx_inline_test   113.33.00+4.03  [required by core]
  ∗  install ppx_here          113.33.00       [required by ppx_assert, ppx_jane]
  ∗  install ppx_variants_conv 113.33.00+4.03  [required by ppx_expect, ppx_jane]
  ∗  install ppx_typerep_conv  113.33.00+4.03  [required by ppx_jane]
  ∗  install ppx_sexp_conv     113.33.01+4.03  [required by ppx_expect, ppx_assert, ppx_jane]
  ∗  install ppx_fields_conv   113.33.00+4.03  [required by ppx_expect, ppx_jane]
  ∗  install ppx_enumerate     113.33.00+4.03  [required by ppx_jane]
  ∗  install ppx_compare       113.33.00+4.03  [required by ppx_expect, ppx_assert, ppx_jane]
  ∗  install ppx_bin_prot      113.33.00+4.03  [required by ppx_jane]
  ∗  install ppx_bench         113.33.00+4.03  [required by core]
  ∗  install ppx_fail          113.33.00+4.03  [required by ppx_jane]
  ∗  install ppx_sexp_value    113.33.00+4.03  [required by ppx_jane]
  ∗  install ppx_sexp_message  113.33.00+4.03  [required by ppx_jane]
  ∗  install ppx_custom_printf 113.33.00+4.03  [required by ppx_expect, ppx_jane]
  ∗  install ppx_assert        113.33.00       [required by core]
  ∗  install ppx_expect        113.33.01+4.03  [required by core]
  ∗  install ppx_jane          113.33.00       [required by core]
  ∗  install core_kernel       113.33.02+4.03  [required by core]
  ∗  install core              113.33.02+4.03
===== ∗  31 =====
Do you want to continue ? [Y/n] Fatal error:
# opam-version    1.2.2
# os              darwin
opam: "tcgetattr" failed: Inappropriate ioctl for device
Backtrace:
  Raised by primitive operation at file "core/opamGlobals.ml", line 550, characters 17-32
  Called from file "client/opamSolution.ml", line 620, characters 14-54
  Called from file "client/opamClient.ml", line 1501, characters 10-68
  Called from file "client/opamClient.ml", line 153, characters 4-7
````

Thanks,

Jonathan

**Comment by AltGr** [comment]
This has been somehow fixed already in opam 2.0 dev, in the sense that it doesn't fail with an error anymore, but the chosen behaviour is to always answer `no` when stdin is not bound to a tty. opam 1.2 got confused when stdout was a tty but not stdin.

**Comment by msprotz** [comment]
Hmm so `yes | opam something` will mean "answer no to everything"?

**Comment by AltGr** [comment]
Indeed. Maybe checking wether `stdin` is _open_ would be more clever than checking if it's a tty ?
Really, you shouldn't use `yes |`, though, and the decision was made because it's never intended that scripts answer interactive questions.

**Comment by msprotz** [comment]
Hmm sure, but out of curiosity can you say why I should never use `yes |`? I always thought this was the exact right Unix-y way of doing that sort of things (driving a script).

**Comment by AltGr** [comment]
Well, opam makes slightly different choices between interactive and batch mode: there are cases, typically when handling errors, where the user may be asked about the course of actions, but a script should definitely fail.

For example, `opam pin --edit` will spin an editor (or whatever command set in `OPAMEDITOR`), and upon closing, check that the file is correct and prompt to reedit if not. This is convenient for the user, but from a script, even with `--yes`, you never want to answer `yes` to that question or you will get in a loop (this issue has been reported already).

This is not very different from what `apt-get` does:

       -y, --yes, --assume-yes
           Automatic yes to prompts; assume "yes" as answer to all prompts and run
           non-interactively. If an undesirable situation, such as changing a held package, trying
           to install a unauthenticated package or removing an essential package occurs then
           apt-get will abort. Configuration Item: APT::Get::Assume-Yes.

**Comment by msprotz** [comment]
Alright, makes sense. Thanks!
