### ISSUE TITLE
mark packages as being ok for git repos

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#2778]
With mainline opam-repository, `opam admin make` results in warnings;

```
[acpc.1.2.1] downloaded from https://github.com/UnixJunkie/ACPC/archive/v1.2.1.tar.gz
[WARNING] [ocaml-base-compiler.3.08.4] no checksum, not caching
[lambda-term.1.4] downloaded from http://forge.ocamlcore.org/frs/download.php/1136/lambda-term-1.4.tar.gz
```

it would be nice to be able to (e.g. via a tag) mark the `ocaml-base-compiler` and other packages that legitimately use git tags as being ok.  Then our cron updates of opam archives could flag genuine warnings more easily rather than getting lost in the noise of GitHub PR compiler variant packages.

**Comment by AltGr** [comment]
The changes in checksum handling and caching were done with the broader picture of repository signing in mind. In this context, mixing the signed, released packages with `dev` packages in the official repository is a bad idea (by "`dev` packages", I mean packages that don't point to a stable archive with a known checksum).

My opinion is that OCaml development packages should be moved to a different repository. Most users don't need all the `ocaml-variants.4.05.0+prXXX` packages, and for the ones who need them, they are one `opam repo add` away. Unless they start using signed git tags, and opam/conex starts supporting them (which is not planned), dev packages would require a different security policy anyway (requiring you to trust github and your https link to it, basically).

cc @hannesm

**Comment by AltGr** [comment]
Note that, in the case of `ocaml-base-compiler.3.08.4` which points to `http://caml.inria.fr/pub/distrib/ocaml-3.08/ocaml-3.08.4.tar.gz`, there is no reason not to have a checksum.
- the rewriting script should add the missing checksums for generated OCaml packages (I thought it did already)
- in case of VCS URLs, we could skip the warning. In "secure" mode, opam should ignore any packages from the repository that don't have a signed hash for their upstream, anyway.

Note that meaningful package errors are summarised at the end of the command:
```
[lymp.0.1.2] downloaded from https://github.com/dbousque/lymp/archive/0.1.2.tar.gz
[zephyrus.0.1] downloaded from http://archives.pps.univ-paris-diderot.fr/~qba/archives/2013.08.30/zephyrus-0.1.tar.gz
Rebuilding index.tar.gz ...
[ERROR] Got some errors while processing: cubicle.1.0, frama-c-base.20160501, frenetic.1.0, ocamltter.2.1.1, ox.1.0.0
  - [cubicle.1.0] http://cubicle.lri.fr/cubicle-1.0.tar.gz (download failed)
  - [frama-c-base.20160501] http://frama-c.com/download/frama-c-Aluminium-20160501.tar.gz (download failed)
  - [frenetic.1.0] https://people.cs.umass.edu/~arjun/download/frenetic.1.0.tar.gz (Bad checksum, expected md5=fe898ac5cdc8c06dc9d39b8d1b678af4)
  - [ocamltter.2.1.1] https://github.com/yoshihiro502/ocamltter/archive/2.1.1.tar.gz (download failed)
  - [ox.1.0.0] https://people.cs.umass.edu/~arjun/download/ox.1.0.tar.gz (Bad checksum, expected md5=ff90432a72ae48d52505968df2723ba1)
```

**Comment by avsm** [comment]
> My opinion is that OCaml development packages should be moved to a different repository

Yes, I think this is a reasonable thing to do for OPAM2.  A remote discovery mechanism would be awesome though, much like `brew tap` works, for common remotes like this to be listed.  Something post-OPAM2.0 of course :-)

**Comment by Drup** [comment]
> My opinion is that OCaml development packages should be moved to a different repository. Most users don't need all the ocaml-variants.4.05.0+prXXX packages,

Bonus point: it helps perfs a bit :p

**Comment by hannesm** [comment]
I do agree, the closest (easiest) I can come up with in the meantime would be to allow pins to git commits (for which we can produce a tarball with the very same hash every time).  This would also benefit version information (i.e. if there is an issue, and the branch is busy, a user can easily tell which commit they are on).

But, providing git urls via a separate repository, not enabled by default, also sounds good to me.

**Comment by AltGr** [comment]
On the second point, `opam show` already tells you what git hash a dev package has been installed with.
