### ISSUE TITLE
opam-version line is wrong for converted files

### ISSUE THREAD

**Issue by agarwal** [ocaml/opam#2779]
I added [Jane Street's opam repo](https://github.com/janestreet/opam-repository.git), which has files in 1.2 format. I'm running opam 2.0~alpha5. To investigate some issue I wanted to see how opam is treating the opam file for a package from this repo. So I did this:

```
$ opam info ppx_sexp_conv.114.10+84 --raw
opam-version: "1.2"
...
```

The file that is printed is in the new format, so shouldn't this say "2.0".

**Comment by AltGr** [comment]
There may be slight differences in the way the file is printed back, but if you didn't do the conversion on the repository, the file hasn't really been converted (no translation of `available: ocaml-version` to `depends: "ocaml"`, etc.) — it's just the original file, parsed and reprinted.
opam will only convert files on the fly when found in the source tree of packages you pin.

In this case, to get a 2.0 repository, you should:
```
git clone git@github.com:janestreet/opam-repository.git
cd opam-repository
opam-admin upgrade-format
git commit -a -m "opam-admin upgrade-format"
```
then use that local repository in opam.

**Comment by agarwal** [comment]
> the file hasn't really been converted (no translation of `available: ocaml-version` to `depends: "ocaml"`, etc.)

If the printout is in 1.2 format, then of course there is no error. However I'm certain this constraint was converted to 2.0 format, but unfortunately I can't reproduce that now. I'll add information if I manage to hit the issue again.
