### ISSUE TITLE
opam seeing repo in other switch

### ISSUE THREAD

**Issue by agarwal** [ocaml/opam#2780]
```
$ opam repo

=-=- Repository configuration for switch 4.03.0 -=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
 1 default https://opam.ocaml.org/2.0~dev

$ opam repo add janestreet https://github.com/janestreet/opam-repository.git
[ERROR] Repository janestreet is already set up and points to
        https://github.com/janestreet/opam-repository.git. Maybe you meant 'opam repository
        set-url' ?
```

Repos are now switch specific, right. So this is wrong. I did add a "janestreet" repo to another switch, so opam seems to be picking it up from there. I definitely did run ``eval `opam config env` ``, so it's not that.

**Comment by AltGr** [comment]
The map (repo name → repo url (and local cache)) is still global. You can now configure the list of repositories for each switch though.

In your case, the target URL is the same, though, so opam should have correctly handled it (the same as `opam repo add janestreet` would have been). It's probably a bug, I'll look.

**Comment by AltGr** [comment]
Assuming this to be fixed, without any similar report since. Thanks for reporting!
