### ISSUE TITLE
opam admin: preserve original distfile name in the hashed area?

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#2781]
opam admin make currently generates something like:

```
./md5/ed/edbe78a521ea127f4a8678505886565f
./md5/ed/edc888e16eaa90d7eade80aaf60dfee4
./md5/ed/ed9627a3509d8dc65a5b059de65da0e6
./md5/ad
./md5/ad/ad2dc42f74c77dae9302c40cf2b5ff86
```

It would be nice to also have a symlink tree of the original distfile names also linked into this structure, so that they can be retrieved like that by browsing the archive. Fedora has a scheme like: http://pkgs.fedoraproject.org/repo/pkgs/planets/planets-0.1.13.tgz/2c72f2469ee0413bd470a2ad84f2f0f8/ that allows similar functionality.

**Comment by AltGr** [comment]
Indeed, I was thinking that something like that could easily be added later :)

**Comment by AltGr** [comment]
`opam admin index --link DIR` does this:

       --link=DIR
           Create reverse symbolic links to the archives within DIR, in the
           form DIR/PKG.VERSION/FILENAME.
