### ISSUE TITLE
ocamlfind packages are not installed in ocaml directory

### ISSUE THREAD

**Issue by lefessan** [ocaml/opam#279]
I was expecting libraries to be installed in .opam/VERSION/lib/ocaml/, but most libraries are installed (by ocamlfind, I think) in .opam/VERSION/lib/.

This might be a problem for people using the "-I +library" option, because the library is not in $OCAMLLIB/library as expected, but one level upper (it is also a problem for ocp-build when trying to infer the environment from the $OCAMLLIB directory, since most libraries are missing there).

**Comment by linas** [comment]
Nine years later, some people are reading this thread because they still cannot figure out how to correctly install ocaml packages. I mean, `ocamlfind install` does install stuff, but not in a way that `ocaml` can find and open those packages. Sigh. All this seems harder than it should be.
