### ISSUE TITLE
building opam from source x86_64 and i686

### ISSUE THREAD

**Issue by ErwanGa** [ocaml/opam#2790]
Due to project constraints I've to build opam source.
for branch 1.2.2, The build fails : the source of extlib will result in an invalid MD5 checksum 
_*******
make[1]: Entering directory '/work/ocaml/opam-1.2.2/src_ext'
[ -e  extlib-1.5.3.tar.gz ] || curl  -OL http://ocaml-extlib.googlecode.com/files/extlib-1.5.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1586  100  1586    0     0   7085      0 --:--:-- --:--:-- --:--:--  7112
ocaml ../shell/md5check.ml extlib-1.5.3.tar.gz 3de5f4e0a95fda7b2f3819c4a655b17c
MD5 for extlib-1.5.3.tar.gz differ:
  expected: 3de5f4e0a95fda7b2f3819c4a655b17c
    actual: a0830b6fd2439ba2e924e08ba9e82a79
******_

It appears that 
=> http://ocaml-extlib.googlecode.com/files/extlib-1.5.3.tar.gz is no more available.
The content of the archive has be moved @ https://github.com/ygrek/ocaml-extlib/archive/1.5.3.tar.gz

=> The archive has also been updated
     The previous content was  :  ./extlib/foo
     The new content is             : ./ocaml-extlib-1.5.3/extlib/foo  and also contents ./ocaml-extlib-1.5.3/test

**Comment by ErwanGa** [comment]
Here is the patch I'm using
[opam-1.2.2-extlib-1.5.3.txt](https://github.com/ocaml/opam/files/663968/opam-1.2.2-extlib-1.5.3.txt)

=> It works, but I do not have any idea if there is some side effects

**Comment by AltGr** [comment]
The `1.2` branch (rather than the `1.2.2` tag) should have been fixed already, see 742b7e3e517d66ed898075ac3b6ee7aa307995db.
Best,

**Comment by ErwanGa** [comment]
Ok 
Thanks
I'm just surprised that there is no tag/release for that as tag 1.2.2 is broken

However, I'll take this commit as patch. 
Cheers
