### ISSUE TITLE
interest in support npm style layout?

### ISSUE THREAD

**Issue by bobzhang** [ocaml/opam#2792]
Currently [bucklescript](https://github.com/bloomberg/bucklescript) generates node compatible modules, this requires for each package the directory name has to be `node_modules`.
for example current in opam the directory layout is 

```
lib 
|----- unix
|------ yojson
```

in node style, it maybe adjusted to 

```
lib
|---- node_modules--- unix
|-----node_modules -- yojson
```

I am not a npm expert, cc @jordwalke @chenglou

**Comment by AltGr** [comment]
Not sure exactly what the question is, but opam 2 allows to customise switch variables, including standard directories:
```
opam switch create --empty foo
opam config set lib $(opam var lib)/node_modules
```

This needs to be done by hand for every new switch, though.

**Comment by jordwalke** [comment]
In that example what is `lib`? Is it the findlib `lib` directory at the top of the `opam` root?

**Comment by AltGr** [comment]
`lib` is the variable describing the switch's `lib/` directory, normally `<switch-prefix>/lib`
A more reliable (and idempotent) command would have been `opam config set lib $(opam var prefix)/lib/node_modules`

**Comment by jordwalke** [comment]
As part of `esy`, we have found a way to make it so each findlib library gets its own lib/man directory and then we dynamically create findlib search paths on the fly custom tailored to the building of each package, exposing only the things that it models as a dependency. This also allows multiple versions of a package to exist simultaneously. It's kind of like a hybrid of node_modules and OPAM layout.
