### ISSUE TITLE
Impossible to install packages from janestreet dev repo (opam2)

### ISSUE THREAD

**Issue by vbmithr** [ocaml/opam#2799]
I'm using latest HEAD.
Steps to reproduce:

```
git clone git://github.com/janestreet/opam-repository js-opam-repo
cd js-opam-repo
opam-admin upgrade-format
opam pin add repo js .
opam info ppx_optcomp
```

Produces the following error:
```
=-=- Version-specific details -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Fatal error: Invalid character '<' in package version "<none>"
```

Those packages also fails to install, although there is no issue when pinning them to their dev repo.

**Comment by AltGr** [comment]
You're confused with `opam repo` vs `opam pin`:
- `opam pin` is for a single package. Here opam would be creating a package named `repo`
- `opam repo` manages package repositories

You probably want:
```
git clone git://github.com/janestreet/opam-repository js-opam-repo
cd js-opam-repo
opam-admin upgrade-format
opam repo add js .
opam info ppx_optcomp
```

I couldn't reproduce the error, the `pin` command should fail, and did here with:
```
% opam pin add repo js .
opam: opam: Too many arguments.
      Usage: opam pin [OPTION]... add PACKAGE TARGET
```
The `invalid character` error seems worrying too, but I couldn't reproduce.
