### ISSUE TITLE
Don't write to user's shell files

### ISSUE THREAD

**Issue by awalgarg** [ocaml/opam#2800]
Hello :)

I just noticed - opam appends a call to an initialization shell script to my fish shell config on running `opam init`. With the current stable opam release in most major distro's repos (1.2.2), this breaks fish shell (https://github.com/ocaml/opam/issues/2255). I understand that that issue has been fixed. But.. I don't see why opam should automatically write anything to the *user*'s shell configuration file.

Such issues can easily occur even in the future, and recovering from broken shells is kind of a big hassle (because, well, shell is as basic an interface as it gets for many users). I propose that `opam init` only print instructions to initialize the opam environment (which, I believe it does already) and stops touching user's shell configuration file(s).

-- Thanks

**Comment by dbuenzli** [comment]
It's been a long time since I didn't `opam init` but I think that nowadays `opam` politely asks you before fiddling with your files.

**Comment by awalgarg** [comment]
Well, I didn't get any prompts yesterday. I just tried it again setting a
different `OPAMROOT` as well, no prompts. I am on Arch Linux, using the
version of opam in the official repos (1.2.2). Happy to provide any more
information needed :)

**Comment by AltGr** [comment]
Sorry about the `fish` issue; indeed it should now be fixed, but there was no release since, and I know it's quite bad. Seems we were lacking in fish-using beta testers.
This was one of the earliest complaints, though, and the config-file modification operation has since been quite explicit, and off by default:
```
% OPAMROOT=/tmp/foo opam.1.2.2 init
Checking for available remotes: rsync and local, git, mercurial, darcs. Perfect!

=-=- Fetching repository information =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] synchronized from https://opam.ocaml.org

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed base-bigarray.base
∗  installed base-threads.base
∗  installed base-unix.base
Done.

In normal operation, OPAM only alters files within ~/.opam.

During this initialisation, you can allow OPAM to add information to two
other files for best results. You can also make these additions manually
if you wish.

If you agree, OPAM will modify:

  - ~/.zshrc (or a file you specify) to set the right environment
    variables and to load the auto-completion scripts for your shell (zsh)
    on startup. Specifically, it checks for and appends the following line:

    . /tmp/foo/opam-init/init.zsh > /dev/null 2> /dev/null || true


  - ~/.ocamlinit to ensure that non-system installations of `ocamlfind`
    (i.e. those installed by OPAM) will work correctly when running the
    OCaml toplevel. It does this by adding $OCAML_TOPLEVEL_PATH to the list
    of include directories.

If you choose to not configure your system now, you can either configure
OPAM manually (instructions will be displayed) or launch the automatic setup
later by running:

   opam config setup -a


Do you want OPAM to modify ~/.zshrc and ~/.ocamlinit?
(default is 'no', use 'f' to name a file other than ~/.zshrc)
    [N/y/f] 

Global configuration:
  Updating /tmp/foo/opam-init/init.sh
  Updating /tmp/foo/opam-init/init.zsh
  Updating /tmp/foo/opam-init/init.csh
  Updating /tmp/foo/opam-init/init.fish

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

1. To configure OPAM in the current shell session, you need to run:

      eval `opam config env`

2. To correctly configure OPAM for subsequent use, add the following
   line to your profile file (for instance ~/.zshrc):

      . /tmp/foo/opam-init/init.zsh > /dev/null 2> /dev/null || true

3. To avoid issues related to non-system installations of `ocamlfind`
   add the following lines to ~/.ocamlinit (create it if necessary):

      let () =
        try Topdirs.dir_directory (Sys.getenv "OCAML_TOPLEVEL_PATH")
        with Not_found -> ()
      ;;

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

opam 2 further simplified this, since the `.ocamlinit` part is no longer needed. In addition, as it is sensitive, the config-file modification doesn't honor the `--yes` option that other opam commands do.

My only guess is that you copy-pasted init instructions from someone ill-advised who added the `-a` or `--auto-setup` flag, which explicitely does the modification without asking ; that specific flag is still needed in some automatic setup scenarios, e.g. Docker container initialisation.

**Comment by AltGr** [comment]
Another possibility is that you already did the initialisation with an earlier release, that added e.g. `. ~/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true` to your init files; and that file changed with the update of opam, without actually modifying your shell init scripts another time.
