### ISSUE TITLE
Compiling OPAM 1.3 with lib-ext

### ISSUE THREAD

**Issue by clarus** [ocaml/opam#2803]
Hi,

I cannot run:
```
make lib-ext
```
on the `1.3` branch of OPAM (or the `1.3.0` tag). It says:
```
make -C src_ext lib-ext
make[1]: entrant dans le répertoire « /home/guillaume/tmp/opam/src_ext »
[ -e  extlib-1.5.3.tar.gz ] || curl  -OL http://ocaml-extlib.googlecode.com/files/extlib-1.5.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1586  100  1586    0     0   3666      0 --:--:-- --:--:-- --:--:--  3671
ocaml ../shell/md5check.ml extlib-1.5.3.tar.gz 3de5f4e0a95fda7b2f3819c4a655b17c
MD5 for extlib-1.5.3.tar.gz differ:
  expected: 3de5f4e0a95fda7b2f3819c4a655b17c
    actual: a0830b6fd2439ba2e924e08ba9e82a79
mkdir -p tmp
cd tmp && tar xfz ../extlib-1.5.3.tar.gz
tar (child): ../extlib-1.5.3.tar.gz : open impossible: Aucun fichier ou dossier de ce type
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
make[1]: *** [extlib.stamp] Erreur 2
make[1]: quittant le répertoire « /home/guillaume/tmp/opam/src_ext »
make: *** [lib-ext] Erreur 2
```

It seems that the link http://ocaml-extlib.googlecode.com/files/extlib-1.5.3.tar.gz is broken. After fixing it and some other links, I also got various compilation errors. So it seems to me that the dependencies downloaded by `make lib-ext` are not of the correct versions either.

What should I do in order to compile OPAM 1.3 with `make lib-ext`? Is this still the recommended way to do?

**Comment by AltGr** [comment]
Just curious, why do you want the unreleased version 1.3 ? The lib may be useful for migration, but can be installed more easily through `opam install opam-lib`.

The src_ext Makefile on that branch hasn't been updated for a year or so, which explains it became outdated. Nevertheless, I'll look into it.

**Comment by clarus** [comment]
Thanks! I thought that this was a release as there is a GitHub tag `1.3`.
