### ISSUE TITLE
Force packages to be uploaded over HTTPS

### ISSUE THREAD

**Issue by DemiMarie** [ocaml/opam#2804]
We should force packages to be uploaded over HTTPS, and/or signed with digital signatures, the public keys (or fingerprints thereof) of which are forced to be uploaded over HTTPS.

**Comment by AltGr** [comment]
Note: we are currently developping an end-to-end signing layer for opam;
even in the current state, though, opam will always validate the checksums of downloaded archives, so https doesn't really matter. The default repository (opam.ocaml.org), even if not yet signed, is served over https and updated through github, following its auth mechanisms.
