### ISSUE TITLE
opam list in silent more needs to be more silent

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#2805]
```
opam list -s --color=never --depends-on cfgen.1.0 --installable
```

outputs

```
# no matches found
```

which is a bit tricky for scripting -- ideally it would output nothing as opam 1.2 did.

**Comment by AltGr** [comment]
Indeed, will fix that (even in non-silent mode, the message should probably be printed to stderr).

**Comment by avsm** [comment]
this works great now, thanks!
