### ISSUE TITLE
depext broken on opam2

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#2806]
has the semantics of `external` changed in opam2? Looks like depext needs porting, as the format of the output of `opam list` has also changed.

E.g. below, the `m4` dependency is not output (it is on the equivalent opam1.2 cmdline)

```
$ opam list --safe --recursive --external=x86_64,linux,alpine --required-by=lwt.2.7.0
# Packages matching: (installed | available) & rec-required-by(lwt.2.7.0)
~/src $ opam list --safe --recursive --required-by=lwt.2.7.0
# Packages matching: (installed | available) & rec-required-by(lwt.2.7.0)
# Name         # Installed # Synopsis
base-bigarray  base        Bigarray library distributed with the OCaml compiler
base-threads   base        Threads library distributed with the OCaml compiler
base-unix      base        Unix library distributed with the OCaml compiler
lwt            --          Monadic promises and concurrent I/O
ocaml          4.02.3      The OCaml compiler (virtual package)
ocaml-system   --          The OCaml compiler (system version, from outside of opam)
ocaml-variants --          OCaml 4.05.0 with -safe-string enabled.
ocamlbuild     0           Build system distributed with the OCaml compiler since OCaml 3.10.0
result         --          Compatibility Result module
```

**Comment by AltGr** [comment]
IIRC, opam 1.2.2 would merge the depexts for all the existing versions of the rec-dependencies, while opam 2 only chooses the best one, which probably explains the difference.

**Comment by AltGr** [comment]
(note: that's done without ensuring a consistent installation, though, for that you need `--resolve`)

**Comment by AltGr** [comment]
Would you expect/prefer the old behaviour in this case ? (union of the depexts of all the versions of all the dependencies ?)

**Comment by avsm** [comment]
It seems to make sense to pick the smallest set, and fix up the repo for opam1 support. However, would the depext set be guaranteed to match the package set actually installed by `opam install`?

**Comment by AltGr** [comment]
The issue there is that what `opam install` does may depend on the context.
Using `--resolve` instead of `--rec --required-by` should get you as close as possible, though:
```
opam list --safe --resolve lwt.2.7.0 --external x86_64,linux,alpine
```
