### ISSUE TITLE
opam2: misleading constraint failure with unavailable package

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#2808]
```
The following dependencies couldn't be met:
  - mirage-types-lwt -> mirage-kv-lwt
    unmet availability conditions: ocaml-version >= "4.01.0"
```

it turns out that mirage-kv-lwt didnt exist as a package, so it was nothing to do with ocaml-version

Dockerfile to generate this was:

```
FROM ocaml/opam-dev:ubuntu-16.04_ocaml-4.03.0
RUN printf '#!/bin/sh\n\nif ! opam install $1 --dry-run; then\n  echo Package unavailable, skipping.\n  exit 0\nfi\necho opam depext -ivyj 2 $1\nopam depext -ivyj 2 $1 || exit 1\n' > /home/opam/opam-ci-install && chmod a+x /home/opam/opam-ci-install && sudo mv /home/opam/opam-ci-install /usr/bin/opam-ci-install
RUN opam remote add e1 https://github.com/mirage/mirage-dev.git#adfedb4c9f85ce697a9e8262a46b9a9f1fd7f03e
WORKDIR /home/opam/opam-repository
RUN git checkout master
RUN git remote set-url origin git://github.com/mirage/opam-repository
RUN git fetch origin master:cibranch
RUN git branch -D v2
RUN git checkout -b v2 5d29ce2cb3bee331a3ff4c5905ae1219d83cc20a
RUN opam admin upgrade-format
RUN git add .
RUN git commit -a -m 'upgrade format to opam2'
RUN git clone git://github.com/mirage/mirage /home/opam/src
WORKDIR /home/opam/src
RUN git fetch origin heads/master:cibranch
RUN git checkout 54a81be9b065f6635dee12188391096b92a33fd1
RUN opam pin add -n mirage /home/opam/src
RUN opam pin add -n mirage-types /home/opam/src
RUN opam pin add -n mirage-types-lwt /home/opam/src
RUN opam update -uy
RUN opam-ci-install mirage
```

**Comment by AltGr** [comment]
The package exists, it just wasn't at the right place (but until now, opam actually doesn't care at all about the `**` in `<repo>/packages/**/<name>.<version>/opam` ; that should be changed before we switch to a signed repo, though)

See https://github.com/mirage/mirage-dev/blob/adfedb4c9f85ce697a9e8262a46b9a9f1fd7f03e/packages/mirage-kv/mirage-kv-lwt.1.0.0/opam

**Comment by samoht** [comment]
> The package exists, it just wasn't at the right place

can we try to not change that? This will probably break a lot of custom opam repositories... Also, it will make sense, at one point to move the current layer of opam-repository into something more scalable, e.g. by adding an other layer of indirection (for instance by grouping all packages starting by `a` under`a/`, etc).

**Comment by samoht** [comment]
Also I really want to be able to sort my packages in the way I want: for instance, I started to regroup them by the repository where they come from, to help the future release of Mirage3.

**Comment by avsm** [comment]
My original point in this issue wasnt the unavailable package -- it was that the error message was wrong.

```
unmet availability conditions: ocaml-version >= "4.01.0"
```

**Comment by AltGr** [comment]
Hm; it seems I wasn't clear, sorry:
- the package definition is seen by opam
- the error message is correct, according to the definition that was found (see link in my previous comment)

The part about the repository hierarchy was just my guess to explain that you figured that "mirage-kv-lwt didnt exist as a package", while in fact it existed, just in a place where you might have missed it.

Then I got on to the part about enforcing a repository hierarchy for signed repos but that  was actually unrelated to the issue, or any actual changes in opam 2 to date.
