### ISSUE TITLE
varying ocaml-version constraint based on compiler variants

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#2810]
We have an increasing number of compiler variants such as flambda, and some packages require a specific variant or do not compile in one.

For instance, ocamlnet.4.1.2 fails to compile in +flambda. Is there any way to specify this in the constraints right now? 

```
available: [ ocaml-version >= "4.00.0" & ocaml-version != "4.03.0+flambda" & ocaml-version != "4.04.0+flambda" ]
```

doesnt work, as the +flambda is filtered from ocaml-version.

**Comment by AltGr** [comment]
You could use the `compiler` variable, IIRC (see `opam config list`)
In opam 2, of course, you have the full expressivity of dependencies and conflicts to handle that.

**Comment by avsm** [comment]
but in opam2, is there any way to mark all flambda compilers as conflicts? we dont have wildcards for this do we?

**Comment by AltGr** [comment]
No, we'll need proper `provides:` support for this.

Here we are abusing the versionning ordering to classify by corresponding compiler version (e.g. have all versions start with `4.04.0`) ; this allows us to have the package `ocaml.4.04.0` depend on `ocaml-core-compiler {= 4.04.0} | ocaml-variants {>= 4.04.0 & < 4.04.1~~}`

This can obviously only be used for one-way indexing, though.
Provides would allow to have all flambda variants provide a feature, and then conflict with that feature. But it actually allows us to do better, that is, separate the flambda variant in its own package, that provides e.g. `ocaml-variants`, which would be the cleaner option. The reason that can't be done now is that we would need to be completely explicit to make all compiler variants conflict with each other.

There is, as usual, one dirty hack you could use with dummy packages: if you make your implementations of flambda depend on a dummy package, then they will transitively conflict with any package in conflict with that dummy. Far from pretty...

**Comment by AltGr** [comment]
Wondering if a preliminary implem of `provides:` that can only be referenced from `conflicts:` would be useful here. And if that really avoids the truckful of problems that `provides:` generally arises.
Maybe worth trying for 2.1.

**Comment by avsm** [comment]
> There is, as usual, one dirty hack you could use with dummy packages: if you make your implementations of flambda depend on a dummy package, then they will transitively conflict with any package in conflict with that dummy. Far from pretty..

that's not too bad -- just need to make it work with the automatic translation, or could just wait until the cutover.

**Comment by AltGr** [comment]
See #2827 for the idea above.
It would allow to separate specific compiler variants without too much metadata overhead, but even without doing that, could allow a `flambda` conflict-class to be easily defined.
