### ISSUE TITLE
source archive unpacking results in differing dependencies within builds

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#2814]
Trying to build ocamlgraph 1.8.7 in opam1 and opam2 is failing in opam2 on some machines due to:

```
#=== ERROR while compiling ocamlgraph.1.8.7 ===================================#
# command              make
# path                 /home/opam/.opam/ocaml-variants.4.04.0+flambda/.opam-switch/build/ocamlgraph.1.8.7
# exit-code            2
# env-file             /home/opam/.opam/log/ocamlgraph-20-f1d79c.env
# output-file          /home/opam/.opam/log/ocamlgraph-20-f1d79c.out
### output ###
# autoconf
# make: autoconf: Command not found
# make: *** [Makefile:610: configure] Error 127
```

this seems to be because the `configure: configure.in` rule in the Makefile of the archive detects that the `configure` script is out of date.  It seems that OPAM2 unpacks the archive differently into the build dir from OPAM1, since it doesn't happen there.  A workaround is `touch configure` in this packages case.

**Comment by AltGr** [comment]
opam 2 extracts to a temp dir, then copies over, which would explain the changed timestamps.
We should probably add `--preserve=timestamps` to our copy command. That's not POSIX though, so might as well use `-p` which is and also preserves ownership and permissions.

**Comment by AltGr** [comment]
Please close if you can confirm it's solved!

**Comment by avsm** [comment]
confirmed fixed, thanks!
