### ISSUE TITLE
2.0: Local cancelled switches

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2847]
On 2.0~beta: If I use `opam build` which creates a local switch but I then refuse the solution computed by the solver, it doesn't create a local `.opam` directory but it adds a switch in `.opam/config`.

**Comment by AltGr** [comment]
Are you sure `_opam` didn't get created ? It's an underscore, and not a dot.
Just removing `_opam` should be fine in any case, local switches have been designed to handle it as switch remove implicitely.

**Comment by Drup** [comment]
@AltGr Yeah, it wasn't there (note that this was before https://github.com/ocaml/opam/pull/2848), so maybe everything is better now. The problem was more that it was still visible in `opam switch list`.

**Comment by AltGr** [comment]
Should be solved. `opam switch list` will always filter the "local" switches that were manually removed, in any case.
