### ISSUE TITLE
Opam filesystem check is a bit slow

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2857]
Opam 2.0 now registers the content that each package installs on the file system. The check for that seems to be a bit slow. In particular when you have a large set of libraries (in one of my switches, 2Go of cm* files ...)
and you don't have an SSD.

**Comment by AltGr** [comment]
Should now be much faster. If you can report your impressions... :)

**Comment by Drup** [comment]
It looks like it's much faster indeed! I think we can close for now.
