### ISSUE TITLE
Document the `%{dev}%`, `%{pinned}%` and `%{test}%` variables.

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#2865]
Beyond this it would be nice to have a section in the manual that lists all available built-in variables and variable patterns (by which I mean `PKG:lib`).

**Comment by AltGr** [comment]
Yes; the easiest way to get the list now is `opam config list`. `opam config list <PKG>` also works.

**Comment by AltGr** [comment]
Fixed by 4170148
