### ISSUE TITLE
is there a way to tell opam to install every package that is installable?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#2866]
In order to be able to index all the .mli file that are installable.
opam install '*' ?

**Comment by dbuenzli** [comment]
You need to find consistent cuts on the package universe. If I'm not mistaken @dsheets gave some thinking to this in the past and may have an algorithm to propose.

**Comment by UnixJunkie** [comment]
cc @abate who I suspect might know how to do this

**Comment by AltGr** [comment]
```
opam upgrade --criteria='+count(solution)'
```
Of course, this will only install every package that is installable _at the same time_.
Another solution with opam2 is to get the set of installable packages (`opam list --installable` ¹) ; then use `opam install --soft-request <that set>`; then iterate on the remainder. The script at `admin-scripts/couverture.ml` did something like that, but may need updating.

¹ A note of caution: this depends on your current switch's base packages (unless `--no-switch`)

**Comment by UnixJunkie** [comment]
@AltGr thanks, time to give a try at opam2 then!

**Comment by UnixJunkie** [comment]
opam2 is notably faster than opam-1.2.2 to install packages. I am happily surprised.

**Comment by Drup** [comment]
(On the more general topic, there is some academic litterature on the subject by @rdicosmo and others, I think the first article is [this one](http://dicosmo.org/Publications/CoinstTosem2013.html))

**Comment by rdicosmo** [comment]
Thanks Gabriel for pinging me in

The short answer is: use a preference expression starting with

    +count(solution)
    
More details here
   https://opam.ocaml.org/doc/Specifying_Solver_Preferences.html

On Wed, Mar 01, 2017 at 09:11:33AM -0800, Gabriel Radanne wrote:
> (On the more general topic, there is some academic litterature on the subject
> by @rdicosmo and others, I think the first article is this one)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Roberto Di Cosmo
 
------------------------------------------------------------------
Professeur (on leave at/detache a INRIA)
IRIF                          E-mail : roberto@dicosmo.org
Universite Paris Diderot         Web : http://www.dicosmo.org
Case 7014                    Twitter : http://twitter.com/rdicosmo         
5, Rue Thomas Mann       
F-75205 Paris Cedex 13 France  
------------------------------------------------------------------
Office location:

Paris Diderot                       INRIA
 
Bureau 3020 (3rd floor)             Bureau C123
Batiment Sophie Germain             Batiment C
8 place Aurélie Nemours             2, Rue Simone Iff
                                    Tel: +33 1 80 49 44 42 

Metro
  Bibliotheque F. Mitterrand        Ligne 6: Dugommier
  ligne 14/RER C                    Ligne 14/RER A: Gare de Lyon
------------------------------------------------------------------                                                 
GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3

**Comment by dbuenzli** [comment]
A bit related it would be nice to have easy and high-level commands to try to install *some kind of* (let's say that tries to respect your current universe) maximal set of the reverse dependencies. 

For example nowadays I can no longer do a `opam install $(opam list -s --depends-on cmdliner)` as the resulting universe is totally inconsitent in a way that can only be understood by a machine. No easy filtering can be done on the `list` to get to an consistent one.

**Comment by UnixJunkie** [comment]
Not a command line tool, but this URL can tell you which packages
depend on yours (for each version of yours); cf. right column at:

https://opam.ocaml.org/packages/cmdliner/

**Comment by AltGr** [comment]
@dbuenzli: add `--soft-request`to your command to do just that!
If you have an idea for a better name

**Comment by dbuenzli** [comment]
@Altgr Aha `opam` v2 I presume ! Not there yet but that sounds nice.

Regarding the name I'm not sure I have a better one. But here a few two: 

```
--best-effort
--allow-partial
```

**Comment by AltGr** [comment]
`--best-effort` maybe?

**Comment by dbuenzli** [comment]
> --best-effort maybe?

If that's an accurate description of what happens I would go for it.

**Comment by dbuenzli** [comment]
I'm sure I would remember it better than `--soft-request`: simply try to do the best you can `opam`.

**Comment by AltGr** [comment]
`--best-effort` is a very good first step for that. Getting consistent cuts of the package universe can then be done with a bit of shell scripting, and a greedy algorithm:

```bash
# Get the list of all installable packages
opam list -as | sort >allpkgs
# Install them (with --best-effort, or we would just get a conflict)
opam install --best-effort $(cat allpkgs)
# Get the remaining uninstalled packages
comm -23 allpkgs <(opam list -s | sort) >allpkgs2
# And iterate from step 2
opam install --best-effort $(cat allpkgs2)
comm -23 allpkgs2 <(opam list -s | sort) >allpkgs3
# etc.
```
You may want to tweak the criteria to avoid recompiling packages (e.g. minimise the solution size with `-sum(request,version-lag),-count(solution)` on aspcud). Also, this assumes packages actually get installed: it will retry packages that were in the cut but failed to install.
Also note that, while this will attempt to use recent versions of the packages, but gives no guarantee about using the latest ones.

A better solution, that doesn't depend on the packages successfully installing, would be to generate the cuts beforehand. You could do it with the commands above, in a dummy switch, by using `--fake`, but this is a little heavy. Another solution would be to use `--json log.json` and parse the installation set:

```bash
PACKAGES=($(opam list -as | sort))
i=0
while [ $i -eq 0 ] || [ "$(cat cut_$i)" != "" ]; do
  i=$((i+1))
  opam install ${PACKAGES[*]} --best-effort --show --json /tmp/opamlog.json
  jq -r '.solution | map(select(has("install")) | "\(.install.name).\(.install.version)") | join("\n")' /tmp/opamlog.json | sort >cut_$i
  PACKAGES=($(IFS=$'\n'; comm -23 <(echo "${PACKAGES[*]}") <(sed 's%\..*%%' cut_$i)))
done
```

On 4.02.3 I get 8 cuts:
```
$ wc -l cut_*
 1361 cut_1
  292 cut_2
  155 cut_3
  108 cut_4
  119 cut_5
   65 cut_6
   60 cut_7
   41 cut_8
```


(note that `--best-effort` is currently broken on the built-in solver (#3063). Use `--solver aspcud` until it's fixed)
