### ISSUE TITLE
Switch installations fails on Solus

### ISSUE THREAD

**Issue by hdcos** [ocaml/opam#2872]
I downloaded a precompiled binary for opam because it could not install with the script and then after init and update did the following : ` opam switch 4.02.3+buckle-master`

I have gcc 6.3.0 installed on my machine but I get the following :

```
=-=- Installing compiler 4.02.3+buckle-master -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default.comp] https://github.com/bloomberg/ocaml/archive/master.zip downloaded
Now compiling OCaml. This may take a while, please bear with us...
[ERROR] Compiler build failed at "./configure -prefix /home/hdcos/.opam/4.02.3+buckle-master -with-debug-runtime":
        # opam-version 1.2.2
        # os           linux
        # command      ./configure -prefix /home/hdcos/.opam/4.02.3+buckle-master -with-debug-runtime
        # path         /home/hdcos/.opam/4.02.3+buckle-master/build/ocaml
        # exit-code    2
        # env-file     /home/hdcos/.opam/log/log-25276-1872ec.env
        # stdout-file  /home/hdcos/.opam/log/log-25276-1872ec.out
        # stderr-file  /home/hdcos/.opam/log/log-25276-1872ec.err
        ### stdout ###
        # Configuring for host x86_64-unknown-linux-gnu ...
        # Configuring for target x86_64-unknown-linux-gnu ...
        # Using compiler gcc.
        # [ERROR!] Unable to compile the test program.
        #  Make sure the C compiler gcc -O  is properly installed.

```

**Comment by AltGr** [comment]
This is not an issue with opam, but maybe with OCaml itself, or with its definition in the repository. Please submit where appropriate, thanks! (ocaml/ocaml or ocaml/opam-repository)

**Comment by beajeanm** [comment]
I'm a bit late to the party, but in case somebody (like me) found that issue:
OCaml compilers and many packages have native dependency that are not managed by opam. For Solus, I was able to be up and running after installing the following packages:
binutils gcc libevdev-devel glibc-devel ncurses-devel linux-headers make m4 patch

(This is for installing ocaml 4.05.0 compiler + utop)
