### ISSUE TITLE
Provide a way to bypass dependency constraints

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam#2873]
Following a discussion with @mshinwell

Sometimes you want to temporarily bypass version constraints to test compatibility of packages, e.g. with different compiler version. A new option `--ignore-constraints-on <package>` would be useful for that purpose.

For example, `opam install foo --ignore-constraints-on ocaml` would try to install `foo` normally, but on a package universe where all dependencies towards `ocaml` have had their version constraints stripped, practically meaning that any currently installed version of `ocaml` will be accepted.

**Comment by dbuenzli** [comment]
@AltGr Would it be reflected in the resulting switch state ? If not, we are in for support nightmare.

**Comment by AltGr** [comment]
As I was thinking it, the changed dependencies wouldn't be registered, which means that any further `opam install` or `opam upgrade` would want to "repair" the state by removing or changing the versions of packages with broken constraints. Unless you specify the option again, of course. This is OK if all you want was to test the build of the package...

Having this enabled for a longer run seems like a bad idea, support wise; we can support environment variables like for other options, of course, but anything stored in the switch state should be done explicitely through pinnings. For something more durable, another option is a script that wipes dependency constraints from a repository, letting you use your modified local mirror.

**Comment by dbuenzli** [comment]
> Having this enabled for a longer run seems like a bad idea

Yes my worry is that people come to us with problems in their repos and that we are not able to see that they actually did `ignore-constraints-on` packages.

**Comment by Drup** [comment]
Isn't `opam pin edit foo.1.2.3` sufficient for this use case ?

**Comment by dbuenzli** [comment]
@Drup that may not be enough no ? (recursive deps that also have the constraint).
