### ISSUE TITLE
opam-publish gives different results on different computers

### ISSUE THREAD

**Issue by agarwal** [ocaml/opam#2881]
On one computer:
```
$ opam-publish prepare cfstream.1.2.2 https://github.com/biocaml/cfstream/archive/1.2.2.tar.gz
$ grep solvuu-build cfstream.1.2.2/opam 
  "solvuu-build" {build & >= "0.1.0"}
```

On another computer:
```
$ opam-publish prepare cfstream.1.2.2 https://github.com/biocaml/cfstream/archive/1.2.2.tar.gz
$ grep solvuu-build cfstream.1.2.2/opam 
  "solvuu-build" {build & >= "0.3.0"}
```

Note the version constraint in the latter is the correct one. Any idea how this is possible? We thought the output of opam-publish depends only on the tarball?

**Comment by AltGr** [comment]
No, opam-publish tries to find the correct package definition from the "best" source it can, including the locally pinned-to definition. This is useful for first testing your package using `opam pin`, then publishing the same version you have been validating (it is common to want a slightly different opam file in the git repo and on opam-repository, although new stuff like `dev` dependencies tend to make it possible to avoid that)

**Comment by agarwal** [comment]
Ok, thanks for the explanation. So I'll close this issue.
