### ISSUE TITLE
opam2: opam config subst changes directory too early

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#2888]
from build of vpnkit.0.0.0:

```
# fatal: Not a git repository (or any of the parent directories): .git
# [ERROR] No package matching hostnet found
# [ERROR] No printer for "pinned"
# opam config subst src/bin/depends.ml || true
# Fatal error:
# OpamSystem.File_not_found("/home/opam/.opam/src/bin/depends.ml.in")
# cp src/bin/depends.ml src/bin/depends.tmp
# cp: cannot stat 'src/bin/depends.ml': No such file or directory
# Makefile:31: recipe for target 'src/bin/depends.ml' failed
# make: *** [src/bin/depends.ml] Error 1
```

@altgr diagnoses this as an opam2 regression: 
> I recently added a forced Sys.chdir to opamroot, to avoid issues when CWD got removed during the opam run
> (typically when running from a temp build dir, which does happen when debugging opam packages)  
> but it seems `config subst` resolves the file names _after_ that happened

cc @djs55

**Comment by AltGr** [comment]
Fixed
