### ISSUE TITLE
opam pin add URL_OR_PATH_TO_TARBALL

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#2892]
Hello,
Can't we do that?
Especially, if the tarball contains an opam file, I'd like opam to not ask me
to create an opam file (which is currently what opam-1.2.2 is trying to do).
Thanks,
F.

**Comment by AltGr** [comment]
You can do that, at least in `2.0` ; the only limitation is that you have to specify the package name manually in this case, e.g. `opam pin NAME TARBALL_URL`
