### ISSUE TITLE
missing descriptions of the meaning of opam exit codes

### ISSUE THREAD

**Issue by matejkosik** [ocaml/opam#2894]
When I type
```
man opam install
```
I do not see a section that would describe all the exit codes that `opam install` process can provide and what do they mean.

E.g., is it possible to discriminate between "download failure" and "compilation failure"?

This is not a problem if `opam` program is used by humans because the corresponding messages appear in the `std{out,err}` but when we want to include `opam` into scripts, we may want to rely on these exit codes. If they are undocumented/unofficial, the scripts themselves are fragile and possibly incorrect.

**Comment by avsm** [comment]
Agreed it would be useful to have this documented for OPAM2 -- the CI could use it as well.

**Comment by dbuenzli** [comment]
Note that `cmdliner 1.0.0` has support to document them, see the `exits` argument [here](http://erratique.ch/software/cmdliner/doc/Cmdliner.Term.html#VALinfo).

**Comment by AltGr** [comment]
Now fairly consistent and well documented.
