### ISSUE TITLE
OPAM does not handle custom Homebrew install locations

### ISSUE THREAD

**Issue by sdevlin** [ocaml/opam#2905]
On macOS, OPAM (optionally?) uses Homebrew to manage external dependencies. Homebrew installs in /usr/local by default. OPAM does not seem to handle custom install locations. For example:

    $ opam install frama-c
    The following actions will be performed:
      ∗  install conf-gmp     1                   [required by zarith]
    ...
    #=== ERROR while installing conf-gmp.1 ========================================#
    # opam-version 1.2.2
    # os           darwin
    # command      sh -exc cc -c $CFLAGS -I/usr/local/include test.c
    ...
    =-=- conf-gmp.1 troobleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    => This package relies on external (system) dependencies that may be missing. `opam depext conf-gmp.1' may help you find the
       correct installation for your system.
    ...
    $ opam depext conf-gmp.1
    # Detecting depexts using flags: x86_64 osx homebrew
    # The following system packages are needed:
    #  - gmp
    # All required OS packages found.
    $ brew --prefix
    /opt/brew

OPAM should probably insert `brew --prefix` in the include path.

**Comment by AltGr** [comment]
I am not sure if opam (apart from depext handling) should interfere with homebrew, or other packaging systems. Shouldn't the user had `brew --prefix` to her PATH ?

Thanks for reporting — and sorry for the lag!

**Comment by rjbou** [comment]
Is this still an issue ?

**Comment by rjbou** [comment]
Closing, feel free to reopen if needed. Thanks!
