### ISSUE TITLE
opam doesn't know how to remove a package if its definition is removed from the original opam repository

### ISSUE THREAD

**Issue by hcarty** [ocaml/opam#2908]
It would be helpful if opam could, somehow, always keep package definitions around for installed packages, even if they are removed from any available repos.  This would avoid the problem of having a package definition removed from the official repo breaking existing opam installations using the removed package/package version.

**Comment by AltGr** [comment]
It's the case in opam 2.0 :)

**Comment by avsm** [comment]
we've generally tried to be cautious in removing packages in the mainline opam repository, but maintainers do have the right to request that an explicitly broken package be removed. If there's a particular package removal that is causing issues, do feel free to flag it up in the relevant PR as well so we can reconsider the removal.

**Comment by hcarty** [comment]
@AltGr Very cool, thank you! Apologies for the noise.

@avsm That all makes sense, thank you
