### ISSUE TITLE
is there way to discard of upgrading other packages during installation?

### ISSUE THREAD

**Issue by mryau** [ocaml/opam#2909]
I'm use OCaml cross-compiler and patched versions of some packages.
During  installation of customised *ppx_tools*, OPAM requires to upgrade *oasis* package:
```
ssp@ssp-vb:/mnt/ssp/ppx_tools-4.02.3$ opam pin add arm-ppx_tools .
Package arm-ppx_tools does not exist, create as a NEW package ? [Y/n] y
arm-ppx_tools is now path-pinned to /mnt/ssp/ppx_tools-4.02.3

[arm-ppx_tools] /mnt/ssp/ppx_tools-4.02.3/ synchronized
[arm-ppx_tools] Installing new package description from /mnt/ssp/ppx_tools-4.02.3

arm-ppx_tools needs to be installed.
The following actions will be performed:
  ↗  upgrade oasis         0.4.4-1 to 0.4.8
  ∗  install arm-ppx_tools *               
===== ∗  1   ↗  1 =====
Do you want to continue ? [Y/n] 
```
But opam file from arm-ppx_tools does not require new version of oasis, moreover, I want to live with this specific and patched version of oasis.
How can I cancel request to upgrade such packages?

**Comment by AltGr** [comment]
You have a few options for this:
- run `opam install arm-ppx_tools oasis.0.4.4-1` explicitely
- specifically pin `oasis` to your version beforehand with `opam pin add oasis 0.4.4-1` (I assume you patched it without pinning to source? That might have been an easier way)
- change the solver criteria, e.g. `--criteria=paranoid`. See http://opam.ocaml.org/doc/Specifying_Solver_Preferences.html
