### ISSUE TITLE
opam2: more flexible config selection

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#2917]
The containers in https://hub.docker.com/r/ocaml/opam-dev/ for OPAM2 install wrapper scripts for activating sandboxing, in /etc/opamrc.userns. They are not activated by default as they require privileged containers to work.

It would be useful in the CI to select this config file dynamically per `opam` invocation, without having to cp the file into `/etc/opamrc`.  It would be even more useful if there was a per-switch `opam config` call that could set the relevant fields for a given switch, so that a single opam installation could run a differential test with and without the sandboxing.

In general, a CLI interface for manipulating the scoped config options would be useful to have, as some might be set on a switch level, a per-user level (~/.opamrc) or a global level (/etc/opamrc).

**Comment by AltGr** [comment]
https://github.com/ocaml/opam/pull/2916/commits/c38b73af83ef20b39a5ce93868d4d00435a01c61 may already help a tiny bit (but remains a global `opam init` option)

**Comment by AltGr** [comment]
a generic CLI tool for editing opam-syntax files might be an idea too

**Comment by dra27** [comment]
I think #2930 may also be part of the journey towards this?

**Comment by AltGr** [comment]
`opam init --config` is now extended a bit, and supports URLs. I think the other usability issues gathered here are tracked separately (switch-defaults #2930 ; supporting specifying global/switch options without having to edit the files is a more general concern)
