### ISSUE TITLE
opam init -a should recommend another shell syntax

### ISSUE THREAD

**Issue by zapashcanon** [ocaml/opam#2925]
Hi,

When running `opam init -a`, the output contains:

``` sh
# To setup the new switch in the current shell, you need to run:
eval `opam config env`
```

It should be:

```sh
# To setup the new switch in the current shell, you need to run:
eval $(opam config env)
```

See [this explanation](https://github.com/koalaman/shellcheck/wiki/SC2006).

**Comment by dra27** [comment]
Both syntaxes are valid POSIX, and you're really not going to hit the nesting issues which can plague backtick command quoting. However, there are users whose default shell doesn't support `$()` (I believe Solaris 10 doesn't, from a quick Google).

On the basis that it's less typing and, even in 2017, we'd have to add code to detect whether `$()` is actually valid, I'd say it's best left as it is.

**Comment by AltGr** [comment]
Ah, I had been wanting to do this for a while (I only ever use `$()` myself, and backticks are more annoying to type on some exotic non-english keyboards) -- and actually did in 42913bc30bd7cb356ad17ccfa5ea95fb54366e73 -- but I didn't know about Solaris 10. Should I revert ?

Note that we already detect the shell, and have a different escape for `fish`, so reverting to backticks on plain `sh` only would be just one line (except in the manpages, but who cares).

**Comment by dbuenzli** [comment]
> and backticks are more annoying to type on some exotic non-english keyboards

And write in markdown...

> Should I revert ?

Since it's valid POSIX I would say no.

**Comment by AltGr** [comment]
> And write (or c&p) in markdown...

They were more annoying to write in the Cmdliner man syntax though ;)

**Comment by dbuenzli** [comment]
> They were more annoying to write in the Cmdliner man syntax though ;)

If you talk about the `$` I would even say that the behaviour used to be close to random. `cmdliner` 1.0.0 fixed that see [here](http://erratique.ch/software/cmdliner/doc/Cmdliner.html#doclang).

**Comment by AltGr** [comment]
Yes yes, I have made sure to use the 1.0.0 syntax. I should probably update the `cmdliner` version requirement, though, we're still advising 0.9.8.

**Comment by zapashcanon** [comment]
@AltGr, I looked at 42913bc, it looks like one character hasn't been removed, I hl you on the commit.
