### ISSUE TITLE
`findlib` files in package metadata should be documented or removed

### ISSUE THREAD

**Issue by whitequark** [ocaml/opam#2948]
Everyone can see these files in the OPAM repository. However, no one knows what function they serve. They are [not documented in manual](https://opam.ocaml.org/doc/Manual.html#Packagespecification), [not mentioned in packaging documentation](https://opam.ocaml.org/doc/Packaging.html), [do not support optional findlib packages](https://github.com/ocaml/opam/issues/2187) and do not even bother to list these, as in case of [lwt](https://github.com/ocaml/opam-repository/blob/master/packages/lwt/lwt.2.5.2/findlib). Thus I posit that there is no such function nor they even *can* meaningfully serve any function.

Multiple times (#2187, #2254) people have asked for clarification on the mechanism behind the findlib files but @AltGr has carefully avoided giving any clarification on that part, going as far as silently closing #2187 as he is wont to do.

Well, I would like to finally have an answer on this, because one of the contributors to opam-cross-android says that the lack of `findlib` files [breaks something](https://github.com/whitequark/opam-cross-android/pull/33#discussion_r118680664) yet I don't see any reason why that would be the case, nor is the presence of `findlib` files even appropriate there because opam-cross-android does not install into `%{lib}%`.

cc @dbuenzli @Chris00 who were similarly mystified

**Comment by dra27** [comment]
Looking at the code, I think this may be more one for @samoht?

Virtually everything to do these with these files has been deleted in opam2.

**Comment by avsm** [comment]
It serves no function in OPAM1 for the main package repository, and CI does not test anything to do with them.  I have no objection to removing these files from the main repository.

**Comment by whitequark** [comment]
@avsm https://github.com/ocaml/opam-repository/issues/9328

**Comment by lpw25** [comment]
For reference: IIRC these files were used by [the old opam-doc prototype](https://github.com/lpw25/opam-doc) for determining which findlib libraries corresponded to which packages. In the newer documentation work this role is handled by odig which does not rely on these files. I think they were also intended to allow some opam support for finding which package contained a particular library but that never materialised.

**Comment by AltGr** [comment]
I confirm that they have no purpose, and are not used in any way, by the opam tool itself.
They may have a use for some external tools, though.

**Comment by whitequark** [comment]
Thanks @AltGr @lpw25 @avsm!

**Comment by Chris00** [comment]
`oasis2opam` uses them to determine which findlib libraries are provided by an opam package—there is no certain way to do that when the package is not installed.  Now that OPAM is widely deployed, it would be IMHO good if there would only be two layers: opam packages providing one or several OCaml libraries (`.cma`, `.cmxa`, `.cmxs`,...).

**Comment by whitequark** [comment]
@Chris00 I'm not especially convinced, for example, the OCaml packages in Debian do not go through opam.

**Comment by Chris00** [comment]
But they use *ocamlfind* — so *opam* could become a dependency instead of *findlib*.  Of course, that may require *opam* to have a few additional capabilities (like being able to consider packages coming from the system) but, especially with the trend towards the removal of optional dependencies, opam package dependencies will closely match findlib ones (and `.install` files give locations and could slowly become mandatory).  I think it is a good time to revisit the idea of having less layers in our build systems.

**Comment by whitequark** [comment]
> especially with the trend towards the removal of optional dependencies

Which trend?

**Comment by Chris00** [comment]
https://discuss.ocaml.org/t/ann-cstruct-3-0-0-with-packaging-changes/284
