### ISSUE TITLE
opam init fails with Permission denied error on msys2

### ISSUE THREAD

**Issue by cr1901** [ocaml/opam#2950]
I have successfully compiled `opam` from github source using commit 6ccd57e. Compilation runs without error. However, when initializing `opam`, I receive the following error:

```
William@William-THINK MINGW32 ~/src/opam
$ opam init
[NOTE] Will configure from built-in defaults.
Checking for available remotes: rsync and local, git.
  - you won't be able to use mercurial repositories unless you install the hg command on your system.
  - you won't be able to use darcs repositories unless you install the darcs command on your system.

[WARNING] No external solver found, one of aspcud, packup and mccs is recommended (see http://opam.ocaml.org/doc/Install.html#ExternalSolvers for details)
[ERROR] Initialisation failed
Sys_error("Permission denied")
C:\msys64\home\William\.opam\config.lock - The process cannot access the file because it is being used by another process.
C:\msys64\home\William\.opam\lock - The process cannot access the file because it is being used by another process.
C:\msys64\home\William\.opam\repo\lock - The process cannot access the file because it is being used by another process.
C:\msys64\home\William\.opam\repo\state.cache - The process cannot access the file because it is being used by another process.
Fatal error:
Sys_error("Permission denied")

William@William-THINK MINGW32 ~/src/opam
$ opam config report
# opam config report
# opam-version    2.0.0~beta3 (6ccd57e3763bdebde18c3b0f48978631a832ce6a)
# self-upgrade    no
# os              win32
[ERROR] No switch is currently set. Please use 'opam switch' to set or install a switch
# read-state      OpamStd.OpamSys.Exit(66)

William@William-THINK MINGW32 ~/src/opam
$ ocaml -version
The OCaml toplevel, version 4.04.0
```

Installing Cygwin is _not_ an option for me.

**Comment by dra27** [comment]
The master branch of opam only runs in Cygwin at the moment, so if Cygwin really isn't an option then I'm afraid neither's opam. I think from that message you have compiled opam using i686-w64-mingw32-gcc rather than MSYS2's internal gcc? The latter might work, although I don't know how well opam-repository would adapt to msys2's internal environment vs Cygwin.

I'm working on a native Windows port of opam in https://github.com/dra27/opam/tree/windows, which is the process of being merged. That said, while supporting MSYS2 is on the list, there're other things above it!

**Comment by cr1901** [comment]
@dra27 
>I don't know how well opam-repository would adapt to msys2's internal environment vs Cygwin

For the time being, I've just been installing packages manually (including `ocamlbuild`, `yojson`). They work with a few minor kinks not important here, and indeed they were compiled with `i686-w64-mingw32-gcc`. So this is an option for the time being when Cygwin isn't an option.

As I'm an OCaml beginner, I'm unsure how using `opam-repository` differs from directly building from the Github repos for each project.

**Comment by dra27** [comment]
@cr1901 - once it's working for Windows, simplicity! There's no practical difference building from the repos for each project and installing via opam (for an historic example, see https://github.com/dra27/OCaml-Windows-Build), although packages in opam-repository may have patches which haven't (yet) made it upstream to the github repo.
