### ISSUE TITLE
Confusing error when patch utlity is not found

### ISSUE THREAD

**Issue by choeger** [ocaml/opam#2954]
I just tried to install ppx_deriving.4.1 and got an irritating error:

```
#=== ERROR while installing ppx_deriving.4.1 ==================================#
These patches didn't apply at /home/choeger/.opam/4.04.0/build/ppx_deriving.4.1:
  - fix_ppx_deriving_make_mllib.patch
```

Now I know that this package has been installed by many people on many different machines, so obviously it must have been something wrong on my end. But only when I tried to apply the patch myself I noted that there is no binary "patch" on that (freshly installed) system. 

Apparently, the error message from the command gets lost somewhere in the process. For new users this might be a showstopper.

**Comment by dbuenzli** [comment]
I think this has been fixed on master see https://github.com/ocaml/opam/issues/2576

**Comment by AltGr** [comment]
Indeed, this should be fixed already. Note also that `opam init` is supposed to stop with an error if no `patch` is detected on the system.
