### ISSUE TITLE
target-less pins

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2957]
It would be nice to support `opam pin add --edit foo` without target.

**Comment by AltGr** [comment]
Use `opam pin add --edit foo -`

**Comment by AltGr** [comment]
(this is to avoid typing mistakes when you want to pin an existing package)

**Comment by AltGr** [comment]
(or just `opam pin foo -`)

**Comment by Drup** [comment]
I think this should be in the documentation. It's not exactly intuitive.
