### ISSUE TITLE
`opam switch` of 2.0beta+3 is hard to find which is the current

### ISSUE THREAD

**Issue by camlspotter** [ocaml/opam#2963]
```
$ opam switch --color=never
# switch     compiler                    description
4.04.0       ocaml-base-compiler.4.04.0  
4.04.1       ocaml-base-compiler.4.04.1  4.04.1
4.04.1-test  ocaml-base-compiler.4.04.1  base-bigarray.base base-threads.base
                                         base-unix.base
                                         ocaml-base-compiler.4.04.1
```

I cannot find which is the current.  

Even with `--color=always`, it is bit hard for me to tell which is the current.  The current switch is printed with the bold font but not clearly distinguishable for my old eyes.

**Comment by AltGr** [comment]
> Even with --color=always, it is bit hard for me to tell which is the current. The current switch is printed with the bold font but not clearly distinguishable for my old eyes.

That's the problem with terminal colors I guess, it's difficult to predict how they are configured on everyone's machines: the `bold` code most often corresponds to hilighted color (_instead_ — or additionally to — being bold), which is the most visible.

I'll add a more obvious marker.

**Comment by AltGr** [comment]
Done. Thanks for reporting!

**Comment by camlspotter** [comment]
Thanks!

**Comment by mars0i** [comment]
This is currently a problem for me with 2.0.0-beta3.  I'd like to suggest reopening it.  Yes, with color it depends on the terminal configuration, but I've never experienced a problem like this before.   The appearance of bold might also depend on the terminal font.  I am getting bold with color, but it's barely noticeable, and the color noise gets in the way.  But with `--color=never` there is no indication at all what the current switch is--I get no bold, so `never` is only useful as a way of listing available switches.  Can bold be added for `--color=never`?  Or maybe there are terminals where that won't do anything?  How about adding a `*` or some kind of arrow on the right pointing at the current switch, or maybe an addition column that contains either "curr" or nothing?  Thanks-
