### ISSUE TITLE
"opam list -a" doesn't work at all

### ISSUE THREAD

**Issue by ritchie78** [ocaml/opam#2969]
Hello,

On a macosx 10.11.6 (15G1510) el capitan, opam has been install with brew but the basic fonctionnality doesn't work at all : 
opam list -a 
[ERROR] Base package base-threads of compiler system not found! Ignored.
[ERROR] Base package base-bigarray of compiler system not found! Ignored.
[ERROR] Base package base-unix of compiler system not found! Ignored.

Any idea of what is missing in the install ? Thanks.

**Comment by AltGr** [comment]
Did you run `opam init` ? What's the output of `opam config report` ?

**Comment by ritchie78** [comment]
1/ "opam init" tells :

OPAM has already been initialized.
In normal operation, OPAM only alters files within ~/.opam.

During this initialisation, you can allow OPAM to add information to two
other files for best results. You can also make these additions manually
if you wish.

If you agree, OPAM will modify:

  - ~/.profile (or a file you specify) to set the right environment
    variables and to load the auto-completion scripts for your shell (bash)
    on startup. Specifically, it checks for and appends the following line:

    . /Users/ritchie/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true


  - ~/.ocamlinit to ensure that non-system installations of `ocamlfind`
    (i.e. those installed by OPAM) will work correctly when running the
    OCaml toplevel. It does this by adding $OCAML_TOPLEVEL_PATH to the list
    of include directories.

If you choose to not configure your system now, you can either configure
OPAM manually (instructions will be displayed) or launch the automatic setup
later by running:

   opam config setup -a


Do you want OPAM to modify ~/.profile and ~/.ocamlinit?
(default is 'no', use 'f' to name a file other than ~/.profile)
    [N/y/f] y

User configuration:
  ~/.ocamlinit is already up-to-date.
  ~/.profile is already up-to-date.
Global configuration:
  ~/.opam/opam-init/init.sh is already up-to-date.
  ~/.opam/opam-init/init.zsh is already up-to-date.
  ~/.opam/opam-init/init.csh is already up-to-date.
  ~/.opam/opam-init/init.fish is already up-to-date. 

2/
"opam config report" tells : 

# OPAM config report
# opam-version    1.2.2 
# self-upgrade    no
# os              darwin
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            4
# repositories    1* (http)
# pinned          0
# current-switch  system*
# last-update     2017-06-12 21:06

**Comment by ritchie78** [comment]
3/ 
"opam list -a --debug" tells : 

0:00.011  SYSTEM                  locking /Users/ritchie/.opam/lock
00:00.012  STATE                   LOAD-STATE(list)
00:00.022  CUDF                    Checking version of criteria accepted by the external solver
00:00.044  SYSTEM                  [log-1665-4438d8] (in 0.001s) aspcud -v
00:00.045  CUDF                    Solver is aspcud > 1.9: using latest version criteria
00:00.045  STATE                   Loaded /Users/ritchie/.opam/state.cache in 0.000s
00:00.047  STATE                   ROOT      : /Users/ritchie/.opam
00:00.047  STATE                   SWITCH    : system
00:00.047  STATE                   COMPILER  : system
00:00.047  STATE                   COMPILERS : { system }
00:00.047  STATE                   REPOS     : { default }
00:00.047  STATE                   PACKAGES  : {}
00:00.047  STATE                   INSTALLED : {}
00:00.047  STATE                   ROOTS     : {}
00:00.047  STATE                   REINSTALL : {}
00:00.047  STATE                   State list loaded in 0.008s
00:00.104  SYSTEM                  [log-1665-4bcc67] (in 0.004s) ocamlc -version
[ERROR] Base package base-threads of compiler system not found! Ignored.
[ERROR] Base package base-bigarray of compiler system not found! Ignored.
[ERROR] Base package base-unix of compiler system not found! Ignored.
00:00.126  SOLVER                  trim
00:00.126  SOLVER                  Load cudf universe (depopts:false, build:true)
00:00.126  SOLVER                  cudf_versions_map
00:00.126  CLIENT                  names_of_regexp regexps={}
00:00.126  SYSTEM                  Lock released on /Users/ritchie/.opam/lock

4.
"ocamlc -v" tells : 

The OCaml compiler, version 4.04.1
Standard library directory: /usr/local/lib/ocaml

**Comment by dbuenzli** [comment]
Maybe try to `rm -rf ~/.opam` and redo your `opam init && eval $(opam config env)`.

**Comment by dbuenzli** [comment]
Also 4. seems to indicate you are using a system switch which tend to be brittle. Maybe try to `opam switch 4.04.1 && val $(opam config env)`

**Comment by ritchie78** [comment]
5.
"opam switch 4.04.1" tells : 
[ERROR] "4.04.1" is not a valid compiler.

**Comment by dbuenzli** [comment]
What does `opam switch list` say ?

**Comment by dbuenzli** [comment]
and `opam repo list`

**Comment by ritchie78** [comment]
6.
"opam switch lsit" tells : 
system C system  System compiler (4.04.1)

"opam repository list" tells : 
   0 [http]     default     https://opam.ocaml.org

**Comment by dbuenzli** [comment]
Ok so try `opam update` and then see if you get more stuff listed.

**Comment by ritchie78** [comment]
OK, It works. I can see 6911 packages now.
Thank you very much for your help.
