### ISSUE TITLE
how to tell opam where is the "system" compiler

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#2973]
Hello,
I have ocaml installed in user space in ~/bin.
I'd like to tell opam to use this one as the system compiler.
How to do so?

**Comment by UnixJunkie** [comment]
opam switch would fail to install a new compiler from sources, so I installed one by hand

**Comment by UnixJunkie** [comment]
now I'd like to tell opam to use it

**Comment by Khady** [comment]
I am not sure about my answer, but it looks like you want @gasche 's
https://github.com/gasche/opam-compiler-conf

**Comment by UnixJunkie** [comment]
@gasche's thing is for the switch command. I would need something for the opam init command.

**Comment by AltGr** [comment]
When looking for a system compiler, opam simply looks for `ocamlc` in the `PATH`. So `PATH=~/bin:$PATH opam init` should work, but be careful that your switch may no longer work if the compiler is no longer in the `PATH`!

With opam 2.0, you would be able to `opam init --bare` without creating a switch, which gives more control over how the initial switch is created.
