### ISSUE TITLE
Exception Invalid_argument("String.create") when TERM is not right

### ISSUE THREAD

**Issue by smondet** [ocaml/opam#2978]
In *some* weird settings,  `tput` seems to make Opam die with an exception:
*(here my shell is emacs' `M-x shell` running bash, itself running `ssh` through `gcloud compute ssh`, with a `docker-compose exec .... bash` inside)*

```
opam@edc11ba73436:~$ export TERM=nope
export TERM=nope
opam@edc11ba73436:~$ tput cols
tput cols
tput: unknown terminal "nope"
opam@edc11ba73436:~$ opam update 
opam update 

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
tput: unknown terminal "nope"
Fatal error:
Invalid_argument("String.create")
```

While `export TERM=dumb` or `export TERM=xterm` works.

We see that the function that calls `tput` matches on some exceptions but not `Invalid_argument _`:
https://github.com/ocaml/opam/blob/1d14b113febabe720bea795437fcd521e6a8a442/src/core/opamStd.ml#L582

**Comment by smondet** [comment]
Problem also happens when TERM has no value:

```
tput: No value for $TERM and no -T specified
```

**Comment by AltGr** [comment]
Thanks for reporting!
I couldn't easily reproduce ;), but what I suspect is that `get_terminal_columns` _doesn't_ fail  (it doesn't call `String.create`), but that it returns a zero or negative value, which obviously causes trouble afterwards in the formatting functions. Could you get a backtrace to confirm that ?

I'll in the meantime ensure that `columns` is always `>0`

**Comment by smondet** [comment]
Here is the backtrace:

```
opam@edc11ba73436:~$ unset TERM
unset TERM
opam@edc11ba73436:~$ OCAMLRUNPARAM=b opam update
OCAMLRUNPARAM=b opam update

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
tput: No value for $TERM and no -T specified
Fatal error:
Invalid_argument("String.create")
Backtrace:
  Raised by primitive operation at file "bytes.ml", line 34, characters 10-18
  Called from file "string.ml", line 33, characters 2-12
  Called from file "core/opamParallel.ml", line 117, characters 8-68
  Called from file "core/opamParallel.ml", line 163, characters 10-51
  Called from file "core/opamParallel.ml", line 343, characters 10-61
  Called from file "client/opamClient.ml", line 1140, characters 8-184
  Called from file "core/opamFilename.ml", line 324, characters 12-15
```

**Comment by AltGr** [comment]
Thanks! 00934e5 should fix it.
