### ISSUE TITLE
Repository search not working

### ISSUE THREAD

**Issue by sampablokuper** [ocaml/opam#2986]
### Steps to reproduce

1. Go to https://opam.ocaml.org/packages/ in a browser that does not use JavaScript, or has JavaScript disabled.
1. In the "Search packages" field near the top-right of the page, enter a string to search for, e.g. "rdf" (without quote marks).
1. Press <key>Rtn</key>.

### Expected outcome

A list of search results would be presented, which would at least include a link to https://opam.ocaml.org/packages/rdf/ .

### Actual outcome

The page refreshes, emptying the "Search packages" field.

**Comment by AltGr** [comment]
The web pages are actually generated by project ocaml/opam2web . Would you mind reporting there ?
Thanks!

**Comment by sampablokuper** [comment]
Thanks for the quick reply. Done!
