### ISSUE TITLE
opam fails to install ocaml-top

### ISSUE THREAD

**Issue by fredOnGitHub** [ocaml/opam#2992]
Mac version 10.12.5
Hello fail to install
zarith
ocaml-top

i ihave done

brew install opam
opam init
opam install zarith
opam install ocaml-top

Here the report

Somebody knows the issue ?

Thanks

*******:ocaml ****$ opam init
Checking for available remotes: rsync and local, git.
- you won't be able to use mercurial repositories unless you install the hg command on your system.
- you won't be able to use darcs repositories unless you install the darcs command on your system.

=-=- Fetching repository information =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] synchronized from https://opam.ocaml.org

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed base-bigarray.base
∗  installed base-threads.base
∗  installed base-unix.base
Done.

In normal operation, OPAM only alters files within ~/.opam.

During this initialisation, you can allow OPAM to add information to two
other files for best results. You can also make these additions manually
if you wish.

If you agree, OPAM will modify:

- ~/.bash_profile (or a file you specify) to set the right environment
variables and to load the auto-completion scripts for your shell (bash)
on startup. Specifically, it checks for and appends the following line:

. /Users/****/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

- ~/.ocamlinit to ensure that non-system installations of `ocamlfind`
(i.e. those installed by OPAM) will work correctly when running the
OCaml toplevel. It does this by adding $OCAML_TOPLEVEL_PATH to the list
of include directories.

If you choose to not configure your system now, you can either configure
OPAM manually (instructions will be displayed) or launch the automatic setup
later by running:

opam config setup -a

Do you want OPAM to modify ~/.bash_profile and ~/.ocamlinit?
(default is 'no', use 'f' to name a file other than ~/.bash_profile)
[N/y/f]

Global configuration:
Updating ~/.opam/opam-init/init.sh
Updating ~/.opam/opam-init/init.zsh
Updating ~/.opam/opam-init/init.csh
Updating ~/.opam/opam-init/init.fish

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

1. To configure OPAM in the current shell session, you need to run:

eval `opam config env`

2. To correctly configure OPAM for subsequent use, add the following
line to your profile file (for instance ~/.bash_profile):

. /Users/****/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

3. To avoid issues related to non-system installations of `ocamlfind`
add the following lines to ~/.ocamlinit (create it if necessary):

let () =
try Topdirs.dir_directory (Sys.getenv "OCAML_TOPLEVEL_PATH")
with Not_found -> ()
;;

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

*******:ocaml ****$ opam --version
1.2.2
*******:ocaml ****$ opam install zarith
The following actions will be performed:
∗  install conf-perl 1                      [required by zarith]
∗  install conf-m4   1                      [required by ocamlfind]
∗  install conf-gmp  1                      [required by zarith]
∗  install ocamlfind 1.7.3                  [required by zarith]
∗  install zarith    1.5
===== ∗  5 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] https://opam.ocaml.org/archives/zarith.1.5+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocamlfind.1.7.3+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed conf-perl.1
[ERROR] The compilation of conf-gmp failed at "sh -exc cc -c $CFLAGS -I/usr/local/include test.c".
∗  installed conf-m4.1
∗  installed ocamlfind.1.7.3

#=== ERROR while installing conf-gmp.1 ========================================#
# opam-version 1.2.2
# os           darwin
# command      sh -exc cc -c $CFLAGS -I/usr/local/include test.c
# path         /Users/****/.opam/system/build/conf-gmp.1
# compiler     system (4.04.2)
# exit-code    1
# env-file     /Users/****/.opam/system/build/conf-gmp.1/conf-gmp-3884-d2d111.env
# stdout-file  /Users/****/.opam/system/build/conf-gmp.1/conf-gmp-3884-d2d111.out
# stderr-file  /Users/****/.opam/system/build/conf-gmp.1/conf-gmp-3884-d2d111.err
### stderr ###
# + cc -c -I/usr/local/include test.c
# test.c:1:10: fatal error: 'gmp.h' file not found
# #include <gmp.h>
#          ^
# 1 error generated.

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions were aborted
∗  install zarith 1.5
The following actions failed
∗  install conf-gmp 1
The following changes have been performed
∗  install conf-m4   1
∗  install conf-perl 1
∗  install ocamlfind 1.7.3

=-=- conf-gmp.1 troobleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package relies on external (system) dependencies that may be missing. `opam depext conf-gmp.1' may help you find the correct installation for your system.

The former state can be restored with:
opam switch import "~/.opam/system/backup/state-20170604184735.export"

------------------------------------

Last login: Wed Jul  5 11:29:19 on ttys000
*******:~ ****$ opam install ocaml-top
The following actions will be performed:
∗  install conf-gtksourceview 2             [required by ocaml-top]
∗  install ocp-build          1.99.19-beta  [required by ocaml-top]
∗  install result             1.2           [required by cmdliner]
∗  install base-bytes         base          [required by re]
∗  install ocamlbuild         0.11.0        [required by cmdliner, re]
∗  install lablgtk            2.18.5        [required by ocaml-top]
∗  install topkg              0.9.0         [required by cmdliner]
∗  install re                 1.7.1         [required by ocp-index]
∗  install cmdliner           1.0.0         [required by ocp-indent, ocp-index]
∗  install ocp-indent         1.6.0         [required by ocaml-top]
∗  install ocp-index          1.1.5         [required by ocaml-top]
For ocp-browser, please also install package lambda-term
∗  install ocaml-top          1.1.3
===== ∗  12 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

[default] https://opam.ocaml.org/archives/cmdliner.1.0.0+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocaml-top.1.1.3+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocamlbuild.0.11.0+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocp-build.1.99.19-beta+opam.tar.gz downloaded
Processing  9/12: [lablgtk: from default] [ocp-indent: from default] [ocp-index: from default[default] https://opam.ocaml.org/archives/ocp-indent.1.6.0+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/lablgtk.2.18.5+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/result.1.2+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/re.1.7.1+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/topkg.0.9.0+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocp-index.1.1.5+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed base-bytes.base
[ERROR] The compilation of conf-gtksourceview failed at "pkg-config --short-errors --print-errors gtksourceview-2.0".
∗  installed result.1.2
∗  installed ocamlbuild.0.11.0
∗  installed topkg.0.9.0
∗  installed cmdliner.1.0.0
∗  installed re.1.7.1
∗  installed ocp-build.1.99.19-beta
∗  installed ocp-indent.1.6.0
∗  installed ocp-index.1.1.5

#=== ERROR while installing conf-gtksourceview.2 ==============================#
# opam-version 1.2.2
# os           darwin
# command      pkg-config --short-errors --print-errors gtksourceview-2.0
# path         /Users/****/.opam/system/build/conf-gtksourceview.2
# compiler     system (4.04.2)
# exit-code    127
# env-file     /Users/****/.opam/system/build/conf-gtksourceview.2/conf-gtksourceview-615-48c407.env
# stdout-file  /Users/****/.opam/system/build/conf-gtksourceview.2/conf-gtksourceview-615-48c407.out
# stderr-file  /Users/****/.opam/system/build/conf-gtksourceview.2/conf-gtksourceview-615-48c407.err

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions were aborted
∗  install lablgtk   2.18.5
∗  install ocaml-top 1.1.3
The following actions failed
∗  install conf-gtksourceview 2
The following changes have been performed
∗  install base-bytes base
∗  install cmdliner   1.0.0
∗  install ocamlbuild 0.11.0
∗  install ocp-build  1.99.19-beta
∗  install ocp-indent 1.6.0
∗  install ocp-index  1.1.5
∗  install re         1.7.1
∗  install result     1.2
∗  install topkg      0.9.0

=-=- ocp-indent.1.6.0 installed successfully =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package requires additional configuration for use in editors. Install package 'user-setup', or manually:

* for Emacs, add these lines to ~/.emacs:
(add-to-list 'load-path "/Users/****/.opam/system/share/emacs/site-lisp")
(require 'ocp-indent)

* for Vim, add this line to ~/.vimrc:
set rtp^="/Users/****/.opam/system/share/ocp-indent/vim"

=-=- ocp-index.1.1.5 installed successfully -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package requires additional configuration for use in editors. Either install package 'user-setup', or manually:

* for Emacs, add these lines to ~/.emacs:
(add-to-list 'load-path "/Users/****/.opam/system/share/emacs/site-lisp")
(require 'ocp-index)

* for Vim, add the following line to ~/.vimrc:
set rtp+=/Users/****/.opam/system/share/ocp-index/vim

=-=- conf-gtksourceview.2 troubleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package requires gtksourceview 2.0 development packages installed on your system
=> On OSX, install the `gtksourceview' and `libxml2' packages and define PKG_CONFIG_PATH:

export PKG_CONFIG_PATH=/usr/X11/lib/pkgconfig/:/usr/local/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig/

The former state can be restored with:
opam switch import "~/.opam/system/backup/state-20170605100428.export"

**Comment by dbuenzli** [comment]
Please do read the [CONTRIBUTING.md](https://github.com/ocaml/opam/blob/master/CONTRIBUTING.md) guidelines before reporting issues. These issue need to be reported on the [`opam-repository`](https://github.com/ocaml/opam-repository/).

Regarding zarith it seems you don't have gmp installed on your system, the error mentions this:

> =-=- conf-gmp.1 troobleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> => This package relies on external (system) dependencies that may be missing. `opam depext conf-gmp.1' may help you find the correct installation for your system.

so you should try to invoke this command or `opam dexpext conf-gmp`. Or you can do it yourself manually via `brew install gmp`. 

Regarding the `ocaml-top` error please follow the advice given in the error message:

> =-=- conf-gtksourceview.2 troubleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> => This package requires gtksourceview 2.0 development packages installed on your system
> => On OSX, install the gtksourceview' andlibxml2' packages and define PKG_CONFIG_PATH:
> 
> export PKG_CONFIG_PATH=/usr/X11/lib/pkgconfig/:/usr/local/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig/

**Comment by fredOnGitHub** [comment]
Thanks 

There are proble to install gtksourceview
see here https://github.com/ocaml/opam-repository/issues/9773
