### ISSUE TITLE
Cannot use Dynlink

### ISSUE THREAD

**Issue by Yuren-Zhong** [ocaml/opam#2998]
On Ubuntu, I have installed opam 1.2.2 and switch to 4.04.0. When I try to use the module Dynlink, errors occur.

While using the toplevel of Ocaml, the error message is : Reference to undefined global 'Dynlink' .

While using the ocamlopt, the error massage is : No implementations provided for the following modules:
         Dynlink referenced from c.cmx.

However, under the directory  ~/.opam/4.04.0/lib/ocaml, dynlink files exist. 

```
_$ ls dynlink.*
dynlink.a  dynlink.cma  dynlink.cmi  dynlink.cmx  dynlink.cmxa  dynlink.mli_
```

Could you please help me out? Thanks!

**Comment by SchrodingerZhu** [comment]
This answer comes with a high rank at search.
