### ISSUE TITLE
v2~beta3 Inconsistant cli `opam list` vs `opam switch list`

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#3001]
```
opam list --available
[...]
opam switch list --available 
opam: unknown option `--available'.
Usage: opam switch [OPTION]... [COMMAND] [ARG]...
Try `opam switch --help' or `opam --help' for more information.
```

**Comment by AltGr** [comment]
I didn't get the issue at first, but indeed there is a command `opam switch list-available`, so I can get the confusion. Thanks for reporting.

**Comment by AltGr** [comment]
I am considering this, but on second thought, it would only add to the confusion. Indeed, `opam list` always lists packages, and `--available` is a filter. `opam switch list`, on the other hand lists _installed switches_.

`opam switch list-available` may be badly named, but what it lists is _compilers_, a.k.a. "base package candidates", and that is a different entity -- although the overload allows you to create switches after them, with the same name.

The output reflects that, and `opam switch list` and `opam switch list-available` show very different outputs. The latter is actually equivalent to `opam list --no-switch --available --all-versions --has-flag compiler`.

So, apart from renaming the command (`list-compilers` ? `list-available-compilers` ?), and fundamental issues of how we create switches being already discussed at other places, I don't see this as a bug that should be fixed ?

**Comment by Drup** [comment]
I remember precisely requesting the distinction we have currently when I started doing fancy stuff with switches and getting confused by the `switch list` function. So I agree we really need two distinct commands.

**Comment by dbuenzli** [comment]
> So, apart from renaming the command (list-compilers ? list-available-compilers ?), and fundamental issues of how we create switches being already discussed at other places, I don't see this as a bug that should be fixed ?

I certainly think it would be better to fix the way switches are created an initialized. There are [already](https://discuss.ocaml.org/t/how-to-install-specific-ocaml-version-with-opam-2-0-beta-3/727) hints that the way this currently happens is confusing and doesn't match user expectations.

**Comment by dbuenzli** [comment]
I still find the UI to be pretty bad. But then no-one seems to care. Let's close this.
