### ISSUE TITLE
Fish shell variables.fish is breaking PATH and MANPATH

### ISSUE THREAD

**Issue by abc-mikey** [ocaml/opam#3005]
I've been following the instructions [here](https://github.com/realworldocaml/book/wiki/Installation-Instructions) for installing Ocaml, Opam and Utop.

I found that there is currently a problem with the environment setup script for opam for fish shell. 

_~/.opam/opam-init/variables.fish_
```
set -gx PATH "/home/michael/.opam/4.02.1/bin" "$PATH";
set -gx OCAML_TOPLEVEL_PATH "/home/michael/.opam/4.02.1/lib/toplevel";
set -gx PERL5LIB "/home/michael/.opam/4.02.1/lib/perl5:$PERL5LIB";
set -gx MANPATH "$MANPATH" "/home/michael/.opam/4.02.1/man";
set -gx CAML_LD_LIBRARY_PATH "/home/michael/.opam/4.02.1/lib/stublibs";
```

Here the quotes around `$PATH` on the first line are casing the existing path to be concatenated with spaces and treated as a single path. This actually completely breaks fish shell for all subsequent logins if you have added this script to your _~/.config/fish/config.fish_ profile. 

My guess is that there is the same problem for `$MANPATH` being quoted but I'm not seeing it as I don't have any existing man paths.

**Comment by ksqsf** [comment]
Yes, I just experienced this.

Changing that line to
```fish
set PATH "/home/michael/.opam/4.02.1/bin" $PATH;
```
fixes this problem.

**Comment by abc-mikey** [comment]
Yes that works, actually I just experienced another issue relating to this script getting sourced. 

The opam fish script is appending to / setting `MANPATH`. For me this is unset by default and fish has a check in `"/usr/share/fish/functions/man.fish` so that when MANPATH is unset it looks in the path returned by the command `manpath` which on my system correctly returns the various man paths on my system along with the ocaml path:

```
$manpath
/home/michael/.opam/4.02.1/man:/usr/local/share/man:/usr/share/man
```

However as this is being set by the opam script it is preventing this being run so that *only* the ocaml path is being included, *breaking all my other man pages*.

This can be fixed by commenting out the line or probably better adding a check to see if MANPATH is already set and only then adding the ocaml path to it.

**Comment by AltGr** [comment]
You didn't report your opam version (nor `opam config report`). I'm assuming that it's 1.2.2, in which case this has been reported and fixed already.

About the manpage: we disable setting MANPATH on BSD for that precise reason. However, on Linux, it was my understanding that when you have a trailing colon, the default system man path is appended. I am guessing that this is linked to the special way fish handles a few select variables.

This is how the latest opam dev branch defines the variables on fish: could you please check if that looks OK to you ?

```
# Opam root in use
set -gx OPAMROOT '/tmp/foo';
# Prefix of the current opam switch
set -gx OPAM_SWITCH_PREFIX '/tmp/foo/default';
if [ 0 -eq (count $MANPATH) ]; set -gx MANPATH ""; end;
# Current opam switch man dir
set -gx MANPATH $MANPATH '/tmp/foo/default/man';
# Binary dir for opam switch default
set -gx PATH '/tmp/foo/default/bin' $PATH;
```

Thanks!

**Comment by abc-mikey** [comment]
Yuck, what a mess. Well your proposed solution looks like it works and may be the only reliable solution for fish shell for the moment. There is a supposed fix lined up for fish 3.0, whenever that gets released. I can't say I like it though as it essentially changes the behaviour of all of `MANPAGE` for fish shell for that user. 

If you could be confident that the `manpage` command will always return a list that includes the directory for OPAM, I would almost suggest the less invasive step of only adding the path manually if `MANPATH` is already set.

```
if [ 0 -ne (count $MANPATH) ]; set -gx MANPATH $MANPATH '/tmp/test/man'; end;
```

**Comment by SkySkimmer** [comment]
Note fish-shell/fish-shell#4158.
While fish 2.6 lives, doing
``` fish
set MANPATH ""
set MANPATH $MANPATH "foo"
```
results in the array `"." "foo"`.

**Comment by abc-mikey** [comment]
A terribly hacky alternative to accommodate fish 2.6 may be to use 

```fish
set -gx MANPATH ":"
```

Instead of:

```fish
set -gx MANPATH ""
```

Not sure if that works in all cases. I'm not sure it's clear how many fish 2.6 users there's likely to be. I would still come down on the side of only adding OPAM to the path if there is some previously defined `MANPATH` and trusting that `manpath` is properly configured to find the OPAM directory. Only for the fish users where that is not the case then would have to add it themselves.

**Comment by abc-mikey** [comment]
A terribly hacky alternative to accommodate fish 2.6 may be to use 

```fish
set -gx MANPATH ":"
```

Instead of:

```fish
set -gx MANPATH ""
```

Not sure if that works in all cases. I'm not sure it's clear how many fish 2.6 users there's likely to be. I would still come down on the side of only adding OPAM to the path if there is some previously defined `MANPATH` and trusting that `manpath` is properly configured to find the OPAM directory. Only for the fish users where that is not the case then would have to add it themselves.

**Comment by SkySkimmer** [comment]
2.6 is the current release. I got it through debian testing.

**Comment by iamitava** [comment]
Looks like the expansion of empty element to `.` is being reverted for MANPATH only in fish-shell/fish-shell@1bee665 (for fish-shell/fish-shell#4158, as noted by @SkySkimmer earlier).

However, it seems that *not* setting MANPATH (i.e. leaving it blank in case it was blank) also does the trick.

Example:

```
$ fish --version
fish, version 2.6.0
$ set -e MANPATH 
$ echo (count $MANPATH)
0
$ man ls # shows ls manpage
$ man ocamlbuild # shows ocamlbuild mapage, installed using opam
```

It seems `man` can figure out man path directories for commands in `PATH`, as per [this comment](https://github.com/junegunn/fzf/issues/774#issuecomment-267736908) on junegunn/fzf#774. Indeed,

```
$ man -d ocamlbuild
Reading config file /private/etc/man.conf
...
adding /Users/test/.opam/system/man to manpath
...
$
```

**Comment by AltGr** [comment]
If you could have a look at my solution and verify it's OK, that would be appreciated. Thanks!
(the idea is to not affect MANPATH when not defined already, since it is inferred apparently. As you advised)

**Comment by iamitava** [comment]
I just re-installed opam from head (`brew install opam --HEAD`) which pulled in these changes (i.e. HEAD-4dc7083). After `opam init`, in a new shell MANPATH is not set and everything works fine. In the shell that I installed opam I had an empty MANPATH but `count $MANPATH` was 1 (an array with an empty element), so that didn't work, but I have been using this shell for a while and I guess you could treat this as an edge case. Thanks for the fix!

**Comment by argent-smith** [comment]
The issue is marked as «fixed», but it still bugs me ;)

Here’s what I have after `opam switch`, and it breaks the fish:

```
set -gx PATH "/Users/paul/.opam/4.02.2+multicore/bin" "$PATH";
set -gx OCAML_TOPLEVEL_PATH "/Users/paul/.opam/4.02.2+multicore/lib/toplevel";
set -gx PERL5LIB "/Users/paul/.opam/4.02.2+multicore/lib/perl5:$PERL5LIB";
set -gx MANPATH "$MANPATH" "/Users/paul/.opam/4.02.2+multicore/man";
set -gx OPAMUTF8MSGS "1";
set -gx CAML_LD_LIBRARY_PATH "/Users/paul/.opam/4.02.2+multicore/lib/stublibs»;
```

and how the working version looks:

```
set -gx PATH "/Users/paul/.opam/4.02.2+multicore/bin" "$PATH";
set -gx OCAML_TOPLEVEL_PATH "/Users/paul/.opam/4.02.2+multicore/lib/toplevel";
set -gx PERL5LIB "/Users/paul/.opam/4.02.2+multicore/lib/perl5:$PERL5LIB";
set -gx MANPATH "$MANPATH" "/Users/paul/.opam/4.02.2+multicore/man";
set -gx OPAMUTF8MSGS "1";
set -gx CAML_LD_LIBRARY_PATH "/Users/paul/.opam/4.02.2+multicore/lib/stublibs";
```

Am I doing anything wrong?

**Comment by AltGr** [comment]
> The issue is marked as «fixed», but it still bugs me ;)

Well, are you using a version of opam more recent than the fix ?
Please post the results of `opam config report`.

**Comment by sashang** [comment]
Well I've bumped into this as well. The fix for me is to remove the quotes from "$PATH".

~  > opam config report
# OPAM config report
# opam-version    1.2.2
# self-upgrade    no
# os              linux
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            4
# repositories    1* (http)
# pinned          0
# current-switch  4.06.1
# last-update     2018-03-19 11:30
~  >

**Comment by argent-smith** [comment]
```
# OPAM config report
# opam-version    1.2.2
# self-upgrade    no
# os              darwin
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            4
# repositories    1* (http)
# pinned          2 (version), 1 (version control)
# current-switch  taxi
# last-update     2017-12-28 19:13
```

Still buggy

**Comment by dra27** [comment]
@argent-smith - well, yes, if you upgrade from opam 1.2.2 to, um, opam 1.2.2, you will find the same bugs to be present.

**Comment by argent-smith** [comment]
@dra27 you mean, I should leave the mainstream and try 2.0?

**Comment by dra27** [comment]
If you want a version which has the bug fixed, you will need to switch to a version which has the bug fixed, yes!

Reporting that a known bug in a known version is still a bug is of limited usefulness...

**Comment by sashang** [comment]
Sorry didn't see that this bug was filed against 1.2.2. I'm not familiar with the github bug tracking issue system, so I can't see where they put the version number.... Can't even figure out how to reply to a previous post and it's not worth my time to figure it out. Mailing lists and email clients with threads are so much better.
