### ISSUE TITLE
OPAM 1.2.2 built with OCaml 4.05.0 needs `opam config exec` before `opam install`

### ISSUE THREAD

**Issue by ilovezfs** [ocaml/opam#3007]
This has come up on

https://github.com/Homebrew/homebrew-core/pull/15849
https://github.com/Homebrew/homebrew-core/pull/15683
https://github.com/Homebrew/homebrew-core/pull/15682
https://github.com/Homebrew/homebrew-core/pull/15681

Previously, when OPAM 1.2.2 had been built with OCaml < 4.05.0,

```
opam install foo
```

would be sufficient.

However, now that OPAM 1.2.2 was rebuilt with OCaml 4.05.0 (https://github.com/Homebrew/homebrew-core/commit/f8f754ed3e4a0c985871208b38b488b49f2b9895), we're having to resort to

```
opam config exec -- opam install foo
```

in order to get the right environment into the opam root.

**Comment by ilovezfs** [comment]
CC @avsm @mroch @gabelevi

**Comment by ilovezfs** [comment]
Build log for flow is here: https://gist.github.com/ilovezfs/f23b872c0a017affe23c20232b99b319

**Comment by ilovezfs** [comment]
@avsm are you able to reproduce this?

**Comment by avsm** [comment]
on vacation till monday, will try as soon as back...

**Comment by ilovezfs** [comment]
Thanks @avsm!

**Comment by ilovezfs** [comment]
@avsm any luck reproducing it?

**Comment by ilovezfs** [comment]
@avsm Any luck reproducing the issue?

**Comment by AltGr** [comment]
This is really weird, there really shouldn't be any difference between `opam foo` and `opam config exec -- foo`... opam uses the proper environment internally, the same that it exports on `opam config exec`.

**Comment by ilovezfs** [comment]
@AltGr yes it's very weird. It seems to be a bug caused by building OPAM with OCaml 4.05.0. So I have no idea if the "real" bug is in OPAM or OCaml.

**Comment by dbuenzli** [comment]
Is that seen in a context where `opam` running as root ?  Can you reproduce with `4.04.2` ? This may be related to the hardening of `{Unix,Sys}.getenv`, see https://caml.inria.fr/mantis/view.php?id=7557

**Comment by ilovezfs** [comment]
>Is that seen in a context where opam running as root?

Nope.

>Can you reproduce with 4.04.2

Nope.

**Comment by AltGr** [comment]
> This may be related to the hardening of {Unix,Sys}.getenv
Hmm, that seems likely indeed. I'll investigate, thanks for the pointer.

**Comment by dbuenzli** [comment]
> Hmm, that seems likely indeed. I'll investigate, thanks for the pointer.

Given @ilovezfs's answer my guess is that this is not the case.

**Comment by fdagnat** [comment]
Just an add on to say that I have a similar issue with `opam user-setup install`

```
<fdagnat:517> opam user-setup install
Fatal error: exception # opam-version    1.2.2
# os              darwin
opam: "execvpe" failed on opam-user-setup: No such file or directory
<fdagnat:518> opam config exec -- opam user-setup install
ocamltop > base > .ocamlinit: up to date
emacs > .emacs: already exists, not installing base template
emacs > base > .emacs: up to date
emacs > base > .emacs.d/opam-user-setup.el: up to date
vim > .vimrc: already exists, not installing base template
vim > base > .vimrc: up to date
```

**Comment by AltGr** [comment]
@fdagnat: ah, thanks for the info. Indeed, IIRC, opam 1.2.2 didn't load and adapt the `PATH` _before_ searching for the plugins. This has been fixed a while ago. This shouldn't affect normal commands, like `opam install` though, so I think this is unrelated.

**Comment by AltGr** [comment]
Finally solved this, it's related to a change in ocaml's `Unix.execvpe()` behaviour. See [the Mantis report](https://caml.inria.fr/mantis/view.php?id=7640)
We now have a fix on master.

Thanks everyone for reporting and helping the investigations!

**Comment by ilovezfs** [comment]
Hurray! Thank @AltGr! Will there be a new release with the fix soon?
