### ISSUE TITLE
v3~beta3 opam-installer install directories

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#3008]
The `opam-installer` tool allows to define the install directories for some of the field but not for all of them. Maybe it would be better to define a generic syntax for mapping fields to paths.

Btw. are x-field allowed in .install files ?

**Comment by dbuenzli** [comment]
(and allow specification via environment variable)

**Comment by AltGr** [comment]
Indeed, a more complete mapping would be useful. Note that some paths are generic (`<prefix>/bin`), and others are project-specific (`<prefix>/lib/<pkgname>`) ; there is some magic for manpages, too.

And no, `x-` fields are not allowed at the moment.

**Comment by dbuenzli** [comment]
Moving away from relying on `.install` files so I no longer care.
