### ISSUE TITLE
[Question] Importing compilers from old 1.2 repositories

### ISSUE THREAD

**Issue by Kakadu** [ocaml/opam#3010]
I tried to import https://github.com/ocamllabs/multicore-opam . It succeeds but I don't have a compiler available. Can opam 2.0 import compilers from the old repos? Is it  supported?

**Comment by AltGr** [comment]
Yes, the automatic conversion should turn them into packages on the fly

**Comment by Kakadu** [comment]
https://discuss.ocaml.org/t/searching-for-a-manual-about-packaging-compiler-for-opam-2-0/638
