### ISSUE TITLE
fail to dynamically link object files that use libraries not compiled with the main application

### ISSUE THREAD

**Issue by Yuren-Zhong** [ocaml/opam#3013]
I tried to dynamically link an object file (.cmxs) to my main application. The object file uses the Graphics library. I found that if the main application is compiled and linked with the Graphics library then every thing works, but if the main application isn't linked with the Graphics library then Dynlink.Error(_) is raised. Is there any way that I can dynamically link this library rather than linking it at the very beginning?
Thanks！

**Comment by dra27** [comment]
Yes - you just need to load `graphics.cmxs` dynamically first (you will also need to call `Dynlink.allow_unsafe_modules true` in order to do that).

This question is nothing to do with opam, however - please use [caml-list](https://ocaml.org/community/mailing_lists.html) or discuss.ocaml.org for OCaml questions.

**Comment by Yuren-Zhong** [comment]
but it fails to load `graphics.cmxs`, too.

**Comment by dra27** [comment]
What is "it" - happy to help further, but if that quick answer hasn't solved your problem, please post this question to either of those forums I linked to, where others can potentially then benefit from the answer being in the right place.

**Comment by Yuren-Zhong** [comment]
this is the url of the post on discuss.ocaml.org:
[https://discuss.ocaml.org/t/fail-to-dynamically-link-cmxs-file-when-using-dynlink/655?u=yuren-zhong](url)

'it' means the main application which didn't link with graphics while being built.
