### ISSUE TITLE
OPAM pin issue: fails without any message

### ISSUE THREAD

**Issue by OCamlPro-Iguernlala** [ocaml/opam#3022]
I don't know if this is a known issue and/or if it is fixed in OPAM 2...
With OPAM 1.2.2, the following pin command fails silently:
```
opam pin add frama-c 20161101
```
Once debug activated, I realized that this is due to absence of `url` file for this package.
A message that explains the failure in missing in this case.

**Comment by AltGr** [comment]
You don't give much details on what happens: what makes you say it fails ? Maybe this is a duplicate of #2924 ?

**Comment by OCamlPro-Iguernlala** [comment]
Yes ! duplicate ...
