### ISSUE TITLE
feature request: named environments

### ISSUE THREAD

**Issue by mwweissmann** [ocaml/opam#3037]
instead of naming an environment just like the compiler used (e.g. "4.0.5"), make the name of the environment an arbitrary string. This would enable users to create environments for specific purposed, e.g. "testing-4.0.5-with-lwt" in which he could install and pin packages for this exact purpose. He then can create a second environment with the exact same compiler e.g. "release-4.0.5-core".

The advantage would be that you can have
1. multiple environments with the same compiler
2. name environments after your usage scenario
3. have standardized environments to share between multiple developers working on the same project while not messing with their specific personal environments

(the python installer _anaconda_ provides environments like this)

**Comment by samoht** [comment]
I am not sure what you mean exactly by environment, but you can already do something like:

```
opam switch testing-4.0.5-with-lwt -A 4.05.0
```

**Comment by dra27** [comment]
Or `opam switch create release-4.0.5-core --packages=ocaml.4.05.0` in Opam 2

**Comment by mwweissmann** [comment]
oooh, great -- thats exactly what I meant! 🥇
