### ISSUE TITLE
GitHub SSH clone times out

### ISSUE THREAD

**Issue by MiloDavis** [ocaml/opam#3038]
When running `opam pin --yes add --no-action --dev-repo ocp-ocamlres`, things hang and eventually timeout. The same command works when cloning a number of other packages that use https GitHub links. I can clone the package using the dev-repo specified in the package's opam file. The same problem exists if I specify the url directly:
`opam pin --yes add --no-action ocp-ocamlres git://github.com/OCamlPro/ocp-ocamlres`
but not if I use the https version:
`opam pin --yes add --no-action ocp-ocamlres https://github.com/OCamlPro/ocp-ocamlres`

Here's the error:
```
~/tezos/repo
$ opam pin --yes add --no-action ocp-ocamlres git://github.com/OCamlPro/ocp-ocamlres
opam pin --yes add --no-action ocp-ocamlres git://github.com/OCamlPro/ocp-ocamlres
[NOTE] Package ocp-ocamlres is currently pinned to https://github.com/OCamlPro/ocp-ocamlres (version 0.3).
Proceed and change pinning target ? [Y/n] y
[ERROR] Could not synchronize /Users/milodavis/.opam/default/.opam-switch/sources/ocp-ocamlres from "git://github.com/OCamlPro/ocp-ocamlres":
        "git fetch -q git://github.com/OCamlPro/ocp-ocamlres" exited with code 128
[ERROR] Error getting source from git://github.com/OCamlPro/ocp-ocamlres
```

This issue was also present in Opam 1.

```
# opam config report
# opam-version    2.0.0~beta3 
# self-upgrade    no
# os              darwin
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            3
# repositories    1 (http)
# pinned          1 (git)
# current-switch  default
```

**Comment by AltGr** [comment]
I guess the hang is due to git asking for credentials and blocking on stdin. Try to run with `-vv` to debug. Unfortunately, I couldn't get `GIT_TERMINAL_PROMPT` or `GIT_ASKPASS` to work as advertised. Running `git` with closed stdin doesn't help either.

**Comment by rjbou** [comment]
Closing this issues, feel free to reopen it if needed.
Thanks!
