### ISSUE TITLE
Is it possible to test the linux flavor in an opam file out of the depexts section?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#3040]
Like in the package configure step.
I'd like to test for centos, with the least shell programming needed.

**Comment by UnixJunkie** [comment]
related to needs in https://github.com/ocaml/opam-repository/pull/10195

**Comment by AltGr** [comment]
Related to https://github.com/ocaml/opam/issues/2919#issuecomment-299147538 : we are considering adding more variables with system-related information (distribution, etc.) for use in `depexts:`, but these would be made accessible everywhere. We just need to settle on what variables to define (and how to get them from the system, but we might re-use some code from https://github.com/ocaml/opam-depext for this).
We currently only define `arch` (bound dynamically to `uname -m` through the global / init config file), and `os` (set at switch creation time (!?), defined with ocaml code using `Sys.os_type` and `uname -s`).

**Comment by UnixJunkie** [comment]
For Linux, all we need should be in this file:

    # cat /etc/os-release 
    NAME="Ubuntu"
    VERSION="16.04.3 LTS (Xenial Xerus)"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Ubuntu 16.04.3 LTS"
    VERSION_ID="16.04"
    HOME_URL="http://www.ubuntu.com/"
    SUPPORT_URL="http://help.ubuntu.com/"
    BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
    VERSION_CODENAME=xenial
    UBUNTU_CODENAME=xenial

Especially, the ID and ID_LIKE variables are interesting.

**Comment by AltGr** [comment]
Since it was long, I made a RFC proposal as a separate issue, for visibility: see  #3058 . Please review and comment!

**Comment by AltGr** [comment]
@UnixJunkie  please try to run the following command and report the results to https://github.com/ocaml/opam/issues/3058. Thanks!

    curl -sL https://gist.githubusercontent.com/AltGr/5bfc8cea6f01e74b95de79ceaba39369/raw/opam_analyse.ml | ocaml unix.cma -stdin

**Comment by AltGr** [comment]
Now implemented, see variables `os-distribution` and `os-family` :)
