### ISSUE TITLE
WISH: opam lint --one-line

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam#3046]
Would it be possible to have something like
```
opam lint --one-line FILES
```
to report errors with a **single line** format such as
```
File "...", line ..., characters ...-...: message-on-the-rest-of-the-line
```
This is required to enable flymake to report errors (highlighting the lines in the buffer) in Emacs.

**Comment by AltGr** [comment]
Linting messages don't report file positions at the moment (it wouldn't make sense for most of them, like `missing field`) ; but I guess you are most interested in syntax and format errors, which do. This makes the change in message format slightly more involved, though. I'll see what I can do.
Thanks for reporting!

**Comment by Chris00** [comment]
You do not need to filter errors.  Those which do not respect the format (single line with location) will not be reported in Emacs.  So tracking errors with an optional position and and using that information to decide what to display should be enough.

**Comment by marsam** [comment]
it would be nice to also offer a machine readable output (like json) to allow integration with editors

**Comment by rjbou** [comment]
@Chris00 @marsam @avsm 
Does this format fits your needs:
```
"lint": 
    [
      { "file"     : string <filename>,
        "result"   : string (passed | error | warning),
        "warnings" :
          [ { "id"      : int,
              "message" : string <warning message> },
            ...
          ],
        "errors"   :
          [ { "id"      : int,
              "message" : string <error message> },
            ...
          ]
      },
      ...
    ]
```

**Comment by Chris00** [comment]
Not really in the sense that it needs to be parsed so an external program is still needed.  That being said, the fact that it is well structured will help writing such a program.
