### ISSUE TITLE
Upgrading aliased ocaml version with opam switch

### ISSUE THREAD

**Issue by carlsagan21** [ocaml/opam#3052]
If is there any way to upgrade installed binary OCaml?
What I want to do is something like this.

```
installed ocaml binary: 4.02.03, named as certain-ocaml using the --alias-of option.
...
some operations
...
upgraded ocaml binary: 4.04.0, named as certain-ocaml.
```

The point is, I want to just upgrade an actual version of installed OCaml, while maintaining alias name.
The motivation of upgrading can be diverse. e.g. some packages require higher version, want to use cutting-edge features, or just a whim. Anyhow, I think there is a common need for upgrading a binary or environment while keeping the name same.

Actually binary version control packages for program languages like nvm, pyenv, rbenv supports this feature. They can just upgrade a binary for a certain virtual environment, letting installed dependency packaged just be there.

Now, one way to achieve upgrading using existing functionalities of opam is [`exporting and importing`](https://opam.ocaml.org/doc/FAQ.html#CanIgetanewswitchwiththesamepackagesinstalled).
Export, remove, install, and import. like this.

```
opam switch export current-dependency.export
opam switch remove certain-ocaml
opam switch certain-ocaml --alias-of={upgrading version}
opam switch import current-dependency.export
```

But it is a bit ... irritating and ask for too much typing!
Personally, I made a shell script to do these steps in just a line, but it will be best if this feature is supported by opam natively. And this method is doing a whole installation from the very bottom, so redundant work is done heavily. It might have kept some irrelevant dependencies to not be reinstalled.

I suppose 2 features, which can improve the user experience.

```
1. opam switch upgrade {name} --target-version=4.05.0
  upgrade {name} ocaml binary to 4.05.0

2. opam switch export
  export current dependency as {binary_name}.export in the present working directory.
```

First one is to upgrade ocaml binary, as I argued above.
Second one is a less aggressive way to go. But this makes opam to work almost exactly same with `pip requirement.txt`, so it is helpful for who already know how `pip` works.

How do you guys think about this?

**Comment by carlsagan21** [comment]
and also `opam switch export` is quite.. (sorry to express this way but) primitive, compared with contemporary dependency description methods like `npm package.json`, `yarn package.lock`, `pipenv Pipfile.lock`. IMO, `pip`'s requirement.txt is equivalent with `opam export`, but marginally better in a sense that pip supports comparators(e.g. >= or ==) describing versions.

**Comment by AltGr** [comment]
opam 2.0 handles the compilers as packages, so they can be upgraded normally ; at the moment, though, the compiler is "locked" so you need to do `opam switch set-base` first, but we are considering adding a more convenient workflow (maybe an option like `opam upgrade --allow-base`).

> and also opam switch export is quite.. (sorry to express this way but) primitive, compared with contemporary dependency description methods

the purpose is completely different. Our dependencies are expressed in the package definition (`opam`) files, which are more expressive than any of the methods you mention (having disjunctions of dependencies, conflicts, optional dependencies, etc.). We are considering a more convenient way to share local setups, though.

> And this method is doing a whole installation from the very bottom, so redundant work is done heavily. It might have kept some irrelevant dependencies to not be reinstalled.

The way ocaml works requires that we recompile everything. But indeed, we should allow `opam switch export --packages=PKGLIST` to do a partial export, containing only the transitive closure of dependencies of `PKGLIST`.

**Comment by carlsagan21** [comment]
Thanks for the kind reply.
Opam 2 is still in Beta, right? I will try that one!
and more than thanks maintaining the awesome package.
