### ISSUE TITLE
opam config is slow in 2.0.0-beta3

### ISSUE THREAD

**Issue by mars0i** [ocaml/opam#3060]
I'm wondering if there may have been a change in opam 2.0.0-beta3 from opam 1.2.2 that would cause `opam config var share` to run slowly.  I finally figured out why my OCaml buffers are loading slowing in vim (on a relatively slow machine).  It's this line in my .vimrc file in a section that only runs with OCaml files:
```
let opamshare=system("opam config var share | tr -d '\n'")
```
If I replace that with a line that executes a similar command that doesn't run `opam config`, buffers load instantly:
```
let opamshare=system("echo /Users/marshall/.opam/default/share | tr -d '\n'")
```
If I leave the line as
```
let opamshare=system("opam config var share | tr -d '\n'")
```
but switch to opam 1.2.2, buffers again load instantly.

If I run `opam config var share` from the shell command line, there is an obvious delay before the path prints out with 2.0.0-beta3, but the output appears instantly with 1.2.2.

```
# opam config report
# opam-version    2.0.0~beta3
# self-upgrade    no
# os              darwin
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            1
# repositories    1 (http), 1 (version-controlled)
# pinned          1 (git)
# current-switch  default
```

**Comment by XVilka** [comment]
Is it still an issue for beta4?

**Comment by AltGr** [comment]
Thanks for reporting. It would be helpful to have more precise timings (`/usr/bin/time opam config var share`) ; running with `--debug` could also help find out what takes time.

Opam 2.0 loads the switch state before it can determine the value of variables. This includes reading the cached repository state at `~/.opam/repo/state.cache` — but if this cache needs refreshing (e.g. after an update of opam), that may indeed take a while. Now, some query commands are run with `--readonly` as a safety measure, and to ensure they are non-blocking, but that might cause the cache not to be regenerated. In that case, just running e.g. `opam list` should regenerate it.

**Comment by mars0i** [comment]
Sorry, I've been meaning to try the latestbeta but haven't around gotten to it.  If the problem still is there I'll give you timings.  There's no question that the phenomenon existed with beta3, but I'll get you more info.  Thanks.

**Comment by AltGr** [comment]
For the record, here is what I get on the current version:
```
% /usr/bin/time opam config var share --debug
00:00.002  GSTATE                  LOAD-GLOBAL-STATE @ /home/lg/.opam
00:00.004  RSTATE                  LOAD-REPOSITORY-STATE @ /home/lg/.opam
00:00.096  RSTATE                  Loaded /home/lg/.opam/repo/state.cache in 0.092s
00:00.166  RSTATE                  Cache found, loading repositories without remote only
00:00.170  RSTATE                  loaded opam files from repo memprof in 0.004s
00:00.170  STATE                   LOAD-SWITCH-STATE @ 4.03.0
00:00.212  STATE                   Detected changed packages (marked for reinstall): {}
00:00.214  STATE                   Switch state loaded in 0.044s
/home/lg/.opam/4.03.0/share
0.17user 0.04system 0:00.22elapsed 98%CPU (0avgtext+0avgdata 131368maxresident)k
0inputs+0outputs (0major+33352minor)pagefaults 0swaps
```
This is still a little too long, and is after the disk cache is filled ; but I guess what you noticed wasn't in this order of magnitude ?
Technically, when a global variable is requested, we could skip loading the full switch and just load `~/.opam/<switch>/.opam-switch/switch-config` to get the answer, which would really be instant.

**Comment by mars0i** [comment]
It turns out that after some investigation, I have no idea how to get beta4.  (!)  I installed beta3 using @dbuenzli 's helpful homebrew script.  I can see where to change tarfile URL in the script, but I don't know what the correct URL for beta4 is.  My guess that simply changing the 3 to a 4 just got me a 404 page.  Where are the beta releases listed?  I've looked everywhere I can think of?  Thanks.

**Comment by XVilka** [comment]
@mars0i easy: https://github.com/ocaml/opam/releases/tag/2.0.0-beta4

**Comment by mars0i** [comment]
Not completely easy for me.  I have not committed to opam 2, but instead followed dbuenzli's [helpful instructions](https://github.com/ocaml/homebrew-ocaml/wiki/From-opam-1.2.2-to-2.0.0-and-back-with-the-OCaml-tap) for switching between 1 and 2.  dbuenzli was kind enough to make it easy, but now I have to go further to figure out how to install a more recent version in such a way that I can easily switch back to v1 if v2 is still too slow for vim--and not screw up my opam setup in the process.  (I've done that in the past and don't really want to start over recompiling everything.)  I know that setting up two versions of opam is not fundamentally difficult, but some time is needed to figure it out, and unfortunately I have to focus on other things at the moment. :-(

**Comment by dbuenzli** [comment]
I didn't have enough time and incentives to update the `brew` repo. Also somehow it seems the betas are no longer properly announced, I wouldn't mind taking the time to update to do so if @AltGr properly coordinated with me. 

In any case @bobbypriambodo was kind enough to PR an update a few hours ago to the latest beta but I'm waiting on @AltGr's solver's expertise before merging it (see the comments there).

**Comment by mars0i** [comment]
Thanks very much @dbuenzli, @bobbypriambodo, @AltGr.  (dbuenzli, I very much appreciated the initial brew config, but didn't feel that it committed you to updating it for every version of opam.  Thanks bobbypriambodo.)

**Comment by mars0i** [comment]
Here are detailed time comparisons with beta4.  Could the warning about Owl or changed packages be causing a delay?

opam 1.2.2:
```
~$ opam --version
1.2.2
~$ /usr/bin/time opam config var share
/Users/marshall/.opam/4.05.0/share
        0.04 real         0.00 user         0.01 sys
~$ time opam config var share  # bash time builtin
/Users/marshall/.opam/4.05.0/share

real	0m0.032s
user	0m0.011s
sys	0m0.017s
~$ /usr/bin/time opam config var share --debug
00:00.014  SYSTEM                  locking /Users/marshall/.opam/lock
00:00.015  CONFIG                  config-variable
/Users/marshall/.opam/4.05.0/share
00:00.015  SYSTEM                  Lock released on /Users/marshall/.opam/lock
        0.03 real         0.01 user         0.01 sys
```
opam 2 beta4:
```
~$ opam --version
2.0.0~beta4
~$ /usr/bin/time opam config var share
/Users/marshall/.opam/default/share
        0.46 real         0.36 user         0.09 sys
~$ time opam config var share  # bash time builtin
/Users/marshall/.opam/default/share

real	0m0.521s
user	0m0.403s
sys	0m0.099s
~$ /usr/bin/time opam config var share --debug
00:00.005  GSTATE                  LOAD-GLOBAL-STATE @ /Users/marshall/.opam
00:00.007  RSTATE                  LOAD-REPOSITORY-STATE @ /Users/marshall/.opam
00:00.178  RSTATE                  Loaded /Users/marshall/.opam/repo/state.cache in 0.170s
00:00.232  RSTATE                  Cache found
00:00.232  STATE                   LOAD-SWITCH-STATE @ default
00:00.234  STATE                   warn: owl has conflicting pinning versions between switch-state (0.2.6) and overlay (dev). Using dev.
00:00.401  STATE                   Detected changed packages (marked for reinstall): { ocaml.4.05.0, ocaml-migrate-parsetree.1.0.4, ocamlmod.0.0.8, ounit.2.0.0, owl.0.2.6 }
00:00.440  STATE                   Switch state loaded in 0.208s
/Users/marshall/.opam/default/share
        0.48 real         0.36 user         0.09 sys
```

**Comment by mars0i** [comment]
Times after `update`, `upgrade`, recompiling and installing Owl:
```
~$ opam --version
2.0.0~beta4
~$ time opam config var share
/Users/marshall/.opam/default/share

real	0m0.549s
user	0m0.356s
sys	0m0.107s
~$ /usr/bin/time opam config var share --debug
00:00.006  GSTATE                  LOAD-GLOBAL-STATE @ /Users/marshall/.opam
00:00.008  RSTATE                  LOAD-REPOSITORY-STATE @ /Users/marshall/.opam
00:00.176  RSTATE                  Loaded /Users/marshall/.opam/repo/state.cache in 0.168s
00:00.239  RSTATE                  Cache found
00:00.239  STATE                   LOAD-SWITCH-STATE @ default
00:00.413  STATE                   Detected changed packages (marked for reinstall): {}
00:00.454  STATE                   Switch state loaded in 0.215s
/Users/marshall/.opam/default/share
        0.50 real         0.37 user         0.09 sys
```

**Comment by AltGr** [comment]
Interesting. Here it takes 0.25s to answer, but the contents is different:
- 0.18s to load the full repository state (from cache)
- 0.07s to load the switch state

the first 0.18s, though, are due to the uncommon fact that there are 8 repositories configured (including many instances of opam.ocaml.org), and the marshalled cache is 34MB. So this doesn't explain why your switch loding takes above 0.2s. It might be a difference between beta4 and beta5 though.

All of this time, in any case, is due to loading the switch state (which requires the repository state to be loaded first), including all definitions for all packages. This is obviously not needed in this case, and I'll see if I can avoid loading the full switch when the variable requested isn't a package variable
