### ISSUE TITLE
tuareg and merlin mode

### ISSUE THREAD

**Issue by LOTP** [ocaml/opam#3076]
dear all
have been installing gnu emacs on mac os and got opam installed as well
i did then install tuareg with opam and it worked very well
things started to go rogue when trying to install merlin on top
so i did an: opam install merlin
then i was prompted that it would recompile tuareg, fine i thought and answered Y
then i did the recommended: opam user-setup install
then opening again emacs on an ocaml file would trigger lisp mode (no longuer tuareg) and doing a M-x tuareg-mode would not work (not recognized). same for M-x merlin-version (or something similar) would not work either
any idea??
best

**Comment by AltGr** [comment]
This should probably be reported here: https://github.com/OCamlPro/opam-user-setup/issues

Could you give the output of `opam user-setup install`, and the added part to your `~/.emacs` (probably the tail) ? You can also try starting emacs with `emacs --debug-init some-ml-file.ml` to see what's going on.
Thanks!

**Comment by LOTP** [comment]
ok thanx. done :)
unfortunatelly this time the install of merlin failed...
so i have posted the result i got in my term.

**Comment by LOTP** [comment]
Hello Louis
I indeed tried to reproduce the whole process, unfortunately the install merlin failed that time (see my post online) so i can’t anymore show you what you’re referring to in your mail
Many thx for your help!

--
Francois Carrez, PhD
Senior Research Fellow
Institute For Communication Systems
(formerly known as CCSR)

University of Surrey, Stag Hill, FEPS/ICS
GU2 7XH, Guildford, Surrey, UK
Phone: +44 (0) 1483 689804
Mobiles: +44 (0) 7989195796 or +33 (0)6 43556167
