### ISSUE TITLE
`opam admin add-constraint` allow to specify a list of excluded packages

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#3077]
Currently this affects all `--depend-on` packages but you may want to specify exceptions. Alternatively you may want to specify only a few that should be affected.

**Comment by dbuenzli** [comment]
`opam admin add-constraint` is truly excellent but sadly falls short because of this issue.

That being said I don't think you want to specify a list of excluded packages, you want to specify a list of affected packages, namely those whose build you witnessed failing. 

A simple way would be to turn the synopsis into: 

```
opam admin add-constraint CONSTRAINT [PKG[.VERSION]...]
```

**Comment by dbuenzli** [comment]
Another useful thing would be to output on stdout the affected files (possibly behind a cli switch).

**Comment by dbuenzli** [comment]
> A simple way would be to turn the synopsis into:
> 
> ```
> opam admin add-constraint CONSTRAINT [PKG[.VERSION]...]
> ```

And to be clear this should also add the constraint on the given packages even if the constraint is not currently in the specified package's deps.

**Comment by kit-ty-kate** [comment]
I don’t personally have time to dedicate to this at the moment but this seems to be "workaroundable" with a simple shell script such as:

`add-constraint-except.sh`:
```
opam admin add-constraint "$1"
sed_args=() ; for pkg in $2; do sed_args=("${sed_args[@]}" -e "/^packages\\/$pkg/{p;n;}"); done
git reset --hard -- $(git status --short | grep "^ M " | sed "s/^ M //" | sed -n "${sed_args[@]}")
```

**Comment by dbuenzli** [comment]
Yes it's always workaroundable with a dose of shell scripting :-(

The add constraint everywhere and then commit only those files you want to change works. But it's a tad annoying. 

For reference in this case combining with @dra27's `sed` runes to get the failure from CI. I get to something like: 

```
opam admin add-constraint 'cmdliner<1.1.0'
curl -Ls https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/9e1c4741f678920dce29d3280af125f48430e81d \
| sed -e 's/>/\n/g' \
| sed -nE 's/^([^ ]*) \(failed: (This|Unbound|The).*/\1/p' \
| sort \
| uniq \
| sed 's/\(\([^\.]*\).*\)/packages\/\2\/\1\/opam/g' \
| git add --pathspec-from-file=-
git checkout packages
git commit -m 'Constrain failures on cmdliner 1.1.0'
```

**Comment by kit-ty-kate** [comment]
just in case you want to have a shot at doing it, it seem relatively easy:

https://github.com/ocaml/opam/blob/2b75470059021b66e28eae92b22ddb1fda607950/src/client/opamAdminCommand.ml#L1036

This would be just a matter of a couple of ifs and a new argument around here I believe

**Comment by dbuenzli** [comment]
After five years, I'm still very very interested in having a good workflow for fixing massive opam-repository failures (see e.g. https://github.com/ocaml/opam-repository/pull/22598) and this is part of it. 

Could this please be put on a release target ?

**Comment by dbuenzli** [comment]
Thank you @rjbou ! I missed the resolution. Look forward to integrate that in my tooling.
