### ISSUE TITLE
opam init failed

### ISSUE THREAD

**Issue by fanzhihang** [ocaml/opam#308]
opam init
Cannot download http://opam.ocamlpro.com/urls.txt, please check your connection settings.
  'opam init' failed
It did not show me any hints to fix the error. What should do to fix it?

**Comment by jaseemabid** [comment]
Same error. 

```
# OPAM status report
# opam-version    1.1.1
# os              linux
# external-solver false
# read-state      # opam-version    1.1.1
# os              linux
File /home/j/.opam/config does not exist
```

**Comment by JohnnyXiao** [comment]
i have the same problem ,but it is OK now
try this way:https://gist.github.com/joridos/673aa658e46a7342b154

**Comment by AltGr** [comment]
This might point to an ipv6 config error on our server ? (or maybe on the user local network ?)
