### ISSUE TITLE
Upgrading version of  path-pinned package

### ISSUE THREAD

**Issue by ttamttam** [ocaml/opam#3080]
When working, I found usefull to pin development directories:
```sh
opam pin add my_package /my/path -k path -y
```

When I modified those pinned packages, if I
```sh
opam update my_package
opam upgrade my_package
```
my modifications are installed, but the version number of the package is not updated.

If I did modify the version in the opam file, I have to do 
```sh
opam pin remove my_package
opam pin add my_package /my/path -k path -y
```
instead.

I'm not sure I'm using opam the right way? Or could/should opam be improved to ease this use case?

**Comment by AltGr** [comment]
Is this with opam 1.2 ? It has been improved, and should update the pinned-to version in opam 2.0 (but there still may be bugs).

Also, note that in:
```
opam update my_package
opam upgrade my_package
```
if `my_package` is pinned, the `upgrade` will update it automatically first, so you can skip the first command :)

**Comment by ttamttam** [comment]
> Is this with opam 1.2 ? It has been improved, and should update the pinned-to version in opam 2.0 (but there still may be bugs).

It is with 2.0.0~beta4.

**Comment by AltGr** [comment]
ok, probably a bug then, I'll check. Thanks for the report!
