### ISSUE TITLE
opam commands crash Linux

### ISSUE THREAD

**Issue by mshultznj** [ocaml/opam#3082]
I am currently running Linux Mint Cinnamon, and have had ocaml and opam installed for a couple weeks now. However recently running opam commands has resulted in no action being taken, and after a couple minutes of delay will completely log me out of my Linux session. I have tried uninstalling and reinstalling opam but I am still having the same issue. Are there any ways to fix this? Does anyone know what might be causing these crashes?

**Comment by dbuenzli** [comment]
This will be difficult to answer without a trace of something. Could you run the offending opam command with `--debug` redirect the output to a file and post it somewhere ?

**Comment by AltGr** [comment]
Which commands ? One possibility would be that the `aspcud` external solver is eating up all available memory (it has been known to do that in some cases). Check if you see a `gringo` or `clasp` process taking up lots of memory after opam was started.

Please report your versions of opam (`opam config report` -- that one should be safe), and of `aspcud`.
If this is the case, opam 2 has a better-behaved solver built-in, which should avoid the issue.
Thanks!

**Comment by AltGr** [comment]
Thanks for reporting. Please reopen if there is further info for opam 2.0.0
