### ISSUE TITLE
opam should warn if the user PATH includes `.`

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#3086]
If it does, one of the effect of this is that `ocamlfind` cannot install on macos (see [here](https://github.com/ocaml/opam-repository/issues/10064#issuecomment-323202164) for the explanation) which basically immediately brings the newcomer in a stuck state. Here's [another occurence](https://discuss.ocaml.org/t/mac-install-questions/1047/13?u=dbuenzli).

**Comment by dbuenzli** [comment]
In fact maybe a few sanity checks like this could simply be put in `opam config report`.

**Comment by AltGr** [comment]
Good idea. If you have ideas for other sanity checks to put there, please tell!

**Comment by dbuenzli** [comment]
Thanks !
