### ISSUE TITLE
Broken links in doc pages

### ISSUE THREAD

**Issue by nickzuber** [ocaml/opam#3103]
I noticed that many of the links in the [pages section](https://github.com/ocaml/opam/tree/master/doc/pages) of the docs reference other files here with a `.html` extension while the files actually have a `.md` since they're markdown. 

Is this intentional? If not, I have a PR ready that changes the extensions to markdown.

**Comment by AltGr** [comment]
The doc is intended to be looked up from https://opam.ocaml.org/doc/2.0 , where it's converted to html, hence the links. Maybe it would be cleaner to link to the `.md`, and rewrite the links, but that seems more involved than needed.
For details, you can look at [opam2web](https://github.com/ocaml/opam2web), which does the conversion and generates the website.
Thanks!
