### ISSUE TITLE
OPAM 2 incorrectly parsing available: expression

### ISSUE THREAD

**Issue by mato** [ocaml/opam#3111]
As seen here: https://github.com/ocaml/opam-repository/pull/10810

The `available` expression

````
available: [
  ocaml-version >= "4.02.3" & ocaml-version < "4.07.0" &
  ((os = "linux" & (arch = "x86_64" | arch = "aarch64")) |
   (os = "freebsd" & arch = "amd64"))
] 
````

appears to be parsed as

````
ERROR] ocaml-freestanding = 0.2.3 unmet availability conditions: os = "linux" & (arch = "x86_64" | arch = "aarch64" | os = "freebsd") & arch = "amd64"
````

Unfortunately I don't have a working OPAM 2 installation so I can't narrow down the behaviour to the simplest failing expression, but hopefully this should be enough information to diagnose.

/cc @avsm

**Comment by hannesm** [comment]
FWIW, it may be a caching issue of the datakit CI (since previous bracketing was different)

**Comment by AltGr** [comment]
Quick test:
```
$ cat test.opam
opam-version: "1.2"
available: [
  ocaml-version >= "4.02.3" & ocaml-version < "4.07.0" &
  ((os = "linux" & (arch = "x86_64" | arch = "aarch64")) |
   (os = "freebsd" & arch = "amd64"))
]
$ opam package-upgrade test.opam
[NOTE] File /tmp/test.opam upgraded to format 2.0~beta5
$ cat test.opam 
opam-version: "2.0"
depends: [
  "ocaml" {>= "4.02.3" & < "4.07.0"}
]
available:
  os = "linux" & (arch = "x86_64" | arch = "aarch64") |
  os = "freebsd" & arch = "amd64"
```

`&` is now prioritised higher than `|`, so some parens could be removed, but this seems correct.

**Comment by mato** [comment]
@AltGr Thanks for testing. Would you mind trying the original expression that caused the error in https://github.com/ocaml/opam-repository/pull/10810, prior to my changing it to the above, which is:

````
available: [
  ocaml-version >= "4.02.3" & ocaml-version < "4.07.0" &
  ((os = "linux" & (arch = "x86_64" | arch = "aarch64") |
   (os = "freebsd" & arch = "amd64")))
] 
````

**Comment by hannesm** [comment]
according to the datakit CI (here https://ci.ocaml.io/log/saved/docker-build-9ca1607c1928ee63d3cd8d795e0794d4/01504b30bccbdf31e1eac13f9969e13a291a929c), the initially mentioned expression still gets misinterpreted by opam2 - or maybe by the opam1 to opam2 conversion?

//cc @avsm

**Comment by AltGr** [comment]
```
$ cat >test.opam
opam-version: "1.2"
available: [
  ocaml-version >= "4.02.3" & ocaml-version < "4.07.0" &
  ((os = "linux" & (arch = "x86_64" | arch = "aarch64") |
   (os = "freebsd" & arch = "amd64")))
] 
$ opam package-upgrade test.opam
[NOTE] File /tmp/test.opam upgraded to format 2.0~beta5
$ cat test.opam 
opam-version: "2.0"
depends: [
  "ocaml" {>= "4.02.3" & < "4.07.0"}
]
available:
  os = "linux" &
  (arch = "x86_64" | arch = "aarch64" | os = "freebsd" & arch = "amd64")
```

This indeed seems weird; I'm looking into it

**Comment by AltGr** [comment]
This is actually a bug in the printer: with `OPAMALLPARENS=1` I get the following, which is correct
```
available:
  ((os = "linux") &
   (((arch = "x86_64") | (arch = "aarch64")) |
    ((os = "freebsd") & (arch = "amd64"))))
```
Thanks a lot for spotting this. You can use that variable as a workaround until fixed.

**Comment by AltGr** [comment]
Fixed by https://github.com/ocaml/opam-file-format/commit/212c615669d2e24ceaf754c190f9beb3ec40da03. Oops
