### ISSUE TITLE
opam2: opam-installer seems to need an initialised ~/.opam

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#3114]
When doing a fresh clone and make and make install on osx, I see:

```
$ make install
src_ext/jbuilder/_build/install/default/bin/jbuilder build  opam-installer.install opam.install
        opam (internal)
[ERROR] No OPAM root found at /Users/avsm/.opam.
        Please run 'opam init' to initialize the state of OPAM, or specify
        '--root'.
        See 'opam init --help' for details.
    ocamldep src/core/opam_core.dependsi.ocamldep-output
```

Something isn't quite right here -- none of the tools should be looking inside $HOME while building and installing into a fake root.

**Comment by avsm** [comment]
Worse; it appears to have created a half-initialised `~/.opam` during `make install`.  I think that should only happen on the first `opam init`

**Comment by AltGr** [comment]
well, `jbuilder` calls `opam config env` to select the proper OCaml compiler. Maybe it could make more effort to detect if opam is initialised, rather than just checking if the binary exists.
It seems indeed that opam may create `~/.opam/lock` even if uninitialised (and outside of `opam init`), which is clearly wrong though.

**Comment by avsm** [comment]
cc @rgrinberg re: the possible jbuilder issue

**Comment by rgrinberg** [comment]
Should opam perhaps error out if you call `$ opam config env` without it being initialized? It does seem like there's a jbuilder issue here regardless though. How should we detect if opam has been initialized in jbuilder?

**Comment by AltGr** [comment]
It should already be the case:
```
% OPAMROOT=/tmp/notexist opam env     
[ERROR] Opam has not been initialised, please run `opam init'
<exits with 50>
```
but there was a bug causing the directory to be created. It has now been fixed.

**Comment by avsm** [comment]
thanks @altgr!
