### ISSUE TITLE
new stable release?

### ISSUE THREAD

**Issue by zepatrik** [ocaml/opam#3118]
If I see this right, the latest stable release is 1.2.2 from 2015. Therefore this is the latest version available on the arch repository and I think in other repos too. But that version is not working in arch, the latest master is. Maybe you could make a stable release some time to get package managers a newer version than a over 2 year old. I think the newest beta might be more stable than 1.2.2, but that's up to you.

The problem with 1.2.2 was some resolver issue with aspcud. I didn't want to make a new issue for a 2 year old version so I just installed opam from this repo and it works.

But if you rather would like to update 1.2.2 I can track down the issue.

**Comment by AltGr** [comment]
This is true. I have been wanting to release for a while, but so far the blocker had been that the repository format changed, and migrating https://github.com/ocaml/opam-repository could cause trouble — so it was decided to postpone until a few more things were finalised, e.g. recently the new format for "depexts".

So while the recent betas are quite stable, they use a rewriting on the main repository, and it makes sense not to mark them as "stable" until the repository is going to be fully switched to their format.

I think that now everything is in order, the next stable isn't too far, though. I am now releasing a beta5 which, hopefully, might make it to stable with few changes.

**Comment by Drup** [comment]
@zepatrik The real problem here is that Arch packages are (again ?!) broken, probably because of aspcud/gringo. This is not (completely) opam 1.2.2's fault and it was working on arch a few month ago.

**Comment by zepatrik** [comment]
Yep, the log was about aspcud and gringo
So basically anyone having the issue, just install the beta form this repo for now
