### ISSUE TITLE
commit 4352dfafa8c9eae84eb29d950039ab7af676e9ed

### ISSUE THREAD

**Issue by toolslive** [ocaml/opam#3121]
breaks our automatic builds.

**Comment by toolslive** [comment]
our docker setup executes the following.
```
env ocaml_version=4.04.2
RUN sh ./opam_installer.sh /usr/local/bin ${ocaml_version}
```
and the new opam installer script no longer even accepts these parameters.

**Comment by AltGr** [comment]
Hmm, you mean you were using the version of the script from master ?
Nevermind then, I'll keep it as legacy and create a new one.
