### ISSUE TITLE
Builtin mccs solver can fail to solve real world install request

### ISSUE THREAD

**Issue by jorisgio** [ocaml/opam#3130]
a simple `opam install opam-publish` "hangs" forever from user point of view.
I think there are two issues : 
1. absence of feedback/timeout. The command seems stuck, i killed it several time, tried to install other packages before realizing it was solver running forever at 100% cpu.
A warning about long solver runtime and a timeout looks like a good idea, it does not look probable someone will wait more than 20 minutes for the solver to finish.
2. the actual cudf problem. Aspcud can solve it just fine (in under 1second).

[install.cudf-1.cudf.gz](https://github.com/ocaml/opam/files/1526239/install.cudf-1.cudf.gz)

opam version `2.0.0~beta4` 
mccs solver info: 
```00:00.301  CLIENT                  Orphans: (changes: { opam-publish.0.2.0, opam-publish.0.2.1, opam-publish.0.3.0, opam-publish.0.3.0+transition, opam-publish.0.3.5
}, transitive: false) -> full {}, versions {}
00:00.404  SOLVER                  resolve request=install:(opam-publish) remove:() upgrade:()
00:00.405  SOLVER                  cudf_versions_map
00:00.512  SOLVER                  Load cudf universe (depopts:false, build:true)
00:00.512  SOLVER                  Load cudf universe: opam2cudf
00:00.850  SOLVER                  Load cudf universe: done in 0.338s
00:00.850  CUDF                    resolve request=install:(opam-publish) remove:() upgrade:()
00:04.114  SOLVER                  Calling solver builtin-mccs+glpk with criteria -removed,-count[version-lag:,true],-changed,-count[version-lag:,false]
Initial size: 7877 packages (153 installed, 7724 uninstalled), 1860 virtual packages
Final size: 2331 packages (153 installed, 2178 uninstalled), 298 virtual packages
Constructing initial basis...
Constructing conflict graph...
Conflict graph has 1539 + 560 = 2099 vertices
```
attached is the full cudf passed to the solver

**Comment by AltGr** [comment]
Are you using beta5 ? A timeout _was_ added (set to 1 minute by default), exactly for the reason you mention as 1.

It seems from the log the criteria used are `-removed,-count[version-lag:,true],-changed,-count[version-lag:,false]`, which are the unoptimised criteria (before #3089). Try a newer version!
