### ISSUE TITLE
opam-init/init.zsh creates infinite loop of new Finder and Terminal windows

### ISSUE THREAD

**Issue by dangodev** [ocaml/opam#3133]
**My setup**
- macOS High Sierra 10.13.1
- iTerm
- [Oh My Zsh](https://github.com/robbyrussell/oh-my-zsh) flavor of Z shell

**Steps to reproduce**
Running `opam init` and then modifying `~/.zshrc` with the following line (either manually, or as part of `opam init`):
```
. /Users/drew/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
```

The initial `.` opens a new Finder window, then another Terminal window, indefinitely in an infinite loop, until I’m able to delete the `~/.opam` folder in between window openings.

It’s a bit hard to debug and get more info because it hijacks my system, and I’m a little tired playing whack-a-mole with the ever-opening Finder windows.

**Comment by AltGr** [comment]
Ouch, that looks like an extremely bad behaviour indeed. Sorry about it.

```
. /Users/drew/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
```
> The initial . opens a new Finder window

Now that is extremely surprising, I have never heard of such a behaviour, this shouldn't pop any new windows! What does `which .` return on your system ? `.` is in general well specified, and mostly equivalent to `source`. IIRC we chose the former for reasons of slightly better compatibility.

From the `zsh` manpage:
```
       source file [ arg ... ]
              Same as `.', except that the current directory is always searched
              and is always searched first, before directories in $path.
```
`bash` manpage:
```
       source filename [arguments]
              Read and execute commands from filename in  the  current  shell  environment  and
              return  the  exit status of the last command executed from filename.  If filename
              does not contain a slash, filenames in PATH are used to find the  directory  con‐
              taining  filename.
```

Can you please check the scripts in `/Users/drew/.opam/opam-init/` ? They should be fairly straightforward, here I have:
init.zsh
```bash
# Load the environment variables
test -r /home/lg/.opam/opam-init/variables.sh && . /home/lg/.opam/opam-init/variables.sh > /dev/null 2> /dev/null || true

# Load the auto-complete scripts
if tty -s >/dev/null 2>&1; then
  test -r /home/lg/.opam/opam-init/complete.zsh && . /home/lg/.opam/opam-init/complete.zsh > /dev/null 2> /dev/null || true
fi
```
variables.sh
```bash
# Prefix of the current opam switch
OPAM_SWITCH_PREFIX='/home/lg/.opam/4.05.0'; export OPAM_SWITCH_PREFIX;
[...]
# Binary dir for opam switch 4.05.0
PATH='/home/lg/.opam/4.05.0/bin':"$PATH"; export PATH;
```
complete.zsh
```bash
#compdef opam

if [ -z "$ZSH_VERSION" ]; then return 0; fi
[...] # some function definitions
autoload bashcompinit
bashcompinit
complete -F _opam opam
```

My guess would be that one of the commands used in the scripts is somehow overriden on your system (maybe `complete` ? One of `tty`, `test`, `export` would probably make the system more generally unusable...). Could you try running `which` on them ?

**Comment by dangodev** [comment]
Ah! Good call. I had remapped `.` to `ofd`. 🤦‍♂️ My mistake! Let me remove that to see if it runs like it should on my setup.

**Comment by dangodev** [comment]
Removed the shortcut; now works great on my setup. Thanks for your time!
