### ISSUE TITLE
opam-init/variables.sh does not appreciate local switches

### ISSUE THREAD

**Issue by bobbypriambodo** [ocaml/opam#3134]
opam version: 2.0.0~beta5

I'm not sure whether this is an intended behavior or not, but it would seem that `variables.sh` only appreciate global switches.

```bash
~ $ opam switch 4.04.2
~ $ cat ~/.opam/opam-init/variables.sh
# Prefix of the current opam switch
OPAM_SWITCH_PREFIX='/Users/bobbypriambodo/.opam/4.04.2'; export OPAM_SWITCH_PREFIX;
# Updated by package ocaml-base-compiler
CAML_LD_LIBRARY_PATH='/Users/bobbypriambodo/.opam/4.04.2/lib/stublibs'; export CAML_LD_LIBRARY_PATH;
...

~ $ opam switch 4.02.3+buckle-master
~ $ cat ~/.opam/opam-init/variables.sh
# Prefix of the current opam switch
OPAM_SWITCH_PREFIX='/Users/bobbypriambodo/.opam/4.02.3+buckle-master'; export OPAM_SWITCH_PREFIX;
# Updated by package ocaml-variants
CAML_LD_LIBRARY_PATH='/Users/bobbypriambodo/.opam/4.02.3+buckle-master/lib/stublibs'; export CAML_LD_LIBRARY_PATH;
...

~ $ cd Projects/ezpostgresql             # project with local switch

~/Projects/ezpostgresql $ ls _opam
bin  doc  lib  man  sbin  share

~/Projects/ezpostgresql $ eval `opam env`

~/Projects/ezpostgresql $ cat ~/.opam/opam-init/variables.sh
# Prefix of the current opam switch   ====> NOTE: still 4.02.3+buckle-master
OPAM_SWITCH_PREFIX='/Users/bobbypriambodo/.opam/4.02.3+buckle-master'; export OPAM_SWITCH_PREFIX;
# Updated by package ocaml-variants
CAML_LD_LIBRARY_PATH='/Users/bobbypriambodo/.opam/4.02.3+buckle-master/lib/stublibs'; export CAML_LD_LIBRARY_PATH;
...
```

This particularly messes up PATH of tooling for projects with local switches, like [here](https://github.com/OCamlPro/ocp-indent/issues/259).

**Comment by AltGr** [comment]
`variables.sh` is static. It is designed for shell initialisation, and can only refer to the globally selected switch. 

When a switch is selected dynamically, i.e. in a specific shell instance (through setting `OPAMSWITCH`, `eval $(opam env --switch SW)`, or being in a directory containing a local switch), you can't use that file. You need to call `opam env [--readonly]` instead.

It's unfortunately not possible to keep the `variables.sh` file static and have it adapt to dynamic situations. If you need dynamic, call `opam env`.
