### ISSUE TITLE
Multi pin over http doesn't work.

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#3139]
If I do `opam pin add https://github.com/ocsigen/tyxml.git`, opam will pin both `tyxml` and `tyxml-ppx` with git-pins.

However, if I do `opam pin add https://github.com/ocsigen/tyxml/`, opam uses http-pin (as expected) but only pin `tyxml`, and not `tyxml-ppx`!

(multi-pin is awesome, btw)

------

```
% opam --git-version
e6a17cc467e3b647ec3c56950c250ddadc672eb8
```

**Comment by AltGr** [comment]
I think the latter won't work at all: for http pin, you need to provide the URL to the archive (then opam will uncompress it and should find the proper package definitions). With ‘https://github.com/ocsigen/tyxml/‘, the package name has probably been inferred from the URL, but you won't get a usable package, th download yielding just some HTML.

This is a common mistake, though. One way to mitigate could be to build in some detection of Github URLs and default to the git backend (or even infer the archive URL?), as it's a very common case.

**Comment by Drup** [comment]
Ah, I see. I stopped as soon as I saw it only pined one package, and didn't tried the instalation.

I think adding some auto-detection would be a nice thing. Alternatively, you could detect that you only downloaded some pice of HTML and show a warning (maybe more general).

**Comment by AltGr** [comment]
Indeed, this doesn't actually follow the docs, which state that the URL must yield an archive. In fact, opam is more tolerant than that, and if the file is not found to be a known archive type, it's simply copied over as the whole of the source. This is actually useful in a few cases, like [pinning a virtual package to a remote `opam` file](http://opam.ocaml.org/doc/2.0/Tricks.html#Provide-a-set-of-packages-for-a-group-of-users-to-install). But in this case it's quite harmful.

This is not strictly needed for the trick linked to above, as Github offers to donwload gists as zips too. But now that the feature is here I am afraid I could break use-cases that I have forgotten about by removing it… I'll try locally for now.
