### ISSUE TITLE
make pinning private github repository more intuitive

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#3144]
This url works:

```
opam pin add foo git+ssh://git@github.com/avsm/dev.git
```

but the more intuitive one is something like:

```
opam pin add foo git@github.com:avsm/dev
```

As works with `git clone`.  It took me quite a few iterations of the URL that worked before I realised that I forgot the additional `git@`

**Comment by avsm** [comment]
Also, if you accidentally do 'git+ssh://git@github.com:avsm/dev.git' (colon instead of /), then the pin hangs indefinitely

**Comment by AltGr** [comment]
Hmm, weird, is that with 2.0 ? Opam should correctly parse the `user@host:dir` form, and transform it to the standard (but unintuitive, I agree on that!) `ssh://user@host/dir`. That seems to work here on 2.0 (the refactored URL handling was part of 1.3 IIRC).

> Also, if you accidentally do 'git+ssh://git@github.com:avsm/dev.git' (colon instead of /), then the pin hangs indefinitely

Here I get a DNS error on `github.com:asvm`. Could you run with `-vv` to see what happens with `git` ? Maybe you have ssh aliases for `avsm` and it's asking you for credentials ?

**Comment by avsm** [comment]
Sure:

```
$ opam pin add foo git@github.com:avsm/foo -vv
+ /usr/local/bin/ocamlc "-vnum"
- 4.06.0
[ERROR] Error getting source from ssh://git@github.com/avsm/foo
'opam pin add foo git@github.com:avsm/foo -vv' failed.
```

And

```
$ opam pin add foo git+ssh://git@github.com/avsm/foo.git -vv
+ /usr/local/bin/ocamlc "-vnum"
- 4.06.0
+ /usr/bin/git "init" (CWD=/Users/avsm/src/git/avsm/ocaml-dockerfile/_opam/.opam-switch/sources/foo)
- Initialized empty Git repository in /Users/avsm/src/git/avsm/ocaml-dockerfile/_opam/.opam-switch/sources/foo/.git/
+ /usr/bin/git "config" "--local" "fetch.prune" "false" (CWD=/Users/avsm/src/git/avsm/ocaml-dockerfile/_opam/.opam-switch/sources/foo)
+ /usr/bin/git "remote" "add" "origin" "ssh://git@github.com/avsm/foo.git" (CWD=/Users/avsm/src/git/avsm/ocaml-dockerfile/_opam/.opam-switch/sources/foo)
+ /usr/bin/git "remote" "set-url" "origin" "ssh://git@github.com/avsm/foo.git" (CWD=/Users/avsm/src/git/avsm/ocaml-dockerfile/_opam/.opam-switch/sources/foo)
+ /usr/bin/git "fetch" "-q" "ssh://git@github.com/avsm/foo.git" "--update-shallow" "+HEAD:refs/remotes/opam-ref" (CWD=/Users/avsm/src/git/avsm/ocaml-dockerfile/_opam/.opam-switch/sources/foo)
- ERROR: Repository not found.
- fatal: Could not read from remote repository.
-
- Please make sure you have the correct access rights
- and the repository exists.
+ /usr/bin/git "fetch" "-q" "ssh://git@github.com/avsm/foo.git" (CWD=/Users/avsm/src/git/avsm/ocaml-dockerfile/_opam/.opam-switch/sources/foo)
- ERROR: Repository not found.
- fatal: Could not read from remote repository.
-
- Please make sure you have the correct access rights
- and the repository exists.
[ERROR] Could not synchronize /Users/avsm/src/git/avsm/ocaml-dockerfile/_opam/.opam-switch/sources/foo from
        "git+ssh://git@github.com/avsm/foo.git":
        "/usr/bin/git fetch -q ssh://git@github.com/avsm/foo.git" exited with code 128 "ERROR: Repository not found."
[ERROR] Error getting source from git+ssh://git@github.com/avsm/foo.git
'opam pin add foo git+ssh://git@github.com/avsm/foo.git -vv' failed.
```

**Comment by AltGr** [comment]
Ah, I see. Actually, the URL was rewritten correctly in the first case (`git@github.com:avsm/foo` becomes `ssh://git@github.com/avsm/foo`). But opam doesn't infer this as a `git` address, but a pure `ssh` one (yes, that's allowed, through rsync!).  And of course Github rejects the request.

Since we already handle the `.git` suffix from the command-line, I guess it would be safe to switch to the git backend when the username happens to be `git` ? :)

**Comment by avsm** [comment]
I never realised we could do ssh over rsync! :-) 

I guess that `git@github.com:avsm/foo.git` will work without problems.  Perhaps we should just document this in the man page rather than putting in more heuristics. Particularly because a common setup is to have an `~/.ssh/config` file that automatically adds the `git@` username to `Host github.com`.
