### ISSUE TITLE
ocp-ocamlres error

### ISSUE THREAD

**Issue by munakaya** [ocaml/opam#3154]
"opam pin add --no-action --dev-repo sodium"
and "opam pin add --no-action --dev-repo ocplib-json-typed"
works fine.

opam pin add --no-action --dev-repo ocp-ocamlres
does not work.

Any tips for this?

user@user-PMBSB09A-Samsung-DeskTop:~/my_work/tezos/tezos$ opam pin add --no-action --dev-repo ocp-ocamlres
[NOTE] Package ocp-ocamlres is already git-pinned to git://github.com/OCamlPro/ocp-ocamlres.
This will erase any previous custom definition.
Proceed ? [Y/n] Y

[ERROR] Command "git fetch -q origin" failed:
/# opam-version 1.2.2
/# os linux
/# command git fetch -q origin
/# path /home/user/.opam/tezos/packages.dev/ocp-ocamlres
/# exit-code 128
/# env-file /home/user/.opam/log/log-27306-1872ec.env
/# stdout-file /home/user/.opam/log/log-27306-1872ec.out
/# stderr-file /home/user/.opam/log/log-27306-1872ec.err
/### stderr ###
/# fatal: read error: Connection reset by peer

user@user-PMBSB09A-Samsung-DeskTop:~/my_work/tezos/tezos$

my env is as following

user@user-PMBSB09A-Samsung-DeskTop:~/.opam/tezos/packages.dev$ opam show git
package: git
version: 1.11.3
repository: default
upstream-url: https://github.com/mirage/ocaml-git/releases/download/1.11.3/git-1.11.3.tbz
upstream-kind: http
upstream-checksum: 18254fe863fa8164f2a931f62392cb66
homepage: https://github.com/mirage/ocaml-git
bug-reports: https://github.com/mirage/ocaml-git/issues
dev-repo: https://github.com/mirage/ocaml-git.git
author: Thomas Gazagnaire
license: ISC
doc: https://mirage.github.io/ocaml-git/
depends: jbuilder & mstruct >= 1.3.1 & ocamlgraph & uri >= 1.3.12 & lwt >= 2.4.7 & logs & fmt & hex & astring & ocplib-endian & decompress >= 0.6
installed-version:
available-versions: 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0, 1.11.0, 1.11.2, 1.11.3
description: Git format and protocol in pure OCaml

Support for on-disk and in-memory Git stores. Can read and write all
the Git objects: the usual blobs, trees, commits and tags but also
the pack files, pack indexes and the index file (where the staging area
lives).

All the objects share a consistent API, and convenience functions are
provided to manipulate the different objects. For instance, it is
possible to make a pack file position independent (as the Zlib
compression might change the relative offsets between the packed
objects), to generate pack indexes from pack files, or to expand
the filesystem of a given commit.

user@user-PMBSB09A-Samsung-DeskTop:~/.opam/tezos/packages.dev$ opam list

Installed packages for tezos:
base-bigarray base Bigarray library distributed with the OCaml compiler
base-bytes base Bytes library distributed with the OCaml compiler
base-num base Num library distributed with the OCaml compiler
base-threads base Threads library distributed with the OCaml compiler
base-unix base Unix library distributed with the OCaml compiler
conf-m4 1 Virtual package relying on m4
conf-pkg-config 1.0 Virtual package relying on pkg-config installation.
cppo 1.6.0 Equivalent of the C preprocessor for OCaml programs
cstruct 3.1.1 (pinned) Access C-like structures directly from OCaml
ctypes 0.13.1 Combinators for binding to C libraries without writing any C.
depext 1.0.5 Query and install external dependencies of OPAM packages
integers 0.2.2 Various signed and unsigned integer types for OCaml
jbuilder 1.0+beta16 Fast, portable and opinionated build system
lwt 3.2.0 Promises, concurrency, and parallelized I/O
num 0 The Num library for arbitrary-precision integer and rational arithmetic
ocaml-migrate-parsetree 1.0.7 Convert OCaml parsetrees between different versions
ocamlbuild 0.12.0 OCamlbuild is a build system with builtin rules to easily build most OCaml projects.
ocamlfind 1.7.3-1 A library manager for OCaml
ocplib-endian 1.0 Optimised functions to read and write int16/32/64 from strings and bigarrays, based on new primitives added in version 4.01.
ppx_tools_versioned 5.0.1 A variant of ppx_tools based on ocaml-migrate-parsetree
result 1.2 Compatibility Result module
sexplib v0.10.0 Library for serializing OCaml values to and from S-expressions
topkg 0.9.1 The transitory OCaml software packager
user@user-PMBSB09A-Samsung-DeskTop:~/.opam/tezos/packages.dev$

**Comment by munakaya** [comment]
Result log with -vv

opam pin add --no-action --dev-repo ocp-ocamlres -vv
[NOTE] Package ocp-ocamlres is already git-pinned to git://github.com/OCamlPro/ocp-ocamlres.
       This will erase any previous custom definition.
Proceed ? [Y/n] Y

+ git "init" (CWD=/home/user/.opam/tezos/packages.dev/ocp-ocamlres)
- Initialized empty Git repository in /home/user/.opam/tezos/packages.dev/ocp-ocamlres/.git/
+ git "remote" "add" "origin" "git://github.com/OCamlPro/ocp-ocamlres" (CWD=/home/user/.opam/tezos/packages.dev/ocp-ocamlres)
+ git "commit" "--allow-empty" "-m" "opam-git-init" (CWD=/home/user/.opam/tezos/packages.dev/ocp-ocamlres)
- [master (root-commit) c7bbdac] opam-git-init
+ git "fetch" "-q" "origin" "+HEAD:refs/remotes/opam-ref" (CWD=/home/user/.opam/tezos/packages.dev/ocp-ocamlres)
- fatal: read error: Connection reset by peer
+ git "fetch" "-q" "origin" (CWD=/home/user/.opam/tezos/packages.dev/ocp-ocamlres)
- fatal: read error: Connection reset by peer
'opam pin add --no-action --dev-repo ocp-ocamlres -vv' failed.
[ERROR] Command "git fetch -q origin" failed:
/# opam-version 1.2.2
/# os           linux
/# command      git fetch -q origin
/# path         /home/user/.opam/tezos/packages.dev/ocp-ocamlres
/# exit-code    128
/# env-file     /home/user/.opam/log/log-26434-1872ec.env
/# stdout-file  /home/user/.opam/log/log-26434-1872ec.out
/# stderr-file  /home/user/.opam/log/log-26434-1872ec.err
/### stderr ###
/# fatal: read error: Connection reset by peer

**Comment by dbuenzli** [comment]
> git://github.com/OCamlPro/ocp-ocamlres

It seems's `ocp-ocamlres`'s `dev-repo:` field is wrong. IIRC you can't git clone such an address on github if you are not the owner of the repo,  try to pin to an `https` address.

**Comment by munakaya** [comment]
oh I see. Would would please give me some tips for which file should I fix?

pin add --no-action --dev-repo ocp-ocamlres
commands found the git as "git://github.com/OCamlPro/ocp-ocamlres"

[NOTE] Package ocp-ocamlres is already git-pinned to git://github.com/OCamlPro/ocp-ocamlres.
