### ISSUE TITLE
v2~beta5: `make lib-ext` doesn't compile with 4.06

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#3156]
ocamlgraph needs to be updated to 1.8.8 and it seems that the [`re/nobytes`](https://github.com/ocaml/opam/blob/7e4c657a957ac5befbe43ddb9dd179acc544a6ba/src_ext/patches/re/nobytes-1.7.1.patch) patch reverts safe-stringability from `re`.

**Comment by dbuenzli** [comment]
Also `dose3` seems to need [patching](https://github.com/ocaml/opam-repository/commit/67ba4551c01c1378eb756f460afdd045ee890350)

**Comment by dra27** [comment]
See #3150

**Comment by dra27** [comment]
(the re patch was a legacy as reverting safe-stringability also restored 3.12-4.01 compatibility)

**Comment by dbuenzli** [comment]
Duplicate of #3146
