### ISSUE TITLE
opam2 exec: error message leaks an exception and has a different error code from shell

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#3158]
```
opam exec -- foo
Fatal error: exception opam: "execvpe" failed on foo: No such file or directory
```

The error code returned is also `2`, which seems incorrect for the result of a subshell.  Would it be better to do the same as the shell and return 127 in this case, so that `opam exec` is as transparent as possible?

**Comment by AltGr** [comment]
Indeed, thanks for the suggestion!
