### ISSUE TITLE
Built-in solver limitations

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam#3161]
I've just managed to hit another explosion of the internal solver. Context to reproduce:
- Fresh `ocaml-system.4.02.3` switch
- opam at 6a5779a45f6f05290207f0efc7938df6e7b775a2 (just after beta6, 2017-12-20) with built-in solver
- repo as of dec. 18th (083c78814442f463b121c9c43a047907543ab69d)
- just run `opam install github`. The more precise `opam install github.2.3.0` works as well.

Some notes:
- aspcud solves it without problem
- removed the depopts, conflicts, same result
- actually the solution is not that far away: if we explicit the direct dependencies in the request:
  ```
  opam install 'github.2.3.0' tls 'uri>=1.9.0' 'cohttp>=0.17.0' 'lwt>=2.4.4' 'atdgen>=1.10.0' 'yojson>=1.2.0' 'stringext' 'lambda-term' 'ocaml>=4.02.3' 'cmdliner>=0.9.8' 'base-unix' 'ocamlfind' 'ocamlbuild'`
  ```
  this is solved easily by mccs as well. The following workaround even works:
  ```
  opam install github $(opam list -s --required-by github.2.3.0)
  ```
- Actually this can in this case be reduced to just `opam install github cohttp`. There are currently 48 releases of cohttp in the repo. maybe that is a little excessive ?

The above may seem weird but is actually easy to understand if you look closely at the criteria
```
-removed,-count[version-lag,request],-count[version-lag,changed],-changed
```
The only effect of adding the direct dependencies of `github` to the request is to the second criterion here: the solver will optimise the versions of the requested packages first. In the first case, `opam install github.2.3.0`, this criterion can be completely ignored, so we basically fall back to the next one. In the expanded case, the versions of the direct dependencies are optimised first, which apparently drives us to the solution relatively easily.

The next criterion, `-count[version-lag,changed]`, in fact applies to all packages since we are on a fresh switch. That makes a lot, and the resulting formula is probably too big to be well handled by glpk. In fact, in our case the criteria would be equivalent to:
```
-count[version-lag,solution],-new
```
since on our fresh switch, nothing is allowed to be removed, the requested package is fixed and any change has to be an addition.

Last note: this makes it look like mccs is crap compared to aspcud. Remember, though, that with compilers-as-packages we already had to add a layer of filtering of packages specifically for aspcud, without which it would completely collapse. That filtering was wholly unneeded (and is without a noticeable effect) on mccs, which does its own trimming.

**Comment by Drup** [comment]
> The next criterion, -count[version-lag,changed], in fact applies to all packages since we are on a fresh switch.

Maybe my understanding of the query language is too limited, but I don't understand this. Shouldn't this apply only to packages that are part of the solution?

Also, since the transformation seem pretty harmless, would it be possible to automatically add all the direct dependencies to the query ?

**Comment by avsm** [comment]
Would it help to reset the opam-repository a little for opam2, and make the minimum supported version of packages to be (e.g.) OCaml 4.03.0 via an automated filter?  We could still provide the older packages in a separate remote, and just break up the current packages.

**Comment by Drup** [comment]
I do not think this is a great solution, and I doubt this would even properly solve the problem. If we simply cut a bit of the package set, It's simply a matter of time until we get issues again.

**Comment by avsm** [comment]
Well yes, but it buys us a year or so to solve it properly.  It generally seems a good discipline to partition our package sets in the longer term.

**Comment by AltGr** [comment]
> I do not think this is a great solution, and I doubt this would even properly solve the problem. If we simply cut a bit of the package set, It's simply a matter of time until we get issues again.

The problem is two-fold, and we can not ignore one side:
- the repo is still small as it is, and opam needs to handle many more packages to come
- solving is NP-complete, and we can only scale so far

So cleaning up the repo (on a regular basis) is as important as optimising opam. I don't pretend it's a solution, though, just the other side of the problem. There is also the question of the shape of the problem: the same solvers scale to many, many more packages in debian, but they don't get more than a handful releases per package. I do think 48 is excessive and we shouldn't really need it. Rest assured I am still working to make it work and this isn't like a quick way out ;)

**Comment by dra27** [comment]
This solver issue (and others) is increasing my belief that we should be asking at `opam init` to send canonical solver requests to opam.ocaml.org so that we can have a corpus of real requests to analyse for solver changes...

**Comment by AltGr** [comment]
That's actually what the Mancoosi folks were hoping to do with the "irill solver farm". Unfortunately, no one got affected to it and the consequence was that it got poorly maintained, and never extended.
They still value very high a corpus of real-world, difficult package installation problems (and I try to keep track of all difficult `.cudf` files I get by). It's possible they could use them to organise a new [MISC competition](http://www.mancoosi.org/misc/).

**Comment by AltGr** [comment]
> >  The next criterion, -count[version-lag,changed], in fact applies to all packages since we are on a fresh switch.
> 
> Maybe my understanding of the query language is too limited, but I don't understand this. Shouldn't this apply only to packages that are part of the solution?

Yes, all packages that are part of the solution (_solution_ meaning all packages that will be installed after resolution). Which, at this point, might be any available package.

> Also, since the transformation seem pretty harmless, would it be possible to automatically add all the direct dependencies to the query ?

Not really: might help in this case, but we can't be sure how generic it is. And it would mean the criteria won't really optimise what their specification says they should.

> Would it help to reset the opam-repository a little for opam2, and make the minimum supported version of packages to be (e.g.) OCaml 4.03.0 via an automated filter? We could still provide the older packages in a separate remote, and just break up the current packages.

The filtering on compiler versions is already done dynamically by opam, so that wouldn't help (it's actually part of the preprocessing that aspcud needs, but mccs doesn't). 


Don't worry, I'll find something ;)

**Comment by AltGr** [comment]
I am closing this precise issue, although this obviously remains a constant concern !

**Comment by abate** [comment]
@rdicosmo !
