### ISSUE TITLE
Disjunctive dependencies and choice

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#3172]
I tried to find an answer in the docs without success. Assuming a package `q` with:
```
depends: [ "p1" | "p2" | "p3" ]
```
and a switch state where none of `p{1,2,3}` are installed and `opam instal q` is invoked.

1. Is there a convention on which one will be selected ?
2. Is there a way to specify a preference ? 
3. Would it maybe make sense to simply interactively ask the user ?

**Comment by Drup** [comment]
> Is there a convention on which one will be selected ?

No.

> Is there a way to specify a preference ?

No. I remember requesting that a long time ago, I think it's a solver limitation.

> Would it maybe make sense to simply interactively ask the user ?

I'm afraid that would make things *very* noisy to the point of being unusable. But otherwise, I guess the answer is:

# 🎉  Features 🎉

**Comment by dbuenzli** [comment]
> I'm afraid that would make things very noisy to the point of being unusable

I'm not sure I see why. It seems to me that disjunctive between packages in deps are not so widespread. Note that the idea here is to do so for a disjunction when all package *names* are all uninstalled not for e.g. a disjunction of versions for the same package. This is basically for when you do [this](https://github.com/ocaml/opam/blob/master/doc/pages/Tricks.md#alternate-implementations-for-a-package).

In any case I don't mind instructing people to do an `opam install (p0|p1|p2) q` however I think it would still be nice to be able to specify a default one if none is currently installed (i.e. at least 2.).

**Comment by AltGr** [comment]
As @drup mentionned:
1. No, although your solver criteria might play a role (depending on the respective version-lag of the dependencies, and how many new packages they will pull)
2. Except by specifying it on the command-line, no. A preference would have to be intermingled with the criteria, which doesn't seem easy to do. Not impossible, though, if we were to use something like what Debian does for `recommended` dependencies and the `-unsat-recommends` criterion. A bit heavy though.
3. The black-box nature of the solver prevents us from doing so.

Indeed, the (new) `features:` field could somewhat help: you could name subsets of your dependencies, e.g.
```
features: [ foo { "p1" } {"Package installed with p1 yields feature foo"} ]
```
then advising e.g. `opam install pkg%foo`.
Note that this is not implemented (although the `features:` syntax is defined).

**Comment by dbuenzli** [comment]
Ok thanks for the answers. `features` could indeed be a nice way of specifying more complex preferences.
