### ISSUE TITLE
2.0.0~beta6: opam update keeps removing local modifications to my pinned packages

### ISSUE THREAD

**Issue by drvink** [ocaml/opam#3183]
Whenever I do `opam update` and one of the version-pinned packages against which I've made changes to the `opam` file and/or added patches gets updated, opam deletes `~/.opam/the_switch/.opam-switch/overlay/the_package/files` and/or resets the `opam` file. The old versions remain in `~/.opam/the_switch/.opam-switch/packages/the_package`, but I have to copy them back into place, merging whatever changes there may have been.

This definitely didn't happen with 1.2.2--it would ask if you wanted to use the newer versions, and if you answered yes, would move the old files to `~/.opam/backup`--and I'm pretty sure was not happening as of a few betas ago, either.

**Comment by AltGr** [comment]
Thanks for reporting. This sounds like a bug, the code for detecting conflicts and asking whether to overwrite or not is still there. I'll investigate.
