### ISSUE TITLE
List of tools used by opam

### ISSUE THREAD

**Issue by jpdeplaix** [ocaml/opam#3197]
Is there a list available somewhere of the tools that could be used by opam ? (e.g. rsync, tar, patch, make, git, …)

**Comment by dra27** [comment]
Sort of: https://github.com/ocaml/opam/blob/master/src/client/opamClient.ml#L550-L552 and https://github.com/ocaml/opam/blob/master/src/client/opamClient.ml#L601-L609

**Comment by jpdeplaix** [comment]
Nice, that what I was looking for ! Thanks a lot ! :)

**Comment by AltGr** [comment]
I was going to point you to the same place :) . That should be in the README or manual though, but it's so hard to keep them up-to-date!
