### ISSUE TITLE
opam depext -y doesn't have the same behaviour as opam 1.2.2

### ISSUE THREAD

**Issue by jpdeplaix** [ocaml/opam#3198]
With opam 2.0.0~rc if the depext package is not installed ```opam depext -yi somepkg``` does not install depext whereas opam 1.2.2 installs it (due to the -y argument)

Is this change wanted or is this a regression ?

**Comment by AltGr** [comment]
The trouble is that _all_ parameters after `opam PLUGIN` are passed on to the plugin, so we can't make assumptions about them. This actually didn't work in `1.2.2` either.

__But__ the workaround should be to set `OPAMYES=1` instead, which indeed did work in `1.2.2` and doesn't anymore in `2.0.0~rc`. I'll fix that. Thanks for reporting!

**Comment by AltGr** [comment]
Looking at the code, I found out there is already a hack built-in, which I forgot about: you can put a `-y` or `--yes` in front:
```
opam -y depext -i somepkg
```
