### ISSUE TITLE
When installing a package pointing to a specific git commit : Cannot update ref with nonexistent object

### ISSUE THREAD

**Issue by jhjourdan** [ocaml/opam#3207]
It seems like that if an URL of a package points to a specific git commit of a repo, which is not an ancestor of master, then opam 2 fails with the following error message:

```[ERROR] Could not synchronize
        /home/jjourdan/Travail/soft/gpfsl/_opam/.opam-switch/sources/coq-iris.branch.gen_proofmode.2018-01-27.0
        from
        "git+https://gitlab.mpi-sws.org/FP/iris-coq.git#1addf2ac04a252ad0623d790f7517a830e88a77e":
        "/usr/bin/git update-ref
        refs/remotes/opam-ref-1addf2ac04a252ad0623d790f7517a830e88a77e
        1addf2ac04a252ad0623d790f7517a830e88a77e" exited with code 128 "fatal:
        update_ref failed for ref
        'refs/remotes/opam-ref-1addf2ac04a252ad0623d790f7517a830e88a77e':
        cannot update ref
        'refs/remotes/opam-ref-1addf2ac04a252ad0623d790f7517a830e88a77e':
        trying to write ref
        'refs/remotes/opam-ref-1addf2ac04a252ad0623d790f7517a830e88a77e' with
        nonexistent object 1addf2ac04a252ad0623d790f7517a830e88a77e"
```

For reproducing:

```
opam repo add coq-released https://coq.inria.fr/opam/released
opam repo add iris-dev git+https://gitlab.mpi-sws.org/FP/opam-dev.git
git clone https://gitlab.mpi-sws.org/FP/gpfsl.git
git checkout wp_mono
make build-dep
```

My config

```
# opam config report
# opam-version      2.0.0~beta6 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=fedora os-version=27
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              4
# repositories      4 (http), 1 (version-controlled) (default repo at 2018-02-05 10:03)
# pinned            1 (git), 1 (rsync), 1 (version)
# current-switch    /home/jjourdan/Travail/soft/gpfsl
```

Thanks !

**Comment by AltGr** [comment]
What git version ? This is the most relevant part here (unfortunately... :/)
Thanks for reporting!

**Comment by jhjourdan** [comment]
```
$ git --version
git version 2.14.3
```

**Comment by AltGr** [comment]
Ah, also, you mention that the commit is not an ancestor of `master`, but is it the ancestor of _any_ branch or tag, or none ? I need to verify this, but I think that in general, unlinked commits are not discoverable remotely.

**Comment by jhjourdan** [comment]
This is an ancestor of a branch (namely, the `gen_proofmode` branch).

One more bit of information: as a workaround, `git fetch` in the corresponding directory fixes the issue. Sometimes, `git fetch` can be issued beofre running the `opam` command, and sometimes it has to be issued at the same time as `opam` is updating the git repo.

**Comment by AltGr** [comment]
Apparently it may be tied to an `uploadpack.allowReachableSHA1InWant` server-side option (from git 2.5 on). What we do is try `git fetch <hash>`, and if that fails (e.g. too old client), fall back to just `git fetch`. This avoids always fetching unrelated branches with a recent client.

My guess is that, in your case, the (recent) client accepts the command but actually doesn't manage to fetch the object (due to the server being too old or not having the above option set). Somehow this is not detected, so we don't use the fallback, and when we try to switch to the commit, it's actually absent locally.

I'll need to do some tests to verify that, and see if a workaround can be found (detecting the error, or, at worst, rolling back to always fetching all...)

Thanks for your help!

**Comment by RalfJung** [comment]
> My guess is that, in your case, the (recent) client accepts the command but actually doesn't manage to fetch the object (due to the server being too old or not having the above option set).

The server is a GitLab. I will try to find out if this option can be configured there.

**Comment by jhjourdan** [comment]
> Apparently it may be tied to an uploadpack.allowReachableSHA1InWant server-side option (from git 2.5 on). What we do is try git fetch <hash>, and if that fails (e.g. too old client), fall back to just git fetch. This avoids always fetching unrelated branches with a recent client.

I have just tested: `git fetch 1addf2ac04a252ad0623d790f7517a830e88a77e` indeed fails with:
```
fatal: '1addf2ac04a252ad0623d790f7517a830e88a77e' does not appear to be a git repository
fatal: Impossible de lire le dépôt distant.

Veuillez vérifier que vous avez les droits d'accès
et que le dépôt existe.
```

However, `git fetch origin 1addf2ac04a252ad0623d790f7517a830e88a77e` succeeds. And a subsequent `git update-ref refs/remotes/opam-ref-1addf2ac04a252ad0623d790f7517a830e88a77e 1addf2ac04a252ad0623d790f7517a830e88a77e` succeeds too.

**Comment by jhjourdan** [comment]
So what command is opam issuing exactly? Is there a way to debug all the commands issued by opam?

**Comment by jhjourdan** [comment]
Ah, sorry... Apparently Ralf already applied the change, so that `git fetch origin 1addf2ac04a252ad0623d790f7517a830e88a77e` succeeds, but probably did not before.

**Comment by RalfJung** [comment]
Right, our GitLab now has `allowReachableSHA1InWant` enabled.

**Comment by AltGr** [comment]
Ok, glad this could be be spotted and got fixed for you. Leaving open as we obviously still need to handle that case better from opam!
