### ISSUE TITLE
installing 2.0.0rc from 1.2.2

### ISSUE THREAD

**Issue by Piervit** [ocaml/opam#3210]
Hello,

I am not sure how much it is a real issue but I prefer to show it instead of simply silent: 
I wanted to check the opam 2.0.0.

I am currently on opam 1.2.2, and saw that "opam update; opam install opam-devel" was said to work.

However while the rc is out, it proposes to add the 2.0.0.beta5 : 

> $opam show opam-devel
>              package: opam-devel
>              version: 2.0.0\~beta5
>           repository: default
>         upstream-url: https://github.com/ocaml/opam/archive/2.0.0-beta5.tar.gz
>        upstream-kind: http
>    upstream-checksum: 9347fabff36c99bc631b30b1007e20db
>             homepage: https://opam.ocaml.org
>          bug-reports: https://github.com/ocaml/opam/issues
>             dev-repo: https://github.com/ocaml/opam.git
>              depends: opam-client = 2.0.0\~beta5 & cmdliner >= 0.9.8 & jbuilder >= 1.0+beta12
>    installed-version: 
>   available-versions: 2.0\~alpha5, 2.0.0\~beta, 2.0.0\~beta3, 2.0.0\~beta3.1, 2.0.0\~beta5
>          description: opam 2.0.0 beta version
> 
> This package compiles (bootstraps) the beta version of opam 2.0.0. For
> consistency and safety of the installation, the binaries are not installed into
> the PATH, but into lib/opam-devel, from where the user can manually install them
> system-wide.

> 

Then, while installing it, I got a compilation error because the unix library is not included as expected:
[opam-devel-11619-05296d.err.log](https://github.com/ocaml/opam/files/1696810/opam-devel-11619-05296d.err.log)

Thanks

**Comment by AltGr** [comment]
Oops, indeed, the package for 2.0.0~rc was forgotten, that's a big issue, thanks for notifying!

**Comment by AltGr** [comment]
Both issues fixed by https://github.com/ocaml/opam-repository/pull/11370
Thanks a lot for reporting!
