### ISSUE TITLE
Weird circular dependency issue with jbuilder and ocaml-migrate-parsetree

### ISSUE THREAD

**Issue by xguerin** [ocaml/opam#3213]
This is a weird one and I'm not sure where to post it. Feel free to close that issue if I am barking at the wrong tree.

In Travis:

```
opam install --show-actions --json solution.json bitstring 
```

Fails with the following:

```
[bitstring] /home/travis/build/xguerin/bitstring/ already up-to-date
The actions to process have cyclic dependencies:
  - ⊘  ocaml-migrate-parsetree.1.0.7 -> ⊘  jbuilder.1.0+beta17 -> ⊘  ocaml-migrate-parsetree.1.0.7
```

cf. https://travis-ci.org/xguerin/bitstring/jobs/338256169, same things regardless of the version: https://travis-ci.org/xguerin/bitstring/builds/338256162

**Comment by AltGr** [comment]
What version of opam ?
There is indeed a cycle between the packages, _when_ `jbuilder` is set to compile with tests.
What is funny however in your case is that the cycle is between remove operations... so test dependencies could have been avoided in this case, but opam isn't actually aware of that. I'll see if something can be done to improve.

In the meantime, `jbuiler` should fix their dependencies, even a `test` dependency isn't allowed to cycle at the moment (package and test builds being done in the same node in the actions graph, there would be no correct ordering of operations).

**Comment by xguerin** [comment]
> What version of opam ?

1.2. what puzzles me is that I could not reproduce the problem locally.

> In the meantime, jbuiler should fix their dependencies

I'll ping them.

**Comment by let-def** [comment]
jbuilder requires ocaml-migrate-parsetree for tests. So this problem doesn't appear in normal build.

**Comment by xguerin** [comment]
> even a test dependency isn't allowed to cycle at the moment

What puzzles me here is that I am not testing `jbuilder`. So why would `jbuilder`'s test dependency, valid or not, have any impact on `bitstring` ?

**Comment by avsm** [comment]
probably because asking for `bitstring` test dependencies also pulls in its dependencies' test dependencies.

**Comment by dra27** [comment]
Indeed opam 1.x applies the request to build for tests recursively; opam 2 doesn't.

**Comment by rjbou** [comment]
Closing this issues, feel free to reopen it if needed.
Thanks!
