### ISSUE TITLE
Upgrading opam-core stuck on ./configure step

### ISSUE THREAD

**Issue by bcc32** [ocaml/opam#3214]
```
# opam config report
# opam-version      2.0.0~beta5
# self-upgrade      no
# system            arch=x86_64 os=macos os-distribution=homebrew os-version=10.13.3
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              3
# repositories      1 (http) (default repo at 2018-02-07 05:03)
# pinned            3 (git)
# current-switch    4.05.0
```

I was trying to `opam update && opam upgrade`, which asked me to upgrade from `2.0.0~beta5` to `2.0.0~rc`.  However, this results in the upgrade step being stuck at 2/264 on opam-core, with the command `./configure`.

The program starts burning a lot of CPU, but I'm not sure what for.  htop reveals that the child `sh` process is a zombie and `opam upgrade` is just spinning or something and using ~96% of CPU.

**Comment by AltGr** [comment]
It's a known problem that happens sometimes in beta5, and was fixed in beta6. Sorry about it!
You could get out by upgrading the dependencies explicitely in a few smaller steps, or, for example, by using the [released binaries](https://github.com/ocaml/opam/releases/tag/2.0.0-rc).
