### ISSUE TITLE
docs: IRC channel suggestion looks wrong

### ISSUE THREAD

**Issue by RalfJung** [ocaml/opam#3219]
The [opam 2 docs](https://opam.ocaml.org/doc/2.0/FAQ.html) say "You may also try IRC channel #opam on Freenode". However, that channel has only 6 people in it, and no operator. Is this really the right channel to go to? Looks to me like the docs need updating.

**Comment by Drup** [comment]
Ah, yes, that channel is quite deserted now. It would be better to just recommend `#ocaml`.

**Comment by AltGr** [comment]
I'm often there though :)
Thanks for reporting!

**Comment by rjbou** [comment]
Fixed. Thanks for reporting!
