### ISSUE TITLE
Inadequate exit code of curl in Makefile

### ISSUE THREAD

**Issue by kkeundotnet** [ocaml/opam#3221]
When running `make lib-ext`, it tries to download tarball caches in `opam.ocaml.org` if the tarball is unavailable from its [original source list](https://github.com/ocaml/opam/blob/master/src_ext/Makefile.sources).  However, the problem is that [the `curl` command](https://github.com/ocaml/opam/blob/1c0dabb3fc7380896d1fe6ad152c9219ae56d97e/src_ext/Makefile#L146) downloading tarballs from `opam.ocaml.org` returns zero exit code even when `opam.ocaml.org` returns 404 not found page.

```bash
$ curl  -LSs -o a4c0e652e56e74c7b388a43f9258d119 https://opam.ocaml.org/2.0~dev/cache/md5/a4/a4c0e652e56e74c7b388a43f9258d119
$ echo $?
0
$ cat a4c0e652e56e74c7b388a43f9258d119
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.2.1</center>
</body>
</html>
```

1. Adding `-f` option to `curl` may solve the issue.
2. The cache links are broken, e.g., the tarball of cudf `https://opam.ocaml.org/2.0~dev/cache/md5/a4/a4c0e652e56e74c7b388a43f9258d119` is not found. Is this because I am using the main branch?

**Comment by AltGr** [comment]
Thanks for reporting. Indeed `-f` should work. Ideally the Makefile should double-check the md5 and assume a failure if wrong, though.

> The cache links are broken, e.g., the tarball of cudf https://opam.ocaml.org/2.0~dev/cache/md5/a4/a4c0e652e56e74c7b388a43f9258d119 is not found. Is this because I am using the main branch?

This is re-using the cache from the opam repository, so the files may not be present for stuff that is not yet packaged there. But in this case, the URL is wrong (seems obsolete), it should be `/2.0/` without the `~dev`.

Will fix shortly, thanks!
