### ISSUE TITLE
opam hangs

### ISSUE THREAD

**Issue by jeremydaw** [ocaml/opam#3225]
trying to follow instructions to install coq at 
https://coq.inria.fr/opam/www/using.html
I get
```
export OPAMROOT=~/opam-coq.8.7 # installation directory
jeremy@cecs-042179:/mnt/local/coq$ opam init -n --comp=4.02.3 -j 2 # 2 is the number of CPU cores
Checking for available remotes: rsync and local, git, mercurial, darcs. Perfect!

=-=- Fetching repository information =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Processing: [default: http]
```
and at this point it hangs

Is this a problem with opam or with the coq installation instructions?

Thanks!
```
$ opam config report
# OPAM config report
# opam-version    1.2.2 
# self-upgrade    no
# os              linux
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            4
# repositories    1* (http)
# pinned          0
# current-switch  system*
# last-update     2018-02-14 23:48
```

**Comment by AltGr** [comment]
This is the point where the repository from https://opam.ocaml.org is downloaded. Maybe there was some transient server or network outage ? You can try running with `-vv` to see the exact commands issued, `--debug` to have details on what opam is doing.

**Comment by jeremydaw** [comment]
Hi, thanks.
$ opam init -vv --debug -n --comp=4.02.3 -j 2 
00:00.010  CLIENT                  INIT default(0 http https://opam.ocaml.org)
OPAM has already been initialized.00:00.010  STATE                   LOAD-STATE(init)
00:01.077  CUDF                    Checking version of criteria accepted by the external solver
00:01.742  SYSTEM                  [log-26872-4438d8] (in 0.000s) aspcud -v
00:01.742  CUDF                    Solver is aspcud > 1.9: using latest version criteria
00:01.750  SYSTEM                  error: File /home/users/jeremy/opam-coq.8.7/repo/default/config does not exist
'opam init -vv --debug -n --comp=4.02.3 -j 2' failed.
# opam-version    1.2.2
# os              linux
File /home/users/jeremy/opam-coq.8.7/repo/default/config does not exist

So, continuing in the coq installation instructions:

$ opam repo add coq-released http://coq.inria.fr/opam/released
# opam-version    1.2.2
# os              linux
File /home/users/jeremy/opam-coq.8.7/compilers/4.02.3/4.02.3/4.02.3.comp does not exist

(with option -vv, or --debug, no difference)

**Comment by AltGr** [comment]
There appears to be a partial `~/.opam` that is getting in the way (a repository is registered, but files are missing). You can try to synchronise it again with `opam update [-vv --debug]`, or just remove it and try `opam init` again.
