### ISSUE TITLE
opam caused a significant portion of my home directory to be deleted

### ISSUE THREAD

**Issue by varkor** [ocaml/opam#3231]
It's not entirely clear exactly what happened, as most of my files have been lost, and my programs corrupted, but I have the log from right before the problem occurred:
```bash
> opam init --no-setup --compiler=4.02.3
OPAM has already been initialized.Your system compiler has been changed. Do you want to upgrade your OPAM installation ? [Y/n] Y

=-=- Upgrading system -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
The following actions will be performed:
  ∗  install conf-gtksourceview 2      
  ∗  install camlp5             7.03   
  ∗  install conf-m4            1      
  ∗  install base-threads       base   
  ∗  install base-unix          base   
  ∗  install base-bigarray      base   
  ∗  install depext             1.0.5  
  ∗  install ocamlfind          1.7.3-1
  ∗  install num                1.1    
  ∗  install lablgtk            2.18.6 
===== ∗  10 =====

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[camlp5] Archive in cache
[depext] Archive in cache
[lablgtk] Archive in cache
[num] Archive in cache
[ocamlfind] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
∗  installed base-bigarray.base
∗  installed base-threads.base
∗  installed base-unix.base
∗  installed conf-m4.1
∗  installed conf-gtksourceview.2
[ERROR] The compilation of camlp5 failed at "./configure --prefix ~/.opam/system -libdir ~/.opam/system/lib -mandir
        ~/.opam/system/man".
∗  installed depext.1.0.5
∗  installed ocamlfind.1.7.3-1
[ERROR] The compilation of num failed at "make findlib-install".
∗  installed lablgtk.2.18.6
[ERROR] User interruption
```
I'm fairly sure it was executing `make uninstall camlp5` before I killed it after noticing that it was taking an unexpected amount of time (so maybe the problem is there), though I think the issue is relevant here regardless.
I'm still a little in shock at having ruined my computer at the moment, so I may try to look into this a little more later, but I think this issue definitely needs to be looked into.

**Comment by varkor** [comment]
Okay, this seems to have been the issue: https://github.com/ocaml/opam-repository
I think something is out of date here, because this issue was fixed a few days ago, but it occurred for me. This might not be the right repository, but any tools that depend on the outdated version need to be updated immediately.

**Comment by AltGr** [comment]
I am very sorry for this outcome, and feel for you. I am hoping you had backups or online versions of any valuable files :cry: 

opam will only run commands within `~/.opam`, however, commands from package scripts (_e.g._ install and remove) are not sandboxed at the moment¹; so it's likely that a poorly written Makefile triggered the disaster. We'll search for it and fix it asap.

Again, I am very sorry this happened to you :disappointed: 


¹ We do have optional sandboxing, but it is still being tested and needs some manual configuration. The upcoming pam 2 can also automatically take care of package uninstallation.

**Comment by varkor** [comment]
Seems like a case of very unfortunate bad timing. It seems also like there will be mitigations to prevent this sort of thing happening in opam in the future, so I think there's nothing more to be said here. Thanks for looking into it!
