### ISSUE TITLE
pin + upgrade seems to remove former version of the package with newer opam file

### ISSUE THREAD

**Issue by rixed** [ocaml/opam#3233]
I noticed while upgrading a pinned package that `opam upgrade` left some files behind (thus emitting  warning), although each opam file properly specify how to remove all installed files. But the former opam files used `ocamlfind remove` while the new one uses dune .install file.
See original bug report with full log here: https://github.com/andrenth/ocaml-stdint/issues/25

Shouldn't instructions on how to remove a package be stored with the installed package itself rather than with synchronized opam files?

**Comment by AltGr** [comment]
Indeed, that should be the case... opam 2.0 rc stores the opam file used for installation and the "current" pinning opam file in different places (resp. `.opam-switch/packages` and `.opam-switch/overlay`).
What version of opam are you using, and if 2.0, was your opam root upgraded from 1.2 format (in which case some information might have been missing) ?

Additionally, opam 2 tracks the files installed by packages (on top of handling `.install` files), so it should be able to remove your package files even if the `remove:` instructions were incomplete.

**Comment by rixed** [comment]
I'm indeed using opam v1.2.2, I feel sorry that I forgot to mention this.
Glad to learn it's fixed in opam 2.0.
Thank you!
