### ISSUE TITLE
(opam2) opam pin command upgrades unrelated packages

### ISSUE THREAD

**Issue by smondet** [ocaml/opam#3234]
I did `opam update` and then `opam pin add ocamlformat https://github.com/ocaml-ppx/ocamlformat.git` and `opam` upgraded `stb_truetype` and `wall` (another pin) which are completely unrelated.

```
The following actions will be performed:
  ↗  upgrade   stb_truetype        0.3 to 0.5* 
  ↗  upgrade   ocamlformat_support 0.2 to 0.3  [required by ocamlformat]
  ↻  recompile wall                ~dev*       [uses stb_truetype]
  ↻  recompile ocamlformat         v0.2*       
===== ↻  2   ↗  2 =====

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ocamlformat_support.0.3] downloaded from cache at https://opam.ocaml.org/2.0/cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
⊘  removed   ocamlformat.v0.2
⊘  removed   ocamlformat_support.0.2
∗  installed ocamlformat_support.0.3
⊘  removed   stb_truetype.0.3
⊘  removed   wall.~dev
∗  installed stb_truetype.0.5
∗  installed wall.~dev
∗  installed ocamlformat.v0.2
Done.
```

```
 $ opam config report
# opam config report
# opam-version      2.0.0~beta6 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=linuxmint os-version=18.3
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              3
# repositories      1 (http) (default repo at 4508c906)
# pinned            6 (git), 1 (version)
# current-switch    4.05.0
[WARNING] PATH contains '.' : this is a likely cause of trouble.
```

**Comment by AltGr** [comment]
Thanks for the report. Any opam action commands (install, remove, etc.) optimise some criteria, which attempt to have the actions remain within the setting of the request. However, first and foremost, opam will preserve (or restore if needed) a notion of _consistency_ of the set of installed packages. Consistency includes having all dependencies satisfied, no conflicting packages installed, and also that pinned packages are at the version they are pined to. Note that this consistency can legally get broken, for example by `opam update` if an installed package added some dependencies, or by `pin -n`.

opam can't process actions in an inconsistent installation, so it will "repair" any such inconsistencies on the next command that has to perform actions, whatever they are, and even when they seem unrelated — in your case `opam pin add`, while `stb_truetype.0.3` was installed although that package was pinned to `0.5`. So this is not really a bug, but to be expected. Maybe it would have been clearer if it was made explicit that this was not really an upgrade, but more a "consistency fix" ?

**Comment by smondet** [comment]
>  in your case opam pin add, while stb_truetype.0.3 was installed although that package was pinned to 0.5.

Not exactly: `stb_truetype` was  pinned to `master` on the Git repo (just like `wall`).

So if had done:

```
 opam pin add -n ocamlformat https://github.com/ocaml-ppx/ocamlformat.git
 opam install ocamlformat
```

would have it avoided the upgrade of the other pins?
