### ISSUE TITLE
opam pin add removes /usr/local/bin contents [MacOS, homebrew]

### ISSUE THREAD

**Issue by teners** [ocaml/opam#3243]
MacOS High Sierra 10.13.3, opam v1.2.2, installed via Homebrew.
During `opam pin add` compilation of `ocamlbuild` and `camlp5` fails and it just hangs up. By this time `/usr/local/bin` is already empty.

After this happened I reproduced it and recorded a screencast, so [here's the demo](https://gfycat.com/EasygoingBigheartedCaecilian).

Unfortunately, I can't include the output of `opam config report` since opam itself was in my `/usr/local/bin` and I've prudently never installed it again on my machine😅

**Comment by hcarty** [comment]
The immediate bug is, unfortunately, in the camlp5 package - see https://github.com/ocaml/opam-repository/issues/11440 for a report against opam-repository and https://github.com/ocaml/opam/issues/3231 for a report against opam itself, each with more discussion.
