### ISSUE TITLE
Provide a `tests` package variable

### ISSUE THREAD

**Issue by nbraud** [ocaml/opam#3246]
OPAM 2 should provide a `tests` package variable, that is true iff tests are being built and run.

This can simplify quite a bit `opam` files; where we currently write:
```
build: [
  [ "ocaml" "pkg/pkg.ml" "build"
      "--dev-pkg" "%{dev}%"
      "--tests" "false" ]
]
run-test: [
  [ "ocaml" "pkg/pkg.ml" "build"
      "--dev-pkg" "%{dev}%"
      "--tests" "true" ]
  [ "ocaml" "pkg/pkg.ml" "test" ]
]
```
it should be possible to write:
```
build: [
  [ "ocaml" "pkg/pkg.ml" "build"
      "--dev-pkg" "%{dev}%"
      "--tests" "%{tests}%" ]
]
run-test: [
  [ "ocaml" "pkg/pkg.ml" "test" ]
]
```

**Comment by nbraud** [comment]
@neubyi Once this is fixed, the `opam` file suggested in https://github.com/neubyi/sds/pull/1 can be improved.

**Comment by dra27** [comment]
Doesn't the `with-test` predicate already work in the build action?

**Comment by nbraud** [comment]
@dra27 Indeed!  Seems I shouldn't send feature requests past midnight.

Thanks for the tip  :)
