### ISSUE TITLE
Un-tar'ing opam archive fails on CircleCI testing server

### ISSUE THREAD

**Issue by nbuonin** [ocaml/opam#3249]
I'm trying to install llvm 3.8 on CircleCI as part of a testing workflow.  When installing llvm with opam it throws an error trying to untar the llvm archive.  It looks like this (running `opam install llvm.3.8 -vvv`):
`/bin/tar: llvm-3.8.0.src/<all-files-in-archive>: Cannot change ownership to uid 107418, gid 5000: Invalid argument`

I suspect that the issue is related to the fact that `tar` is trying to change the owner back to the UID that packaged the archive.  I can cleanly unpack the archive manually if I add `--no-same-owner` to the tar command.

Specifically this happens on the testing server.  When I run the same tests on a local Docker image it builds cleanly.

**Comment by AltGr** [comment]
From tar 1.29 (Debian):
```
       --same-owner
              Try extracting files with the same ownership as exists in the archive (default for superuser).
       --no-same-owner
              Extract files as yourself (default for ordinary users).
```
So it should be OK in this case. Is the process running as UID 0, or is the CI using a specific version of `tar` ?
Unfortunately, `--no-same-owner` is apparently [not portable enough](https://man.openbsd.org/tar)

**Comment by rjbou** [comment]
What is the status of this issue ?

**Comment by kit-ty-kate** [comment]
Closing. Feel free to reopen if you problem is still there
