### ISSUE TITLE
scrypt package release url is not static

### ISSUE THREAD

**Issue by cfcs** [ocaml/opam#3251]
Fetching the `scrypt` package fails with the following error:

```
[ERROR] Bad checksum for /home/travis/.opam/packages.dev/scrypt.0.2.1/v0.2.1:
          - 24704b12638932a14400f74a354c0617 [expected result]
          - e173ad140a900fe3e54d187583550a3a [actual result]
        This may be fixed by running `opam update`.
```

I checked another system, that one gave me the same md5 after downloading the `upstream-url` with my browser:
```
e173ad140a900fe3e54d187583550a3a  constfun-ocaml-scrypt-v0.2.1-0-g1bf8638.tar.gz
```

I fixed it locally with `export OPAMNOCHECKSUMS=true`, but this is not good, since it makes it easier to accidentally mess up other packages that use broken distribution platforms.

**Comment by cfcs** [comment]
Note also that this release contains all manner of `.DS_store` and `.local-vimrc` and what-have-you, it looks like someone just zipped up their working directory and put it on Github.com.

**Comment by dra27** [comment]
Looks like it's using the non-stable GitHub URL rather than the slightly less unstable https://github.com/constfun/ocaml-scrypt/archive/v0.2.1.tar.gz

This is an issue for opam-repository, not opam, though.

**Comment by cfcs** [comment]
@dra27 oh, sorry, I wasn't aware of the distinction, I'll open an issue there instead
