### ISSUE TITLE
Config file is not updated on repo add with opam 2.0.0~rc

### ISSUE THREAD

**Issue by TheLortex** [ocaml/opam#3254]
To reproduce this bug, just create a local repo and add it with ``opam repo add``. The ``~/.opam/config`` file contains a 'repositories' entry that is not updated when a local repo is added. 
You can still see the repo with ``opam repo`` and install packages from the local repo but it's not possible to add a compiler as a package from the local repo unless it's referenced in ``~/.opam/config``.

**Comment by AltGr** [comment]
See `opam repo --help`: repositories are now configurable per-switch, and the configuration in `~/.opam/config` now corresponds to the default for newly created switch.

- the full list of configured repositories is now in `~/.opam/repo/repos-config`
- you can update `~/.opam/config` by adding the `--set-default` option to `opam repo`. See also `--all` to affect all existing switches
- creating repositories directly on switch creation is also possible using e.g. `opam switch create --repos REPO_NAME=REPO_URL,default`

Hope this helps.
