### ISSUE TITLE
difficulty installing opam

### ISSUE THREAD

**Issue by wang-d** [ocaml/opam#3282]
Tried to install opam today and ran into a couple of minor issues. 

Short version: I'm not sure if the issue is that `opam_installer.sh` is
incorrectly labelled legacy code, or that `install.sh` didn't work for me. In
the end, `opam_installer.sh` worked.  Thanks!

# The website recommends a legacy install script

The website

    https://opam.ocaml.org/doc/Install.html#Binary-distribution

recommends I do

    wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin
    
but when I read that file it says,

    # NOTE: this file is here for legacy reasons. It is advised to use the newer 
    # 'install.sh' instead.

# The non-legacy install script doesn't work for me

I found

    https://raw.github.com/ocaml/opam/master/shell/install.sh
      
and tried to substitute it in the original command:

    09:24 wget https://raw.github.com/ocaml/opam/master/shell/install.sh -O - | sh -s /usr/local/bin
    --2018-04-07 09:25:14--  https://raw.github.com/ocaml/opam/master/shell/install.sh              
    Resolving raw.github.com (raw.github.com)... 151.101.20.133
    Connecting to raw.github.com (raw.github.com)|151.101.20.133|:443... connected.
    HTTP request sent, awaiting response... 301 Moved Permanently
    Location: https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh [following]
    --2018-04-07 09:25:24--  https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh
    Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.20.133
    Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.20.133|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 7380 (7.2K) [text/plain]
    Saving to: ‘STDOUT’

    -                               100%[====================================================>]   7.21K  --.-KB/s    in 0s      

    2018-04-07 09:25:24 (18.9 MB/s) - written to stdout [7380/7380]

    opam binary installer v.2.0.0~rc
    Downloads and installs a pre-compiled binary of opam 2.0.0~rc to the system.
    This can also be used to switch between opam versions

    Options:
        --no-backup            Don't attempt to backup the current opam root
        --backup               Force the backup the current opam root (even if it
                              is from the 2.0 branch already)
        --fresh                Create the opam 2.0.0~rc root from scratch
        --restore   VERSION    Restore a backed up opam binary and root

    The default is to backup if the current version of opam is 1.*, or when
    using '--fresh'
    
Eventually I figured out that `install.sh` runs if I save it to a file first:

    09:26 wget https://raw.github.com/ocaml/opam/master/shell/install.sh -O /tmp/install-opam.sh
    --2018-04-07 09:27:03--  https://raw.github.com/ocaml/opam/master/shell/install.sh
    Resolving raw.github.com (raw.github.com)... 151.101.20.133
    Connecting to raw.github.com (raw.github.com)|151.101.20.133|:443... connected.
    HTTP request sent, awaiting response... 301 Moved Permanently
    Location: https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh [following]
    --2018-04-07 09:27:03--  https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh
    Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.20.133
    Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.20.133|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 7380 (7.2K) [text/plain]
    Saving to: ‘/tmp/install-opam.sh’

    /tmp/install-opam.sh            100%[====================================================>]   7.21K  --.-KB/s    in 0.001s  

    2018-04-07 09:27:03 (8.52 MB/s) - ‘/tmp/install-opam.sh’ saved [7380/7380]

    09:27 chmod +x /tmp/install-opam.sh
    09:27 /tmp/install-opam.sh --no-backup
    ## Downloading opam 2.0.0~rc for linux on x86_64...
    ## Downloaded.
    ## Where should it be installed ? [/usr/bin] /usr/local/bin
    Write access to /usr/bin required, using 'sudo'.
    Command: rm -f /usr/bin/opam
    [sudo] password for me: 
    Write access to /usr/local/bin required, using 'sudo'.
    Command: install -m 755 /tmp/opam-2.0.0-rc-x86_64-linux /usr/local/bin/opam
    ## opam 2.0.0~rc installed to /usr/local/bin
    ## Converting the opam root format
    [ERROR] /home/me/.opam exists, but does not appear to be a valid opam root. Please remove it and use `opam init', or
            specify a different `--root' argument
            
I thought I had removed that.  Let's remove it again, to be sure:

    09:27 rm -rf ~/.opam
    09:27 /tmp/install-opam.sh --no-backup
    ## Using already downloaded "/tmp/opam-2.0.0-rc-x86_64-linux"
    ## Where should it be installed ? [/usr/local/bin] 
    Write access to /usr/local/bin required, using 'sudo'.
    Command: rm -f /usr/local/bin/opam
    Write access to /usr/local/bin required, using 'sudo'.
    Command: install -m 755 /tmp/opam-2.0.0-rc-x86_64-linux /usr/local/bin/opam
    ## opam 2.0.0~rc installed to /usr/local/bin
    ## Converting the opam root format
    [ERROR] /home/me/.opam exists, but does not appear to be a valid opam root. Please remove it and use `opam init', or
            specify a different `--root' argument
            
What's in there?

    09:27 ls -l ~/.opam
    total 0
    -rw-r--r-- 1 me me 0 Apr  7 09:27 config.lock
    09:28 ls -l ~/.opam -d
    drwxr-xr-x 2 me me 4096 Apr  7 09:27 /home/me/.opam
    09:28 cat ~/.opam/config.lock
    
Really remove it and try again:

    09:28 rm -rf ~/.opam
    09:28 ls -l ~/.opam -d
    ls: cannot access '/home/me/.opam': No such file or directory
    09:28 /tmp/install-opam.sh --no-backup
    ## Using already downloaded "/tmp/opam-2.0.0-rc-x86_64-linux"
    ## Where should it be installed ? [/usr/local/bin] 
    Write access to /usr/local/bin required, using 'sudo'.
    Command: rm -f /usr/local/bin/opam
    Write access to /usr/local/bin required, using 'sudo'.
    Command: install -m 755 /tmp/opam-2.0.0-rc-x86_64-linux /usr/local/bin/opam
    ## opam 2.0.0~rc installed to /usr/local/bin
    ## Converting the opam root format
    [ERROR] /home/me/.opam exists, but does not appear to be a valid opam root. Please remove it and use `opam init', or
            specify a different `--root' argument

Not sure what's going on there.

# opam config report

This is based on the `opam_installer.sh` that I eventually used:

    # OPAM config report
    # opam-version    1.2.2 
    # self-upgrade    no
    # os              linux
    # external-solver no
    # criteria        -removed,-notuptodate,-changed
    # jobs            4
    # repositories    1* (http)
    # pinned          0
    # current-switch  4.05.0
    # last-update     2018-04-07 13:33

**Comment by dra27** [comment]
When you removed `~/.opam`, presumably you just did `rm -rf ~/.opam`?

I think the first problem was that you read the `opam_installer.sh` script 🙂 And then that `install.sh` needed the `--fresh` switch because you didn't have opam installed previously. Neither of which was obviously your fault!

Having got opam 1.2.2 installed and working, it should be the case that if you now run `install.sh` it will replace it with the release candidate for opam 2 and then successfully upgrade the opam root.

Sorry that your first time install wasn't so great, but thanks for taking the time to report it in detail!

@AltGr - two issues to be fixed:

 - [ ] `install.sh` should assume `FRESH=1` if `~/.opam` doesn't exist
 - [ ] `opam update` called when the opam root doesn't exist should not accidentally create it (this applies to various commands, IIRC)

**Comment by AltGr** [comment]
Thanks for the feedback! Indeed, we are very close to, but not quite at the release of opam 2.0, which makes the situation more complicated than it should be:
- `opam_installer.sh` was acutally the installer for opam 1.2, which is why it is deprecated (I actually intended to deprecate it as part of the git repository, not as a means for installing opam 1.2)
- the newer `install.sh` (for opam 2) is interactive, and running `curl | sh` doesn't allow reading from the terminal (since stdin is plugged from curl). This is why we recommend a different command [here](http://opam.ocaml.org/blog/opam-2-0-0-rc/):
    ```
sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
```
    Updating the installation instruction is very high on my to-do list, I assure you...

Simply removing the `~/.opam` stub and running `opam init`, rather than the whole script again, should get you sorted. And indeed your report points out a few issues that should'nt be too difficult to fix, thanks!

**Comment by wang-d** [comment]
Sorry to revive this issue.  I didn't understand that linking to it would have that effect.  I am not bothered by this problem any more.  Thank you for your help!
