### ISSUE TITLE
Feature suggestion: hint to avoid heterogeneous switch naming caused by system compiler

### ISSUE THREAD

**Issue by gasche** [ocaml/opam#3286]
For bug-testing purposes I need roughly one switch per major OCaml version installed on my system. I thus did `opam switch create 4.06.1`, `opam switch create 4.02.3`, etc., but I hit a snag when I tried with `4.05.0`, as this is also what my system compiler uses:

```
$ opam switch create 4.05.0
[ERROR] Compiler selection '4.05.0' is ambiguous. matching
packages: { ocaml-base-compiler.4.05.0, ocaml-system.4.05.0 }
```

Then I did the following mistake:

```
opam switch create ocaml-base-compiler.4.05.0
```

It creates the switch I expected, but then I have to use `ocaml-base-compiler.4.05.0` as the switch name each time, and the inconsistency with other versions is jarring.

In the error message above, I would suggest to add the following hint:

```
Hint: you may mean the following command
  opam switch create 4.05.0 ocaml-base-compiler.4.05.0
```

The full name to use (here `ocaml-base-compiler.4.05.0`) should be the one of the switch options that is not already installed on the system (the error only shows when there is already a switch at this version). If there are several non-installed switches (I don't think this can happen with OCaml switches today, but in the future or for another language), I would just use one of them arbitrarily (the part that is helpful is to pass two arguments, the user may know which switch they want), or show all the possible commands.

**Comment by kit-ty-kate** [comment]
This close to be 7 years old issue was fixed somewhere along the line:
```
$ opam switch create 4.05.0 --show

<><> Installing new switch packages <><><><><><><><><><><><><><><><><><><><><><>
Switch invariant: ["ocaml-base-compiler" {= "4.05.0"} | "ocaml-system" {= "4.05.0"}]
The following actions would be performed:
=== install 6 packages
  ∗ base-bigarray       base
  ∗ base-threads        base
  ∗ base-unix           base
  ∗ ocaml               4.05.0
  ∗ ocaml-base-compiler 4.05.0
  ∗ ocaml-config        1
```
It was at the very least fixed by https://github.com/ocaml/opam/pull/4607 in opam 2.1.0 or most probably in 2.0.0 since this ticket was created a few month before the final release.
