### ISSUE TITLE
opam2-rc1: unable to install switches from non-default repositories?

### ISSUE THREAD

**Issue by gasche** [ocaml/opam#3292]
In order to try the latest ocaml-multicore releases, I did

```bash
$ opam repository add multicore git+https://github.com/ocamllabs/multicore-opam.git
```

which seems to make the packages available as expected:

```bash
$ opam show ocaml-variants -f available-versions | grep -o "\\S*+multicore"
4.02.2+multicore
4.04.2+multicore
4.06.1+multicore
```

however, `opam switch create` apparently cannot find these switches:

```bash
$ opam switch list-available | grep multicore
# no output

$ opam switch create multicore ocaml-variants.4.06.1+multicore
[ERROR] No compiler matching 'ocaml-variants.4.06.1+multicore' found,
        use 'opam switch list-available' to see what is available,
        or use '--packages' to select packages explicitely.

$ opam install ocaml-variants.4.06.1+multicore
Your request can't be satisfied:
  - no matching version

No solution found, exiting
```

Is there something transient that is wrong with my opam2-rc1 setup? Can other people reproduce the problem with this switch description?

**Comment by AltGr** [comment]
This confusion, due to the new semantics of `opam repo add`, should hopefully be avoided by this recently added message:
```
% opam repository add multicore git+https://github.com/ocamllabs/multicore-opam.git
[multicore] Initialised
[NOTE] Repository at git+https://github.com/ocamllabs/multicore-opam.git doesn't define its version, assuming it's 1.2.

=-=- Upgrading repositories from older opam format =-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Upgrading repository "multicore"...
[NOTE] Repository multicore has been added to the selections of switch 4.05.0 only.
       Run `opam repository add multicore --all-switches|--set-default' to use it in all existing switches, or in newly created
       switches, respectively
```

Can you confirm ?

**Comment by AltGr** [comment]
Note that what you really want, in this case, is the single command:
```
opam switch create multicore ocaml-variants.4.06.1+multicore --repos multicore=git+https://github.com/ocamllabs/multicore-opam.git,default
```

that will configure the new repository only in the switch where you want it :)

**Comment by gasche** [comment]
Thanks! When doing `opam repo`, the following warning should have told me that something was going on, but I didn't realize:

```
[NOTE] These are the repositories in use by the current switch. Use '--all' to see all configured repositories.
```

I think that the new warning would have been very helpful, and I can't think of any other concrete suggestion to improve things, so I'm moving to close this issue. Thanks again for the prompt user support.

**Comment by gasche** [comment]
I thought of a small change that could have helped me, which is a more explicit warning in the `opam repo add` documentation. I sent a proposal for this in #3295.

Another thing that would have helped is the following: when no package of a given name or version is found, try to see if it exists in another switch (pinned, or thanks to an extra repository there), and tell it to the user. I guess that the switch-creation command could have an even more precise instance of this behavior, which explains the per-switch nature of repositories.

**Comment by ygrek** [comment]
adding repository to all switches doesn't work for me still :
```
$ opam info ocaml-variants.4.07.1+abort-on-oom
[ERROR] No package matching ocaml-variants.4.07.1+abort-on-oom found

$ opam repo add --all-switches local ~/work/opam
[local] Initialised

$ opam info ocaml-variants.4.07.1+abort-on-oom
[...]
<><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><><><>
version         4.07.1+abort-on-oom
repository      local
url.src:        "https://github.com/ocaml/ocaml/archive/4.07.1.tar.gz"
url.checksum:   "md5=352fe8d46cb238a26aa10c38bad6ecb6"
maintainer:     "platform@lists.ocaml.org"
flags:          compiler
depends:        "ocaml" {= "4.07.1" & post}
                "base-unix" {post}
                "base-bigarray" {post}
                "base-threads" {post}
conflict-class: "ocaml-core-compiler"
synopsis        Official release 4.07.1, with abort instead of Out_of_memory

$ opam sw create ahrefs 4.07.1+abort-on-oom 
[ERROR] No compiler matching '4.07.1+abort-on-oom' found, use 'opam switch list-available' to see what is available, or use '--packages' to select packages
        explicitly.
```

the workaround works : 
```
opam sw create ahrefs ocaml-variants.4.07.1+abort-on-oom --repos local,default
```

**Comment by rjbou** [comment]
`all-switches` option adds given repository to all **present** switches. To have your repo used by default on switch creation, you'd better use option [`--set-default`](http://opam.ocaml.org/doc/man/opam-repository.html#lbAF).

**Comment by ygrek** [comment]
I missed `set-default` in discussion above and thought `all-switches` does it. Thanks for clarifying!
