### ISSUE TITLE
ERROR while installing core.v0.11.0 on arm64 architectures

### ISSUE THREAD

**Issue by askariMakeya** [ocaml/opam#3301]
As per the package notes for core (https://opam.ocaml.org/packages/core/) , there's restrictions in place, particularly the following **ocaml-version >= "4.04.1" & arch != "aarch64"**. Is there a reason for the latter being enforced, ie **arch != "aarch64**. I can't get core installed on my ARM machine due to failed checks / dependencies not being met. 

Here's the output of my `opam config report`
OPAM config report
opam-version    1.2.2 
self-upgrade    no
os              linux
external-solver aspcud $in $out $criteria
criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
jobs            4
repositories    1* (http)
pinned          0
current-switch  4.06.1
last-update     2018-04-13 19:58

**Comment by AltGr** [comment]
You probably meant to report to https://github.com/ocaml/opam-repository

In the meantime, you can try to `opam pin --edit` the package, to locally tweak its constraints.
