### ISSUE TITLE
External solver failed (ERROR: too many occurrences of argument positional)

### ISSUE THREAD

**Issue by rixed** [ocaml/opam#3312]
Not sure if this has been rep[orted or not, but I couldn't find this exact error message in the issue tracker.
So, while attempting to upgrade a pinned package:

```shell
~/s/s/parsercombinator (master|✚2) $ opam upgrade parsercombinator

=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  � 
[parsercombinator] /Users/rixed/share/src/parsercombinator/ synchronized
[WARNING] External solver failed:
# opam-version 1.2.2
# os           darwin
# command      aspcud /Users/rixed/.opam/log/solver-in-11652-ccabea /Users/rixed/.opam/log/solver-out-11652-42bb52 -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# path         /Users/rixed/share/src/parsercombinator
# exit-code    127
# env-file     /Users/rixed/.opam/log/log-11652-9b8556.env
# stdout-file  /Users/rixed/.opam/log/log-11652-9b8556.out
# stderr-file  /Users/rixed/.opam/log/log-11652-9b8556.err

[ERROR] External solver failure, please fix your installation and check /Users/rixed/.opam/config and variable $OPAMEXTERNALSOLVER.
        You may also retry with option --use-internal-solver
```

Running the above aspcud command by hand with increased verbosity returned `too many occurrences of argument positional`.
Also, aspcud version is 1.9.4.

Retrying to upgrade worked but removed another package supposedly conflicting with that one, that I was allowed to reinstall.

I guess something fishy was going on with my setup but have no idea what. Although this is very minor I thought it was better to report anyway.

```shell
~ $ opam config report
# OPAM config report
# opam-version    1.2.2 
# self-upgrade    no
# os              darwin
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            4
# repositories    1* (http), 2 (local)
# pinned          8 (path)
# current-switch  ramen2
# last-update     2018-04-24 14:47
```

**Comment by AltGr** [comment]
`aspcud` is no longer used by default in opam 2, so it should be safe from this issue; I'd have been interested in the related `cudf` file though, to try and reproduce (`opam install xxx --cudf foo` generates `foo-1.cudf`, which contains the exact request sent to the solver). I haven't seen this precise error either.

Thanks for reporting!

**Comment by rixed** [comment]
Good to know how to get the cudf file. Will do this whenever I see something strange from now on.
