### ISSUE TITLE
Busybox shell detection regression due to use of `ps -p`

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#3314]
There's a regression in shell detection from #3275 on Busybox `ps` which doesn't have `-p` -- e.g. on Alpine Linux.

```
$ docker run ocaml/opam2-staging:alpine
/bin/ps: unrecognized option: p
BusyBox v1.27.2 (2018-01-29 15:48:57 GMT) multi-call binary.

Usage: ps [-o COL1,COL2=HEADER]

Show list of processes

	-o COL1,COL2=HEADER	Select columns for display
```

**Comment by dra27** [comment]
Gah, what's the point in Posix?!? Give me perfectly defined MSDN docs any day :wink:

**Comment by dra27** [comment]
Is it actually failing, or just displaying crap on stderr?

**Comment by avsm** [comment]
The command's failing and displaying crap on stderr :)

**Comment by dra27** [comment]
So detection is failing completely? That's unexpected - if the command fails, it's supposed to be falling back to checking `SHELL`
