### ISSUE TITLE
opam init --comp not documented in man pages

### ISSUE THREAD

**Issue by nagaflokhu** [ocaml/opam#3315]
There is no mention of the `--comp` option in either `man opam`/`opam help` or `opam help init`. I am using opam 1.2.2_4 on macOS Sierra, installed via Homebrew. I would be happy to add `--comp VERSION` as an alternative to `--compiler=VERSION` to the opam-init man page at a later time.

**Comment by dra27** [comment]
It's not mentioned because it's not an option per se - you can also give `--co`, `--com`, `--compi`, etc. 

See the paragraph on Optional Arguments in [Cmdliner's manual](http://erratique.ch/software/cmdliner/doc/Cmdliner.html#cmdline) for more info.

**Comment by nagaflokhu** [comment]
I see. Thank you!
