### ISSUE TITLE
install opam man pages in .opam/[version]/man directory

### ISSUE THREAD

**Issue by pmetzger** [ocaml/opam#3318]
Right now, no manual pages are installed for opam, one reads the man pages with `opam --help`, but this precludes the possibility of reading the man pages with alternative manual readers like Emacs's `M-x man` support.

**Comment by dra27** [comment]
`make man` builds them in `doc/man` - is that sufficient, or do you think they should be installed in $PREFIX/man always?

**Comment by pmetzger** [comment]
I think they should also be installed in $PREFIX/man so that "man opam" etc. work correctly, yes.

**Comment by AltGr** [comment]
indeed, I thought they did, thanks for the report!
