### ISSUE TITLE
Faulty camlp5 package detection script

### ISSUE THREAD

**Issue by dra27** [ocaml/opam#3322]
You've been directed to this page either because you're curious or because the script at https://github.com/dra27/opam/blob/camlp5-detection/shell/opam-detect.sh has advised you to come here.

If you have received the message:

```
opam 1.2 root found in /home/your-user-id/.opam
camlp5 is faulty AND installed AND the system compiler is OCaml 4.06.1

THIS ROOT CANNOT BE UPDATED OR UPGRADED. DO NOT ALLOW OPAM TO UPGRADE THE SYSTEM
COMPILER. DOING SO WILL ATTEMPT TO ERASE YOUR MACHINE
Please see https://github.com/ocaml/opam/issues/3322 for more information
```

then **please do not attempt to run any OPAM 1.2.2 commands**. In particular, this question:

```
Your system compiler has been changed. Do you want to upgrade your OPAM installation 
```

**must be answered with NO**. Especially if you're running on a non-GNU system such as macOS, you run a serious risk of erasing all of your personal files if you don't answer with no.

The problem is a faulty version of the `camlp5` package in opam-repository which was fixed on 18 Feb 2018 but which your system hasn't yet downloaded. You can fix this in one of two ways:

 1. Upgrade to opam 2 (you can safely tell your opam version at any time by running `opam --version`). However, this is a one-way operation.
 2. Downgrade your system compiler back to OCaml 4.06.0 - instructions for this vary, please do comment below if you need specific OS help. You can tell that you've successfully downgraded the system compiler by running the `opam-detect.sh` script again and verifying that it no longer displays the message above.

Note that if you downgrade your system compiler to a different version to the one you previously had installed, you will still get the message about upgrading the system compiler from OPAM 1.2.2 when you run `opam update`. If the `opam-detect.sh` script has told you to run to `opam update` then this upgrade will be safe, because you do not have OCaml 4.06.1, so the faulty camlp5 package instruction will not be triggered. **Backing up your files before doing this is of course recommended!**

**Comment by dra27** [comment]
Preliminary version of the script at https://github.com/dra27/opam/tree/camlp5-detection/shell/opam-detect.sh. Output on an affected system:

```
dra@bionic:~/opam/shell$ ./opam-detect.sh 
opam 1.2.2 found
Scanning /home/dra for opam roots...
. opam 1.2 root found in /home/dra/.opam
.. The system switch of this root HAS camlp5 7.03 installed
.. At least one package repository appears to contain a faulty camlp5.7.03 package
... The system compiler is OCaml 4.06.1
... DO NOT RUN ANY opam COMMANDS WITH THIS ROOT
... Please see http://somewhere.com for more information
```

output on a system which needs `opam update`, but where OCaml 4.06.1 is not the system compiler:
```
dra@bionic:~/opam/shell$ ./opam-detect.sh 
opam 1.2.2 found
Scanning /home/dra for opam roots...
. opam 1.2 root found in /home/dra/.opam
.. The system switch of this root HAS camlp5 7.03 installed
.. At least one package repository appears to contain a faulty camlp5.7.03 package
... The system compiler is not OCaml 4.06.1
... You should run opam update for this root
```

opam 2.x not (yet) supported. The tool does support multiple opam roots for scanning.

**Comment by nerpderp83** [comment]
@dra27 

Wouldn't line

https://github.com/dra27/opam/blob/camlp5-detection/shell/opam-detect.sh#L17

encourage one to run "opam update" ?

**Comment by kit-ty-kate** [comment]
Given the age of this ticket and of opam 1.2.2 systems, i think it's fair to close it. If anyone is still using the script the ticket will show up anyway, and people are still able to reply even if the ticket is closed.
