### ISSUE TITLE
Spurious messages during "opam upgrade"

### ISSUE THREAD

**Issue by pmetzger** [ocaml/opam#3331]
I keep getting the following fairly spurious error when trying to do an `opam upgrade`:

```
$ opam upgrade --verbose
Everything as up-to-date as possible.
The following newer versions couldn't be installed:
  - base-bytes.legacy is not available because your system doesn't comply with
    ocaml-version < "4.02.0".
The following would require downgrades or uninstalls, but you may upgrade them
explicitly:
  - async.v0.11.0
  - async_extra.v0.11.0
  - async_kernel.v0.11.0
  - async_rpc_kernel.v0.11.0
[...]
```
Note that this happens even if I blow away my `.opam` and start from scratch. I used MacPorts to bootstrap. Here's my config:

```
$ opam config report
# OPAM config report
# opam-version    1.2.2 
# self-upgrade    no
# os              darwin
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            4
# repositories    1* (http)
# pinned          0
# current-switch  4.06.1
# last-update     2018-05-04 18:46
```

**Comment by dra27** [comment]
Is the ellipsis OPAM's or yours? Would you be able to do a "run" where you do `opam list` before the failing `opam upgrade` and post the full output of both?

**Comment by pmetzger** [comment]
The ellipsis is mine. I didn't want to overwhelm you with lines.

I can post the full output but it would be Very Long to insert here. I'll put them into a gist instead: https://gist.github.com/pmetzger/912c110e1467f49d62086194bef690f6

**Comment by dra27** [comment]
And what are the root packages (ie what was the `opam install` command you used to populate the switch)

**Comment by pmetzger** [comment]
Almost a fresh install:

```
$ opam list --installed-roots
# Installed packages for 4.06.1:
async             v0.9.0  Monadic concurrency library
async_graphics     0.5.1  Async wrapper for the OCaml Graphics library
base-bigarray       base  Bigarray library distributed with the OCaml compiler
base-threads        base  Threads library distributed with the OCaml compiler
base-unix           base  Unix library distributed with the OCaml compiler
cohttp             1.1.0  An OCaml library for HTTP clients and servers
coq                8.8.0  Formal proof management system.
core              v0.9.2  Industrial strength alternative to OCaml's standard li
core_bench        v0.9.0  Benchmarking library
core_extended     v0.9.1  Extra components that are not as closely vetted or as 
cryptokit           1.12  A library of cryptographic primitives.
hevea               2.29  A quite complete and fast LATEX to HTML translator
lambdasoup         0.6.2  Easy functional HTML scraping and manipulation with CS
menhir          20171222  LR(1) parser generator
merlin             3.0.5  Editor helper, provides completion, typing and source 
ocp-indent         1.6.1  A simple tool to indent OCaml programs
sedlex            1.99.4  unicode-friendly lexer generator
tuareg             2.1.0  OCaml mode for GNU Emacs and XEmacs.
utop               2.1.0  Universal toplevel for OCaml
```

**Comment by dra27** [comment]
Thanks for that (just a general thing: clipping opam output is rarely a good idea - if you knew which lines indicated the problem and could be ignored, then you wouldn't have an issue!)

The base-bytes.legacy message is a bit silly - though not OPAM's fault. I've just made a pull request for that to opam-repository as it's definitely better to be told you can't upgrade base-bytes on an old version of OCaml than to be told, as here, that you need to downgrade OCaml in order to install a legacy version!

The rest is because of `async_graphics` - was that part of what you were regarding as spurious (happy to go into more detail if you want!)

**Comment by dra27** [comment]
Actually, if that's it, this can be closed now - OPAM's not malfunctioning here. The issue is the package repo - there's no reason in principal not to have a newer version of a package constrain you to an older version of a dependency (in this case, ocaml itself), it's just plain unnecessary there.

**Comment by pmetzger** [comment]
Then we can close it! Thank you so much for the help, @dra27!

**Comment by pmetzger** [comment]
@dra27 Is there any thought on when the package repo might be fixed?
