### ISSUE TITLE
Keep track of requested vs. unrequested packages

### ISSUE THREAD

**Issue by pmetzger** [ocaml/opam#3332]
One nice feature of MacPorts is it keeps track of which packages a user asked for vs. the ones that were installed because another package depended on them. Such packages are termed "requested". 

This makes it easy (as just one example) to print out a list of only those things that you _really_ want to install if you blow away your packages and restart from scratch (i.e., if you just install the requested packages, the others will be brought in as a consequence, but not any that are no longer required by the installed packages.)

It also makes it possible to figure out which packages can be gc'ed after you remove some other ones (on the basis that you never really wanted _them_, just something that depended on them.)

**Comment by dra27** [comment]
OPAM calls these roots and that's the source of the underlines in `opam list` - see also the `--set-root` of `opam install`

**Comment by pmetzger** [comment]
My mistake for not noticing. Perhaps the manual should explain this a bit better? Anyway, I'll close this.

**Comment by dra27** [comment]
It sounds like a good entry for https://github.com/ocaml/opam/blob/master/doc/pages/FAQ.md or (possibly Usage.md), yes!

**Comment by pmetzger** [comment]
So, as we've established, neither `opam list --installed-roots` nor `opam remove -a` are prominently mentioned in a place like the FAQ or someplace like https://opam.ocaml.org/doc/Usage.html

(I didn't know about `remove -a` until you just mentioned it, and thank you for that btw.)

**Comment by dra27** [comment]
I think part of this is because the man pages are viewed as a key part of the manual, and I think the original expectation was that the man pages would be read in order to discover the features, not just to look up detail.

I'm not saying that's a good thing, just that I think that's why it's that way at the moment!

**Comment by pmetzger** [comment]
Oh, I quite understand. I think part of the problem may also be that the manual is broken up into many submanuals and since I can't read them inside Emacs I never went through all of them as carefully as I might otherwise.

BTW, as a possible mitigation, can the man pages be put up on opam.ocaml.org? It would make them more easily parused.
