### ISSUE TITLE
2.0.0 Solver compilation error on WinXP

### ISSUE THREAD

**Issue by houndofsound** [ocaml/opam#3333]
I compiled and installed opam without the solver as there were linking errors for that (below).
MCCS as a C++ app suggests this is a cygwin library dependency not mentioned in the install notes.
I did install what I thought would be the right C++ cygwin packages but to no avail.

$ make
/cygdrive/e/temp/opam2/opam-full-2.0.0-rc/src_ext/jbuilder/_build/install/defaul
t/bin/jbuilder build  opam-installer.install opam.install
       ocaml (internal)
fatal: Not a git repository (or any parent up to mount point /cygdrive/e)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
    ocamlopt src/client/opamMain.exe (exit 2)
(cd _build/default && /home/kris/.opam/4.06.1/bin/ocamlopt.opt -w -40 -w +a-4-44
-48 -safe-string -g -o src/client/opamMain.exe -I /home/kris/.opam/4.06.1/lib/oc
aml/ -I src/client -I src/core -I src/format -I src/repository -I src/solver -I
src/state -I src_ext/cmdliner/src -I src_ext/cudf -I src_ext/dose3/algo -I src_e
xt/dose3/common -I src_ext/extlib/src -I src_ext/mccs/src -I src_ext/mccs/src/gl
pk -I src_ext/ocamlgraph/lib -I src_ext/ocamlgraph/src -I src_ext/opam-file-form
at/src -I src_ext/re/lib -I src_ext/result /home/kris/.opam/4.06.1/lib/ocaml/uni
x.cmxa /home/kris/.opam/4.06.1/lib/ocaml/bigarray.cmxa src_ext/ocamlgraph/lib/gr
aphlib.cmxa src_ext/re/lib/re.cmxa src_ext/ocamlgraph/src/graph.cmxa src_ext/re/
lib/re_perl.cmxa src/core/opam_core.cmxa src_ext/opam-file-format/src/opam_file_
format.cmxa src_ext/re/lib/re_pcre.cmxa src_ext/re/lib/re_posix.cmxa src/format/
opam_format.cmxa src/repository/opam_repository.cmxa src_ext/extlib/src/extlib.c
mxa src_ext/cudf/cudf.cmxa src_ext/dose3/common/common.cmxa src_ext/mccs/src/glp
k/mccs_glpk.cmxa src_ext/dose3/algo/algo.cmxa src_ext/mccs/src/mccs.cmxa src_ext
/result/result.cmxa src/state/opam_state.cmxa src/solver/opam_solver.cmxa src_ex
t/re/lib/re_glob.cmxa src_ext/cmdliner/src/cmdliner.cmxa src/client/opam_client.
cmxa src/client/opamMain.cmx)
** Cannot resolve symbols for src_ext/mccs/src\libmccs_stubs.a(removed_criteria.
o/
):
 __ZTVN10__cxxabiv117__class_type_infoE
 __ZTVN10__cxxabiv120__si_class_type_infoE
** Cannot resolve symbols for src_ext/mccs/src\libmccs_stubs.a(notuptodate_crite
ria.o/
removed_criteria.o/
):
 __ZTVN10__cxxabiv117__class_type_infoE
 __ZTVN10__cxxabiv120__si_class_type_infoE
** Cannot resolve symbols for src_ext/mccs/src\libmccs_stubs.a(changed_criteria.
o/
constraint_generation.o/
count_criteria.o/
cudf_reductions.o/
lexagregate_combiner.o/
notuptodate_criteria.o/
removed_criteria.o/
):
 __ZTVN10__cxxabiv117__class_type_infoE
 __ZTVN10__cxxabiv120__si_class_type_infoE
** Cannot resolve symbols for src_ext/mccs/src\libmccs_stubs.a(glpk_solver.o):
 __Unwind_Resume
 __ZTVN10__cxxabiv117__class_type_infoE
 __ZTVN10__cxxabiv121__vmi_class_type_infoE
** Cannot resolve symbols for src_ext/mccs/src\libmccs_stubs.a(mccs_stubs.o):
 __Unwind_Resume
 __ZNSs4_Rep20_S_empty_rep_storageE
** Cannot resolve symbols for src_ext/mccs/src\libmccs_stubs.a(lexagregate_combi
ner.o/
notuptodate_criteria.o/
removed_criteria.o/
):
 __ZTVN10__cxxabiv117__class_type_infoE
 __ZTVN10__cxxabiv121__vmi_class_type_infoE
** Cannot resolve symbols for src_ext/mccs/src\libmccs_stubs.a(cudf_tools.o):
 __Unwind_Resume
** Cannot resolve symbols for src_ext/mccs/src\libmccs_stubs.a(cudf_reductions.o
/
lexagregate_combiner.o/
notuptodate_criteria.o/
removed_criteria.o/
):
 __Unwind_Resume
** Cannot resolve symbols for src_ext/mccs/src\libmccs_stubs.a(constraint_genera
tion.o/
count_criteria.o/
cudf_reductions.o/
lexagregate_combiner.o/
notuptodate_criteria.o/
removed_criteria.o/
):
 __Unwind_Resume
** Cannot resolve symbols for src_ext/mccs/src\libmccs_stubs.a(new_criteria.o):
 __ZTVN10__cxxabiv117__class_type_infoE
 __ZTVN10__cxxabiv120__si_class_type_infoE
** Cannot resolve symbols for src_ext/mccs/src\libmccs_stubs.a(count_criteria.o/

cudf_reductions.o/
lexagregate_combiner.o/
notuptodate_criteria.o/
removed_criteria.o/
):
 __ZNSs4_Rep20_S_empty_rep_storageE
 __ZTVN10__cxxabiv117__class_type_infoE
 __ZTVN10__cxxabiv120__si_class_type_infoE
** Cannot resolve symbols for src_ext/mccs/src\libmccs_stubs.a(mccscudf.o):
 __Unwind_Resume
 __ZNSs4_Rep20_S_empty_rep_storageE
 __ZTTSt18basic_stringstreamIcSt11char_traitsIcESaIcEE
 __ZTVSt15basic_streambufIcSt11char_traitsIcEE
 __ZTVSt15basic_stringbufIcSt11char_traitsIcESaIcEE
 __ZTVSt18basic_stringstreamIcSt11char_traitsIcESaIcEE
 __ZTVSt9basic_iosIcSt11char_traitsIcEE
File "caml_startup", line 1:
Error: Error during linking
make: *** [Makefile:96: opam.install] Error 1

<include here the output of `opam config report`, if applicable>
$ opam config report
# opam config report
# opam-version      2.0.0~rc
# self-upgrade      no
# system            arch=x86_32 os=cygwin os-distribution=cygwin os-version=unknown
[ERROR] No available solver found. Make sure your solver configuration is
        correct. This opam has been compiled without a built-in solver, so you
        need to install and configure an external one. See
        http://opam.ocaml.org/doc/Install.html#ExternalSolvers for details.
# read-state        OpamStd.OpamSys.Exit(50)

**Comment by dra27** [comment]
You need a version of flexlink patched with https://github.com/alainfrisch/flexdll/pull/48.

Of course, you also need to upgrade from Windows XP, but I don't that's actually the issue here.

**Comment by houndofsound** [comment]
thanks.
by the way
http://opam.ocaml.org/doc/Install.html#ExternalSolvers
doesn't exist. yet!

**Comment by houndofsound** [comment]
I put the -lgcc_eh into the 0.37 source and it didn't change the outcome.
nm libgcc_eh.a showed none of the above symbols.
I then added -lstdc++ which is a googled solution to the lack of the above symbols in other settings
and nm indeed shows them defined - but no change in outcome!
libstdc++.a libgcc_eh.a are present on my system.
adding -verbose to the captured invocation of ocamlopt shows the flexlink command has them listed.
unfortunately the intermediate /tmp/xxx.o file doesn't persist.
any idea?

**Comment by dra27** [comment]
Oh, hang on, that PR still needs some work, doesn't it.

I think you should change the `-lgcc` around line 1246 of reloc.ml to `-lgcc_s` (i.e. change the `default_libs` assignment in the `` `CYGWIN`` case). I'm fairly sure you will also need commit 361b6e8.

**Comment by dra27** [comment]
It's in my fork of flexdll (dra27) referenced from the PR. Having looked again, I think it **is** that you wanted to add -lgcc_eh, rather than changing it to `-lgcc_s`. To be honest, I'm not completely sure why our CI is building mccs fine on Cygwin, but you're having trouble - but it's a while since I dusted the Cygwin builds off!

**Comment by houndofsound** [comment]
I just went through the complete list of commits of your flexdll fork
and didn't find 361b6e8.
but you say referenced from the PR - what PR?
I'm sorry but this is unfamiliar territory for me.

**Comment by houndofsound** [comment]
OK, I've found it thanks to a googlie and no thanks to github's search facility!
I've already tried each of -lgcc_eh, -lgcc_s, -lstdc++ to no avail.

**Comment by dra27** [comment]
What's the output of `uname -a` on your system?

**Comment by dra27** [comment]
> the __imps_XXXX patch doesn't look like it affects the symbols I'm encountering.

Have you actually tried a version with https://github.com/dra27/flexdll/commit/361b6e802e6d615321b7c122628472a8b2784017 ?

**Comment by houndofsound** [comment]
I have this morning - and it worked!
thank you very much :)
