### ISSUE TITLE
opam upgrade should explain things being kept back better.

### ISSUE THREAD

**Issue by pmetzger** [ocaml/opam#3334]
Say you type `opam upgrade` and see this:

```
$ opam upgrade 
Everything as up-to-date as possible (run with --verbose to show unavailable
upgrades).
The following would require downgrades or uninstalls, but you may upgrade them
explicitly:
  - lwt.4.0.1
$
```

So what seems to be going on here is (for example) that I have utop 2.1.0  installed which conflicts with lwt 4.0.1, and I'm currently at lwt 3.3.0.

What would be nice would be if the message explained this. Right now it's confusing. First, the line that says:

```
The following would require downgrades or uninstalls, but you may upgrade them
explicitly:
```

is confusing. (Trust me, it confused me at first.) It might be better if it said something like:

```
The following packages are not being upgraded because the new versions
conflict with other installed packages that would need to be downgraded
or uninstalled. However, you may "opam upgrade" these packages explicitly,
which will ask permission to downgrade or uninstall the conflicting packages.
```

And second, it would be nice if it said something like:

```
- lwt.4.0.1 (3.3.0 installed, 4.0.1 conflicts with utop (all versions).)
```

(Perhaps some would argue for the second part only if you say `--verbose` but I think it should always tell you.)

**Comment by dra27** [comment]
I agree - and especially with Jane Street packages like in your referenced example, it would be handy to have an option for something clearer. It probably shouldn't be done by default, because you need to invoke the solver each time, but I wonder if `--verbose` could try the following algorithm:

 - Take the first package which can't be upgraded and solve `opam upgrade X`.
 - Note package downgrades and removals required
 - Remove any packages which are upgraded as part of that solution to their targets from the list
 - etc.

That should allow you a messages like:

```
Requiring utop to be removed:
 - lwt.4.0.1
```

or, from your previous examples:
```
Requiring async_graphics to be removed:
 - etc.
```

There might possibly be some additional cleverness for the possibility of individual sets conflicting with each other, though that might be taking it too far.

**Comment by pmetzger** [comment]
So changing the error message to be clearer (I wrotea new one above) should be a simple commit. Maybe that could go in first, and then the rest of this could be considered separately.

**Comment by dra27** [comment]
Yes, indeed - do you want to do a PR?

**Comment by AltGr** [comment]
```
The following packages are not being upgraded because the new versions
conflict with other installed packages that would need to be downgraded
or uninstalled. However, you may "opam upgrade" these packages explicitly,
which will ask permission to downgrade or uninstall the conflicting packages.
```

Seems clearer, indeed! Note however that the `opam upgrade PKG` might not always be successful (if you pinned a dependency to an incompatible version, for example) — but the command should explain the reason when that happens. Maybe the following would be more accurate, but I am not sure it is much clearer than the original message (it's sometimes hard to forget about all this inner workings knowledge!)

```
The following packages have been kept back due to dependencies or conflicts, try `opam upgrade PACKAGE` to enforce their upgrade.
```

About the specific explanation message, while I agree this would be extremely nice
```
- lwt.4.0.1 (3.3.0 installed, 4.0.1 conflicts with utop (all versions).)
```
I am not quite sure it is doable in practice for the general case. The reason in this case is clear and simple, but that can get arbitrarily complex, and just trying to display understandable messages in case of conflicts is quite a complex piece of code. One thing we could try, though, is limit to detecting the conflicts between the newer version and the installed packages and list that.

**Comment by pmetzger** [comment]
Pull request is now in #3339. Note that I haven't tested the error message out IRL, and I'm a bit unused to this formatting primitive so I'm not sure if it will come out looking nice.

**Comment by AltGr** [comment]
It should, it's just a `printf` that will word wrap depending on the terminal width. Thanks!

**Comment by rjbou** [comment]
@pmetzger PR #3354 improves the message, giving more explicit reasons. I used [`utop`](https://github.com/ocaml/opam-repository/blob/2.0.0/packages/utop/utop.2.1.0/opam#L18) example example with [`lambda-term`](https://github.com/ocaml/opam-repository/blob/2.0.0/packages/lambda-term/lambda-term.1.12.0/opam#L15), and [`0install`](https://github.com/ocaml/opam-repository/blob/2.0.0/packages/0install/0install.2.12.3/opam#L23), to show conflicts from  `depends:` and `conflicts:` fields: 
```$ opam upgrade
Everything as up-to-date as possible (run with --verbose to show unavailable upgrades).
The following packages are not being upgraded because the new versions conflict with 
other installed packages that would need to be downgraded or uninstalled. However, 
you may "opam upgrade" these packages explicitly, which will ask permission to downgrade 
or uninstall the conflicting packages.
  - lwt.4.0.1
    ⊘ lambda-term.1.12.0 is installed and requires lwt >= 2.7.0 & lwt < 4.0.0
    ⊘ 0install.2.12.3 is installed and conflicts with lwt >= 4.0.0
```

**Comment by intractabilis** [comment]
To be honest, it's still confusing. Why "upgrade" downgrades? Moreover, nothing was downgraded when I explicitly "opam upgrade" the listed packages. Instead, a beta version of the compiler was installed. Which I didn't ask for.

**Comment by dra27** [comment]
@intractabilis - would it be possible to have this with more detail in a new issue, especially as what you're briefly describing does not sound like it's related to the original issue here?
