### ISSUE TITLE
opam switch create on NetBSD

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#3362]
Hello,

With opam 2.0.0~rc:
```
$ opam switch create 4.06.1
[...]
#=== ERROR while compiling ocaml-base-compiler.4.06.1 =========================#
"./configure": command not found.
```

**Comment by dra27** [comment]
Could post the content of the ellipsis?

**Comment by UnixJunkie** [comment]
https://gist.github.com/UnixJunkie/191649441b3227b501f150393abc5a94

**Comment by dra27** [comment]
This is definitely with the original rc, not rc2?

If you run with `OPAMKEEPBUILDDIR=yes`, the compiler source tree should be left behind on the error (assuming you don’t tell opam to delete the switch, obviously) - is `configure` executable?

**Comment by UnixJunkie** [comment]
yes, not yet using rc2.

**Comment by dra27** [comment]
Are you able to try the second part?

**Comment by UnixJunkie** [comment]
2.0.0-rc2 doesn't compile in there:
```
'~/bin/ocamlc.opt' -g -w -40 -o boot.exe unix.cma boot.ml
File "boot.ml", line 1:
Error: Error on dynamically loaded library: /usr/pkg/lib/ocaml/stublibs/dllunix.so: /usr/pkg/lib/ocaml/stublibs/dllunix.so: Undefined PLT symbol "caml_strdup" (symnum = 133)
Makefile:27: recipe for target 'src_ext/jbuilder/_build/install/default/bin/jbuilder' failed
gmake: *** [src_ext/jbuilder/_build/install/default/bin/jbuilder] Error 2
```

**Comment by UnixJunkie** [comment]
I think
```
OPAMKEEPBUILDDIR=yes
```
is ignored by 2.0.0-rc

**Comment by rjbou** [comment]
If you answer no to the last question 
```Switch initialisation failed, clean up? ('n' will leave the switch partially installed) [Y/n]```
is file `~/.opam/4.06.1/.opam-switch/{build,sources}/ocaml-base-compiler.4.06.1/configure` exists and is an executable?

**Comment by AltGr** [comment]
> 2.0.0-rc2 doesn't compile in there

hmm, this one seems to have to do with the bootstrap of the (bundled) jbuilder... will have to ask the devs.
On the original issue, this seems quite weird... as @rjbou pointed out, the download of the archive seems OK from your logs (but you could still double-check that: `md5sum ~/.opam/download-cache/md5/d0/d02eb67b828de22c3f97d94b3c46acba` returns `d02eb6...`) ; so we should probably check that the extraction was correct, including the executable bits and other permissions ?

**Comment by rjbou** [comment]
@UnixJunkie What is the version of your installed `tar`.
It would confirm the source of the error: `tar` does not handle `pax_global_header` before 1.14 (cf. [this post](https://github.com/backdrop-ops/contrib/issues/55#issuecomment-73814500)).

**Comment by UnixJunkie** [comment]
gtar (GNU tar I guess) is 1.29.
But the default tar has no --version/-version option.

**Comment by UnixJunkie** [comment]
OK, If I alias tar to gtar by putting a soft link to it in my PATH, it solves the problem.
I.e., on some BSDs, using gtar instead of tar might be a good idea.

**Comment by AltGr** [comment]
Ok, so we could either:
- detect & use `gtar` by default if present
- detect, after uncompressing, the `pax_global_header` situation, and put back the files in their expected place manually

The second solution doesn't seem too difficult and would improve our compatibility...

**Comment by UnixJunkie** [comment]
Looks good to me.
I also prefer the second solution, because I'm not sure gtar would always be available.

**Comment by rjbou** [comment]
PR of the second solution merged. Thanks for reporting!
