### ISSUE TITLE
opam pin documentation for kind of pinning is unclear

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#3366]
```
       -k KIND, --kind=KIND
           Sets the kind of pinning. Must be one of one of `version', `path',
           `http', `git', `darcs', `hg', `none' or `auto'. If unset or auto,
           is inferred from the format of the target, defaulting to the
           appropriate version control if one is detected in the given
           directory, or to path otherwise. OPAMPINKINDAUTO can be set to "0"
           to disable automatic detection of version control.Use none to pin
           without a target (for virtual packages).
```

I was wondering what the equivalent of opam1's mixed pin was (so that my working git directory would be pinned). But in the manual page, there is no explanation of what some of the options do (e.g. the difference between `path` or `version`).

**Comment by AltGr** [comment]
mixed pin was removed as more potentially confusing than it was useful (there were strong advocates against it, and it indeed brought a few annoying corner cases, e.g. modified files were OK but not added files). The closest you can get, apart from path pinning, is the `--working-dir` option, which needs to be specified at every reinstall.

Would it be clearer if we added a sentence specifying that `version` will use the given version as found in the repository ?

**Comment by bluddy** [comment]
I'm also really confused by this. My pin automatically set to `git+file`, but updating either the branch or the file did nothing. Only when I forced a re-pin with `-k path` was I able to get opam to pick on changes to files.

**Comment by bluddy** [comment]
I don't understand why working dir is made so hard to use. Should I just use `path` instead? Working dir is the most natural option when modifying packages.

**Comment by AltGr** [comment]
The main argument against it is that it's good _when modifying the package_, but when you move to a different project and run `opam update -u`, you don't want the current state of the original package to be synched with its possibly broken current source state. Also, I wouldn't call adding `-w` to the command-line "so hard to use" ? There are pretty lengthy arguments about it in the tracker, if you care to search for them...

You can use `path` pinning instead, but be aware that it will copy all files, including build artifacts present in you source tree. It can be OK, but some packages don't support well being built from an unclean directory.

**Comment by bluddy** [comment]
OK I missed the fact that `-w` is there instead of the long form. That's not too bad I guess.

**Comment by rjbou** [comment]
Working-dir is fixed on master: it reflects exactly the local directory.
Thanks!
