### ISSUE TITLE
Why is `--set-switch` needed ?

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#3369]
`eval $(opam env --sw 4.06.0)` used to work, but now it needs `--set-sw`. I don't know why, it's not clear from the documentation, and it will confuse opam 1 users. It also seems quite superfluous, so I wonder if it's such a good idea to need it.

**Comment by AltGr** [comment]
See #3143 for the discussion; basically, it didn't interact so well with local switches.

**Comment by Drup** [comment]
Fair enough. I guess the message when you don't set `--set-sw` should be sufficient (well, except that users don't read error messages :p)
