### ISSUE TITLE
`opam switch create <path> --as <switch>`

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#3370]
I remember @AltGr telling me that having a local switch that points to a global one was possible but
1. I don't remember how, but pretty sure it was something involving a symlink
2. It's not written in the documentation

Sharing one switch between multiple project is certainly more than useful, and with the new autoswitching when entering directories that contain local switch, defining local switches everywhere seem desirable. Having first class support for it would be nice.

**Comment by AltGr** [comment]
Yes, this was in #3269, and related issue #3258. So it needs documenting, but `ln -s OPAMROOT/switchname _opam` is supported and should have `switchname` be automatically selected in the current directory and its descendents (and if you enabled the shell hook feature, the env will be synchronised automatically when you `cd` there)

**Comment by Drup** [comment]
Alright, but I would *much* prefer to have an opam command for that. It makes it discoverable by simply looking at the documentation.

**Comment by AltGr** [comment]
Sure, I didn't mean to exclude a new option! Since `opam switch` is subcommand-based, how about `opam switch link DIR [SWITCH]` / `opam switch unlink DIR` ?

**Comment by Drup** [comment]
I'm not sure if it makes sense to distinguish creation from "linking", but I would be ok with both solution.

I guess I will defer to more opinionated UX people. ;)
