### ISSUE TITLE
opam-devel fails to build on WSL, 4.06.1

### ISSUE THREAD

**Issue by bluddy** [ocaml/opam#3376]
For some reason, opam 2.0 depends on mccs. Not sure why -- didn't we have an internal solver now?

Anyway, mccs fails to build, reporting nothing in the .err and .out.

**Comment by dra27** [comment]
mccs is the internal solver!

**Comment by bluddy** [comment]
Turns out it was a dune issue, possibly together with opam 1.2 -- jbuilder disappeared completely when pinning.

**Comment by rjbou** [comment]
Note that, as `bwrap` is not supported, opam2 sandboxing doesn't work on WSL (cf. https://github.com/ocaml/opam-repository/issues/12050).

**Comment by bluddy** [comment]
> Note that, as bwrap is not supported, opam2 sandboxing doesn't work on WSL (cf. ocaml/opam-repository#12050).

Looks like this issue has been fixed in an insider build, which means it should eventually be available.

**Comment by dra27** [comment]
This issue hasn't been fixed in WSL.
