### ISSUE TITLE
version 1.2.2 doesn't build from source with ocaml 4.06

### ISSUE THREAD

**Issue by ygrek** [ocaml/opam#3386]
because of old bundled extlib version

Is  there any workaround? Updating extlib doesn't work because it will need ocamlfind and cppo..

**Comment by ygrek** [comment]
The simplest solution is to do `OCAMLPARAM="safe-string=0,_" make lib-ext all install`

 I guess this is worth adding to documentation/Install.

Issue solved for me, leaving open at your discretion.

**Comment by rjbou** [comment]
> I guess this is worth adding to documentation/Install.

Indeed, thanks for reporting!

**Comment by ygrek** [comment]
uh, same old extlib version in 2.0.0 rc? https://github.com/ocaml/homebrew-ocaml/issues/11
