### ISSUE TITLE
Improve usability for packagers

### ISSUE THREAD

**Issue by frispete** [ocaml/opam#3389]
Hi,

here's a snippet from a typical innstallation sequence, that is needed for packagers after switching to dune/opam:

```
%build
jbuilder build @install

%install
opam-installer \
    --prefix=%{buildroot}%{_prefix} \
    --docdir=%{buildroot}%{_docdir} \
    --libdir=%{buildroot}%{_libdir}/ocaml \
    --mandir=%{buildroot}%{_mandir} \
    %{name}.install

# remove docs: they landed in %{_docdir}/%{origname}
rm -rf %{buildroot}%{_docdir}

# remove unused opam installation artefacts
rm -rf %{buildroot}%{_libdir}/ocaml/%{name}/{META,opam}
```

I might miss something to improve the situation, but there's room for conceptual improvements, I guess. As a starter, what do you think about a --distdir option, that is prepended to all other paths.

**Comment by dra27** [comment]
An aside - the `META` file is not an opam artefact and you don’t want to delete it - that’s the required metadata for the `ocamlfind` command.

**Comment by dra27** [comment]
This is related to https://github.com/ocaml/dune/issues/680 and, at least in my opinion, probably better solved there.

**Comment by frispete** [comment]
Hey @dra27, thanks for the quick answer and the pointer.

Since dune forced me to use opam-installer directly, I barked at this tree. Will move over...

**Comment by frispete** [comment]
Related to
> An aside - the META file is not an opam artefact and you don’t want to delete it - that’s the required metadata for the ocamlfind command.

Sure, but there are cases, where you want to keep the binary only, e.g. google-drive-ocamlfuse, then ocamlfind becomes useless, doesn't it?
