### ISSUE TITLE
alias-of not working in opam 2.0.0~beta6

### ISSUE THREAD

**Issue by farao** [ocaml/opam#3390]
Hi,

I'm using Fedora 28 and if I install opam there, the default version is 2.0.0~beta6. Now I'm trying to run a script using opam which uses opam switch with the --alias-of option. I'm getting the error:

opam: unknown option `--alias-of'.

Is there a new way to use such aliases in opam 2? If not, how can I change the script?

Thanks!

**Comment by rjbou** [comment]
Usage of `--alias-of` was for [switch creation](http://opam.ocaml.org/doc/Usage.html#opam-switch): `opam switch <name> --alias-of <version>` where `name` is switch name and `version` compiler version. The [new command](http://opam.ocaml.org/doc/2.0/Usage.html#opam-switch) is `opam switch create <name> <compiler>`. 
You can see `opam switch` help for detailed options and the [upgrade guide](http://opam.ocaml.org/doc/2.0/Upgrade_guide.html#What-you-need-to-be-aware-of).

**Comment by dra27** [comment]
Might it be worth having some of these old command-line switches added back in with error messages about where the features have gone?

**Comment by fpottier** [comment]
After spending 15 minutes looking for the new way of saying `--alias-of`, I second that.
Also, the opam Wiki still contains outdated examples of using `--alias-of`.
