### ISSUE TITLE
sandboxing breaks ccache

### ISSUE THREAD

**Issue by gasche** [ocaml/opam#3395]
I'm now using opam2~rc2. On my Fedora system, running

```
opam switch create . 4.06.1
```

fails with the following error

```
#=== ERROR while compiling ocaml-base-compiler.4.06.1 =========================#
# context     2.0.0~rc | linux/x86_64 |  | https://opam.ocaml.org/2.0#bed714e6
# path        ~/tmp/repro/_opam/.opam-switch/build/ocaml-base-compiler.4.06.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build make world
# exit-code   2
# env-file    ~/.opam/log/ocaml-base-compiler-22947-1872ec.env
# output-file ~/.opam/log/ocaml-base-compiler-22947-1872ec.out
### output ###
# make -C byterun  all
# make[1]: Entering directory '/home/gasche/tmp/repro/_opam/.opam-switch/build/ocaml-base-compiler.4.06.1/byterun'
# echo "/home/gasche/tmp/repro/_opam/lib/ocaml/stublibs" > ld.conf
# echo "/home/gasche/tmp/repro/_opam/lib/ocaml" >> ld.conf
# sed -n -e '/^  /s/ \([A-Z]\)/ \&\&lbl_\1/gp' \
#        -e '/^}/q' caml/instruct.h > caml/jumptbl.h
# gcc -c -O2 -fno-strict-aliasing -fwrapv -Wall -fno-tree-vrp  -g -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE  interp.c
# ccache: error: Failed to create temporary file for /home/gasche/.ccache/tmp/tmp.cpp_stderr: Read-only file system
# make[1]: *** [Makefile:205: interp.o] Error 1
# make[1]: Leaving directory '/home/gasche/tmp/repro/_opam/.opam-switch/build/ocaml-base-compiler.4.06.1/byterun'
# make: *** [Makefile:384: coldstart] Error 2
```

It turns out (I had no idea) that `ccache` is enabled by default on Fedora OSes. Could you add `$HOME/.ccache` to the list of directories to the write whitelist of the sandbox?

For reference (if other users encounter the issue), a local fix is to pass `CCACHE_DISABLE=1` explicitly to the command-line:

```
CCACHE_DISABLE=1 opam switch create . 4.06.1
```

of course, many other OPAM packages (than the compiler) invoke `gcc`, so selectively disabling ccache all the time will get old fast -- then export it in your shell environment, etc.

**Comment by AltGr** [comment]
Indeed, breaking on Fedora is a problem!

Adding to the write-allowed directories shouldn't be difficult. For reference, the addition should be made [here](https://github.com/ocaml/opam/blob/2e8b5e77af72008601db84c22482df179852dec2/src/state/shellscripts/bwrap.sh#L31) and [here](https://github.com/ocaml/opam/blob/2e8b5e77af72008601db84c22482df179852dec2/src/state/shellscripts/sandbox_exec.sh#L19). 

Thanks for reporting!

**Comment by avsm** [comment]
This is weird; why isn't ccache enabled on our Fedora 28 containers? Does some package need to be installed?

**Comment by gasche** [comment]
@avsm: looking more into this, it looks like ccache isn't necessarily installed by default (I found this information on the web for older Fedora release), but Fedora's PATH settings make `/usr/lib64/ccache/gcc` take priority over `/usr/bin/gcc` as soon as ccache was installed by the user. (I'm not entirely sure why ccache is installed on my system as I don't record playing with it in recent times, but my knowledge of RPM repo-inspection tools is too weak to provide a clear answer.)
