### ISSUE TITLE
Minimal opam file incompatibility on v1.2 and v2 when pinning

### ISSUE THREAD

**Issue by bobbypriambodo** [ocaml/opam#3403]
I have the following minimal `todolist.opam` file:

```
opam-version: "1.2"
name: "todolist"
version: "1.0.0"
maintainer: "Your Name <email@example.com>"

depends: [
  "jbuilder" {build}
  "caqti"
  "caqti-lwt"
  "caqti-driver-postgresql"
]
```

I'm having trouble pinning this package with opam 2.0.0~rc2.

With opam.1.2.2 (working as expected, installing the dependencies):

```
$ opam pin add todolist .
Package todolist does not exist, create as a NEW package ? [Y/n] y
todolist is now path-pinned to /Users/bobbypriambodo/Projects/todolist

[todolist] /Users/bobbypriambodo/Projects/todolist/ synchronized
[todolist] Installing new package description from /Users/bobbypriambodo/Projects/todolist

todolist needs to be installed.
The following actions will be performed:
  ∗  install conf-m4                 1           [required by ocamlfind]
  ∗  install jbuilder                1.0+beta20  [required by todolist]
  ...
```

With opam.2.0.0~rc2 (not working):

```
$ opam pin add todolist .
Package todolist does not exist, create as a NEW package? [Y/n] y
[todolist.~dev] synchronised from git+file:///Users/bobbypriambodo/Projects/todolist#master
[NOTE] No package definition found for todolist.~dev: please complete the template
Press enter to start "vim" (this can be customised by setting EDITOR or OPAMEDITOR)...
```

When I press enter, an editor opened with a newly created opam file template which I don't want. Changing `opam-version` to `"2.0"` gives the same outcome. From the [Packaging](https://opam.ocaml.org/doc/2.0/Packaging.html) doc, the necessary fields should only  be `opam-version` and `maintainer`. Do you know where I did wrong?

```
# opam config report
# opam-version      2.0.0~rc2
# self-upgrade      no
# system            arch=x86_64 os=macos os-distribution=homebrew os-version=10.12.6
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              3
# repositories      1 (http) (default repo at 3faa926b)
# pinned            3 (git)
# current-switch    default
```

**Comment by rjbou** [comment]
Is you opam file committed on `master`? As your pinned directory is a git repository, opam won't get the opam file from the disk, but from the local git repository: `git+file:///Users/bobbypriambodo/Projects/todolist#master`

**Comment by bobbypriambodo** [comment]
Ah, that indeed makes sense, I don't think I did. I'll try it and get back to you. Btw, is this behavior (syncing with local git) only introduced in opam 2? Because it worked on opam 1.2 previously.

**Comment by bobbypriambodo** [comment]
Okay, confirmed that doing either of these works for v2:

1) Committing the opam file, or
2) Removing the `.git` folder (therefore not as a git repo)

Thanks! Closing this issue.

**Comment by rjbou** [comment]
Indeed, these are the two solutions to have the opam file automatically retrieved. I reopen the issue as a solution to retrieve opam file, even if not versionned, should be implemented.
Thanks for reporting!

**Comment by dbuenzli** [comment]
I didn't check but I'm almost sure `opam pin add -kpath .` does that.

**Comment by dbuenzli** [comment]
> (syncing with local git) only introduced in opam 2? Because it worked on opam 1.2 previously.

The default behaviour changed. It used to default to `path` pinning even if there was a `git` repo, now it's `git` in the latter case.
