### ISSUE TITLE
`opam show -f version: ./opam` does not read the given `opam` file.

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#3423]
It seems to consult the opam-repository, e.g. here in the repo of `uucp` (whose opam file has no version: field).

```
> opam show --normalise -f version: ./opam
"11.0.0"
```
Here in an opam file which has no version field and which `opam` doesn't seem to match to an existing package:

```
> opam show --no-lint --normalise -f version: ./opam
"~dev"
```

**Comment by rjbou** [comment]
In fact, the actual checkout order is from: pinned, installed, repo. For an unknown package, it will behave as a pin: if no version given, it is a `~dev` package.
But yes, if an `opam` file is given, it should give that file version, not the pinned/installed one.

**Comment by rjbou** [comment]
cf. https://github.com/ocaml/opam/pull/3427#issuecomment-404479669

**Comment by rjbou** [comment]
Thanks for reporting!

**Comment by rjbou** [comment]
New version in #3536.
