### ISSUE TITLE
Document the .opam/config jobs: setting

### ISSUE THREAD

**Issue by pmetzger** [ocaml/opam#3441]
I note that the `jobs` variable (and setting in the `config` file) doesn't seem to be documented. (It also seems to be correctly set by `opam init` so I never noticed this before now.) A brief blurb on it might be appropriate.

**Comment by reynir** [comment]
It's described briefly in the opam2 manual: https://opam.ocaml.org/doc/2.0/Manual.html

**Comment by rjbou** [comment]
In this [section precisely](https://opam.ocaml.org/doc/2.0/Manual.html#configfield-jobs) and in `opam init --help` (manpage).

**Comment by pmetzger** [comment]
Ah. I was looking in the 1.2 manual. Perhaps it is time for 2.0 to be released? It might be nice to note that opam init sets this by default, btw. Anyway, feel free to close this (or to close it after adding a note that opam init finds a reasonable default value for jobs:)

**Comment by rjbou** [comment]
Thanks for reporting!
