### ISSUE TITLE
opam switch should use make -j

### ISSUE THREAD

**Issue by pmetzger** [ocaml/opam#3455]
When opam switch builds a new compiler, it should use `make -j N` where `N` is taken from the `jobs:` configuration parameter. This would dramatically speed up building compilers.

**Comment by pmetzger** [comment]
(Note it might be that opam 2.0 already does this; I'm still using opam 1.2. If so, please close this.)

**Comment by dra27** [comment]
This is an opam-repository issue, not an opam issue - opam should definitely not invoke `make -j` by default.

I can short-circuit your raising the issue on opam-repository, though - the compiler's build system is not stable enough to do `make -j` as a matter of course.

**Comment by pmetzger** [comment]
I thought that "opam switch" invocations were managed by opam itself, and not by opam-repository. Presumably that's wrong?

I've been told by a lot of people that invoking `make -j` for the compiler is stable. If that's not the case, then that should be fixed -- there are now even laptops with six cores and twelve threads, and single threaded builds are feeling very slow -- but of course that issue needs to be raised in the ocaml repo.

**Comment by dra27** [comment]
That is indeed wrong - in both 1.2.2 and 2.0, the commands executed for setting up switches are in the repository.

We test the parallel build, but I’m not convinced that that’s a good default to have without some kind of fallback on error. Out of curiosity, who/where is “lots of people”?

**Comment by pmetzger** [comment]
@gasche and others have told me it's find for doing clean builds (which is what opam does.) There was a discussion on discuss.ocaml.org, and some discussion on the discord chat channel as well. It certainly speeds up the build a great deal.

If it's buggy, it should be debugged, but this is probably not the right place to discuss that of course.

**Comment by gasche** [comment]
Parallel clean builds are tested in the CI and seem to have worked robustly in the last year or so on `trunk`, but I also agree with @dra27's incomfort at making that the default for unaware users, without another fallback strategy than "just run the command again". Given that installing a new switch is not a very frequent operation for users, it does seem sensible to wait until we move from "we know it's broken but it seems to work in practice" to "we trust it to work properly" to make this the default.

**Comment by pmetzger** [comment]
What would be needed to gain confidence beyond it working for a year in the CI system?

I rebuild switches often enough that I find it a bit irritating, but I understand the reluctance if it still isn't considered robust. That said, would there be any obvious way to make it optional so someone like me can just turn on parallel builds?

**Comment by pmetzger** [comment]
> Would you care to elaborate on what is your need for rebuilding switches?

Mostly hacking and trying out pre-releases. I'll also often do things like throwing away a switch I'm not using to save disk space and may want it back later. Since I'm not doing partial rebuilds with opam terribly often it's not really important to be able to do incremental rebuilds for me. Anyway, if there was an option for consenting adults, it wouldn't be too awful a thing. I'm not sure if there's an obvious way to get such behavior in opam though.

**Comment by dra27** [comment]
Various options:
 - It's easy enough to define your own opam-repository remote which includes the `-j`. You can either have a remote which just includes the `compilers` (OPAM 1.2.2) or the `ocaml-base-compiler` packages (opam 2.0.0) and so overrides the default repository or, given how infrequently old definitions change, you could safely have a branch which you rebase and just replace opam-repository with your own fork.
 - I have work in the pipeline for Windows opam which will allow feeding configuration parameters to packages during switch creation, but that's not going to land until at least opam 2.1
 - With opam 2.0, you can set-up multiple system compilers with different versions/configurations and trick opam 2.0 into using different system compilers - so you can create (local) switches without having to rebuild the compiler each time. @avsm has been doing this for some time, I think. Longer term, I have in mind that opam would become more like rustup in this regard - so compilers would always be shared. Equally, there's various people working towards binary artefact sharing, period.
 - The existing compiler packages could be changed to start off using `-j` with a `make distclean` followed by non-parallel make if anything goes wrong.

**Comment by pmetzger** [comment]
> The existing compiler packages could be changed to start off using `-j` with a `make distclean` followed by non-parallel make if anything goes wrong.

This seems like a good option.

> I have work in the pipeline for Windows opam which will allow feeding configuration parameters to packages during switch creation, but that's not going to land until at least opam 2.1

This isn't too bad either, though I suppose 2.1 is a while off.

**Comment by dra27** [comment]
> > The existing compiler packages could be changed to start off using -j with a make distclean followed by non-parallel make if anything goes wrong.

> This seems like a good option.

Sure, but it does need to be contributed (and tested!)

> This isn't too bad either, though I suppose 2.1 is a while off.

It's hoped that the gap between opam 2.0.0 and opam 2.1.0 will be considerably less than the gap between 1.2.2 and 2.0.0 🙂

**Comment by pmetzger** [comment]
So it would seem that, provided we make sure `-j` is only used for clean builds, it should be reasonably safe?

**Comment by yomimono** [comment]
I became interested in this recently after observing how slow installing the first OCaml compiler via `opam` is for a new user.  I also frequently make new switches, but I'm trained to go off for a cup of coffee after starting a new switch build, and so hadn't noticed how much time this takes.

Has there been any further consensus around whether this is "safe enough" by default?

**Comment by avsm** [comment]
I'm sadly not happy with trusting undefined behaviour in `make` to do the right thing in the face of non-determinism to make this change in opam-repo with the current Makefiles.

However, there are `dune` files in 4.08.0 which I haven't played around with, but that could be one way to get a fast and reliable parallel build of the relevant compiler binaries.  That is, at least, something we can debug and get precisely right _vs_ the behaviour of different make implementations when faced with unclear data dependency choices.

**Comment by pmetzger** [comment]
@avsm That still implies needing an initial ocaml build to get the initial dune build to get the initial ocaml build. Make is needed for bootstrap of the compiler for your switch, isn't it?

**Comment by avsm** [comment]
That could be worked around by various mechanisms such as detecting a dune bootstrap binary elsewhere in the system. The first necessary step is to validate the state of `dune build` for getting a usable compiler in the 4.08 betas.

**Comment by gasche** [comment]
I don't think `dune build` in the compiler is usable yet (I suspect it doesn't even build `world.opt`), it's only for dev-purposes. There would be a problem with sending users to a different build system than the developers use. If we want to do something, I would rather use `make -j`, with maybe some fallback logic to clean and restart sequentially for more robustness.

**Comment by kit-ty-kate** [comment]
Closing as this is an old issue regarding opam-repository, not opam itself and it was fixed in https://github.com/ocaml/opam-repository/pull/14257 some years ago anyway.
