### ISSUE TITLE
Certificate on https://opam.ocaml.org/ expired

### ISSUE THREAD

**Issue by adamiak** [ocaml/opam#3458]
Due to expired certificate on https://opam.ocaml.org/ it's not possible to do opam init, as the step that downloads index.tar.gz fails with:

curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt

Browsers also don't want to navigate to https://opam.ocaml.org/ and display Certificate issue warning.

**Comment by rjbou** [comment]
I close this one as it is duplicated of #3457 & https://github.com/ocaml/opam-repository/issues/12359.
Thanks for reporting.
