### ISSUE TITLE
Adding dune-project breaks installing packages

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocaml/opam#3471]
I was confused because after the migration from `jbuilder` to `dune` OPAM 2 (2.0~rc3) stopped being able to install `msgpck`. It can install all other projects except for `msgpck`. Also if I go back to a revision before I added `dune` files, I can install `msgpck` just fine.

Here's a reproducing repo:

https://github.com/Leonidas-from-XIV/dune-break-opam2

```[ERROR] The compilation of msgpck failed at "/Users/Leonidas-from-XIV/.opam/opam-init/hooks/sandbox.sh build jbuilder build -j 4 @install".

#=== ERROR while compiling msgpck.1.4 =========================================#
# context     2.0.0~rc3 | macos/x86_64 | ocaml-base-compiler.4.06.1 | https://opam.ocaml.org/2.0#a613fa1b
# path        ~/dune-break-opam2/_opam/.opam-switch/build/msgpck.1.4
# command     ~/.opam/opam-init/hooks/sandbox.sh build jbuilder build -j 4 @install
# exit-code   1
# env-file    ~/.opam/log/msgpck-67716-9a3a3f.env
# output-file ~/.opam/log/msgpck-67716-9a3a3f.out
### output ###
# Error: exception Sys_error("_build/log: Operation not permitted")
# Backtrace:
# Raised by primitive operation at file "pervasives.ml", line 315, characters 29-55
# Called from file "src/log.ml", line 16, characters 11-59
# Called from file "bin/main.ml" (inlined), line 101, characters 4-48
# Called from file "bin/main.ml", line 792, characters 14-31
# Called from file "vendor/cmdliner/src/cmdliner_term.ml", line 27, characters 19-24
# Called from file "vendor/cmdliner/src/cmdliner.ml", line 106, characters 32-39
# Called from file "vendor/cmdliner/src/cmdliner.ml", line 136, characters 18-36
# Called from file "vendor/cmdliner/src/cmdliner.ml", line 251, characters 22-48
# Called from file "bin/main.ml", line 1647, characters 10-51
```

(it does not depend on `jbuilder` vs `dune`, because in both cases it is `dune` 1.0.0)

Ok, now remove `dune-project`, and run `opam reinstall msgpck` and it works. I am at a complete loss why the addition of a `dune-project` breaks installation of unrelated projects.

```
# opam config report
# opam-version      2.0.0~rc3
# self-upgrade      no
# system            arch=x86_64 os=macos os-distribution=homebrew os-version=10.13.6
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              4
# repositories      1 (http), 2 (version-controlled) (default repo at a613fa1b)
# pinned            1 (git)
# current-switch    /Users/Leonidas-from-XIV/dune-break-opam2
```

**Comment by rjbou** [comment]
It seems that dune looks for a dune-project in parents folder. I have a different error shown:
```
$ opam install msgpck
+ .opam/opam-init/hooks/sandbox.sh "build" "jbuilder" "build" "-j" "7" "@install" (CWD=/tmp/dune-break-opam2/_opam/.opam-switch/build/msgpck.1.4)
[...]
#=== ERROR while compiling msgpck.1.4 =========================================#
# context     2.0.0~rc3 | linux/x86_64 | ocaml-base-compiler.4.06.1 | git+file:///home/rjbou/ocamlpro/opam-repository
# path        /tmp/dune-break-opam2/_opam/.opam-switch/build/msgpck.1.4
# command     ~/.opam/opam-init/hooks/sandbox.sh build jbuilder build -j 7 @install
# exit-code   1
# env-file    ~/.opam/log/msgpck-5193-05296d.env
# output-file ~/.opam/log/msgpck-5193-05296d.out
### output ###
# Entering directory '/tmp/dune-break-opam2'
# From the command line:
# Error: Don't know about directory _opam/.opam-switch/build/msgpck.1.4!
```
This is not a sandbox permission problem, as here `/tmp` is read-only in the sandbox script (same error raised). Besides, as shown in the log, dune enters in the project directory `/tmp/dune-break-opam2`, not the `build` one.
It reminds me this issue https://github.com/ocaml/dune/issues/954. ping @diml?
```
$ cd /tmp/dune-break-opam2/_opam/.opam-switch/build/msgpck.1.4
$ "jbuilder" "build" "-j" "7" "@install"
Entering directory '/tmp/dune-break-opam2'
From the command line:
Error: Don't know about directory _opam/.opam-switch/build/msgpck.1.4!
$ rm ../../../../dune-project 
$ "jbuilder" "build" "-j" "7" "@install" #everyhting is ok here
```

**Comment by Leonidas-from-XIV** [comment]
I've added `Printf.eprintf "CWD=%s\n%!" (Sys.getcwd ());` to dune 1.0.0 in `src/log.ml` right before line 16, and it displays `CWD=/Users/Leonidas-from-XIV/dune-break-opam2` when I have a `dune-project` which is wrong and the sandbox rightfully prevents it to write there.

**Comment by rjbou** [comment]
Yes, for build stage, only the build directory (`_opam/.opam-switch/build/msgpck.1.4` in my logs) have [rw](https://github.com/ocaml/opam/blob/master/src/state/shellscripts/bwrap.sh#L49) rights, others [ro](https://github.com/ocaml/opam/blob/master/src/state/shellscripts/bwrap.sh#L26) only.

Maybe there is some configuration for jbuilder in order to not rollback in its `dune-project` file looking?

**Comment by Leonidas-from-XIV** [comment]
I think the issue is that `jbuilder` used to have some detection of project root that was simplified in `dune` due to the introduction of mandatory `dune-project` files, but it broke the behaviour of existing `jbuilder` projects which don't have `dune-project` roots so `dune` thinks my top level `dune-project` is the right place to build dependency artifacts.
