### ISSUE TITLE
make cold fails for 2.0.0-rc4 on macOS with system sed

### ISSUE THREAD

**Issue by ilovezfs** [ocaml/opam#3480]
```
==> make cold CONFIGURE_ARGS=--prefix /usr/local/Cellar/opam/2.0.0 --mandir /usr/local/Cellar/opam/2.0.0/share/man
env MAKE=/Applications/Xcode.app/Contents/Developer/usr/bin/make ./shell/bootstrap-ocaml.sh 
Bad checksum for http://caml.inria.fr/pub/distrib/ocaml-4.06/ocaml-4.06.0.tar.gz.tar.gz:
- expected: 66e5439eb63dbb8b8224cba5d1b20947
- actual:   
make: *** [compiler] Error 2
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make cold CONFIGURE_ARGS=--prefix\ /usr/local/Cellar/opam/2.0.0\ --mandir\ /usr/local/Cellar/opam/2.0.0/share/man
```

**Comment by AltGr** [comment]
probably `md5sum` is not present? Maybe we should use something that is always there, or have a fallback?

**Comment by rjbou** [comment]
`md5sum` was changed to `openssl` for portability reason.
The actual md5 is get using `openssl md5 <file>`.

**Comment by ilovezfs** [comment]
```
ocaml-4.06.0.tar.gz.tar.gz
```
the .tar.gz.tar.gz looks bogus

**Comment by dra27** [comment]
I agree, that `.tar.gz.tar.gz` is surprising - it looks like the sed expression which defined `$V` has failed to trim it (see `echo ${URL}| sed -e 's/.*\/\([^\/]\+\)\.tar\.gz/\1/'`). Assuming openssl is installed, it means it's most likely that `openssl md5` returned an error which `cut` has then dropped.

**Comment by ilovezfs** [comment]
It's an incompatibility with BSD sed as there's no failure with gnu-sed.

**Comment by dra27** [comment]
Are you able to try changing the `\+` to a `*`? In fact, possible clearer would be `'s|.*/\([^/]*\)\.tar\.gz|1|'`

**Comment by ilovezfs** [comment]
I think you mean `'s|.*/\([^/]*\)\.tar\.gz|\1|'`?

**Comment by dra27** [comment]
Indeed - I edited it to add the missing backslash afterwards!

**Comment by ilovezfs** [comment]
Yes that works with both BSD sed and gnu-sed.

**Comment by dra27** [comment]
Is there an obvious reason why this hasn't been seen before - presumably most users have a system OCaml installed, which I think prevents homebrew from doing `make cold`?

**Comment by ilovezfs** [comment]
The issue doesn't affect 1.2.2, which is the current version in Homebrew. Also, `--without-opam` (the option that runs `make cold`) is non-default so someone would have to have run `--HEAD --without-opam` to hit this. Our analytics show no one using that combination.
