### ISSUE TITLE
Installing opam on OpenBSD 6.3

### ISSUE THREAD

**Issue by maroneze** [ocaml/opam#3483]
This is a report about installing opam on an OpenBSD 6.3, for future reference and in case there are easier ways to install it.

After installing the opam package for OpenBSD 6.3, I got the following error when trying `opam init`, related to an external solver failure (sorry about the screenshot, I could not easily copy-paste from my virtual machine):

![Error in OpenBSD](https://user-images.githubusercontent.com/3179395/43185008-e15cd050-8fea-11e8-896d-20f71c826259.png)

I then tried downloading and running `opam_installer.sh`, but it didn't find a 1.2.2 release for openbsd. I didn't check why it didn't try downloading opam 2.

Then, I manually downloaded [opam 2 rc4 for openbsd](https://github.com/ocaml/opam/releases/download/2.0.0-rc4/opam-2.0.0-rc4-amd64-openbsd) from the Releases page, but when running it I got:

```
ld.so: opam-2.0.0-rc4-amd64-openbsd: can't load library `libc.so.89.3`
```

I manually added a symlink from `/usr/lib/libc.so.89.3` to `/usr/lib/libc.so.92.3` (which was the file present in my system) and opam seemed to work fine with that.

I was then able to do `opam init`, which installed 4.07.0 by default, and when installing some other packages, I did have some OpenBSD-specific issues (e.g. with autoconf), but nothing specific to opam.

Overall, this was a much better experience than installing opam on NetBSD.
If things were supposed to be easier to install, some directions could be useful. Otherwise I'll close the issue, hoping it will still be indexed so others having the same error messages will find it.

**Comment by dra27** [comment]
I think you need to use `install.sh` rather than `opam_installer.sh` for opam 2 (@rjbou?)

Not sure why it's preferring an external solver - I thought that the internal solver is preferred (and presumably the binaries are built with one @AltGr?)

**Comment by rjbou** [comment]
> I think you need to use install.sh rather than opam_installer.sh for opam 2 (@rjbou?)

Indeed, for opam2, it is the [`install.sh` script](https://opam.ocaml.org/doc/2.0/Install.html#Binary-distribution), but the 1.2 documentation still points to the [`opam_installer.sh` script](https://opam.ocaml.org/doc/Install.html#Binary-distribution).

**Comment by maroneze** [comment]
@dra27 sorry for not being precise: `pkg_add opam` found a 1.2.2 opam with OCaml 4.03.0, which is I believe why it preferred the external solver. Version 2 did have the internal solver so it worked as expected.

Running `install.sh` as recommended by the webpage, I get this:

```
openbsd# sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
## Downloading opam 2.0.0~rc3 for openbsd on x86_64...
There may not yet be a binary release for your architecture or OS, sorry.
See https://github.com/ocaml/opam/releases/tag/2.0.0-rc3 for pre-compiled binaries,
or run 'make cold' from https://github.com/ocaml/opam/archive/2.0.0-rc3.tar.gz
to build from scratch
```

**Comment by rjbou** [comment]
Indeed, the script will get architecture information to construct the download url. As the openbsd release is named [`opam-2.0.0-rc4-amd64-openbsd`](https://github.com/ocaml/opam/releases/download/2.0.0-rc4/opam-2.0.0-rc4-amd64-openbsd) and it detect you have an `x86_64`architecture. There is a little inconsistency between release script (`x86_64` and `amd64`, depending of `uname -m` output) and the `install.sh` script, which ["merge" them](https://github.com/ocaml/opam/blob/master/shell/install.sh#L126).

This referenced PR fixes this for future releases (`x86_64` by default), but we still need to rename actual binaries. It should be available soon (ping @AltGr).

**Comment by madroach** [comment]
Its almost a year now. The latest opam can be installed from ports or packages. Can this issue be closed?

**Comment by maroneze** [comment]
Yes. I just tried installing it on the latest OpenBSD (6.5), and `pkg_add opam` worked fine.
