### ISSUE TITLE
opam failed to open

### ISSUE THREAD

**Issue by yasharsad** [ocaml/opam#3486]
Hi I am trying to install opam and get it to run. it constantly gives me an error message:
I am not able to install its packages either.

```
<opam: "open" failed on /home/bash/.opam/log/command-21591-5a61c5.out: Permission denied
>
```

**Comment by dbuenzli** [comment]
It looks like you have a permission problem on a directory somewhere on this path ` /home/bash/.opam/log/`

**Comment by yasharsad** [comment]
Thanks. I used chown to change the ownership to myself and it seems that it is working now. I will repost if it fails to work.
