### ISSUE TITLE
install.sh is hard to use for automated installs

### ISSUE THREAD

**Issue by brendanlong** [ocaml/opam#3500]
I'm in the process of switching our CI box over to opam 2.0, which took about an hour and the final version doesn't use the install script at all (we just download the latest binary and drop it in /usr/local/bin). There are a few things that could make this easier for other people in the future:

 - Accept the install dir as an argument instead of requiring user input. It *does* work to do `echo /usr/local/bin | install.sh`, but it's not ideal.
 - Have an option that doesn't install a switch by default (we can't use 4.07 right now because of Core, so building it just adds several minutes to my test cycle right now)
 - Make it possible to pass `--disable-sandboxing` through to `opam init` (or add a `--no-init` option). We do plan to turn on sandboxing, but right now bubblewrap isn't packaged for any distro we use.

**Comment by AltGr** [comment]
Indeed, the script is intended for end-users, and I don't believe it helps in any aspects for CI, compared to just downloading the archive: you don't need automatic selection of the binary, or backup of an old install, or automatic initialisation.

But we should certainly advertise it as such more clearly!
Note that you also have the option of using pre-built Docker images for various configurations from https://hub.docker.com/r/ocaml/opam2/

**Comment by brendanlong** [comment]
That makes sense. It wasn't very hard once I stopped trying to use the installer.

**Comment by 0cjs** [comment]
Recent events seem to have demonstrated that help for CI is needed to test this script itself. Yesterday's version update from 2.0.4 to 2.0.5 had a bug in the commit (fix in PR #3926), causing it to download the wrong version and display "Checksum mismatch."
