### ISSUE TITLE
Sandboxing / bubblewrap on Windows

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ocaml/opam#3505]
```
ec@Bei-Bei:/mnt/c/Users/ec$ opam config report
# opam config report
# opam-version      2.0.0
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=ubuntu os-version=16.04
[ERROR] No switch is currently set. Please use 'opam switch' to set or install a switch
# read-state        OpamStd.OpamSys.Exit(50)
```

I can't say I'm much of a Windows user; but I try and make sure my work is *accessible* to Windows users, so I have a Windows machine sitting next to my work Mac.

In particular, after setting up Windows Subsystem for Linux / Ubuntu-on-Windows, installing the latest opam 1.2, and then upgrading to opam 2.0 rc4 via `opam install opam-devel`, I find myself unable to install additional switches due to the requirement of `bwrap`:

```
ec@Bei-Bei:/mnt/c/Users/ec$ opam switch create ocaml-base-compiler.4.02.3

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ocaml-base-compiler.4.02.3] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
[ERROR] The compilation of ocaml-base-compiler failed at "/home/ec/.opam/opam-init/hooks/sandbox.sh build ./configure -prefix /home/ec/.opam/ocaml-base-compiler.4.02.3 -with-debug-runtime".

#=== ERROR while compiling ocaml-base-compiler.4.02.3 =========================#
# context     2.0.0 | linux/x86_64 |  | https://opam.ocaml.org/2.0#b203824b
# path        ~/.opam/ocaml-base-compiler.4.02.3/.opam-switch/build/ocaml-base-compiler.4.02.3
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./configure -prefix /home/ec/.opam/ocaml-base-compiler.4.02.3 -with-debug-runtime
# exit-code   10
# env-file    ~/.opam/log/ocaml-base-compiler-30926-58c514.env
# output-file ~/.opam/log/ocaml-base-compiler-30926-58c514.out
### output ###
# The 'bwrap' command was not found. Install 'bubblewrap' on your system, or
# disable sandboxing in ~/.opam/config at your own risk.
# See https://github.com/projectatomic/bubblewrap for bwrap details.
# For 'bwrap' use in opam, see the FAQ:
#   https://opam.ocaml.org/doc/2.0/FAQ.html#Why-does-opam-require-bwrap



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ocaml-base-compiler 4.02.3
└─
┌─ The following changes have been performed (the rest was aborted)
│ ∗ install base-bigarray base
│ ∗ install base-threads  base
│ ∗ install base-unix     base
└─
```

I can work around this by wiping out `~/.opam/config`, I think, and using `opam init --disable-sandboxing`, but that's somewhat less than an ideal user-experience.

Some suggestions:

 - I hear there's a Windows-native build in the works - congratulations! In the meantime, a functional story for the various popular Windows configurations should still be established (people *do do* development on Windows / have functioning setups, whether through cygwin or whatnot, or the newer WSL). I suspect such a story may need to be maintained even once a Windows-specific native build is established. (Sigh, Windows support. hahaha)

 - `--disable-sandboxing` should probably be the default on Windows, unless there's an equivalent tool to Bubblewrap, which I doubt.

Thanks for y'all's time, maintainership is hard, but good, pure, and appreciated, work. `<3`

**Comment by dra27** [comment]
Thanks for the detail! It is possible to detect that a distribution is specifically running atop WSL, and we should use this to disable sandboxing automatically for the platform. That'll be a 2.0.1 change at this stage.

**Comment by ELLIOTTCABLE** [comment]
Given that WSL is still slightly beta (although less than previously!), I'd expect anybody using it to be pretty technically-competent, enough-so to handle this themselves. Wouldn't call this a critical fix, put it off as long as you need to!

Detecting it: [simple enough](https://stackoverflow.com/a/43618657/31897)!

**Comment by nekketsuuu** [comment]
Related: ocaml/opam-repository#12050

**Comment by danilaml** [comment]
Is there a list of https://github.com/Microsoft/WSL/ issues that this depends on?

**Comment by Akito13** [comment]
> detect that a distribution is specifically running atop WSL, and we should use this to disable sandboxing automatically for the platform

Is this still being worked on? I think it would be nice, as this issue, previously unkown to me, was the cause for entirely breaking my WSL, which forced me to reinstall it completely. Others should be saved from such an occurence.
