### ISSUE TITLE
Avoid unreleased versions of OCaml unless specified

### ISSUE THREAD

**Issue by jberdine** [ocaml/opam#3510]
With opam 2, it is probably not desirable for the solver to choose the latest (and likely unreleased) version of ocaml unless specifically asked to:
```
$ opam switch create --empty ./
$ opam install ocaml
The following actions will be performed:
  ∗ install base-bigarray  base
  ∗ install base-threads   base
  ∗ install ocaml-variants 4.08.0+trunk+fp+flambda [required by ocaml]
  ∗ install base-unix      base
  ∗ install ocaml          4.08.0
===== ∗ 5 =====
Do you want to continue? [Y/n]
```
It is unlikely that I want `4.08.0+trunk+fp+flambda` when just asking for `ocaml`. :-)

**Comment by gasche** [comment]
I just learned about this issue today (thanks to @rjbou) and I think it is a serious problem. We don't want to have opam2 users install unreleased versions of the compiler without noticing. The suggestion to move experimental compiler versions to a separate repository seems fine, has someone worked on it yet, is there a related PR or place to ping?

**Comment by samoht** [comment]
As far as I know, nobody has started to work on that. Any help to do that would be highly appreciated!

**Comment by avsm** [comment]
@gasche moving these to a new remote would be good. You may also want to look at the `ocaml-version` library -- my medium term plan is to try to autogenerate all the compiler variants from that library mechanically.  The same library is used to generate (e.g.) the Dockerfile test matrix, so it's useful to have it programmatically expressed rather than cut-and-pasted across releases.

**Comment by gasche** [comment]
My time to work on this is very limited. What about a by-need approach? I propose to send a PR to remove all unreleased OCaml packages from opam-repository, and then wait and see who needs these in opam and kindly ask them to create (and maintain!) a new remote.

**Comment by gasche** [comment]
(Limited before October. But I think this should be solved sooner than that, because it sounds like a usability disaster.)

**Comment by avsm** [comment]
That sounds good. I have also not done the mechanical port for similar reasons :)

**Comment by avsm** [comment]
Actually, we do build 4.08 snapshots in the Dockerfiles, so this will break that CI. Cutting and pasting those into another remote would let me continue to build them...

**Comment by gasche** [comment]
@avsm, did you just volunteer? :-)

**Comment by avsm** [comment]
I just noticed that https://github.com/ocaml/ocaml-pr-repository (where we moved the opam1 PRs to) script has stopped updating, so it seems like that feature isn't particularly popular among our users.  As far as I can tell to fix this PR we could:

- remove the 4.08 compiler directory only from the 2.0.0 branch on opam-repository
- add them to the ocaml-pr-repository, and update that one to be in opam 2.0 format and also add trunk compilers there.

Does this sound right ?

**Comment by avsm** [comment]
This is quite a high priority bug to fix in a point release: it also affects RC versions of OCaml, which makes them difficult to stage in the mainline repository.

**Comment by rjbou** [comment]
As described in https://github.com/ocaml/opam-repository/pull/13302#issuecomment-459128712, @avsm  set up a new repo https://github.com/ocaml/ocaml-beta-repository. to host beta ocaml compilers packages.

**Comment by kit-ty-kate** [comment]
I believe this was fixed by the introduction of the `avoid-version` flag in opam 2.1.0 (via https://github.com/ocaml/opam/pull/4281 and https://github.com/ocaml/opam/pull/4527). Closing. If I made a mistake feel free to ask to reopen.
