### ISSUE TITLE
opam2 and debian-stable (9.5 / stretch) and git issue

### ISSUE THREAD

**Issue by hannesm** [ocaml/opam#3523]
I installed debian stable and tried to install a package from a repository which included:
```
url {
  src: "git+https://github.com/hannesm/ocaml-otr.git#080c8a18160856abda395ab2558df465193c87ef"
}
```
opam2 is not able to synchronise this repository, from a verbose run, the following command fails with "cannot find remote reference":
```
git "fetch" "-q" "https://github.com/hannesm/ocaml-otr.git" "--update-shallow" "+080c8a18160856abda395ab2558df465193c87ef:refs/remotes/opam-ref-080c8a18160856abda395ab2558df465193c87ef"
```

The installed `git` version is `2.11.0-3+deb9u3`, which I suspect is too old for that?  The same opam file works fine on my FreeBSD with a git 2.18.0.

**Comment by hannesm** [comment]
sorry, I forgot to mention why I'd like to use this as above.  The reason is that while conex can sign releases (by signing the opam files which contain the checksum of the archives and the build instructions), a way to sign a git repository is by refering to the commit hash (which is SHA1, but better than nothing ;) since tags and branches are mutable.  I've prepared a demo repository for conex at https://github.com/hannesm/jackline-opam.git if you're interested (more docs coming soon) - which lead to this behaviour on a debian 9.5 virtual machine (which i now upgraded to sid).

**Comment by rjbou** [comment]
Indeed, it seems to be related to the git version (I have 2.11.1). If I refer to the branch by name, it is fetched, but If I use hash, the object is not found (if it is not on master) 
```bash
# sandboxing HEAD -> ko
$ usr/bin/git "fetch" "-q" "https://github.com/hannesm/ocb-stubblr.git" "--update-shallow" "+00a03bcf37a1e14169beeb28c7544620320785d1:refs/remotes/opam-ref-00a03bcf37a1e14169beeb28c7544620320785d1"
error: no such remote ref 00a03bcf37a1e14169beeb28c7544620320785d1
# sandboxing by name -> ok
$  /usr/bin/git "fetch" "-q" "https://github.com/hannesm/ocb-stubblr.git" "--update-shallow" "+sandboxing:refs/remotes/opam-ref-sandboxing" 
# master HEAD -> ok
$ /usr/bin/git "fetch" "-q" "https://github.com/hannesm/ocb-stubblr.git" "--update-shallow" "+739773c3dc78c27f4b8114cd53a3060c383bc293:refs/remotes/opam-ref-739773c3dc78c27f4b8114cd53a3060c383bc293"
```

**Comment by rjbou** [comment]
After looking further, git 2.14 removed the restriction to advertised refs for sha1 fetch (cf. [commit](https://github.com/git/git/commit/02c531eba2925d89856baca8dc6a9d1b31bc4d7f)).
As you don't want to rely on branch names, one of the solution that I found is to get a the moment the associated branch name, in order to be able to fetch the branch/commit it without fetching the whole repo
```bash
$ git ls-remote
From https://github.com/hannesm/ocb-stubblr.git
739773c3dc78c27f4b8114cd53a3060c383bc293	HEAD
e414e9521d832a0919212d2e3ba3c17cf1825c8a	refs/heads/fix
40a3b0b2e169166c237c39f8209d62c0586b64e1	refs/heads/gh-pages
739773c3dc78c27f4b8114cd53a3060c383bc293	refs/heads/master
00a03bcf37a1e14169beeb28c7544620320785d1	refs/heads/sandboxing
[...]
$ /usr/bin/git "fetch"  "https://github.com/hannesm/ocb-stubblr.git" "--update-shallow" "+refs/heads/sandboxing:refs/remotes/opam-ref-00a03bcf37a1e14169beeb28c7544620320785d1"
remote: Counting objects: 133, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 133 (delta 0), reused 3 (delta 0), pack-reused 130
Receiving objects: 100% (133/133), 35.24 KiB | 0 bytes/s, done.
Resolving deltas: 100% (67/67), done.
From https://github.com/hannesm/ocb-stubblr
 * [new branch]      sandboxing -> opam-ref-00a03bcf37a1e14169beeb28c7544620320785d1
 * [new tag]         v0.0.1     -> v0.0.1
 * [new tag]         v0.0.2     -> v0.0.2
```

It can be set as a fallback mechanism if the others commands fail (tested locally).

I'm not completely convinced, as a command output is "grepped" to compose the next one, but for the moment I don't see another way to do it without fetching all the repo.

**Comment by avsm** [comment]
This seems like a great excuse to experiment with integrating [mirage/ocaml-git](https://github.com/mirage/ocaml-git) to get a portable implementation inline in opam ;-)

**Comment by rjbou** [comment]
@hannesm 
> Your proposal, to specify the branch -- any idea how to encode the branch name in the url in an opam file? or would you do the grep for the branch of git ls-remote in opam? would this work only for the tip of the branch?

Yes, it was by grepping the output of `ls-remote` and using it to construct the refspec. It is equivalent to 
```bash
branch=`git ls-remote  | grep ${commit_sha1} | cut -f 2 -d ' '`
git fetch ${remote_url} --update-shallow $branch:refs/remotes/opam-ref-${commit_sha1}
```

This works only for the tip of the branch, not other commits. 

The other option is to fetch the whole repo to be able to retrieve any commit by its sha1. I tend to this solution, as it is used only as a fallback, so it isn't the common case (ftm) that whole repo is fetched (2 conditions: commit by sha1 and git < 2.14).
You can test on this [branch](https://github.com/rjbou/opam/tree/git-sha1-fetch).

@avsm is `ocaml-git` stable enough? as I see on the readme, push is still experimental

**Comment by RalfJung** [comment]
I ran into the same problem. Currently, on Debian stable, upgrading opam 1 to opam 2 is a functional regression.

**Comment by rjbou** [comment]
Thanks for reporting!
