### ISSUE TITLE
Opam init fails on windows subsystem for linux

### ISSUE THREAD

**Issue by slothdude** [ocaml/opam#3527]
Hi, I am trying to use OPAM to run OCaml on windows 10 using the windows subsystem for linux. When I try to run `opam init -v --debug`, I get this:

```
00:00.038  CLIENT                  INIT default(0 http https://opam.ocaml.org)
OPAM has already been initialized.00:00.042  STATE                   LOAD-STATE(init)
00:00.112  SYSTEM                  error: File /home/Marc/.opam/repo/default/config does not exist
'opam init -v --debug' failed.
# opam-version    1.2.2
# os              linux
File /home/Marc/.opam/repo/default/config does not exist
```

When I run `opam config report`, I get this:

```
opam config report
# OPAM config report
# opam-version    1.2.2
# self-upgrade    no
# os              linux
# read-state      # opam-version    1.2.2
# os              linux
File /home/Marc/.opam/repo/default/config does not exist
```

I was just following the instructions from https://www.cs.umd.edu/class/spring2018/cmsc330/ocamlInstallationGuide.pdf but this is after I tried installing opam via `wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin` and when that failed, I tried deleting the opam directory and trying again. Any ideas on what I should try?

**Comment by dra27** [comment]
Try `rm -rf /home/Marc/.opam` and redo `opam init`?

**Comment by slothdude** [comment]
```
Marc@DESKTOP-J2UO6JE:~$ rm -rf /home/Marc/.opam
Marc@DESKTOP-J2UO6JE:~$ opam init
Checking for available remotes: rsync and local, git.
  - you won't be able to use mercurial repositories unless you install the hg command on your system.
  - you won't be able to use darcs repositories unless you install the darcs command on your system.

[WARNING] Recommended external solver aspcud not found.

=-=- Fetching repository information =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Processing: [default: http]
```

And at this point, it hanged, but I interrupted then tried the commands again and it worked. Thanks!

**Comment by abhi18av** [comment]
The solution is also mentioned here 
https://github.com/ocaml/opam/issues/3602
