### ISSUE TITLE
opam2 -  bwrap - hook/sandbox.sh does not allow to mount exotic path

### ISSUE THREAD

**Issue by ErwanGa** [ocaml/opam#3534]
Hi
I'm using opam in my build system.
I'm currently switching on opam2 and I'm currently facing an issue while creating a new switch.

It stops at ocaml-variants build 
```
# Configuring OCaml version 4.06.1
# Configuring for host x86_64-unknown-linux-gnu ...
# Configuring for target x86_64-unknown-linux-gnu ...
# Using compiler /work/CG-2.1/_build/vm-current/host/bin/x86_64-linux-gcc.
# ./configure: 1: ./configure: /work/CG-2.1/_build/vm-current/host/bin/x86_64-linux-gcc: not found
# Compiler family and version: .
# [ERROR!] Unable to compile the test program.
#  Make sure the C compiler /work/CG-2.1/_build/vm-current/host/bin/x86_64-linux-gcc is properly installed.

[ERROR] The compilation of ocaml-variants failed at "/work/CG-2.1/_build/_opam/opam-init/hooks/sandbox.sh build
        ./configure -prefix /work/CG-2.1/_build/_opam/vm-guichet -cc
        /work/CG-2.1/_build/vm-current/host/bin/x86_64-linux-gcc -as
        /work/CG-2.1/_build/vm-current/host/bin/x86_64-linux-as -aspp
        /work/CG-2.1/_build/vm-current/host/bin/x86_64-linux-gcc -c -partialld
        /work/CG-2.1/_build/vm-current/host/bin/x86_64-linux-ld -r -no-curses -fPIC".
```
The _opam/opam-init/hooks/sandbox.sh file seems not able to mount an exotic path for gcc compilers

``` 
 build)
        add_mounts ro "$OPAM_SWITCH_PREFIX"
        add_mounts rw "$PWD"
        add_ccache_mount
        ;;
``` 
is enough  not as my $PWD is something like /work/CG-2.1/buildsystem/ and does not contains /work/CG-2.1/_build/

I've updated mine as following (and adapt my build system with the required new variable)
``` 
 build)
        add_mounts ro "$OPAM_SWITCH_PREFIX"
        add_mounts rw "$PWD"
        if  [ -n "${OPAM_USER_PATH_RO-}" ]; then
           add_mounts ro "$OPAM_USER_PATH_RO"
        fi
        if  [ -n "${OPAM_USER_PATH_RW-}" ]; then
           add_mounts rw "$OPAM_USER_PATH_RW"
        fi
        add_ccache_mount
        ;;
    install)
        add_mounts rw "$OPAM_SWITCH_PREFIX"
        add_mounts ro "$OPAM_SWITCH_PREFIX/.opam-switch"
        add_mounts rw "$PWD"
        if  [ -n "${OPAM_USER_PATH_RO-}" ]; then
           add_mounts ro "$OPAM_USER_PATH_RO"
        fi
        if  [ -n "${OPAM_USER_PATH_RW-}" ]; then
           add_mounts rw "$OPAM_USER_PATH_RW"
        fi
        ;;

``` 
Is it possible to have such update in a future release?

Regards,
Erwan

**Comment by rjbou** [comment]
Thanks for the report & proposal!

It is useful for unusual install to add those variables, it avoids user to change the sandboxing script. The inconvenience is that it can add a failure point, as packages can set environment variable on their opam file, making these variables used while not set by the user. And as the sandboxing is here to avoid packages to access whole user filesystem...

A good compromise would be to just add `OPAM_USER_PATH_RO`, like that if needed programs are installed in unusual path, it is possible to reach them without permitting a full access.

Would you like to do a PR with those changes?

**Comment by ErwanGa** [comment]
I agree for the inconvenience of $OPAM_USER_PATH_RW but my opam root is not in $PWD (/work/CG-2.1/buildsystem) and but somewhere in /work/CG-2.1/_build/. I need that  /work/CG-2.1/_build/_opam  (my opam root) becomes writable.

**Comment by ErwanGa** [comment]
PR done
