### ISSUE TITLE
Two repositories that list a package by the same name

### ISSUE THREAD

**Issue by Janno** [ocaml/opam#3539]
I am not sure if this is a bug, but I was very surprised today when I found out that opam (2.0.0) silently chooses one out of two packages by the same name provided by two repositories. In this case, the repository which was added first won but I haven't made more tests to see if this behavior is consistent.

I would love to get a warning when this happens. A way of listing all sources for an ambiguous package would also be very helpful.

**Comment by AltGr** [comment]
Replacing packages in custom repositories is a common practice. See the `--rank` option, and the `priority` and `set-repos` sub-commands of `opam repository`.
Opam will choose the best version available, and if available from multiple repositories, select the repository with the lowest rank.

**Comment by Janno** [comment]
Thanks for the reply. It seems that most of my confusion comes from a different issue (potentially a bug). My current understanding is that `opam show` indeed shows *all* available versions and not just those from the highest-ranked repository. If that is correct then there is no problem here. Thanks again!
