### ISSUE TITLE
how do I build without needing to fetch dependencies?

### ISSUE THREAD

**Issue by pmetzger** [ocaml/opam#3549]
Howdy! I'm updating the MacPorts `opam` package to 2.0.0, and I read the following in the `README.md`:

> Run `make lib-ext` as advertised by `./configure` if you don't have the dependencies installed. This will locally take care of all OCaml dependencies for you (downloading them, unless you used the inclusive archive we provide for each release).

What is the name of the inclusive archive? I thought it was `opam-full-2.0.0.tar.gz`, but when I run `make lib-ext` over that, it appears to still fetch the dependencies. For better or worse, I need to rig this up so it will build standalone.

(It might be nice if the documentation explained this part a bit more.)

**Comment by rjbou** [comment]
This is the archive you need. When you run the `make lib-ext`, it prints all instructions, including curl ones that are here as fallback. As the opam archive contains all its needed libraries archives, it effectively downloads nothing, just moves sources at the right place.
Isn't that behaviour you have?

**Comment by dra27** [comment]
@pmetzger - are you sure it's actually invoking a download command? The commands to prepare the archives are long sequences which begin with an attempt to copy the file from the local cache in `src_ext/archives`.

The full archive is prepared using `make -C src_ext cache-archives` which downloads all the required lib-ext archives to `src_ext/archives`. You can verify that no downloading is taking place by editing `Makefile.config` after running configure and changing `FETCH` to `false`.

**Comment by pmetzger** [comment]
@rjbou:
> When you run the make lib-ext, it prints all instructions, including curl ones that are here as fallback.

Ah! Perhaps that was confusing me. 

@dra27
> You can verify that no downloading is taking place by editing Makefile.config after running configure and changing FETCH to false.

I think I'll try that just to make sure, but I bet the bug is entirely with my understanding of what is going on. :)

**Comment by pmetzger** [comment]
BTW, it would still be nice to have some text explaining this in the README.md (including naming the archive and explaining how it works...)

**Comment by pmetzger** [comment]
So I changed FETCH to /usr/bin/false and now the build fails. This makes me wonder if something peculiar is happening. I'll debug more.

**Comment by pmetzger** [comment]
Okay, so `src_ext/archives` doesn't seem to exist when I unpack `opam-full-2.0.0.tar.gz`.

**Comment by rjbou** [comment]
What is you download url? I have an error 404 with this one ` https://github.com/ocaml/opam/releases/download/2.0.0/opam-full-2.0.tar.gz`

**Comment by pmetzger** [comment]
It was my fault. MacPorts by default fetches using the GitHub API based on a tag. Github then synthesized that for me. I set the flag to fetch the released file instead, set the version to 2.0.0 instead of 2.0, and everything worked correctly. All problems on my end.
