### ISSUE TITLE
FreeBSD port of 2.0.0

### ISSUE THREAD

**Issue by hannesm** [ocaml/opam#3550]
I just submitted a pull request to the FreeBSD ports tree at https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=231477 to upgrade to opam 2.0.0. /cc @jorisgio would be great if you can approve the update and maintainer change if you can recover your bugs.freebsd.org credentials. /cc @rjbou

**Comment by jorisgio** [comment]
tried here : https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=231531 and also put a + sign on your bug whatever it means.

**Comment by hannesm** [comment]
@jorisgio thanks! :)

**Comment by hannesm** [comment]
got merged into FreeBSD ports tree (https://svnweb.freebsd.org/ports?view=revision&revision=480326), installation instructions (from https://opam.ocaml.org/doc/Install.html#FreeBSD) now apply again (the ocaml-opam port will install opam2 :D)
