### ISSUE TITLE
configure for 2.0.0 does not allow FETCH=no

### ISSUE THREAD

**Issue by pmetzger** [ocaml/opam#3551]
I'm constructing the `Portfile` for the MacPorts opam package.

As we don't want to actually fetch any dependencies, I'm using the version of the distfile that contains all dependencies in it already. However, if "curl" or "wget" isn't available, configure fails. As I don't actually _want_ to fetch anything, having to depend on one of those two is suboptimal.

I can set `FETCH` in the environment to `no`, which prevents this, but then a test in the configure script complains that either curl or wget must be available.

For now I'm patching this out and the build proceeds just fine, but it would be nice to have an official configure flag that says "don't depend on a fetch program, I'm using the cached version of the dependencies".

**Comment by rjbou** [comment]
You can disable checks in the configure with `--disable-checks` and then `make lib-ext`, it works even without having curl or wget installed, taking present archives.

**Comment by pmetzger** [comment]
When I tried that it seemed to no longer want to build the internal solver? I can try checking if that is the case a second time though to confirm it.

**Comment by lindig** [comment]
```

**Comment by hannesm** [comment]
opam2.0 port on FreeBSD passes `--disable-checks` as well (to avoid `curl` or `wget` compile-time dependency). in build logs, [here](https://builds.ixsystems.com/poseidon/data/trident-master-current/latest-per-pkg/ocaml-opam-2.0.0.log) or [here](http://198.167.222.206:8080/data/latest-per-pkg/ocaml-opam/2.0.0/builder-default.log) you see the line `Opam will be built WITHOUT a built-in solver`, but later mccs is at least compiled.

How do I check whether the opam binary actually embeds and uses `mccs`?

**Comment by pmetzger** [comment]
Regardless, I'd rather not perpetuate the hack I used for MacPorts. It's working but it's the wrong thing.

**Comment by lindig** [comment]
```
:opam $ env FETCH=no ./configure
checking for ocamlc... ocamlc
OCaml version is 4.07.0
...
configure: error: You must have either curl or wget installed.
```

This looks like a real bug because we explicitly request not to fetch anything.

**Comment by dra27** [comment]
@lindig - no, that test is correct. You should be passing `--disable-checks` to configure, not trying to override an internal variable.

@hannesm - this is a bug (and sadly, I think, one of mine!). I'm not certain why it's then building mccs anyway, but you can see part of the problem in that there's no detection in the output of configure for a C++ compiler!

**Comment by dra27** [comment]
@pmetzger - which hack are you referring to?

**Comment by pmetzger** [comment]
see: https://github.com/macports/macports-ports/blob/master/sysutils/opam/files/patch-stop-fetch-check.diff

**Comment by pmetzger** [comment]
(That's a patchfile MacPorts applies before building. There's also one other gross hack I have to apply, I do the more equivalent of running sed on opam-installer.install after it gets created, but I have a separate issue open for that problem, https://github.com/ocaml/opam/issues/3552 )

**Comment by hannesm** [comment]
@dra27 this may be a bug, but AFAICT passing `--disable-checks` works for my use case: avoid a build-time dependency on curl/wget; compile and link mccs.  a fix for configure should IMHO support this (there's a `--without-mccs` configuration parameter, but I can't find a `--with-mccs` (and am confused about the whole mccs configuration right now: it may come from an external packages?! or from the tarball shipped with opam-full!? and there can be an opam2 binary which does not use mccs at all!?).

**Comment by pmetzger** [comment]
Regardless, as a package maintainer I want to be able to specify that the build process must not depend on curl or wget, must never fetch, and must build the internal solver. I'd suggest an explicit `--disable-fetch` for fetching which impacts fetching _and nothing else_ (it shouldn't touch whether the internal solver is used!) is a good thing. An explicit `--with` or `--enable` for the internal solver is probably also a good thing.

**Comment by dra27** [comment]
@pmetzger - why are you using that patch, rather than `--disable-checks`?

@hannesm - the bug is that it's saying that it won't build with MCCS and then builds with it anyway but the fix is that it should be saying that it will build MCCS and then build it (you clearly have a C++ compiler). The bug is actually in the error message - MCCS is being enabled (it's the default - there is `--with-mccs` for being explicit about that, which the opam CI uses). The bug comes about because the test for that message assumes that the package tests will have been run. I'll do a patch later, but the important thing is that what you're doing at the moment will definitely do what you want (as long as you have a C++ compiler installed) and will continue to do you want even after I patch it!

**Comment by dra27** [comment]
You can tell if the opam you're looking at has a built-in solver from `opam config report` which should include `# solver            builtin-mccs+glpk`

**Comment by pmetzger** [comment]
> @pmetzger - why are you using that patch, rather than --disable-checks?

Because --disable-checks tells me it disables the internal solver or at least says it does. Read my posts above. I explained it. And I don't _want_ everything --disable-checks does, I just want to disable fetch, and this is the minimal change that does only that.
