### ISSUE TITLE
"opam config env" hangs if .opam/lock exists

### ISSUE THREAD

**Issue by pmetzger** [ocaml/opam#3553]
`eval $(opam config env)` is run typically in one's shell init file. However, if `.opam/lock` exists, the command hangs. This is a serious problem, as if one's shell hangs during initialization, fixing a stale lockfile gets much more entertaining.

**Comment by rjbou** [comment]
Which version of opam do you use?
`opam config env` and `opam env` don't take a lock, just load the global state, the presence of the `.opam/lock` file shouldn't cause trouble:
```bash
$ opam install coq
The following actions will be performed:
  ∗ install camlp5 7.06  [required by coq]
  ∗ install coq    8.8.1
===== ∗ 2 =====
Do you want to continue? [Y/n] 
[1]+  Stopped                 opam install coq
$ ls /tmp/.opam/lock
/tmp/.opam/lock
$ opam config env 
OPAM_SWITCH_PREFIX='/tmp/.opam/sw'; export OPAM_SWITCH_PREFIX;
CAML_LD_LIBRARY_PATH='/tmp/.opam/sw/lib/stublibs:/tmp/.opam/sw/lib/ocaml/stublibs:/tmp/.opam/sw/lib/ocaml'; export CAML_LD_LIBRARY_PATH;
OCAML_TOPLEVEL_PATH='/tmp/.opam/sw/lib/toplevel'; export OCAML_TOPLEVEL_PATH;
MANPATH=':/tmp/.opam/sw/man'; export MANPATH;
PATH='/tmp/.opam/sw/bin:/tmp/ocp_usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games'; export PATH;
```

**Comment by pmetzger** [comment]
Odd. Now I can't reproduce it. Maybe this only was a problem during my initial conversion from 1.2.x to 2.0.x? Anyway, I'm closing as I can't make it happen now.

**Comment by AltGr** [comment]
the simple existence of the file doesn't block: it will only block if a live opam process is holding a lock to it (using `Unix.lockf`).
Furthermore, the lock for `opam env` can only happen if the `env` file for the current switch doesn't exist... maybe the switch was being initialised ?

**Comment by pmetzger** [comment]
So I'd just installed opam 2 into my path, and this was the first time an opam 2 command was executed. I couldn't find any other opam processes at all at the time. Once I removed the lock file, executing `opam config env` caused the upgrade process to trigger, so that might have been the issue.

**Comment by rjbou** [comment]
You were doing the switch to opam 2.0.0,  as you suspected, it is from that. Usually `opam config env` don't need the lock, but when opam2 trigger that its root is in a 1.2 format and need upgrade, it a top check, every command, opam invocation will do the upgrade, and need to lock.

**Comment by pmetzger** [comment]
I think it's a bit late now, but it should probably have been the case that `opam config env` didn't trigger the whole upgrade, because it's typically done in shell init files and could thus hang the thing that was needed to fix the thing causing the hang. At this point, though, with 2.0.0 already going into wide release, it might not be feasible any longer.

**Comment by pmetzger** [comment]
Apparently not.

BTW, should I be changing my configs to say `opam env` and not `opam config env` at this point?

**Comment by rjbou** [comment]
Yes, you are advised to change, `opam config env` is just a shortcut now for `opam env`.
