### ISSUE TITLE
upgrade guide has incorrect info now that release is out

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#3556]
From https://opam.ocaml.org/doc/Upgrade_guide.html
> Everything from 1.2 is converted to 2.0 when needed (on the fly by opam, automatically on the git repository, or manually using opam admin upgrade).
> When publishing packages, remember that:
> packages in 1.2 format must be published to master, and they will be available to everyone
> packages in 2.0 format must be published to the 2.0.0 branch — e.g. using the new opam-publish.2.0. They will only be available to opam 2.0 users.

This is now incorrect as the master branch is for 2.0

There is also no mention of `opam-package-upgrade` for repositories, which is a very helpful tool :)

**Comment by avsm** [comment]
while there, I noticed that the install guide at https://opam.ocaml.org/doc/Install.html

- still mentions the rc release
- recommends ocamlbrew, which i dont believe is maintained any more (@hcarty?)

**Comment by hcarty** [comment]
@avsm I'm not actively maintaining ocamlbrew. I'll happily update it if there is a need and accept PRs against it. But in general it's probably simpler for almost anyone to go directly to opam.

**Comment by hannesm** [comment]
I'm also wondering whether the "binary installation", e.g. on ubuntu `apt install opam` will result in a opam2 or opam1.  I suspect arch linux and maybe some others already have updated to 2.0, but some other OS may still be in opam1-land.  This should be clarified on that install page.

**Comment by rjbou** [comment]
Updated the upgrade doc, deleted the ocamlbrew part, and added an link to the distribution wiki page like that user can check if its distrib provides opam 1.2 or 2.0.
