### ISSUE TITLE
the opam debian package is not reproducible

### ISSUE THREAD

**Issue by hannesm** [ocaml/opam#3562]
someone brought to my attention that opam2, now in buster, is not entirely reproducible.  the very kind people from the reproducible builds project host a website containing their results: https://tests.reproducible-builds.org/debian/rb-pkg/buster/amd64/diffoscope-results/opam.html

what do we see there? the (optional) opam-docs package, which installs the doc/dev-manual (still at version 1.1.2 AFAICT), does contain - as common in latex - a timestamp of when the tex was translated to a pdf.

I think this can easily be avoided by using some waternarking (`%%VERSION%%`) in the tex - or unset `\date{}`. The timestamp of when latex was run is not very informative, it is much more interesting which opam release this document is targeting, or the git head!?

I haven't looked inside the dev-manual at all, but if it is specific for opam1, maybe it could be deleted or needs to be updated.

**Comment by h01ger** [comment]
thanks Hannes for reporting this.

If you want a timestamp in the manual, I suggest to use the last modification of the source code (and not the build time...), see https://reproducible-builds.org/specs/source-date-epoch/

**Comment by rjbou** [comment]
PR #3583 that remove dev manual merged.
Thanks for reporting!
