### ISSUE TITLE
AppVeyors fails in opamFormat

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam#3564]
OPAM fails on AppVeyor with [the message](https://ci.appveyor.com/project/kennknowles/ocaml-freetds/build/1.0.15#L390):
```
Fatal error:
File ".\src\format\opamFormat.ml", line 328, characters 9-15: Assertion failed
```

**Comment by dra27** [comment]
Which opam is that?

**Comment by Chris00** [comment]
The one of [ocaml-ci-scripts](https://github.com/ocaml/ocaml-ci-scripts).  The log does not give details but according to [appveyor-opam.sh](https://github.com/ocaml/ocaml-ci-scripts/blob/master/appveyor-opam.sh#L13), it is “https://github.com/fdopen/opam-repository-mingw/releases/download/0.0.0.1/opam64.tar.xz”.  Should they use a different URL?

**Comment by dra27** [comment]
It's a fork - but I'll have a look

**Comment by Chris00** [comment]
Thanks.  I guess they could use the stock opam 2 now, right?  (That's what I thought they did.)

**Comment by dra27** [comment]
No - stock opam 2.0 doesn’t get work for native Windows. It’s possinle that stock opam 2.0 as a Cygwin binary can be made to work with the mingw repo. 2.1 patches coming as soon as I get the chance to rebase them!
