### ISSUE TITLE
Provide a way to provide configure parameters for ocaml-base-compiler build

### ISSUE THREAD

**Issue by ptMuta** [ocaml/opam#3565]
We're currently facing an issue caused by opam when building `docker-machine-driver-xhyve` for macOS. The major changes in the latest major revision broke two parts of the build. One can be easily worked around by disabling the sandbox for the build, but as of current moment I cannot find a reasonable way to disable the graphics capabilities of the compiler [which are not compatible with macOS by default](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/30974/version=mojave_testing/testReport/junit/brew-test-bot/mojave/install_docker_machine_driver_xhyve/).

As I've only scratched the usage of opam while debugging this issue to save time and sanity I now ask, is there an undocumented way to do this and if not, would it be possible to establish a way to manually provide configure flags for the packages?

**Comment by dra27** [comment]
There's something strange going on here - the graphics library is compatible with macOS. What's strange is that `configure` is clearly enabling graph but then it's not working later on.

The workaround at the moment would be to patch the ocaml-base-compiler description to pass `-no-graph`. Less hackily would be to have a remote which does this by default. But I think this is hiding something else which is not working.

**Comment by ptMuta** [comment]
Any suggestions on what would be the best approach to provide a workaround as an immediate solution? 

Currently this issue breaks atleast the aforementioned `docker-machine-driver-xhyve` on Homebrew which in turn makes [minishift](https://www.okd.io/) unusable on without manually compiling ocaml, opam and xhyve driver on macOS.

**Comment by hodrigohamalho** [comment]
Needing this fix 👍

**Comment by ptMuta** [comment]
@dra27 any other suggestions or should I go ahead and try to script the manual compilation of the compiler into the brew formula? I personally still think the best approach in the long run would be to provide a way to pass arguments to `configure` for all packages. This would provide a way to fine tune compilation while using opam without resorting to manual compilation.

**Comment by dra27** [comment]
@ptMuta - at this stage, I'd say your better off finding out why OCaml's `configure` script is detecting the X11 headers (and so enabling the graphics library) but then having the compilation failing later.

Passing `-no-graph` shouldn't be necessary here - if there's a bug in OCaml's configure script, the fix would be applied in opam-repository which would provide an easy fix for this issue... I can look at (full) build logs, but I don't have any equivalent systems to test it on.

**Comment by dra27** [comment]
Passing arbitrary flags to packages will hopefully be an opam 2.1 feature, but I would be amazed if it's back-ported to 2.0...

**Comment by ptMuta** [comment]
Right, I'll try to figure out a workaround revolving around patching the compiler for an immediate solution then. I'll dismantle it once opam 2.1 hits.

I can't reproduce this issue on my local machine either but fresh macOS installations seem to have this issue consistently.

Should this issue be kept open or should I close it?

**Comment by dra27** [comment]
Is this consistently failing on a mac CI system, though? With my OCaml dev team hat on, I'm very happy help walk through identifying what `configure` is regarding as OK (and how to get the logs out of opam in the first place).

This issue doesn't need to stay open to track the parameters feature, but it would be good to have an OCaml Mantis issue tracking the underlying problem if that's not going to be addressed directly.

**Comment by ptMuta** [comment]
It does consistently fail on the Homebrew CI. The jenkins cleaned up the linked logs so I'd have to trigger a new build to get the full stack though. I can take a few hours tonight to get a debug stack out of the CI for us, but I don't have access to the build artifacts. I s'pose I can setup a virtual Mojave for local env for replication 🤔

**Comment by Amar1729** [comment]
rip - we're having the same problem trying to bump a version of a different package (infer) in homebrew:  
https://github.com/Homebrew/homebrew-core/pull/39190

The previous way (`opam-1.2`) this formula dealt with `-no-graph` was to [replace a line in the corresponding `.comp` file for ocaml 4.06.1+flambda](https://github.com/Homebrew/homebrew-core/blob/b825200fd1944c4c66c3173dabb52b33149c49aa/Formula/infer.rb#L52), but trying that with the `opam` file under the (`opam-2.0`) `ocaml-variants.4.07.1+flambda` package doesn't work.  

The `configure` script still "finds" X11, but then fails later on during `make world` trying to include it.

**Comment by dra27** [comment]
Closing this, as I expect with the passage of time it's become less relevant (graphics was removed from OCaml in 4.09). If this is still an issue, it can probably be addressed in opam-repository.

Please feel to comment here/re-open if this is still an issue.
