### ISSUE TITLE
Missing switches when upgrading to OPAM 2.0.0

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/opam#3578]
I upgraded from 1.2 to 2.0 as per the instructions here:

https://opam.ocaml.org/blog/opam-2-0-0/

Now I see:

```
gorge:repos john$ opam switch
#  switch        compiler                             description
   3.11.2        ocaml-base-compiler.3.11.2
   4.01.0        ocaml-base-compiler.4.01.0
   4.02.0        ocaml-base-compiler.4.02.0
   4.02.3        ocaml-base-compiler.4.02.3
   4.03.0        ocaml-base-compiler.4.03.0
   4.04.0        ocaml-base-compiler.4.04.0
   4.04.2        ocaml-base-compiler.4.04.2
   4.05.0        ocaml-base-compiler.4.05.0
   4.05.0+trunk  ocaml-variants.4.05.0+trunk
   4.06.0        ocaml-base-compiler.4.06.0
   4.06.0+beta1  ocaml-variants.4.06.0+beta1
→  4.06.1        ocaml-base-compiler.4.06.1
          base-bigarray.base base-threads.base base-unix.base
          ocaml-base-compiler.4.06.1
   4.07.0+rc1    ocaml-variants.4.07.0+rc1
   system        ocaml-system.4.07.0+dev6-2018-04-10
```

But I cannot see 4.07, other than the rc1. I have tried "opam update" and "opam upgrade".

What have I done wrong?

```
# opam config report
# opam-version      2.0.0 
# self-upgrade      no
# system            arch=x86_64 os=macos os-distribution=homebrew os-version=10.13.6
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              4
# repositories      1 (http) (default repo at 309c6ca1)
# pinned            0
# current-switch    4.06.1
```

**Comment by rjbou** [comment]
Curuous, the upgrade from 1.2.2 to 2.0.0 keep all the switches.
Did you had any notification (error, warning,upgrade note) during the upgrade process?

I see that your switch named `system` is based on a `4.07.0` compiler, in a `dev6-2018-04-10` version. Is that the switch you're looking for?
Previously (opam1.2.2), did you pinned the package `ocaml-system` to a specific version?

Just to know, what procedure did you choose to perform the upgrade (`install.sh`, using opam, binary)?

Thanks for reporting!

**Comment by johnwhitington** [comment]
Thanks.

I used the `opam install opam-devel' route.

No errors or warnings so far as I remember.

I'm looking for the normal 4.07.0 release, not the system one. I have never pinned anything, so far as i know.

**Comment by rjbou** [comment]
Can you check in your `OPAMROOT` if an `4.07.0` folder exists (or the name you gave to the switch).

**Comment by johnwhitington** [comment]
```
gorge:.opam john$ ls
3.11.2		4.04.0		4.06.0+beta1	config		opam-init
4.01.0		4.04.2		4.06.1		config.lock	repo
4.02.0		4.05.0		4.07.0+rc1	download-cache	system
4.02.3		4.05.0+trunk	archives	lock
4.03.0		4.06.0		backup		log
'''

It appears not...

**Comment by rjbou** [comment]
Just to be sure, are you looking for an existing switch that you created using opam1.2.2, or for available compilers to install in a switch (`opam switch list-available`)?

**Comment by johnwhitington** [comment]
Thanks! Fixed now.

It used to be that `opam switch' would also list the available ones.

The output of `opam switch list-available' isn't very useful, because `ocaml-base-compiler 4.07.0' appears on line 435 of the output, when it's what most users will want.

Also, a beginning user wouldn't know how to append `ocaml-base-compiler' and `4.07.0' into `ocaml-base-compiler.4.07.0'.
