### ISSUE TITLE
opam v2. ubuntu packages

### ISSUE THREAD

**Issue by vzaliva** [ocaml/opam#3584]
The installation instruction page on OPAM website https://opam.ocaml.org/doc/Install.html states:

"Ubuntu has native packages for opam"

However, this package is for v1.2 only. Please provide an alternative Ubuntu package for v2.0.

**Comment by Richard-Degenne** [comment]
I suggest you install OPAM 2.0 using precompiled binaries for the time being. It can take time before Ubuntu's maintainers agree to release a new version for OPAM.

**Comment by dra27** [comment]
See [this thread](https://discuss.ocaml.org/t/opam-2-0-experimental-ppas/2446). opam 2 is already in [Debian sid](https://packages.debian.org/sid/opam), so I would hope it’ll make it to Ubuntu 19.04.
