### ISSUE TITLE
opam 2 switch doesn't work on opam 1.2.2 switches without `environment` file etc.

### ISSUE THREAD

**Issue by Blaisorblade** [ocaml/opam#3594]
After upgrading from opam 1.2.2 to opam 2, all old switches have no `.opam-switch/environment`, and the behavior of `opam env` is too random for me too describe (some info in #3593). I've only started making sense of this through https://github.com/ocaml/opam/issues/3573#issuecomment-426295990.

```
$ ls ~/.opam/*/.opam-switch/environment
/Users/pgiarrusso/.opam/coq-8.8.2/.opam-switch/environment
$ ls -ld ~/.opam/*/.opam-switch/
drwxr-xr-x 11 pgiarrusso staff 352 Oct  9 18:18 /Users/pgiarrusso/.opam/4.05.0/.opam-switch/
drwxr-xr-x 12 pgiarrusso staff 384 Oct  9 18:18 /Users/pgiarrusso/.opam/coq-8.8.0/.opam-switch/
drwxr-xr-x 12 pgiarrusso staff 384 Oct  9 18:18 /Users/pgiarrusso/.opam/coq-8.8.1-equations-1.0/.opam-switch/
drwxr-xr-x 12 pgiarrusso staff 384 Oct  9 21:19 /Users/pgiarrusso/.opam/coq-8.8.1/.opam-switch/
drwxr-xr-x 12 pgiarrusso staff 384 Oct  9 21:19 /Users/pgiarrusso/.opam/coq-8.8.2/.opam-switch/
```

also, the `.opam-switch/config/*` files have no useful config:

```
giarrusso@SilenceOfTheLambdas:~/git/Coq$ ls  /Users/pgiarrusso/.opam/coq-8.8.1/.opam-switch/config/
base-bigarray.config  base-threads.config  beluga.config  camlp5.config   coq-equations.config           coq-ott.config  cppo.config  extlib-compat.config  num.config                  ocamlbuild.config  ott.config
base-bytes.config     base-unix.config     camlp4.config  conf-m4.config  coq-mathcomp-ssreflect.config  coq.config      dune.config  jbuilder.config       ocaml-base-compiler.config  ocamlfind.config   ulex.config
pgiarrusso@SilenceOfTheLambdas:~/git/Coq$ cat  /Users/pgiarrusso/.opam/coq-8.8.1/.opam-switch/config/*
opam-version: "2.0.0"
variables {

}
```

>   If your issue concerns a package not building, please report to
>   https://github.com/ocaml/opam-repository/issues or to the package maintainer
>   unless you are confident it is an issue in the opam tool itself.

```bash
$ opam config report
# opam config report
# opam-version      2.0.0
# self-upgrade      no
# system            arch=x86_64 os=macos os-distribution=homebrew os-version=10.13.6
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              4
# repositories      2 (http), 1 (version-controlled) (default repo at 33424880)
# pinned            2 (version)
# current-switch    coq-8.8.2
```

**Comment by Blaisorblade** [comment]
FWIW: I understand #3573 suggests there was a bug in the past, but opam 1 worked; so either opam 2 should read the format that opam 1 used to find the needed info, or the upgrade instructions should warn that old switches might not work.

**Comment by rjbou** [comment]
I have a few question about the issue:
1. before using the shell hook was you used to eval the `opam env`?
2. did you tried to remove the environment file and reinstall a package on broken switches? It seems to have worked on switch `coq.8.8.2` as it is the only present
3. on this https://github.com/ocaml/opam/issues/3593#issuecomment-428315120, it was on the switch `coq.8.8.2` or another one? It contains only the switch variable, which is uncommon.
4.you seem not having an `ocaml.config` file. Can you check that the config variables are defined in the original opam file with `opam show ocaml -f setenv:` (cf. https://github.com/ocaml/opam/issues/3573#issuecomment-426295990)

**Comment by Blaisorblade** [comment]
> 1. before using the shell hook was you used to eval the opam env?
Can't parse that, but I used `eval $(opam env)`, and my `.profile` contains this line — in fact, twice! (just removed one copy):

```
. /Users/pgiarrusso/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true
```

> 3. on this #3593 (comment), it was on the switch coq.8.8.2 or another one? It contains only the switch variable, which is uncommon.

That's the "old switch", meaning coq.8.8.1, and has no environment file.

> 4.you seem not having an ocaml.config file. Can you check that the config variables are defined in the original opam file with opam show ocaml -f setenv: (cf. #3573 (comment))

That has the same result in both switches, coq-8.8.2 (new and working) and coq-8.8.1:
```
$ opam show ocaml -f setenv:
[CAML_LD_LIBRARY_PATH = "%{_:stubsdir}%"]
[CAML_LD_LIBRARY_PATH += "%{lib}%/stublibs"]
[OCAML_TOPLEVEL_PATH = "%{toplevel}%"]
```

> 2. did you tried to remove the environment file and reinstall a package on broken switches?

Tried now, the problem evolved. See below the line. But the evolution strengthens my feeling that old switches don't actually work.

> It seems to have worked on switch coq.8.8.2 as it is the only present

The coq.8.8.2 was setup by opam 2, it seems that's why it has an environment file. But that might indeed be why the build first failed and then succeeded.

--------

To be sure. There is no environment file, so `opam env` sets neither `CAML_LD_LIBRARY_PATH` nor `OCAML_TOPLEVEL_PATH`. In fact, on old switches `opam` thinks that `ocaml` is plain not installed, even tho it clearly is. However, after installing it, the environment looks fine, and we move on to the next problems.
First, installing `num` fails, because `ocamlfind` complains it's already there. Then, after a couple of attempts with `install` and `reinstall` and `remove` (which claimed to do nothing), installation worked, and I got to the next issue (which I'll file separately).

```bash
pgiarrusso@SilenceOfTheLambdas:~/git/Coq/dot-calculus$ opam upgrade
The following actions will be performed:
  ∗ install   ocaml         4.06.1                    [required by camlp5, coq-equations]
  ↗ upgrade   camlp5        7.05 to 7.06.10-g84ce6cc4
  ↻ recompile ott           0.28                      [uses ocaml]
  ↻ recompile ocamlfind     1.8.0                     [uses ocaml]
  ↻ recompile num           1.1                       [uses ocaml]
  ↻ recompile coq           8.8.0*                    [uses camlp5]
  ↗ upgrade   coq-equations 1.0+8.8 to 1.1+8.8
  ↻ recompile coq-ott       0.28                      [uses ocaml]
===== ∗ 1   ↻ 5   ↗ 2 =====
Do you want to continue? [Y/n]
pgiarrusso@SilenceOfTheLambdas:~/git/Coq/dot-calculus$ opam switch
#  switch                   compiler                    description
   4.05.0                   ocaml-base-compiler.4.05.0
→  coq-8.8.0                ocaml-base-compiler.4.06.1  base-bigarray.base base-threads.base base-unix.base ocaml-base-compiler.4.06.1
   coq-8.8.1                ocaml-base-compiler.4.06.1  base-bigarray.base base-threads.base base-unix.base ocaml-base-compiler.4.06.1
   coq-8.8.1-equations-1.0  ocaml-base-compiler.4.06.1
   coq-8.8.2                ocaml-base-compiler.4.07.0  coq-8.8.2
pgiarrusso@SilenceOfTheLambdas:~/git/Coq/dot-calculus$ which ocaml
/Users/pgiarrusso/.opam/coq-8.8.1/bin/ocaml
pgiarrusso@SilenceOfTheLambdas:~/git/Coq/dot-calculus$ which ocamlc
/Users/pgiarrusso/.opam/coq-8.8.1/bin/ocamlc
pgiarrusso@SilenceOfTheLambdas:~/git/Coq/dot-calculus$ ll /Users/pgiarrusso/.opam/coq-8.8.1/bin/ocaml
-rwxr-xr-x 1 pgiarrusso staff 12630063 Jul 10 01:33 /Users/pgiarrusso/.opam/coq-8.8.1/bin/ocaml*
pgiarrusso@SilenceOfTheLambdas:~/git/Coq/dot-calculus$ opam install ocaml
The following actions will be performed:
  ∗ install   ocaml         4.06.1
  ↻ recompile ott           0.28    [uses ocaml]
  ↻ recompile ocamlfind     1.8.0   [uses ocaml]
  ↻ recompile camlp5        7.05    [uses ocaml]
  ↻ recompile num           1.1     [uses ocaml]
  ↻ recompile coq           8.8.0*  [uses num, camlp5, ocamlfind]
  ↻ recompile coq-ott       0.28    [uses ocaml]
  ↻ recompile coq-equations 1.0+8.8 [uses ocaml]
===== ∗ 1   ↻ 7 =====
Do you want to continue? [Y/n] y
```



```
pgiarrusso@SilenceOfTheLambdas:~/git/Coq/dot-calculus$ opam install num
The following actions will be performed:
  ∗ install num 1.1

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
[num.1.1] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
[ERROR] The installation of num failed at "make install".

#=== ERROR while installing num.1.1 ===========================================#
# context     2.0.0 | macos/x86_64 | base-bigarray.base base-threads.base base-unix.base ocaml-base-compiler.4.06.1 | https://opam.ocaml.org/#353f5fa6
# path        ~/.opam/coq-8.8.0/.opam-switch/build/num.1.1
# command     ~/.opam/opam-init/hooks/sandbox.sh install make install
# exit-code   2
# env-file    ~/.opam/log/num-37979-e4db2f.env
# output-file ~/.opam/log/num-37979-e4db2f.out
### output ###
# /Library/Developer/CommandLineTools/usr/bin/make -C src install
# cp META.in META
# ocamlfind install num META
# ocamlfind: Package num is already installed
#  - (file /Users/pgiarrusso/.opam/coq-8.8.0/lib/num/META already exists)
# make[1]: *** [install] Error 2
# make: *** [install] Error 2



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
┌─ The following actions failed
│ ∗ install num 1.1
└─
╶─ No changes have been performed

==
⊘ removed   coq-equations.1.0+8.8
⊘ removed   coq-ott.0.28
⊘ removed   coq.8.8.0
⊘ removed   camlp5.7.05
⊘ removed   num.1.1
⊘ removed   ocamlfind.1.8.0
⊘ removed   ott.0.28
```

**Comment by rjbou** [comment]
Update: env file regeneration just merged!

**Comment by rjbou** [comment]
Environment file are regenerated since 2.0.3.
Closing this issue, feel free to reopen if needed.
Thanks for the report!
