### ISSUE TITLE
Reinstall feature

### ISSUE THREAD

**Issue by XVilka** [ocaml/opam#3601]
Sometimes opam install fails if you have local modifications for some other packages, while the rest of ocaml packages weren't recompiled against changed implementations. Would be nice to have something like `opam install --recompile package` with just recompilation and reinstallation of the package against changed environment.

**Comment by AltGr** [comment]
Not sure I get exactly what you are after, but this looks like `opam reinstall PACKAGE` ?
You could also try `opam update --dev && opam reinstall --pending` to update and recompile any packages with e.g. git sources that have changed.
