### ISSUE TITLE
Installation issues with ccache

### ISSUE THREAD

**Issue by sebastiansturm** [ocaml/opam#3607]
I'm using ccache, but have my `cache_dir` set to a path within `/tmp/` that may or may not exist at any given time. Unfortunately, `opam-init/hooks/sandbox.sh` doesn't check whether a user-configured ccache directory actually exists, but instead tries to setup a mount unconditionally. In my experience, this causes switch/package installation attempts to fail with an empty .out file.
If my diagnosis is correct, can sandbox.sh be changed to either create the mount conditionally or at least abort with a specific error message if a specified ccache directory is found to be nonexistent?
thanks!

**Comment by rjbou** [comment]
Thanks for reporting.

Can you precise the error: Is it opam that fails mounting the non existent path (bwrap error) or ccache that misuses it?

**Comment by sebastiansturm** [comment]
If I recall correctly, commenting out the mount command made the issue go away, but I can retry tomorrow to make sure I'm not making any false claims here.
Would opam try to invoke ccache if present? Because with the way my machine is set up, ccache won't be called unless I do so explicitly

**Comment by rjbou** [comment]
>  commenting out the mount command made the issue go away

Ok, so it's ccache directories mounting, not fail to launch ccache.  Does it fail with an _No such file or directory_ error? We can then check the existence of the directory before adding it to the mounted ones. 

>Would opam try to invoke ccache if present?

No, opam don't use ccache itself (cf. #3395), but indeed, the directory must exists in order to bwrap mount it.

**Comment by sebastiansturm** [comment]
sandbox.sh doesn't emit any error message, it just fails with an exit code of 1 and no output at all. If I change `[ -d "$dir" ] && ARGS=("${ARGS[@]}" "$B" "$dir" "$dir")` to `if [ -d "$dir" ]; then (etc)`, then it skips the ccache mount and proceeds to configure OCaml (or at least it attempts to do so, it then complains about some read-only file system; that issue only arises when I try to manually invoke sandbox.sh though. `opam init` works fine if the ccache directory exists)

**Comment by rjbou** [comment]
Merged. Thanks for the reporting!
