### ISSUE TITLE
opam compiler packages require shared lib support

### ISSUE THREAD

**Issue by nojb** [ocaml/opam#3608]
The `gen_ocaml_config.ml` script is run when installing switches and requires shared library support to be built into the switch in question. This is incompatible with switches built with `-no-shared-libs`. See e.g. https://github.com/ocaml/opam-repository/issues/12769.

**Comment by avsm** [comment]
It's also problematic to keep copying this script throughout the opam repository whenever there is a new minor version of `ocaml` released.  We should think about how to factor this script out to make maintenance easier.

**Comment by dra27** [comment]
That should be easy to refactor into `Sys.command` calls.

The script propagation problem can be solved by having a branch on opam-repository to park the scripts in and then referencing that. However, to fully fix it, the script should be put in a package (say `ocaml-config-detect`) which should then become a dependency of the `ocaml` package.

**Comment by vog** [comment]
Why was this issue reopened? Are there any open issue here?

**Comment by dra27** [comment]
I expect because @avsm didn't expect updating his own fork of opam-repository would cause the "Closes" comment in a commit being pushed to propagate here! However, the issue can indeed be closed.

**Comment by avsm** [comment]
Deary me, the dangers of an over privileged github account...
