### ISSUE TITLE
`opam install --deps-only --with-test` does not seem to install test dependencies

### ISSUE THREAD

**Issue by Niols** [ocaml/opam#3609]
Hello there,

When developing, I am almost always using the scheme:
- `opam install . --deps-only`
- `make`

I wanted to have something similar for tests, like:
- `opam install . --deps-only --with-test`
- `make`
- `make test`

However, `opam install . --deps-only --with-test` (and also `OPAMWITHTEST=true opam install . --deps-only`) seems to only install the same dependencies as `opam install . --deps-only` which is, to me, a bit surprising. Is it a bug? Is there an other way to achieve this?

By the way, there seems to be the same problem with `--with-doc`.

---

In case you need it, my `opam config report`:

```
# opam-version      2.0.0 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=arch os-version=rolling
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              3
# repositories      1 (http) (default repo at 7484a9dd)
# pinned            1 (git)
# current-switch    4.06.1
```

**Comment by rjbou** [comment]
It have the expected behavior:
```
$ opam show . -f depends:
"ocaml" {>= "4.02.3"} "ago" "abella" {with-test}
$ opam install . --deps-only
The following actions will be performed:
  ∗ install ago 0.4
Do you want to continue? [Y/n] n
$ opam install . --deps-only --with-test
The following actions will be performed:
  ∗ install ago    0.4
  ∗ install abella 2.0.5
===== ∗ 2 =====
Do you want to continue? [Y/n] n
```

Is your opam file in 1.2 or 2.0 format? 

There was an change in the test and doc variables which are now `with-{test,doc}` cf. [upgrade guide](https://opam.ocaml.org/doc/Upgrade_guide.html)

_extra dependencies needed for test and documentation must now be flagged with resp. with-test and with-doc. Fields build-test: and build-doc: are deprecated in favour of filters on build: instructions, and there is a new run-test: field_

If it is in an 1.2 format, this update is done internally, but if it is 2.0 format and using the variable `test`, it will be ignored, as it is an undefined variable (cf. #3580).

**Comment by Niols** [comment]
Oh. The flags too are `with-tests` and `with-doc`. This explains everything: I had specified them with only `test` and `doc` in a 2.0 OPAM file. Shouldn't that be a warning in `opam lint`? Or are they kept because they are valid in the 1.2 format?

**Comment by Niols** [comment]
OK. I guess my linting version was just not up-to-date. Thank you very much for your time and your explanations :-), and sorry about the noise.

**Comment by rjbou** [comment]
fyi, opam.2.0.1, which contains the added linting warning, will be release from now until the end of this week. 
Thanks!

**Comment by anentropic** [comment]
Has this changed again in opam 2.1?

I have test deps specified as:

```
   "alcotest" {with-test & >= "1.4" & < "1.5"}
  "junit_alcotest" {with-test & >= "2.0" & < "2.1"}
```

but `opam install --deps-only --with-test .` does not install them

**Comment by mroch** [comment]
> Has this changed again in opam 2.1?

this is an old closed issue which won't get much visibility. I suggest opening a new one.
