### ISSUE TITLE
colon in <pkgname>.config grammar

### ISSUE THREAD

**Issue by gitoleg** [ocaml/opam#3612]
Looks like it's a bug somewhere: either in manual, or in opam.
manual (colon exits):
```
variables: "{" { <ident>: ( <string> | [ <string> ... ] | <bool> ) ... } "}"
```
in real life colon missed: 
```
$ cat ~/.opam/4.05.0/.opam-switch/config/ocaml.config
opam-version: "2.0.0"
variables {
...
```
And opam failed with `Parse error` at install stage if I generate config file with `:`.

**Comment by rjbou** [comment]
Indeed, it is an error in the documentation. Thanks for reporting!
