### ISSUE TITLE
Opam init error message lacking context

### ISSUE THREAD

**Issue by NathanReb** [ocaml/opam#3614]
If you run `opam init` with an empty string passed to `--compiler`, say because it is passed an unset env variable in your CI, you get the following error message:

```
Fatal error: Package version can't be empty
```

which, while not being completely impossible to grasp, is still confusing and could use a little more context. Even just concatenating `"Invalid compiler version: "` or something similar to the message would be a huge improvement.

It seems to directly come from a `failwith` in [opamPackage.ml](https://github.com/ocaml/opam/blob/master/src/format/opamPackage.ml#L27).

I'd be happy to contribute if you feel like this is worth fixing!

**Comment by rjbou** [comment]
Thanks for reporting!
