### ISSUE TITLE
dev-repo url as git branch in opam file

### ISSUE THREAD

**Issue by barockobamo** [ocaml/opam#3616]
Packaging my software as an opam package i would like to test it in a fork of opam-repository.
Since i am still coding, i did not merge my branch yet in my repositories.
So i try to set the dev-repo url in my opam package as an url on a branch like mentioned here : https://opam.ocaml.org/doc/Manual.html#URLs 3
Could it work ?
Because when i test it seems that opam is still using the master branch.
Regards,
Sam.

**Comment by rjbou** [comment]
If you want to test a fork of opam repository, you can add a [new repo](https://opam.ocaml.org/doc/Manual.html#Repositories) using the command `opam repo add <name> <url>` where `<url>` conform [URL specification](https://opam.ocaml.org/doc/Manual.html#URLs) (and then can be a branch of you repo, e.g `git+https://github.com/xxx/yyy#branch`).

The [`dev-repo`](https://opam.ocaml.org/doc/Manual.html#opamfield-dev-repo) field in the opam file is used for [pinning](https://opam.ocaml.org/doc/Manual.html#Pinning) a package to its current development state, following the reference repository.

**Comment by barockobamo** [comment]
Thanks, then i was doing things in the right way. So here is my second and last question :
Why after my new dev branched repository is well added (with my package opam file in it)
can't i install my package ? Where does my sources are downloaded from ? At this point each time opam try to download the tar file from the right url from the url section it fail... :
``Next task in job 2: 
/usr/bin/curl --write-out %{http_code}\n --retry 3 --retry-delay 2 --user-agent opam/2.0.0 -L -o /home/test/.opam/4.04.2/.opam-switch/sources/fjs_of_fml.0.1/fjs_of_fml-0.1.tar.gz.part https://gforge.inria.fr/frs/download.php/file/37774/fjs_of_fml-0.1.tar.gz
Processing  3/3: [fjs_of_fml.0.1: http]
00:02.765  PARALLEL               Collected task for job 2 (ret:0)
00:02.766  SYSTEM                 rm /home/test/.opam/4.04.2/.opam-switch/sources/fjs_of_fml.0.1/fjs_of_fml-0.1.tar.gz.part
00:02.766  CURL                   Could not download file at https://gforge.inria.fr/frs/download.php/file/37774/fjs_of_fml-0.1.tar.gz.
``
Sorry for the no format format source :~

**Comment by rjbou** [comment]
Can you precise the process/steps you followed, from adding the package to your opam repo to the problematic point. It is helpful to understand the issue.

>  At this point each time opam try to download the tar file from the right url from the url section it fail...

This target url is not publicly reachable (redirect to a login page and curl downloads only an xml file).

> Sorry for the no format format source :~

There was a missing backquote, I edited you comment :)

**Comment by nieulSshit** [comment]
Here is my opam file in may : opam-dev-repo : https://github.com/nieulSshit/opam-repository/blob/jsexp/packages/fjs_of_fml/fjs_of_fml.0.1/opam
The path of the repo and the path tar are in it.
The way i have been tested is the one tou described, so you can reproduce it easily.

**Comment by rjbou** [comment]
There is some error in your opam file (version, urls, description). You can use `opam lint` to validate your opam files.

> The way i have been tested is the one you described, so you can reproduce it easily

I can guess command you used to install pin, etc, but I can't be sure. For example, I can reproduce the install that fails to download the tar, but I don't know if you tried to install it or dev-pin it.
If you try to install, as I said in my previous comment, this [archive](https://gforge.inria.fr/frs/download.php/file/37774/fjs_of_fml-0.1.tar.gz) is not reachable, opam can't download it.

**Comment by nieulSshit** [comment]
* Local installation works fine ("opam install ."). That's why i started integration tests before pulling or merging anything.
* A this point i don't understand how opam get the sources. Is it with "dev-repo" or "url" section. I tried both without success (last is "url"). (I guess this is the important point)
* About opam file itself. Is Opam only using the one in its repository ? Or is there a check about conscistency with the one at the root of the package.
* About the url path and the archive. How can i check that opam can access it ? With wget or through 
a navigator it's ok, so what else could i do ?

**Comment by rjbou** [comment]
> A this point i don't understand how opam get the sources. Is it with "dev-repo" or "url" section.

Without pinning, `opam install` takes `url` section from the repository opam file

> Opam only using the one in its repository ? Or is there a check about conscistency with the one at the root of the package.

Without pinning, opam takes only the one in the repository. No consistency check is performed, package maintainer way want ot have different opam files from dev-pin and repo install.
But depending on how you choose to publish the package, opam can take the project opam file to publish it.

> How can i check that opam can access it ?

You can try a simple `wget` or `curl` check, and if you launch on vebose mode, you have the exact command that opam launches, like the one in https://github.com/ocaml/opam/issues/3616#issuecomment-432226382 (you just need to change the output file, as it is an opam internal files/directory).

**Comment by nieulSshit** [comment]
Ok, i had an issue on Inria Gforge. I changed  the src path in url section in ``https://www.dropbox.com/s/mc02gmv8iov2d7a/fjs_of_fml-0.1.tar.gz?dl=1``.
This command : ``/usr/bin/curl --write-out %{http_code}\n --retry 3 --retry-delay 2 --user-agent opam/2.0.0 -L -o ./fjs_of_fml-0.1.tar.gz.part https://www.dropbox.com/s/mc02gmv8iov2d7a/fjs_of_fml-0.1.tar.gz?dl=1`` do the job.
But here is the opam one : ``00:03.766  PARALLEL               Next task in job 2: /usr/bin/curl --write-out %{http_code}\n --retry 3 --retry-delay 2 --user-agent opam/2.0.0 -L -o /home/test/.opam/4.04.2/.opam-switch/sources/fjs_of_fml.0.1/fjs_of_fml-0.1.tar.gz.part https://www.dropbox.com/s/mc02gmv8iov2d7a/fjs_of_fml-0.1.tar.gz`` Why is it truncated ? Is dropbox forbidden ? Even for dev ?

**Comment by rjbou** [comment]
Check your opam file. You can find from which repository and the content of the opam file using the command `opam show`. opam doesn't truncate the url, downloads well, but your next error will be 
```
$ opam install jsf_of_fml -vv -y
The following actions will be performed:
  ∗ install conf-autoconf 0.1 [required by fjs_of_fml]
  ∗ install fjs_of_fml    0.1
===== ∗ 2 =====

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+ /usr/bin/curl "--write-out" "%{http_code}\\n" "--retry" "3" "--retry-delay" "2" "--user-agent" "opam/2.0.1" "-L" "-o" "/home/rjbou/.opam/rec/.opam-switch/sources/fjs_of_fml.0.1/fjs_of_fml-0.1.tar.gz?dl=1.part" "https://www.dropbox.com/s/mc02gmv8iov2d7a/fjs_of_fml-0.1.tar.gz?dl=1"
[...]
[fjs_of_fml.0.1] downloaded from https://www.dropbox.com/s/mc02gmv8iov2d7a/fjs_of_fml-0.1.tar.gz?dl=1
[ERROR] The sources of the following couldn't be obtained, aborting:
          - fjs_of_fml.0.1:
            Unknown archive type: /tmp/opam-25936-1872ec/fjs_of_fml-0.1.tar.gz?dl=1

'opam install fjs_of_fml -vv -y' failed.
```
opam need the extension to determine the archive type,and with the `?dl=1` part, it becomes unclear.

**Comment by barockobamo** [comment]
Thanks Raja,
I will upload my sources somewhere else.
Thanks for all yours advices. I will close this issue and thankfully it's the holidays, i'm going to go and raise goats in Larzac.
Sam
