### ISSUE TITLE
Website: Cannot subscribe to RSS feed

### ISSUE THREAD

**Issue by RalfJung** [ocaml/opam#3619]
I am trying to subscribe to the RSS feed at https://opam.ocaml.org/blog/feed.xml, but it doesn't work. I am using Thunderbird as my feed reader, and it just stops at "Verifying the feed". Plenty of other feeds work just fine, so I am left to suspect that it is something about this feed in particular that is causing this breakage.

One thing I noticed is that the content-type is wrong: The HTTP response header contains no content-type, whereas usually it should say "Content-Type: application/xml". I am not sure if that is the problem. I cannot see anything useful in Thunderbird's error logs.

**Comment by dbuenzli** [comment]
Validation [fails](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fopam.ocaml.org%2Fblog%2Ffeed.xml).

**Comment by rjbou** [comment]
all green now!

**Comment by rjbou** [comment]
Thanks for reporting!
