### ISSUE TITLE
Opam version on Alpine Linux

### ISSUE THREAD

**Issue by jrochel** [ocaml/opam#3621]
Hello,

I just wanted to remark that on Alpine Linux the latest opam version available is still 1.2.2-r4.
Tagging @avsm who is the maintainer of the package for Alpine Linux.

Jan

**Comment by avsm** [comment]
I did a quick PR at https://github.com/alpinelinux/aports/pull/5478 -- comments/testing welcome there

**Comment by avsm** [comment]
the opam2 port will be in alpine 3.9
