### ISSUE TITLE
OPAM 2.0 does not understand symlinks

### ISSUE THREAD

**Issue by jstolarek** [ocaml/opam#3622]
On my system directory `~/.opam` is a symlink to an actual directory on a different partition. This is due to lack of space on my `/home` partition.  OPAM 1.2.2 was perfectly fine with this setup, but OPAM 2.0 apparently does not understand symlinks and errors out.  Here's an example scenario. I have created an empty `~/.opam` directory (not a symlink), downloaded OPAM 2.0 with `sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)` and installed 4.06.1 switch. All works fine so far. Now, I create a directory on a different partition, copy all of `~/.opam` contents to that directory, remove (now empty) `~/.opam`, and create a `~/.opam` symlink to the directory that now contains OPAM data.  Here's what happens when I try to install dune:

```
$ opam install dune
The following actions will be performed:
  ∗ install dune 1.4.0

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[dune.1.4.0] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of dune failed at "/home/killy/.opam/opam-init/hooks/sandbox.sh build ocaml bootstrap.ml".

#=== ERROR while compiling dune.1.4.0 =========================================#
# context     2.0.0 | linux/x86_64 | ocaml-base-compiler.4.06.1 | https://opam.ocaml.org#1fa4c078
# path        ~/.opam/4.06.1/.opam-switch/build/dune.1.4.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml bootstrap.ml
# exit-code   1
# env-file    ~/.opam/log/dune-31468-ad8886.env
# output-file ~/.opam/log/dune-31468-ad8886.out
### output ###
# Can't mkdir /home/killy/.opam/4.06.1: No such file or directory



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build dune 1.4.0
└─
╶─ No changes have been performed
```

I now revert everything to how it was originally, i.e. remove `~/.opam` symlink, create `~/.opam` directory, and copy back all of the contents that was originally there. Now everything works:

```
$ opam install dune
The following actions will be performed:
  ∗ install dune 1.4.0

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[dune.1.4.0] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed dune.1.4.0
Done.
```

```
$ opam config report
# opam config report
# opam-version      2.0.0
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=debian os-version=9.5
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              7
# repositories      1 (http) (default repo at 1fa4c078)
# pinned            0
# current-switch    4.06.1
```

**Comment by rjbou** [comment]
opam resolves symlinks, it shouldn't be an issue if you move and symlink (successfully tried it, same os besides).
You can see the internal  opamroot wih `opam config var root`, can you share it?
How did you create your link?

**Comment by jstolarek** [comment]
> opam resolves symlinks, it shouldn't be an issue if you move and symlink (successfully tried it, same os besides).

I claim that for me it doesn't. I just reproduced the problem on a second machine.

>  You can see the internal opamroot wih `opam config var root`, can you share it?

```
$ opam config var root
/home/killy/.opam
```

> How did you create your link?

In `~` directory:
```
$ ln -s /data/sandboxes/ocaml .opam
```

**Comment by jstolarek** [comment]
For the sake of completeness:

```
$ ls -al
total 11432
lrwxrwxrwx  1 jstolarek jstolarek       21 Nov  6 16:37 .opam -> /data/sandboxes/ocaml
```
```
$ ls .opam
config  config.lock  default  download-cache  lock  log  opam-init  repo
```

Interestingly, log files are created inside `log` subdirectory without problems.

**Comment by rjbou** [comment]
Ah! The command result is not the resolved path, this is unusual.

The presence of the `log` folder is maybe a consequence of the fail to normalize the path. In order to get the linked path, opam uses `Unix.getcwd` and if it fails, create the log dir (cf. [`normalize`](https://github.com/ocaml/opam/blob/master/src/core/opamSystem.ml#L271) and [`getchdir`](https://github.com/ocaml/opam/blob/master/src/core/opamSystem.ml#L261)).

Could it be related to some permission problem on the `/data/sandboxes` volume?

**Comment by jstolarek** [comment]
> Could it be related to some permission problem on the `/data/sandboxes` volume?

Both `/data/sandboxes` and `/data/sandboxes/ocaml` have 755 permissions.

**Comment by jvillard** [comment]
#3677 was another instance of this. Just as a data point I mount .opam somewhere else because my home directory is on a network filesystem and putting .opam there would slow things down.

That said, I cannot reproduce the error in the original post in my setup: I am able to install packages (including "dune"). The thing I am unable to do is create a local switch *and specify its compiler* at the same time (see #3677).

**Comment by rjbou** [comment]
Found it! `OpamFilename.{,Dir}.of_string` , filename & dirname creation resolves symlinks, but not the concatenation operators `OpamFilename.Op.{/,//}`, which is used to create the [default root_dir](https://github.com/ocaml/opam/blob/master/src/state/opamStateConfig.ml#L30).

**Comment by jvillard** [comment]
Meanwhile this hack/workaround helps:

```sh
OPAMROOT=${OPAMROOT:-"$HOME"/.opam}                                                                                                                           
OPAMROOT=$(realpath "$OPAMROOT")                                                                                                                              
export OPAMROOT
```

**Comment by rjbou** [comment]
Thanks for reporting!
