### ISSUE TITLE
Upgrade `opam lint` to v2 practices

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#3623]
I recently got a few remarks by the OCaml `opam-repository` maintainers about my `opam` file submissions. It would be nice if `opam lint` could report these, at least as warnings. Specifically: 

* `test` vs `with-test` (IIRC there are other of these tags that went from `TAG` to `with-TAG`), in [this submission](https://github.com/ocaml/opam-repository/pull/12846#issuecomment-432242445) 
* Checksum specification in `url` sections and normalization of `src` vs `archive` (one should be chosen in my opinion), in [this submission](https://github.com/ocaml/opam-repository/pull/12796#issuecomment-429648055)

**Comment by dbuenzli** [comment]
Ah @mseri [tells](https://github.com/ocaml/opam-repository/pull/12846#issuecomment-432246410) this may be solved in 2.0.1, I'll let you close if that is the case.

**Comment by rjbou** [comment]
Indeed, cf. discussions in #3580 and https://github.com/ocaml/opam-repository/issues/12729.

For checksum, adding a warning if not specified given can be added.

**Comment by dbuenzli** [comment]
> For checksum, adding a warning if not specified given can be added.

I don't mind the way it is now. It would only be nice if `opam lint` matches what `opam-repository` maintainers want.

**Comment by rjbou** [comment]
Resolved by #3591 #3758.
Thanks for the report!
