### ISSUE TITLE
Trying to install opam 2.0.1 gives 2.0.0

### ISSUE THREAD

**Issue by Blaisorblade** [ocaml/opam#3626]
The instructions on https://opam.ocaml.org/blog/opam-2-0-1/ install opam 2.0.0 instead because the version hasn't been updated:

https://github.com/ocaml/opam/blob/f721385a528a4d04a508c4fabb17ffa046cc2169/shell/install.sh#L8

I've run into https://github.com/ocaml/opam/pull/3560#issuecomment-430236580 but the script on the 2.0 branch wasn't updated either.

I'd have PRed this, but one must also update the checksums, and the proper fix would touch the release process (either the checklist or the scripts). I don't see a script for updating the checksum, which makes this sort of error more likely.

```bash
$ sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
## Downloading opam 2.0.0 for darwin on x86_64...
## Downloaded.
## Where should it be installed ? [/usr/local/bin]
## opam 2.0.0 installed to /usr/local/bin
## Converting the opam root format & updating
[NOTE] Will configure from built-in defaults.
Checking for available remotes: rsync and local, git.
  - you won't be able to use mercurial repositories unless you install the hg command on your system.
  - you won't be able to use darcs repositories unless you install the darcs command on your system.
```

**Comment by rjbou** [comment]
Install script has been updated. Thanks for the report!
