### ISSUE TITLE
Incomprehensible bug with 2.0.1

### ISSUE THREAD

**Issue by pmetzger** [ocaml/opam#3636]
I'm trying to update the MacPorts package for opam to 2.0.1. The update was extremely straightforward, and the resulting binary seems to do `opam update` just fine, but `opam upgrade` does something I've never seen before:

```
$ opam --version
2.0.1
$ opam upgrade   
opam(44003,0x112e675c0) malloc: can't allocate region
*** mach_vm_map(size=259407338536550400) failed (error code=3)
opam(44003,0x112e675c0) malloc: *** set a breakpoint in malloc_error_break to debug
Fatal error: out of memory.
```

My machine isn't out of memory, it's behaving just fine. Obviously I can't push the new package to the MacPorts repository until this is fixed. Note that so far as I can tell, 2.0.0 was working just fine. I'm quite stumped.

`opam config report` output is below.

```
$ opam config report
# opam config report
# opam-version      2.0.1 
# self-upgrade      no
# system            arch=x86_64 os=macos os-distribution=macports os-version=10.14
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              7
# repositories      1 (http) (default repo at 27ae4ff1)
# pinned            0
# current-switch    ocaml-base-compiler.4.07.1
```

**Comment by dra27** [comment]
What happens if you go back to your 2.0.0 binary?

**Comment by dra27** [comment]
> My machine isn't out of memory, it's behaving just fine.

It definitely was - that's not an OCaml message!

**Comment by AltGr** [comment]
it most likely comes from MCCS... but there were _no changes_ since 2.0.0.
Expect perhaps in the compilation commands or options ?

**Comment by pmetzger** [comment]
Restoring the 2.0.0 binary completely repairs the problem. I'm at a loss to explain what is going on.

**Comment by pmetzger** [comment]
I'm happy to do whatever is necessary to debug this problem but I have no clue how to begin.

**Comment by pmetzger** [comment]
(Is there a way I could compile mccs without the change in compilation flags just to check? What do I need to do in order to do that?)

**Comment by dra27** [comment]
So the 2.0.0 binary allows you to run `opam upgrade` - having done that, what does the 2.0.1 one do?

**Comment by pmetzger** [comment]
I see no reason to believe it would do anything other than what it did last time, but I'm checking now.

**Comment by pmetzger** [comment]
...and now, it is not dying any more. Is that because the solver isn't being invoked?

**Comment by dra27** [comment]
The solver will be being invoked, yes. Do you have a backup of the opam switch from before the upgrade, or can you relatively easily reset the switch to the same state (enough scrollback on the terminal?!)

**Comment by pmetzger** [comment]
I don't have a backup, and now I can't trigger the bug when trying 2.0.1 no matter what I do. This is annoying.

**Comment by dra27** [comment]
Incidentally, I just noticed the size of the page `malloc` tried to allocate 😱

**Comment by dra27** [comment]
Well, for now it suggests that it’s more likely an issue between two separate builds than specifically its being 2.0.1. If it crops again, armed with a backup, the issue may be bisectable.

**Comment by pmetzger** [comment]
I'm going to close this for now. I'm presuming it's real but that it involves some weird and hard to reproduce combination of circumstances.

**Comment by avsm** [comment]
that addition of `-x c++` could have caused a change wrt PIE behaviour that might cause this. See https://caml.inria.fr/mantis/view.php?id=5707 or https://caml.inria.fr/mantis/view.php?id=5717 for other hard-to-track down instances of this sort of large-malloc error caused by register corruption somewhere...

**Comment by jberdine** [comment]
FYI I think I ran across this issue (same error message). Unfortunately I wasn't paying very close attention and didn't search enough to find this while I could still repro the issue. But in case it helps, I had opam 2.0.2 and saw this error when my default switch was set to use ocaml 4.07.0 from brew, and the brew package had switched to 4.07.1. After changing the base of the default switch and recompiling everything, `opam upgrade` no longer failed with these huge map calls.

**Comment by dbuenzli** [comment]
FWIW, I also *sometimes* see this:

```
opam(4007,0x1193e55c0) malloc: can't allocate region
*** mach_vm_map(size=259407338536550400) failed (error code=3)
opam(4007,0x1193e55c0) malloc: *** set a breakpoint in malloc_error_break to debug
Fatal error: out of memory.
``` 
when I do:
```
opam list --available -s | xargs opam install --best-effort --yes
```
Usually trying a second time gets through it though (that was on a 4.07.1 switch).

**Comment by dbuenzli** [comment]
Could be related to https://github.com/ocaml/opam/issues/3636

**Comment by gasche** [comment]
I just looked, and couldn't find any usage of value recursion in the opam codebase, so I'm a bit skeptical.

```shell
$ git grep -C30 -e "let rec [a-zA-Z_0-9]* =" --and --not -e "function"
```
