### ISSUE TITLE
Bash PROMPT_COMMAND error after upgrade to opam 2.01

### ISSUE THREAD

**Issue by grayswandyr** [ocaml/opam#3640]
Hi

after installing Opam 2.01, the prompt of my bash install is broken, see the extract below. Please note that I use [bash-it](https://github.com/Bash-it/bash-it) to improve the Bash experience (in particlar by installing the Powerline prompt theme), so I guess there is a bad interaction between the two, with semicolons in the wrong place. For this reason, I can't affirm the issue comes from Opam but my problem is that I don't even find how to remove the Opam hook...?
```
# opam config report
# opam-version      2.0.1 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=ubuntu os-version=18.04
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              3
# repositories      1 (http) (default repo at 2913c56a)
# pinned            0
# current-switch    4.06.1
bash: PROMPT_COMMAND: ligne 1: erreur de syntaxe près du symbole inattendu « ;; »
bash: PROMPT_COMMAND: ligne 1: `__powerline_prompt_command;_opam_env_hook;;preexec_invoke_cmd'
```

**Comment by rjbou** [comment]
You can use `opam init` to disable and enable shell hook, see [man page](https://opam.ocaml.org/doc/man/opam-init.html#lbAF).

You'll find the file containing the hook in `~/.opam/opam-init/env-hook.sh`, you can edit it to change it to be bash-it-compliant.

**Comment by grayswandyr** [comment]
OK thank you I'll look into this.

**Comment by rjbou** [comment]
If you have a corrective for `bash-it`, please share with us. I could help other opam & bash-it users :)
Thanks for the report!

**Comment by grayswandyr** [comment]
If I find a fix, I'll share it!
