### ISSUE TITLE
opam cannot uninstall package

### ISSUE THREAD

**Issue by neuer93** [ocaml/opam#3647]
When I tried to run 
**opam uninstall z3**
```
> Your request can't be satisfied:
>   - ocaml-base-compiler = 4.05.0 is in conflict with ocaml-system
> 
> No solution found, exiting
```
I don't how it happened, since I didn't install ocaml-system.

Opam version: 2.0.1
```
> → opam list

> # Packages matching: installed
> # Name              # Installed # Synopsis
> base-bigarray       base
> base-num            base        Num library distributed with the OCaml compiler
> base-threads        base
> base-unix           base
> camlidl             1.05        Stub code generator for OCaml
> cil                 1.7.3       A front-end for the C programming language that facilitates program analysis and transformation
> conf-gmp            1           Virtual package relying on a GMP lib system installation
> conf-m4             1           Virtual package relying on m4
> conf-python-2-7     1.0         Virtual package relying on Python-2.7 installation
> num                 0           The Num library for arbitrary-precision integer and rational arithmetic
> ocaml               4.05.0      The OCaml compiler (virtual package)
> ocaml-base-compiler 4.05.0      Official 4.05.0 release
> ocamlbuild          0.12.0      OCamlbuild is a build system with builtin rules to easily build most OCaml projects.
> ocamlfind           1.8.0       A library manager for OCaml
> z3                  4.7.1       pinned to version 4.7.1 at git://github.com/Z3Prover/z3#a7a0dee
```
[rjbou] Edit format

**Comment by neuer93** [comment]
I find the problem may be that ocaml-system is already in my system and it is outside of opam.

```
> → opam list --base

> # Packages matching: base
> # Name        # Installed # Synopsis
> base-bigarray base
> base-threads  base
> base-unix     base
> ocaml-system  --          The OCaml compiler (system version, from outside of opam)

```

The output of other cmds:

```
> → opam config report

> # opam config report
> # opam-version      2.0.1
> # self-upgrade      no
> # system            arch=x86_64 os=macos os-distribution=homebrew os-version=10.14
> # solver            builtin-mccs+glpk
> # install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
> # upgrade-criteria  -removed,-count[version-lag,solution],-new
> # jobs              4
> # repositories      1 (http) (default repo at 921c0342)
> # pinned            1 (git)
> # current-switch    system
```

```
> → opam config var sys-ocaml-version

> 4.07.0
```

```
> → opam list --installed-roots
> # Packages matching: root
> # Name        # Installed # Synopsis
> base-bigarray base
> base-threads  base
> base-unix     base
> camlidl       1.05        Stub code generator for OCaml
> cil           1.7.3       A front-end for the C programming language that facilitates program analysis and transformation
> z3            4.7.1       pinned to version 4.7.1 at git://github.com/Z3Prover/z3#a7a0dee
```

**Comment by rjbou** [comment]
opam handles ocaml installed outside of opam, and uses it on system-based switch. Here it seems there is some inconsistency. On your first comment, the switch contains an opam installed `ocaml.4.05.0`, while on the second comment, the switch relies on an system installed `ocaml.4.07.0`, but without having the package `ocaml-system` installed (no version and absent from roots).

Did you changed the switch base / compiler in the meantime?
You intended to use the opam installed `ocaml.4.05.0 ` compiler or system one?

Can you check and share the ocaml version when using this switch and the `compiler` field in the file `~/.opam/<switchname>/.opam-switch/switch-state`.

**Comment by neuer93** [comment]
Yes, I switched the version of ocaml from 4.07.0 to 4.05.0 before. 
So the suggestion is to switching base/ compiler in the meantime or switch ocaml back to 4.07.0?

**Comment by rjbou** [comment]
ok, seems that something wrong happened when you switched you switch compiler from system 4.07.0 to opam 4.05.0. 
Do you remember how you did it ?
You'll need to recover to a normal state? Wich one do you want for this switch : system 4.07.0 or opam 4.05.0?

**Comment by neuer93** [comment]
I tried to install Z3 and it automatically changed the version of opam. 
If possible, I prefer to switching to the original version of opam and uninstall z3.

**Comment by rjbou** [comment]
A package can't change a switch compiler, unless you specify the option `--unlock-base`. 
If you want to get back system 4.07.0 installed in the switch, you'll need to reinstall the system compiler and then set it as base:
```
$ opam install ocaml-system.4.07.0 --unlock-base #it will recompile everything
$ opam switch set-base ocaml ocaml-config  ocaml-system base-bigarray base-unix base-threads
```
