### ISSUE TITLE
Where does opam install stuff and why the binaries are not included in path?

### ISSUE THREAD

**Issue by kant111** [ocaml/opam#3648]
Where does opam install stuff in mac? and why the binaries are not included in path?

For example when I do

`opam install why3`

It Installs successfully but then when I type `why3` in command line it says `command not found`

or if I want to install some other program that I depends on `why3` then it fails because `why3` is not found although it installed successfully.

**Comment by dra27** [comment]
You'll get a wider audience for help on OCaml's [Discuss forum](https://discuss.ocaml.org).

The installation location is by default `~/.opam` which can be found with `opam config list` (see `root` in `Global opam variables`):

```
dra@cosmic:~$ opam config list

<><> Global opam variables ><><><><><><><><><><><><><><><><><><><><><><><><><><>
arch              x86_64          # Inferred from system
jobs              3               # The number of parallel jobs set up in opam configuration
make              make            # The 'make' command to use
opam-version      2.0.1           # The currently running opam version
os                linux           # Inferred from system
os-distribution   ubuntu          # Inferred from system
os-family         debian          # Inferred from system
os-version        18.10           # Inferred from system
root              /home/dra/.opam # The current opam root directory
```

For the binaries not being in PATH, it sounds as though you haven't run `eval $(opam env)` in your shell (or whichever incantation is necessary for the shell you're using). `opam init` will have offered to add that to appropriate startup scripts - perhaps you just need to relaunch your terminal?

**Comment by rjbou** [comment]
Resolved by env hook (if enabled)!
Thanks!

**Comment by greenm01** [comment]
Love this little calculator!
