### ISSUE TITLE
with-test is not defined inside run-test, contrarily to the doc

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam#3653]
The [documentation should be updated](https://opam.ocaml.org/doc/Manual.html#Package-variables) as it says that `with-test` is available inside `run-test` while [it is not the case](https://github.com/ocaml/opam-repository/pull/12922#issuecomment-435691357).

**Comment by rjbou** [comment]
Yes, `run-test` was erroneously on this list. As `run-test` needs the package be installed with `with-test`, there is no need to add the `{with-test}` filter on its commands.

**Comment by rjbou** [comment]
Doc updated, thanks for the report!
