### ISSUE TITLE
Sandboxing breaks gcc on centos

### ISSUE THREAD

**Issue by mroch** [ocaml/opam#3660]
I'm having trouble with sandboxing on CentOS7.

During `opam init` as it tries to compile `ocaml-base-compiler`:

```
ocaml-base-compiler-4.07.0: gcc: error trying to exec 'cc1': execvp: No such file or directory
```

I got into a sandbox via:

```
bwrap --unshare-net --new-session --proc /proc --dev /dev \
  --bind /tmp /tmp --setenv TMPDIR /tmp --setenv TMP /tmp --setenv TEMPDIR /tmp \
  --setenv TEMP /tmp --tmpfs /run --tmpfs /var \
  --ro-bind /usr /usr --ro-bind /bin /bin --ro-bind /lib /lib --ro-bind /lib64 /lib64 \
  --ro-bind /etc /etc --ro-bind /opt /opt --ro-bind /home /home \
  bash
```

`gcc` is having trouble finding its sub-programs:

```sh
# Outside sandbox:
$ gcc -print-prog-name=cc1
/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/cc1
# Inside sandbox:
$ gcc -print-prog-name=cc1
cc1
```

The search paths are weird:
```sh
# Outside sandbox:
$ gcc -print-search-dirs
install: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/
programs: =/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:...lots more...
# Inside sandbox:
$ gcc -print-search-dirs
install: /bin/../lib/gcc/x86_64-redhat-linux/4.8.5/
programs: =/bin/../libexec/gcc/x86_64-redhat-linux/4.8.5/:/bin/../libexec/gcc/:...lots more...
```

I'm not sure why the search paths are different inside the sandbox, but... outside the sandbox, `/bin` is a symlink to `/usr/bin`, so `realpath /bin/../libexec` resolves to `/usr/libexec`. Inside the sandbox, `/bin` is a mount, so it resolves to `/libexec` which doesn't exist.

Changing `sandbox.sh` to do `--symlink usr/bin /bin` instead of `--ro-bind /bin /bin` fixes it, but only on platforms where `/bin` is a symlink. :/ And I don't know why gcc's search paths are different inside the sandbox; if they weren't, things would work.

GCC: `gcc-4.8.5-28.el7_5.1.x86_64` RPM
OS: `CentOS Linux release 7.5.1804` (per /etc/centos-release)
bubblewrap: 0.3.0 RPM from [here](https://centos.pkgs.org/7/epel-x86_64/bubblewrap-0.3.0-1.el7.x86_64.rpm.html)

```
# opam-version      2.0.1
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=centos os-version=7
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              23
# repositories      1 (http) (default repo at e5263e9b)
# pinned            0
# current-switch    default
```

**Comment by rjbou** [comment]
Thanks!
