### ISSUE TITLE
Opam remove -a tries to remove ocaml-config and fails

### ISSUE THREAD

**Issue by NathanReb** [ocaml/opam#3662]
It seems the `--auto-remove` option of `opam remove` does not cope very well with the new `ocaml-config` package.

This is triggered by the ocaml-ci `.travis-docker.sh` script and was first reported here: https://github.com/ocaml/ocaml-ci-scripts/issues/265
The issue contains all the details as to how to reproduce the bug.

It also looks similar to this issue: https://github.com/ocaml/opam/issues/3461

I may not understand the `--auto-remove` option very well but it seems to me that if a package can't be removed because other packages depend on it, the command shouldn't fail and simply leave the package alone since it's then not meant to be auto-removed isn't it?

**Comment by rjbou** [comment]
This is because of the switch state not updated when a base package have a new dependency. And as the autoremove relies on it to lock them...
Thanks for reporting!

**Comment by rjbou** [comment]
Update of switch-state is one of the problem, even with it, opam should have kept `ocaml-config` in the package to keep. A bug on dependencies construction (fixed in #3670) didn't included it because of cycles on the graph (`ocaml-base-compiler` ⇄ `ocaml`).
