### ISSUE TITLE
opam show -f and field names consistency

### ISSUE THREAD

**Issue by trefis** [ocaml/opam#3664]
Start from [merlin's opam file](https://github.com/ocaml/opam-repository/blob/master/packages/merlin/merlin.3.2.2/opam).
```
$ opam show merlin -f version
3.2.2
$ opam show merlin -f depends
[ERROR] No printer for "depends". Did you mean the opam field "depends:" (with a colon)?
$ opam show merlin -f depends:
"ocaml" {>= "4.02.1" & < "4.08"}
"dune" {build}
"ocamlfind" {>= "1.5.2"}
"yojson"
"craml" {with-test}
```
Is there any reason for that inconsistency? It looks like a bug to me.

**Comment by rjbou** [comment]
It have its origin on the way opam show internal (especially field detection) has been first written I think, but maybe i'm missing something.
@AltGr is there any objection to permit not having the colon at the end of fields?
At least, we must continue supporting colons for backward compat.

**Comment by rjbou** [comment]
After discussion with @AltGr, it is to differentiate computed information and raw field querying, as mentioned in `opam show` manpage: 
```
the raw value of any opam-file field can be queried by suffixing a colon character (:)
```
it is relevant for some case, e.g:
```bash
$ opam show lablgtk -f depexts
libexpat1-dev libgtk2.0-dev
$ opam show lablgtk -f depexts:
["libgtk2.0-dev" "libexpat1-dev"] {os-distribution = "debian"}
["libgtk2.0-dev" "libexpat1-dev"] {os-distribution = "ubuntu"}
["gtk" "expat"] {os-distribution = "homebrew" & os = "macos"}
["gtk2-devel"] {os-distribution = "centos"}
["gtk2-devel"] {os-distribution = "fedora"}
["gtk2-devel"] {os-distribution = "ol"}
["gtk+2.0-dev"] {os-distribution = "alpine"}
["gtk2-devel"] {os-family = "suse"}
```

**Comment by dbuenzli** [comment]
Personnally I find that to be a bit too subtle ui-wise. Why not simply use the existing `--raw` option for that ?

**Comment by dbuenzli** [comment]
I think it's too late to change the`:` bit (possibly you could output a deprecation warning on stderr). However it would be nice to make it so that `opam show labltgk -f depexts:` and  `opam show lablgtk --raw -f depexts` lead to the same result --- at the moment using both `--raw` and `-f`  output the whole `opam` file.

**Comment by rjbou** [comment]
Yes, that's the idea about the needed/wanted modifications, as it is possible to remain backward compatible.
