### ISSUE TITLE
Should opam set PKG_CONFIG_PATH ?

### ISSUE THREAD

**Issue by emillon** [ocaml/opam#3676]
Hi,

Mirage uses pkg-config to store information about the libraries it uses. For example, `ocaml-freestanding` installs [this pkg-config file](https://github.com/mirage/ocaml-freestanding/blob/6e495bc5c9b80b4483c8123e6246dcd88790afec/ocaml-freestanding.pc.in) into `$(opam config var lib)/pkgconfig`. This is next queried by some packages by setting the `PKG_CONFIG_PATH` [like so](https://github.com/mirage/checkseum/blob/97b2de7009b1fc2005646ef36e29c7e99e1c5b5a/src-c/native/freestanding/cflags.sh).

We're trying to make this pattern more integrated with dune (see ocaml/dune#1492 and ocaml/dune#1553), but for the `PKG_CONFIG_PATH` part it would be great if opam could set this environment variable in `opam config env` and when building packages.

What do you think?

I can contribute a PR but I'm not too sure where to add this in `opamEnv.ml`. Would `compute_updates` be a good place for this?

Thanks!

**Comment by dra27** [comment]
I don’t think this needs a patch in opam - can’t it be done with setenv in the conf-pkg-config package?

**Comment by emillon** [comment]
Ah, I didn't know about this mechanism. It looks like it could work, but there does not seem to be any package (other than compilers) using this. I'll check whether that works.

**Comment by emillon** [comment]
I don't think we'll need to patch opam in the end - @thelortex has found a nice way to do that without pkg-config in mirage/mirage#969. Thanks!
