### ISSUE TITLE
opam install pkgs gcc error

### ISSUE THREAD

**Issue by colin4124** [ocaml/opam#3686]
When `opam install pkgs` , it output gcc error as below:

```
gcc: error: /bin/../lib/gcc/specs: Is a directory
```

It looks like mount symbol link problem as https://github.com/ocaml/opam/pull/3661

I have use this patch but failed, my report as below

```
# opam config report
# opam-version      2.0.0 (c38db3e180a4188a60f7ee93b2c6ddcba019238a) 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=aosc os-version=5.3.2
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              3
# repositories      1 (http) (default repo at 77c49895)
# pinned            1 (git)
# current-switch    default
```

My file system symbol link as below:

![tmp](https://user-images.githubusercontent.com/1255176/49386317-3f8b2100-f75a-11e8-889e-d87f5f74e3c1.png)

**Comment by rjbou** [comment]
Your use case should have been handled by this patch, regardless to how the path  is resolved (relative path first or symlink). Plus, as in the script `/usr` is mounted before `/bin` and `/lib`, bwrap have no problem to link them. 

As I see, you have a git-installed opam. After updating opam, you need to run an `opam init --reinit -n` to be sure that your installed sandbox script is updated too. You can check the installed and opam used version of sandbox script at `~/.opam/opam-init/hooks/sandbox.sh`.

**Comment by colin4124** [comment]
Thanks very much! I have reinstall after I have installed release version from git, so I run `opam init` agin it works. Thanks again. ^_^
