### ISSUE TITLE
opam --locked does not correct the version of already-installed packages

### ISSUE THREAD

**Issue by jvillard** [ocaml/opam#3694]
Consider for instance [this opam.locked](https://github.com/facebook/infer/blob/ed82a0e572a453870c228e1b27eaa3927f9e38af/opam.locked) file. I would expect opam to downgrade javalib in this scenario (since the file specifies version 2.3.5) but it doesn't:

```console
$ opam install --deps-only --locked infer .
[starting in an empty switch, this installs all the dependencies at the correct version]
$ opam upgrade
...
  ↗ upgrade   javalib     2.3.5 to 3.0
  ↗ upgrade   sawja       1.5.4 to 1.5.6
...
$ opam install --deps-only --locked infer .
Nothing to do.
$ # javalib has not been downgraded to 2.3.5
$ opam show javalib --field=version 
3.0
```

**Comment by AltGr** [comment]
This indeed appears to be a bug. What I think probably happens is that `--locked` is not correctly taken into account if the package is already pinned (which it was after the first `install` command).

We'll look into it, thanks for reporting!

**Comment by AltGr** [comment]
To confirm, does the following workaround work for you ?
- before the second `opam install` command, run `opam unpin -n infer`

**Comment by jvillard** [comment]
It reports `[NOTE] infer is not pinned.`.

**Comment by rjbou** [comment]
Didn't noticed it at first look, but there is just a confusion about the `--locked` option: it can be set with or without argument, in this latter the argument is the suffix for the locked file (default `.locked`).
In your commands, you use the `--locked`, then name the package to install `infer`, but what is interpreted by opam is that you set the new lock file suffix as `infer`.
That's also why there is a different behaviour between cited `opam.locked` and master's one ; at the end, installed packages are only based on the `opam` file and as javalib `<3.0` restriction was added...
Just moving `--locked` to makes it with no argument really install locked packages (e.g. from [this state/commit](https://github.com/facebook/infer/commit/ed82a0e572a453870c228e1b27eaa3927f9e38af)):
```
$ opam install --deps-only infer  .  --locked
The following actions will be performed:
  ↘ downgrade javalib  3.0 to 2.3.5
  ↘ downgrade dune     1.6.2 to 1.5.1
  ↘ downgrade cmdliner 1.0.3 to 1.0.2
  ↘ downgrade sawja    1.5.6 to 1.5.4 [uses javalib]
  ↻ recompile jbuilder transition     [uses dune]
  ↘ downgrade base64   2.3.0 to 2.2.0
===== ↻ 1   ↘ 5 =====
Do you want to continue? [Y/n] 
```

I'll keep this issue open, it worth adding some doc about it!

**Comment by jvillard** [comment]
Woah, so some options can have either 0 or 1 argument and for these their position on the command line changes the way they are interpreted, I find that pretty scary in general :) Should the other behaviour be made into its own option, e.g. `--locked-suffix`? Anyway, that's a different and more debatable issue, thanks for getting to the bottom of this!

**Comment by dra27** [comment]
This behaviour is "normal" GNU-style option behaviour, I think - can't it also be solved in a more standard way by using `--`, i.e. `opam install --deps-only --locked -- infer .`?

**Comment by AltGr** [comment]
Note that this is all implemented by the [`cmdliner`](http://erratique.ch/software/cmdliner) library, which indeed follows the GNU style. The `--` should also work, but indeed, in this case it can otherwise get confusing and `--locked-suffix` sounds like a better design (I don't think anyone has been using custom suffixes yet, so it is probably still time to change it).

**Comment by dbuenzli** [comment]
To be fair to the [GNU guidelines](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html) they force using `=` to specify values to *long* options. These in turn are the only options which are allowed to have *optional* values (see the next to last paragraph). 

`Cmdliner` though allows to specify the option value without the `=` and allows them to be optional aswell which greatly increases the ambiguity, as is witnessed here, so maybe options with optional values are best avoided. The syntax implemented by cmdliner can be found [here](http://erratique.ch/software/cmdliner/doc/Cmdliner.html#optargs).

**Comment by dra27** [comment]
@AltGr - it doesn't matter whether the option is being used or not, 2.0 is released, so changing it ceases to be possible! What might be better is to do something as Git does with ref/filename ambiguity - in the contexts where it matters, if the locked suffix is also a package name, then complain. That way users learn to change to the safer option **and** you have a change which is still compatible with any older invocations.

**Comment by jvillard** [comment]
Maybe opam could complain if `opam.<suffix>` does not exist? In my case that would have complained about "opam.infer", giving me a hint that something is wrong.

**Comment by rjbou** [comment]
@jvillard With the integration of opam-lock, `--locked` has been splitted in `--locked` && `--lock-suffix`.

**Comment by rjbou** [comment]
PR merged, closing. Thanks!
