### ISSUE TITLE
opam 2.0.2 throwing weird errors during install phase

### ISSUE THREAD

**Issue by pmetzger** [ocaml/opam#3700]
I'm trying to upgrade MacPorts to install 2.0.2. Unfortunately, I run into this during the install phase. It happens over and over:

```
cmdliner error: Undefined variable $($b,\$OPAMBESTEFFORT) in "Don't fail if all requested packages can't be installed: try to install as many as possible. Note that not all external solvers may support this option (recent versions of $(i,aspcud) or $(i,mccs) should). This is equivalent to setting $($b,\\$OPAMBESTEFFORT) environment variable."
```

(BTW, if it's not obvious, I'm the MacPorts maintainer for OCaml, and what I'm trying to do here is upgrade the MacPorts provided package. I can't ask anyone else to help me, I'm supposedly the "expert".)

**Comment by avsm** [comment]
Some more details would be useful about the build/install environment. Is MacPorts doing anything special in the install phase, such as setting some environment variables for fakeroot or similar? How was the binary compiled?

**Comment by avsm** [comment]
It might be simpler to actually do the installation during the build phase, and just copy the files over in the install phase :-)

**Comment by dra27** [comment]
@avsm - it wouldn't fix the problem, unfortunately! The issue is that some targets are unconditionally rebuilt (for development convenience)

**Comment by avsm** [comment]
So what's different from the Homebrew package then, which works?  There's clearly a workaround for this issue or else all the package managers would see it...

```
    ENV.deparallelize

    system "./configure", "--prefix=#{prefix}", "--mandir=#{man}"
    system "make", "lib-ext"
    system "make"
    system "make", "man"
    system "make", "install"
```

**Comment by dra27** [comment]
@avsm - assuming you’ve got 2.0.2 installed with homebrew, run `opam —help`, then quit the pager and see what appeared on stderr (which should be that same error message)

**Comment by avsm** [comment]
Hm, oddly enough I can't repro this with a 2.0.2 binary on my laptop, but an upgrade on my desktop does happen with `opam --help` on Homebrew as well.  I'll chalk the laptop failed repro down to some developer/upgrade hitch...

**Comment by pmetzger** [comment]
@dra27 Can you post the  patch needed to fix this? I can then have MacPorts apply it during the patch phase. Or, if 2.0.3 will be out within a few days, I can just wait for that.

**Comment by dra27** [comment]
@pmetzger - either https://github.com/ocaml/opam/pull/3706/commits/626baf53c4306221763b44c1a0b0e134eafe10fa from #3706 or https://github.com/ocaml/opam/pull/3703/commits/f0a6ae259d55de88c806530c2e71e2269907b632 from #3703.
