### ISSUE TITLE
opam system compiler changing fails to upgrade

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#3708]
With opam 2.0.2, I did a `brew upgrade` which upgraded the system compiler from 4.06.0 to 4.07.1.  The resulting system fails to upgrade however:

```
$ opam upgrade
[WARNING] File /usr/local/bin/ocamlc, which package ocaml-system.4.06.1 depends upon, was changed on your system. ocaml-system has been marked as
          removed, and will be reinstalled if necessary.
[WARNING] Upgrade is not possible because of conflicts or packages that are no longer available:
The following dependencies are the cause:
  - ocaml → ocaml-base-compiler = 4.06.1
      conflict with the base packages of this switch
  - ocaml → ocaml-system = 4.06.1
      unmet availability conditions: sys-ocaml-version = "4.06.1"
  - ocaml → ocaml-variants >= 4.06.1
      conflict with the base packages of this switch

You may run "opam upgrade --fixup" to let opam fix the current state.

The former state can be restored with:
    opam switch import "/Users/avsm/.opam/default/.opam-switch/backup/state-20181216091405.export"
yak:opam-repository avsm$ opam upgrade --fixup
[WARNING] File /usr/local/bin/ocamlc, which package ocaml-system.4.06.1 depends upon, was changed on your system. ocaml-system has been marked as
          removed, and will be reinstalled if necessary.
[ERROR] It appears that the base packages for this switch are no longer available. Either fix their prerequisites or change them through 'opam list
        --base' and 'opam switch set-base'.
The following dependencies couldn't be met:
  - ocaml → ocaml-base-compiler = 4.06.1
      conflict with the base packages of this switch
  - ocaml → ocaml-system = 4.06.1
      unmet availability conditions: sys-ocaml-version = "4.06.1"
  - ocaml → ocaml-variants >= 4.06.1
      conflict with the base packages of this switch

No solution found, exiting

The former state can be restored with:
    opam switch import "/Users/avsm/.opam/default/.opam-switch/backup/state-20181216091413.export"
yak:opam-repository avsm$ ocaml -version
The OCaml toplevel, version 4.07.1
```

**Comment by rjbou** [comment]
You changed the underlying base package requirements, i.e, `ocaml-system` that needs ocaml 4.06.1 system installed. To recover, you need to update system base packages as follow
```
$ ocamlc -vnum
4.02.3

$ opam init -ni
[...]
Done.

# update ocaml system
$ ocaml -vnum
4.07.1

$ opam upgrade #fails
[WARNING] File /usr/bin/ocamlc, which package ocaml-system.4.02.3 depends upon, was changed on your system. ocaml-system has been marked as removed, and will be reinstalled if necessary.
[WARNING] Upgrade is not possible because of conflicts or packages that are no longer available:
The following dependencies are the cause:
  - ocaml → ocaml-base-compiler = 4.02.3
      conflict with the base packages of this switch
  - ocaml → ocaml-system = 4.02.3
      unmet availability conditions: sys-ocaml-version = "4.02.3"
  - ocaml → ocaml-variants >= 4.02.3
      conflict with the base packages of this switch

You may run "opam upgrade --fixup" to let opam fix the current state.

The former state can be restored with:
    opam switch import "/tmp/rrr/default/.opam-switch/backup/state-20181219102938.export"

$ opam list --base #base is still on 4.02.3
[WARNING] File /usr/bin/ocamlc, which package ocaml-system.4.02.3 depends upon, was changed on your system. ocaml-system has been marked as removed, and will be reinstalled if necessary.
# Packages matching: base
# Name        # Installed # Synopsis
base-bigarray base
base-threads  base
base-unix     base
ocaml         4.02.3      The OCaml compiler (virtual package)
ocaml-config  1           OCaml Switch Configuration
ocaml-system  --          The OCaml compiler (system version, from outside of opam)

# install correct ocaml packages
$ opam install ocaml.4.07.1 ocaml-system.4.07.1 --yes --unlock-base 
[WARNING] File /usr/bin/ocamlc, which package ocaml-system.4.02.3 depends upon, was changed on your system. ocaml-system has been marked as removed, and will be reinstalled if necessary.
The following actions will be performed:
  ∗ install   ocaml-system 4.07.1
  ↻ recompile ocaml-config 1                [uses ocaml-system]
  ↗ upgrade   ocaml        4.02.3 to 4.07.1
===== ∗ 1   ↻ 1   ↗ 1 =====

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⊘ removed   ocaml.4.02.3
⊘ removed   ocaml-config.1
∗ installed ocaml-system.4.07.1
∗ installed ocaml-config.1
∗ installed ocaml.4.07.1
Done.

# set them as base packages
$ opam sw set-base ocaml.4.07.1 ocaml-system.4.07.1 ocaml-config --yes

$ opam list --base
# Packages matching: base
# Name       # Installed # Synopsis
ocaml        4.07.1      The OCaml compiler (virtual package)
ocaml-system 4.07.1      The OCaml compiler (system version, from outside of opam)

$ opam upgrade
Already up-to-date.
Nothing to do.
```

`--fixup` is for package installation, not handling compiler / base packages inconsistency.

**Comment by avsm** [comment]
Thanks for the workaround; very useful! This used to work on opam 1.2.2 though, so it would be really nice if opam could work automatically with a system compiler upgrade, or otherwise direct the user as to how to fix the issue.

**Comment by avsm** [comment]
Is it possible to get this workaround into a release of opam soon-ish?  When OCaml 4.08.0 is out, this will affect a lot of users. The `opam install ocaml.4.07.1 ocaml-system.4.07.1 --yes --unlock-base` works great, but is almost impossible to figure out if @rjbou hadn't described it above :-)

**Comment by rjbou** [comment]
Yup! Next one should be the alpha of 2.1.0 :D

**Comment by avsm** [comment]
Awesome :-)

**Comment by RalfJung** [comment]
With ocaml 4.08 landing in Debian, I am now affected by this problem as well. The adjusted version of the work-around is
```
opam install ocaml.4.08.1 ocaml-system.4.08.1 --yes --unlock-base
```

**Comment by FroggMaster** [comment]
Experienced same issue in Manjaro with ocaml 4.09.0
Solution was as follows:
```
#Installing Correct Packages
opam install ocaml.4.09.0 ocaml-system.4.09.0 --yes --unlock-base

#Setting Base
opam sw set-base ocaml.4.09.0 ocaml-system.4.09.0 ocaml-config --yes
```

**Comment by XVilka** [comment]
Shouldn't be this one closed by the https://github.com/ocaml/opam/pull/3894?

**Comment by rjbou** [comment]
Indeed ! Thanks!

**Comment by vedgar** [comment]
I don't know whether this should be closed, but I seem to have the same problem.

✦ ❯ opam install ocaml.4.09.0 ocaml-system.4.09.0 --yes --unlock-base
[WARNING] File /usr/bin/ocamlc, which package ocaml-system.4.05.0 depends upon,
          was changed on your system. ocaml-system has been marked as removed,
          and will be reinstalled if necessary.
[ERROR] ocaml-system = 4.09.0 unmet availability conditions: sys-ocaml-version
        = "4.09.0"

**Comment by rjbou** [comment]
What version of opam do you use?

**Comment by vedgar** [comment]
2.0.7

**Comment by rjbou** [comment]
It is fixed in opam `2.1.0~alpha`

**Comment by klartext** [comment]
File /usr/bin/ocamlc, which package ocaml-system.4.10.0 depends upon, was changed on your system. ocaml-system has been marked as removed, and will be reinstalled if necessary.

opam 2.0.7

**Comment by goderich** [comment]
I was affected by the same problem as @klartext with the same opam version number.
Running `opam install ocaml.4.11.1 ocaml-system.4.11.1  --yes --unlock-base` solved the issue.

**Comment by RalfJung** [comment]
> It is fixed in opam `2.1.0~alpha`

Is there any estimation of when there will be a stable relase of the 2.1 series? All my switches are broken again due to this; the command given by @goderich helps.

**Comment by dra27** [comment]
We’re finalising beta4 this week (it’s actually the third beta, but there were some tarballs of beta2 which reported beta3, so we bumped it to 4 for unambiguous reports!).

There are a few decisions after that as to things which need to fixed before finalising the release, but we’re expecting to move to a release candidate in mid-January, rather than having another beta.

**Comment by Alyko** [comment]
I have the same problem : I can't upgrade ocaml from 4.08.1 to 4.11.1
The command `opam install ocaml.4.11.1 ocaml-system.4.11.1 --yes --unlock-base` returns 
`[ERROR] ocaml-system = 4.11.1 unmet availability conditions: sys-ocaml-version = "4.11.1"`

I tried a few things :
- I upgraded opam to version `2.1.0~beta4` using opam-devel (with `opam pin add opam-devel --dev` and 
`cp /home/paul/.opam/default/lib/opam-devel/opam /usr/local/bin`). At this point I tried 
`opam install ocaml.4.11.1 ocaml-system.4.11.1 --yes --unlock-base` again and I got a different error : 
`opam: unlock-base was removed in version 2.1 of the opam CLI, but version 2.1 has been requested. Use --update-invariant instead or set OPAMCLI environment variable to 2.0.`
- I set the OPAMCLI variable in opam to `2.0` but I still get the same error message.
- I tried replacing `--unlock-base` with `--update-invariant` :
when I run `opam install ocaml.4.11.1 ocaml-system.4.11.1 --yes --update-invariant` 
I still get `[ERROR] ocaml-system = 4.11.1 unmet availability conditions: 'sys-ocaml-version = "4.11.1"'`

Any help would be much appreciated

**Comment by kit-ty-kate** [comment]
@Alyko could you confirm that the ocaml compiler installed on your system is ocaml 4.11.1? `ocamlc -version`

**Comment by Alyko** [comment]
The compiler is still 4.08.1
Do I need to upgrade the compiler first?

**Comment by kit-ty-kate** [comment]
Then the error is expected. opam is telling you that OCaml 4.11.1 hasn't been found. System compiler will get upgraded automatically as your distribution upgrades it.
However, if you want OCaml 4.11.1 but your distribution doesn't have it yet, you can just create a new switch as follow:
```
opam switch create 4.11 4.11.1
```

I'm curious, where did you get the `opam install ocaml.4.11.1 ocaml-system.4.11.1 --yes --unlock-base` command from?

**Comment by Alyko** [comment]
I found it on this issue : [https://github.com/ocaml/opam/issues/3708](url)

**Comment by rjbou** [comment]
@Alyko this issue and its solution is for updating opam compiler packages when system compiler packages changes (by system package manager upgrade). For handling different ocaml compilers, you can see [`switch`](https://opam.ocaml.org/doc/Usage.html#opam-switch) documentation. And if you just want to update your current switch compiler, you just need to install the `ocaml` package in the desired version : `opam install ocaml.4.11.1` (you'll need to `--update-invariant` if there is incompatible one set).

**Comment by RalfJung** [comment]
@Alyko the command needs to be adjusted to your system compiler version.  So for you it would probably be `opam install ocaml.4.08.1 ocaml-system.4.08.1 --yes --unlock-base`. That's why you can find multiple commands given in this issue.

**Comment by Alyko** [comment]
Thank you @rjbou, the command `opam install ocaml.4.11.1 --update-invariant` worked. You really saved me there.
@RalfJung, as for your solution, the command `opam install ocaml.4.08.1 ocaml-system.4.08.1 --yes --unlock-base` still failed because of the `--unlock-base`. Since in this issue [https://github.com/ocaml/opam/issues/3708](url) people still mentioned using `opam install ocaml.4.11.1 ocaml-system.4.11.1 --yes --unlock-base` as early as september of 2020 (latest version of ocaml was 4.11.1) and I thought they needed to upgrade to the latest version like me so I used that command. My bad.
Thanks a lot to both of you.
