### ISSUE TITLE
Upload opam-2.0.2-x86_64-darwin

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocaml/opam#3710]
Currently [all CI builds](https://github.com/ocaml-community/yojson/issues/70) on macOS fail because the [CI scripts expect opam-2.0.2-x86_64-darwin to exist](https://github.com/ocaml/ocaml-ci-scripts/issues/279) and I think for now the least effort solution would be to just upload it while the rest is being fixed.

**Comment by rjbou** [comment]
We harmonised and switched to `macos` naming on binaries and scripts. For the moment, we make them both available, and soon only `macos` will be uploaded.
`ocaml-ci-scripts` have alreayd been updated accordingly (cf. ocaml/ocaml-ci-scripts/pull/282)
