### ISSUE TITLE
about opam version update

### ISSUE THREAD

**Issue by kypiching** [ocaml/opam#3712]
Hi, guys.

I want ask a stupid quesion.

how to update `opam` **itself** version use **opam**?

thanks.

**Comment by rjbou** [comment]
If you want to update opam using opam, you can use package `opam-devel`, as described [here](http://opam.ocaml.org/doc/FAQ.html#How-to-get-install-and-upgrade-opam) (after having updated repository).

**Comment by kypiching** [comment]
**Thanks** @rjbou 
One more ask.

Does it work right when i directly upgrade `opam` binary?

I changed `opam` binary version to `2.0.1` from `1.**` has some problem.
`Opam` can not `update` & `upgrade` working as normal.

I deleted `.opam` directory and reinstall all i needed package from `opam 2.0.1` to solve that.

I want choose a **right way** to upgrade `opam` version.

**thanks**.

**Comment by rjbou** [comment]
On first launch, opam.2.0.x proposes to update your opam root from 1.2 format to 2.0 one before doing any operation.
Do you remember what was the errors you encountered?

**Comment by kypiching** [comment]
Many days ago. I already forgot that message.
Using `opam-2.0.2` now.
This time directly update `opam` binary file.
It's working normal for now.

**Comment by rjbou** [comment]
Great!
