### ISSUE TITLE
Fatal error on `opam switch create .` with an unknown compiler

### ISSUE THREAD

**Issue by lpw25** [ocaml/opam#3713]
I've been trying to add some opam files to the ocaml compiler to allow the compiler to be pinned easily (https://github.com/ocaml/ocaml/pull/2207). They work if I do:
```bash
$ opam switch create . --empty
$ opam install .
```
but if I instead try:
```bash
$ opam switch create .
```
which I was hoping would do the same thing, and also mark the compiler package as a "base" one, then I get:
```bash
(W)CudfAdd: package ocaml-variants (= 18) is not associate with an integer in the given universe
Fatal error:
Not_found
```

**Comment by rjbou** [comment]
Creating a local switch directly with a local compiler is not handled by opam. What happens is that at a first step opam finds the local compiler, adds it as a base compiler to install in current switch, but afterwards, during availability check based on repo compilers, it doesn't find it, and fails.
I'll update the title accordingly.
Thanks for reporting!
