### ISSUE TITLE
opam show on files is slow

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#3721]
```
> opam --version
2.0.2
> time opam show ./cmdliner.opam --normalise --no-lint --field=authors:,bug-reports:,depends:,dev-repo:,doc:,homepage:,license:,maintainer:,synopsis:,tags:,version: > /dev/null

real	0m0.223s
user	0m0.154s
sys	0m0.060s
```
I guess some stuff must be going on to enable evaluation with respect to the current repo/switch. But I'm really interested in the raw fields like `opam-query` gave us. Would it maybe be possible to add an option that skips unneeded setup ?

**Comment by rjbou** [comment]
Indeed, the switch is loaded to retrieve all information about the package in the current (and other) switch, then it is given to the printer, which applies filters. Even for local opam files, we need that switch loading for information like `all_versions`, `all_installed_versions`, etc.

There is the deprecated option `--file`, that doesn't load the switch
```
       --file=FILE
           DEPRECATED: use an explicit path argument as package instead. Get
           package information from the given FILE instead of from known
           packages. This implies --raw unless --fields is used. Only raw
           opam-file fields can be queried.
```
Can be interesting to add an option for light querying.

**Comment by dbuenzli** [comment]
Thank you !
