### ISSUE TITLE
Cygwin setup opam version

### ISSUE THREAD

**Issue by pela9** [ocaml/opam#3739]
It seems that new compiler switches and packages can only be fetched with opam version >= 2.0, but the cygwin package manager (setup-x86_64) only provides 1.2.2. I therefore humbly hope for an upgrade of the opam cygwin package. (I tried to compile latest version of opam myself from sources but got the dreaded flexlink error telling me that the unix module could not be loaded.)

**Comment by rjbou** [comment]
opam can now be built from cygwin setup (cf. https://github.com/ocaml/opam/issues/3503#issuecomment-533828877).
Thanks for the report!
