### ISSUE TITLE
release 2.0.3 missing their full tarball now :/

### ISSUE THREAD

**Issue by hannesm** [ocaml/opam#3740]
earlier https://github.com/ocaml/opam/releases/download/2.0.3/opam-full-2.0.3.tar.gz was available, it is no longer
```
SHA256 (opam-full-2.0.3.tar.gz) = 0589da4da184584a5445d59385009536534f60bc0e27772245b2f49e5fa8f0e2
SIZE (opam-full-2.0.3.tar.gz) = 7870020
```

any chance to re-instantiate that tarball?

**Comment by rjbou** [comment]
Yup! It will be back as soon as we can. Thanks for notifying!

**Comment by rjbou** [comment]
Full archive is back!
