### ISSUE TITLE
`opam admin make $PACKAGES` with opam 2

### ISSUE THREAD

**Issue by vsiles** [ocaml/opam#3755]
Hi !
I'm trying to port an offline install script from 1.2 to 2.0.
In the original script, a tgz from ocaml-repository is downloaded and then opam.tar.gz files are fetched using `opam admin make pkg-name1 ... pkg-nameN`.

I could not found an equivalent command in opam2. `opam admin make` no longer accepts package names and only create the url file.

Is there a way to emulate the 1.2 behavior in 2.0+ or should I look to other solutions (opam-bundle maybe ? something else ?)

Best,
V.

**Comment by rjbou** [comment]
This option is no more available in opam2. You can reproduce this behavior by using `opam admin filter` option to keep on the repository only selected packages, and then do the `opam admin make`.

**Comment by vsiles** [comment]
Thanks, I'll try with that !

**Comment by AltGr** [comment]
`opam admin make` is deprecated, and now just an alias, since it had quite uncear meaning: please use `opam admin index` and `opam admin cache` instead (which generate the index and cache, respectively).
