### ISSUE TITLE
opam-admin: allow to select only a subset of packages 

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#3767]
When editing/fixing the main opam-repository, it's very common to edit a few opam files explicitely. Using `opam-admin` to add hashes or constraints in that case is not very convenient as all the opam files in the repo will be scanned and updated (and in the case of `add-hashes` it will download all the archives as well).

So it would be great to allow to pass package names on the command-line as anonymous argument (or if not possible with a `-p <pkg-name>` argument).

**Comment by rjbou** [comment]
Thanks for reporting!

**Comment by Drup** [comment]
@rjbou thank *you* for implementing, this is very useful! :)
