### ISSUE TITLE
opam-lock does not include dependencies marked as {dev}

### ISSUE THREAD

**Issue by hcarty** [ocaml/opam#3769]
If a dependency is marked with `{dev}` in `project.opam` then it is not carried over to `project.opam.locked` by `opam lock project.opam`.

opam 2.0.3 and opam-lock 0.2

**Comment by rjbou** [comment]
Added in the PR (commits https://github.com/ocaml/opam/pull/3746/commits/28432f98041d7ab0bafc0ca2c96c0169e6ccbcf4 & https://github.com/ocaml/opam/pull/3746/commits/963454ca8d4171675bd151338ea0fca0ee92e586). Indeed it was missing, as for `{with-test}` & `{with-doc}`.
Thanks for the report!

**Comment by hcarty** [comment]
Thanks!
