### ISSUE TITLE
opam ignores PKG_CONFIG_PATH ?

### ISSUE THREAD

**Issue by vsiles** [ocaml/opam#3770]
```
PKG_CONFIG_PATH=/path/to/custom/pc/files opam reinstall pcre
```

The above commands ignores `PKG_CONFIG_PATH`: if I build pcre by hand invoking dune with/without setting `PKG_CONFIG_PATH`, I get the `pcre.cmxa` I want. However if I try to install the package via opam, my `PKG_CONFIG_PATH` is ignored.

Is there a way to set `PKG_CONFIG_PATH` to a user defined value when installing a package with opam ?

**Comment by vsiles** [comment]
Some intend of what I'm trying to do: by default `pcre` will try to link with what pkg-config outputs, which is the system lib. In my case, I can't update this lib (no sudo access) and the system lib is buggy. So I compiled one locally and I'd like pkg-config to output the correct location (the `-L/path/to/my/pcre/lib` part).

**Comment by vsiles** [comment]
the issue is that `PKG_CONFIG_PATH` points to a directory which is not exported through bwrap. Is there a known way to add some directories to the bwrap command without touching sandbox.sh manually ?

**Comment by rjbou** [comment]
You can use the environment variable `OPAM_USER_PATH_RO` to add directories to read-only mount on the sandbox script (cf. [bwrap faq entry](https://opam.ocaml.org/doc/FAQ.html#Why-does-opam-require-bwrap)).

**Comment by vsiles** [comment]
Thanks a lot, that's helping !
