### ISSUE TITLE
Searching for gcc inside the bwrap sandbox on NixOS

### ISSUE THREAD

**Issue by umazalakain** [ocaml/opam#3773]
I was trying to get mirage built on NixOS, but opam had trouble finding cc/gcc. `opam config env` declares a `PATH` containing the directory `/home/uma/.nix-profile/bin`, where both cc and gcc can be found in form of soft links. Note that neither cc or gcc are found in standard locations on NixOS.

The the sandbox does not mount the directories in `PATH`, and hence gcc/cc are not found. Bypassing the sandbox compiles mirage successfully. 

```
# opam config report
# opam-version      2.0.2
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=nixos os-version=19.09pre171786.34aa254f9eb
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              3
# repositories      2 (http) (default repo at 2b5f8b6c)
# pinned            0
# current-switch    4.07.1
```

**Comment by umazalakain** [comment]
As per the comments on `sandbox.sh`, unusual paths can be added via the `OPAM_USER_PATH` env var. It might be worth mounting ro all the directories in `PATH` though.

**Comment by tg-x** [comment]
Nix sets this already in the `opam` wrapper for `2.0.2`:
https://github.com/NixOS/nixpkgs/blob/f6414428ede349733f2326f3a000cff9ed570d77/pkgs/development/tools/ocaml/opam/default.nix#L107

**Comment by rjbou** [comment]
Closing this one, feel free reopen if needed. Thanks!
