### ISSUE TITLE
Permission denied when using opam publish with Github

### ISSUE THREAD

**Issue by jserot** [ocaml/opam#3774]
When trying `opam publish`, i get the following error message:
```
$ opam publish http://cloud.ip.uca.fr/~serot/rfsm/dist/rfsm-source.tar.gz .

The following will be published:
  - rfsm version 1.4 with opam file at /Users/jserot/Dev/ml/rfsm/working/rfsm.opam
    archive at http://cloud.ip.uca.fr/~serot/rfsm/dist/rfsm-source.tar.gz


Continue ? You will be shown the patch before submitting. [Y/n] Y
Cloning the package repository, this may take a while...
+ /opt/local/bin/git "clone" "git@github.com:ocaml/opam-repository.git" "/Users/jserot/.opam/plugins/opam-publish/repos/ocaml%opam-repository"
- Cloning into '/Users/jserot/.opam/plugins/opam-publish/repos/ocaml%opam-repository'...
- Warning: Permanently added the RSA host key for IP address '192....' to the list of known hosts.
- Permission denied (publickey).
- fatal: Could not read from remote repository.
- 
- Please make sure you have the correct access rights
- and the repository exists.
```
I got this message from the github server after having entered my id and pwd when at the first run of `opam publish`:

`
A personal access token (opam-publish access token (xxx.local)) with public_repo scope was recently added to your account.`

Am i missing sth ?

**Comment by rjbou** [comment]
As the PR is filled using the ssh connection, it need your ssh keys already registered in github (cf.  https://github.com/ocaml/opam-publish/issues/22). Is it your case?

**Comment by jserot** [comment]
How do i know that my ssh keys are registered in github ?

**Comment by rjbou** [comment]
You can see that in your settings, [SSH and GPG keys](https://github.com/settings/keys) item. You'll find more documentation in [this github help](https://help.github.com/en/articles/connecting-to-github-with-ssh).

**Comment by AltGr** [comment]
I guess that, since we get a token, we could use that instead of ssh for submitting the PR: it's indeed counter-intuitive for the ones who don't have their ssh keys already registered...

**Comment by jserot** [comment]
I've regenerated ssh keys and registered in github. 
Seems to work now : `https://github.com/ocaml/opam-repository/pull/13701`

I agree with AltGr that the current mechanism using ssh keys is bit confusing since the initial message about "personal access tokens" seems to imply that authorizations have been set up correctly.
Maybe this should be stated more clearly in the doc ?

Anyway, thanks for the help.

I guess that the rest of procedure is the same that when using "manual" publishing in opam 1.2 (the merge has to be accepted), isn't it ?

**Comment by rjbou** [comment]
> Maybe this should be stated more clearly in the doc ?

Right! I'll add it in the readme


> I guess that the rest of procedure is the same that when using "manual" publishing in opam 1.2 (the merge has to be accepted), isn't it ?

Yes, it's remain same process for acceptance
