### ISSUE TITLE
Opam can create partially initialized repositories and doesn't warn

### ISSUE THREAD

**Issue by Khady** [ocaml/opam#3789]
When opam initializes a repository, it can get interrupted. After it happens, opam doesn't say anything about it. It doesn't remove the newly created repository. And another initialization doesn't make an update of the repository to make sure it is complete.

Here is a simple example to reproduce. The switch creation must get interrupted while `Processing  1/1: [mirror: git]` is displayed.

```
$ export OPAMROOT=/tmp/opam
$ opam init --bare
$ opam sw -y --repositories mirror=git+https://github.com/ocaml/opam-repository.git create . 4.07.1
Creating repository mirror...
[ERROR] User interruption
```

Then running the switch creation again, opam doesn't complain about the repo being only partially initialized. But it will fail because it doesn't know the ocaml version of because it thinks one of the dependencies of the opam packages in the current directory don't exist.

```
$ opam sw -y --repositories mirror=git+https://github.com/ocaml/opam-repository.git create . 4.07.1
```

**Comment by rjbou** [comment]
Indeed, opam should clean up the non fully initialized repository. Seems that user interruption don't propagate cleaning continuation.
Thanks for the report!

**Comment by rjbou** [comment]
With the new archive-based repository, the issue is handled by #3861.

Thanks for the report!
