### ISSUE TITLE
option name -j defined twice

### ISSUE THREAD

**Issue by qjnr** [ocaml/opam#3804]
Fresh install of Opam on openSUSE Tumbleweed.
Getting the following error whenever I run `opam init`.
```
Fatal error:
Invalid_argument("option name -j defined twice (doc strings are 'Number of jobs to use when building packages.' and 'Set the maximal number of concurrent jobs to use. You can also set it using the $(b,\\$OPAMJOBS) environment variable.')")
```
Couldn't find anything about it on the internet. Please help!

**Comment by avsm** [comment]
I've transferred this issue to the ocaml/opam repository.

**Comment by rjbou** [comment]
I suppose that you have installed opam 1.2.2, it has been fixed in opam.1.3 (cf . #218). But from [repology](https://repology.org/project/opam/packages), I see that openSUSE provides opam 2.0.3.
Can you share opam version?

**Comment by qjnr** [comment]
Sorry for the late reply, my opam version is indeed 2.0.3. I have no idea why (I think system update) but everything just seems to work now. Thank you.
