### ISSUE TITLE
`opam update --working-dir <pkg>` does not update from working state

### ISSUE THREAD

**Issue by Isweet** [ocaml/opam#3807]
I have a package that I have pinned on a local git repository. I am trying to test an update to the OPAM file. I edited the `.opam` file and ran:

```
% opam update --working-dir affixLib
```

where `affixLib` is the name of the package. The output is:

```
$ opam update --working-dir affixLib

<><> Synchronising development packages <><><><><><><><><><><><><><><><><><><><>
[NOTE] Ignoring uncommitted changes in /home/ian/Projects/affix (`--working-dir' not active).
[affixLib.~dev] no changes from git+file:///home/ian/Projects/affix#iss30-maintenance
```

I'm not sure if maybe I'm doing something wrong. I have also confirmed that the update does not work since `opam info affixLib` gives information based on the `.opam` file currently on the last commit in git.

Here's my `opam config report` in case it is helpful:

```
# opam config report
# opam-version      2.0.3 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=ubuntu os-version=18.04
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              4
# repositories      1 (http) (default repo at 854dbae2)
# pinned            2 (git)
# current-switch    affix
```

**Comment by rjbou** [comment]
`working-dir` was not propagated to the update function. Thanks for reporting!

**Comment by voodoos** [comment]
Is this supposed to be fixed ?
I observe a similar behavior on opam `2.1.3` (on macos):

```
❯ opam update --working-dir

<><> Updating package repositories ><><><><><><><><><><><><><><><><><><><><>  🐫 
[default] synchronised from https://opam.ocaml.org

<><> Synchronising development packages <><><><><><><><><><><><><><><><><><>  🐫 
[NOTE] Ignoring uncommitted changes in /Users/ulysse/tmp/dune (`--working-dir' not active).
```

**Comment by rjbou** [comment]
The initial issue is fixed, ie `opam update --working-dir dune` works. But there is a bug when no package is given, could you open a separate issue?
