### ISSUE TITLE
`make compiler` always rebuild ocaml

### ISSUE THREAD

**Issue by vsiles** [ocaml/opam#3810]
Hi !
I'm using `make compiler` before issuing the `./configure && make && ...` sequence so I don't need pre-installed ocaml. I recently saw that if I run `make compiler` twice in a row, the bootstrap ocaml is built two times. Can't we check for some dependency to decide it's ok not to build it again ?

**Comment by dra27** [comment]
The `make cold` stuff is only there to allow getting to an opam from sources with as few dependencies as possible so that you can run `opam init`. I extended it a lot as it was useful to me on Windows... you may need to do similar for this!
