### ISSUE TITLE
Add an opam field to specify the opam `.install` location

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#3820]
Currently opam reads its `.install` file by convention from the root directory of the distribution. But this file is often *generated* and I think it would be nice to be able to specify its location in the `opam` file via an `install-file:` field. 

This would make our `.gitignore`s and `make clean` procedures simpler.

**Comment by rjbou** [comment]
Duplicated with #3880. Thanks!

**Comment by dbuenzli** [comment]
Uuuh sorry about that 👴.
