### ISSUE TITLE
Add —packages option to opam exec

### ISSUE THREAD

**Issue by Khady** [ocaml/opam#3823]
Now opam has built in support for lock files. It is great. But there is no convenient way to run a command in a context that for sure respects the constraints of an opam (or opam.locked) file.

For now we have to do

```
opam install ./my_project.opam ./second_project.opam --deps-only --locked
opam exec -- dune build
```

Instead it would be nice to have a single command that at least makes sure that the switch and an opam file are matching. 

```
opam exec --packages=./my_package.opam,./second_project.opam --locked -- dune build
```

**Comment by rjbou** [comment]
This option would allow install the package and execute the command given this install? Or just check that dependencies specified in the opam file are installed?

Note that if you local opam file contains those build commands, you can use  [`--inplace-build`](https://opam.ocaml.org/doc/man/opam-install.html#lbAG) option to build in the local directory and not in the opam internal build directory.

**Comment by Khady** [comment]
I would already be very happy with "just check that dependencies specified in the opam file are installed".

Unfortunately --inplace-build is not powerful enough for our use case as we have different commands we want to run in the context of one (or multiple) opam file, not only a build command.

**Comment by rjbou** [comment]
From my point of view, it's not the purpose of `opam exec` to perform switch & package checking, especially if it have to handle all the logic of the filtering and opam file selection. It is intended to act on the field of opam/shell environment.
For check purpose, it is possible to add an `install` option, but it won't resolve the problem of two commands to launch.
One solution, is to resolve this at a shell level, or with a plugin that merges the two commands.

cc @AltGr

**Comment by Khady** [comment]
> to resolve this at a shell level

Do you mean to create a shell script that launches the two commands?

My problem with that is how slow `opam install` is, even when using lock files. Close to 2 seconds to check that there is nothing to do.

**Comment by rjbou** [comment]
You can launch the install command with `--debug` to find what is the time consuming operation. Maybe the solver?

You can combine `opam show`& `opam list` to see if a depends package is missing (without calling solver), depending on how you combine them, you can gain some little time (for me 0.5s).

**Comment by rjbou** [comment]
There is now the option `opam install --check` (#3854) without calling the solver, that permit to save some time.
Thanks for the report!
