### ISSUE TITLE
opam v1.1.1 ERROR

### ISSUE THREAD

**Issue by nwuli** [ocaml/opam#3829]
OPAM has already been initialized.[ERROR] Your version of OPAM (1.1.1) is not recent enough to read ~/.opam/config. Upgrade OPAM to a more recent version (at least 2.0) to read this file correctly.

**Comment by dra27** [comment]
Not the most comprehensive of bug reports! It looks like you have been using opam 2.0 and somehow managed to revert to an old `opam` binary?

**Comment by nwuli** [comment]
when i install the opam(v1.1.1) on  ubutun 14.04.1(i3 86). it was successfully install,but when i  configure the opam  by using " opam init".it says that: OPAM has already been initialized.[ERROR] Your version of OPAM (1.1.1) is not recent enough to read ~/.opam/config. Upgrade OPAM to a more recent version (at least 2.0) to read this file correctly.  Also ,when using the  opam to install packages, there was a Fatal error: End_of_file.

**Comment by nwuli** [comment]
i had never installed the opam before

**Comment by rjbou** [comment]
opam 1.1.1 is deprecated, there is a strange, you never installed opam, and opam 1.1.1 generated you a config file for opam2.0.
Can you share the result of these commands
``
$ opam --version`
$ head ~/.opam/config
```

**Comment by dra27** [comment]
OK - at some point, *something* has initialised an opam 2.0 root in `~/.opam`, as it can't have appeared by magic! You may be get some clue by posting the output of `ls -la ~/.opam`.

Your Ubuntu installation is rather behind (14.04.6 is current in that maintenance branch) and only has 13 days of support left, so you're possibly due an upgrade regardless. Contrary to what the webpage says, you can upgrade to opam 2 using the PPA - see https://opam.ocaml.org/doc/Install.html#Ubuntu

**Comment by nwuli** [comment]
@rjbou 
following are the results:
$ opam --version
1.1.1
$ head ~/.opam/config
opam-version: "1.1.1"
repositories: "default"
jobs: 1
switch: "system"

**Comment by AltGr** [comment]
I believe the message is wrong, and must be triggered by another file being for a later version (maybe from the opam-repository).
In any case, opam 1.1 is no longer supported, you should really use 2.0 instead (or, if you absolutely need the older version, 1.2 which is closer to 1.1 in terms of interface, and still has an attached repository, although that is no longer updated).
