### ISSUE TITLE
Compiling on Windows failed with dune_local

### ISSUE THREAD

**Issue by pe200012** [ocaml/opam#3834]
Platform: Windows 10 Cygwin
Toolchain: Mingw-w64
ocaml version: 4.10.0+dev0-2019-04-23

I was running `make` command to build opam on windows from source when it gave me an error message saying:
<pre>
File "src/stdune\\list.ml", line 3, characters 0-18:
Error: Multiple definition of the type name t.
       Names must be unique in a given structure or signature.
make: *** [Makefile:30: src_ext/dune-local/_build/install/default/bin/dune.exe] エラー 2
</pre>
I went to check the `list.ml` file and found nothing useful to solve the problem.
Any solution?

**Comment by dra27** [comment]
This looks like an issue building Dune with trunk OCaml - can you try with a release version of OCaml instead?

**Comment by pe200012** [comment]
@dra27 
Trying to use `make cold` (version 4.07.1), and got a problem:
<pre>
       ocaml src/stubs/opam-putenv.exe (exit 2)
(cd _build/default/src/stubs && D:\download\system\opam\bootstrap\ocaml\bin\ocaml.exe build-putenv.ml opam-putenv.exe opam-putenv.c cc64)
Exception: End_of_file.
       ocaml src_ext/extlib/src/compat-level
</pre>

**Comment by dra27** [comment]
What did `configure` say, in particular do you have both `i686-w64-mingw32-gcc` and `x86_64-w64-mingw32-gcc`?

**Comment by pe200012** [comment]
Though I don't have the log that `configure` output, I can sure that I have only `x86_64-w64-mingw32-gcc`.

**Comment by pe200012** [comment]
<pre>
pe132@DESKTOP-0UDACSI /cygdrive/d/download/system/opam
$ ./configure
checking for ocamlc... ocamlc
OCaml version is 4.07.0
OCaml library path is C:/ocamlmgw64/lib
checking for ocamlopt... ocamlopt
checking for ocamlc.opt... ocamlc.opt
checking for ocamlopt.opt... ocamlopt.opt
checking for ocaml... ocaml
checking for ocamldep... ocamldep
checking for ocamldep.opt... ocamldep.opt
checking for ocamlmktop... ocamlmktop
checking for ocamlmklib... ocamlmklib
checking for ocamldoc... ocamldoc
checking for ocamldoc.opt... ocamldoc.opt
checking for ocamlbuild... no
checking OCaml Sys.os_type... Win32
checking for gawk... gawk
checking for compiler type... cc
checking for compiler architecture... amd64
checking for compiler system... mingw64
checking for x86_64-w64-mingw32-gcc... x86_64-w64-mingw32-gcc -O -mms-bitfields
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-w64-mingw32-gcc -O -mms-bitfields accepts -g... yes
checking for x86_64-w64-mingw32-gcc -O -mms-bitfields option to accept ISO C89... none needed
checking for i686-w64-mingw32-gcc... no
configure: WARNING: Complementary C compiler not found - opam-putenv will not be built
checking for ocamlobjinfo... ocamlobjinfo
checking for ocamlfind... no
checking for curl... curl
checking for dune... no
checking for patch... patch
checking for bunzip2... bunzip2
checking for a workable solution for ln -s... ln -s

checking for OCaml findlib package unix... not found
checking for OCaml findlib package bigarray... not found
checking for OCaml findlib package extlib... not found
checking for OCaml findlib package re... not found
checking for OCaml findlib package re.glob... not found
checking for OCaml findlib package cmdliner... not found
checking for OCaml findlib package ocamlgraph... not found
checking for OCaml findlib package cudf... not found
checking for OCaml findlib package dose3.common... not found
checking for OCaml findlib package dose3.algo... not found
checking for OCaml findlib package opam-file-format... not found
checking for OCaml findlib package mccs... not found
checking for OCaml findlib package cppo... not found
checking for g++... no
checking for c++... no
checking for gpp... no
checking for aCC... no
checking for CC... no
checking for cxx... no
checking for cc++... no
checking for cl.exe... no
checking for FCC... no
checking for KCC... no
checking for RCC... no
checking for xlC_r... no
checking for xlC... no
checking whether we are using the GNU C++ compiler... no
checking whether g++ accepts -g... no

============================================================================
Some dependencies are missing. If you are just interested in the stand-alone
'opam' binary, run 'make lib-ext' to download and include them.
============================================================================

configure: creating ./config.status
config.status: creating Makefile.config
config.status: creating src/ocaml-flags-configure.sexp
config.status: creating src/stubs/c-flags.sexp

Opam will be built WITHOUT a built-in solver

Executables will be installed in /usr/local/bin
Manual pages will be installed in /usr/local/share/man
</pre>

**Comment by pe200012** [comment]
I solved the problem. Using opam's latest released version instead of master just fixed the errors.

**Comment by dra27** [comment]
There are two problems which this highlights, thanks:

 - We need to wind the src_ext version of Dune forward to at least 1.6.0, since versions prior to this are not compatible with OCaml 4.08.0+
 - `opam-putenv` is unconditionally built on the Windows branch (I haven't checked as to whether `enabled_if` has been merged into dune yet for the `executable` stanza, though there's a workaround if not)
