### ISSUE TITLE
opam pin add should provide interactively "skip this pin-depend"

### ISSUE THREAD

**Issue by hannesm** [ocaml/opam#3840]
what I currently get from ``opam pin add yyy `pwd`#HEAD`` when the `yyy.opam` contains `pin-depends` is:

```bash
The following additional pinnings are required by caldav.~dev:
  - webmachine.dev at git+https://github.com/roburio/ocaml-webmachine.git#webdav
Continue? [Y/n] n
You can specify --ignore-pin-depends to bypass
```

what I'd like to get:
```bash
Continue or skip? [Y/s/n] s
...opam continues to install yyy...
```

otherwise I've to run the command twice and put the `--ignore-pin-depends` on commandline.

please let me know what you think about that :)

**Comment by rjbou** [comment]
Good ui point, there is less user interaction using the confirm, that can easily be bypassed by the `--yes` option to not be blocking.
Thanks for the suggestion!
