### ISSUE TITLE
Opam install should not upgrade unrelated packages

### ISSUE THREAD

**Issue by NathanReb** [ocaml/opam#3844]
Running opam install seems to upgrade unrelated packages. See the following example:
```
$ opam install yojson
The following actions will be performed:
  ∗ install yojson     1.7.0
  ↗ upgrade ppx_import 1.5 to 1.6.1
===== ∗ 1   ↗ 1 =====
```

And that even though yojson does not depend on `ppx_import` and I explicitly installed `ppx_import=1.5` beforehand.

Having a look at #3234 it seems that might be a similar issue but it seems like undesirable behaviour to me. Would it be possible to disable those "consistency fixes" with a flag if you wish to preserve this by default?

**Comment by rjbou** [comment]
If you install a given version of a package, it doesn't mean to opam to always try to keep this version. For that you can use `opam pin ppx_import 1.5`.

Concerning those concistency fixes, you can list them with [`opam reinstall --list-pending`](https://opam.ocaml.org/doc/FAQ.html#opam-is-prompting-me-to-install-or-upgrade-packages-that-I-am-not-interested-in-or-doesn-39-t-install-the-latest-version-by-default-Why-What-can-I-do) and tell opam to forget about them with `--forget-pending` option.

**Comment by NathanReb** [comment]
Thanks for your quick response!

> If you install a given version of a package, it doesn't mean to opam to always try to keep this version.

You're right it doesn't. I'm just trying to point out that this behaviour is confusing, unexpected and probably not the best suited default.

The `--forget-pending` option is only available to `opam reinstall` so it doesn't really help in this case unless I'm missing something.

Pinning will do the trick but it still feels odd to have to use a work around here when all I wanted was to install a package without it having the side effect of upgrading something unrelated to my request.

**Comment by AltGr** [comment]
Indeed, opam _normally should not_ do that, and is supposed to not change unrelated packages without a reason (e.g. a consistency issue in the installed set of packages, like missing dependencies) ; so there must be something else in play here. This all depends on the solver used and its options though, please include the output of `opam config report`.

Also, pinning is the right way if you want to keep the version 1.5 over time, but the quickest fix in your case (or in general when opam doesn't do exactly what you expected) is to just extend the request:
```
$ opam install yojson ppx_import=1.5
```
This should work even if ppx_import is already installed, and has the upside of giving an explanation why the solution wasn't chosen in the first place, if there is one (i.e., the two packages somehow conflict, led to an earlier version of yojson being chosen, required extra dependencies to get installed, etc.)

**Comment by NathanReb** [comment]
Hmm for some reason I can't reproduce the issue right now so it must indeed have been caused by my switch being dirty somehow but I unfortunately removed it since.

I have a vague recollection of what I was trying to do and should be able to reproduce it. I'll try and do that and will get back to you with `opam config report` then!
