### ISSUE TITLE
precmd overwritten

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/opam#3849]
File `~/.opam/opam-init/env_hook.csh` overwrites precmd alias, disregarding previously set value. Workaround:

```shell
#alias precmd 'eval `opam env --shell=csh --readonly`'
```

Doesn't feel like a future-proof solution. Any clues?

```shell
~>opam --version
2.0.4
~>opam config report
# opam config report
# opam-version      2.0.4 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=ubuntu os-version=18.04
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              4
# repositories      1 (http) (default repo at a28553e4)
# pinned            0
# current-switch    4.07.1
[WARNING] PATH contains '.' : this is a likely cause of trouble.
```

**Comment by AltGr** [comment]
This is a problem specific to `csh`, the other supported shells have proper handling for adding to `precmd`. I am open to solutions for csh ! If there are none, we might add a warning for csh users before defining the shell hook...

**Comment by rjbou** [comment]
Any `csh` user hint ?

**Comment by dra27** [comment]
PRs for this would be welcomed, but we don't have the `csh` expertise to be able to make progress with it!
