### ISSUE TITLE
Hard wired home instead of variable

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/opam#3851]
Scripts in ~/.opam/opam-init are hard wiring the home instead of using the $HOME variable.  That's brittle.

```shell
~>opam config report
# opam config report
# opam-version      2.0.4 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=ubuntu os-version=18.04
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              4
# repositories      1 (http) (default repo at a28553e4)
# pinned            0
# current-switch    4.07.1
[WARNING] PATH contains '.' : this is a likely cause of trouble.
```

**Comment by AltGr** [comment]
Sorry, I don't get exactly what you mean ?
These scripts are generated based on actual paths, they have no relation to the home, apart from the fact that the default opam root is set to `$HOME/.opam`.

**Comment by cuihtlauac** [comment]
For instance, here is the content of the ~/.opam/init/init.sh file which I had generated:

```shell
if [ -t 0 ]; then
  test -r /home/cuihtlauac/.opam/opam-init/complete.sh && . /home/cuihtlauac/.opam/opam-init/complete.sh > /dev/null 2> /dev/null || true

  test -r /home/cuihtlauac/.opam/opam-init/env_hook.sh && . /home/cuihtlauac/.opam/opam-init/env_hook.sh > /dev/null 2> /dev/null || true
fi

test -r /home/cuihtlauac/.opam/opam-init/variables.sh && . /home/cuihtlauac/.opam/opam-init/variables.sh > /dev/null 2> /dev/null || true
```

There are several occurences of `/home/cuihtlauac` instead of $HOME.

**Comment by AltGr** [comment]
Yes, because the script refers to the absolute paths where the files have been installed. I am guessing you have in mind a case where that would not behave as you would wish... could you elaborate on that ?

I could speculate that you would wish to rename your home or move `~/.opam` across users. That won't work, because besides these scripts, installations of OCaml prefixes will contain hardcoded paths (although we are trying to solve those).

**Comment by dra27** [comment]
As @AltGr notes, using `$HOME` here would create a false sense of portability. If you rename your home directory, opam would require completely reinitialising.
