### ISSUE TITLE
`diff` doesn't have `-a` on Solaris

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#3859]
When trying to do `opam update` after a fresh init on a Solaris 11.4 system:

```
% opam update -vvv
.....
+ /usr/bin/diff "-ruaN" "default" "default.new" (CWD=/home/radanne/.opam/repo)
- /usr/bin/diff: illegal option -- a
- usage: diff [-bitw] [-c | -e | -f | -h | -n | -u] file1 file2
-        diff [-bitw] [-C number | -U number] file1 file2
-        diff [-bitw] [-D string] file1 file2
-        diff [-bitw] [-c | -e | -f | -h | -n | -u] [-l] [-r] [-s] [-S name] directory1 directory2
[ERROR] Could not update repository "default": "/usr/bin/diff -ruaN default
        default.new" exited with code 2
'opam update -vvv' failed.
```

Turns out, `diff` doesn't have `-a` on Solaris 11.4

**Comment by Drup** [comment]
Actually, while I kept digging: there are *lot's* of hurdle for getting anything to work on solaris, and this is just the very first one. I won't dedicate time on crossing the others.

**Comment by rjbou** [comment]
Solaris is not an os handled by opam. Thanks for the report.

**Comment by avsm** [comment]
It should get further if you install the GNU tools on Solaris.

**Comment by dra27** [comment]
I'm going to close this, just because issues for Solaris are not likely to get addressed - PRs, if that's possible, very much welcomed, as long as the changes are maintainable!
