### ISSUE TITLE
creating local switch only works if there already is a switch

### ISSUE THREAD

**Issue by vogler** [ocaml/opam#3874]
I wanted to start using local switches.
Locally, with several existing global switches (one being 4.07.1), `opam switch -y create ./ --deps-only` works fine (log says `installed ocaml-system.4.07.1`).
On travis-ci, after `opam init -y -a --bare` (without having any switches installed), it fails with `No available version of ocaml-base-compiler satisfies the constraints` ([see log](https://travis-ci.com/goblint/analyzer/jobs/207815684#L536)).
There it only works if I specify a compiler version, e.g., `opam switch -y create ./ --deps-only ocaml-base-compiler.4.07.1`.
I would expect that local switches also install a compiler if there is none yet.
The version constraint in the `opam` file is `"ocaml" {>= "4.04.1" & < "4.08"}`.

**Comment by rjbou** [comment]
It is not related to opam initialisation, but there is actually a mistake in the choice of compiler for a specific case, and you reach it: local switch based on local repo, no compiler selected, and range on constraint, and more than one compiler compliant.
Thanks for the report!
