### ISSUE TITLE
opam install coq takes too long time

### ISSUE THREAD

**Issue by Kumikumichocho** [ocaml/opam#3877]
>   If your issue concerns a package not building, please report to
>   https://github.com/ocaml/opam-repository/issues or to the package maintainer
>   unless you are confident it is an issue in the opam tool itself.

I have a question: How long does it take to implement 'opam install coq'? I'm waiting for the process stopped for more than 2hours as following. So I'd like to know this is the standard time to install or just I have something wrong with my opam setting etc...

```
$ opam list
 Packages matching: installed
 Name         Installed        Synopsis
base-bigarray base
base-threads  base
base-unix     base
camlp5        7.06.10-g84ce6cc4 Preprocessor-pretty-printer of OCaml
conf-m4       1                 Virtual package relying on m4
num           1.1               The legacy Num library for arbitrary-precision integer an
ocaml         4.07.1            The OCaml compiler (virtual package)
ocaml-config  1                 OCaml Switch Configuration
ocaml-system  4.07.1            The OCaml compiler (system version, from outside of opam)
ocamlfind     1.8.0             A library manager for OCaml

$ opam install coq
The following actions will be performed:
  ∗ install coq 8.9.1

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[coq.8.9.1] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
Processing  1/2: [coq: make]
```
Environment:
OS→ OSX, memory→ 8G

I'm a true beginner of opam and this is my first post a question to BBS like this. So if there are anything wrong with my explanation, sorry and it would be helpful if you point it out m(_ _)m

thx for watching
```
# opam config report
# opam-version      2.0.4 
# self-upgrade      no
# system            arch=x86_64 os=macos os-distribution=homebrew os-version=10.14.5
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              3
# repositories      2 (http) (default repo at 08cc4d5c)
# pinned            0
# current-switch    ocaml-system.4.07.1
```

**Comment by rjbou** [comment]
Thanks for the report.
Did you tried to see if there is a opam subprocess that is running, for example with htop ? Coq compilation may take some time, but shouldn't be so long. You can try to relaunch with `-vv` to see coq build commands, ans `--debug` to see the opam log commands.

If it appears that there is a _lock_, or error in opam itself, please share the log here, or using a [gist](http://gist.github.com/) if too long. If not, consider opening an issue on the coq bug tracker.

**Comment by ncihnegn** [comment]
I am having the same issue. Make is using 100% cpu and won't stop.

**Comment by rjbou** [comment]
Were you able to target the process that is stuck / uses cpu, with`top` or `htop`?

**Comment by ncihnegn** [comment]
This is resolved on 8.10.2 in my setup.

**Comment by rjbou** [comment]
8.10.2 version of coq ?

**Comment by ncihnegn** [comment]
> 8.10.2 version of coq ?

Yes.

**Comment by dra27** [comment]
This appears to have been resolved - please re-open if that's not the case!

**Comment by ColmBhandal** [comment]
Thought I had the same issue on ``8.15.1`` but when I ran it with ``-vv`` as per the above suggestion I realised it wasn't actually stuck, it just was compiling/installing a lot of packages. Just posting this here in case anyone thinks it's an issue. I would recommend running with ``-vv`` so you can see the progress.
