### ISSUE TITLE
Confusing error messages related to bad VCS states 

### ISSUE THREAD

**Issue by shonfeder** [ocaml/opam#3905]
Using
```$ opam --version
2.0.4
```

I tried to `opam install .` a WIP project, only to have it fail with:

```
[ERROR] Could not synchronize /home/me/.opam/default/.opam-switch/sources/project-name from "git+file:///home/me/projects/project-name#master":
        "/usr/bin/git fetch -q file:///home/me/projects/project-name +master:refs/remotes/opam-ref-master" exited with code 128 "fatal: couldn't find remote ref master"
[ERROR] The sources of the following couldn't be obtained, aborting:
          - project-name.~dev
```

this means nothing to me. Fortunately, i recalled that opam implicitly ties itself in to the state of your git if you happen to have a `.git` dir in the directory. So i made sure that all the changes were committed, and then the install went forward fine.

A message along the following lines would be much more helpful and user friendly:

```
[ERROR] Project project-name has a `.git` file but opam could not synchronize with the `master` branch. 

Commit all changes to `master` and run the command again.
```

I could easily see this kind of thing causing a newbie to give up on our ecosystem, so I think it's important to get ironed out.
 
I would be happy to help improve the state of this, if someone want's to point me at the right block of code.

**Comment by rjbou** [comment]
opam automatically pin (and install) using git when a `.git` directory is present in the targeted directory. But not having a everything committed or not using master shouldn't result to an error, the first one just display a message to inform that only committed files are taken in account and for the second one, opam take the current selected branch as a pinning target.

Was it a just initialised git repo with no commit?

**Comment by shonfeder** [comment]
> Was it a just initialised git repo with no commit?

@rjbou that's exactly right! Perhaps this is one edge condition that isn't handled well yet?

**Comment by rjbou** [comment]
It is not handled as it is a corner case and the reason is given by git : there is no master branch.
If another branch exist, opam takes it as the branch to pin. Here no branch is available, it takes the default _master_, and it is not existing.

**Comment by shonfeder** [comment]
Is there a reason in principle that we don't want to make the error handling around this edge case more user friendly? My own experience show its not that edgy: I've hit it twice in two successive packaging efforts.

Letting git's error message leak through might be fine if the error message actually was `"there is no master branch"`, but, as indicated, it is something much more obscure. Even so, how much do we want users of opam to have to bear the cognitive load of always keeping their VCS front of mind while using the package manager?
