### ISSUE TITLE
Coloring on Windows

### ISSUE THREAD

**Issue by toots** [ocaml/opam#3909]
Hi,

We're using the coloring code from `opam` in our project and I noticed that it was enabled when running the program on windows, which leads to terminal control characters leaking to the printed screen. Evidently, coloring is not supported there.

Shouldn't this line: https://github.com/ocaml/opam/blob/13079ad9b08b3c4fe1c0a8b785ace96a4164e8a3/src/core/opamConsole.ml#L24 have the opposite boolean, i.e.:

```ocaml
let dumb_term = lazy (
  try
    Sys.getenv "TERM" = "dumb"
  with Not_found -> Sys.win32
)
```

**Comment by dra27** [comment]
It's intentional - `TERM` will not usually be set on Windows, so while `TERM=dumb` will disable the colour output on Windows, the absence of the `TERM` environment variable is not taken as being a dumb terminal.

What do you mean by "printed screen" - are you seeing an effect like #3897?

**Comment by toots** [comment]
Yes, I'm seeing terminal color code inside the `cmd.exe` prompt. Honestly, this is all well above my head and I don't really care that much for coloring on windows. I'll close this one if you say this is intended. I'm down to learn more about how to do terminal coloring on windows properly if you have some pointers but I'm already thankful for your time reviewing this!
