### ISSUE TITLE
opam switch consumes all memory, dies

### ISSUE THREAD

**Issue by jtoman** [ocaml/opam#3921]
I am trying to upgrade my switch from 4.03.0 to 4.06.0. After several minutes without any output and slowly consuming more and more memory, OPAM eventually consumes all 16 GB of physical memory on my machine. Looking at the debug output it appears to be sitting at `Loading cudf universe`. I have tried installing another package and OPAM operates just fine.
```
# opam config report
# opam-version    2.0.0~beta3 
# self-upgrade    no
# os              linux
# external-solver no
# jobs            1
# repositories    1 (http)
# pinned          0
# current-switch  4.03.0
```

**Comment by dbuenzli** [comment]
It seems you are using the old internal solver and you should not as it was no longer able to cope with the size of the opam-repository. 

Either install an external solver like `apscud` or rather, since you seem to be living on beta software, upgrade your opam installation, you'll get a decent built-in solver:
```
# solver            builtin-mccs+glpk
```

**Comment by jtoman** [comment]
That did it, thanks.

**Comment by dra27** [comment]
Also, you're running opam 2.0.0 **beta3** ?!?!?

**Comment by jtoman** [comment]
I'm sure I installed it based on some advice I found on the internet years ago and forgot all about it.

**Comment by dra27** [comment]
Definitely worth an update - your Linux distro may have packaged opam 2.0, or there are [instructions for manual installation](https://opam.ocaml.org/doc/Install.html) - you’ll definitely want to redo `opam init`, as noted on that page.
