### ISSUE TITLE
install.sh should allow use of ~ in install path

### ISSUE THREAD

**Issue by 0cjs** [ocaml/opam#3927]
Run `shell/install.sh` and, when prompted for the install directory, type `~/.local/bin` (or any other directory that exists under your home dir) and note that the installer claims that the directory doesn't exist:

```
## Downloading opam 2.0.5 for linux on x86_64...
## Downloaded.
## Where should it be installed ? [/usr/local/bin] ~/.local/bin 
## ~/.local/bin does not exist. Create ? [Y/n] n
## Where should it be installed ? [/usr/local/bin] /home/cjs/.local/bin
## opam 2.0.5 installed to /home/cjs/.local/bin
## Run this script again with '--restore ' to revert.
```

**Comment by dra27** [comment]
Translating a tilde is the shell's job - it's very tricky to do correctly in a script (cf. trying to pass `--prefix=~/.local` to a `configure` script vs `--prefix ~/.local`).

I guess `install.sh` could as a special case recognise `~/` and ask if "$HOME/" was meant?
