### ISSUE TITLE
New field to recommend pinning

### ISSUE THREAD

**Issue by dra27** [ocaml/opam#3933]
The context of this is the discussion in https://github.com/ocaml/ocaml/issues/8781 and the fact that released versions of `findlib` do not work in the OCaml 4.09 beta.

I propose adding a new field (using the `x-` system, so it can be used in opam-repository) which would allow pin recommendations:

```
x-pin-recommend: ["dev-repo" {ocaml >= "4.09.0"}]
```
or
```
x-pin-recommend: ["git+https://..." {ocaml >= "4.09.0"}]
```

where opam's response on `opam install package` would be to ask if a pin should be created instead (**edit** and then resolve the request). The fact that the pin was created from a recommendation should be recorded in the switch state and tested on upgrade so that when the package no longer has a pin recommendation (either because the new version of the *package* doesn't include one, or it isn't satisfied, or because one of the dependencies has been updated) then opam would similarly recommend the removal of the pin.

The intention here is that the latest version of the problem package would contain this field until the next version is released, when the `pin-recommend` would be replaced by a version constraint.

This is related to https://github.com/ocaml/opam/issues/3202

**Comment by avsm** [comment]
Could pin-depends be extended for this purpose? In practise, it is only used until the next release is out (as #3202 requests as well).

**Comment by dra27** [comment]
Extending an existing field is difficult in terms of compatibility - but it seems worth this being separate?

**Comment by dra27** [comment]
As in, `pin-depends` comes into play if you have *requested* the pinning of the package, the field I propose here comes into play when you haven't.

**Comment by avsm** [comment]
Ah yes of course! Your proposal makes perfect sense.

**Comment by ejgallego** [comment]
I wonder how this interacts with CI / automated generation of OPAM packages.

I have the feeling that the ecosystem is moving towards automatically generating this kind of meta-data, and indeed scalability could be a concern if this set is supposed to be set manually.

Imagine the "platform" does include `findlib`, but quite a few other PPX base packages (providing the generic AST, etc...] then having to set this manually may become a bit time-consuming, right?

For the Coq platform, which is going to be OPAM-based, we will indeed set and validate the pins almost automatically, tho it is not clear what the solution will be yet.

**Comment by dra27** [comment]
This field would be odd to use in a repository, so it's not related to automatic generation - it's more about a curated recommendation in opam-repository for how to install a package. In many respects, opam-publish, etc., being unaware of it is useful, since you expect the next release to blow it away.

For CI, opam is run with `--yes`, so the pin recommendation would be taken. As to whether this is what you'd want on a given CI comes back to the (largely unanswered) question of whether one's CI should be using upstream opam-repository directly, as opposed to a CI-specific fork which is brought forward at known points.

**Comment by ejgallego** [comment]
I wonder what that field is a recommendation tho, in principle you would like consistency to be preserved, not optional, right? What would happen if the user says "no" to the recommendation, then it tries to install the faulty package later?

It seems to me that it may complicate dependency resolution.

But indeed I guess this kind of problem is not easy, in the Coq OPAM repos people have been using "dev" packages for a long time, and adding the proper constraints, but that has quite a few downsides too it seems.

**Comment by dra27** [comment]
Well, if the user ignores the recommendation, then the likely outcome will be that the package will fail to build - however, you'd still want the recommendation, since the user may, for example, have pinned `ocaml` and changed something about it. We're in the realm of beta testing and dev versions here, so some aspects of consistency you might like are not guaranteed - in general, yes, you might want to it that having rejected the pin, you re-solve with that package marked as unavailable. However, I think that would be over-engineering the feature.

A dev package would be the other solution, but what I dislike about that is that you then have to delete the package when the official release happens, which is something opam-repository avoids.

**Comment by ejgallego** [comment]
> A dev package would be the other solution, but what I dislike about that is that you then have to delete the package when the official release happens, which is something opam-repository avoids.

Maybe the betas should indeed live in a beta OPAM repository, along with the dev packages? What would be the downsides of this?

**Comment by AltGr** [comment]
This sounds nice, but I am not sure it is worth adding a new feature just for this specific case; at least, #3202 (a `pin-until-next-release` feature) should come first, since it is the important part here. `messages:` and/or `post-messages:` could be used in the meantime to advertise pinning in known specific cases — although that would remain manual.

**Comment by dra27** [comment]
I'm not convinced that's the best ordering - `--pin-until-next-release` is for the *expert* who already knew to pin the package and wants the tool to help remind them to remove it later, where this is for the *beginner* who's just trying to get it to work. Equally, they're close enough features that they'd probably get worked on at the same time 🙂

**Comment by dbuenzli** [comment]
In the end isn't that just a `pin` version constraint ?

**Comment by dra27** [comment]
@dbuenzli - I don't (yet) follow - do you mean `pin-recommend` or `--pin-until-next-release`?

**Comment by dbuenzli** [comment]
Mmmh sorry for the confusion. I misunderstood I thought it was a package that needed a pinned package. But that is not the case. It's rather a package (`ocaml`) that imposes a pin on some of its reverse dependencies (`ocamlfind`). 

What you propose is weird though, since according to what I read in your proposal you would put that in the `opam` file of a specific version of `ocamlfind`. It means that now this opam file is somehow describing something else than that version of `ocamlfind` which is at odds with the conceptual model of opam where opam files describe specific package versions. 

A more logical place to put that would be in the `ocaml` file of the version that imposes the pin. But that's equally weird since a package (`ocaml`) is being made aware of its rev-deps (`ocamlfind`).

In the end this seems rather a repo wide constraints. I didn't give it a deep thought but I 
have the impression that this could be solved by the constraints sets of my [old proposal](https://gist.github.com/dbuenzli/961a71b18600156ec704b465e89d7dc7) to streamline opam switch initialization (which I still find much too convoluted and weird).

In general I have the impression that `opam` is adding more and more stuff and maybe we should take a step back, perform a bit of root cause analysis, and start using the conceptual razor.

**Comment by AltGr** [comment]
> In general I have the impression that opam is adding more and more stuff and maybe we should take a step back, perform a bit of root cause analysis, and start using the conceptual razor.

I've been having that feeling too... there are a lot of specific features that are useful in some cases, but so many that they're not discoverable easily enough by the users who would need them; it might be a documentation issue, but nobody is going to read a 100 pages manual before they use opam.

> In the end this seems rather a repo wide constraints. I didn't give it a deep thought but I
have the impression that this could be solved by the constraints sets of my old proposal to streamline opam switch initialization (which I still find much too convoluted and weird).

FWIW, it doesn't go as far as your proposal, but we are testing a replacement of "switch base packages" by "switch constraints" (which have the same format as depends-formulas). It required some tweaking of the solver, but basically offers more expressivity at no cost. There aren't named constraints at the moment (but those can be emulated using virtual packages of course).

**Comment by dbuenzli** [comment]
@AltGr that looks like excellent news is there somewhere I can have a peek and/or read about ?

**Comment by AltGr** [comment]
Sure, it's here: #3894

**Comment by dra27** [comment]
@dbuenzli For this field, the way I'd envisioned it was:

- Problem identified with a specific version of the compiler, fixed upstream, but not released, so *latest* version of the package gains this field to recommend the pin and all the older versions have version constraints updated (like normal)
- New version of the package is released - so an old pin recommendation (which isn't incorrect, just unnecessary) gets left in the version before the latest, but by default that version will no longer be picked up on the new compiler. Ideally, when the new version is realeased, this package would be updated to constrain it away.

If the info's stored repo-wide as more of a "ocamlfind requires pinning if OCaml >= 4.09" statement, that *has* to be removed when the new version of ocamlfind (or you have to remember to include the version of ocamlfind in the constraint as well). Is it definitely better that way?

(I'm only wedded to the idea that there should be a solution - so installing `ocamlfind` should work because the user is told that it needs pinning - not necessarily what it is!)

**Comment by dbuenzli** [comment]
> * New version of the package is released - so an old pin recommendation (which isn't incorrect, just unnecessary) gets left in the version

No, it may become incorrect with the time. As I highlighted in my message above I think it is wrong from a conceptual point of view to specify this in any of the `opam` files of that package.

> If the info's stored repo-wide as more of a "ocamlfind requires pinning if OCaml >= 4.09" statement, that _has_ to be removed when the new version of ocamlfind (or you have to remember to include the version of ocamlfind in the constraint as well). Is it definitely better that way?

Yes.

**Comment by dra27** [comment]
In the intervening two years, the release readiness efforts started for 4.11, 4.12 and 4.13 have mitigated this rather more effectively!
