### ISSUE TITLE
ERROR while compiling ocaml-base-compiler.4.08.0 on Centos6.8

### ISSUE THREAD

**Issue by BertPeng** [ocaml/opam#3942]
Thanks to @dra27 , I initialized opam succfully by using opam init --disable-sandboxing. Opam2.05, Ocaml4.08.
But;
```
#=== ERROR while compiling ocaml-base-compiler.4.08.0 =========================#
# context     2.0.5 | linux/x86_64 | base-bigarray.base base-threads.base base-unix.base | https://opam.ocaml.org/#635839e7
# path        ~/.opam/system/.opam-switch/build/ocaml-base-compiler.4.08.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./configure --prefix=/home/phang/.opam/system
# exit-code   10
# env-file    ~/.opam/log/ocaml-base-compiler-22687-c743ac.env
# output-file ~/.opam/log/ocaml-base-compiler-22687-c743ac.out
### output ###
# The 'bwrap' command was not found. Install 'bubblewrap' on your system, or
# disable sandboxing in ~/.opam/config at your own risk.
# See https://github.com/projectatomic/bubblewrap for bwrap details.
# For 'bwrap' use in opam, see the FAQ:
#   https://opam.ocaml.org/doc/2.0/FAQ.html#Why-does-opam-require-bwrap
```
Also, didn't find the install guide of bubblewrap.

How to solve this problem? Thanks

Edit by @rjbou: formatting

**Comment by dra27** [comment]
Sorry, the info I gave you was for a fresh `opam init` (so deleting `~/.opam` first) - you need to do `opam init --reinit --disable-sandboxing` when you’ve already run `opam init` already.

For help installing bubblewrap on CentOS, either have a look at the Bubblewrap project itself (URL above) or ask on [Discuss](https://discuss.ocaml.org).

**Comment by BertPeng** [comment]
Thanks, it works, I can use opam to install tools.
