### ISSUE TITLE
warn about mismatch between repo url and format

### ISSUE THREAD

**Issue by jberdine** [ocaml/opam#3969]
I somehow had a repo url and format out of sync, leading to 404 errors, which were unclear how to resolve. In particular, repo-url was `https://github.com/ocaml/opam-repository` which did not work, but repo-url of `https://opam.ocaml.org` or `git://github.com/ocaml/opam-repository` are ok. See https://github.com/ocaml/opam-repository/issues/14747 for context.

**Comment by rjbou** [comment]
It is the normal opam behavior, there is some detection on url backends. It is described [here](https://opam.ocaml.org/doc/Manual.html#URLs). But I don't understand how it worked before... Last changes on url handling date back to 2-4 years...
At some point, did you had as url `https://github.com/ocaml/opam-repository.git`?

As explained @avsm, opam assumed it is an webserver repo, and used the `http` backend to get repo archive. Unless parsing and detecting that there is a `git` in the url, there is not real way to determine that there is a mistake on the backend. And we can't really differentiate if the url is unreachable or wrong backend.

**Comment by rjbou** [comment]
Closing this issues, feel free to reopen. 
Related pr #4086 and issue #4085
