### ISSUE TITLE
Internal failure when trying to build a package from source --inplace

### ISSUE THREAD

**Issue by gasche** [ocaml/opam#3974]
I saw an internal failure of opam that seems transient. After installing the package and installing it again, I cannot reproduce. I may be able to reproduce by creating a fresh switch each time, but that is work, so I thought I would first report here and see if you can already tell what the issue is.

(My machine has opam.2.0.0; I glanced at the Changelog of recent releases and couldn't see a related issue.)

I was trying to reproduce an ocamlbuild build-failure report. First I created a fresh 4.08.1 switch, ran `eval $(opam env)`, and then I built ocamlbuild from a local pin of the git repository. This worked fine. Then I ran

```shell
cd /tmp
opam source ocamlbuild
cd ocamlbuild-14.0
opam install . --inplace-build
```

and I saw the following failure log:

```
$ opam install . --inplace-build
[NOTE] Package ocamlbuild is currently pinned to git+file:///home/gasche/Prog/ocamlbuild/github#master (version 0.14.0).
ocamlbuild is now pinned to git+file:///tmp/ocamlbuild.0.14.0#master (version 0.14.0)
The following actions will be performed:
  - recompile ocamlbuild 0.14.0*

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>

#=== ERROR while compiling ocamlbuild.0.14.0 ==================================#
opam: "chdir" failed on /home/gasche/.opam/4.08.1/.opam-switch/sources/ocamlbuild: No such file or directory
```

It seems that opam is making assumptions about a certain `.opam-switch/sources/PKG` directory existing at some point of the build, assumptions which may be incorrect when `--inplace-build` is used.

I then tried just `opam install .`, which worked, and then `opam remove ocamlbuild`, but then I cannot reproduce the issue anymore by running `opam install . --inplace-build` again -- and indeed the directory now exists.

**Comment by rjbou** [comment]
Indeed, as the `--inplace-build` is set opam doesn't copy sources to internal directory and as a new pin is done, remove the old sources. And no action requires to have access to this directory.

If you can retry: to get back to a similar environment, run these commands before install, and see if you can reproduce?
```
$ opam unpin ocamlbuild -n && opam remove ocamlbuild
$ opam clean #clean unnecessary files/dirs, ocamlbuild is one of them
$ cd /home/gasche/Prog/ocamlbuild/github && opam install . #you had a already pinned ocamlbuild
$ cd /tmp
```

if it reproducible, please share the debug  & verbose output of the failing install.

**Comment by dra27** [comment]
It is reproducible using this `Dockerfile`:

```Dockerfile
FROM ocaml/opam:debian-ocaml-4.08
#RUN sudo ln -f /usr/bin/opam-2.1 /usr/bin/opam && opam update
RUN git clone https://github.com/ocaml/ocamlbuild.git
RUN opam pin add ocamlbuild ocamlbuild
RUN opam source ocamlbuild
WORKDIR ocamlbuild.0.14.0
RUN opam install . --inplace-build
```
however with the second line uncommented (i.e. with opam 2.1) it's also fixed!

**Comment by gasche** [comment]
Apologies for not being so helpful in reproducing the issue, and thanks for the fix!

**Comment by dra27** [comment]
No problem at all!
