### ISSUE TITLE
`make cold` picks up dune from PATH instead of building it

### ISSUE THREAD

**Issue by glondu** [ocaml/opam#3987]
With opam-full-2.0.5.tar.gz, running `make cold` while there is a dune binary in PATH picks up that binary instead of building it.

**Comment by rjbou** [comment]
It is the normal behavior of `make cold`, dune existence is checked, installed only if missing. Meanwhile, it is required to have some version check on dune, as in the opam file, it's minimum `1.2.1`.

**Comment by glondu** [comment]
Would you reconsider this behaviour? I expect `make cold` to produce and use a self-contained installation of all OCaml-related stuff...

**Comment by dra27** [comment]
I don't think that's an unreasonable option. As a workaround, `make DUNE= cold` I think should cause the external dune to be ignored.

**Comment by glondu** [comment]
> As a workaround, `make DUNE= cold` I think should cause the external dune to be ignored.

It tries to use the empty string as dune command, and fails with:

    build --profile=release  opam-installer.install opam.install
    make[1]: build: Command not found
    make[1]: *** [Makefile:107: opam.install] Error 127

**Comment by avsm** [comment]
Agreed. `make cold` was intended to be an entirely standalone target, so it should also build the local dune.
