### ISSUE TITLE
Opam doesn't recognize the `env` command.

### ISSUE THREAD

**Issue by axiomtutor** [ocaml/opam#3988]
```
# OPAM config report
# opam-version    1.2.2 
# self-upgrade    no
# os              linux
# external-solver no
# criteria        -removed,-notuptodate,-changed
# jobs            4
# repositories    1 (http)
# pinned          0
# current-switch  system*
# last-update     2019-09-17 18:20
```
I just installed OPAM on a brand new install of Linux Mint.  I've run all the `sudo apt-get update` and `sudo apt-get upgrade` and so on.  To get OPAM I ran `sudo apt-get install opam` and then `opam init`.  

When I now run `eval `opam env`` as it suggests [at the installation instructions](https://ocaml.org/docs/install.html) the terminal response 

`opam: unknown command `env'.`

I can find no information on this issue so advice or something would be appreciated.  As it is, I have OCaml version 4.05.1 but would prefer to upgrade and OPAM also doesn't recognize the `switch create ...` command.

**Comment by dbuenzli** [comment]
You seem to have problems with quotes try `eval $(opam env)`. 

Another thing is that you are using `opam` 1.2.2 with the internal solver. This is not going to work on the current state of the `opam-repository`. 

Either install opam >= 2.0.0 (which has a decent built-in solver) or install an [external solver](https://opam.ocaml.org/doc/External_solvers.html).

**Comment by axiomtutor** [comment]
Cool, downloading the binaries rather than getting it from my repository gave me an updated version and now everything works.  Thanks!
