### ISSUE TITLE
`opam admin add-constraint` doesn't add constraints for optional dependencies

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#3994]
At the moment `opam admin add-constraint` only modifies the `depends` field of each opam file but this is not complete. Some packages might depend optionally to the one you want to constrain and thus require their `conflicts` field to be modified.

For instance `opam admin add-constraint lwt<3.0.0` should modify `tls.0.9.3` because it depends on lwt optionally:
```
depopts: [
  "lwt"
  [...]
]
conflicts: [
  "lwt" {<"2.4.8"}
  [...]
]
```
If the command would have handled optional dependencies then the opam would look like this after running the command (or something equivalent):
```
depopts: [
  "lwt"
  [...]
]
conflicts: [
  "lwt" {<"2.4.8"}
  "lwt" {>= "3.0.0"}
```

_Tested with opam 2.0.5_

**Comment by rjbou** [comment]
Thanks for the report!
