### ISSUE TITLE
OpamSystem.File_not_found("/home/User/.opam/aliases") when switching from 4.05 to 4.07

### ISSUE THREAD

**Issue by Neywiny** [ocaml/opam#3996]
```
# OPAM config report
# opam-version    1.2.2 
# self-upgrade    no
# os              linux
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            4
# repositories    1 (http)
# pinned          0
# current-switch  system*
# last-update     2019-09-12 13:41
```

Full log is located [here](https://pastebin.com/P6yBF7fc) to avoid spamming

The final few lines are:
```
Processing: [4.07.0: ./configure]
Processing: [4.07.0: make world]
Processing: [4.07.0: make world.opt]
Processing: [4.07.0: make install]
Done.
11:23.047  SYSTEM                  rmdir /home/User/.opam/4.07.0/build/ocaml
11:33.092  STATE                   add_switch switch=4.07.0 compiler=4.07.0
11:33.092  FILE(aliases)           Read ~/.opam/aliases in 0.000s
11:33.095  SYSTEM                  Lock released on /home/User/.opam/lock
Fatal error:
OpamSystem.File_not_found("/home/User/.opam/aliases")
```
```
$ cat /home/User/.opam/aliases
system system
User@comp:~/.opam/4.07.0$ 
```
I've tried using sudo to no avail. I honeslty have no clue why this is happening and it seems like nobody has this issue.

**Comment by rjbou** [comment]
opam 1.2.2 is no more maintained and repository is frozen [since a year](https://opam.ocaml.org/blog/opam-2-0-0), consider upgrading to opam 2.

I'll ping @altgr on this one. Which is weird is that `aliases` file is well read multiple times on the full log.

**Comment by Neywiny** [comment]
Well I upgraded to opam 2.0.0 and now everything is broken. Can't create switches because it says it can't find compilers, can't install compilers because it says my packages are broken and the switch may need to be reinstalled, can't reinstall because it says there's "nothing to do". Can't run opam init because it can't write to a bunch of files in .opam again.

```
$opam switch list-available
# Listing available compilers from repositories: default
# No matches found
```
I ended up just wiping the system and trying again since I need this working more than I want to figure out what was wrong.

**Comment by rjbou** [comment]
Sorry for the inconvenience. Hope that now you everything is well set.

**Comment by Neywiny** [comment]
It is. I ended up getting my things done on time. I had forgotten to add the ppa that includes opam 2.0.0, so it defaulted to the old one and I didn't question it. Looking at the install instructions, that's on me.
