### ISSUE TITLE
What is the correct way to upgrade from 1.2 to 2 unattended ?

### ISSUE THREAD

**Issue by ysalmon** [ocaml/opam#4009]
I upgraded an array of computers from Debian 9 to Debian 10 and thus from opam 1.2 to opam 2.x.

On first run post upgrade, opam asks to upgrade the local repo to the 2.x format ; if I say yes (or use the --yes switch), it performs an update during which it asks if I want to install shell hooks for updating environments. While the idea is nice, I do not want them at the moment.

But to upgrade my array of computers unattended, I currently say ``opam var root --yes``  to trigger the upgrade. But using the --yes switch (to start the upgrade) is taken into account for the question about hooks too.

I could not find in the [upgrade guide](https://opam.ocaml.org/doc/Upgrade_guide.html) the name of a specific command for this. Is there one ?

(Also, when doing eg. ``opam var root --safe`` immediately after updating the opam binary, it still (I think) triggers the repo-update mechanism and fails with an error because acquiring a write lock in --safe mode is bad.)

**Comment by rjbou** [comment]
Unfortunately, there isn't. Using `opam init`, there is the possibility to disable setup, or configure it by option, but for the 2.0 upgrade process, actions are performed in a diverted way, before everything, no option is taken.
It is possible to add an environment variable that disables interactive reinit, but it would be available on next release.
For the moment, you can launch an `opam reinit --disable-shell-hook` on your computers to disable that behaviour.

**Comment by rjbou** [comment]
Now (since 2.1.0~alpha) with opam option, you can empty the build/install/remove wrapper via the cli.
