### ISSUE TITLE
opam init causes problem

### ISSUE THREAD

**Issue by m1cl** [ocaml/opam#4011]
hello, I have an issue with opam. I want to create a new project using opam init.

I got this error message: 
```
Could not update repository "default": OpamDownload.Download_fail(_, "Curl failed: \"/opt/anaconda/bin/curl --write-out %{http_code}\\\\n
        --retry 3 --retry-delay 2 --user-agent opam/2.0.5 -L -o /tmp/opam-17606-e7966f/index.tar.gz.part https://opam.ocaml.org/index.tar.gz\"
        exited with code 77")
```
I am fairly new to the ocaml universe, maybe I did something wrong. I am using arch linux and I installed opam via package manager. 

You are welcome

@rjbou: edit

**Comment by rjbou** [comment]
It seems that there is a problem with the certificate validation, from curl manpage:
```
       77     Problem with reading the SSL CA cert (path? access rights?).
```

Maybe there is some `ca-certificate` missing package on your system ?

**Comment by dbuenzli** [comment]
According to `man curl` an exit code of 77 means:
```
77     Problem with reading the SSL CA cert (path? access rights?).
```
are you sure you don't have any problem with the TSL certificates on your machine,

**Comment by rjbou** [comment]
Closing this issue, feel free to reopen if needed.
