### ISSUE TITLE
opam 2.0.4 has no libraray about Cmo_format [Arch Linux]

### ISSUE THREAD

**Issue by MokkeMeguru** [ocaml/opam#4013]
# Environment
- Manjaro Linux (5.2.21-1-MANJARO)
- ocaml-compiler-libs-4.09.0-1 
- opam-2.0.4
- OCaml  4.09.0

# Problem
```
[...]$ ls /usr/lib/ocaml/compiler-libs/ | grep Cmo
[...]$
```

So, We cannot install some packages ex. `base`

```
opam install base
The following actions will be performed:
  ∗ install base v0.12.2

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[base.v0.12.2] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of base failed at "/home/meguru/.opam/opam-init/hooks/sandbox.sh build dune build -p base -j 7".

#=== ERROR while compiling base.v0.12.2 =======================================#
# context     2.0.4 | linux/x86_64 | ocaml-system.4.09.0 | https://opam.ocaml.org#867b7ac6
# path        ~/.opam/default/.opam-switch/build/base.v0.12.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p base -j 7
# exit-code   1
# env-file    ~/.opam/log/base-7179-d2c37b.env
# output-file ~/.opam/log/base-7179-d2c37b.out
### output ###
#       ocamlc compiler-stdlib/gen/.gen.eobjs/byte/gen.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /usr/bin/ocamlc.opt -w -40 -g -bin-annot -I compiler-stdlib/gen/.gen.eobjs/byte -I /usr/lib/ocaml/compiler-libs -no-alias-deps -o compiler-stdlib/gen/.gen.eobjs/byte/gen.cmo -c -impl compiler-stdlib/gen/gen.ml)
# File "compiler-stdlib/gen/gen.ml", line 59, characters 33-51:
# 59 |      let toc = (input_value ic : Cmo_format.library) in
#                                       ^^^^^^^^^^^^^^^^^^
# Error: Unbound module Cmo_format



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build base v0.12.2
└─ 
╶─ No changes have been performed
```

I think other OS's opam remove it too.
Please fix this problem or give me some advice to fix it.

**Comment by MokkeMeguru** [comment]
I also try https://opam.ocaml.org/blog/opam-2-0-5/  's manual install (`sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)`),
 but then I notice there is no folder `/usr/lib/ocaml/compiler-libs`

**Comment by MokkeMeguru** [comment]
For the same reason, the following AUR packages will not work properly.

https://aur.archlinux.org/packages/ocaml-base/

**Comment by rjbou** [comment]
opam doesn't perform install in the system but in the opam root (by default `~/.opam`). You can do the same check, but on the opam switch directory: `find $OPAM_SWITCH_PREFIX -name cmo_format.*`

Did you set up the shell hook, or evaluated `opam env`? If so, you can check that your path & ocaml library path contains well the good additions.

**Comment by dra27** [comment]
This is a bug in Arch - the 4.09.0 version of the `ocaml-compiler-libs` package has been assembled incorrectly. ocaml/ocaml#2281 moved some files around, and the [PKGBUILD](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/ocaml#n51) for the package isn't looking in the new locations (it's *at least* missing `file_formats/*.cmi`)

**Comment by MokkeMeguru** [comment]
@rjbou 

```
[...]$ find $OPAM_SWITCH_PREFIX -name cmo_format.*
[...]$ echo $OPAM_SWITCH_PREFIX
echo $OPAM_SWITCH_PREFIX
```

I think @dra27 says the correct problem.
@dra27 How to install ocaml-compiler-libs? I saw some output about this problem

 ```
[...] $ ls $OPAM_SWITCH_PREFIX/lib/compiler-libs
META
[...] $ ls /usr/lib/ocaml/compiler-libs/ | grep cmo
main.cmo
topstart.cmo
```

**Comment by dra27** [comment]
To fix it right now, you could create a switch with `opam switch create ocaml-4.09.0 ocaml-base-compiler.4.09.0` which will build OCaml from sources and won't have this problem. For fixing your system package, the issue needs reporting [on the Arch bug tracker for the package](https://bugs.archlinux.org/?project=1&string=ocaml-compiler-libs).

**Comment by j-degreef** [comment]
It is correct to buils ocaml-base but then cause ocamlfuse not being compiled anymore because of a camlidl problem.
Here's my solution : https://aur.archlinux.org/packages/google-drive-ocamlfuse/#comment-712227 :)
