### ISSUE TITLE
Docker containers for statically linked OCaml binaries

### ISSUE THREAD

**Issue by igor-petruk** [ocaml/opam#4022]
It would be great to have ocaml/opam2:alpine with a variant that enables statically linked OCaml binaries (with MUSL and SSL) that can be later run at any distribution and trivially run in "scratch" docker container, for example like Go does.

**Comment by talex5** [comment]
See https://discuss.ocaml.org/t/psa-ocaml-opam2-docker-images-updated-to-4-08-0-release/3948/12?u=talex5

**Comment by igor-petruk** [comment]
Thank you very much, I'll try!

I wonder how far this works though, for example to which dependencies it applies and to which not.

**Comment by igor-petruk** [comment]
Yes, worked for me flawlessly, for lwt-unix for example. I haven't tried anything with SSL yet.

**Comment by XVilka** [comment]
Should be closed then?

**Comment by igor-petruk** [comment]
Yes, it can be closed.

But it might be useful to mention this in some documentation, maybe to docker images or elsewhere. It was not easy to discover this without your suggestion and the link.

**Comment by rjbou** [comment]
It can be added in the containers [wiki documentation](https://github.com/ocaml/infrastructure/wiki/Containers).
