### ISSUE TITLE
opam not creating a switch

### ISSUE THREAD

**Issue by pietro97ventura** [ocaml/opam#4023]
I've been trying to install ocaml-top for a while, but opam is giving me issues. I followed the tutorials online and i always got to the same point:
```
No switch is currently set. Please use 'opam switch' to set or install a switch
```
and then "opam switch" gives me:
```
#  switch  compiler  description
```
I don't know what to do, every time i try to setup a switch it's always the same:
```
opam switch create ocaml-base-compiler 4.09.0
[ERROR] Solver failed: "/usr/bin/aspcud
        /home/metal/.opam/log/solver-in-5414-5f1023
        /home/metal/.opam/log/solver-out-5414-58c514
        -count(removed),-sum(request,version-lag),-count(down),-sum(solution,version-lag),-count(changed)"
        exited with code 1 "ERROR: grounder returned with non-zero exit status"
Switch initialisation failed: clean up? ('n' will leave the switch partially
installed) [Y/n] y
```
Any help would be appreciated

```
# opam config report
# opam-version      2.0.3 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=ubuntu os-version=19.04
[ERROR] No switch is currently set. Please use 'opam switch' to set or install
        a switch
# read-state        OpamStd.OpamSys.Exit(50)

```
edit: rjbou formatting

**Comment by rjbou** [comment]
There is some packaging issues of opam (cf. #3827), it should use builtin solver, but it packaged with `aspcud`.
Can you try this [workaround](https://github.com/ocaml/opam/issues/3827#issuecomment-491365469) ?

**Comment by pietro97ventura** [comment]
@rjbou you saved me. it took a deep purge of opam and ocaml, but at last it worked. thank you so much
