### ISSUE TITLE
Feedback: places where opam2nix implementation required reimplementing parts of opam

### ISSUE THREAD

**Issue by timbertson** [ocaml/opam#4030]
@avsm [invited me](https://discuss.ocaml.org/t/ann-opam2nix-v1/4741) to report on things which were difficult in [opam2nix](https://github.com/timbertson/opam2nix) (which uses opam-lib to automate building nix derivations for opam packages)

Broadly, the main thing I found I had to reimplement was anything which depended on opam switch state. I was able to build my own package universes, variable resolvers etc without too much trouble, but the state is very tied to opam's on-disk state, which is unsurprisingly ill-fitted to a system like nix which is stateless and where every package lives in its own prefix.

I don't think it'd be useful to make `state` generic enough to work for `opam2nix`, but perhaps there are ways to require a concrete state instance in less places.

For examples, here's some code in opam2nix which was largely copied from opam itself but couldn't be reused due to the use of state:

- [OpamSwitchState.get_conflicts](https://github.com/ocaml/opam/blob/c17c5cb2c1aa49a8e2026739714234039889bc14/src/state/opamSwitchState.ml#L479-L524) ([opam2nix version](https://github.com/timbertson/opam2nix/blob/1ffd0231c972bef5d741f178072593bee98c62da/src/select.ml#L83-L122)). This one was quite sneaky, because nothing forced me to implement it. I originally didn't implement this, and only found out about this missing code when diagnosing solves which picked conflicting packages. It's also a good example of something which could be decoupled from the switch state, my implementation only requires `lookup_var nv`, which in your case is `OpamPackageVar.resolve_switch ~package:nv st`.

- [OpamAction.prepare_package_build](https://github.com/ocaml/opam/blob/c17c5cb2c1aa49a8e2026739714234039889bc14/src/client/opamAction.ml#L243-L337) ([opam2nix version](https://github.com/timbertson/opam2nix/blob/1ffd0231c972bef5d741f178072593bee98c62da/src/invoke.ml#L200-L256)). Again `st` seems to be used just to resolve variables and opam files.

- [OpamPath.Switch file paths](https://github.com/ocaml/opam/blob/c35eb977d19457d3f13b31c1aa60de4fb210865d/src/format/opamPath.ml#L77-L139) ([opam2nix version](https://github.com/timbertson/opam2nix/blob/1ffd0231c972bef5d741f178072593bee98c62da/src/vars.ml#L40-L61), although fairly different). This one's not a big deal and might be too hard to bother detaching from state, it was mostly just reading the docs to replicate but would be neat if it could be shared.

And.. that's it actually, most of the rest of the code is necessarily different and makes use of opam internals where appropriate, so thanks :)

**Comment by rjbou** [comment]
First sorry for delay, and thank you very much for the experience sharing!
The states are quite omnipresent in opam, as they are the main point on which we rely for most of actions. 

For `get_conflicts` and `prepare_package_build`, switch state argument can be removed in favor of `lookup` function (and the opam file for the second). It is usually done that way to ease the function call, to not define `~lookup:(fun nv ->OpamPackageVar.resolve ~package:nv st)` for each call. In the other hand, these functions are only called once or two in the same module.

For `OpamPath.Switch` functions, these paths are defined according opam internals structure, so it's quite hard to externalise them. A (hackish?) workaround would be to use the `OpamSwitch.of_string` to retrieve the `switch` string (if there is no `.` nor `/` in it), get the `OpamPath.Switch.xxx` path, and remove from it the `OpamPath.Switch.meta_dirname` string.

And thank you for using opamlib!

**Comment by timbertson** [comment]
Thanks! I actually started on a branch to implement some of these a while ago, I've just put it up as a WIP in #4147. Please let me know what you think of these changes, and I'll try to integrate them with `opam2nix` if they look reasonable.
