### ISSUE TITLE
Custom command aliases support, like git has

### ISSUE THREAD

**Issue by XVilka** [ocaml/opam#4035]
Sometimes opam commands get long for some common commands. Would be nice to have a mechanism to define a custom command aliases, e.g. like git does with `.gitconfig`:
```gitconfig
[alias]
   c = commit --verbose
   l = log --graph --decorate --oneline
```

**Comment by Khady** [comment]
You can emulate such behavior:

```
$ opam foo
#  switch   compiler                             description
→  4.09.0   ocaml-base-compiler.4.09.0           4.09.0
   default  ocaml-base-compiler.4.09.0           default

[WARNING] The environment is not in sync with the current switch.
          You should run: eval $(opam env)
$ cat ~/bin/opam-foo
#!/usr/bin/env bash

opam sw $@
```

**Comment by rjbou** [comment]
Aliases are not supported by opam, at least not via user configuration (there is some internal aliases). We use `cmdliner`, and it completes the command when there is no ambiguity, e.g. `opam sw c .` for switch creation.

We could add it in the `opamrc`, but first we need to see how and if `cmdliner` handles it easily.
