### ISSUE TITLE
Feature request: Add the --download-only option to opam install

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#4036]
Sometimes when testing stuff or for other reasons, we might want to download just the archives we need before installing them.

Would it be possible to get this option added to the `opam install` command?

**Comment by rjbou** [comment]
related to #2895

**Comment by talex5** [comment]
This would also be really useful for ocaml-ci. We want to do the download step with opam having write access to a shared download cache, but perform the builds themselves (which contain untrusted code) with read-only access.
