### ISSUE TITLE
"opam remove -a" fails with conflicting query

### ISSUE THREAD

**Issue by RalfJung** [ocaml/opam#4037]
Doing `opam remove -a` fails, saying

```
$ opam remove -a
The following dependencies couldn't be met:
  - ocaml-system → ocaml → ocaml-variants
      conflict with the base packages of this switch
  - ocaml-system → ocaml → ocaml-system (< 4.04.3~ | >= 4.06.0)
      unmet availability conditions, e.g. sys-ocaml-version = "4.10.0"
  - ocaml-system → ocaml → ocaml-config
  - ocaml-system → ocaml → ocaml-base-compiler != 4.05.0
      conflict with the base packages of this switch
Your request can't be satisfied:
  - Conflicting query for package ocaml-config.1
```

Looks like https://github.com/ocaml/opam/issues/3662 is back? Doesn't look like a test case was added.

My installed packages are:
```
$ opam list
# Packages matching: installed
# Name           # Installed # Synopsis
base-bigarray    base
base-bytes       base        Bytes library distributed with the OCaml compiler
base-num         base        Num library distributed with the OCaml compiler
base-threads     base
base-unix        base
cmdliner         1.0.4       Declarative definition of command line interfaces for OCaml
conf-g++         1.0         Virtual package relying on the g++ compiler (for C++)
conf-m4          1           Virtual package relying on m4
conf-perl        1           Virtual package relying on perl
cppo             1.6.6       Code preprocessor like cpp for OCaml
cudf             0.9         CUDF library (part of the Mancoosi tools)
dose3            5.0.1       Dose library (part of Mancoosi tools)
dune             1.11.4      Fast, portable and opinionated build system
extlib           1.7.6       A complete yet small extension for OCaml standard library (reduced, recommended)
jbuilder         transition  This is a transition package, jbuilder is now named dune. Use the dune
mccs             1.1+10      MCCS (which stands for Multi Criteria CUDF Solver) is a CUDF problem solver developed at UNS during the European MANCOOSI project
num              0           The Num library for arbitrary-precision integer and rational arithmetic
ocaml            4.05.0      The OCaml compiler (virtual package)
ocaml-config     1           OCaml Switch Configuration
ocaml-system     4.05.0      The OCaml compiler (system version, from outside of opam)
ocamlbuild       0.14.0      OCamlbuild is a build system with builtin rules to easily build most OCaml projects.
ocamlfind        1.8.1       A library manager for OCaml
ocamlgraph       1.8.8       A generic graph library for OCaml
opam-client      2.0.5
opam-core        2.0.5
opam-devel       2.0.5
opam-file-format 2.0.0       Parser and printer for the opam file syntax
opam-format      2.0.5
opam-repository  2.0.5
opam-solver      2.0.5
opam-state       2.0.5
re               1.9.0       RE is a regular expression library for OCaml
result           1.4         Compatibility Result module
seq              0.2         Compatibility package for OCaml's standard iterator type starting from 4.07
topkg            1.0.1       The transitory OCaml software packager
```

```
# opam config report
# opam-version      2.0.4 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=debian os-version=testing
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              8
# repositories      4 (http), 4 (local), 1 (version-controlled) (default repo at 7b81d837)
# pinned            1 (rsync)
# current-switch    system
```

**Comment by RalfJung** [comment]
It might be potentially related that this switch seems odd in the sense that base-bigarray, base-threads and base-unix are underlined in `opam list`, which is not the case for any of my other switches. Trying to de-underline them with `opam install --unset-root` fails saying
```
[NOTE] Package base-unix is part of the compiler base and can't be set as 'installed automatically'
[NOTE] Package base-threads is part of the compiler base and can't be set as 'installed automatically'
[NOTE] Package base-bigarray is part of the compiler base and can't be set as 'installed automatically'
```
which is odd at best given that the same packages *are* not set "installed automatically" in other switches.

**Comment by rjbou** [comment]
Yes, seems that `ocaml-config` hasn't been set as a base/compiler package. Can you check with `opam list --base` ?
To unlock you quickly, you can add it to base/compiler packages with `opam switch set-base ocaml-config`.
Is it a switch that you updated or fully installed ?

@AltGr is working in a PR to replace base package with switch invariants (#3894).

**Comment by RalfJung** [comment]
(A few things changed since my last message as my system OCaml got upgraded, but the error remains.)

> Can you check with opam list --base ?

```
$ opam list --base
# Packages matching: base
# Name        # Installed # Synopsis
base-bigarray base
base-threads  base
base-unix     base
ocaml-system  4.08.1      The OCaml compiler (system version, from outside of opam)
```

> you can add it to base/compiler packages with opam switch set-base ocaml-config.

This worked, thanks. :)

> Is it a switch that you updated or fully installed ?

This is the default system switch and it got upgraded many times. It might even have been originally created with opam 1.

In another switch, `list --base` looks as follows:
```
base-bigarray base
base-threads  base
base-unix     base
ocaml         4.05.0      The OCaml compiler (virtual package)
ocaml-system  --          The OCaml compiler (system version, from outside of opam)
```
So, `ocaml-confg` is also not in there, but `ocaml` is. Also (not visible in the copy-paste), in the latter switch, the "base-*" packages are *not* underlined while in the default system switch, they are. I have not yet figured out how to "fix" this inconsistency. (It's not a big deal but I like things to be consistent. :D )

**Comment by rjbou** [comment]
> I have not yet figured out how to "fix" this inconsistency. 

I have to say that actually there is no way to "fix" it, without going deep in opam internal files.
If it is a switch that lived so long, did you manually updated its compiler? I'm wondering what made in one switch to have your base package all in root packages, the normal case (now) is that only the main compiler package (`ocaml-{system,base-compiler,variants}`) is marked as root.

On you second switch, does it have a compiler ? seems that `ocaml-system` is not installed even if marked as base (no version shown).

> It's not a big deal but I like things to be consistent. :D

I know that feeling :D If you want, I can provide guidance into _internals_

**Comment by RalfJung** [comment]
> On you second switch, does it have a compiler ? seems that ocaml-system is not installed even if marked as base (no version shown).

Ah, that is likely because my system ocaml got updated and I didn't yet rebuild all the things.

> I know that feeling :D If you want, I can provide guidance into internals

Thanks, but I think it's not worth it. ;)
If some day it bothers me enough, I'll delete and re-create that switch...

**Comment by rjbou** [comment]
Closing this issue, feel free to reopen it if needed.
