### ISSUE TITLE
opam man pages not updated

### ISSUE THREAD

**Issue by fblanqui** [ocaml/opam#4044]
`man opam-switch` tells that there is an option `--all` for `opam switch list` but it fails when we use it:
```
11:09 ~ opam switch --all
opam: unknown option `--all', did you mean `--full' ?
Usage: opam switch [OPTION]... [COMMAND] [ARG]...
Try `opam switch --help' or `opam --help' for more information.
```

```
# opam config report
# opam-version      2.0.0 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=ubuntu os-version=18.04
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              4
# repositories      2 (http), 1 (version-controlled) (default repo at b340a39e)
# pinned            0
# current-switch    4.07.1
```

**Comment by rjbou** [comment]
You seem to have an issue in manpage settings. `--all` option doesn't exist & `--list-available` exists.
Can you check and share your `MANPATH`?

**Comment by fblanqui** [comment]
```
15:12 ~ echo $MANPATH
:/home/blanqui/.opam/4.09.0/man
```

**Comment by rjbou** [comment]
You should have opam 2.0.0 manpages then. Does `opam switch --help` gives you the same manpages that `man opam switch` ?

**Comment by fblanqui** [comment]
No:
```
17:43 ~ opam switch --help | head -n 20
opam-switch(1)                    Opam Manual                   opam-switch(1)



NAME
       opam-switch - Manage multiple installation prefixes.

SYNOPSIS
       opam switch [OPTION]... [COMMAND] [ARG]...

DESCRIPTION
       This command is used to manage "switches", which are independent
       installation prefixes with their own compiler and sets of installed and
       pinned packages. This is typically useful to have different versions of
       the compiler available at once.

       Use opam switch create to create a new switch, and opam switch set to
       set the currently active switch. Without argument, lists installed
       switches, with one switch argument, defaults to set.

Fatal error: exception Sys_error("Broken pipe")

17:43 ~ man opam switch | head -n 20
<standard input>:111: warning [p 3, 2.8i]: can't break line
<standard input>:111: warning [p 3, 3.2i]: can't break line
<standard input>:169: warning [p 4, 6.3i]: can't break line
<standard input>:209: warning [p 5, 4.3i]: can't break line
OPAM-SWITCH(1)                  Opam Manual                  OPAM-SWITCH(1)

NAME
       opam-switch - Manage multiple installation of compilers.

SYNOPSIS
       opam switch [OPTION]... [COMMAND] [ARG]...

DESCRIPTION
       This command allows one to switch between different compiler
       versions, installing the compiler if opam switch is used to switch
       to that compiler for the first time. The different compiler versions
       are totally independent from each other, meaning that OPAM maintains
       a separate state (e.g. list of installed packages...) for each.

       See the documentation of opam switch list to see the compilers which
       are available, and how to switch or to install a new one.

COMMANDS
       Without argument, defaults to list.
```

**Comment by rjbou** [comment]
How did you install/update opam ?

**Comment by fblanqui** [comment]
Well, I do not remember exactly. It's a local installation. So, I guess I got back the sources and compiled them in my local bin dir. It's not a system-wide install.

**Comment by fblanqui** [comment]
I see. Perhaps things are mixed between the opam 1.2.2 version of the system and my local 2.0.0 version...

**Comment by rjbou** [comment]
If you compiled using sources, and installed with `make install`, you should have opam man pages in `<prefix>/share/man`.

**Comment by fblanqui** [comment]
No, I have no man pages for opam in <prefix>/...

**Comment by rjbou** [comment]
Yes, I think that youhave older version man pages installed system wide. To have those manpages you must have installed _via_ os or sources. They are not updated/installed with the `install.sh` script.

**Comment by fblanqui** [comment]
So, it seems that the man pages of opam 2.0.0 have not been installed...

**Comment by rjbou** [comment]
From sources ?

**Comment by fblanqui** [comment]
I guess so. But I don't know why.

**Comment by fblanqui** [comment]
How can I get the man pages of opam 2.0.0?

**Comment by rjbou** [comment]
[(almost) All distributions](https://opam.ocaml.org/doc/Distribution.html) have now opam 2.0 packages, you can install from you OS if wanted. If you installed 2.0 from sources, you can rerun the trilogy command ` configure <don't forget prefix if needed> ; make ; make install ` from your local sources (or [link](https://github.com/ocaml/opam/archive/2.0.0.tar.gz)).

**Comment by fblanqui** [comment]
Thanks! I removed my old system-wide opam 1.2.2 (I had to remove the man pages by hand), and installed opam 2.0.5 from sources. It works well.

**Comment by rjbou** [comment]
Great!

**Comment by balanco** [comment]
short summary:
Addendum re: manual removal of ocaml system files:
there may be _multiple_ system packages in the ocaml installation (e.g., `ocaml-interp` in Ubuntu).

[rjbou]:
> Thanks! I removed my old system-wide opam 1.2.2 **(I had to remove the man pages by hand)**, and installed opam 2.0.5 from sources. It works well.

Hello rjbou,

I failed to find any specification of your operating environment (apologies if I overlooked), but note that e.g. under Ubuntu 16.04.LTS next to a package named `ocaml` there is an _additional_ package named `ocaml-interp` that provides, among others, the manual pages and the `ocaml` executable.

Even though you already adventured into manually deleting system files (and I do empathise with that!), you may still want to investigate whether you have any further ocaml-related system packages still "officially installed", and, if so, delete (purge) them through your package manager, in order to catch any other files left around that might interfere with your new installation.

Kind regards!

**Comment by rjbou** [comment]
Thanks @balanco for the clarification.
ping @fblanqui that had the (workaround) problem.

**Comment by dra27** [comment]
Indeed, for Debian and derivatives, `dpkg -S /path/to/file` will reveal the package responsible for that file
