### ISSUE TITLE
opam switch list-available --repositories https://opam.ocaml.org/ does not work

### ISSUE THREAD

**Issue by tari3x** [ocaml/opam#4050]
```
~> opam --version 
2.0.5
~> opam switch list-available --repositories https://opam.ocaml.org/
# Listing available compilers from repositories: https://opam.ocaml.org/
# No matches found
```

Am I doing something wrong?

**Comment by tari3x** [comment]
https://opam.ocaml.org/ is set as my default, so list-available without flags does not work either. Should my default repo be something else?

**Comment by rjbou** [comment]
> `opam switch list-available --repositories https://opam.ocaml.org/`

There is a confusion in the `--repositories`  argument: you want to give the url, but opam takes it as a repo name / identifier.
```
--repositories=REPOS
           [...] REPOS should be a comma-separated list of either already registered repository names (configured through e.g. opam repository add --dont-select), or NAME=URL bindings, in which case NAME should not be registered already to a different URL, and the new repository will be registered. [...]
```

Can you check with `opam repository --all` that https://opam.ocaml.org is set as you default (3rd column) or just named default (1st column) ?

```
opam repo --all
# Repository    # Url                                      # Switches(rank)
default              https://opam.ocaml.org         <default>(1) [...]
```

Cf. also #3396

**Comment by tari3x** [comment]
I think it was set as a default one, at least according to my previous message. Since then I nuked and recreated my opam, so sadly I can't confirm. After starting from scratch things work fine.

**Comment by tari3x** [comment]
I guess fine to close for now, I'll let you know if see this again.

**Comment by rjbou** [comment]
Sure!
