### ISSUE TITLE
opam update not working

### ISSUE THREAD

**Issue by pzavar** [ocaml/opam#4062]
I am trying to use Opam for the first time but couldn't properly "opam init":

```
<><> Required setup - please read <><><><><><><><><><><><><><><><><><><><><><><>

  In normal operation, opam only alters files within ~/.opam.

  However, to best integrate with your system, some environment variables
  should be set. If you allow it to, this initialisation step will update
  your bash configuration by adding the following line to ~/.profile:

    test -r /home/pzavar/.opam/opam-init/init.sh && . /home/pzavar/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

  Otherwise, every time you want to access your opam installation, you will
  need to run:

    eval $(opam env)

  You can always re-run this setup with 'opam init' later.

Do you want opam to modify ~/.profile? [N/y/f]
(default is 'no', use 'f' to choose a different file) y
A hook can be added to opam's init scripts to ensure that the shell remains in sync with the opam environment when they
are loaded. Set that up? [y/N] y

User configuration:
  ~/.profile is already up-to-date.
[NOTE] Make sure that ~/.profile is well sourced in your ~/.bashrc.
```

I thought it initialized properly and I went and added "eval $(opam env)" into my ~/.bashrc file to not have to run the command every time.

The Problem: I cannot use ```opam install``` to install anything else. I thought I had to update my opam using ```opam update``` but face this problem:

```
Processing  1/1: [default: http]rm: cannot remove '/home/pzavar/.opam/repo/default.new/packages': Permission denied
rm: cannot remove '/home/pzavar/.opam/repo/default.new/packages': Permission denied
[ERROR] Could not update repository "default": Cannot remove /home/pzavar/.opam/repo/default.new (error 1).
```

What's the problem?

Thank you!

**Comment by dbuenzli** [comment]
By reading the error messages it seems you have permission errors in your `.opam` repository. Did you maybe once invoke opam with sudo ? 

In any case either start over by removing `.opam` or do something like : 
```
chown -R pzavar ~/.opam
```

**Comment by pzavar** [comment]
I think I definitely did at least once invoke opam with sudo. Is that what my mistake could have been?

Also, could you kindly instruct me on how I can remove ```.opam``` from my Ubuntu? 

Thanks.

**Comment by dbuenzli** [comment]
> I think I definitely did at least once invoke opam with sudo. Is that what my mistake could have been?

Yes


> Also, could you kindly instruct me on how I can remove `.opam` from my Ubuntu?

`sudo rm -rf /home/pzavar/.opam`

**Comment by rjbou** [comment]
> I thought it initialized properly and I went and added "eval $(opam env)" into my ~/.bashrc file to not have to run the command every time.

You don't need to add  `eval $(opam env)` in your bashrc, if you answer `yes` to the shell hook question (last one), opam install the good scripts in your bashrc. The script evaluates `opam env` at each command prompt, to keep your env synchronised.

**Comment by rjbou** [comment]
Closing this issue, feel free to reopen if needed.
Thanks!
