### ISSUE TITLE
Regression: Opam 2.0.6 fails any build with cache-related bwrap error [cache as link]

### ISSUE THREAD

**Issue by vphantom** [ocaml/opam#4068]
Possibly related to #4012, after updating from 4.0.5 to 4.0.6 I can no longer upgrade anything.  I consistently get, for packages I tried (`ppx_tools`, `dune`):

```text
### output ###
# bwrap: Can't mkdir /home/lis/.cache/dune: No such file or directory
```

Note that in my setup, `/home/lis/.cache` is a symbolic link to `/tmp/` (which is in RAM with `tmpfs`). If I remove directory `/tmp/dune` it does get re-created, despite what the above error implies.

Downgrading to 4.0.5 restores normal behavior, hence my suspicion that opam may be at fault.

```text
lis@titanium:~$ opam config report
# opam config report
# opam-version      2.0.6
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=debian os-version=10.2
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              7
# repositories      1 (http) (default repo at 4585683c)
# pinned            0
```

**Comment by AltGr** [comment]
Thanks for the report.
Until we figure a way to fix it, you might want to try to use a `mount --bind` instead of a symlink to work around it.

**Comment by rjbou** [comment]
or use the `XDG_CACHE_HOME` env variable (cf. [script](https://github.com/ocaml/opam/blob/2.0/src/state/shellscripts/bwrap.sh#L77))

**Comment by sanette** [comment]
I'm having the same issue with 2.0.7 when trying to install opam+ocaml on a remote machine running ubuntu 18.04 LTS

(installed using `sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)`)

```
#=== ERROR while compiling ocaml-base-compiler.4.11.1 =========================#
# context     2.0.7 | linux/x86_64 |  | https://opam.ocaml.org#74a744bd
# path        /data/home/san/.opam/default/.opam-switch/build/ocaml-base-compiler.4.11.1
# command     /data/home/san/.opam/opam-init/hooks/sandbox.sh build ./configure --prefix=/ome/san/.opam/default -C
# exit-code   1
# env-file    /tmp/opam-san-26147/ocaml-base-compiler-26147-8c0dd3.env
# output-file /tmp/opam-san-26147/ocaml-base-compiler-26147-8c0dd3.out
### output ###
# bwrap: Can't mkdir parents for /home/san/.cache/dune: No such file or directory
```

**Comment by rjbou** [comment]
The fix will be available in 2.0.8

**Comment by vphantom** [comment]
Hi! Sorry to be a drag, but 2.0.8 still produces the same error for me when `~/.cache` is a symlink to `/tmp/`:

```text
### output ###
# bwrap: Can't mkdir /home/lis/.cache/dune: No such file or directory
```

I still have to work around it with:

```sh
#!/bin/sh
export XDG_CACHE_HOME=/tmp/
exec opam-2.0.8 "$@"
```

**Comment by dra27** [comment]
@vphantom - have you updated the sandbox script?

**Comment by vphantom** [comment]
If by sandbox script you mean my 2-liner which defines `$XDG_CACHE_HOME`, then yes the first thing I tried was to run `opam init` and `opam upgrade` directly with 2.0.8 unwrapped, which reproduced the error.  Wrapping 2.0.8 the same way I wrapped 2.0.6 and 2.0.7 solves the issue.

This is with `opam-2.0.8-x86_64-linux` from the GitHub release files.

**Comment by rjbou** [comment]
Did you run `opam init` or `opam init --reinit -ni` ? To check if the sandbox file contains the fix, you can see if there is [this](https://github.com/ocaml/opam/blob/master/src/state/shellscripts/bwrap.sh#L78) piece of code in your `~/.opam/opam-init/hooks/sandbox.sh`.

#4414 related

**Comment by vphantom** [comment]
Ah I couldn't find the instructions back, about adding `--reinit -ni` when updating, I knew it wasn't just `init`… argh.

Yup, the piece of code is there now and opam works without the wrapper. 😃

**Comment by rjbou** [comment]
It is reminded in each blog post release, but 2.0.8 one is not yet published :D

**Comment by jrtc27** [comment]
On my system, /home -> /homes -> /auto/homes, which I believe runs into a similar issue; I see the same error even on 2.0.8. Is that something that can be easily fixed?

**Comment by jrtc27** [comment]
... never mind, now it works, I think I didn't `opam init` after upgrading from 2.0.7 to 2.0.8 to get the new hooks.
