### ISSUE TITLE
Test after install

### ISSUE THREAD

**Issue by liyishuai** [ocaml/opam#4069]
It seemed that `run-test` is performed before `install`.
Is there a packaging configuration that allows running some tests after installing the package?
If no, is it worth having one?

**Comment by rjbou** [comment]
Out of curiosity, why do you want test to be run after install ?
The idea is to test that package is fully functionnal (with checks) before installing it, in order to not install a broken library/progam.

**Comment by liyishuai** [comment]
Say that my [test suite](https://github.com/QuickChick/QuickChick/blob/master/examples/multifile-mutation/Makefile#L1) assumes that the binary executable was installed in PATH, rather than pointing to a relative path where the program was built.

**Comment by rjbou** [comment]
On solution is to not use the `run-test:` field, but add you test in `install:` 
```
install: [
    [ make "install"]
    [ "laucnh" "tests" ] {with-test}
]
```

**Comment by rjbou** [comment]
Where you able to sort this out ?

**Comment by liyishuai** [comment]
Yes, solved.
