### ISSUE TITLE
Add a configure option to disable z3 support

### ISSUE THREAD

**Issue by Armael** [ocaml/opam#4070]
Currently, opam builds with z3 if it is installed in the system or in opam. 

However, this is somewhat annoying because the `z3` opam package requires adding `~/.opam/<switch>/lib/z3` to `LD_LIBRARY_PATH`, otherwise the binary won't start. I'd rather have a configure option to opt out of z3 even if it is installed.

**Comment by kit-ty-kate** [comment]
For the record, if you're having trouble with opam&z3, `opam-health-check` uses `Z3` statically linked. See this branch: https://github.com/kit-ty-kate/opam/commits/opam-health-check (in particular the new `src/client/linking.sexp` file)

**Comment by rjbou** [comment]
ping @AltGr

**Comment by rjbou** [comment]
You can add in the `<opamroot>/config` file the [solver](https://opam.ocaml.org/doc/Manual.html#configfield-solver) that you want to use. For a not permanent change, you can use the general option `--solver` to specify the solver when you don't want z3.
Ftm you need to edit the file, but global & switch option configuration will be available via cli.

**Comment by rjbou** [comment]
Closing ftm, feel free to reopen if needed. Thanks!
