### ISSUE TITLE
"opam install" and environment variables? [OPAMLOG dropped]

### ISSUE THREAD

**Issue by chetmurthy** [ocaml/opam#4076]
>   If your issue concerns a package not building, please report to
>   https://github.com/ocaml/opam-repository/issues or to the package maintainer
>   unless you are confident it is an issue in the opam tool itself.

```
<include here the output of `opam config report`, if applicable>
```
I'm using opam v 2.0.6 (on both Debian Stretch and the most recent Ubuntu LTS), and I notice that the environment variable OPAMLOGS doesn't seem to work?  I searched the sources and couldn't find any mention of it?  And certainly it doesn't seem to have any effect -- logs appear, but in OPAMROOT/log.

**Comment by Armael** [comment]
Have you tried enabling `OPAMKEEPLOGS` in combination with the option?
(the environment variable does appear in the source, but you have to search for `"LOGS"`, and then `log_dir`, the associated option name).

**Comment by chetmurthy** [comment]
Yep, I set both env vars, and just to be sure, I did it just now and include the transcript.

```
chet@twitter:~/Hack/Camlp5/tmp$ l
./  ../
chet@twitter:~/Hack/Camlp5/tmp$ OPAMKEEPLOGS=1 OPAMLOGS=`pwd` opam install camlp5
The following actions will be performed:
  ∗ install camlp5 7.10

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[camlp5.7.10] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed camlp5.7.10
Done.
chet@twitter:~/Hack/Camlp5/tmp$ ls
chet@twitter:~/Hack/Camlp5/tmp$ opam --version
2.0.4
chet@twitter:~/Hack/Camlp5/tmp$ ocaml --version
The OCaml toplevel, version 4.09.0
```

**Comment by rjbou** [comment]
After some investigation, it seems that the `OPAMLOGS` variable content is not kept in the end of the configuration. This feature is quite not used, as git blame give to an 2015 commit :D 
Thanks for the report!
