### ISSUE TITLE
Sandbox script doesn't work with newer versions of ccache

### ISSUE THREAD

**Issue by lpw25** [ocaml/opam#4079]
[It seems](https://ccache.dev/releasenotes.html#_ccache_3_7) that ccache 3.7 changed the name of its `--print-config` argument to `--show-config`. This means that the sandboxing script is now broken if you use ccache with a customized `ccache_dir`. It seems that `--print-config`/`--show-config` is available as `-p` both before and after the rename -- so the easiest fix is probably to use that.

**Comment by lpw25** [comment]
The symptoms of this are that any package that uses the C compiler in its build will fail with weird errors. In particular, the OCaml's configure script will fail in very strange ways.

**Comment by rjbou** [comment]
Thanks for the report!
It can be convenient to also also an environment variable, to prevent future changes, like that no need to go change the sandbox script in case of ccache dir misdetection.
