### ISSUE TITLE
RPM packages for OPAM

### ISSUE THREAD

**Issue by agarwal** [ocaml/opam#409]
**[edit: previous title was "opam_installer.sh fails with GLIBC not found error on RHEL"]**

On my Mac, opam_installer.sh runs fine. But on two RHEL systems, I get:

```
$ sh ./opam_installer.sh ~/bin 4.00.1+short-types
Downloading OPAM...
Do you need to use sudo to write to /home/aa144/bin (y/N) ?

Initializing with compiler 4.00.1+short-types
opam: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by opam)
```

Is it an error in opam? I compile numerous other software without any problems.

**Comment by ansiwen** [comment]
This is still (again?) an issue... all copr repositories are dead... :disappointed:

**Comment by ANogin** [comment]
OpenSUSE Build Service links are all 404 right now - is there an alternative source for these RPMs? Thanks!
