### ISSUE TITLE
`opam-format` failing due to warn-error on 4.10.0-rc2

### ISSUE THREAD

**Issue by mgree** [ocaml/opam#4100]
In https://travis-ci.com/mgree/opam-repository/jobs/291122531, I'm getting a failure from `opam-format` because of deprecation warnings and the build sets `-warn-error`.

It's slightly tricky to get the output of `opam config report`, unfortunately, because all of this is happening within CI.

**Comment by rjbou** [comment]
I just tested on `4.10.0` & `4.10.0-rc2` switches, `opam-format` build prints well those warnings, but don't error on them. There is the `-warn-error A-3`, but in that case, it should have errored multiple times on the module deprecation...

In any case, this module deprecation will be removed.
Thanks for the report

**Comment by rjbou** [comment]
Fixed by #4115
