### ISSUE TITLE
constraints don't work for packages that do not have the patch version

### ISSUE THREAD

**Issue by ivg** [ocaml/opam#4101]
As a high-level demonstration, a freshly created opam switch:
```
$ opam --version
2.0.3
$ opam show zed | grep result
              "result" {< "1.5.0"}
$ opam install zed | grep result
  ∗ install result         1.5    [required by zed]
```
As we can see, result.1.5.0 is still selected for the installation despite the fact that it zed requires an older version. An interesting thing is that in [his PR] @avsm  specified explicitly "1.5" not "1.5.0" and this is what is currently written in the opam files of zed in the master branch, but, for some reason, it is somewhere normalized from 1.5 to 1.5.0 back. And indeed, according to the `opamVersionCompare.ml` (loaded to my toplevel), we see that 1.5 is indeed less than 1.5.0 therefore it is installed.
```
 # compare "1.5" "1.5.0";;
- : int = -1
```

See also, @mjambon [15909][2] PR, which in its original form should work - a workaround right now would be to set the constraint to `<= "1.4.0"` or just to `= 1.4.0`

Note, this issue could be fixed in the later opams (I didn't find any reference to that though), but on opam 2.0.3 I am unable to install zed right now, despite 15906 and 15909 being merged (with the latter reverted, but it doesn't matter). 

[1]: https://github.com/ocaml/opam-repository/pull/15906
[2]: https://github.com/ocaml/opam-repository/pull/15909

**Comment by ivg** [comment]
Ok, so the problem is that opam.org wasn't yet updated to the git version and while I was looking into the git file, the meta was taken somewhere from opam.org caches. So @mjambon's fix with `< "1.5"` works, but is not yet deployed, and Anil's one is in the current opam.ocaml.org and is broken. 

Closing the issue, though, to be honest, I think that the comparison function is broken as 1.5 should be equal to 1.5.0.

**Comment by hannesm** [comment]
> though, to be honest, I think that the comparison function is broken as 1.5 should be equal to 1.5.0.

I agree with this statement, and find it very counterintuitive how opam versions numbering comparison is done (and no, it doesn't help that "it is the same as in debian").

**Comment by avsm** [comment]
Unfortunately, it is defined as "it is the same as in debian" for now, so at least we are consistent.  I also agree the current behaviour is unintuitive, as I introduced the bug above :-)

**Comment by ivg** [comment]
Could we add a lint check for packages that use non-semver-compliant packages? Like if we will softly (but firmly) forbid packages with versions that do not have three parts in them, i.e., <major>.<minor>.<patch>` then we won't have this problems.
