### ISSUE TITLE
Add a default number of retries for download

### ISSUE THREAD

**Issue by XVilka** [ocaml/opam#4113]
Currently it stops the whole installation process if something failed to be downloaded. If it breaks because of the poor network I have to start it again from the beginning. Would be awesome to have some minimum number of retries by default - 3 for example.

**Comment by rjbou** [comment]
It is already the case. `curl` and `wget` are called with `--retry` option, and default number of retries is 3. You can configure it using `OPAMRETRIES` env variable.

What os/distro are you using ? From what I see, `fetch`/`ftp` that are the default for FreeBsd/OpenBSD don't use this retry option.

**Comment by XVilka** [comment]
Thank you for the answer. Yes, I caught the bug on FreeBSD

**Comment by rjbou** [comment]
It definitely make sense yes, but this option, nor [`ftp`](https://man.openbsd.org/ftp.1#r) one, is sure to terminate as there is no option to set number of retries, only another option to timeout for `fetch`.

To make it work for you, you can set a new download command  by setting `OPAMFETCH`:
```
       OPAMFETCH specifies how to download files: either `wget', `curl' or a custom command where 
variables %{url}%, %{out}%, %{retry}%, %{compress}% and %{checksum}% will be replaced. 
Overrides the 'download-command' value from the main config file.
```

**Comment by XVilka** [comment]
Thanks, closing then as solved.
