### ISSUE TITLE
Add command-line access to switch-config setenv

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [ocaml/opam#4119]
The `switch-config` file has a field `setenv` that can be used to modify environment variables. However, there does not appear to be a way to access this field through the command-line. This contrary to `vars`, for which there is `opam config set` and `opam config unset`. It would be nice if there could be commands like `opam config set-env` and `opam config unset-env`. Especially since Opams config files are not very easy to parse by external tools.

**Comment by rjbou** [comment]
Integrated in #4116. Thanks for the issue!

**Comment by LasseBlaauwbroek** [comment]
Nice! That was very quick... Thanks!

**Comment by rjbou** [comment]
Merged!
