### ISSUE TITLE
opam init regression on raspberry pi 4 / raspian

### ISSUE THREAD

**Issue by mro** [ocaml/opam#4126]
working fine in version d6e4e4ac, failing in 1bab95d0.

Culprit IMO the `bwrap` call including `/lib32` et.al. which aren't there on [raspian](https://downloads.raspberrypi.org/raspbian/images/raspbian-2020-02-14/).

**Comment by rjbou** [comment]
Thanks for the report!
If it is a sandbox script error, it's weird that opam fails only from that commit: opam calls sandboxing on package installation process, the latest commit is not sandboxing related.
Can you share the failing command & output ?

**Comment by rjbou** [comment]
After checking, I don't think that the call with `/lib32` & co is the error, there is a [check](https://github.com/ocaml/opam/blob/master/src/state/shellscripts/bwrap.sh#L29) that the directory exists before mounting it. Plus, these directories weren't added recently.

**Comment by mro** [comment]
@rjbou I cannot reproduce. That's very embarrassing and I apologize for wasting your time. In case I run into such again, I'll immediately seize the logs.

**Comment by mro** [comment]
just for the record, that were the precise commands https://blog.mro.name/2020/04/bootstrap-raspi4-ocaml/#ocaml
