### ISSUE TITLE
`opam remove` should not take constraints into account

### ISSUE THREAD

**Issue by anton-trunov** [ocaml/opam#4130]
After installing `coq-color` package like this
```shell
$ opam install coq-color --ignore-constraints-on=coq-mathcomp-finmap
The following actions will be performed:
  ∗ install coq-color 1.7.0

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
[coq-color.1.7.0] downloaded from https://gforge.inria.fr/frs/download.php/file/38188/color.1.7.0.tar.gz

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
∗ installed coq-color.1.7.0
Done.
```

I needed to remove it immediately, but got an error
```shell
opam remove coq-color
The following dependencies couldn't be met:
  - coq-mathcomp-analysis → coq-mathcomp-finmap < 1.4.1 → coq-mathcomp-ssreflect <
    1.8~ → coq < 8.10~
      not available because the package is pinned to version 8.11.1
  - coq-mathcomp-analysis → coq-mathcomp-finmap < 1.4.1 → coq < 8.11~
      not available because the package is pinned to version 8.11.1
Your request can't be satisfied:
  - No available version of coq-mathcomp-finmap satisfies the constraints

No solution found, exiting
```

Notice that I didn't do anything in between installation and removal.

```
# opam config report
# opam-version      2.0.6
# self-upgrade      no
# system            arch=x86_64 os=macos os-distribution=homebrew os-version=10.14.6
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              3
# repositories      4 (http), 3 (version-controlled) (default repo at 8c3b0826)
# pinned            1 (version)
# current-switch    coq8.11
```

**Comment by rjbou** [comment]
opam always tries to keep a coherent package installed universe, on removing also. Ignored constraints are not stored, so when you wanted to remove, an inconsistency was found.
To be able to remove `coq-color`, you can use also the `--ignore-constraints-on=coq-mathcomp-finmap` option with remove command.

**Comment by anton-trunov** [comment]
@rjbou Thank you, this is interesting, I thought `opam` assumed that everything installed is coherent and that removal just removes the package and the packages depending on it. (And if the coherence precondition is false then all bets are off).

I'm really curious where this model breaks, though.

**Comment by rjbou** [comment]
In fact, removing a package is a request to the solver with (roughly): remove the package & its reverse dependencies,  install all installed package (if `-a` is given, only root packages). From that, actions are computed, mostly removal, sometimes packages recompilation if the package to remove is a _depopt_.

**Comment by anton-trunov** [comment]
@rjbou Thanks a lot! Feel free to close the issue.

**Comment by rjbou** [comment]
@anton-trunov You're welcome :)

**Comment by rjbou** [comment]
Note that there is also the `OPAMIGNORECONSTRAINTS` env var, to release from giving the option multiple times. But better not forget about it :)

**Comment by anton-trunov** [comment]
Great, thanks again :)
