### ISSUE TITLE
`opam exec` fails silently if command is not found

### ISSUE THREAD

**Issue by CraigFe** [ocaml/opam#4131]
`opam exec` of a command that is not in the environment fails silently with exit code 127:

```
ᐅ opam exec foo
ᐅ echo $?
127
```

The exit code is documented in the man-page, but I think it would also be helpful to emit a short explanatory error message. For comparison, here is the equivalent output from Dune:

```
ᐅ dune exec foo
Error: Program "foo" not found!
```

**Comment by rjbou** [comment]
Thanks for the report!
