### ISSUE TITLE
Build fails on Android 9 - Linux 3.18 -  aarch64 

### ISSUE THREAD

**Issue by gabrik** [ocaml/opam#4134]
Hi all,

I'm trying to do something pretty strange.

I managed to build OCaml 4.09.0 on Android leveraging one of those CLI applications. 

Bu when trying to build opam I got this error:

```
$ make
...
File "src/colors.ml", line 105, characters 18-48:
Alert deprecated: Stdlib.Format.pp_get_formatter_tag_functions
Use Format.pp_get_formatter_stag_functions.
File "src/colors.ml", line 107, characters 6-36:
Alert deprecated: Stdlib.Format.pp_set_formatter_tag_functions
This function will erase non-string tag formatting functions. Use Format.pp_set_formatter_stag_functions.
src_ext/dune-local/_build_bootstrap/install/default/bin/dune build --profile=release  opam-installer.install opam.install
Error: exception Sys_error("/data/data: Permission denied")
Backtrace:
Raised by primitive operation at file "bin/util.ml", line 28, characters 16-31
Called from file "bin/util.ml", line 49, characters 8-44
Called from file "bin/common.ml", line 365, characters 8-25
Called from file "vendor/cmdliner/src/cmdliner_term.ml", line 27, characters 19-24
Called from file "vendor/cmdliner/src/cmdliner_term.ml", line 25, characters 12-19
Called from file "vendor/cmdliner/src/cmdliner_term.ml", line 22, characters 21-30
Called from file "vendor/cmdliner/src/cmdliner.ml", line 106, characters 32-39
Called from file "vendor/cmdliner/src/cmdliner.ml", line 136, characters 18-36
Called from file "vendor/cmdliner/src/cmdliner.ml", line 251, characters 22-48
Called from file "bin/main.ml", line 1219, characters 10-51

I must not segfault.  Uncertainty is the mind-killer.  Exceptions are
the little-death that brings total obliteration.  I will fully express
my cases.  Execution will pass over me and through me.  And when it
has gone past, I will unwind the stack along its path.  Where the
cases are handled there will be nothing.  Only I will remain.
make: *** [Makefile:114: build-opam] Error 1
```

I followed those steps for configure and for the deps:

```
$ ./configure --prefix=/data/data/com.termux/files/usr/
$ make lib-ext
```

Here some details on OCaml and C compiler version:

ocamlc 4.09.0
clang 9.0.1 

Any ideas?

**Comment by rjbou** [comment]
Intersting... I don't find any of those files on opam or its `src_ext` dependencies...

Let's dig into that!
Does `make lib-ext` ended successfully ?
Can you share the full log of `make`, via a gist maybe ?

**Comment by gabrik** [comment]
It seems that `make lib-ext` ends ok.
[Here the gits](https://gist.github.com/gabrik/988bc92f943425c2d3c4c3022d0a33b2) with the complete output from `./configure --prefix=/data/data/com.termux/files/usr/` to `make`

It seems to fail at the very end of the `dune build`

Maybe the dependencies retrieved by `make lib-ext` do not work on Android

**Comment by rjbou** [comment]
You took the 2.0.x archive, that's why I didn't found the correct files. 2.0 branch have dune 1.6.3 embed, and make fails [there](https://github.com/ocaml/dune/blob/1.6.3-release/bin/util.ml#L49). I think that the `Sys.readdir` errors on you `data/data` directory. You can try to dig into that.

**Comment by gabrik** [comment]
I see I guess it errors because of the missing of root permissions, hence it cannot do the Sys.readdir on `/data/data` I will try on a rooted device.

**Comment by gabrik** [comment]
Just tested on a `rooted` phone and everything went fine.

**Comment by ForceBru** [comment]
This doesn't solve the issue, though. Do I really have to root my phone to install opam? OCaml builds without any issues whatsoever, but opam says `Error: exception Sys_error("/data/data: Permission denied")`.

It's also saying `Raised by primitive operation at file "bin/util.ml", line 28, characters 16-31`, but it doesn't tell me where to search for that `bin/util.ml`. `find . -name util.ml` shows that it's probably `./src_ext/dune-local/bin/util.ml`, so it may be dune's fault.

Is there any reason why it's trying to mess with `/data/data` in the first place? Maybe it shouldn't touch it at all?
