### ISSUE TITLE
opam init compiler version error

### ISSUE THREAD

**Issue by BowenWang** [ocaml/opam#4145]
I was working on a server without root privilege. There is already an Ocaml installed with version 4.02.3. 

I installed my own ocaml and opam with the newest version 4.10.0 somewhere else in the system and set the PATH environment variable. In my account, the output of ocaml --vnum and ocamlc --vnum is 4.10.0.

Then I tried to run opam init but it reports an error saying:
ERROR: the compiler found at /usr/bin/ocamlc has version 4.02.3
and this package requires 4.10.0
You should use e.g. 'opam switch create ocaml-system.4.02.3' instead. 

I am very confused. I have already set the PATH environment variable, why is opam still trying to find the ocamlc in /usr/bin? Is there any solutions? I really need the newest version of ocaml and opam set up for my account.

BTW, I installed opam using the binary distribution.

**Comment by BowenWang** [comment]
According to this link: https://stackoverflow.com/questions/6585098/parallel-installation-of-different-ocaml-versions

I also need to install ocamlfind into the directory I installed ocaml and ocamlc so that opam can find the correct version of ocamlc. But It seems that ocamlfind can only be installed via opam, is there any solution to this?

**Comment by AltGr** [comment]
You should rather let opam install the compiler for you than try to setup a specific "system compiler" to run on: `opam init --compiler=ocaml-base-compiler.4.10.0`

If not recommended, what you did should have worked, though. Are you sure you properly `export`ed the `PATH` variable ?
