### ISSUE TITLE
Opam install script asks for user input, cannot use in docker container

### ISSUE THREAD

**Issue by lucaszanella** [ocaml/opam#4154]
https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh

As I understood by reading the script, there's no way to prevent it asking for user input. Thus I can't use this script to install opam in my docker container.

Shouldn't it have this feature?

**Comment by lucaszanella** [comment]
Nevermind I updated the install script: https://github.com/ocaml/opam/pull/4155

**Comment by rjbou** [comment]
`install.sh` is not intended to be used in scripts. It is meant to be interactive. Plus local install and a docker install are quite different. cf also #4136
