### ISSUE TITLE
Opam configuration corrupted on ENOSPC

### ISSUE THREAD

**Issue by g2p** [ocaml/opam#4157]
If `opam update --upgrade` encounters errors due to lack of free space, the next `opam upgrade` will attempt to remove all packages.

Looking at the `--debug` output, this is because `~/.opam/repo/repos-config` got corrupted and replaced by an empty file; all packages are considered orphaned after this.

This debug message should probably be upgraded to a user-visible warning (or error, if actively used):

```
00:00.251  STATE                  Ignoring globally-selected repository "default", no configured repository by this name found
```

Quick fix for anyone hitting this:

```
opam repository add default --set-default https://opam.ocaml.org
``` 

```
# opam config report
# opam-version      2.0.7 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=ubuntu os-version=20.04
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              7
# repositories      
# pinned            0
# current-switch    4.10.0+fp+flambda
```

**Comment by rjbou** [comment]
Thanks for the report. Opam tries to keep a consistent state when a command or an action fail, but when there is no more space, it's hard to write to good configuration.
I'll close this issue, as duplicated of #2715, we can continue the discussion there.
