### ISSUE TITLE
How to install a package from the remote archive with locally changed file

### ISSUE THREAD

**Issue by MdeLv** [ocaml/opam#4160]
I understand that `opam install foo` uses the file `.opam/repo/default/packages/foo/opam`,which means that it downloads the archive specified in the field src.
So any local change is overridden (such local change is possible if the package was successfully installed). 
Forking the upstream repo, changing a faulty file in the origin repo, them `opam pin add foo some-url-to-foo-in-origin` does the job.
However, is there a simple way to tell opam to use a local version of a file instead of the one from the automatically downloaded archive?
Thanks.

**Comment by rjbou** [comment]
You can use `opam pin --edit <archive>` to pin the package with the given archive, and opam will let you edit the opam file before installing the package. Or, if the package is already install, you can use `opam pin edit`.

**Comment by MdeLv** [comment]
Ok. Thanks.
