### ISSUE TITLE
Virtual package conf-dbm is reinstalled at each upgrade

### ISSUE THREAD

**Issue by MdeLv** [ocaml/opam#4162]
Virtual package conf-dbm is reinstalled at each upgrade, and all dependent packages are proposed for reinstallation. Just have to answer no. It's a non blocking issue. 

This issue has first been opened at opam-repository but it may be an opam issue.

Details: [conf-dbm triggers false "upstream changes" #16308](https://github.com/ocaml/opam-repository/issues/16308)
Do you have an idea of the cause and how to fix that?
opam 2.05 or 2.07

btw: when opam has been installed with https://opam.ocaml.org/doc/Install.html#Binary-distribution, can it be safely (I mean: for the ~/.opam directory) reinstalled with the package manager of the distribution? If no, can we replace safely a fresh ~/.opam directory with the backup directory?
Thanks.

**Comment by MdeLv** [comment]
Here is the result of my last test about this issue: [https://github.com/ocaml/opam-repository/issues/16308#issuecomment-621133271](https://github.com/ocaml/opam-repository/issues/16308#issuecomment-621133271).

opam doesn't download the opam file on opam-repository. 
`opam clean` doesn't solve the issue.

How can we log from where opam downloads individual files, when doing `opam install` or `opam reinstall`?
Thanks.

**Comment by rjbou** [comment]
It's the same problem than in #3995, opam file rewriting make opam detect an non-existent upstream change.
I'll close this issue, and refers to referenced one for further discussion.

**Comment by rjbou** [comment]
Thanks for the report!
