### ISSUE TITLE
Hidden re-ordering of packages passed to `opam show`

### ISSUE THREAD

**Issue by CraigFe** [ocaml/opam#4163]
When invoking `opam show` with multiple packages, the results are reported in alphabetical order of package name. This is fine (if a bit odd) when all of the metadata is displayed, but is a bit pernicious when used in combination with the `--field` option:

```bash
ᐅ opam show --field=version -- irmin ocamlformat alcotest
1.1.0
2.1.0
0.14.1
```

(Here the versions are in the order `alcotest`, `irmin`, `ocamlformat`, but this is non-obvious.)

I would expect the result order to be the same as the order of options passed to `opam show`. Failing that, the manpage for `opam show` should probably indicate that results given out-of-order.

**Comment by rjbou** [comment]
Internally, opam reorder, but I don't know if it the intended behavior since the beginning or a side-effect.
@samoht @dbuenzli how do you handle that in your scripts?

**Comment by samoht** [comment]
I don't think any of my script is relying on that order.

**Comment by avsm** [comment]
I've typically passed `--field=name,version` and parsed the output. I agree that preserving the input order would minimise surprise.
