### ISSUE TITLE
Unavailable packages are silently ignored by `opam show`

### ISSUE THREAD

**Issue by CraigFe** [ocaml/opam#4164]
... when passing more than one package.

If _all_ of the packages passed to `opam` show are non-existent, an error is shown:

```bash
ᐅ opam show --field=version -- void
[ERROR] No package matching void found

ᐅ opam show --field=version -- void1 void2
[ERROR] No package matching void1 or void2 found
```

But if only _some_ packages are non-existent, the failure is ignored:

```bash
ᐅ opam show --field=version -- dune void
2.5.0
```

I would expect error messages to be displayed individually and the exit-code to be non-zero if any error messages have been displayed.

**Comment by rjbou** [comment]
Opam should show a not found message, but i'm not sure about the exit-code, because some package were found, so it's not a hard not found failure.

Thanks for the report!
