### ISSUE TITLE
Infer switch invariant on opam2.0 switch make syscalls

### ISSUE THREAD

**Issue by rjbou** [ocaml/opam#4188]
When called in sandbox (some packages uses opam in their build / install instructions), os polling syscalls lead to an open file failure du to the read-only home rule.
To reproduce:
* have a 2.0 switch, with no `invariant` field
* run a generic `opam var x --readonly -vv` command 
* or run with sandbox script to have the failure

**Comment by dra27** [comment]
@rjbou - is this issue still active and needing fixing for 2.1?

**Comment by rjbou** [comment]
Closing, to reopen if needed / reproduced
