### ISSUE TITLE
When pinning, local paths should be fully resolved

### ISSUE THREAD

**Issue by Armael** [ocaml/opam#4208]
When pinning a local path, it looks like the path itself is not fully resolved before being registered. In particular, if it is a relative path, it is stored as is.

I ran `opam pin add foo .` while in the directory of the package I wanted to pin. Later on, I ran `opam upgrade` from my home directory: opam then started copying my entire home directory into the sources directory for the package.

I expected instead the path to be resolved to an absolute path at the time the pin was added.

**Comment by Armael** [comment]
Note: this is in the case of a pin "as files" (`file://`), not as a git repository.

**Comment by rjbou** [comment]
Thanks for the report!
This is weird because paths are fully resolved. What is your opam version ? Are you able to reproduce ? If yes, can you re run the upgrade with `-vv`, and share output.
