### ISSUE TITLE
opam accepts switch names that create unusable switches

### ISSUE THREAD

**Issue by emillon** [ocaml/opam#4231]
Hi,

Opam can create switches with some characters in their names that create unusable switches:

### colons

When a switch name contains a colon, `PATH` is extended with this switch's bin directory, but since this is a colon-separated variable (with no escape mechanism), it fails to find the right binaries:

```
% opam switch create test:a 4.09.1 
...
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
∗ installed ocaml-base-compiler.4.09.1
∗ installed ocaml-config.1
[ERROR] The compilation of ocaml failed at
        "/home/etienne/.opam/opam-init/hooks/sandbox.sh build ocaml
        /home/etienne/.opam/test:a/share/ocaml-config/gen_ocaml_config.ml 4.09.1
        ocaml".

#=== ERROR while compiling ocaml.4.09.1 =======================================#
# context     2.0.0 | linux/x86_64 | ocaml-base-compiler.4.09.1 | https://opam.ocaml.org/#9e7e7e45
# path        ~/.opam/test:a/.opam-switch/build/ocaml.4.09.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml /home/etienne/.opam/test
:a/share/ocaml-config/gen_ocaml_config.ml 4.09.1 ocaml
# exit-code   1
# env-file    ~/.opam/log/ocaml-104246-ad6566.env
# output-file ~/.opam/log/ocaml-104246-ad6566.out
### output ###
# OCaml version mismatch: 4.08.1, expected 4.09.1
```

The reason for the error message is that it tries to find `ocaml` in `PATH`, but because there's a colon in there it cannot find it and falls back to my system compiler.

This happens in a local switch as well if the directory contains colons at any level.

### shell metacharacters (backticks, dollar sign)

When a switch name (or in the case of a local switch, a directory name) contains characters that are interpreted by the shell such as backticks or dollar signs, they are interpreted during the installation. For example, a switch created in a directory named `id` (backtick, i, d, backtick) will try to create a switch named by the output of this command, and a switch named `xmessage hello` (backtick, x, ..., o, backtick) will open popup window during switch creation. A similar behavior can be observed with dollar signs. This suggests that somewhere a command is built with double quotes and passed to the shell.

### Possible security concerns

Opam is primarily a development tool, so it's expected that it will run external code or install binaries. There might be scenarios where an attacker can control a directory name or a global switch name but I don't think that should be an important concern.

Thanks!

**Comment by rjbou** [comment]
Thanks for the (detailled) report!
