### ISSUE TITLE
ocamlc unable to find packages installed by opam

### ISSUE THREAD

**Issue by EvanBoyle** [ocaml/opam#4233]
I'm trying to follow this tutorial here: https://ocaml.org/learn/tutorials/structure_of_ocaml_programs.html#Modules-and-open

There's a graphics-related code snippet that has a comment with a build command: 
```sh
ocamlc graphics.cma grtest2.ml -o grtest2

File "grtest2.ml", line 1, characters 5-13:
1 | open Graphics;;
```

Even after running `opam install graphics` I get the same output. I can build a functioning executable if I use `ocamlbuild` and `ocamlfind`:

```sh
ocamlbuild -use-ocamlfind -pkg graphics grtest2.native
```

`ocamlfind` shows that the graphics package is installed in `$(opam var lib)`:

```sh
$ ocamlfind query graphics
/Users/evanboyle/.opam/default/lib/graphics
```

But ocaml -where does not seem to be configured to look in this directory:

```
$ ocamlc -where
/Users/evanboyle/.opam/default/lib/ocaml
```

Is there some sort of config that I need to set to get this to __just work__? I initially started off with a ocaml and opam installed via brew, but deleted those installations, installed opam from the install script, and then installed the ocaml compiler via opam. Pointers to relevant docs or resources would be greatly appreciated. I have run both `opam init`, and `eval $(opam env)`.

```
$ opam config report
# opam config report
# opam-version      2.0.7 
# self-upgrade      no
# system            arch=x86_64 os=macos os-distribution=homebrew os-version=10.15.4
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              11
# repositories      1 (http) (default repo at 610bb40e)
# pinned            0
# current-switch    default
```

**Comment by rjbou** [comment]
In the tutorial, it said that `graphics` files are in `/usr/lib/ocaml/`, and opam sets the `OCAML_LD_LIBRARY_PATH` to the switch `lib/ocaml` directory (you can view it with `opam env`). The graphics opam package doesn't install in that directory, but in the `lib/graphics` switch  directory (you can view it with `opam show  graphics -f installed-files`). In that case, you need to link it on your side, you can use `ocamlbuild` as you found, or `ocamlfind` : `ocamlfind ocamlc  grtest2.ml -o grtest2 -linkpkg -package graphics` (cf. [discuss post](https://discuss.ocaml.org/t/graphics-package/1073/18)).

The would be better asked in the [discuss](https://discuss.ocaml.org) ocaml forum.

I'll close this issue, but if finally it is an opam issue, feel free to reopen it!

Thanks!

**Comment by EvanBoyle** [comment]
Fair enough. I can understand that this is by design, but I'm struggling to find anywhere where this is clearly documented. 

Perhaps some documentation that expands upon the opam layout convention and interop with ocamlc conventions would be in order. This FAQ seems like a good starting place: https://opam.ocaml.org/doc/FAQ.html#How-to-link-to-libraries-installed-with-opam

Perhaps this is more appropriately filed as a bug on the tutorial? Could we move this issue over to ocaml/ocaml.org? As written this tutorial does not seem to lead users into the pit of success.

**Comment by rjbou** [comment]
I can't move the issue, maybe @avsm? But yes, it would be better to open a issue there, or propose a pull request with the missing hint.
