### ISSUE TITLE
[opam 2.1~alpha] opam remove -a (without arguments) does not work

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#4250]
With opam 2.0, using `opam remove -a` was a useful command which removes any packages that hasn't been purposefully installed by the user.

However with opam 2.1 (master) currently, the following error is given:
```
$ opam remove -a
The following dependencies couldn't be met:
  - ocaml-variants -> ocaml = 4.11.0 -> ocaml-config
Your request can't be satisfied:
  - Conflicting query for package ocaml-config.1

No solution found, exiting
```

**Comment by AltGr** [comment]
From your message, it seems that the dependencies of the base packages are not properly added to the switch roots before the cleanup; obviously trying to remove them then results in a failure.
Thanks for reporting!

**Comment by AltGr** [comment]
I have a fix for this, but it's stacked on top of other pending PRs.
So you just have to wait to a little more, but it's fixed.
