### ISSUE TITLE
[opam 2.1~alpha] Failure to create an empty local switch

### ISSUE THREAD

**Issue by CraigFe** [ocaml/opam#4259]
After upgrading to Opam 2.1, the command I previously used for installing an empty switch in the current directory no longer works:

```shell
ᐅ opam switch create ./ ocaml-base-compiler.4.10.0 --empty
[ERROR] Individual packages, options --packages, --formula and --empty may not be specified at the same time
```

I'm not sure what's causing this error, but I believe the previous behaviour was to install an empty switch regardless, which I find more natural. The error message is perhaps not ideal :slightly_smiling_face:

(edit: I initially assumed that `./` is interpreted as a set of "individual packages" – since the directory does contain `.opam` files – but that appears to not be the issue here.)

**Comment by rjbou** [comment]
The previous behavior was to install a local switch with  `ocaml-base-compiler.4.10.0` as compiler/base package (which can be considered as a bug, as specifying a compiler and empty compiler is contradictory).
In 2.1.0, that check is done, and you gave as argument a (compiler) package `ocaml-base-compiler`, and `--empty` in the same time, that's what the error displays.
What is maybe missing is the specification of the given individual packages ?

**Comment by CraigFe** [comment]
I interpreted the previous behaviour of `--empty` as "don't try to install `opam` files present in that directory", which is what I want. With the new behaviour, is there a single command to create a new local switch at a specified compiler version _without_ also pulling in the `opam` files in that directory?

Also, I think the man-page for `opam switch` could make it clearer that `COMPILER` and `--empty` is not supported:

> COMPILER, if omitted, defaults to SWITCH if it is a plain name, unless --packages, --formula or --empty is specified.

**Comment by dra27** [comment]
This is a good example for the `OPAM_CLI_VERSION`/`--cli-version=` switch when we add it!

**Comment by pascutto** [comment]
> I interpreted the previous behaviour of `--empty` as "don't try to install `opam` files present in that directory", which is what I want. With the new behaviour, is there a single command to create a new local switch at a specified compiler version _without_ also pulling in the `opam` files in that directory?

I just ran into this, there is a `--no-install` option that does just that.
