### ISSUE TITLE
'opam switch list-available' doesn't output anything

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#4290]
```
# opam switch list-available
# Listing available compilers from repositories: 
# No matches found
```

```
# opam config report
# opam-version      2.0.3 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=ubuntu os-version=18.04
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              16
# repositories      1 (http), 2 (version-controlled) (default repo at 88c614be)
# pinned            7 (git)
# current-switch    default
```

What can I do then?
'rm -rf ~/.opam && opam init' is not desirable.

This prevents me from installing a beta version of the compiler, for example.

**Comment by dra27** [comment]
What’s the output of `opam remote list —all`?

Note that you can’t ever install a beta of the compiler the way you’re mentioning - you need to follow the incantation included in the release announcement.

You also never have to blow away your opam root in order to diagnose something - `OPAMROOT=~/.opam-temp opam init` will set up an entirely separate one; alternatively, you can rename `~/.opam` and run `opam init` (the `OPAMROOT` technique works for all `opam` commands and is very useful for testing new opam versions)

**Comment by UnixJunkie** [comment]
```
# opam remote list --all
# Repository   # Url
          # Switches(rank)
beta           git+https://github.com/ocaml/ocaml-beta-repository.git
github         git+https://github.com/ocaml/opam-repository.git
          default(2)
opam.ocaml.org https://opam.ocaml.org
          default(1)
```

**Comment by dra27** [comment]
Curioser and curioser - I presume you've updated them in recent history (`opam update --all`)? What happens if you try to install something which should be there - e.g. `opam update --all && opam switch create temporary-test ocaml-base-compiler.4.10.0`?)

**Comment by UnixJunkie** [comment]
```
# opam update --all && opam switch create temporary-test ocaml-base-compiler.4.10.0

<><> Updating package repositories ><><><><><><><><><><><><><><><><><><><><><><>
[beta] no changes from git+https://github.com/ocaml/ocaml-beta-repository.git
[github] no changes from git+https://github.com/ocaml/opam-repository.git
[opam.ocaml.org] no changes from https://opam.ocaml.org

<><> Synchronising development packages <><><><><><><><><><><><><><><><><><><><>
[NOTE] Ignoring uncommitted changes in /home/berenger/src/rankers
       (`--working-dir' not active).
[rankers.2.0.7] no changes from git+file:///home/berenger/src/rankers#master
[ERROR] No compiler matching 'ocaml-base-compiler.4.10.0' found, use 'opam
        switch list-available' to see what is available, or use '--packages' to
        select packages explicitly.
```

How can I end up in that state where I cannot create any switch...

**Comment by UnixJunkie** [comment]
Ok, I end up in that sorrow state because I did not add '--set-default' when I added my current switches...

**Comment by dra27** [comment]
Oh, of course - you have a switch named `default`. I confused `<default>` with `default` in your opam repo list. Yes indeed, if you have no default remotes then you won't have any available compilers.

The message should definitely be better, though.

**Comment by dra27** [comment]
I expect you've already found it, but `opam remote list --set-default` (slightly strangely) shows the default repositories and `opam remote add opam.ocaml.org --set-default` adds a repo to that list.

**Comment by rjbou** [comment]
Closing this one, feel free to reopen it if needed. Thanks!
