### ISSUE TITLE
Depext: Passing "answer yes" or "don't ask questions" option down to OS package manager

### ISSUE THREAD

**Issue by MSoegtropIMC** [ocaml/opam#4295]
Many package managers have an option to answer questions on also installing dependencies with yes automatically - like "-y" for MacPorts. It would be nice if depext would have such an option it would pass down the the respective system package managers (where they support it).

See (https://github.com/ocaml-opam/opam-depext/issues/130)

**Comment by rjbou** [comment]
It is present in [opam.2.1.0~alpha2](https://github.com/ocaml/opam/pull/4168).
Thanks!
