### ISSUE TITLE
Feature request: API link

### ISSUE THREAD

**Issue by kanishka-azimi** [ocaml/opam#4309]
It would be nice if opam presented the "doc" field from opam packages. Thanks for considering.

**Comment by rjbou** [comment]
Can you elaborate more the expected behavior? The `doc:` field is an url in the opam package.

**Comment by kanishka-azimi** [comment]
(I am new to ocaml and opam, so feel free to note that I am missing an already implemented feature)

I would display the value as a link, similar to homepage

**Comment by kanishka-azimi** [comment]
Moving to proper repo

**Comment by dbuenzli** [comment]
Maybe `opam info` could show the link.
