### ISSUE TITLE
New global options for opam lock correctly handled

### ISSUE THREAD

**Issue by dra27** [ocaml/opam#4320]
This a tracking issue which might also want writing up into a "HACKING" or developer's doc. A big implication of moving a plugin into opam is that the plugin gains all of the opam's global command line options, and we need to be sure they've remained sensible/been implemented.

The only plugin which has been _moved_ (as opposed to be made obsolete, in the case of `opam-depext`) is `opam-lock`.

## Irrelevant/ignored options
 - `--best-effort`
 - `--criteria`
 - `--cudf`
 - `--ignore-pin-depends`
 - `--no-aspcud`
 - `--solver`
 - `--use-internal-solver`

## Handled correctly:
 - [X] `--cli`
 - [X] `--color`
 - [X] `--debug`
 - [X] `--debug-level`
 - [X] `--git-version`
 - [X] `--json`
 - [X] `--no-auto-upgrade`
 - [X] `--no-self-upgrade`
 - [X] `--root`
 - [x] `--safe/--readonly` - is this implemented?
 - [x] `--strict`
 - [x] `--switch` - is this definitely being interpreted in the same way as the plugin?
 - [x] `--verbose`
 - [ ] `--working-dir`
 - [x] `--yes`

**Comment by rjbou** [comment]
ftm, opam lock do not handles `working-dir`, and don't even update sources to fetch last package definition.

**Comment by rjbou** [comment]
There 2 ways to handle it:
* Update the source for pinned packages and retrieve last version. `-w` is here to take the uncommitted opam file changes. But it needs a write lock (`opam lock` takes a lock none atm).
* Take the local opam file when found. No `-w` needed and no write lock. Sources remains not synced.
