### ISSUE TITLE
Bootstrapping from full tarballs fails with gcc-10

### ISSUE THREAD

**Issue by glondu** [ocaml/opam#4330]
The latest [full source release tarball](https://github.com/ocaml/opam/releases/download/2.0.7/opam-full-2.0.7.tar.gz) fails with gcc-10 (in current Debian testing) because of the embedded OCaml copy (4.07.1) that fails because of multiple definitions.

See https://github.com/ocaml/ocaml/issues/9144

A new tarball release should be made.

**Comment by avsm** [comment]
There is a fix on the 2.0 branch (https://github.com/ocaml/opam/pull/4262) that shifts the cold compiler to 4.09 and avoids this problem.  This is pending a opam 2.0.8 release.

How urgent is this for you? I thought Debian didn't use the full source release tarball for generating the opam package.

**Comment by glondu** [comment]
> How urgent is this for you?

I found a workaround (adding `-cc "gcc -fcommon"` to the `./configure` call), so it is not that urgent now...

> I thought Debian didn't use the full source release tarball for generating the opam package.

Indeed. I noticed that when [updating](https://gitlab.inria.fr/belenios/belenios/-/commit/023010ec951448259b40dbc6726d7d8a972a77ac) the script `opam-bootstrap.sh` in Belenios.

**Comment by avsm** [comment]
Glad you found a workaround; let us know if you're blocked on anything else.  I'll leave this open until we release opam 2.0.8 with the fix.

**Comment by glondu** [comment]
> let us know if you're blocked on anything else

My workaround for https://github.com/ocaml/opam/issues/3987 is to uninstall dune, which is not very satisfactory...

**Comment by dra27** [comment]
I think this has been fixed just by winding the "cold" version of OCaml forwards
