### ISSUE TITLE
opam depext times out on 32 bit systems

### ISSUE THREAD

**Issue by emillon** [ocaml/opam#4331]
Hi,

In a 32 bit environment with mccs, the following command times out after 60 minutes.

    opam depext --update -y ocamlformat.dev alcotest.1.2.1 astring.0.8.5 base.v0.14.0 base-bigarray.base base-bytes.base base-threads.base base-unix.base cmdliner.1.0.4 conf-m4.1 cppo.1.6.6 dune.2.7.0 dune-configurator.2.7.0 fix.20200131 fmt.0.8.8 fpath.0.7.2 menhir.20200624 menhirLib.20200624 menhirSdk.20200624 ocaml.4.10.1 ocaml-base-compiler.4.10.1 ocaml-config.1 ocaml-migrate-parsetree.1.7.3 ocamlbuild.0.14.0 ocamlfind.1.8.1 ocp-indent.1.8.1 odoc.1.5.1 ppx_derivers.1.2.1 re.1.9.0 result.1.5 seq.base sexplib0.v0.14.0 stdio.v0.14.0 stdlib-shims.0.1.0 topkg.1.0.2 tyxml.4.4.0 uchar.0.0.2 uucp.13.0.0 uuidm.0.9.7 uuseg.13.0.0 uutf.1.0.2

The full build log can be found at:

https://ci.ocamllabs.io/github/ocaml-ppx/ocamlformat/commit/90ead798169b98d4a3ec43932b5433a0a95c29f9/variant/debian-10-ocaml-4.10_x86_32

ocaml-ci uses opam 2.0.7 at the moment. Similar time outs occur with this configuration.

Thanks!

**Comment by AltGr** [comment]
It's likely the resolution of the opam installation that times out, you can check with `--debug`.

The command would probably be something like:
```
opam list --resolve=ocamlformat.dev,alcotest.1.2.1,astring.0.8.5,base.v0.14.0,base-bigarray.base,base-bytes.base,base-threads.base,base-unix.base,cmdliner.1.0.4,conf-m4.1,cppo.1.6.6,dune.2.7.0,dune-configurator.2.7.0,fix.20200131,fmt.0.8.8,fpath.0.7.2,menhir.20200624,menhirLib.20200624,menhirSdk.20200624,ocaml.4.10.1,ocaml-base-compiler.4.10.1,ocaml-config.1,ocaml-migrate-parsetree.1.7.3,ocamlbuild.0.14.0,ocamlfind.1.8.1,ocp-indent.1.8.1,odoc.1.5.1,ppx_derivers.1.2.1,re.1.9.0,result.1.5,seq.base,sexplib0.v0.14.0,stdio.v0.14.0,stdlib-shims.0.1.0,topkg.1.0.2,tyxml.4.4.0,uchar.0.0.2,uucp.13.0.0,uuidm.0.9.7,uuseg.13.0.0,uutf.1.0.2
```
which takes us back to the solver performance issues on specific switch configurations.

**Comment by avsm** [comment]
This appears to be an odd one-off issue with a particular build worker on Scaleway, so closing this as "cannot repro" once that has been decommissioned. It happened on some 64-bit builds as well.
