### ISSUE TITLE
Opam admin cache add --secondary-cache flag

### ISSUE THREAD

**Issue by FMProof** [ocaml/opam#4352]
This affects opam 2.0.7.

Given that many artifact URLs become obsolete over time, users requiring an offline clone of the opam repository need a way to fetch missing artifacts from other opam repository caches.  

Many source URLs in the opam repository are becoming obsolete.  For example, bitbucket has stopped serving archives of mercurial repositories.  Running `opam admin cache` will never fully populate these entries even though the artifacts are still present on opam.ocaml.org in the cache.

I would like `opam admin cache` to add a flag `--secondary-cache` that names the url of an opam cache directory to use when directly fetching an artifact fails.  This way, artifacts can be located when a URL cannot be resolved or a checksum is wrong.

**Comment by AltGr** [comment]
I think adding the cache to `~/.opam/config` or [the `repo` file](http://opam.ocaml.org/doc/Manual.html#repofield-archive-mirrors) should do the trick. Can you check ?

If the latter works, https://github.com/ocaml/opam-repository/pull/17355 should actually be enough to do the trick.

Note however that this approach means that the cache will always be hit _before_ trying the upstream URL, which differs from what you were asking.

**Comment by FMProof** [comment]
I appended the following to `~/.opam/config`:
```
archive-mirrors: [ "https://opam.ocaml.org/cache" ]
```
This did not work.  `opam admin cache` is not respecting this field.

I then checked the values in `~/.opam/repo/default/repo`.  It already contains this line:
```
archive-mirrors: "cache"
```
This means that opam knows about this cache location somewhere.  However, it doesn't know that the git clone that I'm using is the same as this cache, so it doesn't look.

I then modified the mirrored repo directly, adding the opam URL to `archive-mirrors`
```
archive-mirrors: ["cache" "https://opam.ocaml.org/cache"]
```
This also did not work.

Was there another value you wanted me to try modifying somewhere?

It really appears that `opam admin cache` ignores other caches when downloading.

**Comment by AltGr** [comment]
Thanks for testing!
It makes sense that `~/.opam/repo/default/repo` doesn't work, since it is only expected to be used on the configured `default` repository, which opam doesn't know could be linked to your global git clone. `~/.opam/config` should work always, though, as should defining the mirror in the local `repo` file; so indeed it seems it's not respected by `opam admin`, I'll see to it.

**Comment by FMProof** [comment]
Thank you very much!  I am constantly supporting offline development environments at my workplace, so a solution is very welcome.
