### ISSUE TITLE
Programs called from opam hooks need a way to display information to the user

### ISSUE THREAD

**Issue by lefessan** [ocaml/opam#4359]
For `opam-bin`, I would like to display information to the user about what happened during an `opam install` command, for example the number of binary packages that were built, and, if some binary packages could not be built, why, without making the full opam command fail.

A possibility would be to write append some text at the end of a file `$OPAM_SWITCH_PREFIX/.opam-switch/plugins/post-install-message.txt` for example, that would be cleared at the beginning of the session and displayed at the end.

**Comment by AltGr** [comment]
Note: this is related to opam `hooks`, and tools leveraging them, rather than plugins in general

Another possible solution that was discussed: allow output from pre/post-session hooks, and let the plugin gather its own messages.
A way for the plugin to identify the session would be useful, though.

**Comment by avsm** [comment]
I don't really understand the overall feature request.  What does `opam-bin` have to do with `opam install`?  Does it invoke `opam install` internally?

**Comment by AltGr** [comment]
@avsm It's the other way around, it's expected to be set as a `hook` in opam configuration to wrap package installs. It's true that at the moment, if you do this you have no way to report to the user except erroring out.

**Comment by lefessan** [comment]
Let's take another example: if a package tries to read/write the /etc/passwd, sandboxing (in opam hooks) will prevent it, but the package will still be able to catch the error and install itself normally, and the user will notice nothing. It would be better to report to the user that the package tried to access /etc/passwd, even if it didn't manage to do it. For that, programs called from opam hooks should be able to display messages at the end of the session.

**Comment by avsm** [comment]
Thanks, the original issue seemed to imply some interaction with plugins that I didn't understand. It's now clearer that it refers to the hooks mechanism instead.
