### ISSUE TITLE
There is no package installed in my Mac.

### ISSUE THREAD

**Issue by dipin24** [ocaml/opam#4372]
I've been trying to install frama-c in my Mac via opam.
The process is as follows : https://frama-c.com/install-sulfur-20171101.html#installing-frama-c-on-mac-os-x

As soon as I reach the :opam install altgr-ergo why3

This error pops up: `No switch is currently set. Please use 'opam switch' to set or install a switch`

And then I run this command for seeing all the switches : `opam switch list`
And this is the output :

`#  switch  compiler  description`

And when I run this command: `opam switch list-available`
This is the output 
```
# Listing available compilers from repositories: default
# No matches found

```

Whenever I try to create a switch using : `opam switch create ocaml-base-compiler 4.10.0`

```
 No compiler matching '4.10.0' found, use 'opam switch list-available' to see what is
        available, or use '--packages' to select packages explicitly.
```
I've installed ocaml separately , current version is 4.10.0
I think my OCaml-base-compiler is not installed

What should I do, as I am stuck here for days. I've tried many things and none of them gave any results.

I've reinstalled from beginning maybe 9-10 times

Plz help ...

**Comment by kit-ty-kate** [comment]
How did you call `opam init`?

**Comment by rjbou** [comment]
Also, can you share `opam repo` output ?

**Comment by AltGr** [comment]
Seems that the remote repositories are not configured correctly: opam finds no packages (or even compilers) to install; Check the output of `opam repo`, try `opam update`, or if you want to try to reinstall from scratch, remember to remove the `~/.opam` directory.

**Comment by dipin24** [comment]
> How did you call `opam init`?

 opam init

<><> Required setup - please read <><><><><><><><><><><><><><><><><><><><><><><>

  In normal operation, opam only alters files within ~/.opam.

  However, to best integrate with your system, some environment variables
  should be set. If you allow it to, this initialisation step will update
  your bash configuration by adding the following line to ~/.bash_profile:

    test -r /Users/dipin/.opam/opam-init/init.sh && . /Users/dipin/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

  Otherwise, every time you want to access your opam installation, you will
  need to run:

    eval $(opam env)

  You can always re-run this setup with 'opam init' later.

Do you want opam to modify ~/.bash_profile? [N/y/f]
(default is 'no', use 'f' to choose a different file) y
A hook can be added to opam's init scripts to ensure that the shell remains in
sync with the opam environment when they are loaded. Set that up? [y/N] y

User configuration:
  ~/.bash_profile is already up-to-date.
[NOTE] Make sure that ~/.bash_profile is well sourced in your ~/.bashrc.

**Comment by dipin24** [comment]
> Also, can you share `opam repo` output ?


opam repo
[WARNING] No switch is currently set, perhaps you meant '--set-default'?
[NOTE] These are the repositories in use by the current switch. Use '--all' to see all
       configured repositories.

**Comment by AltGr** [comment]
Indeed, no repositories seem to be configured :thinking: 
That could have been caused by an error during the first `opam init`; or maybe a stale `~/.opamrc` or `/etc/opamrc` ?? You can also check `env | grep OPAM`.
In any case, you should be able to configure the default repository with:
```
opam repository add default https://opam.ocaml.org --set-default
```
Then the `opam switch create` command should work and you can get started.

**Comment by dipin24** [comment]
> Indeed, no repositories seem to be configured 🤔
> That could have been caused by an error during the first `opam init`; or maybe a stale `~/.opamrc` or `/etc/opamrc` ?? You can also check `env | grep OPAM`.
> In any case, you should be able to configure the default repository with:
> 
> ```
> opam repository add default https://opam.ocaml.org --set-default
> ```
> 
> Then the `opam switch create` command should work and you can get started.

Can you please elaborate the steps, I can't seem to understand your commands.

**Comment by rjbou** [comment]
Certainly an error during the `opam init`. To fix it, you can use this command line
```opam repository add default https://opam.ocaml.org --set-default```
(that will fix repository that opam uses), then continue by creating a switch `opam switch create <switchname> <compiler version` and then you'll be able to continue the framac install process from `opam install altgr-ergo why3`

**Comment by dipin24** [comment]
> Certainly an error during the `opam init`. To fix it, you can use this command line
> `opam repository add default https://opam.ocaml.org --set-default`
> (that will fix repository that opam uses), then continue by creating a switch `opam switch create <switchname> <compiler version` and then you'll be able to continue the framac install process from `opam install altgr-ergo why3`

I did as you said and created switch via this command `opam switch create . ocaml-variants.4.06.1+flambda`
Then I was able to install 'opam install alter-ergo why3' and `opam install frama-c`

But when I ran a C code on frama-c using this command `frama-c -wp arraymax.c`, this output appeared: 

```
[kernel] Parsing arraymax.c (with preprocessing)
[wp] Warning: Missing RTE guards
[wp] User Error: Prover 'alt-ergo' not found in why3.conf
[wp] Goal typed_arraymax_ensures : not tried
[wp] Goal typed_arraymax_loop_invariant_preserved : not tried
[wp] Goal typed_arraymax_loop_invariant_established : not tried
[wp] Goal typed_arraymax_loop_invariant_2_preserved : not tried
[wp] Goal typed_arraymax_loop_invariant_2_established : not tried
[wp] Goal typed_arraymax_loop_assigns : trivial
[wp] Goal typed_arraymax_loop_variant_decrease : not tried
[wp] Goal typed_arraymax_loop_variant_positive : not tried
[wp] User Error: Deferred error message was emitted during execution. See above messages for more information.
[kernel] Plug-in wp aborted: invalid user input.

```

**Comment by rjbou** [comment]
This is a frama-c error, please report to frama-c bug tracker.
