### ISSUE TITLE
`opam switch create` should check whether cached sources are up to date

### ISSUE THREAD

**Issue by wang-d** [ocaml/opam#4377]
```
opam switch create catenable ocaml-base-compiler.4.07.1 
```

failed with output (trimmed) like this:

```
<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ocaml-base-compiler.4.07.1] found in cache
...
[ERROR] The compilation of ocaml-base-compiler failed at
        "/home/???/.opam/opam-init/hooks/sandbox.sh build make world".
...
# /usr/bin/ld: backtrace.pic.o:/home/???/.opam/catenable/.opam-switch/build/ocaml-base-compile
r.4.07.1/byterun/backtrace.c:31: multiple definition of `caml_debug_info'; backtrace_prim.pic.o:/hom
e/???/.opam/catenable/.opam-switch/build/ocaml-base-compiler.4.07.1/byterun/backtrace_prim.c:4
7: first defined here                                                                              
# collect2: error: ld returned 1 exit status
# make[1]: *** [Makefile:208: libcamlrun_shared.so] Error 1
# make[1]: Leaving directory '/home/???/.opam/catenable/.opam-switch/build/ocaml-base-compiler
.4.07.1/byterun'                                                                                   
# make: *** [Makefile:389: coldstart] Error 2
```

I was confused because it looked exactly like [this bug][], which had been fixed months ago.

[this bug]: https://github.com/ocaml/opam-repository/pull/16722

The problem went away after I did this:

```
opam update -a
opam upgrade
```

I'm guessing that `opam switch create` used the sources it found in my cache without checking whether they were up to date with the repo.  It only picked up the patch after I instructed the `update` and `upgrade`.  Does that sound plausible?

If so, would it be possible to make opam check whether its cached sources are up to date before using them?

```
# opam config report
# opam-version      2.0.0 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=debian os-version=10.0
[ERROR] No switch is currently set. Please use 'opam switch' to set or install a switch
# read-state        OpamStd.OpamSys.Exit(50)
```

As an aside (I know this is not your fault), I encountered this error while following this [quick start guide][] for my first dune project. It was pretty discouraging to start my first dune project with two hours investigating a link error in the compiler, followed by an hour [setting up automatic formatting][], followed by an hour investigating and then working around a type error in [code generated by a ppx][].

[quick start guide]: https://ocamlverse.github.io/content/quickstart_ocaml_project_dune.html
[setting up automatic formatting]: https://github.com/ocaml/dune/issues/3854
[code generated by a ppx]: https://github.com/janestreet/base_quickcheck/issues/2 

If you're wondering why I started my first project with old compiler sources in my opam cache, I think they were left over from the last time I tried to set up OCaml, which resulted in my filing issues with the [ocaml][] and [opam][] repos.  :-(

[ocaml]: https://github.com/ocaml/ocaml.org/issues/979
[opam]: https://github.com/ocaml/opam/issues/3282

Luckily, I have had some positive experiences with OCaml before, so I am not so easily discouraged. :-)

**Comment by AltGr** [comment]
Indeed that seems like a lot of bumps you encountered on the road... Thanks for taking the time to report them so we can improve!

We do have a warning for such cases (code [here](https://github.com/ocaml/opam/blob/b65140094c0a8c4f9f20139a05d461d35496f434/src/client/opamClient.ml#L145-L148)), but indeed it seems like it's only printed on `opam install`, and not on `switch create` or `upgrade`. This should be fixed!

Various efforts to make getting started on a project easier are underway, for example you may want to check out [drom](https://github.com/ocamlpro/drom). Be aware it's still in its alpha stage though.

**Comment by wang-d** [comment]
Thanks for the quick response!  drom looks like it will solve many of my getting-started problems.

**Comment by rjbou** [comment]
It is already called for `opam install` and `opam upgrade`. I'll add it for `opam switch create`.
