### ISSUE TITLE
[opam 2.1] opam init should upgrade the layout of /home/opam/.opam from version 2.0 to version 2.1

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#4409]
Using opam 2.1 (currently 2.1~beta2):
```
$ cat ~/.opam/config | grep opam-version
opam-version: "2.0"
$ opam init -ya

User configuration:
  ~/.profile is already up-to-date.
[NOTE] Make sure that ~/.profile is well sourced in your ~/.bashrc.

$ cat ~/.opam/config | grep opam-version
opam-version: "2.0"
```
It works with `--reinit` but I'm not sure why we need to specify this option here.

**Comment by rjbou** [comment]
In fact, the upgrade is done on the fly, and written on disk only when there is an opam write action (write lock required) cf. #4314

**Comment by avsm** [comment]
dev meeting: not a bug; `opam reinit` is what side-effects and rebuilds `~/.opam`.
