### ISSUE TITLE
unable to install various packages

### ISSUE THREAD

**Issue by vladislav-miroshnikov** [ocaml/opam#4412]
Good afternoon! After installing opam I ran into some problem, I cannot install various libraries, opam update / upgrade commands do not work.
The following is displayed:
```
opam install core
Fatal error:
In /home/vlad-miroshnikov/.opam/4.11.1/.opam-switch/packages/base_quickcheck.v0.14.0/opam:
unsupported or missing file format version
```
With opam update/upgrade is the same situation
Do you know what this is related to?
Ubuntu 20.04
@AltGr maybe you can help me? I would be very grateful!

**Comment by vladislav-miroshnikov** [comment]
[https://psv4.userapi.com/c856220/u169552307/docs/d14/6941e32c5a8a/fy.jpg?extra=NKRx5EwKgQLcXhdkGthl8OFrC2F-jtAUJ7FERFK3Ra4PZLKbk60ONhvyZjxq98RWBw81WN8DVkrNC3h7iD7vxXksHdu1oe8iB60kAMnFbccFm72hxDxZoXuRmFHtOB6PTxqoOmt2EA468c0lGQjYNAeDFw](url)

**Comment by vladislav-miroshnikov** [comment]
https://psv4.userapi.com/c856220/u169552307/docs/d14/6941e32c5a8a/fy.jpg?extra=NKRx5EwKgQLcXhdkGthl8OFrC2F-jtAUJ7FERFK3Ra4PZLKbk60ONhvyZjxq98RWBw81WN8DVkrNC3h7iD7vxXksHdu1oe8iB60kAMnFbccFm72hxDxZoXuRmFHtOB6PTxqoOmt2EA468c0lGQjYNAeDFw

**Comment by rjbou** [comment]
Seems an internal error, something went wrong on installing `base_quickcheck`. What is you opam version ? 
Can you share the content of the incriminated file please.

**Comment by vladislav-miroshnikov** [comment]
the problem was solved

**Comment by rjbou** [comment]
Nice! Out of curiosity, what was the problem/how did you solve it ?
