### ISSUE TITLE
opam init error

### ISSUE THREAD

**Issue by lyqssb** [ocaml/opam#4417]
>   If your issue concerns a package not building, please report to
>   https://github.com/ocaml/opam-repository/issues or to the package maintainer
>   unless you are confident it is an issue in the opam tool itself.
I tried install opam on ubuntu1804.  I tried:
`add-apt-repository ppa:avsm/ppa
apt update
apt install opam`

opam --version : I got 2.0.4
But when I tried to `opam init`, I got this:
```
 [ERROR] Could not update repository "default": OpamDownload.Download_fail(_, "Curl
        failed: \"~/anaconda3/bin/curl --write-out %{http_code}\\\\n --retry 3
        --retry-delay 2 --user-agent opam/2.0.4 -L -o
        /tmp/opam-20845-e7966f/index.tar.gz.part
        https://opam.ocaml.org/index.tar.gz\" exited with code 1")

 [ERROR] Initial download of repository failed
```
How can I fix this？Thank you very much! @mroch 
```
<include here the output of `opam config report`, if applicable>
# opam config report
# opam-version      2.0.4 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=ubuntu os-version=18.04
[ERROR] Opam has not been initialised, please run `opam init'
# read-state        OpamStd.OpamSys.Exit(50)
```

**Comment by dra27** [comment]
What’s the value of the `PATH` environment variable and what is `~/anaconda3/bin/curl`?

**Comment by dra27** [comment]
Also, have you set `OPAMCURL` or `OPAMFETCH`?

**Comment by lyqssb** [comment]
`PATH`  on my ubuntu1804:
'''
export PATH="/usr/local/cuda-10.2/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/cuda-10.2/lib64:$LD_LIBRARY_PATH"
export PATH="/home/ubuntu1804/anaconda3/bin:$PATH"

alias sudo='sudo env PATH=$PATH'
'''
I don't know the `OPAMCURL` and `OPAMFETCH`. Last time I tried these  same commands on my ubuntu1604 , I did't met such error.I just input commands and it worked.  But I don't hava anaconda3 on my ubuntu1604. So  do you think the installation of anaconda3 cause this error?

**Comment by dra27** [comment]
What's the output of `/home/ubuntu1804/anaconda3/bin/curl --version`?

**Comment by lyqssb** [comment]
The output:
'''
curl 7.26.0 (x86_64-unknown-linux-gnu) libcurl/7.26.0 zlib/1.2.11
Protocols: dict file ftp gopher http imap pop3 rtsp smtp telnet tftp 
Features: IPv6 Largefile libz 
'''

**Comment by dra27** [comment]
Can you try running `opam init` again (to confirm it's still failing) and if so then try running again without `/home/ubuntu1804/anaconda3/bin` in `PATH`?

**Comment by lyqssb** [comment]
I tried the way you said. I got same error.  I  even tried to comment out all the paths about anaconda3. Just like this:
'''
#export PATH="/usr/local/cuda-10.2/bin:$PATH"
#export LD_LIBRARY_PATH="/usr/local/cuda-10.2/lib64:$LD_LIBRARY_PATH"
#export PATH="/home/ubuntu1804/anaconda3/bin:$PATH"

#alias sudo='sudo env PATH=$PATH'
''' and `source ~/.bashrc`
the error doesn't seem to change at all:
'''
(tensorflow2) ubuntu1804@ubuntu1804-virtual-machine:~/wq$ sudo vim ~/.bashrc
[sudo] ubuntu1804 的密码： 
(tensorflow2) ubuntu1804@ubuntu1804-virtual-machine:~/wq$ source ~/.bashrc
ubuntu1804@ubuntu1804-virtual-machine:~/wq$ workon tensorflow
ERROR: Environment 'tensorflow' does not exist. Create it with 'mkvirtualenv tensorflow'.
ubuntu1804@ubuntu1804-virtual-machine:~/wq$ opam init
[NOTE] Will configure from built-in defaults.
Checking for available remotes: rsync and local, git, mercurial, darcs. Perfect!

<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>
[ERROR] Could not update repository "default": OpamDownload.Download_fail(_, "Curl
        failed: \"~/anaconda3/bin/curl --write-out %{http_code}\\\\n --retry 3
        --retry-delay 2 --user-agent opam/2.0.4 -L -o
        /tmp/opam-24819-e7966f/index.tar.gz.part
        https://opam.ocaml.org/index.tar.gz\" exited with code 1")
'''

**Comment by dra27** [comment]
You're replying when I ask for environment with scripts, though - what's the actual value at that point (i.e. `echo $PATH`)? The output from opam shows it's still executing `curl` from anaconda3.

**Comment by lyqssb** [comment]
Yes, you're right. After I input `echo $PATH`, I got:
'''
ubuntu1804@ubuntu1804-virtual-machine:~/wq$ echo $PATH
/home/ubuntu1804/anaconda3/bin:/usr/local/cuda-10.2/bin:/usr/local/cuda-10.2/bin:/usr/local/cuda-10.2/bin:/home/ubuntu1804/.local/bin/.virtualenvs/tensorflow2/bin:/home/ubuntu1804/anaconda3/bin:/usr/local/cuda-10.2/bin:/home/ubuntu1804/anaconda3/bin:/usr/local/cuda-10.2/bin:/home/ubuntu1804/anaconda3/bin:/usr/local/cuda-10.2/bin:/home/ubuntu1804/anaconda3/bin:/usr/local/cuda-10.2/bin:/home/ubuntu1804/anaconda3/bin:/usr/local/cuda-10.2/bin:/home/ubuntu1804/anaconda3/bin:/usr/local/cuda-10.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
'''
But I've already sourced it. I don't know how to change. It looks as if I've only changed the surface. So where is the real path?  Thanks so much for response!

**Comment by rjbou** [comment]
Your real `PATH` is at the end: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`. You can set it in your current session with an `export`: `export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`. But this is more an bash setting environment issues.
