### ISSUE TITLE
[optimization] Only check for changes on the filesystem when necessary

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#4422]
Currently opam check for changes in the `.opam` after every single package installation. This produces a lot of IO.
However when the package being installed does not have any `install` field and sandbox is on this is totally unnecessary.

~Two solution could a considered:~
1) ~If we decide that the sandbox must be enabled, here is what is required to get this working internally:~
* [ ] ~a way for opam to know if the sandbox is enabled (currently the sandbox is simply a `wrap-*-command`)~
* [ ] ~a way for opam to ensure the sandbox script is unmodified~

~Since this requires the sandbox to be there, only Linux and MacOS would be eligible to this.~

2) Another solution would be to disregard whether or not the sandbox is enabled and do this anyway as a package trying to cross the sandbox is a packaging issue and would fail anyway on systems with sandbox enabled.

*Original idea by @Armael*

**Comment by kit-ty-kate** [comment]
The first solution already goes out of the window when considering parallel builds. Parallel installs would detect things installed during the build phase of the potential faulty package and mess things up anyway.

The second solution of simply disabling scanning of `opamroot` when a package has no `install` field is still possible

**Comment by dra27** [comment]
Fixed by #4494
