### ISSUE TITLE
Cannot create switch on Raspberry Pi

### ISSUE THREAD

**Issue by smimram** [ocaml/opam#4424]
I am trying to install ocaml on an old Raspberry Pi (model B rev 2) and I cannot seem to be able to switch to a recent compiler. The switch creation always fails:
```
$ opam switch create 4.11.1
[ERROR] Solver failed: "/usr/bin/mccs -i
        /home/pi/.opam/log/solver-in-7065-7afd23 -o
        /home/pi/.opam/log/solver-out-7065-5f1023
        -lexagregate[-removed,-count[version-lag:,true],-changed,-count[version-lag:,false],-new]"
        exited with code 255 "ERROR: Cannot read solution from lp solver."
Switch initialisation failed: clean up? ('n' will leave the switch partially
installed) [Y/n] y
```
I also tried various recent versions of OCaml and solvers (`aspcud` and `packup`) without more success. My configuration is
```
# opam config report
# opam-version      2.0.3 
# self-upgrade      no
# system            arch=arm32 os=linux os-distribution=raspbian os-version=10
# solver            mccs
# install-criteria  -removed,-count[version-lag:,true],-changed,-count[version-lag:,false],-new
# upgrade-criteria  -removed,-count[version-lag:,false],-new
# jobs              1
# repositories      1 (http) (default repo at 706be51c)
# pinned            0
# current-switch    default
```
Is there any simple way for me to debug this?

Thanks!

**Comment by AltGr** [comment]
It appears you are using `mccs` as an external solver, and there is an issue in what it returns. You could try:
- running with the built-in solver, which is the recommended default (if opam was built with it, which should be the case for all provided binaries): `--solver=builtin-mccs+glpk`
- increasing verbosity to see how the solver is called precisely `-vvv`
- running the command by hand to debug: `opam switch create xxx --cudf=solver-debug`, then `mccs solver-debug-1.cudf -lexagregate[...]`

Hope that helps

**Comment by smimram** [comment]
This did not go on so well. This version does not have a builtin resolver
```
$ opam switch --solver=builtin-mccs+glpk create 4.11.1
[ERROR] No installed solver matching the selected 'builtin-mccs+glpk' found
```
verbose mode is uninformative
```
$ opam switch -vvv create 4.11.1
+ /usr/bin/lsb_release "-s" "-r"
- 10
+ /usr/bin/ocamlc "-vnum"
- 4.05.0
[ERROR] Solver failed: "/usr/bin/mccs -i
        /home/pi/.opam/log/solver-in-1165-7afd23 -o
        /home/pi/.opam/log/solver-out-1165-5f1023
        -lexagregate[-removed,-count[version-lag:,true],-changed,-count[version-lag:,false],-new]"
        exited with code 255 "ERROR: Cannot read solution from lp solver."
```
and I could not fully generate a solver file for mccs
```
$ opam switch create 4.11.1 --cudf=solver-debug
Killed
```
In the end, I would tend to think that it is simply somthing like a memory problem or so, and the solver gets killed.

I have solved the situation by installing binary packages from testing which are quite up-to-date, so let's close this report, thanks for the help!
