### ISSUE TITLE
Report error on invalid syntax for version constraint in opam file

### ISSUE THREAD

**Issue by mjambon** [ocaml/opam#4439]
I mistakenly specified `"lsp" {"1.1.0"}` instead of `"lsp" {= "1.1.0"}` in an opam file for a project. No error was reported by either `opam lint` or `opam install`. It would be great if an error was reported, rather than the dependency being ignored silently.

The session below shows that `lsp` is not installed and that having `"lsp" {"1.1.0"}` as a dependency is like having nothing instead.

```
$ opam config report
# opam config report
# opam-version      2.0.5 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=ubuntu os-version=20.04
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              3
# repositories      1 (http) (default repo at ad125b9b)
# pinned            2 (git)
# current-switch    4.10.0

$ opam list | grep lsp

$ opam lint opam
/home/martin/tmp/report/opam: Passed.

$ opam install --deps-only .
Nothing to do.

$ cat opam
opam-version: "2.0"
name: "thing"
version: "0.0.0"
synopsis: "A a"
description: "A a"

maintainer: "x <x@example.com>"
authors: [ "x <x@example.com>" ]
license: "LGPL-2.1"
homepage: "https://example.com"
dev-repo: "git+https://github.com/example/foo"
bug-reports: "https://github.com/example/foo/issues"

depends: [
  "lsp" {"1.1.0"}
]

build: [make]
```

**Comment by rjbou** [comment]
This syntax is allowed as the constrained filter evaluates correctly `{"true"}`, or `{"%{a-var}%"}` when `a-var` is a boolean, it is the default otherwise (here false). But yes, opam should at least warn on this kind of syntax when it is not a bool nor a variable.

**Comment by rjbou** [comment]
Added a lint warning #66. Thanks for the report

**Comment by mjambon** [comment]
Awesome, thank you!
