### ISSUE TITLE
Print information about substitutions in verbose mode

### ISSUE THREAD

**Issue by lthls** [ocaml/opam#4453]
(Reporting on behalf of @shindere)

When using file substitutions (`substs:` field of the opam file), there is no output detailing what substitutions were performed even in verbose mode.

@shindere mentioned the following features that would be nice to have:
- Basic printing that substitutions are being done
- Details of which files are generated from which templates
- Details of each substitution (which variable is replaced by which value)

**Comment by shindere** [comment]
Many thanks for the report, Vincent!

The features you list couldindeed be reported, with more details as the
verbosity level increases.

I'm not sure I would actually find the simple mention that
"substitutions are being performed" usefule. I think, even at the most
basiclevel, it would be handy to know which files are generated from
which templates.

**Comment by rjbou** [comment]
In fact, there was the mechanism for patches, but the function wasn't applied. Added the same for substitutions, debug & verbose mode
```
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
00:04.552  ACTION                 download_package: pat-sub.0.1
00:04.686  ACTION                 prepare_package_source: pat-sub.0.1 at .opam/switch/.opam-switch/build/pat-sub.0.1
00:04.686  ACTION                 pat-sub: expanding opam variables in baz-update.patch.in, generating baz-update.patch.

[pat-sub: subst] expanding opam variables in baz-update.patch.in, generating baz-update.patch
00:04.686  ACTION                 pat-sub: applying bar-update.patch.

[pat-sub: patch] applying bar-update.patch
Processing  2/3: [pat-sub: patch]
00:04.719  ACTION                 pat-sub: applying baz-update.patch.

[pat-sub: patch] applying baz-update.patch
00:04.759  ACTION                 pat-sub: expanding opam variables in foo.in, generating foo.

[pat-sub: subst] expanding opam variables in foo.in, generating foo
```

**Comment by shindere** [comment]
Looks very nice! Thanks!
