### ISSUE TITLE
Question: how to access specific files of sources of an opam package?

### ISSUE THREAD

**Issue by MSoegtropIMC** [ocaml/opam#4465]
I maintain the Coq platform, a set of scripts which install opam and a largish set of opam packages in a beginner friendly way. These scripts also allow to create a Windows installer from an opam switch (in a fairly generic way which might be useful elsewhere - if this is of interest I could put a wiki entry somewhere).

One issue is that I need to test the result of the installer - an opam switch tree packaged into an installer and extracted elsewhere - and for this I need to download example files from the source trees of various packages in the version installed in opam. I wonder what would be the best way to access the sources. Obviosuly opam does have a way to download the sources, but I wonder if this is somewhere exposed in the command line interface of opam. As far as I can see there is not even a way to extract the source url short of `opam show` combined with `awk`.

**Comment by rjbou** [comment]
`opam source` permit you to download the source in a given directory, but all the sources (untar the archives), not specific files.

**Comment by MSoegtropIMC** [comment]
@rjbou : thanks for the quick answer. I didn't see this command somehow. It is fine to extract the complete sources - the packages are usually small and performance is not an issue for generation of the test kit.
