### ISSUE TITLE
access to source...

### ISSUE THREAD

**Issue by progman1** [ocaml/opam#4466]
I was using [opam var ocaml:build] to provide access to the source code for extraction and building of extra tooling.
but things seem to have changed after 4.07.1 and the build directory doesn't appear
to hold the source only where/ocaml.config files.
the source is elsewhere in the .opam tree but I have not found a variable that offers it.

is there another way of doing this?

**Comment by rjbou** [comment]
What version of opam do you use ?
You need to retrieve only ocaml's source or the one from build ?

**Comment by progman1** [comment]
v2.0.1
I want to condition my building of extra tooling on users having OPAMKEEPBUILDDIR=true and thereby having the source available without further effort on their part.
or any other means of accessing the source without users explicilty having to request it.

**Comment by progman1** [comment]
the ..opam-switch/sources/ocaml-base-compiler.XXXX would be fine
except I cannot find any variable that points to it.

**Comment by rjbou** [comment]
To retrieve `ocaml-base-compiler` build directory (if you are in a `OPAMKEEPBUILDDIR` env), you can retrieve it with `opam config var ocaml-base-compiler:build`. The `ocaml` package permit to choose between system, base & variant compiler, and generates the ocaml.config files. The real build is done by the `ocaml-base/variants` packages.
If you want to access to all variable defined for a given package,  use `opam var --package <pkg>` .

Note that `opam config var` will be remove in 2.1 ( but you will still can access it using cli versioning).

**Comment by progman1** [comment]
ah! 
just the ticket.
thank you.

**Comment by progman1** [comment]
but no variable just for the package source?

**Comment by rjbou** [comment]
No, this variable doesn't exist
