### ISSUE TITLE
Checksum error during install on macOS ARM64 (works otherwise)

### ISSUE THREAD

**Issue by MSoegtropIMC** [ocaml/opam#4473]
I tried to install opam on a Mac with M1 (ARM64) processor. The only issue I found is that I get a checksum error when I run the install script. When I remove the checksum test from the install script it works. I also compiled ocaml 4.10.2 and Coq 8.12.1 and it did work all well (no extensive tests of Coq as yet but basic smoke tests are fine).

Steps to reproduce: run on a Mac with M1 processor:
```
sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
```
Result: "Checksum mismatch, a problem occurred during download."

**Comment by rjbou** [comment]
Could you provide outputs of
* `uname -m` output, it seems that it is [`arm64`](https://developer.apple.com/forums/thread/668206)
* `openssl 512 $(which opam)`, assuming that you have in your path the opam that install script installed

**Comment by MSoegtropIMC** [comment]
I get this output:
```
% uname -m                 
arm64
% which opam               
/usr/local/bin/opam
% opam --version
2.0.7
% openssl dgst -sha512 $(which opam) 
SHA512(/usr/local/bin/opam)= ff8463f4450eff488d458be209e04cbc2286265b967b8cbcd9c7dd4b9bebad5951c0e4f42fc96a7745da7d80750eb1d30046ea2b5de41e3a78487f547229a8db
```

**Comment by rjbou** [comment]
Found it! It confused me as usually we don't generate arm64 for macos, but the release has been updated, with a note:
> As an addendum to this release, the macOS/arm64 binary was built by @avsm (but not yet signed).

and the install script has not been updated accordingly.

**Comment by MSoegtropIMC** [comment]
Actually I think what might have happened is that I got the Intel code and it is executed using the emulator. But I think the code it builds is ARM - need to double check. I think it wouldn't be that bad if opam itself wound run under the emulator as long as the code it produces is ARM.

**Comment by MSoegtropIMC** [comment]
Thanks, I will test it asap!
