### ISSUE TITLE
Package installed using `opam` disappeared from my system

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [ocaml/opam#4486]
I installed google-drive-ocamlfuse using opam according to the instructions in the [wiki](https://github.com/astrada/google-drive-ocamlfuse/wiki/Installation#installing-with-opam). After I encountered a problem with all my disk space being eaten up when copying directories from the remote Google Drive mounted at a mount point on my file system, I got the error `df: cloud_storage/: Input/output error` when I ran the command `df -h cloud_storage/`. From this moment I noticed that google-drive-ocamlfuse was no longer on my system, it just vanished.

I can no longer run `google-drive-ocamlfuse` from the command line.

What happened to the google-drive-ocamlfuse package I installed using opam and why did it disappear?

```
$ opam config report
# opam config report
# opam-version      2.0.4 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=fedora os-version=31
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              3
# repositories      1 (http) (default repo at 2432f42e)
# pinned            0
# current-switch    default
```

**Comment by dra27** [comment]
What do the output of `opam list` and `find ~/.opam -name google-drive-ocamlfuse` give?

**Comment by ChukwuemezieChristopherAneke** [comment]
> What do the output of `opam list` and `find ~/.opam -name google-drive-ocamlfuse` give?

```
$ opam list
# Packages matching: installed
# Name                 # Installed # Synopsis
.
.
.
.
google-drive-ocamlfuse 0.7.23      A FUSE filesystem over Google Drive
ocaml                  4.11.1      The OCaml compiler (virtual package)
ocaml-base-compiler    4.11.1      Official release 4.11.1
.
.
.
.

```
I've left out unnecessary lines in the output of `opam list`.

$ find ~/.opam -iname google-drive-ocamlfuse
/home/user/.opam/repo/default/packages/google-drive-ocamlfuse
/home/user/.opam/default/lib/google-drive-ocamlfuse
/home/user/.opam/default/doc/google-drive-ocamlfuse
/home/user/.opam/default/bin/google-drive-ocamlfuse

**Comment by dra27** [comment]
Does `opam exec -- google-drive-ocamlfuse` do something meaningful?

**Comment by ChukwuemezieChristopherAneke** [comment]
@dra27 after I rebooted my system, `googled-drive-ocamlfuse` magically reappeared again. Somehow my extremely low disk space made the `google-drive-ocamlfuse` that was installed using `opam` unavailable. I didn't even have enough available disk space to create a file using touch.
