### ISSUE TITLE
Installing opam with Homebrew on MacOS: update for instructions

### ISSUE THREAD

**Issue by vcgalpin** [ocaml/opam#4510]
I suggest that the Homebrew instructions at https://opam.ocaml.org/doc/Install.html#OSX be updated to
```
# Homebrew
brew install gpatch
brew install pkg-config
brew install opam
```
If pkg-config is not installed, then `opam init` installs ocaml 4.07.0 rather than the latest version, and `opam switch install 4.xx.x` is necessary and reveals the requirement for pkg-config before the latest version can be installed.

**Details of the installation process**

I installed opam via homebrew on MacOS 11 (Big Sur) today and observed the following behaviour.

I followed the instructions at https://opam.ocaml.org/doc/Install.html#OSX
```
# Homebrew
brew install gpatch
brew install opam
```
and then did `opam init`. This installed opam 4.07.0 so I needed to do `opam switch install 4.xx.x` to get a more recent version, as well as `brew install pkg-config` for the switch install to work.

I then (uninstalled and) reinstalled opam after installing pkg-config.
```
# Homebrew
brew install pkg-config
brew install gpatch
brew install opam
```
and `opam init` installed Ocaml 4.11.1 as the default. This seems to be a more direct and better outcome for installation.

**Comment by rjbou** [comment]
In that case, the formulae itself to be updated., ping @avsm ?

**Comment by rjbou** [comment]
related #4421

**Comment by avsm** [comment]
The base OCaml compiler shouldn't depend on pkg-config. It's not clear why the selection isn't working for you: would you be able to post the output of `opam init`?  Is it affected by whether you do a `brew install ocaml` before the opam init?

**Comment by vcgalpin** [comment]
I tried to reproduce this issue on a test machine running Big Sur but was unable to. I will close the issue.
