### ISSUE TITLE
[feature request] 'deprecated' flag

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#4522]
A builtin support in opam for a `deprecated` flag would be nice. Here what such flag would do:
* Any packages flagged with `deprecated` would be avoided by the solver unless there is no other choice (e.g. some user wants to install package `a` which depends on `b` which is deprecated)
* If it is installed, show up a note after installation notifying the user that the package is deprecated. If the developer deprecating the package wants to add precisions, they can do it using the `post-messages` field as it was already done for such a purpose.

Related to https://github.com/ocurrent/opam-health-check/issues/8

**Comment by dbuenzli** [comment]
Related to https://github.com/ocaml/opam/issues/2046

**Comment by AltGr** [comment]
There is a significant overlap with `hidden-version` (which we haven't renamed yet it seems ?) here;

**Comment by dra27** [comment]
I think it would implemented internally as `hidden-version` - the difference is just the extra messages, I think?

**Comment by kit-ty-kate** [comment]
Implemented in https://github.com/ocaml/opam/pull/4523

> I think it would implemented internally as `hidden-version` - the difference is just the extra messages, I think?

The differences are:
- the name: which is going to be used by external tools (e.g. opam-health-check). For that purpose only we most likely want to differenciate the two.
- upgrade to `deprecated` is not forbidden as it is with `hidden-version`
- the extra message
