### ISSUE TITLE
opam 2.0.8 opam packages?

### ISSUE THREAD

**Issue by RalfJung** [ocaml/opam#4536]
I hope this is the right place to ask: I wanted to install the latest opam 2.0.8 release, as usual by updating the `opam-devel` package and building it myself locally. However, `opam-devel` does not seem to have a version 2.0.8:
```
$ opam show opam-devel

<><> opam-devel: information on all versions ><><><><><><><><><><><><><><><><><>
name                   opam-devel
all-installed-versions 2.0.7 [system]
all-versions           2.0~alpha5  2.0.0~beta  2.0.0~beta3  2.0.0~beta3.1  2.0.0~beta5  2.0.0~rc  2.0.0~rc2  2.0.0~rc3  2.0.0  2.0.1  2.0.2  2.0.3  2.0.4  2.0.5  2.0.6  2.0.7  2.1.0~beta2  2.1.0~beta4
```
Am I looking in the wrong place? This package is explicitly mentioned in the [release announcement](https://opam.ocaml.org/blog/opam-2-0-8/).

**Comment by rjbou** [comment]
It is the good place. There is some delay in the publishing, I'll answer back when it is available.

**Comment by avsm** [comment]
You win a medal for being first to want to test the release, @RalfJung :)

**Comment by RalfJung** [comment]
:medal_sports: 

I even waited almost a day after GitHub sent me the notification for the release yesterday, but then I saw the blog post so I figured the packages would be out already. *oops* I'll be more patient next time.^^ (The only trouble is this means I need to remember to get back to this, it's easier to react right when the announcement  arrives.)

**Comment by kit-ty-kate** [comment]
This should now be fixed. The release is accessible on opam-repository (now if you're using the git remote, or in a couple of hours if you're using the default remote)

Thanks!
