### ISSUE TITLE
Cannot build opam from sources, when 'dune-project' file is presented in the parent directory

### ISSUE THREAD

**Issue by rvem** [ocaml/opam#4537]
Hi, I've been trying to build `opam` from sources and stumbled upon this problem.

To reproduce:
```
git clone https://github.com/ocaml/opam.git
touch dune-project
cd opam && ./configure && make opam
```

The following error occurs:
```
src_ext/dune-local/dune.exe build --profile=release   --promote-install-files opam-installer.install opam.install
Entering directory '/experiments'
File "dune-project", line 1, characters 0-0:
Error: Invalid first line, expected: (lang <lang> <version>)
Makefile:128: recipe for target 'build-opam' failed
make: *** [build-opam] Error 1
```

Environment: Ubuntu 18.04 (actually docker container), OCaml 4.0.5

**Comment by rjbou** [comment]
Seems that `dune` check if there is `dune-project` in the parent directory...

**Comment by dra27** [comment]
Dune is following its algorithm for [Finding the root](https://dune.readthedocs.io/en/stable/usage.html#finding-root).

If you're putting opam's sources inside another Dune project, this is "vendoring" (from Dune's perspective) and the correct way to build opam would to be invoke `dune` at this point (which should work).

However, it also makes sense for the default arguments in the `Makefile` to include `--root=.`, which I think @kit-ty-kate is preparing a PR for.

**Comment by dra27** [comment]
(As a workaround, I think `make DUNE_ARGS=--root=. opam` should work)
