### ISSUE TITLE
opam 2.0.8 for macos on arm64 - Checksum mismatch

### ISSUE THREAD

**Issue by lindig** [ocaml/opam#4540]
```
% sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
## Downloading opam 2.0.8 for macos on arm64...
Checksum mismatch, a problem occurred during download.
```

Above is the recommended method to install Opam.

**Comment by kit-ty-kate** [comment]
The macos/arm64 binaries got forgotten about, sorry about that. I'll be fixed soon.

In the meantime you can use opam 2.0.7 which has the macos/arm64 binary by calling the install script this way:
```
sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh | sed "s/VERSION='2\.0\.8'/VERSION='2.0.7'/")
```
I'm a bit surprised by the error message you got however. When I try to emulate a macos/arm64 environment on my local machine (which is not a macos nor arm64) I get:
```
## Downloading opam 2.0.8 for macos on arm64...
There may not yet be a binary release for your architecture or OS, sorry.
See https://github.com/ocaml/opam/releases/tag/2.0.8 for pre-compiled binaries,
or run 'make cold' from https://github.com/ocaml/opam/archive/2.0.8.tar.gz
to build from scratch
```

**Comment by lindig** [comment]
Thanks. The error is pasted straight from my shell on MacOS arm64 so I don't know why it looks different for you.

**Comment by mroch** [comment]
the 2.0.8 macos arm64 binaries exist now, but install.sh doesn't have the checksum, so it ends up comparing the real checksum to `no sha` which gives the "Checksum mismatch, a problem occurred during download." error.

**Comment by mroch** [comment]
similar to @kit-ty-kate's workaround, I did this in the meantime:

```
sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh | sed "s/opam-2.0.8-arm64-linux/opam-2.0.8-arm64-macos)     echo "45eb0a414f66307a566974eda14dc6061b999e4fcb6626b39477bdbf189c75b1c0f20bd480d88d2c41ea77658073e2cbb5b73c969e187de7de311bbae516216e";; opam-2.0.8-arm64-linux/")
```
