### ISSUE TITLE
Allow specifying command to apply patches

### ISSUE THREAD

**Issue by MisterDA** [ocaml/opam#4551]
The `patches` field allows listing patches that _are applied sequentially to the source as with the `patch` command_, however not all patches are created equal. For instance, Git has a custom format for binary diffs that the venerable `patch` utility doesn't understand.  In order to support such patches, the patch utility should be changed to `git apply` (although I haven't yet checked if that works outside a git repo). An example of a binary file that cannot be patched easily today is the configure script from the OCaml compiler.

**Comment by rjbou** [comment]
It is not possible ftm to specify a patch command, as for make, curl, etc.  `[g]patch` is an opam required tool, but even if git is widely used, it is not required by opam. There is several issues where pops the idea to use an ocaml written patch, to get ride of some `patch` limits (see https://github.com/ocaml/opam/issues/3782#issuecomment-476177916).

**Comment by dra27** [comment]
Early versions of the Windows patches used 2.0... it was unreliable which is why the patch rewriter got added.

@rjbou has referenced the tracking issue - for the time being, it's better to amend the patch - see, for example, https://github.com/ocaml/opam/blob/master/shell/re-patch.sh

**Comment by dra27** [comment]
Closing this in favour of the main patch issue
