### ISSUE TITLE
random crashes during `opam init` and `opam install`

### ISSUE THREAD

**Issue by vsiles** [ocaml/opam#4552]
>   If your issue concerns a package not building, please report to
>   https://github.com/ocaml/opam-repository/issues or to the package maintainer
>   unless you are confident it is an issue in the opam tool itself.

Hi !
Yesterday at work I updated our Buck based build system from 4.07.1 to 4.09.1. Today I'm trying to update the dune based build system in the same way, and I'm facing random build error, both during `opam init` while building ocaml, or during `opam install` while building some dependencies.

Here are some examples:
https://pastebin.com/bbwj2JvV 
https://pastebin.com/siyBi368

I'm running this setup on machines with respectively 24 and 80 cores. I tested with 2.0.1 originally and then with 2.0.8

And I have cases where everything works ok, so I'm guessing there is a parallelism/concurrency issue somewhere.
My current attempts involved:
- set `OPAMJOBS=12` in the environment
- set `--jobs=12` on the command line interface
- set `MAKEFLAGS="--jobs=12"`

This last one is totally ignored: in the `.env` file produce when opam has a build error, I can see `MAKEFLAGS=`.

```
# opam config report
# opam-version      2.0.8
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=centos os-version=8
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              23
# repositories      1 (http) (default repo at fbcd9451)
# pinned            0
# current-switch    4.09.1
```

Is there a local/short term fix I can deploy to make `opam init` and `opam install` work ?

**Comment by avsm** [comment]
You appear to be building dune itself in parallel twice, for some reason. Can you reproduce this outside of Buck on the CLI?

**Comment by vsiles** [comment]
As I said, the part involving Buck is completely fine. This happens from the CLI (https://github.com/facebook/hhvm/blob/master/hphp/hack/opam_setup.sh) using only dune and opam.

**Comment by vsiles** [comment]
Overall this script is just a glue to deal with internal/external build where we have different opam locations, and we don't fetch from the internet but from a tar.gz we have versioned. It boils down to `opam init && opam install`

**Comment by vsiles** [comment]
the patch we apply at  FB is not on github, but should not matter here: we patch the configure file of ocaml to pass in FB related paths for gcc & cie, so we amend CFLAGS/LDFLAGS.

**Comment by vsiles** [comment]
if it helps, you can find the full log of the last failure at https://pastebin.com/bgBNYnTx which failed during the build of opam

**Comment by rjbou** [comment]
From those logs, there is the `-j 23` & `-j 79` that makes me think that builds are still using `nb core - 1`. Just checked with 2.0.8, `OPAMJOBS` and `--jobs` are well passed to `make` (as defined in the opam file ` [make "-j%{jobs}%" {os != "cygwin"} "world.opt"]`). I found only one case where those options are ignored, it is when the switch config [`variables`](https://opam.ocaml.org/doc/Manual.html#switchconfigsection-variables) contains a `jobs` variable. You can check that with `opam config list`, in the current switch part.

**Comment by rjbou** [comment]
It is set by `opam config set jobs x`, but I don't see such command on your scripts...

**Comment by rjbou** [comment]
As a side note, on `opam_setup.sh`, from what I see, you source & pin the compiler in opam internals repo directory. You should change that. Even if it works, you shouldn't have the source in the repo, even less in opam internals. Ftm it is working, but in 2.1 those internals change (silently in user view), and the [`pushd`](https://github.com/facebook/hhvm/blob/cf83715159c17db84c3d7585e5ae8f7d50aa240c/hphp/hack/opam_setup.sh#L96) command will fail.

**Comment by vsiles** [comment]
> As a side note, on `opam_setup.sh`, from what I see, you source & pin the compiler in opam internals repo directory. You should change that. Even if it works, you shouldn't have the source in the repo, even less in opam internals. Ftm it is working, but in 2.1 those internals change (silently in user view), and the [`pushd`](https://github.com/facebook/hhvm/blob/cf83715159c17db84c3d7585e5ae8f7d50aa240c/hphp/hack/opam_setup.sh#L96) command will fail.

How do you suggest I proceed to apply a custom patch to the compiler then ?

FYI I'm removing noise in our scripts to try and nail what can be the issue (if it comes from this), and I  completely removed the patch mechanics. They are not the problem

**Comment by rjbou** [comment]
If you can launch them with `-vv` to have the launched command too.

**Comment by vsiles** [comment]
> From those logs, there is the `-j 23` & `-j 79` that makes me think that builds are still using `nb core - 1`. Just checked with 2.0.8, `OPAMJOBS` and `--jobs` are well passed to `make` (as defined in the opam file ` [make "-j%{jobs}%" {os != "cygwin"} "world.opt"]`). I found only one case where those options are ignored, it is when the switch config [`variables`](https://opam.ocaml.org/doc/Manual.html#switchconfigsection-variables) contains a `jobs` variable. You can check that with `opam config list`, in the current switch part.

I definitely still saw `-j 23` while using `--jobs=12` or `OPAMJOBS=12`. Do you think I should try with a `opam config set jobs 12` ?

Will try with -vv

**Comment by rjbou** [comment]
> How do you suggest I proceed to apply a custom patch to the compiler then ?

Exactly the same way, but in a different directory outside `$OPAMROOT`. The process is good.  There is an other way to do it by acting directly on your custom repo and use `patches:` field, but your only advantage is less rsyncing and avoid 1 download (`opam source` one).

**Comment by rjbou** [comment]
> Do you think I should try with a `opam config set jobs 12` ? 

It will certainly unblock you, but it won't permit to determine the issue.

**Comment by dra27** [comment]
Do you also see it just building OCaml 4.09.1 from the release tarball with `make -j23 world.opt`, etc.?

**Comment by vsiles** [comment]
Here is a run with -vv https://pastebin.com/cZephX6z
I did not try to change the number of jobs in this one

**Comment by vsiles** [comment]
Got some errors with just `opam init`, no more mini repo... Continuing to strip things down.
How can I `set jobs 12` before compiling ocaml itself ? the command requires a switch

**Comment by rjbou** [comment]
> Here is a run with -vv https://pastebin.com/cZephX6z

ok, this one is the default, on a 24core machine, so we have the default `-j 23` l.378

>  How can I set jobs 12 before compiling ocaml itself ? the command requires a switch

You can't. You'll need a bare init, empty switch, configure it then install ocaml.
```
$ opam init --disable-sandboxing --no-setup --bare
$ opam switch create "$HACK_OPAM_NAME" --empty
$ opam config set jobs 12
$ opam install ocaml+variants.4.09.1+fp -v
```

I propose you these commands instead to check/debug
```
$ opam init --disable-sandboxing --no-setup --bare
$ opam switch create "$HACK_OPAM_NAME" --empty
$ opam config list # to check that jobs variable isn't set (just to be sure)
$ opam install ocaml+variants.4.09.1+fp -j 12 -v || true # it should fail and show a `-j 23`
$ opam config set jobs 12
$ opam config list # to check that jobs variable is well set
$ opam install ocaml+variants.4.09.1+fp -v
```

**Comment by vsiles** [comment]
I'm running multiple CI with `opam config set jobs 12`  and so far it seems to be a valid workaround.
Any idea where the error is in opam/ocaml ?

**Comment by rjbou** [comment]
>  Any idea where the error is in opam/ocaml ?

The job issue is definitively an opam one.
The parallel build error seems to be an ocaml one. To check that you can try to compile ocaml with -j 23
```
$ opam init --disable-sandboxing --no-setup --bare
$ opam switch create "$HACK_OPAM_NAME" --empty
$ cd /tmp
$ opam source ocaml+variants.4.09.1+fp
$ cd ocaml+variants.4.09.1+fp
$ ./configure 
$ make -j23 world        # or 79 if in a 80 core machine
$ make -j23 world.opt  # same
$ opam install ocaml+variants.4.09.1+fp
```
If local and opam build fail, it is an ocaml issue, if only opam fails, ocaml in opam issue. 

> So I can already confirm that the `-j 12 -v # show a -j 23` is accurate: I see `/usr/bin/make "-j23" "world.`

And I have no idea why... Does the config list confirmed that the jobs variable is not set in switch ?

**Comment by vsiles** [comment]
> $ opam init --disable-sandboxing --no-setup --bare
> $ opam switch create "$HACK_OPAM_NAME" --empty
> $ cd /tmp
> $ opam source ocaml+variants.4.09.1+fp
> $ cd ocaml+variants.4.09.1+fp
> $ ./configure 
> $ make -j23 world        # or 79 if in a 80 core machine
> $ make -j23 world.opt  # same
> $ opam install ocaml+variants.4.09.1+fp

I just tested that and got an error a `make -j23 world`. Looks like the error is on ocaml then. Should I open a PR there ?

**Comment by vsiles** [comment]
I managed to repro this on ocaml only, 4.11.1. Closing and will report to them directly. Thanks a lot for the help in investigating this.

**Comment by rjbou** [comment]
You're welcome :)
