### ISSUE TITLE
opam init in 2.1 is not selecting the system compiler

### ISSUE THREAD

**Issue by dra27** [ocaml/opam#4577]
```
FROM ubuntu:20.10
RUN apt-get update
RUN apt-get install opam -y
RUN opam init --root=/root/opam-root-build -n --disable-sandboxing
WORKDIR /root
RUN git clone https://github.com/ocaml/opam.git -o upstream
WORKDIR /root/opam
RUN git checkout 0249289cfc5279eca4e2c25ce428abbed7503a77
RUN opam pin add --no-action --root=/root/opam-root-build dose3 '5.0.1-1'
RUN opam install --root=/root/opam-root-build cmdliner mccs dose3 opam-file-format --yes
RUN opam exec --root=/root/opam-root-build -- ./configure
RUN opam exec --root=/root/opam-root-build -- make
RUN ./opam init -n --disable-sandboxing
```
At the first opam init (which is 2.0) you can see `ocaml-system` being selected. 0249289cfc5279eca4e2c25ce428abbed7503a77 then compiles 4.12 from sources.

**Comment by avsm** [comment]
Doesn't seem to happen on macOS with opam checkout 0249289cfc5279eca4e2c25ce428abbed7503a77 -- I get the brew-installed ocaml-system on a fresh `opam init`.

**Comment by rjbou** [comment]
*On behalf of @AltGr*
If the criteria are only e.g. `ocaml >= 4.08`, the solver will proceed normally to choose an implementation thereof. So if it has two implementations, `ocaml-base-compiler` and `ocaml-system`, it will choose between the two using its usual criteria, i.e. the one with the fewest newer releases and minimising the number of new packages. If all things are equal, the black-box that is the solver will return one or the other arbitrarily (remember that on 2.0, it was an error if you got a choice between system and base compilers at the same version). 
The mechanics where the default-compiler setting was actually a list masquerading as a formula, and where the first satisfiable formula in the list would be chosen as invariant, were removed.

**Comment by dra27** [comment]
From dev meeting: restore the 2.0 treatment of the default compiler setting in opamrc to treat the disjunction as a list of a formulae to try in turn; OK to use that disjunction "correctly" in `opam switch create .`

**Comment by dra27** [comment]
Next dev meeting notes: idea to have both the old `default-compiler` (which would select ocaml-system for speed) and also `default-invariant` so that the invariant is still `"ocaml" {>= 4.05}` to allow an easier first-time-user experience for getting to a specific version of OCaml.

**Comment by AltGr** [comment]
One way to do it without re-introducing a big dependency and conflicts analysis machinery (the beauty of the new approach is that everything goes through a single call to the solver) could be to have `opam init`'s switch creation behave similarly to:
```bash
$ opam switch create xx --empty
$ opam switch set-invariant <default-invariant> --no-action
$ opam install <default-compiler> --best-effort
```

This would
- always set `default-invariant`
- assuming `default-compiler` is compatible with `default-invariant`, it would initially create the switch with that compiler installed (version or variant)
- if it's not compatible, `--best-effort` would still enforce the default invariant following its optimisation criteria
- we keep the "1 solver call" implementation

Any downsides ? Of course this requires `--best-effort` to work reliably.

**Comment by AltGr** [comment]
Of course that would not be equivalent to the 2.0 behaviour where all alternatives in `default-compiler` would be tried in turn until one was satisfiable ; do we really need to be able to specify a list of alternatives there ?

(And no, I don't want to consider the possibility to iter solver calls ; I would even prefer to hack onto the `version-lag` to just increase the weight of later alternatives...)

**Comment by dra27** [comment]
The main thing is that we need to have `opam init` select, say, `ocaml-system.4.08.1` when it's available over `ocaml-base-compiler.4.12.0`, the precise mechanism worries me less 🙂

That said, while I know we try to avoid calling the solver more than once like the, um, plague, the normal configuration of opam isn't ever going to do that iterating over `"ocaml-system" {>= "4.02.3"} | "ocaml-base-compiler"`. If `"ocaml-system {>= "4.02.3"}` is _available_ then we know it's going to be _solvable_ unless a user purposely goes out of their very convoluted way to engineer custom repositories which don't! So is it really something we need to worry about here?
