### ISSUE TITLE
Opam 2.1.0 install always creates a backup of the main `.opam` folder

### ISSUE THREAD

**Issue by NathanReb** [ocaml/opam#4579]
Installing the latest opam as suggested in the [opam 2.1.0 alpha announcement post](https://opam.ocaml.org/blog/opam-2-1-0-alpha/), i.e. running the following:
```
sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh) --dev
```
always go through a back up step of the `.opam` folder.
This is a sane thing to do in most cases but it might be the case that you want to skip it, for example because you already backed it up yourself or simply because you're upgrading from an older `2.1` beta.

It would be good to add a way to skip this step, especially given the potential size of the `.opam` folder and therefore the cost of this operation.

Do you think it would make sense to add a prompt there?

**Comment by rjbou** [comment]
You can use the `--no-backup` [option](https://github.com/ocaml/opam/blob/master/shell/install.sh#L91)

**Comment by NathanReb** [comment]
Ah nice thanks! Is this documented somewhere outside the script?

**Comment by rjbou** [comment]
Outside the script it would be on a term with `./install.sh --help` :innocent: 
We can add a section with the several options of this script at the bottom of [install page](https://opam.ocaml.org/doc/Install.html), with a hint/link at the[ Binary-distribution*](https://opam.ocaml.org/doc/Install.html#Binary-distribution) section.

**Comment by NathanReb** [comment]
Ah nevermind it's described in `--help`, didn't get that at first.

I guess describing the options in the manual would be great indeed but now that I know the script has a `--help` option I'll think about looking there next time! Thanks, closing this!

**Comment by rjbou** [comment]
The issue is most of users will use that script with `curl`, without really downloading & launching it by hand (no exploration), so no really access to the `--help`.
