### ISSUE TITLE
[ERROR] The compilation of X failed at Y - limited debugging information offered

### ISSUE THREAD

**Issue by mbardwell** [ocaml/opam#4596]
Reproduce:
* clone https://github.com/gjasny/v4l-utils
* `cd v4l-utils && dune init proj v4l && cd v4l`
* _dune-project_
```
(lang dune 2.8)
(name v4l)
(generate_opam_files true)
(use_standard_c_and_cxx_flags true)
```
* `opam install v4l` - works
* Add files
```
v4l/lib
├── dune
├── v4l2_ctl.ml
└── v4l2-ctl-stubs.cpp

# dun
(library
 (public_name v4l)
 (name v4l)
 (modules v4l2_ctl)
 (foreign_stubs (language cxx) (names v4l2-ctl-stubs) (flags (-O2)) (include_dirs %{project_root})))
```
* `dune build v4l` - no error
* `opam install v4l --debug-level 100` - fails
```
...
00:00.209  FILE(.config)          Cannot find <$HOME>/.opam/dune284/.opam-switch/config/angstrom.config
...
[ERROR] The compilation of v4l failed at "<$HOME>/.opam/opam-init/hooks/sandbox.sh build dune build -p v4l -j 7 @install"
```

when I run the [ERROR] command in my terminal, it does not return an error. There is no other debug information to help me with this problem as far as I can see.

```
# opam config report
# opam-version      2.0.7
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=ubuntu os-version=18.04
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              7
# repositories      1 (http) (default repo at 15d6aa57)
# pinned            2 (rsync), 1 (version)
# current-switch    dune284

```

**Comment by mbardwell** [comment]
`~/.opam/log/v4l-22623-1872ec.out` empty

```
mdbardwe@oumuamua:~$ grep "OPAM\|OCAML" ~/.opam/log/v4l-22623-1872ec.env
OCAML_TOPLEVEL_PATH=<$HOME>/.opam/dune284/lib/toplevel
OPAMNOENVNOTICE=true
OPAM_PACKAGE_NAME=v4l
OPAM_PACKAGE_VERSION=1.0
OPAM_SWITCH_PREFIX=<$HOME>/.opam/dune284
```

**Comment by mbardwell** [comment]
~/.opam/log/v4l-22623-1872ec.out empty

```
# ~/.opam/log/v4l-22623-1872ec.env
OCAML_TOPLEVEL_PATH=<$HOME>/.opam/dune284/lib/toplevel
OPAMNOENVNOTICE=true
OPAM_PACKAGE_NAME=v4l
OPAM_PACKAGE_VERSION=1.0
OPAM_SWITCH_PREFIX=<$HOME>/.opam/dune284
```

**Comment by AltGr** [comment]
That is weird... if you wait until the end of the opam run you should have an `error report` section that gathers info about the process, its command line, the last lines of its log and a pointer to the full log. Can you post the full output ?

Also, I assume the package is pinned to that directory, using the default of git-pinning, and that you committed all your changes ?

**Comment by rjbou** [comment]
Thanks for the detailed report, but there is still some missing information, I wasn't able to reproduce. Especially the content (or a content) of `v4l2_ctl*` files, tu have dune build them. Without the cpp file, I had no error (and I had some additionnal commands todo).
To have more information on launched processes (build commands), you should use verbose option `-vvv` thant debug one. Debug is for opam debugging, but verbose will print all processes launched.

**Comment by mbardwell** [comment]
> `v4l2_ctl*` files

The files looked something like

```
# v4l2_ctl.ml
external hi: int -> int = "hi_stub"

# v4l2-ctl-stubs.cpp
#include <caml/mlvalues.h>
#include "v4l2-ctl.h"
CAMLprim value hi_stub(value foo) {
  CAMLparam1(foo);
  CAMLreturn(foo);
}
```

> Can you post the full output?

Decided not to ocaml-ify v4l2-ctl for now, instead opting for a more custom solution. Thanks for the help.
