### ISSUE TITLE
Compilation of some packages hanging!

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam#4597]
Thanks @avsm for finding this, it seems it is a very recent regression.

```
$ cd /tmp
$ git clone https://github.com/avsm/debug-opam-dune-hang
$ opam switch create debug-opam-dune-hang/ -v --debug --yes
[...]
02:25.329  FILE(opam)             Wrote /tmp/debug-opam-dune-hang/_opam/.opam-switch/packages/dune-configurator.2.8.4/opam in 0.000s
02:25.329  PARALLEL               Job 44612439 finished
Processing 46/51: [bigstringaf: dune build]
02:25.329  PARALLEL               Starting job 268152395 (worker 2/24 -/1 -/5): λ mirage-crypto.0.8.10
02:25.329  SYSTEM                 rmdir /tmp/debug-opam-dune-hang/_opam/.opam-switch/build/mirage-crypto.0.8.10
02:25.335  ACTION                 prepare_package_source: mirage-crypto.0.8.10 at /tmp/debug-opam-dune-hang/_opam/.opam-switch/build/mirage-crypto.0.8.10
02:25.335  PARALLEL               Next task in job 268152395: $HOME/.opam/opam-init/hooks/sandbox.sh build dune build -p mirage-crypto -j 24
Processing 47/51: [bigstringaf: dune build] [mirage-crypto: dune build]
<hangs here>
```
Disabling the sandbox doesn't seem to help.

**Comment by AltGr** [comment]
It seems that `mirage-crypto` builds with `dune` that calls `make` in `freestanding` that calls `opam config var prefix` which hangs ; killing the latter releases the build.

**Comment by dra27** [comment]
Simpler repro: `opam switch create hangs ocaml-system mirage-crypto bigstringaf`. The issue only occurs during switch creation (i.e. `opam switch create works ocaml-system && opam install mirage-crypto bigstringaf` works).

The fault's been present since the first beta - it was introduced by c6aaa6074f2a4f2a187b60198c54865bd8785cb9 in #4314.

**Comment by AltGr** [comment]
Thanks for the bisecting!
