### ISSUE TITLE
rfc: improved switch cli ux - set switch

### ISSUE THREAD

**Issue by cdaringe** [ocaml/opam#4602]
# Problem

`opam` switch management has everything we need, yet I spend a large amount of time trying to get them in line, and have a difficult time getting my env sync'd to my switch 100% the time, reliably.

Perhaps some UX improments can be made. 

current: `eval $(opam env --switch 410 --set-switch)`
desired: `opam switch use 410`

thanks for the consideration.

**Comment by dra27** [comment]
It's not clear what you're after here - you can't drop the `eval $()` part - that's the shell, not opam.

**Comment by cdaringe** [comment]
ya, i wasn't thinking clearly. thx
