### ISSUE TITLE
 rfc: improved switch cli ux - auto load local switch

### ISSUE THREAD

**Issue by cdaringe** [ocaml/opam#4603]
# Problem

Local switches are awesome, but do not auto-load.

# Discussion
In my shell, I overload `cd` to test for some hint of `ocaml`, and attempt to autoload my switch:

```sh
load-opam-dune() {
  if [[ -f dune && -r dune ]]; then
    echo "🐪 detected. attemptin to load local switch"
    eval $(opam env --switch=. --set-switch)
  fi
}
cd() { builtin cd "$@"; 'load-opam-dune'; }
```

Overriding `cd` is subjectively undesirable. `opam` can surely detect a local switch and tap into it by default. For most users and use cases, this is certainly desirable behavior. Some `OPAM_DISABLE_LOCAL_SWITCH_AUTOLOAD` could be used to support those who prefer the status-quo.

**Comment by rjbou** [comment]
opam already automatically select local switch if it is called from the directory (or its sub directory) of the local switch. 
Since 2.0, at init step (`opam init`) opam proposes to update your `*rc` file to have an always up-to-date environment (but don't select the switch, if non local).

**Comment by AltGr** [comment]
Yup, we already have this feature, just see `opam init --enable-shell-hook` :)
