### ISSUE TITLE
Opam is not installing local files without committing changes

### ISSUE THREAD

**Issue by leoheck** [ocaml/opam#4611]
Hi, I am using opam 2.0.5 and I cannot install a local package that I am changing without having to commit changes on my repo. 
I tried with `-w` but nothing happens. I also have an extra bash script that has to be installed too.

```
➜ opam config report
# opam config report
# opam-version      2.0.5 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=ubuntu os-version=20.04
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              11
# repositories      1 (http) (default repo at 191daf37)
# pinned            2 (git)
# current-switch    4.09.1
```

**Comment by dra27** [comment]
Sounds like you’re using git pins rather than path pins. Assuming you added the pin with something like `opam pin add package .`, you want to add `-k path` to that as opam as opam will assume you meant to pin the repository (i.e. committed changes) by default.

**Comment by leoheck** [comment]
This assumption is right. Thanks for this info.
I have zero experience with opam. I was struggling to find this kind of info.

**Comment by leoheck** [comment]
Ops, could not make it run. This is what the author of this repo is teaching to do.
```
opam pin add -y plotkicadsch .
```

This is what I understood from your commet?

![image](https://user-images.githubusercontent.com/1277920/111920756-83aba800-8a6f-11eb-931d-6510906df6ad.png)

Am I doing something wrong?
Supposing I have a repo that I want to install and test changing stuff, how should I do it?

**Comment by dra27** [comment]
Ah, no, I meant _literally_ `-k path` - so `opam pin add -y -k path pltkicadsch .`

**Comment by dra27** [comment]
It depends on exactly what you want to test - if you want to alter `plotkicadsch` itself and see what the changes are like, then you probably just want to build it (`dune build`). opam pinning allows you to test the effect of your changes on _other_ packages in opam - although looking at opam-repository, there's nothing dependent on it.

If you're writing a test application of your own and you want to test changes, then given that the system is written in Dune you may want to try out Dune's vendoring: I wrote a [blog post](https://www.dra27.uk/blog/platform/2018/08/15/dune-vendoring.html) about this a few years ago. Essentially, start a Dune project of your own and clone the plotkicadsch inside it. You can then work on both a test application and the library at the same time. Do head over to [our Discuss forum](https://discuss.ocaml.org) if you need some more help with that, or OCaml in general!

**Comment by leoheck** [comment]
Oh boy, thanks.

My objective is to modify software that does not do what I need and then use it with my changes on my computer. With that being said, I thought it was easier to modify sources locally, and then install it as I was installing as the author of the repo said to do.

This is the way that I am installing this tool
```
opam switch create 4.09.1
opam switch 4.09.1
eval `opam config env`
opam pin add kicadsch .
opam pin add plotkicadsch .
opam update
opam install plotkicadsch
```

This is what you are teaching me to do
```
opam switch create 4.09.1
opam switch 4.09.1
eval `opam config env`
opam pin add -y -k path kicadsch .
opam pin add -y -k path plotkicadsch .
opam update
opam install plotkicadsch
```

Opam does these uncommon things. For instance, `-k path` is so strange as a command line parameter, I confess. Also, Opam help opens a man page, this is so weird. Usually, linux apps have a man page that is long like a manual, and then they also have a `-h`/`--help` flag for fast and simple instructions on how to execute the command line.

Well, thanks for the Help @dra27

**Comment by dra27** [comment]
Actually, I was more advocating this workflow, in a clean directory:
```bash
opam switch create ocaml-base-compiler.4.09.1
eval $(opam env)
opam install dune -y
dune init exe myapp
git clone https://github.com/jnavila/plotkicadsch
echo '(vendored_dirs plotkicadsch)' >> dune
cd plotkicadsch ; opam install . --deps-only -y ; cd ..
dune exec -- plotgitsch --version
```

You can hack both a test application and the package itself without using opam at all, beyond getting `dune` and your dependencies.

> Opam does these uncommon things. For instance, `-k path` is so strange as a command line parameter, I confess.

Yes, it is - it would arguably have been better if `opam pin add plotkicadsch https://github.com/jnavila/plotkicadsch.git` created a git pin and `opam pin add plotkicadsch .` created a path pin by default, but changing behaviour of the tool is tricky for users expecting the current behaviour.

> Also, Opam help opens a man page, this is so weird. Usually, linux apps have a man page that is long like a manual, and then they also have a `-h`/`--help` flag for fast and simple instructions on how to execute the command line.

This comes from [Cmdliner](https://erratique.ch/software/cmdliner), which is the command line argument parsing library used extensively in OCaml applications (and isn't ours!). That said, cf. `git commit --help` and even `dune exec -- plotgitsch --help`.
