### ISSUE TITLE
SPDX format linter should not allow case insensitive operators

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#4613]
The SPDX format checked for by `opam lint` explicitly says that:
```
License expression operators (AND, OR and WITH) should be matched in a case-sensitive manner.
```
see: https://spdx.github.io/spdx-spec/appendix-IV-SPDX-license-expressions/

opam allows `<license> with <exception>` but it should not be the case

**Comment by dra27** [comment]
Cross-referencing #4598

**Comment by kit-ty-kate** [comment]
The syntax for having multiple license currently accepted is `license: ["license1" "license2"]` where it should probably be `license: "license1 AND license2)"`
