### ISSUE TITLE
opam pin: unintuitive behavior

### ISSUE THREAD

**Issue by cdisselkoen** [ocaml/opam#4614]
As a relatively new user, the behavior of `opam pin` is not what I expect.  It's possible that this is just me misunderstanding the purpose of `opam pin` though.

I would expect that when I `opam pin` a package to a particular version, `opam` will not change that package's version, or uninstall it, as a result of other `opam` commands.  However, `opam` in some cases does not respect my previous request to `pin` a package to a particular version.

Steps to reproduce:

1. Start from a fresh `opam` switch with OCaml 4.10.0
```
opam switch create 4.10.0
```
2. Pin the `ocamlformat` package to version 0.14.0
```
opam pin ocamlformat 0.14.0
```
This installs, among other things, `base` version 0.13.2, which is great.

3. Request to pin the `core` package to version v0.14.1.
```
opam pin core v0.14.1
``` 
`opam` tries to upgrade `base` to version 0.14.1 and uninstall `ocamlformat` (?!) despite it being pinned.

In this case, `core v0.14.1` and `ocamlformat 0.14.0` are incompatible, due to irreconcilable version requirements for `base`.  But I expected some kind of loud/hard error here, rather than `opam` defaulting to uninstall a package I previously had pinned.

Here is `opam config report`, after step 3 but refusing to perform the install/uninstall operations which step 3's `pin` command suggested.
```
# opam config report
# opam-version      2.0.4 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=ubuntu os-version=18.04
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              11
# repositories      1 (http), 1 (version-controlled) (default repo at bb1ab5d2)
# pinned            2 (version)
# current-switch    4.10.0
```

Another example with a variation of the same behavior:

1. Start from a fresh `opam` switch with OCaml 4.09.0
```
opam switch create 4.09.0
```
2. Pin the `bap-std` package to version 2.1.0
```
opam pin bap-std 2.1.0
```
This installs, among other things, `base` version 0.12.2, as well as version 2.1.0 of many `bap-std` dependencies, such as `bap-main`, `bap-build`, `bap-plugins`, etc.

3. Request to pin the `ocamlformat` package to version 0.16.0.
```
opam pin ocamlformat 0.16.0
```
`opam` tries to upgrade `base` to version 0.14.1 and uninstall `bap-std` despite it being pinned.  It also tries to upgrade many `bap-std` dependencies such as `bap-main`, `bap-build`, `bap-plugins` etc to 2.2.0.  There are several things unintuitive about this (to me):
- I would expect a loud/hard error when trying to pin packages with incompatible/irreconcilable requirements for dependency versions
- I would not expect `opam` to default to uninstalling `bap-std` when I had previously pinned it
- I would not expect `opam` to default to upgrading `bap-main`, `bap-build`, `bap-plugins` etc to versions which are incompatible with the version of `bap-std` which I previously pinned
- If `opam` would uninstall `bap-std`, I would perhaps expect it to uninstall other `bap-std` dependencies which were only installed for the sake of `bap-std` and not for any other installed/pinned packages.  (Similar to `apt autoremove` on Debian/Ubuntu.)  Or, at least to offer to uninstall them.

Again, as a relatively new user I could be misunderstanding the purpose of `opam pin`.  This could just be my own user error.  Or maybe this is a feature request, I'm not sure.  Thanks in advance for your help!

**Comment by dra27** [comment]
It is a misunderstanding of pinning, yes, although that doesn't mean we don't need to change something.

Pinning and installation are separate things (which, as it happens, is the case in other package managers too). For example, by using `opam pin add --no-action`, it is possible to add a pin and not install the package. That's actually most commonly used when adding lots of pins at once. With your first example:

```bash
dra@thor:~$ opam pin add ocamlformat 0.14.0 -n
ocamlformat is now pinned to version 0.14.0
dra@thor:~$ opam pin add core v0.14.1 -n
core is now pinned to version v0.14.1
dra@thor:~$ opam pin list
core.v0.14.1        (uninstalled)  version  v0.14.1
ocamlformat.0.14.0  (uninstalled)  version  0.14.0
```

we have now told opam that if core is installed then it must be at version v0.14.1 and if we install ocamlformat then it must be at version 0.14.0. The fact those two things conflict is not part of pinning - the pins override the behaviour of the package repositories we're using (version pins effectively "delete" the other packages from view).

You can then see the conflict if you try to install them both at once:

```bash
dra@thor:~$ opam install ocamlformat core
[ERROR] Package conflict!
  * Incompatible packages:
    - core >= v0.14.1 → sexplib >= v0.14
    - ocamlformat = 0.14.0 → base < v0.14

No solution found, exiting
```

Note that if I do `opam install ocamlformat -y` (which obviously works) then when you subsequently `opam install core` (or, as you did, pin it), opam does not _silently_ remove ocamlformat:

```
dra@thor:~$ opam pin add core v0.14.1
core is now pinned to version v0.14.1

The following actions will be performed:
  ⊘ remove  ocamlformat             0.14.0*            [conflicts with base]
  ∗ install ocaml-compiler-libs     v0.12.3            [required by ppxlib]
  ∗ install stdlib-shims            0.3.0              [required by ppxlib]
  ↗ upgrade sexplib0                v0.13.0 to v0.14.0 [required by base, sexplib]
  ∗ install jane-street-headers     v0.14.0            [required by core_kernel]
  ∗ install spawn                   v0.13.0            [required by core]
  ∗ install octavius                1.2.2              [required by ppx_js_style]
  ∗ install num                     1.4                [required by sexplib]
  ↗ upgrade ocaml-migrate-parsetree 1.8.0 to 2.1.0     [upstream or system changes]
  ↗ upgrade base                    v0.13.2 to v0.14.1 [required by core_kernel]
  ∗ install ppxlib                  0.21.0             [required by ppx_jane]
  ∗ install variantslib             v0.14.0            [required by core_kernel]
  ∗ install typerep                 v0.14.0            [required by core_kernel]
  ∗ install parsexp                 v0.14.0            [required by sexplib]
  ∗ install fieldslib               v0.14.0            [required by core_kernel]
  ↗ upgrade stdio                   v0.13.0 to v0.14.0 [required by core_kernel]
  ∗ install ppx_stable              v0.14.1            [required by ppx_jane]
  ∗ install ppx_sexp_conv           v0.14.2            [required by core_kernel]
  ∗ install ppx_pipebang            v0.14.0            [required by ppx_jane]
  ∗ install ppx_optional            v0.14.0            [required by ppx_jane]
  ∗ install ppx_let                 v0.14.0            [required by ppx_jane]
  ∗ install ppx_js_style            v0.14.0            [required by ppx_base]
  ∗ install ppx_here                v0.14.0            [required by ppx_jane]
  ∗ install ppx_fixed_literal       v0.14.0            [required by ppx_jane]
  ∗ install ppx_enumerate           v0.14.0            [required by ppx_base]
  ∗ install ppx_compare             v0.14.0            [required by ppx_base, bin_prot]
  ∗ install ppx_cold                v0.14.0            [required by ppx_base]
  ∗ install ppx_variants_conv       v0.14.1            [required by ppx_jane]
  ∗ install ppx_typerep_conv        v0.14.1            [required by ppx_jane]
  ∗ install sexplib                 v0.14.0            [required by core]
  ∗ install ppx_fields_conv         v0.14.2            [required by ppx_jane]
  ∗ install ppx_optcomp             v0.14.1            [required by ppx_jane]
  ∗ install ppx_custom_printf       v0.14.1            [required by ppx_jane]
  ∗ install ppx_sexp_value          v0.14.0            [required by ppx_jane]
  ∗ install ppx_sexp_message        v0.14.1            [required by core_kernel]
  ∗ install ppx_hash                v0.14.0            [required by core_kernel]
  ∗ install ppx_assert              v0.14.0            [required by core_kernel]
  ∗ install bin_prot                v0.14.0            [required by core_kernel]
  ∗ install ppx_base                v0.14.0            [required by core_kernel]
  ∗ install jst-config              v0.14.0            [required by core]
  ∗ install ppx_bin_prot            v0.14.0            [required by ppx_jane]
  ∗ install ppx_string              v0.14.1            [required by ppx_jane]
  ∗ install time_now                v0.14.0            [required by core_kernel]
  ∗ install ppx_module_timer        v0.14.0            [required by ppx_jane]
  ∗ install ppx_inline_test         v0.14.1            [required by core_kernel]
  ∗ install ppx_expect              v0.14.1            [required by ppx_jane]
  ∗ install ppx_bench               v0.14.1            [required by ppx_jane]
  ∗ install splittable_random       v0.14.0            [required by core_kernel]
  ∗ install base_quickcheck         v0.14.0            [required by core_kernel]
  ∗ install ppx_jane                v0.14.0            [required by core]
  ∗ install base_bigstring          v0.14.0            [required by core_kernel]
  ∗ install core_kernel             v0.14.1            [required by core]
  ∗ install timezone                v0.14.0            [required by core]
  ∗ install core                    v0.14.1*
===== ∗ 49   ↗ 4   ⊘ 1 =====
Do you want to continue? [Y/n]
```
In the very first item (as it happens!) it tells you that ocamlformat has to go to satisfy your request.

In opam 2.1 you can say `opam switch create ocamlformat-for-the-win --invariant '"ocamlformat" {= 0.14.0}"'` (you'll get a warning about installing packages which aren't marked as compilers, but that's OK). You now have a switch which states that ocamlformat _must_ be present and must be at version 0.14.0:

```bash
dra@thor:~$ opam switch invariant
["ocamlformat" {= "0.14.0"}]
dra@thor:~$ opam remove ocamlformat
  * Incompatible packages:
    - (invariant) → ocamlformat = 0.14.0
    - (request)
    You can temporarily relax the switch invariant with `--update-invariant'

No solution found, exiting
```

and if you try to install core v0.14.1, you'll get:

```bash
dra@thor:~$ opam install core.v0.14.1
[ERROR] Package conflict!
  * No agreement on the version of stdio:
    - (invariant) → ocamlformat = 0.14.0 → stdio < v0.14
    - core >= v0.14.1 → jst-config >= v0.14 → stdio >= v0.14
    You can temporarily relax the switch invariant with `--update-invariant'

No solution found, exiting
```

You can sort of achieve that in opam 2.0 by having `ocamlformat` as a base package and then using a pin, but it's very clunky.

Incidentally, just in case this was also part of the confusion, you can install a package at a specific version without using a pin at all (as I did above) with `opam install ocamlformat.0.14.0`. However, if you install an older version of a package this way then `opam upgrade` will attempt to update to the latest version - that's where the pins then come in to hold the package at the older version.

**Comment by cdisselkoen** [comment]
Thanks for the response!  This does clear things up.

I did notice that `opam` tells me it's going to remove `ocamlformat` in my first example (which is great!) - I just expected a hard error more along the lines of the `Package conflict!` error that I see you got by installing both at once.  I now understand that I was misunderstanding `pin` though.

Thanks for the help!

**Comment by dra27** [comment]
No problem!
