### ISSUE TITLE
Opam shouldn't suggest to run `eval $(opam env)` in Windows cmd/powershell

### ISSUE THREAD

**Issue by MisterDA** [ocaml/opam#4689]
In some cases, at the end of an Opam 2.0.8 invocation, it suggests to

```
# Run eval $(opam env --root=C:/opam/.opam) to update the current shell environment
```

However, I'm running a Windows cmd shell, and this line has no meaning in that shell. If I'm not mistaken, Opam already has ways of detecting the shell and update the cmd environment on Windows, so it could detect that it shouldn't print this line in this configuration.

**Comment by dra27** [comment]
The shell integration is coming in 2.2 and my patches have long since dealt with this - closing not because it's wrong, but because it won't not (!!) be dealt with when the support's finally merged.
