### ISSUE TITLE
The layout update should not fail even if the installed-switches are incorrect

### ISSUE THREAD

**Issue by smorimoto** [ocaml/opam#4713]
If you run `rm -rf _opam` insetad of `opam switch remove .` to delete a local switch, opam cannot update the config properly. If you try to update the layout under these conditions, you will get an error like the following, but it should not occur or it should be more friendly.

```
~
❯ opam update --upgrade
This version of opam requires an update to the layout of /home/smorimoto/.opam from version 2.1~alpha to version
2.1~rc, which can't be reverted.
You may want to back it up before going further.
Perform the update and continue? [Y/n] y
Fatal error:
Sys_error("/home/smorimoto/src/github.com/REDACTED/REDACTED/_opam/.opam-switch/switch-config: No such file or directory")
```

**Comment by dra27** [comment]
I can reproduce this from 2.1.0~alpha2 onwards, but not for 2.1.0~alpha - was that the release tag or a subsequent build from the master branch in git?

**Comment by dra27** [comment]
Oh no, I see what happened now!
