### ISSUE TITLE
Repetition in the [ERROR] message of $ opam var

### ISSUE THREAD

**Issue by Fourchaux** [ocaml/opam#4785]
(opam 2.1.0)

e.g.
```
$ opam var ocaml:hash
[ERROR] Variable ocaml:hash not found in in switch 4.12.0+flambda
```
Double display of 'in'.

**Comment by kit-ty-kate** [comment]
Thanks a lot for making this issue. I just opened a fix to this: https://github.com/ocaml/opam/pull/4786. It should be fixed in the upcoming opam 2.1.1
