### ISSUE TITLE
feature request : preserve comments while reading/writing opam files

### ISSUE THREAD

**Issue by abate** [ocaml/opam#4799]
Hello,

While using `opam-dune-lint` I've noticed that comments in opam files are removed by 
the functions `OpamFile.OPAM.read` and `OpamFile.OPAM.write`.

Would it be possible to preserve comments ? It's often useful to add annotations in
opam files, but also be able to lint them automatically.

ref: https://github.com/ocurrent/opam-dune-lint/issues/37

**Comment by kit-ty-kate** [comment]
Unless I didn't understand your feature request, I believe `OpamFile.OPAM.to_string_with_preserved_format` is what you want. If so, can this be closed?

**Comment by kit-ty-kate** [comment]
Here is an example of how to use it: https://github.com/ocamllabs/dune-release/blob/71bdccf4765939c29cfd85e17df90a87fd1c1182/bin/opam.ml#L39

**Comment by kit-ty-kate** [comment]
https://github.com/ocurrent/opam-dune-lint/pull/40 fixed your issue it looks like. Feel free to reopen if i got it wrong.
