### ISSUE TITLE
Opam giving patch not installed error

### ISSUE THREAD

**Issue by gitssinghal** [ocaml/opam#4806]
Hi There,

I am trying to build opam on ppc64le from source and i get the following error.

checking for library containing acl_get_perm... no
checking for ocamlobjinfo... ocamlobjinfo
checking for ocamlfind... no
checking for curl... curl
checking for dune... no
checking for cppo... no
checking for patch... no
checking for bunzip2... bunzip2
configure: error: You must have patch installed.
make: *** [Makefile:253: cold] Error 1

Looking at the code, unable to determine which patch it is looking. Please help here.

Regards,
Swati Singhal

**Comment by kit-ty-kate** [comment]
opam requires the patch binary (usually available in `/usr/bin/patch`) to be installed

**Comment by kit-ty-kate** [comment]
The installation will depend on your distribution, but e.g. on Debian-based distributions `sudo apt install patch` should do.

**Comment by gitssinghal** [comment]
great! I installed patch, now it is looking for ocaml which also is not supported on ppc. which repo should i try building, any suggestions?

**Comment by gitssinghal** [comment]
building this : https://github.com/ocaml/ocaml

**Comment by kit-ty-kate** [comment]
> now it is looking for ocaml which also is not supported on ppc.

mmh, which distribution do you have? OCaml does support ppc64le, we're building docker images of opam on ppc64le every week.

Now for your specific case you can simply call `make cold` and it will build everything that is required to build opam (and opam itself) including the ocaml compiler. This should take care of everything for you.

**Comment by gitssinghal** [comment]
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"
Red Hat Enterprise Linux release 8.4 (Ootpa)
Red Hat Enterprise Linux release 8.4 (Ootpa)


This is what i have. doing this inside ubi8 image container. checking make cold

**Comment by gitssinghal** [comment]
With some initial hiccups I am able to install opam using
make cold CONFIGURE_ARGS="--prefix ~/local"
make install
make libinstall

now i can see 

[root@p006vm80 flow]# opam --version
2.2.0~alpha~dev

**Comment by kit-ty-kate** [comment]
Cool! Then I'm guessing I can close this issue. Feel free to reopen if you have another issue or to https://github.com/ocaml/ocaml/issues if you have issues building OCaml itself.

**Comment by gitssinghal** [comment]
yes .. thank you :)
