### ISSUE TITLE
opam init failed

### ISSUE THREAD

**Issue by bobzhang** [ocaml/opam#481]
I tried to install opam on a machine where I don't have root access
hongboz>opam init
Error: http://opam.ocamlpro.com is unavailable.
'opam init' failed.
hongboz>uname -a
Linux UBIQUITY 3.1.10-1.16-desktop #1 SMP PREEMPT Wed Jun 27 05:21:40 UTC 2012 (d016078) x86_64 x86_64 x86_64 GNU/Linux

**Comment by pascalgermain** [comment]
Hi, I installed opam on 2 machines on the same network at the same time, on the 2nd machine the opam init was blocked when it has to download http://opam.ocamlpro.com/urls.txt, so after a (long) while I stopped it, and now it says opam is already initialized, which I can check is wrong, didn't make some stuff I saw it make on the 1st machine. Is it possible to "re-init" it? Thanks!

**Comment by amirmc** [comment]
If nothing was installed, then the simplest way might be to remove `~/.opam` and run `opam init` again.  

Also, which version of opam was this and how did you obtain it?  I'm curious why it's looking for an ocamlpro url (I can see the url but the list is out of date).

**Comment by pascalgermain** [comment]
Thanks for the fast reply, remove the `~/.opam` folder and it worked :) The problem was the machine had lost connection...

Actually the url is https://opam.ocaml.org/urls.txt, I copied/pasted the one from samoht's message... sorry. And the version is 4.02.1. Now I'm stuck on both machines, after the make command I get:
```
File "ocamllib/libbase/uchar.ml", line 1:
Error: Some fatal warnings were triggered (3 occurrences)
Command exited with code 2.
```
But I guess it's off-topic here. Thanks again.

**Comment by amirmc** [comment]
Glad to hear it!  I actually meant the version of opam you were using, not the OCaml compiler, but it doesn't matter now.  It's sometimes useful to include the output of `opam config report` as it answers some of the basic questions.
