### ISSUE TITLE
'eval $(opam env)' doesn't make ocaml find installed modules

### ISSUE THREAD

**Issue by yurivict** [ocaml/opam#4824]
I installed the module ```num``` using opam. Then I ran ```eval $(opam env)```.

However, the command ```#load "nums.cma";;``` in the ocaml prompt fails to find it.

```
$ opam env
OPAM_SWITCH_PREFIX='/usr/home/yuri/.opam/default'; export OPAM_SWITCH_PREFIX;
CAML_LD_LIBRARY_PATH='/usr/home/yuri/.opam/default/lib/stublibs:/usr/local/lib/ocaml/stublibs:/usr/local/lib/ocaml:/usr/local/lib/ocaml/site-lib/parmap:/usr/local/lib/ocaml/site-lib/pcre:/usr/local/lib/ocaml/site-lib/uutf:/usr/local/lib/ocaml/site-lib/ssl:/usr/local/lib/ocaml/site-lib/text:/usr/local/lib/ocaml/site-lib/react:/usr/local/lib/ocaml/site-lib/lablgtk2:/usr/local/lib/ocaml/site-lib/zarith'; export CAML_LD_LIBRARY_PATH;
OCAML_TOPLEVEL_PATH='/usr/home/yuri/.opam/default/lib/toplevel'; export OCAML_TOPLEVEL_PATH;
PATH='/usr/home/yuri/.opam/default/bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin'; export PATH;
```

ocaml-opam-2.1.0
ocaml-4.12
FreeBSD 13

**Comment by dra27** [comment]
I'm assuming you're using ocaml-system in the switch (see output of `opam list`) in which case this is correct - for a system compiler, the num package is installed as a normal ocamlfind package, so (assuming you have ocamlfind installed) you need to issue `#use topfind;;` and then `#require "num";;`

**Comment by rjbou** [comment]
Closing, feel free to reopen if needed.
