### ISSUE TITLE
opam clean --untracked

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#4831]
We currently do not have a way to detect and clean (interactively) a switch containing external/modified files.
It would be nice to have this option around so that when we get warnings such as:
```
[NOTE] While removing ocaml-base-compiler.4.12.0: not removing non-empty directories:
  - share
```
we could do something about it and know what was added or modified in this directory.

Voiced in https://github.com/ocaml/opam/issues/4781

**Comment by rjbou** [comment]
ref also to #4419
