### ISSUE TITLE
Consider Windows opam.exe in official Opam releases

### ISSUE THREAD

**Issue by jonahbeckford** [ocaml/opam#4839]
I'm building and packaging opam.exe in https://gitlab.com/diskuv/diskuv-ocaml/-/releases . There are 32-bit and 64-bit MSVC compiled versions, with some reproducible build scripts that probably only make sense in the Diskuv OCaml Windows distribution.

At the moment this Windows distribution is in preview, but ultimately I think it makes sense to distribute native Windows opam.exe as part of the official Opam releases (https://github.com/ocaml/opam/releases). Perhaps in a few (?) months.

What needs to happen for that to occur?

Related question: Why isn't there already a Windows executable of Opam?

(Consider this as an important but not urgent planning issue)

Thanks! Jonah

**Comment by dra27** [comment]
I'm suffering from a few too many moving parts at the moment, but here's the brief summary 🙂 The actual opam 2.2 roadmap for the rest of this year should be appearing in our wiki in the next few weeks!

The short answer is that there isn't (and won't be) an official Windows distribution of opam until the various upstream parts support it. opam-repository-mingw has always been a (very welcome!) fork, but not with a view to being upstreamed.

For the remaining upstreaming support tasks, I did a developer presentation on some of that last year (there are slides [in the wiki](https://github.com/ocaml/opam/wiki/opam-2.2-slides.pdf)). The nub of the plan for 2.2:

- ocaml/opam-repository needs to support msvc and mingw **in ocaml-base-compiler** (i.e. not as ocaml-variants). I have this one in progress based on the new ocaml-option-* layout. Technically those changes will work with an opam 2.1 Windows binary too.
- Native depext support needs to be implemented
- Finalising the shell support on native Windows

**Comment by jonahbeckford** [comment]
Okay, thanks! Closing.
