### ISSUE TITLE
Synopsis line not printed (with $ opam list)

### ISSUE THREAD

**Issue by Fourchaux** [ocaml/opam#4846]
opam v2.1.0 - iter v1.2.1

The synopsis line of iter:
```
synopsis: "Simple abstraction over `iter` functions, intended to iterate efficiently on collections while performing some transformations"
```
is not printed when running:
$ opam list

Seems a problem with the handling of backquote character inside the string.

**Comment by rjbou** [comment]
`synopsis:` content is printed but it is empty in `iter.1.2.1` opam file. `opam list` only displays `synopsis:` field, not `description:`.
```
$ opam show iter -f version,description:,synopsis: --all
version      1.2
description:
synopsis:    "Simple abstraction over `iter` functions, intended to iterate efficiently on collections while performing some transformations"
version      1.2.1
description: "Simple abstraction over `iter` functions, intended to iterate efficiently on collections while performing some transformations"
synopsis:    ""

**Comment by Fourchaux** [comment]
Well, the iter.opam files are different between:

github/iter 1.2.1:
https://github.com/c-cube/iter/blob/master/iter.opam#L1

and 
my switch: 4.13.0+flambda/.opam-switch/packages/iter.1.2.1/opam:
```
opam-version: "2.0"
synopsis: ""
description:
  "Simple abstraction over `iter` functions, intended to iterate efficiently on collections while performing some transformations"
maintainer: "simon.cruanes.2007@m4x.org"
authors: ["Simon Cruanes" "Gabriel Radanne"]
...
```

**Comment by rjbou** [comment]
Did you pinned `iter` package to a dev repo ? If not, it's the opam repository opam file that is [taken into account](https://github.com/ocaml/opam-repository/blob/master/packages/iter/iter.1.2.1/opam#L2).

**Comment by Fourchaux** [comment]
No dev repo.
The opam-repository file is wrong. How to update it?

**Comment by rjbou** [comment]
You can contact the maintainer via the iter [issue tracker](https://github.com/c-cube/iter/issues), or open a pull request in [opam-repository](https://github.com/ocaml/opam-repository/pulls) (make sure to ping the maintainer in PR comment).
/cc @c-cube
