### ISSUE TITLE
Question: build order and package order on the command line

### ISSUE THREAD

**Issue by MSoegtropIMC** [ocaml/opam#4849]
I maintain an opam based set of build scripts for the Coq proof assistant. I call opam with a largish package list (about 50 directly specified plus about 50 dependencies). On fast multi core machines the build time is dominated by the build time of a single package which remains as sole build target at the end for 20 minutes. Obviously it helps the situation if opam starts building this package as early as possible.

With opam 2.0.X I had the impression that packages specified last on the command line are built earlier, so I gave this package last on the command line. With opam 2.1 I have the impression that the order is now the natural order and packages specified first are built first.

Was there such a change between opam 2.0 and 2.1? Is there a more structured way to tell opam "I know this package builds for a long time, so please start it as early as possible" - say a build priority?

**Comment by AltGr** [comment]
The order on the command-line doesn't affect the build order, in both 2.0 and 2.1. What opam does is build the dependency graph, queue all tasks that are ready, then pick from the queue until the number of allowed processes (`-j`) is reached: I am afraid there is no way to affect the way the processes are picked at the moment.

**Comment by MSoegtropIMC** [comment]
> The order on the command-line doesn't affect the build order, in both 2.0 and 2.1.

I don't think this is likely to be true. The installation order must come from somewhere. Either it is the order in which they have been added to one end of the queue, or the packages are sorted e.g. by depth in the dependency tree and name, or the order is explicitly randomized. I would think the first variant is the most likely one, which implies that it is either the forward or reverse order of the packages given on the command line (with the respective dependencies added in between in some way).

But I think it remained the same in 2.0 and 2.1. E.g. the order in which `[NOTE] Package ... is already installed` notes are printed appears to be the reverse order of packages given on the command line in 2.1. You can easily try this.
