### ISSUE TITLE
CLI versioning: opam-depext support

### ISSUE THREAD

**Issue by dra27** [ocaml/opam#4854]
Cross-referencing issue for https://github.com/ocaml-opam/opam-depext/issues/141 as I can't add Project Notes to milestones!

TL;DR opam-depext should install in opam 2.1.x and invoke an appropriate version of the command (i.e. it should disable opam 2.1's built-in depext if necessary).

**Comment by rjbou** [comment]
merged  & opam-depext 1.2 released!
