### ISSUE TITLE
opam init failed

### ISSUE THREAD

**Issue by ldthan** [ocaml/opam#4856]
opam init
No configuration file found, using built-in defaults.
Checking for available remotes: rsync and local, git.
  - you won't be able to use mercurial repositories unless you install the hg
    command on your system.
  - you won't be able to use darcs repositories unless you install the darcs
    command on your system.

<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>
[ERROR] Could not update repository "default": OpamDownload.Download_fail(_,
        "Curl failed: \"/usr/bin/curl --write-out %{http_code}\\\\n --retry 3
        --retry-delay 2 --user-agent opam/2.1.0 -L -o
        /private/var/folders/yk/j8my1w6d6wj75mpjzz4rskf40000gn/T/opam-10009-993e43/index.tar.gz.part
        -- https://opam.ocaml.org/index.tar.gz\" exited with code 60")
[ERROR] Initial download of repository failed. 

I am using Mac OS 10.14.6.
 opam --version
2.1.0

I am get the error

**Comment by ldthan** [comment]
"`brew upgrade wget`" I was used and it work for my now based on using this ref: https://github.com/ocaml/opam-repository/issues/13111 , thanks

**Comment by dra27** [comment]
Not sure if this was an expired certificate or issues with the recent LetsEncrypt root certificates, but as this seems solved, I'm going to close this one. Please feel free to re-open if the problem re-emerges!
