### ISSUE TITLE
opam list --installed is slow (depexts + yum)

### ISSUE THREAD

**Issue by eponier** [ocaml/opam#4875]
As already noted in [another issue](https://github.com/ocaml/opam/issues/4172#issuecomment-632300057), the opam command written by opam itself in the config files of the editors is slow and thus slows down the start of instances of these editors. I noted that with vim and the comment linked above noted that for emacs.

The culprit is the command `opam list --installed --short --safe --color=never [packages]`. It is rather fast (typically 0.6 s on my system) when it is given installed packages and non-existing packages (although I would expect such command to be instantaneous, not just fast, but I don't know what exactly happens under the hood and it is not blocking in practice). But it is slow when it is given at least one uninstalled package (typically 6.5 s on my system).

I saw that a few issues are open related to performance regressions in latest versions. This may be related.

**Comment by rjbou** [comment]
I'll close it, feel free to reopen it, especially if you have an idea of something faster than `dnff`
