### ISSUE TITLE
Allow installation of binaries in .opam/bin

### ISSUE THREAD

**Issue by raphael-proust** [ocaml/opam#489]
I recently needed to `opam switch system` to build ocp-indent (see 
https://github.com/OCamlPro/typerex/issues/73). The `ocp-indent` executable 
is installed in `.opam/system/bin/ocp-indent`. Thus, after switching back to 
a different compiler, the executable is not in the `PATH` anymore (but is 
still usable).

Binaries that do not depend on the switch-environment should be installed in 
`.opam/bin/` (or other switch-independent directory).

There can be some problems when two switches share common binaries. (Thus, 
binaries should be duplicated to `.opam/bin` rather than only installed 
there.)

**Comment by AltGr** [comment]
There is still no clear story on a "more global than switch" level of installation for packages;
however, for the specific [ocp-indent](https://opam.ocaml.org/packages/ocp-indent/) issue, this is nicely handled by [opam-user-setup](https://opam.ocaml.org/packages/user-setup/), which knows about editor tools that work across switches and will configure them in your editor session accordingly.

**Comment by dra27** [comment]
Also related to #2410

**Comment by AltGr** [comment]
Closing in favor of #2410
