### ISSUE TITLE
Have a way to temporarily remove opam from the environment (opam exec --empty)

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#4951]
Having `opam exec --empty` and ~`opam env --empty`~ or similiar command available would be really nice for setups where you need to take things added by opam out of the equation.

Currently I use a hack instead:
```
$ opam switch create empty --empty
$ eval $(opam env)
```
but this isn’t pretty, nor is it easy to use in scripts

EDIT: I was unaware of `opam env --revert`, but a similar thing with `opam exec` would still be nice

**Comment by Khady** [comment]
there is `eval $(opam env --revert)` which might do what you want

**Comment by kit-ty-kate** [comment]
> there is `eval $(opam env --revert)` which might do what you want

Thanks! I was unaware of opam env --revert, but a similar thing with `opam exec` would still be nice

**Comment by rjbou** [comment]
proposal: add `opam exec --revert-env`
