### ISSUE TITLE
Unable to `opam init` on CentOS 7

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/opam#4954]
I have installed all the pre-requisites, and then I see the following:

<img width="1293" alt="centos" src="https://user-images.githubusercontent.com/1702581/145569836-07e48a8f-eb59-4170-90e5-5edeb6c2f967.png">
.

(tar is installed). Is there any way to report the output of `tar` here to help debugging?

**Comment by kit-ty-kate** [comment]
what was the error? We could always improve the output if it was something that can happen often

**Comment by johnwhitington** [comment]
I'm afraid I accidentally deleted the Virtual Machine concerned. If I see it again I'll let you know.
