### ISSUE TITLE
[META issue] Backport release: 2.1.3

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#5000]
## Fix PRs
* #4882
*  #4999
*  #4934
*  #4998
*  #4978
*  #4971
*  #5017
*  #4982
*  #5030
*  #5056
* #5097
* #5030 
* #5027
* #5117
* #5176
* #5047
* #4879
* #5223
* #5233 

# Reftests updates
* #4965
* #4913
* #4966 
* #4979 
* #4974 
* #5009 
* #5004 
* #5024 (very partial)
* #4963
* #5162
* #5131

**Comment by AltGr** [comment]
woohoo issue #5000 ! :tada:

**Comment by rjbou** [comment]
released! :tada:
