### ISSUE TITLE
Exposing `equal` or `compare` in OpamStd.ABSTRACT

### ISSUE THREAD

**Issue by NathanReb** [ocaml/opam#5003]
I am working with the opam library quite extensively in opam-monorepo and I've had to define those functions myself for a few modules that implement the `OpamStd.Abstract` module type. Given this include a `Map` and `Set` submodule, it also has to define a comparison function and I'd like to be able to use this function so that opam and opam-monorepo agree on it.

I'm aware that in most cases it is simply the polymorphic compare (it'd be great if it wasn't but that's another issue) but exposing this function would simplify external use of the opam libs and would make it future proof: if that function changes internally, external code will still be up to date.

Once again, I'm happy to provide a PR if you think it's a worthy addition!

**Comment by kit-ty-kate** [comment]
Already done in https://github.com/ocaml/opam/pull/4918. This will be part of 2.2.0
