### ISSUE TITLE
Handling external dependencies tries to use `yum` instead of `dnf` on CentOS8.

### ISSUE THREAD

**Issue by sandreenko** [ocaml/opam#5032]
Hello, I am working on CentOS8 and I want to add some opam packages with:
```
opam install core ppx_deriving ocamlscript utop ounit2 bignum batteries sexp_pretty --debug
```
but I am getting such error:
```
The following system packages will first need to be installed:
    gmp-devel

<><> Handling external dependencies <><><><><><><><><><><><><><><><><><><><><><>
Let opam run your package manager to install the required system packages?
(answer 'n' for other options) [Y/n] y
+ /usr/bin/sudo "yum" "install" "gmp-devel"
- sudo: yum: command not found
[ERROR] System package install failed with exit code 1 at command:
            sudo yum install gmp-devel
You can now try to get them installed manually.
```

the issue here is that CentOS8 uses `dnf` not `yum`, so opam should use `sudo dnf install gmp-devel` instead of `sudo yum install gmp-devel`.

Do I understand correctly that this is the problem with tool and the fix should be in this repo or does it look like my local issue? If the later could you please help me with the fix? `--debug` does not show any information about how this command is constructed.

Thank you.

**Comment by kit-ty-kate** [comment]
Was fixed in 2.1.2 (see #4825)

**Comment by sandreenko** [comment]
> Was fixed in 2.1.2 (see #4825)

Thanks @kit-ty-kate , do I understand correctly that  if I use "opam switch create 4.versionAfterTheFix" instead of the current "opam switch create 4.05.0" it would work now?

**Comment by kit-ty-kate** [comment]
no you need to upgrade opam itself. The version of ocaml doesn’t play a role here.
```
bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)"
```
will install the latest version of opam for you.

**Comment by sandreenko** [comment]
oh, I was installing opam with:
```
sudo dnf install opam
```
I guess it points to a source with an old opam tool? I am trying to pack it all into one script that would work for some time without edits. Can I add a repo for "dnf config-manager --add-repo repo" that has a fresh version of opam so `sudo dnf install opam` installs what I need. If yes what would be the repo address?

**Comment by kit-ty-kate** [comment]
> I guess it points to a source with an old opam tool? 

I guess. I’m not sure where you got it though, the main CentOS 8 repositories do not seem to have opam.

> Can I add a repo for "dnf config-manager --add-repo repo" that has a fresh version of opam so `sudo dnf install opam` installs what I need. If yes what would be the repo address?

I have no idea. According to https://repology.org/project/opam/versions, of the RHEL-based distributions, it seems that only Fedora Rawhide is up-to-date, so maybe if there is a way to get it from it, it should mostly be always up-to-date.

**Comment by sandreenko** [comment]
I see, thanks again @kit-ty-kate
