### ISSUE TITLE
Order the list of packages shown when installing by name

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#5041]
When opam installs/upgrades/reinstalls many packages, it is a bit hard to comprehend what opam is going to do and to look for specific packages in that list.

I think it would be nice if opam ordered all the packages in two deterministic ways:
* First by actions (remove, install, upgrade, reinstall)
* Then, within each action group, by name

This way it would be easy to see what’s going on and to look for specific packages, as well as being visually pleasing ^^"

~(for opam devs: concequently this would remove any use of ` | unordered` in the testsuite)~

**Comment by AltGr** [comment]
I like the current ordering (by dependency order), but I don't know what's best from a UI point of view, so I won't mind the change if there is consensus on this; indeed most package managers display it more like you advise (although my reference is `apt` and I can't say the display is nice).

> (for opam devs: concequently this would remove any use of | unordered in the testsuite)

Not really, that wasn't needed for the summary of actions, which is deterministic, but for the messages during the parallel resolution of actions afterwards.

**Comment by rjbou** [comment]
Addressed in #5045
