### ISSUE TITLE
Feature request: Have an option to disable git --depth 1 on opam source --dev

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#5061]
When pulling the git sources of an opam package it would be nice to have an option to make it not use `--depth 1` (or the opposite, remove the `--depth 1` by default and add an option for that).
It would avoid having to do the annoying subsequant `git pull --unshallow` to it, to be able to push stuff to a fork for instance

**Comment by kit-ty-kate** [comment]
Actually this is a change/regression in 2.2. Adding temporarily to the 2.2 project for discussion at the next dev meeting.

**Comment by kit-ty-kate** [comment]
Something discovered is also that there seems to be an issue with caching. We might want to have a futher look at it.
```
$ opam source -vvvv integers --dev-repo
[...]
+ git "push" "$HOME/.opam/download-cache/git" "+refs/remotes/opam-ref:refs/remotes/947ec437042b4a98874a2870ccf8bb84" (CWD=$HOME/integers)
- To $HOME/.opam/download-cache/git
-  ! [remote rejected]       opam-ref -> 947ec437042b4a98874a2870ccf8bb84 (shallow update not allowed)
- erreur : impossible de pousser des références vers '$HOME/.opam/download-cache/git'
```

**Comment by shym** [comment]
A small suggestion regarding the interface: I would imagine in many cases users will know they should have used the opam option only when they are blocked later down the line, wouldn’t they? So I would suggest an extra message, teaching users the git `--unshallow` option, when a shallow clone is performed.
(The caching is more of a concern though)

**Comment by moyodiallo** [comment]
> Something discovered is also that there seems to be an issue with caching. We might want to have a futher look at it.
> 
> ```
> $ opam source -vvvv integers --dev-repo
> [...]
> + git "push" "$HOME/.opam/download-cache/git" "+refs/remotes/opam-ref:refs/remotes/947ec437042b4a98874a2870ccf8bb84" (CWD=$HOME/integers)
> - To $HOME/.opam/download-cache/git
> -  ! [remote rejected]       opam-ref -> 947ec437042b4a98874a2870ccf8bb84 (shallow update not allowed)
> - erreur : impossible de pousser des références vers '$HOME/.opam/download-cache/git'
> ```

I think this could be in separate issue.

**Comment by kit-ty-kate** [comment]
> I think this could be in separate issue.

could you open it separately?
