### ISSUE TITLE
Question: how to set gcc option "-mmacosx-version-min" for a complete switch?

### ISSUE THREAD

**Issue by MSoegtropIMC** [ocaml/opam#5064]
I am using opam to build executables which I then package into a binary installer for macOS. One issue with this is that the range of macOS versions supported by the resulting binaries is a bit random this way.

I found that Xcode gcc has an option "-mmacosx-version-min" which one can set to ensure that the resulting binaries are compatible with the chosen macOS version or higher.

I wonder what the safest / recommended method would be to pass this option to everything opam builds with gcc for a specific switch.

**Comment by dbuenzli** [comment]
I may be wrong but I think `ocaml` honour `CFLAGS` nowadays. So maybe try setting the env var when you create the switch.

**Comment by MSoegtropIMC** [comment]
Isn't it so that opam does some environment sanitation to ensure reproducible builds? I can't find a reference for it right now but I believe to remember something like this.

**Comment by kit-ty-kate** [comment]
> Isn't it so that opam does some environment sanitation to ensure reproducible builds?

No it does at the moment, I believe because there are too many environement variable that could be used/useful and listing them all in all context is rather tedious.

**Comment by MSoegtropIMC** [comment]
OK, thanks! I will try my luck with CFLAGS, CXXFLAGS & Co then.

It would be nice if one could set environment variables in a switch, so that successive packages are also compiled with these settings, but since I anyway use wrapper scripts for opam, I am fine.

**Comment by dbuenzli** [comment]
> It would be nice if one could set environment variables in a switch,

You can do so via a dummy package which has a [`setenv`](https://opam.ocaml.org/doc/Manual.html#opamfield-setenv) field. E.g.
```
setenv:
[[PKG_CONFIG_LIBDIR =+ "%{prefix}%/usr/share/pkgconfig" ]
 [PKG_CONFIG_LIBDIR =+ "%{lib}%/pkgconfig" ]
 [PKG_CONFIG_LIBDIR =+ "%{share}%/pkgconfig" ]]
```

I'm also a bit unsure about whether you can maybe achieve that with `opam var VAR=value` (that's opam variables, but I'm no longer sure if they get reified as env vars or not).

**Comment by MSoegtropIMC** [comment]
@dbuenzli : thanks for the pointers!

Wouldn't a package with setenv only influence dependent packages and the shell? I would interpret (https://opam.ocaml.org/doc/Manual.html#opamfield-setenv) this way.

I will do some experiments with the setenv field in switch-config.

**Comment by dbuenzli** [comment]
> Wouldn't a package with setenv only influence dependent packages and the shell? I would interpret (https://opam.ocaml.org/doc/Manual.html#opamfield-setenv) this way.

Yes indeed you would need to add it as some kind of root dependency. I bet since you want to use the stock opam-repo that's not really an option.

**Comment by MSoegtropIMC** [comment]
Well I do have a local patch opam repo anyway - which I register before compiling OCaml - and I use a specific version of OCaml, so I could add it to the OCaml package itself, but it wouldn't be that nice.

**Comment by dbuenzli** [comment]
Maybe you could use [switch invariants](https://opam.ocaml.org/blog/opam-2-1-0/#Switch-invariants) for that (don't know how they work just waving into directions :–).

**Comment by MSoegtropIMC** [comment]
As far as I understand this switch invariants don't influence package dependencies, so that one can't introduce a global dependency this way, but I might be wrong - I will test it.

**Comment by MSoegtropIMC** [comment]
To summarize the most promising approaches I see are:

- use a patched OCaml package with a setenv line (or create an extra package for it and depend OCaml on it). This is not problematic for me since I anyway have a local opam patch repo and use a specific version of OCaml.

- use environment variables set in my scripts - this has the disadvantage that packages installed later by the user wouldn't see this setting, but this is anyway only relevant when creating installers - not when creating locally compiled installations.

- patch the `setenv` field in the switch-config file (I anyway first create an empty switch and then later add OCaml). I am not sure how safe this is (that is if this field is regenerated every now and again.

**Comment by dbuenzli** [comment]
> * patch the `setenv` field in the switch-config file

Note that it should be possible to use `opam option --switch=$(SW)` for that (avoids hardcoding opam managed file paths).

**Comment by MSoegtropIMC** [comment]
> Note that it should be possible to use opam option --switch=$(SW) for that (avoids hardcoding opam managed file paths).

Very nice - I was not aware of `opam option` and the `FIELD+=VALUE` syntax.
