### ISSUE TITLE
Pinning base (?) packages doesn't show `pin` url and `source-hash` 

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#5072]
Being able to pin the `ocaml` package is absolutely fantastic.  

However in `opam` 2.1.2, in contrast with what happens when I pin other packages, the `pin` url and `source-hash` fields are not shown on `opam info ocaml`.

That would be great to have. Thanks.

**Comment by kit-ty-kate** [comment]
> `source-hash` fields are not shown on `opam info ocaml`.

note that it would be on `opam info ocaml-variants` in this case as `ocaml` is just a virtual package.

However in this case after a little digging I realized it’s not opam that’s responsible here but opam-repository.
`source-hash` is indeed present for pinned packages and packages whose source is a git repository, however in this case the `ocaml-variants` packages usually chose the `https://github.com/<org>/<proj>/archive/<branch>.tar.gz` route, so opam is not being able to recover the hash from there (as the archives are not git repositories themselves, only auto-generated from git repository)

Transfering to opam-repository (basically to fix this all the packages using the live archive trick have to be moved to use the git repository instead)
