### ISSUE TITLE
Add json library

### ISSUE THREAD

**Issue by rjbou** [ocaml/opam#5085]
For the moment there is just an internal [json encoder & basic printer(https://github.com/ocaml/opam/blob/master/src/core/opamJson.mli).
Software heritage fallback need to parse json (ftm it is done via regexp), and in order to have a better support of json output (mainly tests), it is better to have a printer. Instead of rewrite another json library, proposal was done to integrate `jsonm`.

**Comment by avsm** [comment]
Using jsonm sounds good to me.
