### ISSUE TITLE
Reversal of dependencies with opam uninstall

### ISSUE THREAD

**Issue by MSoegtropIMC** [ocaml/opam#5105]
When I want to uninstall a package, opam wants to recompile packages the uninstalled packages depend on (not the other way around):
```
$ opam uninstall coq-vst
The following actions will be performed:
  - remove    coq-vst      2.9.1
  - recompile coq-compcert 3.10  [uses coq-vst]
===== 1 to recompile | 1 to remove =====
Do you want to continue? [Y/n] n
```
The respective opam files are:
[coq-compcert](https://github.com/coq/opam-coq-archive/tree/master/released/packages/coq-compcert/coq-compcert.3.10)
[coq-vst](https://github.com/coq/opam-coq-archive/tree/master/released/packages/coq-vst/coq-vst.2.9.1)
So clearly coq-vst depends on coq-compcert, and not the other way around. Why would opam recompile coq-compcert, when I uninstall coq-vst? Do I miss something?

```
# opam config report
# opam-version         2.1.0 
# self-upgrade         no
# system               arch=x86_64 os=macos os-distribution=macports os-version=11.6.2
# solver               builtin-mccs+glpk
# install-criteria     -removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed
# upgrade-criteria     -removed,-count[avoid-version,changed],-count[version-lag,solution],-count[missing-depexts,changed],-new
# jobs                 15
# repositories         4 (http), 14 (local) (default repo at 77c72183)
# pinned               0
# current-switch       __coq-platform.2022.03.0~8.15~2022.03
# ocaml:native         true
# ocaml:native-tools   true
# ocaml:native-dynlink true
# ocaml:stubsdir       /Users/msoegtrop/.opam/__coq-platform.2022.03.0~8.15~2022.03/lib/ocaml/stublibs:/Users/msoegtrop/.opam/__coq-platform.2022.03.0~8.15~2022.03/lib/ocaml
# ocaml:preinstalled   false
# ocaml:compiler       4.12.1+options+flambda
```

**Comment by rjbou** [comment]
It clearly shouldn't recompile `coq-compcert`, as there is dependency in this way. Maybe`cop-compcert` has been marked as to recompile, and removing `coq-vst` triggers it.
Are you able to reproduce? In a fresh install, it works as usual, with a minimal case, and with those packages.

**Comment by MSoegtropIMC** [comment]
I will check this, but even if this would be the case, the `[uses coq-vst]` is strange.

**Comment by rjbou** [comment]
I should print another message i agree, this one is not the good one.
I'll make as non reproducible, and we'll reopen when/if encountered again.
