### ISSUE TITLE
opam-core fails to build with cmdliner-1.1.1

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ocaml/opam#5120]
```
Error: No implementations provided for the following modules:
         Cmdliner_term_deprecated referenced from /usr/lib64/ocaml/cmdliner/cmdliner.cmxa(Cmdliner)
```
From https://github.com/gentoo/gentoo/pull/24951#issuecomment-1099772717

**Comment by dra27** [comment]
This is a bug in the packaging of cmdliner, not opam - though please re-open if that turns out to be an incorrect assessment!
