### ISSUE TITLE
Non-interactively installing depext in 2.1

### ISSUE THREAD

**Issue by maroneze** [ocaml/opam#5121]
I'm trying to build a Docker image with opam on Alpine `edge` (I couldn't find ready-made Docker images for that version of Alpine), so I just installed opam from `apk`, plus several required packages, and then tried installing something using depext.

My commands with pre-2.1 opam were: `opam install depext -y && opam depext frama-c`.

However, `opam install depext` now fails, since it is no longer a package.

But if I try `opam depext frama-c` directly, it asks *interactively* *Opam plugin "depext" is not installed. Install it on the current switch? [Y/n]*. That kind of prompt is not very helpful when running Docker commands. And even if I add `--yes` to the `opam depext` command, it does not work.

Is there a way to configure the depext plugin without having to try `opam depext` and then answering "yes" to that prompt?

```
# opam config report
# opam-version         2.1.2 (750a64fe9bae1a16145bf0c2ccf690bdccb5a407) 
# self-upgrade         no
# system               arch=x86_64 os=linux os-distribution=alpine os-version=3.16.0_alpha20220328
# solver               builtin-mccs+glpk
# install-criteria     -removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed
# upgrade-criteria     -removed,-count[avoid-version,changed],-count[version-lag,solution],-count[missing-depexts,changed],-new
# jobs                 11
# repositories         1 (http) (default repo at efb39a00)
# pinned               0
# current-switch       4.12.1
# ocaml:native         true
# ocaml:native-tools   true
# ocaml:native-dynlink true
# ocaml:stubsdir       /home/opam/.opam/4.12.1/lib/ocaml/stublibs:/home/opam/.opam/4.12.1/lib/ocaml
# ocaml:preinstalled   false
# ocaml:compiler       4.12.1
```

**Comment by rjbou** [comment]
As you are using opam 2.1, you no more need to call `opam depext`: the plugin was [integrated](https://opam.ocaml.org/blog/opam-2-1-0/#Seamless-integration-of-System-dependencies-handling-a-k-a-quot-depexts-quot) in opam itself.
When installing a package, opam checks and asks you to install system dependencies.
If you want to avoid interactive questions, you have the `--confirm-level` option
```
--confirm-level=LEVEL

Confirmation level, LEVEL must be one of ‘ask', ‘no', ‘yes' or ‘unsafe-yes'. Can be specified more than once.
If --yes or --no are also given, the value of the last --confirm-level is taken into account.
```

**Comment by maroneze** [comment]
Thanks! I had never seen the `--confirm-level` option, and indeed `unsafe-yes` seems to work for my Docker case.
