### ISSUE TITLE
Cannot install conf-LLVM via OPAM, on cygwin

### ISSUE THREAD

**Issue by zhenweigc** [ocaml/opam#5138]
>   If your issue concerns a package not building, please report to
>   https://github.com/ocaml/opam-repository/issues or to the package maintainer
>   unless you are confident it is an issue in the opam tool itself.
As you can see, I cannot install conf-llvm properly via opam.
![image](https://user-images.githubusercontent.com/15207351/167270460-5fa3cd07-a680-4835-9d5d-e29d7602c824.png)
Here is a list of packages i have installed
![image](https://user-images.githubusercontent.com/15207351/167270501-99be4e0d-a7c3-4061-a006-c0c0842bb8d7.png)

![image](https://user-images.githubusercontent.com/15207351/167270478-008a887d-27ad-48a6-b2d3-2160251c5570.png)
config report as required

**Comment by dbuenzli** [comment]
It seems you don't have `llvm-config`  in your `PATH`.

**Comment by zhenweigc** [comment]
> It seems you don't have `llvm-config` in your `PATH`.

Ah I see. So what should I add to Path?
More specifically, what should I add after 'export PATH=$PATH:'?

**Comment by dbuenzli** [comment]
The directory in which you have the `llvm-config` binary.

**Comment by dbuenzli** [comment]
Note this is not a problem for `opam` per se, nor for `opam-repository` where you should have filed this. Rather it seems a problem with your environment. 

It's likely better to close this and seek help on https://discuss.ocaml.org where there are more people willing to help with these things (and in particular, hopefully, other windows users).

**Comment by zhenweigc** [comment]
Sure, I haven't find the correct path to add with yet. But I will close the issue for now. Thanks for the comment.
