### ISSUE TITLE
system dependencies installation fails because flag --yes is not passed to apt

### ISSUE THREAD

**Issue by paracetamolo** [ocaml/opam#5140]
When run non-interactively, even if opam is called with option `--yes` (or OPAMYES=true), during the installation of the system dependencies, `apt-get install` aborts at `Do you want to continue? [Y/n] Abort.` because it can't read stdin.  
I think opam should pass the option `--yes` to `apt-get`. 

This problem was not present with opam < 2.1 using depext.

Setting: docker image `debian:bookworm-slim` used by gitlab CI.
```
# opam config report
[WARNING] Running as root is not recommended
# opam config report
# opam-version         2.1.2 
# self-upgrade         no
# system               arch=x86_64 os=linux os-distribution=debian os-version=unknown
[ERROR] Opam has not been initialised, please run `opam init'
# read-state           OpamStd.OpamSys.Exit(50)
```

**Comment by rjbou** [comment]
There is the option `--confirm-level` that you can set to `unsafe-yes` (or `OPAMCONFIRMLEVEL`) to permit running system package manager non interactively.

**Comment by liyishuai** [comment]
The current hint is not so informative. Maybe worth reminding the user of `OPAMCONFIRMLEVEL` if OPAM knows that it is run non-interactively?

    <><> Handling external dependencies <><><><><><><><><><><><><><><><><><><><><><>
    Let opam run your package manager to install the required system packages?
    (answer 'n' for other options) [Y/n] n
    [NOTE] Use 'opam option depext-run-installs=false' if you don't want to be prompted again.
    This command should get the requirements installed:
  
        apt-get install clang
  
    You can retry with '--assume-depexts' to skip this check, or run 'opam option depext=false' to permanently disable handling of system packages altogether.

**Comment by kit-ty-kate** [comment]
I’ve reopened this as i feel like it indeed might need a hint somewhere. @liyishuai if you have any idea how to phrase this, please feel free to open a PR.
