### ISSUE TITLE
How to re-install an old version of opam ?

### ISSUE THREAD

**Issue by jserot** [ocaml/opam#5170]
When trying to upgrade my version of `opam`, the install script failed (probably due to the fact that my version of Mac OS, 10.12, is a rather old one):

```
$ bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)"
## Downloading opam 2.1.2 for macos on x86_64...
## Downloaded.
## Where should it be installed ? [/usr/local/bin] 
Write access to /usr/local/bin required, using 'sudo'.
Command: rm -f /usr/local/bin/opam
Password:
Write access to /usr/local/bin required, using 'sudo'.
Command: install -m 755 /var/folders/s4/f89rj2j88xj249001s6j4jr80000gp/T//opam-2.1.2-x86_64-macos /usr/local/bin/opam
## opam 2.1.2 installed to /usr/local/bin
## Converting the opam root format & updating
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/opam
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/opam
  Expected in: /usr/lib/libSystem.B.dylib

/dev/fd/63: line 453: 31175 Abort trap: 6           "$BINDIR/opam" init --reinit -ni
```

This left me with an unusable version of `opam`. 
I can't even rebuild it from sources since the only "surviving" `ocamlc` compiler is `4.02.2` and the build process requires `4.02.3` :(

My previous version of `opam` was 2.0.3` (IIRC).

Is there a way of telling the install script to use an previous version instead of the latest ?

**Comment by kit-ty-kate** [comment]
> Is there a way of telling the install script to use an previous version instead of the latest ?

Yes:
```
bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh) --version 2.0.3"
```

**Comment by dra27** [comment]
The script only goes back to 2.0.6 - there are binaries on the 2.0.3 release tag at https://github.com/ocaml/opam/releases/tag/2.0.3

**Comment by jserot** [comment]
Thanks !
