### ISSUE TITLE
How to install package with updated constraints?

### ISSUE THREAD

**Issue by tsnobip** [ocaml/opam#5178]
Let's say I add a constraint to my opam file, like going from 
```opam
  "ocamlformat" {dev}
```
to 
```opam
  "ocamlformat" {dev & = "0.21.0"}
```

Neither `opam install . -w`, `opam reinstall . -w` or `opam upgrade . -w` will reinstall ocamlformat with version 0.21.0.

What should I do?

**Comment by kit-ty-kate** [comment]
I was unable to reproduce the issue with the latest opam master. Which version of opam do you have, and if it is 2.1.2, could you try with the latest master to see if this has been fixed?

**Comment by tsnobip** [comment]
sure I'm gonna try with master, I'm using 2.1.2 right now.
