### ISSUE TITLE
opam ubuntu ppa

### ISSUE THREAD

**Issue by hannesm** [ocaml/opam#5222]
Hello,

I don't know where to report this issue proiperly, but I was wondering about the "ubuntu" "ppa" that distribute some opam packages, namely I'm on ubuntu 20 and tried to add opam 2.1, using` deb http://ppa.launchpad.net/avsm/ppa/ubuntu focal main` in my `/etc/apt/sources.list`.

Now, I'm curious how this "ppa" is actually updated and maintained, since I was not able to find any newer opam version than 2.1.0 in there. Also, the `opam` package in there failed to install since the `opam-installer` and `opam-doc` ubuntu packages (2.0.5, previously installed) owned some files that the `opam` package wants to install as well.

Is there any documentation about the ppa, and how and when packages are added (//cc @avsm)?

**Comment by kit-ty-kate** [comment]
The ppa has been removed from the recommended installation for ubuntu in https://github.com/ocaml/opam/pull/5988. The install script will always provide the latest version for those who need it, in case the latest version in ubuntu's package repository is out-of-date.
