### ISSUE TITLE
Add an option to select temp_dir

### ISSUE THREAD

**Issue by palainp** [ocaml/opam#5264]
>   If your issue concerns a package not building, please report to
>   https://github.com/ocaml/opam-repository/issues or to the package maintainer
>   unless you are confident it is an issue in the opam tool itself.

On QubesOS 4.1 the /tmp partition is mounted with a small number of inodes. This leads to an impossible update of the opam.
Step to reproduce:
```
[user@dev ~]$ sudo mount -o remount,nr_inodes=8192 /tmp
[user@dev ~]$ opam update -yu

<><> Updating package repositories ><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] Could not update repository "default": /usr/local/bin/opam: "mkdir"
        failed on /tmp/opam-2872-22f107: No space left on device
...
```
One solution I've been using for a while is to increase the number of inodes on /tmp, but I wonder if it's possible to add a specific option to tell opam what the temporary directory is (defaulted to /tmp)?

```
[user@dev ~]$ opam config report
# opam config report
# opam-version         2.1.2 
# self-upgrade         no
# system               arch=x86_64 os=linux os-distribution=fedora os-version=34
# solver               builtin-mccs+glpk
# install-criteria     -removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed
# upgrade-criteria     -removed,-count[avoid-version,changed],-count[version-lag,solution],-count[missing-depexts,changed],-new
# jobs                 3
# repositories         1 (http), 2 (version-controlled) (default repo at 549f56d6)
# pinned               1 (git), 1 (rsync)
# current-switch       default
# ocaml:native         true
# ocaml:native-tools   true
# ocaml:native-dynlink true
# ocaml:stubsdir       /home/user/.opam/default/lib/ocaml/stublibs:/home/user/.opam/default/lib/ocaml
# ocaml:preinstalled   false
# ocaml:compiler       4.14.0
```

**Comment by rjbou** [comment]
opam uses [`Filename.get_temp_dirname`](https://v2.ocaml.org/api/Filename.html#VALget_temp_dir_name), so you can change it with `TMPDIR` environment variable.

fyi, related sandbox PR #4589

**Comment by palainp** [comment]
Thanks a lot for the pointer!
