### ISSUE TITLE
https://opam.ocaml.org/ is down

### ISSUE THREAD

**Issue by alexeyt** [ocaml/opam#5292]
Website is down. Fetching packages fails.

**Comment by Wilfred** [comment]
Previously #3724 -- is there a similar GC going on?

**Comment by cridlig** [comment]
Still down

**Comment by avsm** [comment]
It's rebuilding. Should be up shortly.

**Comment by dra27** [comment]
It's indeed back up - not related to #3724, no, @Wilfred 🙂
