### ISSUE TITLE
`opam tree` JSON output for Opam Dependency Submission

### ISSUE THREAD

**Issue by smorimoto** [ocaml/opam#5298]
I think we all know that https://github.com/ocaml/opam/issues/3775 and https://github.com/ocaml/opam/pull/5171 eventually merged and it works pretty well. But the tree is output for humans, not for machines. I would like to propose a subsequent PR implementation that outputs JSON for ODS. The structure here doesn't have to be for ODS, I think it would be better to have a more general structure. Does anyone have any thoughts?

**Comment by smorimoto** [comment]
CC: @rjbou @cannorin

**Comment by cannorin** [comment]
I think it would need some RFC for the format of the said JSON. @smorimoto can you suggest some example JSON output you would need so that we can discuss the format based on it?

**Comment by rjbou** [comment]
The rfc is a good point. Note, at the beginning we can set it as experimental, and finalise the output after some use.

**Comment by cannorin** [comment]
Opened a PR in #5303, where the output JSON has the type `Forest` in the following structure:

```typescript
interface Package {
  name: string;
  version: string;
}

interface DepsTree extends Package {
  dependencies: DepsNode[];
}

interface DepsNode extends DepsTree {
  satisfies: string | null;
  is_dup: boolean;
}

interface RevdepsTree extends Package {
  requirements: RevdepsNode[];
}

interface RevdepsNode extends RevdepsTree {
  demands: string | null;
  is_dup: boolean;
}

type Forest = DepsTree[] | RevdepsTree[]
```

Also, here is an example output: https://gist.github.com/cannorin/ae87f55695c38356a9b880e0418a7a12

What do you think? @smorimoto

**Comment by cannorin** [comment]
Note that there are no JSON encoders for `OpamFormula` and `OpamFilter`, so the condition formula is encoded as just `string`.

Do you want the condition formula to be properly encoded?
