### ISSUE TITLE
API struggle how to download a package

### ISSUE THREAD

**Issue by hannesm** [ocaml/opam#5313]
Dear opam developers,

I've come across the third-party tool "opam monorepo", which (amongst other things) downloads opam packages into a local directory. It uses the `OpamRepository.pull_tree : string -> ?cache_dir:dirname -> ?cache_urls:url list -> ?working_dir:bool -> ?subpath:subpath -> dirname -> OpamHash.t list -> url list -> string download OpamProcess.job`. The main issue with this function is that it doesn't respect any `archive-mirrors` (which `OpamUpdate.download_package_source : 'a switch_state -> package -> dirname -> (string download option * (string * string download) list) OpamProcess.job` does respect).

So, I was wondering whether it would be possible to adapt the behaviour of `OpamRepository.pull_tree` to use the `archive-mirror` (of all repositories, or at least the global one (see #5272)? This would be great and reduce the network load, especially in low bandwidth situations.

Unfortunately, in "opam monorepo" the "OpamUpdate.download_package_source" cannot easily be used, since it loads a "lock" file with the URLs and downloads them, i.e. the package names and vesions are already gone.

Thanks a lot for taking care of opam.

**Comment by kit-ty-kate** [comment]
`OpamRepository.pull_tree` already accepts a `?cache_urls` optional argument.
If you look at the implementation of `OpamUpdate.download_package_source` you can see this argument can directly be given `OpamFile.Config.dl_cache st.switch_global.config` to handle `archive-mirrors`

So to summarize, doing something like that should work (hopefully, i haven't tested):
```
OpamSwitchState.with_ `Lock_none gt @@ fun st ->
let cache_urls = OpamFile.Config.dl_cache st.switch_global.config in
OpamRepository.pull_tree ~cache_urls ...

**Comment by kit-ty-kate** [comment]
Now that said this shows that the opam code base tends to overuse optional arguments in my opinion and we should probably think of removing a handful of them in my opinion.

**Comment by hannesm** [comment]
Indeed, thanks @kit-ty-kate -- your proposed code works (and can even be simplified since we've at the call site the global_state already to `let cache_urls = OpamFile.Config.dl_cache global_state.config in`. I opened a PR for opam-monorepo and will close this.
