### ISSUE TITLE
https://opam.ocaml.org/ is down

### ISSUE THREAD

**Issue by rmatthes** [ocaml/opam#5322]
Already for an hour or so, no chance to execute `opam init` or `opam update`. Looking at the output of `opam repo list`, I tried `ping opam.ocaml.org` without response. I do not know if that server would respond to ping when operating normally.

**Comment by dra27** [comment]
Is it still down (just 6 mins later?) - it seems to be fine for me here?

**Comment by rmatthes** [comment]
I am experiencing the same problems as before - on two computers that otherwise communicate with the internet.

**Comment by rjbou** [comment]
good for me too. Ping doesn't work (maybe blocked?) but retrieving archive is ok.

**Comment by rjbou** [comment]
Can you try `wget https://opam.ocaml.org/index.tar.gz` (or `your favorite download tool`)?

**Comment by rmatthes** [comment]
Okay, ping is not the best test, but `opam update` does not work either. I am on Ubuntu 20.04 with opam v2.0.5. And I wanted to do `opam init` on a fresh Ubuntu 22.04 installation with opam v2.1.2.

The `wget` command succeeds, but download is as slow as 10kB/s.

**Comment by rmatthes** [comment]
When I try to download Ubuntu 22.04, the speed is around 10MB/s. So, it is not my internet connection in general. Maybe the problem is related to IPv6?

**Comment by rjbou** [comment]
My average speed was 4.6MB/s, it could originate from your internet connection?
You can see what's happening with command launched by opam with `-vv` (`curl` & `wget` display progression).

**Comment by rmatthes** [comment]
Update: the update with opam v2.0.5 finally succeeded.
I launched  `opam init -vv` on Ubuntu 22.04. This confirms the 10kB/s - thanks a lot.
So, the OPAM server is not down but serving so slowly that it becomes useless for me.

**Comment by rjbou** [comment]
Good to hear!

**Comment by rjbou** [comment]
You can try to use git repository instead opam.ocaml.org one, maybe you would have a different speed?
```
 opam repo set-url default git+https://github.com/ocaml/opam-repository
 ```

**Comment by rmatthes** [comment]
@rjbou Thanks a lot for this final advice. I had no further problems when installing the prerequisites for Coq (that I install from sources) after following it.
