### ISSUE TITLE
Add xz to the list of recommended tool checked during init

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#5341]

**Comment by kit-ty-kate** [comment]
(oops keyboard typed enter too soon ^^")

**Comment by progressive-galib** [comment]
done

**Comment by progressive-galib** [comment]
@kit-ty-kate so are you gonna  close it or merge it ?

**Comment by kit-ty-kate** [comment]
Since nobody had any issues in 2 years and i'm unable to remember or reproduce what was the problem with opam, lets close it. We can always reopen it later if needed.
