### ISSUE TITLE
how to get visibility into `opam install` build-dir preparation process ?

### ISSUE THREAD

**Issue by chetmurthy** [ocaml/opam#5379]
Hello, I have a bug I'm chasing that involves a mis-prepared build-directory.  It's somewhat reproducible, but not completely.  Is there some way I can get opam to spit out a trace of the commands it uses to prepare the build-directory before running build-commands ?

**Comment by kit-ty-kate** [comment]
`-vvv` should be able to do that. If this is not enough `--debug` and if that's again not enough `--debug-level=3` is the highest level of debug we have

**Comment by chetmurthy** [comment]
Ah, excellent!  Thank you!  When it happens next, I'll be armed!
