### ISSUE TITLE
opam update is failing

### ISSUE THREAD

**Issue by ncihnegn** [ocaml/opam#5408]
```
$ opam update

<><> Updating package repositories ><><><><><><><><><><><><><><><><><><><><>  🐫
[default] no changes from https://opam.ocaml.org
[ERROR] Could not update repository "default": In
        /private/var/folders/x8/8s64cxbx0yj16d3shdxmm5gr0000gn/T/opam-12814-5e0534/default/packages/ocaml-variants/ocaml-variants.5.0.0+trunk/opam:
        unsupported or missing file format version; should be 2.0 or older
```

And I can't open
https://opam.ocaml.org/packages/ocaml-variants/ocaml-variants.5.0.0+trunk/

**Comment by dra27** [comment]
I think this can be worked around by erasing the repo state and re-updating (@rjbou ?)

**Comment by dra27** [comment]
@ncihnegn - it's possible that another `opam update` should now fix the problem. If it doesn't, you should be able to do: `opam repo set-url default git+https://github.com/ocaml/opam-repository` and then `opam repo set-url default https://opam.ocaml.org`, as that will trigger a re-init.

**Comment by ncihnegn** [comment]
It works after re-init.
