### ISSUE TITLE
2.0.11/2.1.5 PRs & issues to backport

### ISSUE THREAD

**Issue by rjbou** [ocaml/opam#5409]
### Todo
* [x] #5352
* [x] #5350
* [x] #5315 
* [x] #5342
* [x] #5538

**Comment by hannesm** [comment]
could both of these PRs being packported? As usual, it is debatable whether these are bugfixes or features, but honestly they're both low-profile and make the behaviour of opam much more in line of user expectations (i.e. without 5321 I can't use archive-mirrors with "opam-monorepo")
- https://github.com/ocaml/opam/pull/5321
- https://github.com/ocaml/opam/pull/5342

**Comment by dra27** [comment]
@hannesm - no problem, both added to the list

**Comment by rjbou** [comment]
released!
