### ISSUE TITLE
`opam switch create .` hangs

### ISSUE THREAD

**Issue by apsheronets** [ocaml/opam#5413]
STEPS TO REPRODUCE

being on Debian 11.6 x86_64 GNU/Linux
`sudo apt-get install opam`
`opam init` (press n then y cause dunno)
`mkdir test && cd test`
`$(opam env)`
`opam switch create .` (result: nothing)

Before the handing up the process was trying to readlink _opam file 26071 times (I checked with strace)

By the way, `opam switch create . 4.14.1` works totally fine.

**Comment by apsheronets** [comment]
Okay. I found the app doesn't really hang, it just calculates the version of OCaml to install for 10 seconds.

**Comment by apsheronets** [comment]
Okay, it's even worse when you have a `packagename.opam` file in the current directory. In this case, it's 2 minutes instead of 10 seconds.

**Comment by apsheronets** [comment]
Okay. I did some `perf` and figured out that something called `EdosSolver` sucks.
I think my adventure ends here.

**Comment by kit-ty-kate** [comment]
Could you try with the latest version of opam https://opam.ocaml.org/doc/Install.html ? The version debian 11 ships with is almost 5 years old

**Comment by apsheronets** [comment]
```
$ wget -q "https://github.com/ocaml/opam/releases/download/2.1.4/opam-2.1.4-arm64-linux" 
$ chmod +x opam-2.1.4-arm64-linux 
$ ./opam-2.1.4-arm64-linux 
zsh: exec format error: ./opam-2.1.4-arm64-linux
$ uname -a
Linux hostname 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux
```
I think I'm fine with my 5 years old version.

**Comment by apsheronets** [comment]
Okay, after confusing arm64 with amd64 I was able to get a binary of opam 2.1.4 and found it not performing any long operations which look like "hanging".

**Comment by apsheronets** [comment]
(by the way, the version of opam 2.0.8 debian stable having was released just less than 2 years ago!)
https://github.com/ocaml/opam/releases/tag/2.0.8

**Comment by kit-ty-kate** [comment]
The 2.0 branch is 5 years old. The 8 minor releases are only minor backports

**Comment by kit-ty-kate** [comment]
I'm closing this issue since it looks like this has been fixed. Thanks for your report! Please feel free to reopen if the issue comes back.
