### ISSUE TITLE
"No agreement on the version of ocaml" while opam file seems fine

### ISSUE THREAD

**Issue by MdeLv** [ocaml/opam#5427]
`opam install` seems to tell  the contrary of what is stated in the opam file. How is it possible?

See example: https://github.com/OCamlPro/ocaml-top/issues/76 where we have ocaml.4.02.0 or newer required and opam says "- ocaml-top → ocaml < 4.02.4":

```
$ cat ocaml-top.opam
depends      "ocaml" {>= "4.02.0"}

```
and

```
$ opam install ocaml-top
[ERROR] Package conflict!
  * No agreement on the version of ocaml:
    - (invariant) → ocaml-base-compiler = 4.14.0 → ocaml = 4.14.0
    - ocaml-top → ocaml < 4.02.4
    >>> You can temporarily relax the switch invariant with `--update-invariant'   <<<
  * No agreement on the version of ocaml-base-compiler:
    - (invariant) → ocaml-base-compiler = 4.14.0
    - ocaml-top → ocaml < 4.02.4 → ocaml-base-compiler < 3.07+1
  * Missing dependency:
    - ocaml-top → ocp-build < 1.99.8-beta
    no matching version
  * Missing dependency:
    - ocaml-top → ocaml < 4.02.4 → ocaml-variants → ocaml-beta
    unmet availability conditions: 'enable-ocaml-beta-repository'

No solution found, exiting

```

**Comment by kit-ty-kate** [comment]
With the opam 2.1.4 i get:
```
[ERROR] Package conflict!
  * No agreement on the version of ocaml:
    - (invariant) -> ocaml-base-compiler = 4.14.1 -> ocaml = 4.14.1
    - ocaml-top >= 1.2.0 -> ocp-pp -> ocaml < 4.11
    You can temporarily relax the switch invariant with `--update-invariant'
  * No agreement on the version of ocaml-base-compiler:
    - (invariant) -> ocaml-base-compiler = 4.14.1
    - ocaml-top >= 1.2.0 -> ocp-pp -> ocaml < 4.11 -> ocaml-base-compiler = 4.07.0
  * Missing dependency:
    - ocaml-top >= 1.2.0 -> ocp-pp -> typerex-build -> ocaml < 4.05.0 -> ocaml-variants >= 4.02.3 ->
      ocaml-beta
    unmet availability conditions: 'enable-ocaml-beta-repository'

No solution found, exiting
```
which, while not being the most concise (see #4373) is at least correct.

**Comment by MdeLv** [comment]
$ opam --version
2.1.4

This kind of opam message is neither concise nor immediately understandable.
How can you explain (4.14.0, my example) `- ocaml-top → ocaml < 4.02.4 → ocaml-base-compiler < 3.07+1` while the opam file says `ocaml-version >= "4.02.0"`?

[ocaml-top.opam (1.1.5)](https://github.com/OCamlPro/ocaml-top/blob/1.1.5/ocaml-top.opam)
```
opam-version: "1.2"
version: "1.1.5"
maintainer: "contact@ocamlpro.com"
tags: [ "org:ocamlpro" "gui" "teaching" "toplevel" ]
authors: "Louis Gesbert <louis.gesbert@ocamlpro.com>"
homepage: "http://www.typerex.org/ocaml-top.html"
dev-repo: "https://github.com/OCamlPro/ocaml-top.git"
bug-reports: "https://github.com/OCamlPro/ocaml-top/issues"
license: "GPL-3"
available: [ ocaml-version >= "4.02.0" ]
build: ["jbuilder" "build" "-p" name]
depends: [
  "jbuilder"
  "ocp-pp"
  "lablgtk" {>= "2.16.0"}
  "conf-gtksourceview" {= "2"}
  "ocp-indent" {>= "1.4.0"}
  "ocp-index" {>= "1.0.0"}
]
```

I feel and think that the opam file is WRONG and MISLEADING.
It claims or at least suggests that "ocaml 4.02.0 or newer is required", which is the main question we ask ourselves when installing a package.

It also means that [packages.opam.org](https://opam.ocaml.org/packages/) (and opam) accepts WRONG and MISLEADING packages regarding ocaml version. At least one, but I have memories of other packages.

What do you think about the following proposition?

**Proposition:** 
Enforce opam files (hence hinder their authors) to mention an explicit range (>= and <=) for ocaml version as prerequisite that guarantees its installability if this range is respected.
Example:
`Dependencies  ocaml >=4.03.0 <=4.07.1`
(yes, ">= and <=" and NOT "> and <" or ">= and <")

PS: where is the specification of opam?

**Comment by rjbou** [comment]
Please keep discussions polite. If you feel that ocaml-top opam file is not correct, please help fixing it by opening a [PR in its own repository](https://github.com/OCamlPro/ocaml-top/compare). If you want to discuss, or better help improve opam repository and its policy, please help in their [repository](https://github.com/ocaml/opam-repository/pulls), there is also several discussions on [ocaml forum](https://discuss.ocaml.org/) concerning opam repository. This bug tracker is only for opam issues, not ecosystem or package issues.

So, on opam itself, when no solution is found, opam tries to rollback to find a reason for no solution to the request. What happened in your case is that you didn't try to install a specific version of ocaml-top, but asked a version to be installed. And one choosen path by opam was ocaml-top version 1.1.2 or 1.1.3 that have the constraint `ocaml <= 4.02.3`. That's why opam prints that error message, and why it doesn't fit ocaml-top.1.1.5 opam file.
If you specify the version, you get another message

```
$ opam install ocaml-top.1.1.5
[ERROR] Package conflict!
  * No agreement on the version of ocaml:
    - (invariant) → ocaml = 4.14.0
    - ocaml-top >= 1.1.5 → ocp-pp → ocaml < 4.11
    You can temporarily relax the switch invariant with `--update-invariant'

No solution found, exiting
```

Opam should take the path of the latest version when it's possible, there is an issue tracking this problem: https://github.com/ocaml/opam/issues/4373/ (reproduced here: https://github.com/ocaml/opam/discussions/5130#discussioncomment-4780087).

Closing this issue as duplicate.

You can find opam files specification in opam [manual](https://opam.ocaml.org/doc/Manual.html#opam).

**Comment by MdeLv** [comment]
1/ We are talking about facts. What is not polite?

2/ It looks like opam, then [packages.opam.org](https://opam.ocaml.org/packages/) can accept WRONG and/or MISLEADING opam files and let packages be published. I don't understand how the CI process can accept that. Do you ?
Should the author be authorized to publish a package that can't be published? (in that case it's a package for education that should be delivered out of the box, if you don't want newcomers to run away from OCaml at first contact...)

3/ I think that it IS an opam issue not to enforce a **clear** ocaml version range, which is the main criterion when installing a package on a current OCaml configuration (system-wide or possibly in a so-called OCaml "switch").
https://opam.ocaml.org/doc/Manual.html#opam has a bunch of specifications but it seems it doesn't address that simple and key requirement (ocaml version range). Isn't it ?

**Comment by rjbou** [comment]
1/ It's possible to talk about facts and be polite, it's completely 2 different things. It's always better to ask to involved people about how project/community works, how it is managed, etc. before openly and [loudly](https://en.wikipedia.org/wiki/All_caps#Association_with_shouting_or_yelling) criticising other people work.

2-3/ As said in previous answer, this is not an opam issue. Maybe there was a misunderstanding. Opam (this repository) is the tool, the package manager. It is the [opam repository](https://github.com/ocaml/opam-repository) who is in charge of managing the opam repository, in which maintainer publish their packages, in which contribution follow guidelines, etc. And opam.ocaml.org is just a website that contains opam manual/documentation, and opam repository package information. These are 3 distinct repositories and projects.
Opam the tool just apply what is in the given opam file, following its [format/specification](https://opam.ocaml.org/doc/Manual.html#opam). It is not even aware that it is an OCaml compiler.

**Comment by MdeLv** [comment]
We are very polite, aren't we?

Do you think that the tool (opam) can let people write a wrong .opam file?

I've already seen incorrect .opam files that make good software become a uselessly bad experience.

Who is responsible for checking that an .opam file of published package is correct regarding a range for dependencies' versions?
