### ISSUE TITLE
`opam` command default action–install package deps?

### ISSUE THREAD

**Issue by yawaramin** [ocaml/opam#5446]
This is a feature request.

Can we make the `opam` command default action be to reliably do the following:

1. Create a local switch if not already present
2. Install all package dependencies (including `with-test` dependencies) listed in the top-level `opam` file

This would make development workflow much more ergonomic. It would greatly lower the barrier to entry of developers working on OCaml projects.

**Comment by dra27** [comment]
There is work in progress (led by Tarides, being prototyped at the moment) to support a unified workflow for OCaml, with a particular focus on a single point of entry. However, the intention with that is to have `dune` (i.e. the build system) as the entry-point, not `opam` (the choice of Dune doesn't preclude other build systems being used for similar ideas). With that, opam repositories remain the source of truth for packages, but the build system is responsible for setting up the build environment (i.e. the "switch") - the user would longer be required to configure _both_ opam and a build system.

Given that `opam` is never going to drive build systems, having `opam` create a default switch in this way still then requires the user to interact with both a package manager and a build system. There's also a pretty big compatibility concern with changing the `opam` command itself.

**Comment by yawaramin** [comment]
OK, understood; so, are there any materials publicly viewable about these plans for dune and if so could you give me a pointer?
