### ISSUE TITLE
Invariant syntax in opam config report doesn't match the expected syntax by --invariant

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#5491]
`opam config report` since #5480 returns the invariant for the current switch:
```
# invariant            ocaml-base-compiler >= 5.0 & ocaml-base-compiler < 5.1
```
However this syntax isn't accepted by other parts of opam dealing with invariants (e.g. `--invariant`)
It should be something like:
```
# invariant            "ocaml-base-compiler" >= "5.0" & "ocaml-base-compiler" < "5.1"
```
instead

**Comment by rjbou** [comment]
It is dsisplayed in a readable way, it is not purpose of `opam config report` to be given as input of other commands.

**Comment by kit-ty-kate** [comment]
I disagree. I think having something consistent is more human readable than having 3 different incompatible syntaxes.
