### ISSUE TITLE
opam depext should accept --best-effort 

### ISSUE THREAD

**Issue by hhugo** [ocaml/opam#5569]
similar to `opam install --best-effort`

**Comment by rjbou** [comment]
opam depext is an independant [plugin](https://github.com/ocaml-opam/opam-depext), that is frozen as external dependencies handling is integrated in opam since 2.1.

**Comment by hhugo** [comment]
Thanks. I guess I got tricked by https://github.com/ocaml/setup-ocaml/issues/639.
