### ISSUE TITLE
Packaging: passing environment variables to build commands

### ISSUE THREAD

**Issue by maroneze** [ocaml/opam#5610]
Is there a way to specify values for environment variables when running commands in the `build` part of an opam package?

For instance, I need to fix a specific `./configure` build for Cygwin compatibility. Manually, I can run `VAR=value ./configure` in a shell and it works, because the shell will interpret `VAR=val`.

But I cannot simply add it to the `build` script (as in, replace `build: ["./configure"]` with `build: ["VAR=value" "./configure"]`), because opam expects the first element to be a command, not a "shell modifier".

 I did find a section in the documentation mentioning [environment updates](https://opam.ocaml.org/doc/Manual.html#Environment-updates) but I'm not sure it applies to my case, and in any case I couldn't get it working.

**Comment by rjbou** [comment]
Did you try with [`build-env:`](https://opam.ocaml.org/doc/Manual.html#opamfield-build-env) field ?

**Comment by maroneze** [comment]
Thanks! I missed that before...

It *almost* works, the only missing part is that I need to change the environment variable *only* on a specific OS (`{os = "windows"}`), and it seems not to be allowed at this point (`File format error in 'build-env' at line 25, column 0: expected env-binding`).

**Comment by rjbou** [comment]
True, it can't take a filter. 
Are you trying to install a package, or is it to propagate/share it ?

**Comment by rjbou** [comment]
I'm afraid there is no way, or at least simple to do that.

**Comment by maroneze** [comment]
I'd like to fix the `why3.1.6.0` package to make it work on Cygwin. Currently its custom `configure` script sets a `INSTALL_DATA` variable to `install -m 644` (on all systems), which removes execute permission from the installed `.cmxs` file, rendering it unusable on Cygwin. I found out that by doing `INSTALL_DATA=install ./configure` it works, but I'd like to avoid touching the configuration on Linux and macOS, so simply adding `build-env` does not seem the safest approach.

I will try contacting them, but preparing a release takes time, so if this "quick patch" could work, it would be nice. Maybe they'll accept the `build-env` on all systems (most .cmxs files already have the `x` bit anyway).

In any case, thanks for the information, it saved me a lot of time!!

**Comment by rjbou** [comment]
There is a hacky way to do it :) but i wouldn't recommend for publication.
Have a virtual package `conf-cygwin-why3` that declares in its config file the variable `conf-install:"install"`. Then, make `why3` depends on `conf-cygwin-why3` conditionally on cygwin and add in its `build-env` the `INSTALL_DATA` definition from `conf-install`:

* conf-cygwin-why3.config
```
opam-version: "2.0"
variables { conf-install:"install" }
```
* why.opam
```
depends: [
...
"conf-cygwin-why3` { os = "cygwin" }
]
build-env: [ INSTALL_DATA="%{conf-cygwin-why3:conf-install}%"]
```
It will result on `INSTALL_DATA` defined at build stage to `install` on cygwin, and defined but empty on all other oses.
