### ISSUE TITLE
`opam lint`: a command line flag to make `opam lint` return 1 on warnings

### ISSUE THREAD

**Issue by Niols** [ocaml/opam#5651]
`opam lint` can report either errors or warnings. Currently, the return code of the command is 1 if there were errors and 0 if there weren't any (including if there were warnings). I would like a command line flag to either make warnings become errors or to make the return code be 1 also on warnings.

I “discovered” this behaviour when I realised that my CI running `opam lint` wasn't catching warnings and that I needed a fancier test involving reading the standard output of `opam lint`.

**Comment by kit-ty-kate** [comment]
I've open a PR to allow marking warnings as errors in https://github.com/ocaml/opam/pull/5652

**Comment by Niols** [comment]
Oh wow, very nice, thank you!

**Comment by Niols** [comment]
Impressive; thank you! :tada:
