### ISSUE TITLE
Cannot compile opam-full-2.2.0-alpha with msys2-64w toolchain

### ISSUE THREAD

**Issue by Chimrod** [ocaml/opam#5660]
Hello,

I can’t compile opam in msys2. The error I got is this one:

```
checking for flexdll sources... no
checking for flexlink... flexlink
checking whether flexlink works... no
configure: error: flexlink does not work
make: *** [Makefile:278: compiler] Error 1
```

flexdll where installed with pacman:

`$ pacman -S mingw-w64-x86_64-flexdll`

and seems to be installed correctly:

```
$ ls ${MSYSTEM_PREFIX}/lib/flexdll
default.manifest  default_amd64.manifest  flexdll.c  flexdll.h  flexdll_initer.c  flexdll_initer_mingw64.o  flexdll_mingw64.o
```

I’ve run the compilation with this command:

```
CPATH=$CPATH:${MSYSTEM_PREFIX}/lib/flexdll make cold
```

Is there an environment to use or a procedure to follow in order to build opam ?

In attachment, you will get the configuration logs from the `bootstrap` directory:

[config.log](https://github.com/ocaml/opam/files/12573922/config.log)

**Comment by Chimrod** [comment]
I’ve updated the command with this one:

`FLEXLINKFLAGS="-I${MSYSTEM_PREFIX}/lib/gcc/x86_64-w64-mingw32/13.1.0 -I${MSYSTEM_PREFIX}/lib" CPATH=$CPATH:${MSYSTEM_PREFIX}/lib/flexdll make cold`

But the compilation still fails a step later:

```
ocamlc -output-complete-exe -w -24 -g -o .duneboot.exe -I boot unix.cma boot/libs.ml boot/duneboot.ml
.\.duneboot.exe
/home/opam-full-2.2.0-alpha/src_ext/dune-local/dune.exe build --profile=release --root .  --promote-install-files -- opam-installer.install opam.install
File "src_ext/dose3/src/common/dune", line 16, characters 0-255:
16 | (rule
17 |  (targets gitVersionInfo.ml)
18 |  ; Ensures the hash update whenever a source file is modified ;
19 |  (deps
20 |   (source_tree %{workspace_root}/.git)
21 |   (:script get-git-info.mlt))
22 |  (action
23 |   (with-stdout-to
24 |    %{targets}
25 |    (run %{ocaml} unix.cma %{script}))))
Cannot load required shared library dllunix.
Reason: dllunix.dll: Le module sp�cifi� est introuvable.
.
make[1]: *** [Makefile:144: build-opam] Error 1
make[1] : on quitte le répertoire « /home/opam-full-2.2.0-alpha »
make: *** [Makefile:285: cold] Error 2
```

**Comment by rjbou** [comment]
Is it the same issue than https://github.com/ocaml/opam/issues/5628#issuecomment-1670078748 ?

**Comment by Chimrod** [comment]
It’s very close. Thanks for pointing the ticket, I did not found it before opening this one. The difference here is that I’m using msys2 instead of cygwin, but it seems we are both following the same path (and encountering the same errors).

I will read the issue and the nexts steps and see if I have differents errors.

**Comment by kit-ty-kate** [comment]
`make cold` alone (no need to add FLEXDLL related environment variables) should be working just fine with `master` instead of the first alpha.
2.2.0~alpha3 will be released soon with those fixes

**Comment by Chimrod** [comment]
Using the git repo, I’ve found another error:

```
…
make[3] : on entre dans le répertoire « /home/opam/bootstrap/ocaml-4.14.1/flexdll »
echo "let version = \"0.43\"" > version.ml
rm -f COMPILER-*
x86_64-w64-mingw32-windres version.rc version_res.o
make[3]: x86_64-w64-mingw32-windres: No such file or directory
```

Do you want me to open another isssue ?

**Comment by kit-ty-kate** [comment]
it looks like this is a known difference with MSYS2 vs Cygwin. https://github.com/msys2/MSYS2-packages/issues/937#issuecomment-599122802 shows a path forward but I'm not an MSYS2 expert so I'm not sure what `Msys-mingw crosscompilers` means.

cc @jonahbeckford in case there is something to highlight

**Comment by kit-ty-kate** [comment]
cc @MisterDA just in case too

**Comment by kit-ty-kate** [comment]
ah actually it looks like this package has it: https://packages.msys2.org/package/mingw-w64-cross-binutils?repo=msys&variant=x86_64

Could you try installing `mingw-w64-cross-binutils` and retrying `make cold` from a fresh state?

**Comment by Chimrod** [comment]
After the insallation of the package and running `PATH=$PATH:/opt/bin/ make cold` all the dependencies are now compiled.

Unfortunately, I still have an error during the opam configuration.

```
env PATH="`pwd`/bootstrap/ocaml/bin:$PATH" CAML_LD_LIBRARY_PATH= ./configure --with-vendored-deps --without-dune --enable-cold-check
```` 

fails with thoses lines:

```
checking for acl/libacl.h... no
checking for library containing acl_get_perm... no
checking for x86_64-w64-mingw32-i686-w64-mingw32-gcc... no
checking for i686-w64-mingw32-gcc... no
configure: error: amd64 C compiler not found - opam-putenv cannot be built
```

[config.log](https://github.com/ocaml/opam/files/12608346/config.log)

I’m looking there is an error in the linking for acl. The [package is installed](https://packages.msys2.org/package/msys2-runtime-devel). I’ll keep you informed.

**Comment by jonahbeckford** [comment]
It sounds like the report in https://github.com/ocaml/opam/issues/4104 . The solution there was https://github.com/ocaml/opam/issues/4104#issuecomment-855791216:
> ... install `mingw64-i686-gcc-core`

**Comment by Chimrod** [comment]
I’m not sure. Looking in the log, the real error is a compilation error. 

```
configure:4992: x86_64-w64-mingw32-gcc -O2 -fno-strict-aliasing -fwrapv -mms-bitfields   -c -g -O2  conftest.c >&5
conftest.c:47:10: fatal error: acl/libacl.h: No such file or directory
   47 | #include <acl/libacl.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
configure:4992: $? = 1
…
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\msys64\tmp\ccmIGvGv.o: in function `main':
D:/msys64/home/opam/conftest.c:27: undefined reference to `acl_get_perm'
```

This is reported as an error with a missing compiler, but this seems misleading. I’m not sure for the real cause, however. If the error lies between cygwin/linux/msys this is something out of my domain.

**Comment by Chimrod** [comment]
Hello,

I’ve got some news. After having installed [mingw-w64-i686-gcc](https://packages.msys2.org/package/mingw-w64-i686-gcc) I got some errors in the compilation in steps which worked before!

I solved it by extracting the binary `x86_64-w64-mingw32-windres.exe` and included it in it’s own path.

The process so far is this one:

```console
$ pacman -S mingw-w64-x86_64-toolchain
$ pacman -S mingw-w64-cross-binutils
$ pacman -S mingw-w64-i686-gcc
$ mkdir /home/bin
$ cp /opt/bin/x86_64-w64-mingw32-windres.exe /home/bin/
$ PATH="$PATH:/home/bin/" make cold 
```

After that, I have an error in the external dependencies:

```
Downloading vendored source dependencies...
 * Downloading sha...
 * Downloading swhid_core...
 * Downloading mccs...
done
Extracting vendored source dependencies in src_ext/... bunzip2.exe: Can't open input file ../jsonm.tbz: No such file or directory.
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
make[1]: *** [Makefile:197: jsonm.stamp] Error 2
done
env PATH="`pwd`/bootstrap/ocaml/bin:$PATH" CAML_LD_LIBRARY_PATH= make
make[1] : on entre dans le répertoire « /home/opam »
/home/opam/src_ext/dune-local/dune.exe build --profile=release --root .  --promote-install-files -- opam-installer.install opam.install
File "src/core/dune", line 6, characters 56-66:
6 |   (libraries   re (re_export ocamlgraph) unix sha jsonm swhid_core uutf
                                                            ^^^^^^^^^^
Error: Library "swhid_core" not found.
-> required by library "opam-core" in _build/default/src/core
-> required by executable opam_installer in src/tools/dune:28
-> required by _build/default/src/tools/opam_installer.exe
-> required by _build/install/default/bin/opam-installer.exe
-> required by _build/default/opam-installer.install
make[1]: *** [Makefile:144: build-opam] Error 1
make[1] : on quitte le répertoire « /home/opam »
make: *** [Makefile:283: cold] Error 2
```

I’m looking for this.
