### ISSUE TITLE
Opam appears to be broken by tezos-benchmark-examples

### ISSUE THREAD

**Issue by jakubrpawlowski** [ocaml/opam#5674]
Tried everything, fresh opam installation, different macbook, fresh repo - no matter what I do for example: `opam update` I get:

Fatal error:
In /private/var/folders/7g/tfwr6mgs1kj9dwsf89jd4kdc0000gn/T/opam-82648-fb1a31/default/packages/tezos-benchmark-examples/tezos-benchmark-examples.10.2/opam:
unsupported or missing file format version; should be 2.0 or older

**Comment by jakubrpawlowski** [comment]
I don't know why, but this morning deleting opam, all files in  /private/var/folders/7g/tfwr6mgs1kj9dwsf89jd4kdc0000gn/T/ begining with opam... and reinstalling it again fixed the issue. Not sure why last night it didn't.

**Comment by kit-ty-kate** [comment]
On macOS you need to install GNU Patch as the default one doesn't handle file deletion (can't distinguish between file deletion and emptying a file)

This should be fixed by https://github.com/ocaml/opam/pull/5400 whenever we get around to making sure it works on all platforms as expected.
