### ISSUE TITLE
Issues creating an offline repository

### ISSUE THREAD

**Issue by josecastillolema** [ocaml/opam#5677]
Hi,

I am working on some [Flatpak](https://flatpak.org/) packaging.
I need to create a simple offline repository with two packages.
Steps:
```
$ mkdir packages
$ cd packages
$ opam source ocp-indent
Successfully extracted to /.../packages/ocp-indent.1.8.1
$ opam opam source ocamlfind
Successfully extracted to /.../packages/ocamlfind.1.9.6
$ cd ..
$ opam admin cache
Adding cache to /.../repo...
Done.
$ tree -L 2 .
.
├── packages
│   ├── ocamlfind.1.9.6
│   └── ocp-indent.1.8.1
└── repo
```
### Issue number 1
Only one packet of the two gets recognized:
```
$ opam admin list
# Packages matching: available
# Name    # Installed # Synopsis
ocamlfind --          A library manager for OCaml
```

In order for the `ocp-indent` package to get recognized you have to rename its opam file:
```
$ mv packages/ocp-indent.1.8.1/ocp-indent.opam packages/ocp-indent.1.8.1/opam
$ opam admin list
# Packages matching: available
# Name     # Installed # Synopsis
ocamlfind  --          A library manager for OCaml
ocp-indent --          A simple tool to indent OCaml programs
```

While I guess this may be expected behavior as I see the file is indeed named `opam` in its [opam-repository repo](https://github.com/ocaml/opam-repository/blob/master/packages/ocp-indent/ocp-indent.1.8.1/opam), is there any way around this?

### Issue number 2
The `ocp-indent` package is not installable:
```
$ opam admin check
Checking installability of every package. This may take a few minutes...
[ERROR] These packages are not installable (1):
        ocp-indent.1.8.1
Summary: out of 2 packages (2 distinct names)
- 1 uninstallable roots
```
Note 1: The package gets correctlly installed with `opam install .` though.
Note 2: Exactly the same behavior if trying with the opam file from its  [opam-repository repo](https://github.com/ocaml/opam-repository/blob/master/packages/ocp-indent/ocp-indent.1.8.1/opam), which is almost identical besides [the absent url field](https://github.com/ocaml/opam-repository/blob/master/packages/ocp-indent/ocp-indent.1.8.1/opam#L51-L57).

**Additional info**
```
$ opam admin lint
In ocamlfind.1.9.6:
  warning  4: Field 'version: "1.9.6.git"' while the directory name or pinning implied "1.9.6"
  warning 41: Some packages are mentioned in package scripts or features, but there is no dependency or depopt toward
              them: "ocaml"
In ocp-indent.1.8.1:
  warning 62: License doesn't adhere to the SPDX standard, see https://spdx.org/licenses/ : "LGPL-2.1-only with
              OCaml-LGPL-linking-exception"

$ opam config report
# opam config report
# opam-version         2.2.0~alpha2
# self-upgrade         no
# system               arch=x86_64 os=linux os-distribution=fedora os-version=38
# solver               builtin-mccs+glpk
# install-criteria     -removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed
# upgrade-criteria     -removed,-count[avoid-version,changed],-count[version-lag,solution],-count[missing-depexts,changed],-new
# jobs                 15
# repositories         1 (http), 3 (local) (default repo at b61304c6)
# pinned               3 (rsync)
# current-switch       5.0.0
# invariant            ocaml-base-compiler = 5.0.0 | ocaml-system = 5.0.0
# compiler-packages    ocaml-base-compiler.5.0.0, ocaml-options-vanilla.1
# ocaml:native         true
# ocaml:native-tools   true
# ocaml:native-dynlink true
# ocaml:stubsdir       /opt/opam/5.0.0/lib/ocaml/stublibs:/opt/opam/5.0.0/lib/ocaml
# ocaml:preinstalled   false
# ocaml:compiler       5.0.0
```

**Comment by kit-ty-kate** [comment]
Similar to my comment in https://github.com/ocaml/opam/issues/5658#issuecomment-1713720454 I don't understand what you are trying to do.

A repository should look like this: https://github.com/ocaml/opam-repository/ and does not contain the source.
If you follow @rjbou's comment on the same ticket you'll be able to create a self contained repository.

The repository should look like this:
```
$ tree
.
├── packages
│   ├── ocamlfind.1.9.6
|             └── opam
│   └── ocp-indent.1.8.1
|              └── opam
└── repo
```
You can then use `opam admin cache ./cache` to create a subdirectory `cache` containing the archives
Then you just need to add `archive-mirrors: "cache"` to the `repo` file and you have your self-contained repository.

**Comment by kit-ty-kate** [comment]
> Similar to my comment in [#5658 (comment)](https://github.com/ocaml/opam/issues/5658#issuecomment-1713720454) I don't understand what you are trying to do.

or rather I understand what you're trying to do but I don't understand where you saw an opam repository that contain the sources like you're trying to do. Are you following a blog post from somewhere?

**Comment by josecastillolema** [comment]
L8 mistake here, apologies.
I have tested the provided procedure and it works properly.

Thanks
