### ISSUE TITLE
Broken use of curl in 2.2.0~alpha3 on native Windows

### ISSUE THREAD

**Issue by jonahbeckford** [ocaml/opam#5681]
### Assets

* `opam.exe`: https://github.com/diskuv/dkml-component-opam/releases/tag/2.2.0-alpha3-20230918 has a tarball that contains MSVC-compiled Windows 64-bit `opam.exe` (and other operating systems but those are easy to build).
* `with-dkml.exe`: Sadly there is not an easy way to get this except to install DkML 2.0.3 from https://gitlab.com/dkml/distributions/dkml/-/releases/2.0.3. But for this issue all that it should be doing is placing MSYS2 into the PATH.

### Problem

Context: `curl` has always been broken as a download method on native Windows. So after `opam init` I always do a `opam option --yes --global download-command=wget` in DkML.

With `opam.2.2.0~alpha0` (commits until 2022-12-28) I could do the following without a problem:

```sh
$ with-dkml opam init --yes --no-setup --bare --disable-sandboxing default https://opam.ocaml.org

# The following command is executed only if repo/default or repo/default.tar.gz was not created
# - It is created in 2.2.0~alpha0 so this won't execute. Some earlier versions of opam didn't though.
$ with-dkml opam repository add default https://opam.ocaml.org --yes --dont-select --rank=3

$ with-dkml opam option --yes --global download-command=wget
```

Now with `opam.2.2.0~alpha3` (commits until 2023-09-18) I have to use `--no-cygwin-setup` (which is fine) but I get an error:

```sh
$ with-dkml opam init --yes --no-setup --bare --disable-sandboxing --no-cygwin-setup
[WARNING] Flag --no-cygwin-setup is experimental, there is no guarantee that it will be kept; avoid using it in scripts.
No configuration file found, using built-in defaults.
Checking for available remotes: rsync and local, git.
  - you won't be able to use mercurial repositories unless you install the hg command on your system.
  - you won't be able to use darcs repositories unless you install the darcs command on your system.


<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><>  🐫
[ERROR] Could not update repository "default": OpamDownload.Download_fail(_, "curl: code %http_coden while downloading https://opam.ocaml.org/index.tar.gz")
[ERROR] Initial download of repository failed.
```

**Comment by jonahbeckford** [comment]
Blocks verification of #5673

**Comment by jonahbeckford** [comment]
### Root cause

The `opam.2.2.0~alpha0` version had debug logs:

```
00:00.218  PARALLEL               Next task in job 0: C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\usr\bin\curl.exe --write-out %{http_code}\n --retry 3 --retry-delay 2 --user-agent opam/2.2.0~alpha0~20221228 -L -o C:\Users\beckf\AppData\Local\Temp\opam-32908-84161f\index.tar.gz.part -- https://opam.ocaml.org/index.tar.gz
00:00.835  PROC                   cygvoke(glob): "C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\usr\bin\curl.exe" "--write-out" "%{http_code}\n" "--retry" "3" "--retry-delay" "2" "--user-agent" "opam/2.2.0~alpha0~20221228" "-L" "-o" "C:\Users\beckf\AppData\Local\Temp\opam-32908-84161f\index.tar.gz.part" "--" "https://opam.ocaml.org/index.tar.gz"
Processing  1/1: [default: http]
00:03.573  PARALLEL               Collected task for job 0 (ret:0)
```

But `opam.2.2.0~alpha3` has:

```
00:00.102  PARALLEL               Next task in job 0: C:\Users\beckf\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\usr\bin\curl.exe --write-out %{http_code}\n --retry 3 --retry-delay 2 --user-agent opam/2.2.0~alpha3~dev -L -o C:\Users\beckf\AppData\Local\Temp\opam-14628-ac7d23\index.tar.gz.part -- https://opam.ocaml.org/index.tar.gz
Processing  1/1: [default: http]
00:02.702  PARALLEL               Collected task for job 0 (ret:0)
...
[ERROR] Could not update repository "default": OpamDownload.Download_fail(_, "curl: code %http_coden while downloading https://opam.ocaml.org/index.tar.gz")
```

---

I guess that is unsurprising since for DkML I have to use `--no-cygwin-setup`, and that is needed for the `cygvoke(glob)`

**Comment by jonahbeckford** [comment]
So ... can we do one of the following (or some or all):

1. Provide a command line option to use `wget` rather than `curl` in `opam init`?
2. Provide a command line option to skip the download of the initial repository in `opam init`?
3. Fix `curl` so that it can reliably pass the newline character on Windows, or remove the need for the newline character?

**Comment by kit-ty-kate** [comment]
I use curl on Windows and the master branch and I haven't seen this issue. Is the MSYS2 version of curl known to be more buggy compared to Cygwin?

Actually re-reading myself as I'm writing makes me think mixing MSYS2 and Cygwin is the problem.
Could you try again with the Cygwin version installed?
I think opam automatically puts cygwin into the PATH first but I'm not entirely sure. @rjbou is this what we are doing?

**Comment by jonahbeckford** [comment]
I am quite fine with `OPAMFETCH=wget` ... it is only for the initial `opam init`.

And it gets past the `curl` issue, so technically this issue can be closed.

However, `opam init` fails at a later point, and I do now think that `--msys2-location=DIR` is unavoidable. I'll open a new issue for that.

**Comment by jonahbeckford** [comment]
Resolved with `OPAMFETCH=wget`. Thanks!
