### ISSUE TITLE
opam init with MSYS2

### ISSUE THREAD

**Issue by jonahbeckford** [ocaml/opam#5683]
I am quite fine with `OPAMFETCH=wget` ... it is only for the initial `opam init`.

And it gets past the `curl` issue, so technically this issue can be closed.

However, `opam init` fails at a later point, and I do now think that `--msys2-location=DIR` is unavoidable. I'll open a new issue for that.

_Originally posted by @jonahbeckford in https://github.com/ocaml/opam/issues/5681#issuecomment-1728073761_

**Comment by jonahbeckford** [comment]
### Proposed Solutions

1. Get back to the old behavior for MSYS2 (using `cygpath` when executing opam subprocesses, etc.). That can't happen unless opam knows about MSYS2:

```
opam init --msys2-location=DIR
```

2. Wrap all opam launched processes with a user-specified command (ex. `with-dkml`), rather than just the `wrap-build-commands/wrap-install-commands/wrap-remove-commands` subset. *I don't think this is a good idea right now ... it will take a lot of soak testing to get right, and will unnecessarily delay opam 2.2*

---

Also, I don't need `--msys2-internal-install` or `--msys2-local-install` because I still need `with-dkml` for DkML users

**Comment by kit-ty-kate** [comment]
Does it work if you use `opam init --cygwin-location=C:\msys64` ?

**Comment by Chimrod** [comment]
When I specify the path to msys (in my case `D:\msys64`), opam look for a subdirectory `\home\msys64` which do not exists:

```
$ opam init  --cygwin-location=D:\msys64
[WARNING] Flag --cygwin-location is experimental, there is no guarantee that it will be kept; avoid using it in
          scripts.
No configuration file found, using built-in defaults.

<><> Unix support infrastructure ><><><><><><><><><><><><><><><><><><><><><>  🐫
[ERROR] Error while checking Cygwin install (C:\cygwin64): D:\msys64\home\msys64 not found!
```

I’ve tried differents way to spectify the path, but I do not understand the hierarchy required…
