### ISSUE TITLE
Opam does not remove some directories during uninstallation

### ISSUE THREAD

**Issue by AllanBlanchard** [ocaml/opam#5688]
In Frama-C we have noticed a surprising change between Opam 2.0 and 2.1 (yes, we notice it only now), on the uninstallation of `META` files and their directories. Currently I have only been able to produce it for Frama-C plug-ins.

With a small Frama-C plug-in like [empty.zip](https://github.com/ocaml/opam/files/12727067/empty.zip) (requires Frama-C installed).

With commands:
```
opam install .
opam uninstall --debug frama-c-empty
```

We can see in the following difference in the uninstallation log:

Opam 2.0.8
```
...  ACTION                 Removing the misc files
...  SYSTEM                 rm (switch)/.opam-switch/install/frama-c-empty.install
...  SYSTEM                 rm (switch)/lib/frama-c/plugins/empty/META
...  SYSTEM                 rmdir (switch)/lib/frama-c/plugins/empty
...  SYSTEM                 rm (switch)/.opam-switch/install/frama-c-empty.changes
```

Opam 2.1.5
```
...  ACTION                 Removing the misc files
...  SYSTEM                 rm (switch)/.opam-switch/install/frama-c-empty.install
...  SYSTEM                 rm (switch)/lib/frama-c/plugins/empty/META
...  SYSTEM                 rm (switch)/.opam-switch/install/frama-c-empty.changes
```

This can cause trouble with `dune-site` when loading plug-ins.

Is it a bug or is it intended (if it is intended, I guess we'll have to fix dune site) ?

**Comment by rjbou** [comment]
I was indeed a bug. It is resolved by linked PR.

**Comment by AllanBlanchard** [comment]
Thanks!
