### ISSUE TITLE
version 2.1.5 conflict of Base64 with base64 / extlib

### ISSUE THREAD

**Issue by Miezhiko** [ocaml/opam#5694]
have error during build:

Error: Files /usr/lib64/ocaml/base64/base64.cma(Base64)
       and /usr/lib64/ocaml/extlib/extLib.cma(Base64)
       both define a module named Base64

**Comment by kit-ty-kate** [comment]
From what i gather from your github profile, it looks like this happens on Gentoo.

Looking at Gentoo’s package definition for `extlib`:

https://github.com/gentoo/gentoo/blob/68e0e2c5e8992ce587a8f89f9636b289a0e21967/dev-ml/extlib/extlib-1.7.9.ebuild#L33C2-L33C15

is non-standard for extlib. It should be `emake minimal=1 -j1 all`. See the README.md from extlib:

https://github.com/ygrek/ocaml-extlib/blob/98380323d26cc1c152d3298c04219013191d6194/README.md?plain=1#L49

or better yet replace it with `dune build -p extlib` as per its opam file definition:

https://github.com/ygrek/ocaml-extlib/blob/98380323d26cc1c152d3298c04219013191d6194/extlib.opam#L40

Opam is only compatible with `extlib` not `extlib-compat` (which is the version without `minimal=1`)

**Comment by Miezhiko** [comment]
yes, adding minimal=1 solves problem, thank you a lot

you've found out what I use, found proble in a package, said how to fix (and even improve ebuild) and explained why
it's truely impressive for me!
