### ISSUE TITLE
`opam config -env` should be evaluated by default

### ISSUE THREAD

**Issue by cagdasbozman** [ocaml/opam#57]
Why `eval 'opam config -env'` is not evaluated by default ? It's kind of annoying to execute this after each opam switch or opam init.

Is it possible to have this done automatically ?

**Comment by shonfeder** [comment]
I'm curious about why

```
eval `opam config env`
```

is necessary. I've never had to run anything like this with any other package manager I've used. While my experience isn't vast, I have used a variety of package managers including `homebrew`, `apt`, `pip`, Haskell's `stack`, and others. `opam` is the only one I've used where I've often had to execute this kind of auxiliary command to refresh my shell's environment. This isn't meant to be a complaint, as I am generally very impressed with `opam`, but I am curious what is different about this package manager that makes such hi-jinx necessary so frequently.

**Comment by AltGr** [comment]
These package managers don't support multiple switches, as far as I know, so just need to change your PATH once (or work in local sandboxes that require `pkg-manager run CMD` to run in the sandbox, which is also possible with `opam exec -- CMD`). Opam normally doesn't require `eval $(opam env)` unless you change the active switch.

One solution is to define `alias opam='/path/to/opam "$@" && eval $(opam env)'`, but we don't want to force such tricks upon the user.

**Comment by Trolldemorted** [comment]
rustup/cargo have a sort of multiple switches, iirc they have a wrapper script which evaluates which environment was selected and set it before invoking rustc.

Is there any sane way to convince opam to play nicely inside docker containers and CI builds, or do I have to prepend every command with eval `opam env &&`?
