### ISSUE TITLE
partially installed compiler

### ISSUE THREAD

**Issue by Azatic** [ocaml/opam#5710]
when I write opam switch create 5.1.0 (for example) and finish the process before completion, I still get 5.1.0 in the available versions of the compiler, although there are many errors when using it
I would like it to be visible when writing opam switch, which compiler is partially installed

**Comment by kit-ty-kate** [comment]
How did you get into this situation in the first place? opam should ask you if you want to clean up the switch and it’s even set to be the case by default:
```
Switch initialisation failed: clean up? ('n' will leave the switch partially
installed) [y/n] y
```
What prompted you to answer `no`, or if no question was asked what command did you launched and which version of opam do you have?

**Comment by Azatic** [comment]
i have opam version 2.1.5, question wasn't asked

**Comment by kit-ty-kate** [comment]
could you show us the output of the command you launched? This way we’ll be able to see when the process was interrupted.

**Comment by Azatic** [comment]
perhaps we misunderstood each other. I am running an opam switchset ... pressed control + c

**Comment by kit-ty-kate** [comment]
I didn’t misunderstood this. I need to be able to see when you pressed Ctrl-C as I’m not able to reproduce your issue and timings are important for this kind of problem.

For example for me, interrupting it halfway leads to this output:
```
$ opam switch create 5.1.0

<><> Installing new switch packages <><><><><><><><><><><><><><><><><><><><>  🐫
Switch invariant: ["ocaml-base-compiler" {= "5.1.0"} | "ocaml-system" {= "5.1.0"}]

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
∗ installed ocaml-options-vanilla.1
⬇ retrieved ocaml-base-compiler.5.1.0  (cached)
[ERROR] User interruption


<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
┌─ The following actions failed
│ λ build ocaml-base-compiler 5.1.0
└─
┌─ The following changes have been performed (the rest was aborted)
│ ∗ install base-bigarray         base
│ ∗ install base-threads          base
│ ∗ install base-unix             base
│ ∗ install ocaml-options-vanilla 1
└─

<><> ocaml-base-compiler.5.1.0 troubleshooting ><><><><><><><><><><><><><><>  🐫
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/opam-repository/issues
=> You can try installing again including --jobs=1
      to force a sequential build instead.
Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [y/n] y
```

**Comment by Azatic** [comment]
everything works fine on 5.1.0, this problem is only with 5.2.0
```sh
opam switch create  5.2.0+trunk 

<><> Installing new switch packages <><><><><><><><><><><><><><><><><><><><>  🐫 
Switch invariant: ["ocaml-variants" {= "5.2.0+trunk"}]
^C
[WARNING] Switch 5.2.0+trunk left partially installed
➜  ~ opam switch list
#  switch       compiler                   description
→  5.1.0        ocaml-base-compiler.5.1.0  5.1.0
   5.2.0+trunk                             5.2.0+trunk
   default      ocaml.4.14.0               default

[WARNING] The environment is not in sync with the current switch.
          You should run: eval $(opam env)
```

**Comment by kit-ty-kate** [comment]
Thank you. I see where the problem is now. I’m not sure how easily fixable this is but we’ll discuss it tomorrow and we’ll get back to you.

In the meantime you can use `opam switch remove` to remove the partially installed switch.
It also looks like you didn’t enable the shell hook during opam init (that automatically changes the current switch) and that exacerbate your current issue. You can enable it now using `opam init --reinit --auto-setup`

Thanks for the report.
