### ISSUE TITLE
opam switch import does not upgrade changed pins

### ISSUE THREAD

**Issue by mmottl** [ocaml/opam#5717]
If I call `opam switch export foo` in a switch that includes pins, then change the pinned git branch of a package in `foo`, and finally call `opam switch import foo`, OPAM will only update the pins, but not propose to upgrade/reinstall the package.

However, calling `opam switch import foo` a second time, or calling `opam upgrade` will trigger OPAM to propose upgrading the changed pin, which suggests that this behavior is a bug.

It seems that this behavior is unique to pins. Changing the version of a regular package in `foo` will make OPAM prompt for upgrades immediately.

**Comment by kit-ty-kate** [comment]
I’m unable to reproduce using opam 2.2.0~alpha2. Which version of opam do you have? Could you confirm it’s fixed when using the latest alpha release:
```
bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh) --dev"
```

My guess is that has been fixed in https://github.com/ocaml/opam/pull/5181

**Comment by mmottl** [comment]
The latest alpha version apparently fixes the problem.
