### ISSUE TITLE
Windows switch create fails with cl compiler

### ISSUE THREAD

**Issue by nobody-famous** [ocaml/opam#5735]
>   If your issue concerns a package not building, please report to
>   https://github.com/ocaml/opam-repository/issues or to the package maintainer
>   unless you are confident it is an issue in the opam tool itself.

```
# opam config report
# opam-version         2.2.0~alpha3 (0d6d867ba135bd69b16b40227f1b2d937e89073d)
# self-upgrade         no
# system               arch=x86_64 os=win32 os-distribution=cygwin os-version=10.0.22621
# solver               builtin-mccs+glpk
# install-criteria     -removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed
# upgrade-criteria     -removed,-count[avoid-version,changed],-count[version-lag,solution],-count[missing-depexts,changed],-new
# jobs                 19
# current-switch       none set
```

When I try to do `opam switch create 5.1.0`, it gives the error,
```
# configure: error: C11 atomic support is required, use another C compiler
```
I'm using the Windows cl compiler,
```
Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32822 for x64
```

**Comment by kit-ty-kate** [comment]
Are you using @dra27's repository? https://github.com/dra27/opam-repository/tree/windows-5.0/packages/ocaml-variants/ocaml-variants.5.1.0%2Boptions. If so it might be worth to contact him to report the issue. https://github.com/ocaml/opam-repository/issues is probably the most central place to put this kind of issue. You can cc him on it if you do.

**Comment by nobody-famous** [comment]
OK, I'll go ahead and close this. I'm mainly interested in the effects stuff, so wanted 5.x. Just found out the VSCode extension is unusable on windows, anyway (after formatting it complains about \r characters everywhere), so I'll try again in a year or so.
