### ISSUE TITLE
`opam pin add` should display more information on package conflicts

### ISSUE THREAD

**Issue by JasonGross** [ocaml/opam#5740]
See https://github.com/JasonGross/test/actions/runs/6976238997/job/18984411851
I see
```
00:12.845  CUDF                   resolve request=install:(js%5fof%5focaml & js%5fof%5focaml-compiler & js%5fof%5focaml-lwt & js%5fof%5focaml-ppx & js%5fof%5focaml-ppx%5fderiving%5fjson & js%5fof%5focaml-toplevel & js%5fof%5focaml-tyxml & wasm%5fof%5focaml-compiler) remove:() upgrade:()
00:15.125  CLIENT                 conflict!
[ERROR] Package conflict!
00:15.125  CUDF                   Conflict reporting
  * Missing dependency:
    - js_of_ocaml < 1.2
    no matching version
[NOTE] Pinning command successful, but your installed packages may be out of sync.
```
but as far as I can tell, nothing is requesting `js_of_ocaml < 1.2`.  The command was `opam pin add -y --debug-level=3 https://github.com/ocaml-wasm/wasm_of_ocaml.git`.  There should be more information about what is generating the version constraint.

(Also, is there a way to get this information currently?)

**Comment by rjbou** [comment]
As it is an conflict message issue, closing in favor to meta discussion #5130.
Thanks for the report!
