### ISSUE TITLE
usability suggestion: fail if opam cannot build a built-in solver, unless explicitly requested

### ISSUE THREAD

**Issue by maroneze** [ocaml/opam#5749]
I feel there's a usability issue with the way opam is currently built: if opam cannot build its built-in solver mccs (e.g., if the user has no C++ compiler available), there is a message in the build process that says so ("opam will be compiled WITHOUT a built-in solver"), but otherwise, there is no indication that this happened.

This is especially problematic in the case of `opam-bundle`: its first script, `bootstrap.sh`, will run and terminate successfully (since opam was indeed installed), but the user will have no explicit message about the lack of a built-in solver. Then, the user will run `./configure.sh`, which will fail due to lack of any available solvers, and the user will be puzzled.

Since option `--without-mccs` exists, I believe it should be clearly specified by the user to allow the build to continue, if mccs cannot be built. This serves to confirm the user's intent that "yes, I want you to build regardless". Otherwise, the build should fail with "cannot compile a built-in solver; please ensure that your system can build mccs, or try to build opam with option `--without-mccs`".

This is just a suggestion, feel free to close this issue if you have already considered this. It's mostly because every 6 months, when I try to re-use opam-bundle on a new Docker image, I end up forgetting to add `g++` to the list of dependencies, and I end up thinking that opam-bundle is somehow broken...

**Comment by rjbou** [comment]
Which opam version are you using ?

**Comment by rjbou** [comment]
If it is <2.2, can you test with opam 2.2.0~alpha at least, it contains PR #5527, that may fix your issue.

**Comment by maroneze** [comment]
Indeed it works perfectly! Sorry about the noise.
