### ISSUE TITLE
Dune can't compile on a ocaml-variants.4.14.1+msvc64c variant

### ISSUE THREAD

**Issue by F-Loyer** [ocaml/opam#5806]
Dune can't compile on a ocaml-variants.4.14.1+msvc64c switch.

```
# ocamlc -output-complete-exe -w -24 -g -o .duneboot.exe -I boot unix.cma boot/libs.ml boot/duneboot.ml
# link: missing operand
# Try 'link --help' for more information.
# link: extra operand « /libpath:C:/Users/frede/AppData/Local/opam/4.14.1+msvc64c/lib/ocaml »
# Try 'link --help' for more information.
# ** Fatal error: Error during linking
```

In fact, any program can't be compiled by `ocamlc -output-complete-exe` which trigger a wrong MSVC `link` command. `ocamlc` without `-output-complete-exe` is ok. 

I am using Microsoft Studio Community 2022.

**Comment by kit-ty-kate** [comment]
I’m not sure what opam (the tool) can do here. Could you open a ticket on dune or/and the compiler (4.14 is still maintained as it is an LTS) instead?

**Comment by F-Loyer** [comment]
Ok, a new ticket is opened. https://github.com/ocaml/ocaml/issues/12944

**Comment by kit-ty-kate** [comment]
Looking at the answer there, could you show what the output of `opam env --switch=4.14.1+msvc64c` is?

**Comment by F-Loyer** [comment]
The issue can be closed.

It deals with a conflict between the linker `link` from MSVC and the Cygwin `link`command. One just have to make sure the acurate PATH is used when using MSVC.

**Comment by kit-ty-kate** [comment]
Sorry for the lack of update, just to note that this should be fixed by https://github.com/ocaml/opam/pull/5832 slotted for the next beta
