### ISSUE TITLE
Initial pin of VCS directory includes untracked and ignored files [2.1 regression]

### ISSUE THREAD

**Issue by dra27** [ocaml/opam#5809]
```Dockerfile
FROM ocaml/opam:debian-12-opam
RUN git clone https://github.com/ocaml/stdlib-shims.git
RUN sudo ln -f /usr/bin/opam-2.2 /usr/bin/opam
RUN rm -rf ~/.opam && opam init --bare -a ~/opam-repository
RUN touch stdlib-shims/stdlib-shims.install stdlib-shims/untracked
RUN opam switch create --empty stdlib-shims
RUN opam pin add stdlib-shims git+file:///home/opam/stdlib-shims -yn
RUN ls -a /home/opam/.opam/stdlib-shims/.opam-switch/sources/stdlib-shims > before
RUN opam update stdlib-shims
RUN ls -a /home/opam/.opam/stdlib-shims/.opam-switch/sources/stdlib-shims > after
RUN grep '\.git\|untracked\|install' before
RUN diff -u before after
```

Since opam 2.1, the initial copy of the pin directory incorrectly:
- Has _no_ `.git` folder
- Has copies of `stdlib.shims.install` (which is in `.gitignore`) and `untracked` (which should be an untracked file)

Replacing the `opam-2.2` with `opam-2.1` tests 2.1 and and removing that and the following line completely tests 2.0.

The first `opam update` of the VCS sources causes the `.git` directory to be added and the untracked/ignored files to be removed.

**Comment by kit-ty-kate** [comment]
I've just hit the same bug when pinning opam itself locally with my local directory containing vendored dependencies in `src_ext`

**Comment by kit-ty-kate** [comment]
it's actually a big issue for local projects that have git submodules that have been pulled as this issue makes them fail completely. However anecdotally (i need to test a bit more), that setup seem to have worked with opam 2.1 but not 2.2
