### ISSUE TITLE
Full data for "most used" packages

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/opam#5813]
At https://ocaml.org/packages there is a column marked "most used" which shows how many packages use each of the top 5 opam packages.

Is the full data available anywhere? Obviously I could derive it, but if someone happens to have it to hand it would save some time.

**Comment by kit-ty-kate** [comment]
We (the opam dev team) do not know how the ocaml.org website works. Could you reopen the ticket at https://github.com/ocaml/ocaml.org/issues instead? I would transfer it but i don't have the necessary rights on the ocaml.org repository for that.

In the future, if you have questions about opam.ocaml.org however, the issue tracker for that is at https://github.com/ocaml-opam/opam2web/issues
