### ISSUE TITLE
Dead link to SPDX license expressions

### ISSUE THREAD

**Issue by dhil** [ocaml/opam#5846]
The SPDX link (https://spdx.github.io/spdx-spec/SPDX-license-expressions/) mentioned in the item https://opam.ocaml.org/doc/Manual.html#opamfield-license is dead. I believe, it ought to link to https://spdx.github.io/spdx-spec/v2.3/SPDX-license-list/ now.

**Comment by dbuenzli** [comment]
> https://spdx.github.io/spdx-spec/v2.3/SPDX-license-list/ now.

The version number here is higher https://spdx.org/licenses/

**Comment by kit-ty-kate** [comment]
the equivalent link should be https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/ instead. The list of licenses is something else (list of available licenses vs. spec of the license expression)

**Comment by kit-ty-kate** [comment]
https://github.com/ocaml/opam/pull/5849 should fix that
