### ISSUE TITLE
conf-bash not detecting installed bash on OpenBSD

### ISSUE THREAD

**Issue by jideelgh** [ocaml/opam#5887]
(OpenBSD 7.4, ksh)
conf-bash keeps asking to install bash every time "opam upgrade" is launched, while it's already installed.

I tried to let opam to install bash or to install it manually.
Bash is installed in /usr/local/bin/bash, I tried to symlink to /bin/bash, no success.
`bash --version` returns
```
GNU bash, version 5.2.15(1)-release (x86_64-unknown-openbsd7.4)
Copyright (C) 2022 Free Software Foundation, Inc.
[...]
```
I used ktrace to investigate some pledge/unveil issue, couldn't identify one.
I also tried to start opam w/ the `--debug` flag & adjusting the level with `--debug-level` flags, no obvious error message (except maybe "ocamlc not found", quite weird as  ocamlc is well installed and reachable, may not be related).
(behavior identified because JaneStreet Base 0.16.0 added conf-bash as a dependency)

**Comment by kit-ty-kate** [comment]
I've transferred this issue to opam, where the issue most likely is.

**Comment by jideelgh** [comment]
@mseri opam 2.1.5

**Comment by kit-ty-kate** [comment]
@jideelgh what does `pkg_info -mqP | grep bash` give you?

**Comment by rjbou** [comment]
What are the output of `opam var os-family` and `pkg_info -mqP | grep bash` ?

**Comment by jideelgh** [comment]
@rjbou `bsd`

**Comment by jideelgh** [comment]
@kit-ty-kate `shells/bash`

**Comment by kit-ty-kate** [comment]
ah it looks like it's my fault, i did an off-by-one error in https://github.com/ocaml/opam/pull/4396/files#diff-6c0a6590c49c5a229f469d627b9e9484f1b20c1fb5fb1c8102d64a3d2c1d09b6R187 ..

sorry about that

**Comment by kit-ty-kate** [comment]
Actually it's already fixed in https://github.com/ocaml/opam/commit/4b060e73684135c107fe44f829cc5206916fbe7c by @mndrix 

You can fix this by using the latest beta:
```
bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh) --dev"
```

**Comment by rjbou** [comment]
Should we backport the fix in 2.1.6 ?

**Comment by mseri** [comment]
Good idea, it seems a small enough fix on a possibly common future error to warrant a backport

**Comment by kit-ty-kate** [comment]
Fair enough, I've backported the commit to https://github.com/ocaml/opam/pull/5870. We expect to release it a couple weeks after the next 2.2.0 beta.

I'll close this as it is fixed in master

**Comment by jideelgh** [comment]
Glad I could help. That was fast :) Thank you all.
