### ISSUE TITLE
Invalid Ubuntu repository

### ISSUE THREAD

**Issue by vzaliva** [ocaml/opam#5987]
I am following Ubuntu installation instructions from https://opam.ocaml.org/doc/Install.html

`sudo add-apt-repository ppa:avsm/ppa` gives the following errors:

```
Ign:17 https://ppa.launchpadcontent.net/avsm/ppa/ubuntu mantic InRelease
Err:18 https://ppa.launchpadcontent.net/avsm/ppa/ubuntu mantic Release
  404  Not Found [IP: 2620:2d:4000:1::81 443]
...
E: The repository 'https://ppa.launchpadcontent.net/avsm/ppa/ubuntu mantic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

**Comment by vzaliva** [comment]
Please note that Ubuntu-supplied OPAM version triggers warnings on `opam update`:

```
default (at https://opam.ocaml.org):
    [WARNING] opam is out-of-date. Please consider updating it
    (https://opam.ocaml.org/doc/Install.html)
```

So, removing PPA from documentation will leave Ubuntu users unable to install the recent Opam version via the package manager.

**Comment by kit-ty-kate** [comment]
The binary distribution section offers a way to always install the most up-to-date version of opam: https://opam.ocaml.org/doc/Install.html#Binary-distribution

If your distribution is out-of-date it would also be advised to ping your maintainers so they can remedy this (cc @mehdid)

**Comment by vzaliva** [comment]
I've emailed the maintainer and awaiting his response.
