### ISSUE TITLE
lock hold/release messages as part of another command should be printed on stderr

### ISSUE THREAD

**Issue by Khady** [ocaml/opam#5990]
information messages such as "Another process has locked" and "lock acquired" should be printed on stderr, not stdout, as they aren't really part of the output of a command.

An example where we caught the problem
```
opam switch set-invariant --packages=ahrefs-setup,ahrefs-dev-tools-deps,ocaml-base-compiler.$(opam show ocaml-base-compiler --field=installed-version),ahrefs-all-deps
```

Can end up being executed as
```
opam switch set-invariant --packages=ahrefs-setup,ahrefs-dev-tools-deps,ocaml-base-compiler.Another process has locked /home/user/monorepo/.opam/repo/state-11ABC690.cache, waiting (C-c to abort)... lock acquired. 4.14.0,ahrefs-all-deps
```

This is true for lock messages but probably also applied to other informational messages.

**Comment by kit-ty-kate** [comment]
Will be fixed by https://github.com/ocaml/opam/pull/5999

**Comment by kit-ty-kate** [comment]
In the meantime, i believe that if you add `--readonly` to your `opam show` invocation it should now work fine without waiting for the lock.

**Comment by rr0gi** [comment]
are there cases when opam show is not readonly?

**Comment by kit-ty-kate** [comment]
Yes, for example, if the internal repository data cache (marshalled data) isn't up-to-date or has been removed, opam will try to save that file by default
