### ISSUE TITLE
opam init fails: https://opam.ocaml.org/index.tar.gz\ not found

### ISSUE THREAD

**Issue by edumirosi** [ocaml/opam#6075]
>   If your issue concerns a package not building, please report to
>   https://github.com/ocaml/opam-repository/issues or to the package maintainer
>   unless you are confident it is an issue in the opam tool itself.
>   If your issue concerns failures with the opam.ocaml.org website, please report to
>   https://github.com/ocaml/infrastructure/issues

```
opam config report
# opam config report
# opam-version         2.1.2
# self-upgrade         no
# system               arch=x86_64 os=linux os-distribution=ubuntu os-version=22.04
[ERROR] Opam has not been initialised, please run `opam init'
# read-state           OpamStd.OpamSys.Exit(50)

opam init -vv
No configuration file found, using built-in defaults.
Checking for available remotes: rsync and local, git, mercurial, darcs. Perfect!
+ /home/treers/.opam/opam-init/hooks/sandbox.sh "build" "sh" "-c" "echo SUCCESS >$TMPDIR/opam-sandbox-check-out && cat $TMPDIR/opam-sandbox-check-out; rm -f $TMPDIR/opam-sandbox-check-out"
- SUCCESS

<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>
+ /usr/bin/curl "--write-out" "%{http_code}\\n" "--retry" "3" "--retry-delay" "2" "--user-agent" "opam/2.1.2" "-L" "-o" "/tmp/opam-45229-1683ea/index.tar.gz.part" "--" "https://opam.ocaml.org/index.tar.gz"
-   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
-                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
- curl: (60) SSL certificate problem: self-signed certificate in certificate chain
- More details here: https://curl.se/docs/sslcerts.html
-
- curl failed to verify the legitimacy of the server and therefore could not
- establish a secure connection to it. To learn more about this situation and
- how to fix it, please visit the web page mentioned above.
- 000
[ERROR] Could not update repository "default": OpamDownload.Download_fail(_, "Curl failed: \"/usr/bin/curl --write-out
        %{http_code}\\\\n --retry 3 --retry-delay 2 --user-agent opam/2.1.2 -L -o /tmp/opam-45229-1683ea/index.tar.gz.part --
        https://opam.ocaml.org/index.tar.gz\" exited with code 60")
[ERROR] Initial download of repository failed.
'opam init -vv' failed.
```

Following the instructions at https://frama-c.com/html/get-frama-c.html when I run the following line of code in my ubuntu 22.04:

```
opam init --disable-sandboxing --shell-setup

I get the following error in the terminal:

<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>
[ERROR] Could not update repository "default": OpamDownload.Download_fail(_, "Curl failed: \"/usr/bin/curl --write-out
        %{http_code}\\\\n --retry 3 --retry-delay 2 --user-agent opam/2.1.2 -L -o /tmp/opam-41235-b13419/index.tar.gz.part -- https://opam.ocaml.org/index.tar.gz\" exited with code 60")
[ERROR] Initial download of repository failed.
```

As I already searched for a solution, it seems the certificate https://opam.ocaml.org/index.tar.gz\ has expired, just like in #4187. I already checked for disk space, and I have over 700 Gbs free.

How can I solve this?

**Comment by edumirosi** [comment]
I did that and I still get the same error.  I also tried running:

`Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 2 not upgraded.
Need to get 0 B/155 kB of archives.
After this operation, 0 B of additional disk space will be used.
Preconfiguring packages ...
(Reading database ... 39523 files and directories currently installed.)
Preparing to unpack .../ca-certificates_20230311ubuntu0.22.04.1_all.deb ...
Unpacking ca-certificates (20230311ubuntu0.22.04.1) over (20230311ubuntu0.22.04.1) ...
Setting up ca-certificates (20230311ubuntu0.22.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for ca-certificates (20230311ubuntu0.22.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.`

, and still got the same error. When I run this line of code i get the following prints on the terminal:

**Comment by mtelvers** [comment]
> curl: (60) SSL certificate problem: self-signed certificate in certificate chain

Are you connecting through a proxy server?

Please can you review/post the output from `openssl s_client -connect opam.ocaml.org:443 -showcerts`

**Comment by mtelvers** [comment]
```
Server certificate
subject=CN = opam.ocaml.org
issuer=C = ES, ST = ES, L =BLAH, O = BLAH, OU = key, CN = blah.com, emailAddress = blah@blah.com
```

As you redacted these elements, I guess they contain details of your local organisation.  In this case, I suspect a transparent proxy, rather than an explicit one, at the network level, which is decoding and resigning your HTTPS traffic.

May I also enquire which OS you are using?  You mention `cmd` and `WinHTTP` which makes me think you are running on Windows, but the initial report appear to be Ubuntu 22.04.  Are you running in a Linux VM under Windows or WSL or something else?

**Comment by edumirosi** [comment]
My code is similar to this, however it appears with this kind of errors: 

`Verify return code: 19 (self-signed certificate in certificate chain)`

for the email with depth = 2.

Regarding the OS, I'm using Ubuntu 22.04 in Windows as a WSL. I used WinHHTP to check for the proxy server but doing the same for ubuntu with `echo "$https_proxy"` still prints an empty string. This way I also tend to believe there is not an explicit proxy being used




> The expected output is
> 
> ```
> $ openssl s_client -connect opam.ocaml.org:443 -showcerts
> CONNECTED(00000003)
> depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
> verify return:1
> depth=1 C = US, O = Let's Encrypt, CN = R3
> verify return:1
> depth=0 CN = opam.ocaml.org
> verify return:1
> ---
> Certificate chain
>  0 s:CN = opam.ocaml.org
>    i:C = US, O = Let's Encrypt, CN = R3
>    a:PKEY: id-ecPublicKey, 256 (bit); sigalg: RSA-SHA256
>    v:NotBefore: Apr 25 05:27:31 2024 GMT; NotAfter: Jul 24 05:27:30 2024 GMT
> -----BEGIN CERTIFICATE-----
> MIIEHzCCAwegAwIBAgISA14h9cLAAyEx+AWucUBkK2kOMA0GCSqGSIb3DQEBCwUA
> MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
> EwJSMzAeFw0yNDA0MjUwNTI3MzFaFw0yNDA3MjQwNTI3MzBaMBkxFzAVBgNVBAMT
> Dm9wYW0ub2NhbWwub3JnMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE/hIXqW8v
> UcXkPgur01MpPgtmwElc7zrg4DhNYWokng0njU2Mb3BzKImjU9V/7dVN7D5CiD5f
> Ahe3oeOfdcJcYKOCAhEwggINMA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAUBggr
> BgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU7f0X7/8D
> ztm8BEGkedAUFjdDuGEwHwYDVR0jBBgwFoAUFC6zF7dYVsuuUAlA5h+vnYsUwsYw
> VQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVodHRwOi8vcjMuby5sZW5jci5v
> cmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9yMy5pLmxlbmNyLm9yZy8wGQYDVR0RBBIw
> EIIOb3BhbS5vY2FtbC5vcmcwEwYDVR0gBAwwCjAIBgZngQwBAgEwggEFBgorBgEE
> AdZ5AgQCBIH2BIHzAPEAdwBIsONr2qZHNA/lagL6nTDrHFIBy1bdLIHZu7+rOdiE
> cwAAAY8T8BNdAAAEAwBIMEYCIQC7jp9Ma04qJh5xOA8FNLDWjW3mEbkgb1Vow6X0
> nSscKwIhALZ9yZK6yOWRNdMx9UrEKiUc588cw70TqbD6kHnNcCGeAHYA7s3QZNXb
> Gs7FXLedtM0TojKHRny87N7DUUhZRnEftZsAAAGPE/ATYQAABAMARzBFAiAg2hUU
> uUp2u5+4zgYDuz/qIQdul47NSFfVZLqRPS1P7wIhANaYcrqOd7xLDIJSxQ4/5iCO
> wCt1O9A9PjWQ1lvk3GGWMA0GCSqGSIb3DQEBCwUAA4IBAQAnMWs8AvWgyb0vImaS
> +BVgR+PNeGhiDIFdeWMgcxMwbvc+JF4uJOXYmfa3AIJ+Ik1B6A7Gpc/UPxxdLpkV
> ecBMwRltrhiuV4X1ULwTwqDJCoruHzCqj8YGbA6pIZnhynmdfWuJTi2KNTuzR6zk
> 9hKm0+WekfQApxyKi3GWOL1I16LSq5KeUw6qjdJPVDbLbITGIzHv8zv0u6aojXby
> eO004wJjb+262ZtEUnB49oNgJ1/UeOYCaz2wP8909Zt7stkGG6gZcgUGDRj4jjSa
> 7DkO1U131/CnkLvqjxjCNe3s4g1pR5sv6f6ovGY5PB/1l3IWH/yjqCv/9/SHV9rF
> sK44
> -----END CERTIFICATE-----
>  1 s:C = US, O = Let's Encrypt, CN = R3
>    i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
>    a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
>    v:NotBefore: Sep  4 00:00:00 2020 GMT; NotAfter: Sep 15 16:00:00 2025 GMT
> -----BEGIN CERTIFICATE-----
> MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
> TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
> cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
> WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
> RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
> AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
> R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
> sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
> NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
> Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
> /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
> AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
> Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
> FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
> AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
> Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
> gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
> PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
> ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
> CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
> lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
> avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
> yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
> yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
> hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
> HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
> MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
> nLRbwHOoq7hHwg==
> -----END CERTIFICATE-----
> ---
> Server certificate
> subject=CN = opam.ocaml.org
> issuer=C = US, O = Let's Encrypt, CN = R3
> ---
> No client certificate CA names sent
> Peer signing digest: SHA256
> Peer signature type: ECDSA
> Server Temp Key: X25519, 253 bits
> ---
> SSL handshake has read 2744 bytes and written 396 bytes
> Verification: OK
> ---
> New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
> Server public key is 256 bit
> Secure Renegotiation IS NOT supported
> Compression: NONE
> Expansion: NONE
> No ALPN negotiated
> Early data was not sent
> Verify return code: 0 (ok)
> ---
> ```

**Comment by edumirosi** [comment]
This is my output:

```
CONNECTED(00000003)
depth=2 emailAddress = blah@blah.com, CN = blah.com, O = blah, L = London, ST = London, C = GB
verify error:num=19:self-signed certificate in certificate chain
verify return:1
depth=2 emailAddress = blah@blah.com, CN = blah.com, O = blah, L = London, ST = London, C = GB
verify return:1
depth=1 C = ES, ST = ES, L = blah, O = blah, OU = blah, CN = blah.com, emailAddress = blah@blah.com
verify return:1
depth=0 CN = opam.ocaml.org
verify return:1
---
Certificate chain
 0 s:CN = opam.ocaml.org
   i:C = ES, ST = ES, L = blah, O = GMV, OU = blah, CN = blah.com, emailAddress = blah@blah.com
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jun  8 09:52:35 2024 GMT; NotAfter: Jul  8 09:52:35 2025 GMT
-----BEGIN CERTIFICATE-----
...5UD/e6F0zf/DPSLZfjO+HzVPmfVf1
-----END CERTIFICATE-----
 1 s:C = ES, ST = ES, L = blah, O = blah, OU = blah, CN = blah.com, emailAddress = blah@blah.com
   i:emailAddress = blah@blah.com, CN = blah.com, O = blah, L = London, ST = London, C = GB
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Apr  6 19:45:09 2024 GMT; NotAfter: Apr  4 19:45:09 2034 GMT
-----BEGIN CERTIFICATE-----
...+eDJjiyAmtruxj
-----END CERTIFICATE-----
 2 s:emailAddress = blah@blah.com, CN = blah.com, O = blah, L = London, ST = London, C = GB
   i:emailAddress = blah@blah.com, CN = blah.com, O = blah, L = London, ST = London, C = GB
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jan  9 01:37:45 2024 GMT; NotAfter: Jan  6 01:37:45 2034 GMT
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
---
Server certificate
subject=CN = opam.ocaml.org
issuer=C = ES, ST = ES, L = blah, O = blah, OU = blah, CN = blah.com, emailAddress = blah@blah.com
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3656 bytes and written 396 bytes
Verification error: self-signed certificate in certificate chain
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 19 (self-signed certificate in certificate chain)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: C4DFDB69379...
    Session-ID-ctx:
    Resumption PSK: C847D1547EE1356490E...
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
...

    Start Time: 1720448089
    Timeout   : 7200 (sec)
    Verify return code: 19 (self-signed certificate in certificate chain)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: BFD27...6
    Session-ID-ctx:
    Resumption PSK: 1759510D292858FEF9...FB236CB79164522B04E493818
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
  ...
    Start Time: 1720448089
    Timeout   : 7200 (sec)
    Verify return code: 19 (self-signed certificate in certificate chain)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
read:errno=104
```

**Comment by edumirosi** [comment]
To further add, I noticed one of the emails uses comes from an entity in NetSkope, which is cloud data protector

**Comment by mtelvers** [comment]
> My code is similar to this, however it appears with this kind of errors:
> `Verify return code: 19 (self-signed certificate in certificate chain)`

The certificate on opam.ocaml.org is not self-signed.  It is signed by Let's Encrypt.

> To further add, I noticed one of the emails uses comes from an entity in NetSkope, which is cloud data protector

Yes, your connection seems to be being intercepted.  They are probably decoding your HTTPS traffic to scan for viruses/malware and then issuing new certificates back to you.  I have setup systems like this within corporate networks before.

Assuming you trust these organisations, and their interception of your traffic isn't a surprise to you, you can add their certificate(s) into your certificate store.  Typically, this is done by adding the certificate in PEM format to `/usr/local/share/ca-certificates` and then running `update-ca-certificates`.

**Comment by edumirosi** [comment]
How can I know where the certificates are?

**Comment by mtelvers** [comment]
You can see the content from the `openssl` command that you ran.  You need to use your output to get the certificates you are being presented with (which aren't the ones installed on the server).

Save this into a file `foo.crt`.

```
-----BEGIN CERTIFICATE-----
...+eDJjiyAmtruxj
-----END CERTIFICATE-----
```

The certificate can be converted into PEM format by piping it through `openssl x509 -outform PEM`.  Save the certificate as `foo.pem` into `/usr/local/share/ca-certificates` and then running `update-ca-certificates`.

**Comment by edumirosi** [comment]
Discovered the problem! While connected to the company's WIFI, there was an underlying proxy server running. Now connected to another network the installation of opam worked fine! Thanks for the help!
