### ISSUE TITLE
"opam help" prints UTF-8 characters even when LANG doesn't support them

### ISSUE THREAD

**Issue by pmetzger** [ocaml/opam#6076]
>   If your issue concerns a package not building, please report to
>   https://github.com/ocaml/opam-repository/issues or to the package maintainer
>   unless you are confident it is an issue in the opam tool itself.
>   If your issue concerns failures with the opam.ocaml.org website, please report to
>   https://github.com/ocaml/infrastructure/issues

Under opam 2.2.0, `opam help` does not seem to respect the locale. things like this even if `LANG=C`:

<img width="573" alt="image" src="https://github.com/ocaml/opam/assets/1907413/e43ed25f-be8c-42ce-b207-4ee77afea2d0">

(Note that the particular characters being printed out here seem to be a horizontal ellipsis character, which isn't really important enough to reach for Unicode in all cases.)

**Comment by kit-ty-kate** [comment]
`--help` is generated by cmdliner so that would be an issue there. Could you open a ticket in https://github.com/dbuenzli/cmdliner/issues/ instead?

**Comment by pmetzger** [comment]
Even if I open it there, it's still an issue here because it impacts the opam help command even if you can't fix it here. It should remain open here until it gets fixed there. If that makes any sense?

**Comment by kit-ty-kate** [comment]
of course. I wasn't going to close it. We would still need to vendor the fix release of cmdliner to fix this issue on our end anyway.

**Comment by pmetzger** [comment]
See: https://github.com/dbuenzli/cmdliner/issues/189 — not the best bug report I've ever produced because I don't actually understand how opam is using cmdliner so I'm not doing a great job of supplying the detail he'll likely want.

**Comment by pmetzger** [comment]
Daniel Bünzli is displaying his characteristic friendly and accommodating manner in discussing this. I'm expecting there will be no resolution.

**Comment by kit-ty-kate** [comment]
I think the passive-aggressive tone was unwarranted, please avoid this in the future.

Now that's said, regarding what you said in https://github.com/dbuenzli/cmdliner/issues/189#issuecomment-2217834522 about your meta-key not working. Does it not work if you set `LANG=C.UTF-8` instead? After some local testing i found out that the `C.` prefix was relevant on my system so i'm wondering if it can fix yours.

If it doesn't, then setting `LESSCHARSET=UTF-8` should fix your issue if you're using `less`. If you're using `most` however you need to change your pager to be `env LANG=C.UTF-8 most` instead

**Comment by pmetzger** [comment]
The problem is that if you're using UTF-8, high bits get set regardless, so it's basically impossible to use current command line meta bits in such contexts. Long term there needs to be a better solution, perhaps a standard protocol for ANSI terminals to convey the information more cleanly, but of course, none of this addresses the problem of (say) a Japanese person who just doesn't want to deal with Unicode's Han Unification and would prefer not to get mojibake in his manual pages. Like it or not, sometimes other character sets are going to be in use on people's terminals.

However, on the other topic:

I didn't mean to have a passive aggressive tone. It was meant to be direct. Perhaps I should have been even more direct about how I put it, but being more direct would have been culturally inappropriate around my part of the world.

But as long as we're being completely (and unpleasantly) direct rather than "passive aggressive":

Daniel has driven people away from OCaml in the past, and the price of using his code is that more people will be driven away in the future. His code is of course very, very good, and so it's tempting to incorporate it into one's projects, but then one has to deal with Daniel, and Daniel is never pleasant to deal with. Eventually someone has to communicate with him, he's almost always condescending and insulting, and then, more often than one would like, the object of Daniel's scorn decides that it's not worth being around.

I will admit that the moment you told me to give him a bug report, my heart sank, and I nearly decided not to bother, because I expected such an outcome was likely. It doesn't matter if he's correct about technical points or wrong about them, he's almost always demeaning and unpleasant to other people even though it would be straightforward to be nice even when refusing a request.

Individuals who do not know how to be pleasant to other people eventually appear in most software ecosystems; successful projects usually decide that the price of keeping them around is too high. I have been around several projects where we foolishly decided that a person's extreme skill made it necessary to accept their abusive behavior, but it turns out that is never really true, and those individuals did permanent damage in each case.

I am not always a fan of codes of conduct; they can be weaponized and used to hurt people for merely having unusual opinions or lifestyles. However, I understand why projects like Rust have adopted them and do not allow people like this to stay around. Unpleasant people are a net negative, and tolerance for them is ultimately corrosive because they destroy morale and drive good people away. There's a book I've seen called [The No Asshole Rule](https://en.wikipedia.org/wiki/The_No_Asshole_Rule) — it's not wrong.

Oh, and yes, I myself don't do much work in OCaml any more because of this issue and similar ones.

Anyway, we should probably just close this. The immediate technical issue isn't going to get solved because Daniel doesn't want to solve it, and the other issue probably isn't appropriate to continue discussing here.

**Comment by dbuenzli** [comment]
You make quite a few unsubstantiated claims in your last message:

1. > Daniel has driven people away from OCaml in the past, and the price of using his code is that more people will be driven away in the future.
2. > Eventually someone has to communicate with him, he's almost always condescending and insulting, 
3. > I have been around several projects where we foolishly decided that a person's extreme skill made it necessary to accept their abusive behavior
4. > The immediate technical issue isn't going to get solved because Daniel doesn't want to solve it,

I will add a [direct reference](https://github.com/dbuenzli/cmdliner/issues/189#issuecomment-2217814399) to the message that apparently warrants me this ad-hominem attack which, it should be added, is in direct violation of the code of conduct of the project, here, on which you are writing this.

These are pretty strong, unsubstantiated, accusations. If you have problems with me I suggest you shoot me an email to discuss this over or, if you rather not, get in touch with the [people responsible](https://github.com/ocaml/code-of-conduct/blob/main/CODE_OF_CONDUCT.md#enforcement) of enforcing the OCaml community code of conduct with incriminating material. The internet is a rumor machine and I can't let this through.

Maybe you don't like my interaction style but I think you will find it hard to find occurrences online where I *insult* people or that I'm being *abusive*. I don't claim to be always perfect in my interactions, far from that. But it's always easy for people that rarely interact and never get into the meat of discussions to judge others that have thousands of online interactions per year across dozens of projects and a life and circumstances which are abstracted away by the systems we interact on.

Regarding 4. the last provably unsubstantiated claim, of course I'd be open to find a solution but 1) on the bare surface I don't think there is one 2) I'm not going to research it. 

If it were not for the unsufferrable rumors and dirt that you are trying to spread on me I'd find it a bit hilarious that you claim it's not possible to work with me when, as can be seen in the aforelinked discussion, all you do is complain, write comments behind my back, and do not even try to offer any hint of a technical resolution. 

I hope that this will be enough to convince future people reading this discussion that maybe the problem has more to do with you, Perry Metzger, than me.

**Comment by pmetzger** [comment]
I already directly linked the issue above. No need to appear here to link to the issue. Also, no need to tell me what a terrible person you think I am for the eightieth time, it's not like you haven't said so over and over again.

Anyway, don't worry, Daniel. I mostly use other languages now. I decided that your long standing policy of being "direct" about your opinions (along with that of a couple of other people) was one of a number of good reasons to move on. I got into this because I still maintain the OCaml packages in MacPorts and had to test one of them and noticed a problem, but I should not have tried to get the problem fixed once I was told it was in one of your packages. Sorry for bothering you.

**Comment by dbuenzli** [comment]
> No need to appear here to link to the issue.

I'm not appearing here. I'm following the project. And I'm not here to link to the issue I'm here to clear up my name of the unsubstantiated claims and dirt you are putting me. One more being:

5. > Also, no need to tell me what a terrible person you think I am for the eightieth time, it's not like you haven't said so over and over again.

I'm not sure exactly where you get this from. I find it highly unprobable that I wrote that you are a terrible person. I critique ideas and code not people (and I hope with the years in more sensitive ways that I may have done in the past). And by the way with respect to what you linked to, if there's something I'm pretty sure I never do or did is "target people who are less powerful".

Again, my email is open for discussion if you wish to. It seems you got hurt by something at some point and I'm willing to discuss it with you.

**Comment by pmetzger** [comment]
The fact that you can't remember previous interactions in which you were, shall we say, less than polite is unsurprising; it appears to be so routine that remembering single individuals you've been unpleasant to is probably hard for you. If you've improved in this regard in recent years, it was hard to detect in your reaction.

Regardless, I don't see the point in continuing this. You do not intend to fix the issue and I doubt there is appetite to pressure you to do otherwise. As for the wider issue, OCaml may well remain a beautiful language with few users while other, technically inferior solutions are vastly more popular, primarily because the other communities are nicer to their users as a matter of culture. Note that the overwhelming majority of OCaml hackers are wonderful people; the problem is with a small minority, but a few bad apples can destroy a whole barrel, and the local culture is to tolerate that minority.

I have been especially impressed with the Rust community, where significant technical requests I've made were discussed in a friendly way and addressed quickly even though I was unknown to almost everyone involved in the conversations. Part of the reason they have been so successful is that they not only make an explicit point of being nice, but also do not tolerate people who aren't. When someone reports an issue, they ask themselves how they could make the user's life easier rather than how they can demonstrate that they're smarter and more technically accomplished than a poor fool daring to mention a problem. The resulting difference in adoption rates is striking.

The moral of the story, in my opinion: a lack of civility is its own punishment.

**Comment by dbuenzli** [comment]
> The fact that you can't remember previous interactions in which you were, shall we say, less than polite is unsurprising; it appears to be so routine that remembering single individuals you've been unpleasant to is probably hard for you. 

The lack of references for your claims is rather astonishing. But yes I have thousands of interactions every year with dozens of different people, sorry for not necessarily remembering those that specifically involved you a few years ago.

I offered to discuss this with you. It seems you are not willing to but rather keep on insulting me. Your choice.

> If you've improved in this regard in recent years, it was hard to detect in your reaction.

Well let's be clear. I see no reason to be nice to someone that writes this kind of [comment](https://github.com/ocaml/opam/issues/6076#issuecomment-2217839106) behind my back. Before claiming people are not being nice to you perhaps question your own interaction style.

> You do not intend to fix the issue and I doubt there is appetite to pressure you to do otherwise.

Please stop making stuff up. You can repeat that as much as you want it's not going to be true. I already said what the steps were here: come up with a reasonable proposal and I'm willing to consider it.

**Comment by pmetzger** [comment]
> Regarding changing the encoding depending on which LANG, LC_TYPE or whatever LOCALE you have, I'm afraid we are not going to do that because it's 2024 and trying to transcode UTF-8 to whatever crazy encoding you are allowed to put in these variables is not going to happen, if only possible. It's time for US-ASCII to go.

> Well I wouldn't like to disappoint @pmetzger.
> Fix your systems.

**Comment by dbuenzli** [comment]
Not sure what point you are trying to make. Apparently it seems you have a solution to embed UTF-8 text into US-ASCII text. I'm sure many people will be extremely happy to know about your solutions. 

So I suggest you do the following: write a commit message in `git` with international text, then do a `LANG=C git log` and please go annoy the people there for a fix. I will happily copy whichever solution they come up with if it's possible to implement it with the bare stdlib.

Regarding the rather dry message and early closure. It is only to respond to your uncivil behaviour, which if you were not selectively quoting is suggested in the [closure message](https://github.com/dbuenzli/cmdliner/issues/189#issuecomment-2217854328).

Btw. more generally I'm a bit surprised by the lack of moderation by the opam maintainers on this issue. Should I gather that it is ok to insult, spread rumors and violent unsubstantiated claims on members of the OCaml community on this project ?

**Comment by dra27** [comment]
> Btw. more generally I'm a bit surprised by the lack of moderation by the opam maintainers on this issue. Should I gather that it is ok to insult, spread rumors and violent unsubstantiated claims on members of the OCaml community on this project ?

To be honest, we'd hoped it would fizzle out yesterday, but apparently that was a vain hope. It's not incumbent on maintainers to leap in the second (or day) there's a disagreement, especially between two, if you don't mind, community old-timers.

This looks bad and it's no way constructive on this issue tracker - please either actually continue it somewhere else, or preferably just stop. The [OCaml Code of Conduct committee](mailto:coc-help@ocaml.org) exists if either of you wishes to take this further, but I propose locking this conversation and hiding the comments after @kit-ty-kate's on 9 July.
