### ISSUE TITLE
opam switch list-available should only display packages that aren't flagged with avoid-version/deprecated

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#6089]
https://discuss.ocaml.org/t/error-on-opam-install-utop-fedora/14948/6

I think that command could be improved by only returning the list of packages without those flags by default and adding a `--all` argument to get the previous behaviour

**Comment by dra27** [comment]
For the UI (as in `opam switch list-available` being used at the console by the user, rather than for a script) we'll want some kind of indication that there _are_ avoid-version packages which aren't listed. A little like the warning on `opam upgrade` when some upgrades are unavailable.
