### ISSUE TITLE
Opam Windows Beta installer: error: cannot load shared library dllunix

### ISSUE THREAD

**Issue by ManasJayanth** [ocaml/opam#6095]
I tried `winget install opam` today and got the following error in a new window

```
Fatal error: cannot load shared library dllunix
```

Winget logs:
```
Found opam [Diskuv.opam] Version 2.2.0-beta3
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Packages
      Microsoft.VCRedist.2015+.x64
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 2
```

**Comment by dra27** [comment]
This I expect will be mainly for @JonahBeckford, but did you have any other OCaml installations before running `winget install opam`? In particular, is ocamlrun already in PATH (`where ocamlrun`) and are either `OCAMLLIB` or `CAML_LD_LIBRARY_PATH` set in the environment?

**Comment by ManasJayanth** [comment]
No globally available `ocamlopt/ocamlc....`. No `$env:OCAMLLIB` and `$env:CAML_LD_LIBRARY_PATH` set either.

Happy to provide any more information. Happy look what's going on underneath too.

**Comment by jonahbeckford** [comment]
There is at least one side issue ... `2.2.0-beta3` is seen as the latest, not `2.2.0`. Tracked in https://github.com/ocaml/opam/issues/6096

Can you do:

```sh
winget install opam --version 2.2.0 --override "-v -v"
```

and paste the output?

**Comment by ManasJayanth** [comment]
That worked

```
Found opam [Diskuv.opam] Version 2.2.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Packages
      Microsoft.VCRedist.2015+.x64
(1/1) Found Microsoft Visual C++ 2015-2022 Redistributable (x64) [Microsoft.VCRedist.2015+.x64] Version 14.40.33810.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.visualstudio.microsoft.com/download/pr/1754ea58-11a6-44ab-a262-696e194ce543/3642E3F95D50CC193E4B5A0B0FFBF7FE2C08801517758B4C8AEB7105A091208A/VC_redist.x64.exe
  ██████████████████████████████  24.2 MB / 24.2 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Downloading https://github.com/diskuv/dkml-installer-opam/releases/download/2.2.0/unsigned-opam-windows_x86_64-i-2.2.0.exe
  ██████████████████████████████  65.0 MB / 65.0 MB
Successfully verified installer hash
Starting package install...
Successfully installed
Notes: See https://opam.ocaml.org/blog for the latest news on how to use opam.
```

**Comment by ManasJayanth** [comment]
Side note: it got installed in `~/AppData\Local\Programs\opam\bin\opam.exe` I was expecting it to be present in WinGet Links, but thats okay.

This issue can be closed. Feel free to re-open if want to use it to track something however.

**Comment by jonahbeckford** [comment]
@ManasJayanth @dra27  The WinGet Links is for portable executables ... I think we could package up opam.exe like that. https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.6.0/installer.md. When I first got familiar with Winget (version 2) it didn't offer portable executables.

Basically, we don't need an installer so it is much simpler. I think it is just a zip file containing opam.exe, opam-putenv.exe and opam-install.exe.

@ManasJayanth Do you have experience with them? And is that something you'd want to do?

**Comment by ManasJayanth** [comment]
WinGet manifests for portable aren't hard to write from my experience. Where can I find the opam binaries in the zip file?

**Comment by ManasJayanth** [comment]
I only see the main opam binary here: https://github.com/ocaml/opam/releases/tag/2.2.0

Where can I find `opam-putenv.exe` and `opam-install.exe`?

**Comment by ManasJayanth** [comment]
This was tested locally: https://github.com/DiningPhilosophersCo/winget-pkgs/blob/prometheansacrifice%2Fportable-opam/manifests/d/Diskuv/opam/2.2.0/Diskuv.opam.installer.yaml#L1

**Comment by kit-ty-kate** [comment]
> I only see the main opam binary here: https://github.com/ocaml/opam/releases/tag/2.2.0
> 
> Where can I find `opam-putenv.exe` and `opam-install.exe`?

None are necessary for the typical opam usage. opam-putenv is only for (rare) cases where you have x86 opam running in x64 a parent process (or the inverse) on Windows, and opam-install is never used internally and is a separate tool when you want to install `.install` files manually without opam.

For these reasons, we currently don't distribute them with opam on any platforms and if you really want them you'd have to compile them individually.

**Comment by ManasJayanth** [comment]
Then, I guess, I can start upstreaming my patch. Rasing a PR

**Comment by ManasJayanth** [comment]
https://github.com/microsoft/winget-pkgs/pull/163593#issuecomment-2236257488

**Comment by jonahbeckford** [comment]
@ManasJayanth Can you put yours with a different namespace ... ie. `OCaml.opam`? The uninstallation will be a pain if we mix two very different installers in the same winget namespace at the same version.

I'd be surprised if the winget maintainers let you do that, but they may let it go through accidentally.

My thought was to use the portable installer for the next version (or at least bump up the patch version number).

**Comment by ManasJayanth** [comment]
@jonahbeckford The reviewer is also asking us to remove the package from Diskuv publisher/namespace. Is that okay with you?

**Comment by ManasJayanth** [comment]
On it!

- prometheansacrifice
