### ISSUE TITLE
How to change GitHub repo for publishing?

### ISSUE THREAD

**Issue by ip2whois** [ocaml/opam#6099]
When I tried to run `opam publish` on a server that have previously published to another GitHub repo, I get the below error.

[ERROR] Uncaught exception: "/usr/bin/git push user +HEAD:opam-publish-ip2whois.1.0.0" exited with code 128 "ERROR: Permission to ip2location/opam-repository.git denied to ip2whois."

How can I remove/reset the old repo credentials so I can publish to this new repo?

**Comment by kit-ty-kate** [comment]
NOTE: the correct repository for opam-publish questions/issues is https://github.com/ocaml-opam/opam-publish 

that said, a way to fix this would be to run:
```
rm -r "$(opam var root)/plugins/opam-publish"
```
to reset the opam-publish configuration. That directory contains the github token and the repository (when the name of the remote for your for is `user`). If you know what needs to be changed you can instead separately only modify one of them.

**Comment by ip2whois** [comment]
Thanks!! That worked perfectly!!
