### ISSUE TITLE
`opam install --check`'s output is not consistent

### ISSUE THREAD

**Issue by Khady** [ocaml/opam#6108]
When `opam install --check` detects a missing dependency, its output is half on stdout and half on stderr.

```
$ opam install --check ./foo.opam.locked  2> /dev/null 
junit
$ opam install --check ./foo.opam.locked  1> /dev/null 
Missing dependencies:
```

FTR the output when there's no dep missing is on stderr.

**Comment by kit-ty-kate** [comment]
if it's just that `Missing dependencies:` and the list of packages are on stderr/stdout respectively, i think this is expected. This way the command makes it possible to be piped to the output of another, while also being """human readable"""

**Comment by Khady** [comment]
Ok, makes sense.
