### ISSUE TITLE
failure to fetch git submodules are not errors

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#6131]
https://github.com/ocaml/opam/commit/c030dcbff6aada1c8fa32e868268d4eda676d0c7 (in opam 2.0) added support for git submodules when pulling a source repository.
However currently failures while fetching the submodules are not errors but only displays a warning. I think this should be an error instead, as not stopping early can change the behaviour of building a such a package drastically.

**Comment by hhugo** [comment]
related to https://github.com/ocaml/opam/issues/6021

**Comment by kit-ty-kate** [comment]
good point, although in your case Windows' `MAX_PATH` is the real culprit but indeed failing early would show a better error message for sure
