### ISSUE TITLE
Finding installed OCaml version

### ISSUE THREAD

**Issue by mtelvers** [ocaml/opam#6136]
OCaml-CI determines the installed OCaml version using `opam list` as below:

```
$ docker run --rm -it ocaml/opam:debian-12-ocaml-4.14-flambda@sha256:6cae4d2fb777869903563a65b6b1de4ecf5c2def4f58733560d88e7b744285d2
opam@401311ca18bb:~$ opam --version
2.0.10
opam@401311ca18bb:~$ opam list -s --color=never --base --roots --all-versions ocaml-base-compiler ocaml-variants ocaml-system
ocaml-variants.4.14.2+options
```

This also works as expected in opam 2.1
```
opam@401311ca18bb:~$ sudo ln -f /usr/bin/opam-2.1 /usr/bin/opam
opam@401311ca18bb:~$ opam --version
2.1.6
opam@401311ca18bb:~$ opam list -s --color=never --base --roots --all-versions ocaml-base-compiler ocaml-variants ocaml-system
ocaml-variants.4.14.2+options
```

However, in opam 2.2 there is a warning message and suggested resolutions
```
opam@401311ca18bb:~$ sudo ln -f /usr/bin/opam-2.2 /usr/bin/opam
opam@401311ca18bb:~$ opam --version
2.2.0
opam@401311ca18bb:~$ opam list -s --color=never --base --roots --all-versions ocaml-base-compiler ocaml-variants ocaml-system
opam: --base was removed in version 2.1 of the opam CLI, but version 2.2 has been requested. Use --invariant instead or set OPAMCLI environment variable to 2.0.
```
However, neither resolution produces any output:
```
opam@401311ca18bb:~$ OPAMCLI=2.0 opam list -s --color=never --base --roots --all-versions ocaml-base-compiler ocaml-variants ocaml-system
[WARNING] OPAMCONFIRMLEVEL was ignored because CLI 2.0 was requested and it was introduced in 2.1.
opam@401311ca18bb:~$ opam list -s --color=never --invariant --roots --all-versions ocaml-base-compiler ocaml-variants ocaml-system
```

Furthermore, `opam list -s --color=never --roots --all-versions ocaml` produces no output either.

This only affects the `-flambda` compilers.  Without `-flambda` either of the suggested actions works.

**Comment by rjbou** [comment]
Is there a reason that the request contains, in the same time, base, root, and all versions packages?
If you want to know what is the installed ocaml package and ocaml version in your current switch, you can directly request that:
```
opam@0e026a1be74c:~$ opam list -s --color=never --installed ocaml-base-compiler ocaml-variants ocaml-system --column package     
ocaml-variants.4.14.2+options
opam@0e026a1be74c:~$ opam list -s --color=never --installed ocaml --column package
ocaml.4.14.2
```
The `--column package` permits to have the package as output, but it can be another fiels (name, version, etc.)

**Comment by mtelvers** [comment]
> Is there a reason that the request contains, in the same time, base, root, and all versions packages?

I suspect this is left over from the previous incarnations of OCaml-CI.  At the moment, the only thing we expect as the output is `ocaml-variants.4.14.2+options` or similar.  I think your first option will work here.

Many thanks
