### ISSUE TITLE
Git --depth 1 breaks orb/dune

### ISSUE THREAD

**Issue by reynir** [ocaml/opam#6145]
First of all congratulations on releasing opam 2.2! 🥳

In [orb](https://github.com/robur-coop/orb/) we recently updated to the version 2.2 opam libraries in https://github.com/robur-coop/orb/pull/15 and https://github.com/robur-coop/orb/pull/17. It builds successfully, but when we use the new orb to build itself again we observe an error on Debian: https://builds.robur.coop/job/orb/build/955defa7-9ff5-447b-b67b-4e928d80cda4

The error is that `dune subst` produces a version number `da200fd` instead of the expected `0.0.2-25-gda200fd`.

After some investigation with @hannesm we believe it may be due to https://github.com/ocaml/opam/pull/4442 where a shallow git clone is done now. Dune uses git tags to derive the version number, and with a shallow clone these are no longer available.

From our point of view we didn't find a way to force a deep clone.

**Comment by kit-ty-kate** [comment]
I had a go at adding the missing `?full_fetch` however i think this is too big of a change for such a feature we don't use and which would be easy to break in the future.

What about we instead introduce a new `full_fetch` option to `OpamRepositoryConfig` and the associated `OPAMFULLFETCH` environment variable? This way would make the code change much simpler and would also allow users of the opam binary to force this behaviour too if they need to.

**Comment by kit-ty-kate** [comment]
Thinking about this further i think https://github.com/ocaml/opam/pull/4442's use-case was for the opam-repository fetch, for regular packages maybe it would make sense to keep `full_fetch:true` by default as they might depend on some git information

**Comment by kit-ty-kate** [comment]
I've opened https://github.com/ocaml/opam/pull/6146 which implements my last comment
