### ISSUE TITLE
usage on symlink failed

### ISSUE THREAD

**Issue by jmikedupont2** [ocaml/opam#6157]
given  a symlink from /mnt/data1/nix/time/2024/08/12/ocaml  to ~/2024/08/12/ocaml  the install fails.

```
~/.local/bin/opam switch create . --empty
  ./configure --prefix=$(~/.local/bin/opam var prefix)
~/.local/bin/opam  install . --assume-built
```

fails with 
```
Proceed with ∗ 5 installations? [y/n] y
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⬇ retrieved ocaml-config.3  (cached)
[ERROR] The installation of ocaml-variants failed at "make install".

#=== ERROR while installing ocaml-variants.5.3.0+trunk ========================#
# context              2.3.0~alpha~dev | linux/x86_64 |  | pinned(git+file:///mnt/data1/nix/time/2023/12/10/ocaml#trun\
k#744006bfbfa045cc1ca442ff7b52c2650d2abe32)
# path                 /mnt/data1/nix/time/2023/12/10/ocaml
# command              ~/.opam/opam-init/hooks/sandbox.sh install make install
# exit-code            1
# env-file             ~/.opam/log/ocaml-variants-1289489-822ed2.env
# output-file          ~/.opam/log/ocaml-variants-1289489-822ed2.out
### output ###
# bwrap: Can't mkdir parents for /home/mdupont/2024/08/12/ocaml: No such file or directory
```
but 
```  cd /mnt/data1/nix/time/2024/08/12/ocaml
    /home/mdupont/.opam/4.14.0/lib/opam-devel/opam  install . --assume-built
  ```
works

**Comment by kit-ty-kate** [comment]
Something's weird with the output. On one hand you have:
```
pinned(git+file:///mnt/data1/nix/time/2023/12/10/ocaml[...])
````
and on the other you have 
```
# bwrap: Can't mkdir parents for /home/mdupont/2024/08/12/ocaml: No such file or directory
```
`2023/12/10` vs `2024/08/12` whereas the source and destination directories should have the same suffix.
Are there other symlinks at play? Given it only fails during install i'm gonna guess `/home/mdupont/2024/08/12/ocaml` is your current `OPAMROOT` or something. If so is it also a symlink?
If not, could you provide more information? e.g. `opam config report`, your environment variables, …

**Comment by jmikedupont2** [comment]
Yeah I'm using Nick's but that's not an issue right now I mean I could
remove it but it's definitely something that occurs when it's being run in
a Sim link directory I can try and create a another test case but I can
tell you for a fact that I fixed it by just changing to the absolute
directory in getting rid of the linked directory

**Comment by kit-ty-kate** [comment]
cc @RyanGibb in case you have a guess as to what's happening

**Comment by jmikedupont2** [comment]
I will try and create a test case that's easy to reproduce maybe using
docker

**Comment by RyanGibb** [comment]
> cc @RyanGibb in case you have a guess as to what's happening

No idea I'm afraid... Is this path something to do with https://nixos.org/ `/mnt/data1/nix/time/2023/12/10` @jmikedupont2? A reproducible test case without Nix sounds like it would be quite useful.
