### ISSUE TITLE
Suggestion for command hints

### ISSUE THREAD

**Issue by ttamttam** [ocaml/opam#6158]
I’d suggest to always output command hints on one single separate line.

It would make it a lot easier to copy paste if needed.

By instance

```
Run (& opam env --switch=default) -split '\r?\n' | ForEach-Object { Invoke-Expression $_ } to update the current shell environment
```

Would become 

```
To update the current shelll environment, run
    (& opam env --switch=default) -split '\r?\n' | ForEach-Object { Invoke-Expression $_ }
```

Best regards

**Comment by kit-ty-kate** [comment]
I've opened https://github.com/ocaml/opam/pull/6159 with a slight difference explained in the description. What do you think?

**Comment by ttamttam** [comment]
Closing. See #6159
