### ISSUE TITLE
Had to add mingw64-x86_64-gcc-g++ cygwin package

### ISSUE THREAD

**Issue by ttamttam** [ocaml/opam#6180]
Installing a private pinned package on windows (opam 2.2.1) with something like this:

```
 (foreign_stubs
  (language cxx)
  ...
  )
```

failed with : `x86_64-w64-mingw32-gcc: fatal error: cannot execute 'cc1plus': spawn: No such file or directory`.

After I added `mingw64-x86_64-gcc-g++` package, it worked.

Best regards

**Comment by ttamttam** [comment]
Oh! Maybe adding a dependency to conf-g++ in my package would be enough to solve this?

**Comment by dra27** [comment]
In order to rely on external commands, you do need a dependency on the appropriate conf- package which is indeed conf-g++ in this case

**Comment by ttamttam** [comment]
Thanks for answering: I actually checked that it worked and forgot to close this ticket.
