### ISSUE TITLE
how to tell opam at init to use a different ~/.opam directory [question]

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#6250]
Hello,

Is it possible to say something like:
```bash
opam init --dot-opam-dir=/tmp/this_directory
```
i.e. force opam to use an explicitly given directory to
store the dot opam dir?

Thanks,
F.

**Comment by kit-ty-kate** [comment]
yes, using `--root` or the `OPAMROOT` environment variable

**Comment by UnixJunkie** [comment]
thanks a lot Kate!
