### ISSUE TITLE
opam init cannot succeed

### ISSUE THREAD

**Issue by Tan8520** [ocaml/opam#6254]
Hello, 
I'm trying to run opam init (I believe it is my first time trying to do so), and have ran into this issue. I have tried to install all the packages required with cygwin, but the issue still persists and instead became a "could not update repository "default"".
I really haven't found any issue of the sort on the internet with the exit code 35 as shown in the error message.
I would appreciated any help.
```
PS C:\Users\dvtha> opam config report
# opam config report
# opam-version         2.2.1
# self-upgrade         no
[ERROR] Opam has not been initialised, please run `opam init'
# read-state           OpamStd.OpamSys.Exit(50)
PS C:\Users\user> opam init
No configuration file found, using built-in defaults.

<><> Windows Developer Mode <><><><><><><><><><><><><><><><><><><><><><><><>  🐫
opam does not require Developer Mode to be enabled on Windows, but it is
recommended, in particular because it enables support for symlinks without
requiring opam to be run elevated (which we do not recommend doing).

More information on enabling Developer Mode may be obtained from
https://learn.microsoft.com/en-gb/windows/apps/get-started/enable-your-device-for-development

<><> Unix support infrastructure ><><><><><><><><><><><><><><><><><><><><><>  🐫

opam and the OCaml ecosystem in general require various Unix tools in order to operate correctly. At present, this requires the installation of Cygwin to provide these tools.

How should opam obtain Unix tools?
> 1. Automatically create an internal Cygwin installation that will be managed by opam (recommended)
  2. Use Cygwin installation found in C:\cygwin64
  3. Use MSYS2 installation found in C:\msys64
  4. Use another existing Cygwin/MSYS2 installation
  5. Abort initialisation

[1/2/3/4/5] 1
Fatal error:
OpamDownload.Download_fail(_, "curl failed: \"C:\\\\Windows\\\\system32\\\\curl.exe --write-out %{http_code}\\\\n --retry 3 --retry-delay 2 --user-agent opam/2.2.1 -L -o C:\\\\Users\\\\dvtha\\\\AppData\\\\Local\\\\Temp\\\\opam-27416-402329\\\\sha512.sum.part -- https://cygwin.com/sha512.sum\" exited with code 35")
PS C:\Users\user> opam init
No configuration file found, using built-in defaults.

<><> Windows Developer Mode <><><><><><><><><><><><><><><><><><><><><><><><>  🐫
opam does not require Developer Mode to be enabled on Windows, but it is
recommended, in particular because it enables support for symlinks without
requiring opam to be run elevated (which we do not recommend doing).

More information on enabling Developer Mode may be obtained from
https://learn.microsoft.com/en-gb/windows/apps/get-started/enable-your-device-for-development

<><> Unix support infrastructure ><><><><><><><><><><><><><><><><><><><><><>  🐫

opam and the OCaml ecosystem in general require various Unix tools in order to operate correctly. At present, this requires the installation of Cygwin to provide these tools.

How should opam obtain Unix tools?
> 1. Automatically create an internal Cygwin installation that will be managed by opam (recommended)
  2. Use Cygwin installation found in C:\cygwin64
  3. Use MSYS2 installation found in C:\msys64
  4. Use another existing Cygwin/MSYS2 installation
  5. Abort initialisation

[1/2/3/4/5] 2
Checking for available remotes: rsync and local, git.
  - you won't be able to use mercurial repositories unless you install the hg command on your system.
  - you won't be able to use darcs repositories unless you install the darcs command on your system.


<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><>  🐫
[ERROR] Could not update repository "default": OpamDownload.Download_fail(_, "curl failed:
        \"C:\\\\Windows\\\\system32\\\\curl.exe --write-out %{http_code}\\\\n --retry 3 --retry-delay 2 --user-agent
        opam/2.2.1 -L -o C:\\\\Users\\\\dvtha\\\\AppData\\\\Local\\\\Temp\\\\opam-29228-1c7dac\\\\index.tar.gz.part --
        https://opam.ocaml.org/index.tar.gz\" exited with code 35")
[ERROR] Initial download of repository failed.
PS C:\Users\user> opam init
No configuration file found, using built-in defaults.

<><> Windows Developer Mode <><><><><><><><><><><><><><><><><><><><><><><><>  🐫
opam does not require Developer Mode to be enabled on Windows, but it is
recommended, in particular because it enables support for symlinks without
requiring opam to be run elevated (which we do not recommend doing).

More information on enabling Developer Mode may be obtained from
https://learn.microsoft.com/en-gb/windows/apps/get-started/enable-your-device-for-development

<><> Unix support infrastructure ><><><><><><><><><><><><><><><><><><><><><>  🐫

opam and the OCaml ecosystem in general require various Unix tools in order to operate correctly. At present, this requires the installation of Cygwin to provide these tools.

How should opam obtain Unix tools?
> 1. Automatically create an internal Cygwin installation that will be managed by opam (recommended)
  2. Use Cygwin installation found in C:\cygwin64
  3. Use MSYS2 installation found in C:\msys64
  4. Use another existing Cygwin/MSYS2 installation
  5. Abort initialisation

[1/2/3/4/5] 3

The following system packages will first need to be installed:
    diffutils make patch rsync unzip

<><> Handling external dependencies <><><><><><><><><><><><><><><><><><><><>  🐫

opam believes some required external dependencies are missing. opam can:
> 1. Run C:\msys64\usr\bin\pacman.exe to install them (may need root/sudo access)
  2. Display the recommended C:\msys64\usr\bin\pacman.exe command and wait while you run it manually (e.g. in another
     terminal)
  3. Continue anyway, and, upon success, permanently register that this external dependency is present, but not
     detectable
  4. Abort the installation

[1/2/3/4] 4

[NOTE] You can retry with '--assume-depexts' to skip this check, or run 'opam option depext=false' to permanently
       disable handling of system packages.
```

**Comment by dbuenzli** [comment]
Curl exits with code 35 which is:

```
  35     SSL connect error. The SSL handshaking failed.
```

So it's likely a certificate problem with your curl install.

**Comment by Tan8520** [comment]
> Curl exits with code 35 which is:
> 
> ```
>   35     SSL connect error. The SSL handshaking failed.
> ```
> 
> So it's likely a certificate problem with your curl install.

I've tried to dabble with the curl path and now have gotten this error : 
OpamDownload.Download_fail(_, "curl failed: \"C:\\\\Windows\\\\system32\\\\curl.exe --write-out %{http_code}\\\\n --retry 3 --retry-delay 2 --user-agent opam/2.2.1 -L -o C:\\\\Users\\\\dvtha\\\\AppData\\\\Local\\\\Temp\\\\opam-27928-5f5e7a\\\\sha512.sum.part -- https://cygwin.com/sha512.sum\" exited with code 60")
I'm really lost here I would appreciate very much if I was shown a detailed run down on how to fix this curl problem. 
Thank you in advance.

**Comment by kit-ty-kate** [comment]
Certificate problems could come from an outdated Windows installation. Is your Windows installation up-to-date?
*Although i've tried an unupdated 22H2 just last week and it worked just fine, so unless you're really outdated it's probably not that.*

Are you able to access https://cygwin.com in a regular web browser?

**Comment by Tan8520** [comment]
@kit-ty-kate Thank you for your answer. I've ended up abandoning and installing opam in WSL and things ended up working fine. I have an updated Windows 11 and have no problem accessing cygwin so it shouldn't be that.

**Comment by rocky** [comment]
I just encountered the same problem. What we seem to know is that there is a certification problem with curl. While this could be caused by some sort of "Old version of Windows",  this did not appear to be the case for @Tan8520 and it not my situation either. 

https://curl.se/docs/sslcerts.html suggests options one add to curl, so how do we influence "opam init" adjust how it runs curl? Looking at curl docs I tried setting the environment variable CA_CERT_FILE but that didn't work.  Is th?ere a way to debug steps inside `opam init` on Windows?

**Comment by kit-ty-kate** [comment]
> Is th?ere a way to debug steps inside `opam init` on Windows?

yes, using `opam init -vvv`

> how do we influence "opam init" adjust how it runs curl?

using the `OPAMFETCH` environment variable. You can read up on how to use it via the manpage/`opam --help`

**Comment by rocky** [comment]
For what it's worth I spent way too much time on this. For those who stumble here, you may find it easier to use OCaml via WSL on Windows.  

There seems to be just too much hacky stuff for Windows going on. The curl command that `opam init`  is using (as opposed to what you'd get if you ran it from a command line seems to needs special care for certs, and passing `--insecure` may give you an because of weird paths that may or not be found (possible two many or two few backlash escape characters.)  If you try to build opam from source, you'll be faced with trying to findlib working. There is some sort of finddll that is a replacement on Windows but you are just going down a rabbit hole.
