### ISSUE TITLE
Include RISCV64 build for 2.2.1

### ISSUE THREAD

**Issue by mtelvers** [ocaml/opam#6287]
It would be excellent if a precompiled binary was available for 2.2.1 (current release) for riscv64.

The documentation says that there is a riscv64 binary available. [see here](https://opam.ocaml.org/doc/Install.html)

I can see that one will be available in the `2.3.0` series as it is already available in the release candidate.

Thank you.

**Comment by rjbou** [comment]
When we add a new binary target, it is only available for the ongoing release and future ones. We should add a note about that in the documentation. 
We'll see if we can provide a riscv64 binary for 2.2.1, and more generally to provide the new binary target for last stable releases when they are added.

**Comment by kit-ty-kate** [comment]
This was fixed by https://github.com/ocaml/opam/pull/6293 with the release of 2.3.0
