### ISSUE TITLE
UI: since using 2.2.1 (likely 2.2), the default answer to interactive questions is barely visible

### ISSUE THREAD

**Issue by hannesm** [ocaml/opam#6288]
With opam 2.1, for any question that opam asked, there was a default answer indicated by an uppercase character `Do you want to continue with installation [Y/n]`.

Now, using opam 2.2, I can barely see what the default is --- yes, it is underlined and bold... but that's at least in my terminal barely visible:

![opam-2 2-default-option](https://github.com/user-attachments/assets/396cc154-d4d9-4030-8f35-897553ba391d)

**Comment by dbuenzli** [comment]
FWIW I also almost reported an issue about that. Having the default uppercased in such kind of interactive dialogue seems quite "standard" to me.

**Comment by rjbou** [comment]
This change was introduced in 2.2.0alpha, with the addition of a menu (#5053).
