### ISSUE TITLE
What is the option to specify an http/https proxy in the ~/.opam/config file ?

### ISSUE THREAD

**Issue by sebma** [ocaml/opam#6325]
>   If your issue concerns a package not building, please report to
>   https://github.com/ocaml/opam-repository/issues or to the package maintainer
>   unless you are confident it is an issue in the opam tool itself.
>   If your issue concerns failures with the opam.ocaml.org website, please report to
>   https://github.com/ocaml/infrastructure/issues

Hi, I don't want export http_proxy and https_proxy variables because this would impact all the programs using cURL.

What is the option to specify an http/https proxy in the ~/.opam/config file ?

Here is my configuration :
```
$ opam config report
# OPAM config report
# opam-version    1.2.2
# self-upgrade    no
# os              linux
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            4
# repositories    1 (http)
# pinned          0
# current-switch  system*
# last-update     2024-12-05 08:54
$
```

**Comment by kit-ty-kate** [comment]
Setting
```
OPAMFETCH="curl --proxy your-proxy"
```
will work. It's technically possible to set `download-command` in the config file instead but i wouldn't recommend it as it is much more complicated as the full command has to be used not just a prefix.

However, looking at your current configuration, your version of opam is extremely old (from 10 years ago!), i would recommend first upgrading to a more recent version before doing anything else: https://opam.ocaml.org/doc/Install.html

**Comment by sebma** [comment]
@kit-ty-kate Thank you answer, on last question : this `OPAMFETCH` variable should be defined in my `~/.profile` right ?

**Comment by sebma** [comment]
@kit-ty-kate Thanks 👍

**Comment by sebma** [comment]
BTW : I was able to update upto v2.0.4 thanks to this [opam launchpad repo for Xenial](https://launchpad.net/~avsm/+archive/ubuntu/ppa?field.series_filter=xenial) : 
```shell
$ apt policy opam
opam:
  Installed: 2.0.4-0ppa1~xenial
  Candidate: 2.0.4-0ppa1~xenial
  Version table:
 *** 2.0.4-0ppa1~xenial 500
        500 http://ppa.launchpad.net/avsm/ppa/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     1.2.2-4 500
        500 http://fr.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
$
```

**Comment by kit-ty-kate** [comment]
note that 2.0 is also pretty old (6 years old) so i would encourage you to rather use our install script if you can:
```
bash -c "sh <(curl -fsSL https://opam.ocaml.org/install.sh)"
```
`opam update` will alert you if your opam binary is out-of-date automatically
