### ISSUE TITLE
Fatal: `"waitpid" failed: No child processes`

### ISSUE THREAD

**Issue by dsheets** [ocaml/opam#646]
I occasionally observe opam failing with this error in ocamlot build runs. I speculate that it is the result of some kind of race between waiting and forking in opam's parallel job implementation but I don't really know and would rather someone familar with the worker pool implementation analyze it. This is issue ocamllabs/ocamlot#8

```
==== ERROR [while installing tplib.1.3] ====
Internal error:
  # opam-version    1.0.1 (9099a057e96ce2aa9e058645906f8aee8dcc520d)
# os              linux
/usr/local/bin/opam: "waitpid" failed: No child processes
Backtrace:
  Raised at file "src/client/opamAction.ml", line 548, characters 10-11
  Called from file "src/core/opamParallel.ml", line 271, characters 16-23
```

**Comment by AXACustomer** [comment]
Issue is not fixed yet. Please help

**Comment by AltGr** [comment]
@AXACustomer, this issue is 4 years old and hasn't happened since. If you do have a similar one, please give some more detail (OS, version, etc. — at least the results of `opam config report`).
opam 1.2.2 had a completely refactored parallel job processing engine and doesn't use `fork` anymore, so even if you got similar symptoms, yours might be a different issue.

**Comment by girishshetye14** [comment]
Cloning into SDK
remote: Counting objects: 23385, done.
remote: Compressing objects: 100% (13809/13809), done.
remote: Total 23385 (delta 13406), reused 16893 (delta 8747)
Receiving objects: 100% (23385/23385), 176.16 MiB | 2.07 MiB/s, done.
Resolving deltas: 100% (13406/13406), done.
error: waitpid for fetch-pack failed: No child processes

I am getting this error on git 2.x version.
Unable to resolve. 
Please guide to overcome this.

**Comment by AltGr** [comment]
@girishshetye14 your report looks like a git error, without any way to link it to opam. Please elaborate.

**Comment by girishshetye14** [comment]
Hi AltGr,
I was searching about my issue and found somewhat relevant to it although it is git issue.
So I thought getting some guideline from someone.
Later after your comment I realize that it is git error, so by mistake and arg of getting for help I posted.
Sorry for wrong comment.
