### ISSUE TITLE
Display package CHANGES file

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#733]
Extracted from #466 

Targeted for `outgoing` as it is not clear to me how this can be done properly.

**Comment by dbuenzli** [comment]
> To avoid overloading opam this could also be provided via another tool like opam-doc (well that name is already taken).

[`odig`](http://erratique.ch/software/odig) basically does this. It works only with text files but allows to access them in your terminal or in our browser.

**Comment by dbuenzli** [comment]
Here again following https://github.com/ocaml/opam/issues/1900#issuecomment-310091848 I think this can be closed.
