### ISSUE TITLE
opam: should check validity of downloaded archives

### ISSUE THREAD

**Issue by edwintorok** [ocaml/opam#736]
I am using the git version of opam: 1.0.0-492-ga40ebd6.

It'd be nice if opam was more robust on disk I/O:
  * verify checksum of downloaded archive before using it (or at least its size). If wrong download again: the user doesn't have to manually rm files after a failure.
  * have a command akin to debsums that would verify the checksums of installed files to detect corruption. These sums would be computed locally and stored in an fsync()-ed file
  * have the ability to fsync() or sync() during installation. I think that at least after one package gets installed it should be synced, otherwise it might get lost but opam would think it is installed. Calling fsync on each file would be an overkill (not to mention a performance nightmare, as for example ext4 is very slow on repeated fsyncs).

Now for the actual bug: opam got interrupted by a reboot while installing some packages.
Tried to continue the installation, but got an error about a truncated file, the file was 0 bytes:
<pre>
-rw-r--r-- 1 edwin edwin 0 Aug  8 23:24 /home/edwin/.opam/archives/cohttp.0.9.10+opam.tar.gz
</pre>

I have worked this about by manually deleting the 0-sized archive.
Looks like a previously installed package got corrupted though:
<pre>
Error: Corrupted compiled interface
/home/edwin/.opam/4.01.0dev+trunk/lib/async/async.cmi
Command exited with code 2.
</pre>

So I had to opam remove the corrupt package, and install it again.

The error:
<pre>
The following actions will be performed:
 - install cohttp.0.9.10
1 to install | 0 to reinstall | 0 to upgrade | 0 to downgrade | 0 to remove

=-=-= Installing cohttp.0.9.10 =-=-=
The compilation of cohttp.0.9.10 failed.
Removing cohttp.0.9.10.
  ocamlfind remove cohttp

==== ERROR [while installing cohttp.0.9.10] ====
# opam-version    1.1.0 (a40ebd66fa07e2f719ca33614df472e4f4de049c)
# os              linux
# command         tar xfz /home/edwin/.opam/archives/cohttp.0.9.10+opam.tar.gz -C /tmp/opam-5005-dd682e
# path            /home/edwin/HDD/me/language/OCaml/examples
# exit-code       2
# env-file        /home/edwin/.opam/log/log-5005-ccabea.env
# stdout-file     /home/edwin/.opam/log/log-5005-ccabea.out
# stderr-file     /home/edwin/.opam/log/log-5005-ccabea.err
### stderr ###

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

'opam install --yes core core_extended cryptokit core_bench atdgen async yojson textwrap cohttp async_graphics menhir' failed.
</pre>

**Comment by AltGr** [comment]
There has been much work done on verifying (and signing) archives since this issue, so closing as obsolete and superseded by newer, more specific feature discussions.
