### ISSUE TITLE
Can't install lwt on opam 1.0

### ISSUE THREAD

**Issue by sergi** [ocaml/opam#758]
It complains about  package `wikidoc` not found. The complete output:

```
The following actions will be performed:
 - install lwt.2.4.3
1 to install | 0 to reinstall | 0 to upgrade | 0 to downgrade | 0 to remove

=-=-= Installing lwt.2.4.3 =-=-=
The archive for lwt.2.4.3 is in the local cache.
Extracting /Users/sergi/.opam/archives/lwt.2.4.3+opam.tar.gz.
Building lwt.2.4.3:
  patch -p1 -i 4.01cloexec.diff
  ./configure --disable-libev --enable-react --disable-ssl --enable-unix --enable-extra --enable-preemptive --disable-glib --disable-text
  make build
  make install
The compilation of lwt.2.4.3 failed.
Uninstalling lwt.2.4.3:
  ocamlfind remove lwt


==== ERROR [while installing lwt.2.4.3] ====
# opam-version    1.0.0
# os              darwin
# command         make build
# path            /Users/sergi/.opam/4.01.0dev+trunk/build/lwt.2.4.3
# exit-code       2
# env-file        /Users/sergi/.opam/4.01.0dev+trunk/build/lwt.2.4.3/lwt-1872ec.env
# stdout-file     /Users/sergi/.opam/4.01.0dev+trunk/build/lwt.2.4.3/lwt-1872ec.out
# stderr-file     /Users/sergi/.opam/4.01.0dev+trunk/build/lwt.2.4.3/lwt-1872ec.err
### stdout ###
...[truncated]
ocamlfind ocamldep -package unix -package camlp4 -package bigarray -syntax camlp4o -ppopt syntax/pa_optcomp.cmo -modules src/unix/lwt_io.mli > src/unix/lwt_io.mli.depends
ocamlfind ocamldep -package unix -package bigarray -modules src/unix/lwt_bytes.mli > src/unix/lwt_bytes.mli.depends
ocamlfind ocamldep -package unix -package camlp4 -package bigarray -syntax camlp4o -ppopt syntax/pa_optcomp.cmo -modules src/unix/lwt_unix.mli > src/unix/lwt_unix.mli.depends
ocamlfind ocamlc -c -g -I src/core -package unix -package camlp4 -package bigarray -syntax camlp4o -ppopt syntax/pa_optcomp.cmo -I src/unix -I src/core -o src/unix/lwt_unix.cmi src/unix/lwt_unix.mli
+ ocamlfind ocamlc -c -g -I src/core -package unix -package camlp4 -package bigarray -syntax camlp4o -ppopt syntax/pa_optcomp.cmo -I src/unix -I src/core -o src/unix/lwt_unix.cmi src/unix/lwt_unix.mli
File "src/unix/lwt_unix.mli", line 301, characters 5-283:
Error: This variant or record definition does not match that of type
         Unix.open_flag
       The field O_CLOEXEC is only present in this definition.
Command exited with code 2.
### stderr ###
ocamlfind: Package `wikidoc' not found
E: Failure("Command ''/Users/sergi/.opam/4.01.0dev+trunk/bin/ocamlbuild' syntax/optcomp.cma syntax/optcomp.cmxa syntax/optcomp.a syntax/optcomp.cmxs src/core/lwt.cma src/core/lwt.cmxa src/core/lwt.a src/core/lwt.cmxs src/unix/liblwt-unix_stubs.a src/unix/dlllwt-unix_stubs.so src/unix/lwt-unix.cma src/unix/lwt-unix.cmxa src/unix/lwt-unix.a src/unix/lwt-unix.cmxs src/simple_top/lwt-simple-top.cma sr...[truncated]
make: *** [build] Error 1

'opam install lwt' failed.
```

**Comment by makofka** [comment]
not fixed again with Ocaml 4.02.2

**Comment by samoht** [comment]
which version of lwt?

**Comment by makofka** [comment]
2.5.0 and 2.4.8. I downloaded the tarballs and they don’t build either – so maybe not an opam problem. I’m using Cygwin, ocaml 4.02.2  . Trying to build Elisom.
Dsm

**Comment by makofka** [comment]
Should also mention that I downloaded the wikidoc-master zip and muddled through getting some of that build. May have just messed things up.

**Comment by samoht** [comment]
You should at least give the error messages that you get if you want some help debugging it. But yes, if the archives don't build, it is not a problem of opam: https://github.com/ocsigen/lwt/issues would maybe be a better place to get help.

**Comment by makofka** [comment]
Thanks. I’ll continue on git/lwt. I may go back and uninstall wikidocs so I can get those errors back. Also, is it possible that things that installed to lib as opposed to lib/ocaml don’t get their shared lib’s propagated to stublibs? I had to move the netsys dll* files manually.

**Comment by edalorzo** [comment]
In running Mac OS Yosemite
Did a fresh installation of OCaml using Homebrew (i.e. ```brew install ocaml```)
REPL shows OCaml version 4.02.1
OPAM version 1.2.2

I simply run a: ```opam install lwt```

And I get a LWT installation problem:

-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of lwt failed at "./configure --prefix /Users/edalorzo/.opam/system --disable-libev --enable-camlp4 --enable-react --disable-ssl --enable-unix --enable-preemptive --disable-glib --enable-ppx".
Processing  1/1: [lwt: ocamlfind remove]
#=== ERROR while installing lwt.2.5.0 =========================================#
# opam-version 1.2.2
# os           darwin
# command      ./configure --prefix /Users/edalorzo/.opam/system --disable-libev --enable-camlp4 --enable-react --disable-ssl --enable-unix --enable-preemptive --disable-glib --enable-ppx
# path         /Users/edalorzo/.opam/system/build/lwt.2.5.0
# compiler     system (4.02.1)
# exit-code    1
# env-file     /Users/edalorzo/.opam/system/build/lwt.2.5.0/lwt-42084-6d07ae.env
# stdout-file  /Users/edalorzo/.opam/system/build/lwt.2.5.0/lwt-42084-6d07ae.out
# stderr-file  /Users/edalorzo/.opam/system/build/lwt.2.5.0/lwt-42084-6d07ae.err
### stderr ###
# [...]
# W: Field 'pkg_camlp4' is not set: When looking for findlib package camlp4, directory /usr/local/Cellar/objective-caml/4.02.1_2/lib/ocaml/camlp4 return doesn't exist
# W: Field 'pkg_camlp4_quotations_o' is not set: When looking for findlib package camlp4.quotations.o, directory /usr/local/Cellar/objective-caml/4.02.1_2/lib/ocaml/camlp4 return doesn't exist
# W: Field 'pkg_camlp4_extend' is not set: When looking for findlib package camlp4.extend, directory /usr/local/Cellar/objective-caml/4.02.1_2/lib/ocaml/camlp4 return doesn't exist
# W: Failure("When looking for findlib package camlp4, directory /usr/local/Cellar/objective-caml/4.02.1_2/lib/ocaml/camlp4 return doesn't exist")
# W: Failure("When looking for findlib package camlp4, directory /usr/local/Cellar/objective-caml/4.02.1_2/lib/ocaml/camlp4 return doesn't exist")
# W: Failure("When looking for findlib package camlp4.quotations.o, directory /usr/local/Cellar/objective-caml/4.02.1_2/lib/ocaml/camlp4 return doesn't exist")
# E: Cannot find findlib package camlp4
# E: Cannot find findlib package camlp4.extend
# E: Cannot find findlib package camlp4.quotations.o
# E: Failure("3 configuration errors")



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install lwt 2.5.0
