### ISSUE TITLE
install: option to ignore compiler constraints

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#829]
It would be useful to have a debugging command-line option to opam-install to ignore `ocaml-version` constraints, for testing purposes.

**Comment by thranur** [comment]
I tried the suggested lines on OPAM 1.2.2 and none of them work. Has this behavior changed since then?

**Comment by AltGr** [comment]
try setting `OPAMVAR_<varname>` :)
It's documented at the end of the `ENVIRONMENT VARIABLES` section of the manpage (`opam --help`)

**Comment by thranur** [comment]
Thank you very much! It's a bit unfortunate that the underlining introduced by my `man` viewer does not show at all the underscore between `OPAMVAR` and `var` in the phrase `OPAMVAR_var overrides the contents of the variable var ...`, which could lead to a bit of confusion, but a bit of testing will probably lead the user to that conclusion anyway.
