### ISSUE TITLE
Track snapshots of the compiler for finer constraints

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#835]
For dev versions of the compiler, the ABI version is semi-regularly updated to let intermediate snapshots be distinguished.  It would be useful to track this and let it be used in `ocaml-version` constraints to make ongoing trunk testing easier.

See http://anil.recoil.org/2013/09/09/ocamlot-autotriaging.html for a little bit more background on this topic.

**Comment by AltGr** [comment]
From `opam config list`:
```
ocaml-version        4.01.0               # The version of the currently used OCaml compiler
compiler             4.01.0+BER           # The name of the current OCaml compiler (may be more specific than the version, eg: "4.01.0+fp", or "system")
```
Both can be used in the `available:` field
