### ISSUE TITLE
Dropping dependency to Camlp4

### ISSUE THREAD

**Issue by alainfrisch** [ocaml/opam#917]
OPAM currently requires Camlp4.  Apparently, Camlp4 is used only in the 'dose' external dependency, which uses the "**FILE**" macro.  It is sad to bring such a big dependency on Camlp4 for such a small use.  If this is indeed the only use of Camlp4 within OPAM, I'd suggest to get rid of **FILE** (by manually inserting the source file name instead, or using sed) and then drop the dependency on Camlp4 for OPAM.

**Comment by abate** [comment]
the dependency on camlp4 has now been removed in dose. I decided to use cppo as suggested.
