### ISSUE TITLE
Optional dependencies for tests

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam#942]
With ocamlot supporting the execution of tests, I wonder whether a target `deptests` to list dependencies only required to run tests wouldn't be useful.

In the same vein, a variable like `%{ocamlot-test:enable}%` would be nice — or maybe a package `ocamlot-test` providing a library to ease the writing of those tests...

**Comment by samoht** [comment]
I think this is now fixed eg. you can use the `tests` filter

**Comment by Chris00** [comment]
> I think this is now fixed eg. you can use the tests filter

So we can write 
```
  [ "./configure"] {!tests}
  [ "./configure" "--enable-tests"] {tests}
```
Should we avoid the the `build-test` section?

**Comment by samoht** [comment]
Not really, but you could write:

```
build: [ 
  ["./configure" ]
  [make]
]
build-test: [
  ["./configure" "--enable-tests"]
  [make "test"]
```

Which is different from what Daniel was proposing. I'm happy to re-open the issue if you think this needs improvement (it works well for me as it is).

**Comment by dbuenzli** [comment]
I still think that separating test building from running is a good idea.

**Comment by Chris00** [comment]
For me it is OK.  I read quickly and it was not clear whether the `build-test` was going to become obsolete or not.
