### ISSUE TITLE
opam gets confused if the CWD no longer exists

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/opam#969]
feast:~ john$ mkdir foo
feast:~ john$ cd foo
feast:foo john$ rm -r ../foo
feast:foo john$ opam update
Fatal error: exception Sys_error("No such file or directory")

(OS X 10.8.5)

**Comment by kit-ty-kate** [comment]
https://github.com/ocaml/opam/issues/2442 also shows the same issue but is still open

**Comment by dbuenzli** [comment]
The stack trace is a bit different though.
